language-server/src/main/resources/logback.xml

Example
```
22:51:40.144 INFO  s.m.l.Main$ - Starting server in /Users/gabro/buildo/scalameta-language-server/test-workspace
22:51:40.151 INFO  s.m.l.Main$ - Classpath: /Users/gabro/buildo/scalameta-language-server/vscode-extension/coursier
22:51:40.151 DEBUG l.core.MessageReader - Received headers:
Content-Length: 1230
22:51:40.155 DEBUG l.core.Connection - Received {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":11108,"rootPath":"/Users/gabro/buildo/scalameta-language-server/test-workspace","rootUri":"file:///Users/gabro/buildo/scalameta-language-server/test-workspace","capabilities":{"workspace":{"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRe …
```

Configure logback for shorter logs

---

README.md
language-server/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala
language-server/src/main/scala/scala/meta/languageserver/SymbolIndexer.scala

Add hoverProvider support

---

README.md

Alexey has been actively contributing to this project since day 2 both
via discussions in issues and pull requests. Welcome!

Invite Alexey Alekhin to the team!

---

.travis.yml
build.sbt
project/build.properties
project/plugins.sbt

Fixes #28.
* `releaseEarly` works locally
* it _should_ get triggered in CI only on merge commits to `master`
@jvican I would appreciate your feedback

Setup sbt-release-early

---

build.sbt
metaserver/src/main/scala/scala/meta/languageserver/Linter.scala
metaserver/src/main/scala/scalafix/languageserver/ScalafixEnrichments.scala
test-workspace/a/src/main/scala/example/User.scala

There had been an uncaught regression in the uri published by scalafix
with the index refactorings.

Upgrade scalafix

---

metaserver/src/main/scala/scala/meta/languageserver/compiler/CompletionProvider.scala
metaserver/src/test/scala/tests/compiler/CompletionsTest.scala

Still WIP, but opening for a quick feedback

Add kind to completion items

---

metaserver/src/main/scala/scala/meta/languageserver/compiler/CompletionProvider.scala
metaserver/src/test/scala/tests/compiler/CompletionsTest.scala

Sort completion items by relevance

---

metaserver/src/main/scala/scala/meta/languageserver/mtags/MtagsIndexer.scala
metaserver/src/main/scala/scala/meta/languageserver/mtags/ScalaMtags.scala
metaserver/src/test/scala/tests/mtags/BaseMtagsTest.scala
metaserver/src/test/scala/tests/mtags/ScalaMtagsTest.scala

Followup of #74 and related to #72. Only second commit is relevant.

Improve scala mtags

---

BETA.md

The purpose of this PR is to put together a mini-guide for testing the server on arbitrary Scala projects.
The intention is *not* to advertise this too much, but if someone is willing to try and give some early feedback I think it's useful to have a reference guide to get started.

Add instructions for beta testers

---

metaserver/src/main/scala/scala/meta/languageserver/compiler/SignatureHelpProvider.scala

Use _CURSOR_ in signatureHelp

---

languageserver/src/main/scala/langserver/core/LanguageServer.scala
languageserver/src/main/scala/langserver/messages/Commands.scala
languageserver/src/main/scala/langserver/types/types.scala
metaserver/src/main/scala/scala/meta/languageserver/ScalametaEnrichments.scala
metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala
metaserver/src/main/scala/scala/meta/languageserver/search/DefinitionProvider.scala
metaserver/src/main/scala/scala/meta/languageserver/search/ReferencesProvider.scala
metaserver/src/main/scala/scala/meta/languageserver/search/SymbolIndex.scala
metaserver/src/main/scala/scala/meta/languageserver/search/TrieMapSymbolIndexer.scala
metaserver/src/test/scala/tests/search/SymbolIndexTest.scala
test-workspace/src/main/scala/example/User.scala
test-workspace/src/test/scala/example/UserTest.scala

Fixes #70. WIP
This is not ready yet, but all the wiring boilerplate is already in place.

Implementation for textDocument/references

---

metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala
metaserver/src/main/scala/scala/meta/languageserver/providers/CompletionProvider.scala
metaserver/src/main/scala/scala/meta/languageserver/providers/DefinitionProvider.scala
metaserver/src/main/scala/scala/meta/languageserver/providers/HoverProvider.scala
metaserver/src/main/scala/scala/meta/languageserver/providers/ReferencesProvider.scala
metaserver/src/main/scala/scala/meta/languageserver/providers/SignatureHelpProvider.scala
metaserver/src/test/scala/tests/compiler/CompletionsTest.scala
metaserver/src/test/scala/tests/compiler/SignatureHelpTest.scala
metaserver/src/test/scala/tests/hover/HoverTest.scala

See 
* https://github.com/scalameta/language-server/pull/93#discussion_r154569956
* https://github.com/scalameta/language-server/pull/93#discussion_r154802522

Moved all providers to the same package

---

build.sbt
metaserver/src/main/scala/scala/meta/languageserver/Parser.scala
metaserver/src/main/scala/scala/meta/languageserver/Semanticdbs.scala
metaserver/src/main/scala/scalafix/languageserver/ScalafixEnrichments.scala

I tried to track down what is causing the infinite loop in completions but haven't been able to nail down exactly what it is except that downgrading to 2.12.3 seems to fix the issue.

Downgrade to 2.12.3 to avoid infinite loop.

---

.gitignore
BETA.md
project/ScalametaLanguageServerPlugin.scala

I kept everything in the same file to retain the single file copy
installation step in BETA.md.

Add semanticdbEnable command for easier quick installation.

---

metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala

Previously, we ran the presentation compiler on the main scheduler which
defaults to a thread pool with 4 threads. While trying out the plugin
I noticed that the presentation compiler used to crash a lot with
cryptic error messages.
I suspect concurrent access to compiler data structures from semanticdb,
completions and hover caused these crashes. Let's see if this improves
the situation. I tested this change manually by running the plugin
for a small session and didn't see any errors in the logs.

Run presentation compiler from single thread.

---

bin/start-server.sh

This script becomes useful to start the language server using other
editors (e.g. vim).

Add shell script to start the language server

---

vscode-extension/package.json

This is something I forgot to do in #204. I think I also broke scalac diagnostics somewhere in 4eda98aafafbd18d505a78fbdec09afc58da104a...15398a10a92978b2096e501f8c36977849adc782, I'm working on fixing it now and will submit another PR.

Update vscode configuration with separate scalac settings

---

.travis.yml
BETA.md
CONTRIBUTING.md
README.md
metals/src/test/scala/tests/search/SymbolIndexTest.scala
project/MetalsPlugin.scala
roadmap.md

I'm a bit uncomfortable by how many are trying out metals with the
expectation that it's a ready-to-use solution. I hope these changes make
it clearer that the project is not ready or intended for public use yet.

Update readme to set correct expectations.

---

metals/src/main/scala/scala/meta/metals/compiler/CompilerConfig.scala
metals/src/main/scala/scala/meta/metals/compiler/ScalacProvider.scala
project/MetalsPlugin.scala

Report error when scalaVersion is not 2.12

---

.travis.yml

Fixing Travis again

---

.gitignore
.travis.yml
build.sbt

I've sort of blindly followed the instructions here https://github.com/scalacenter/sbt-release-early/wiki/How-to-release-in-Travis-(CI) so if this doesn't work blame @jvican 😆

Add pgp keys for stable releases to Travis

---

BETA.md
CONTRIBUTING.md
docs/installation.md
sbt-metals/src/main/scala/scala/meta/sbt/MetalsPlugin.scala

To merge when we release 0.1.0, but can be already reviewed

Update installation and contributing docs

---

docs/new-editor.md
metals/src/main/scala/scala/meta/metals/MetalsServices.scala
metals/src/main/scala/scala/meta/metals/Models.scala
metals/src/main/scala/scala/meta/metals/Semanticdbs.scala
metals/src/main/scala/scala/meta/metals/Workspace.scala
metals/src/main/scala/scala/meta/metals/compiler/CompilerConfig.scala
metals/src/main/scala/scala/meta/metals/sbtserver/SbtServer.scala
vscode-extension/src/extension.ts

Fixes #253:
* watches `active.json` and reconnect to the server if it appears/changes
* checks sbt versions on manual connection and warns user if the version is too old:

Smart sbt connection

---

CONTRIBUTING.md

Based on my own experience as a first-time user of VSCode and Metals

Expand the troubleshooting advice

---

vscode-extension/package-lock.json
vscode-extension/package.json

Upgrade vscode package to resolve vulnerability report

---

docs/installation-contributors.md

To follow up from questions on Gitter. The requirements are quite limiting in terms of environment. I wish we did better, but I think it's fair to list them upfront instead of everyone finding out the hard way.

Document requirements.

---

metals/src/main/scala/scala/meta/metals/mtags/JavaMtags.scala
metals/src/test/scala/tests/mtags/JavaMtagsTest.scala

Fix for issue #280 
This patch fixes calculation of the symbol range in file in case if symbol was not actually found at given line number.
It is quite rare situation and happens at least for ParserConstants.java. The qdox gives line number 109 for symbol tokenImage which is actually the line at the end of the initializer. For other similar declarations like JPEGImageMetadataFormatResources.imageContents qdox gives correct line number.

Fix issue #280

---

metals/src/main/scala/scala/meta/metals/Semanticdbs.scala
metals/src/main/scala/scala/meta/metals/mtags/Mtags.scala
metals/src/main/scala/scala/meta/metals/search/InMemorySymbolIndex.scala
metals/src/test/scala/tests/search/SymbolIndexTest.scala

This minimal patch fixes most obvious problems with windows paths (backslashes) addressed in the issue #323

Fix issue #323

---

docs/overview.md

Remove unused references in overview.md

---

tests/slow/src/test/scala/tests/SbtSlowSuite.scala

This is less fragile than testing against specific states like
failed/cancelled/...

Assert only against installed status

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Instead of crashing with exception.

Return empty responses for unsupported features

---

vscode-extension/package.json

In preparation for publishing the plugin.

Update VS Code plugin metadata

---

metals/src/main/scala/scala/meta/internal/metals/HtmlBuilder.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsHttpClient.scala

🚲 🏠  <-- this is a bike shed, and so is this PR

Add NES theme 

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Some clients may send the `exit` notification before receiving the
`shutdown` response resulting in the zinc analysis files to not get
persisted (causing the next server to unnecessarily re-compile a lot of
code). This commit is a safeguard to ensure that shutdown always
happens.

Ensure shutdown is always run before exit

---

metals/src/main/scala/scala/meta/internal/metals/MetalsHttpClient.scala

Addressing some concerns from #354 
This is on my 15" screen

Make more stuff fit in viewport

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Register server commands in `initialize` response

---

build.sbt
docs/build-tools/bloop.md
docs/build-tools/sbt.md
docs/editors/atom.md
docs/editors/vscode.md
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
project/plugins.sbt

Minor docs updates and upgrade dependencies

Prepare for v0.3.0 release

---

README.md
docs/build-tools/bloop.md
docs/build-tools/sbt.md
metals-docs/src/main/resources/META-INF/services/mdoc.StringModifier
metals-docs/src/main/scala/docs/CustomizeBloopModifier.scala
metals-docs/src/main/scala/docs/RequirementsModifier.scala

- clarify sbt/bloop docs
- update readme
- update supported scala versions in requirements

Docs cleanup

---

docs/editors/vim.md

I noticed that the two known issues you had referenced here have both been closed. I just removed them, but made sure to still include a link leading to the appropriate places for people to report bugs if they come across them.

Update issues on Vim page

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Fixing stubbed method names

---

docs/editors/new-editor.md
docs/editors/sublime.md
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala

See https://github.com/tomv564/LSP/issues/410 for context.
cc/ @ayoub-benali

Exit the process on shutdown for Sublime Text

---

build.sbt

This was supposed to be part of the 0.3.2 release but I forgot.

Bump bloop version

---

metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
tests/unit/src/test/scala/tests/CreateDirectoriesSuite.scala

Fixes #416 
@olafurpg do you have an idea on how to test this automatically?

Handle sbt pluginsDirectory as symbolic link

---

tests/unit/src/test/scala/tests/CreateDirectoriesSuite.scala

Followup of #417 that adds an extra test more specific to the case reported in #416

Add test to CreateDirectoriesSuite

---

metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
tests/slow/src/test/scala/tests/SbtSlowSuite.scala

Don't attempt build import if sbt version is < 0.13.7

---

metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala

Fix wrong log

---

docs/editors/overview.md

Document the two feature that have been recently merged on master.
Discussed offline: we should probably make the GIFs smaller

Document textDocument/documentSymbol and textDocument/formatting

---

metals/src/main/scala/scala/meta/internal/metals/Classfile.scala
metals/src/main/scala/scala/meta/internal/metals/CompressedPackageIndex.scala
metals/src/main/scala/scala/meta/internal/metals/Compression.scala
metals/src/main/scala/scala/meta/internal/metals/PackageIndex.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticdbDefinition.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
tests/unit/src/test/scala/tests/ClasspathSymbolRegressionSuite.scala

Fixes some errors while testing workspace symbol.

Small fixes to workspace symbol

---

docs/editors/sublime.md
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala

given the new [release](https://github.com/tomv564/LSP/releases/tag/0.8.0) for the LSP plugin, I updated the doc. 
@olafurpg do we need to create a gif for the "import changes" prompt ?

update sublime doc to reflect the changes in the LSP plugin

---

docs/editors/overview.md
metals-bench/readme.md
metals/src/main/scala/scala/meta/internal/metals/Fuzzy.scala
metals/src/main/scala/scala/meta/internal/metals/PackageIndex.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolQuery.scala
tests/unit/src/main/scala/tests/Library.scala
tests/unit/src/test/scala/tests/ClasspathSymbolRegressionSuite.scala
tests/unit/src/test/scala/tests/FuzzySuite.scala
tests/unit/src/test/scala/tests/WorkspaceSymbolSlowSuite.scala

Fuzzy symbol search is starting to look closer to completions.

Several polish improvements to workspace symbols

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

My brain is not trained for null :(
Fixes #516

Handle null fields from lsp4j

---

docs/editors/emacs.md

Update Emacs docs

---

docs/editors/vscode.md
metals-docs/src/main/scala/docs/BootstrapModifier.scala

Document using HTTP proxy from VS Code

---

.travis.yml
NOTICE.md
azure-pipelines.yml
sbt

The Travis CI machines are reliably timing out and I'm unable to
reproduce on my machine or on Appveyor. This is an attempt to migrate
to Azure Pipelines, which hopefully have more powerful machines.

Configure Azure pipeline.

---

mtags/src/main/scala/scala/meta/internal/metals/Fuzzy.scala
mtags/src/main/scala/scala/meta/internal/pc/CompletionFuzzy.scala
mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala/scala/meta/internal/pc/Completions.scala
mtags/src/main/scala/scala/meta/internal/pc/Identifier.scala
test-workspace/src/main/scala/example/User.scala
tests/cross/src/main/scala/tests/BaseCompletionSuite.scala
tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionBacktickSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

This feature conflicts with snippets causing undesirable behavior. See comment in diff for details.
Thank you @jvican for reporting!

Disable `(` as commit character.

---

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala/scala/meta/internal/pc/Completions.scala
mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala/scala/meta/internal/pc/SignatureHelpProvider.scala
test-workspace/src/main/scala/example/User.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala

This PR fixes several issues towards #542. Completions for type members will be implemented separately.

Improve string interpolator completions

---

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala/scala/meta/internal/pc/Completions.scala
mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala
test-workspace/src/main/scala/example/User.scala
tests/cross/src/main/scala/tests/BaseCompletionSuite.scala
tests/cross/src/main/scala/tests/TextEdits.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala

Implement type member selection in string interpolators.

---

metals/src/main/scala/scala/meta/internal/metals/Configs.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java
mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala/scala/meta/internal/pc/Completions.scala
mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideConfigSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

See individual commits for details.

Two completion improvements

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/Configs.scala
metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/SbtDigest.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala/scala/meta/internal/docstrings/MarkdownGenerator.scala
mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala
test-workspace/src/main/scala/example/User.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala
tests/slow/src/test/scala/tests/DefinitionCrossSlowSuite.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/DefinitionSlowSuite.scala
tests/unit/src/test/scala/tests/HoverSlowSuite.scala
tests/unit/src/test/scala/tests/JavadocSuite.scala
tests/unit/src/test/scala/tests/SbtDigestSuite.scala
tests/unit/src/test/scala/tests/SbtRelatedSuite.scala

Builds upon #596, see individual commits.

Several small fixes

---

mtags/src/main/scala/scala/meta/internal/mtags/MtagsIndexer.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaMtags.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
mtags/src/main/scala/scala/meta/internal/pc/Completions.scala
mtags/src/main/scala/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala/scala/meta/internal/pc/SignatureHelpProvider.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala
tests/input/src/main/scala/EmptyPackage.scala
tests/unit/src/test/resources/definition/EmptyPackage.scala
tests/unit/src/test/resources/documentSymbol/EmptyPackage.scala
tests/unit/src/test/resources/expect/toplevels.expect
tests/unit/src/test/resources/mtags/EmptyPackage.scala
tests/unit/src/test/resources/semanticdb/EmptyPackage.scala
tests/unit/src/test/resources/workspace-symbol/EmptyPackage.scala

This PR fixes most of the issues on the v0.5 milestone that are labeled as "bug", see individual commits for details.

Fix six bugs

---

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala/scala/meta/internal/pc/Completions.scala
mtags/src/main/scala/scala/meta/internal/pc/HoverProvider.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala

Thanks to @jvican for reporting several minor quirks, see individual commits for details.

Several UX improvements 

---

mtags/src/main/scala/scala/meta/internal/metals/Fuzzy.scala
tests/unit/src/test/scala/tests/FuzzySuite.scala

Enable workspace query to match package object

---

README.md
build.sbt

As part of a new collaboration between the Scala Center and VirtusLab, Marek (@marek1840) and Tomasz (@tgodzik) will be contributing to Metals development for the coming months. They have already contributed several impressive pull requests:
- `textDocument/foldingRange` (#632): code folding that understands Scala syntax.
- `textDocument/documentHighlight` (#621): highlight occurrences of a symbol in  the current file.
- `textDocument/completion` (#640): override def completions from without the need to type "override def ".
It is my pleasure to welcome them to the team and I look forward to working together with them to improve the Scala editing experience :)

Welcome Marek and Tomasz to the team!

---

docs/editors/vscode.md

'search for metals in the marketplace' briefly confused me since I didn't know
which 'marketplace' this was referring to.

Link to vscode marketplace

---

tests/mtest/src/main/scala/tests/BaseSuite.scala
tests/unit/src/main/scala/tests/BaseSlowSuite.scala
tests/unit/src/test/scala/tests/CompletionSlowSuite.scala

This test has repeatedly failed on Appveyor, let's see if disabling it
helps stabilize the CI. Towards #667

Disable flaky test on Appveyor.

---

CHANGELOG.md
website/blog/2019-04-26-mercury.md

The artifacts for v0.5.1 are already on Maven.

Add release notes for v0.5.1

---

README.md
website/core/Footer.js

Add star count in the website footer

---

build.sbt
docs/editors/new-editor.md
metals-docs/src/main/scala/docs/Docs.scala
metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala
metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
metals/src/main/scala/scala/meta/metals/Main.scala

These settings make it easier for Bloop/Metals contributors to customize
the Bloop version during local development.

Make bloop versions customizable via server properties.

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Previously, it was possible for the Metals process to never exit if the
shutdown future never returns.  Now, we always call `System.exit` even
when the shutdown runs forever.  Without a reliable reproduction, it's
difficult to confirm 100% that this change fixes issue #715. However,
this change should close one potential reason for why the process doesn't exit.

Set timeout for shutdown procedure, fixes #715.

---

docs/editors/new-editor.md

Sorry, if I had seen it before I'd have done both changes together

Clarifiyng a setting

---

.travis.yml
tests/slow/src/test/scala/tests/feature/ClasspathSymbolRegressionSuite.scala
tests/slow/src/test/scala/tests/feature/CompletionCrossSlowSuite.scala
tests/slow/src/test/scala/tests/feature/DefinitionCrossSlowSuite.scala
tests/slow/src/test/scala/tests/feature/WorkspaceSymbolRegressionSuite.scala
tests/slow/src/test/scala/tests/gradle/GradleSlowSuite.scala
tests/slow/src/test/scala/tests/maven/MavenSlowSuite.scala
tests/slow/src/test/scala/tests/mill/MillSlowSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtSlowSuite.scala

Fixes https://github.com/scalameta/metals/issues/754

Move slow tests to separate directories and run them separately on Travis

---

website/siteConfig.js

Remove Work-in-progress from the tagline

---

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Fixes https://github.com/scalameta/metals/issues/791

Remove dot as a commit character

---

project/plugins.sbt

Tiny change, this only affects our own build.

Use sonatype:public in our own meta build

---

docs/editors/vim.md
metals-docs/src/main/scala/docs/RequirementsModifier.scala

Great work on the newest version!
Noticed the nvim version was lagging behind and that the required version of Java wasn't updated yet.

nvim version and updated info about required java versions

---

metals/src/main/resources/millw
metals/src/main/resources/millw.bat
metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala

Fixes https://github.com/scalameta/metals/issues/841

Fix issue with wrong mill version in predef script and update millw scripts

---

mtags/src/main/scala/scala/meta/internal/metals/Fuzzy.scala
tests/unit/src/test/scala/tests/FuzzySuite.scala

Fixes https://github.com/scalameta/metals/issues/832

Fix issue if exact query is longer than the class name

---

metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala

The support was added in https://github.com/emacs-lsp/lsp-mode/pull/936

Emacs supports client commands now

---

metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala

Related to https://github.com/scalacenter/bloop/issues/880

Do not report issues in Java only projects

---

docs/editors/overview.md

Features grow faster than editors, so I feel it's more natural to have editors as columns and features as rows.

Transpose features/editors table

---

mtags/src/main/scala/scala/meta/internal/pc/CompilerAccess.scala

This is an attempt to reduce flaky test failures. Supersedes #861

Catch ShutdownReq exception from stopping a presentation compiler.

---

metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/MavenBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala

Recommend a recent version of the build tool when incompatible or unknown

---

build.sbt
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala

Should fix issues we were having with crashing PC

Bump Metals Scala version to 2.12.9

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
tests/unit/src/test/scala/tests/TreeViewSlowSuite.scala

- ensure we use a stable version of guava, previously it would change between runs.
- ensure we shutdown the rambo compiler Thread if it's used

Fix broken tests

---

bin/merged_prs.py
website/blog/2019-09-02-thorium.md

Fixes https://github.com/scalameta/metals/issues/895

Fix links to merged PRs in blogpost

---

docs/editors/vscode.md
mtags/src/main/scala/scala/meta/internal/pc/CompilerAccess.scala
tests/unit/src/test/scala/tests/TreeViewSlowSuite.scala

Follow from https://github.com/scalameta/metals/pull/873 - this should finally fix the issues with tests and possibly more.

Retry with clean compiler after ShutdownReq

---

docs/editors/sublime.md

As we agreed at Gitter channel I prepared some tips & tricks for better development productivity in Sublime Text.

Add additional tips & tricks to the sublime text documentation

---

docs/editors/overview.md

The Eclipse plugin has been updated to support these new features.

Update with new Eclipse capabilities

---

build.sbt
mtags/src/main/scala/scala/meta/internal/pc/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Found it being an issue after adding subtyping.

Don't propose completions for null or nothing

---

tests/unit/src/test/scala/tests/CodeLensesSlowSuite.scala

Previously, the code lenses were tested against classes defined in an empty package. 
Now, the classes are within a package.

Test code lenses within packages

---

tests/mtest/src/main/scala/tests/BaseSuite.scala

This will help debug test failures in CI.
Context https://gitter.im/lihaoyi/utest?at=5d9c3404e8de6f3ca05cc2e7

Print summary of test failures at the end of the logs.

---

README.md
build.sbt

Chris has contributed a lot of nice improvements to Metals, including
"implement all methods" completions, fixing multi-line string formatting
on paste, codebase cleanups and improving the documentation for vim
users. It is my pleasure to welcome Chris as a Metals maintainer!

Welcome Chris to the team!

---

tests/unit/src/test/scala/tests/worksheets/WorksheetLspSuite.scala

Disable flaky test on Window

---

project/plugins.sbt

This fixes a typo made [here](https://github.com/scalameta/metals/commit/7462e5d359a6782e4cb16ba26e733c224f8d3533)

Update sbt-ci-release to 1.4.31

---

project/build.properties
tests/cross/src/test/scala/tests/pc/MacroCompletionSuite.scala

Alas! Again the test failure migrate!
I have no idea what classpath magic influences this :sweat_smile:

Update sbt to 1.3.4 and fix flaky 2.13.0 test

---

build.sbt

Let's give it a second go with the mac tests enabled :apple:

Update directory watcher to 0.9.6

---

metals-docs/src/main/scala/docs/TextEditorModifier.scala

Reopening https://github.com/scalameta/metals/pull/1127

Update import documentation for Emacs

---

build.sbt
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

Update mdoc-interfaces to 2.1.1

---

metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala

_why is this only finding one occurance... I swear I saw more... wait a second_

typo - evaluating

---

mtags/src/main/scala/scala/meta/internal/mtags/MtagsEnrichments.scala
tests/unit/src/test/scala/tests/DefinitionSuite.scala
tests/unit/src/test/scala/tests/MtagsEnrichmentsSuite.scala

* Fix the logic in various "does this range enclose that position/range" checks, particularly for multi-line ranges
* Add unit tests
* Minor refactoring: renaming; combining two implicit classes into one

Fix some incorrect range-encloses checks and add tests for them

---

docs/editors/vim.md

I also added in a small section about worksheets in Vim/Neovim.

Change namespace to scalameta

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala

I missed that when refactoring previous PR.

Add ability to cancel build server connection

---

bin/merged_prs.py
bin/test-release.sh
docs/build-tools/bloop.md
docs/build-tools/gradle.md
docs/build-tools/maven.md
docs/build-tools/new-build-tool.md
docs/editors/debug-adapter-protocol.md
docs/editors/debugging.md
docs/editors/new-editor.md
docs/editors/overview.md
docs/editors/vscode.md
website/blog/2020-01-10-cobalt.md
website/i18n/en.json
website/sidebars.json

I think these release notes cover almost everything that we wanted to mention. If anyone has any last comments, let me know. I will start the release later today and merge them afterwards.
Also as a side effect fixes https://github.com/scalameta/metals/issues/1078

Add release notes for the epic version of Metals :D

---

website/blog/2020-01-10-cobalt.md

Link authors' github accounts for release notes

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question.md

Very small, but we might as well update them with the release.

Update versions in issue templates

---

mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala

Fixes https://github.com/scalameta/metals/issues/1328

Change last require in PC to warning

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala

Fixes https://github.com/scalameta/metals/issues/1334
This uri is what we get from DAP requests and it seems broken.

Make sure the path on windows is a proper URI

---

docs/contributors/getting-started.md

Mention debugging in contributing docs

---

.github/workflows/ci.yml

After recent changes it should now be possible to cache up to 2 GB, so we should be fine to cache the Coursier directories.

Add caching to github actions for Cousier

---

docs/editors/overview.md

Renaming symbols, running tests and debugging is actually supported now

Updated "unsupported features"

---

.github/workflows/ci.yml
build.sbt

Fixes https://github.com/scalameta/metals/issues/1161
Can anyone using MacOS confirm?

Update Nu Process to 1.2.5 and directory watcher to 0.9.9

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/debug/MetalsDebugAdapters.scala

Fixes https://github.com/scalameta/metals/issues/1334
This time checked on windows properly.

Resolve uri from path properly for setting breakpoints

---

tests/unit/src/test/scala/tests/ReferenceLspSuite.scala

I merged the PR around the same time the munit PR was merged.

Fix testAsync -> test after a logical merge conflict

---

.github/workflows/ci.yml
project/plugins.sbt

See https://scalameta.org/munit/docs/reports.html for an example report.
This will allow us to track how flaky some tests are and which tests are
slow to run.

Start recording test reports with sbt-munit

---

metals/src/main/scala/scala/meta/internal/pantsbuild/Args.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/PantsExport.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTargetType.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/TargetType.scala

Several improvements to Pants integration

---

build.sbt
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/LinkCommand.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/OpenCommand.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/RemoveCommand.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedCommand.scala

Fixes issues in https://github.com/scalameta/metals/pull/1422

Update metaconfig-core to 0.9.8

---

metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala
tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala

The issue explained in the test case.

Fix issue with multiple pipes in string

---

docs/editors/debug-adapter-protocol.md
docs/editors/emacs.md

Thank you for the excellent debugging support!
I recently used it in an emacs project, and wanted to update the documentation on it.

Document emacs integration with debug adapter and tree view protocol

---

metals/src/main/scala/scala/meta/internal/pantsbuild/PantsGlobs.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/CreateCommand.scala
tests/slow/src/test/scala/tests/pants/PantsGlobsSuite.scala

Polishing touches on Pants integration

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question.md
build.sbt
docs/contributors/releasing.md
docs/editors/vim.md
metals/src/main/scala/scala/meta/internal/metals/UserConfigurationOption.scala
website/blog/2020-02-26-cobalt.md

I plan to do the release tomorrow, so let me know if we should include something more.
There is one more section that I need to add, but otherwise it's almost ready.

Add release notes for the 0.8.1 release

---

docs/build-tools/mill.md
metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala

- Add `.mill-version` to mill.md

Bump mill default version

---

metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedCommand.scala

Resolves https://github.com/twitter/twitter-virtuslab/issues/13

Don't run bloop install when opening intellij

---

metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedCommand.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SwitchCommand.scala

* Refine message if the Bloop project is not yet exported.
* Generate symbolic links for directories to improve the "project files" view

Minor polish for Pants integration

---

project/plugins.sbt

When I did #1534 I forgot to also update the sbt-munit plugin. This pr updates that plugin.

Update sbt-munit plugin

---

build.sbt
project/plugins.sbt

This pr updates the mdoc dependency and plugin.

Update mdoc dependencies

---

metals/src/main/scala/scala/meta/internal/pantsbuild/commands/Project.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/ProjectRoot.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/RemoveCommand.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedCommand.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedOptions.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SwitchCommand.scala

Several small polishing touches for Pants integration

---

build.sbt

This pr is just a few more of the trivial dependency updates.
jsoup
flyway-core
scala-java8-compat

A few more dependency updates

---

build.sbt

This pr updates the 2 coursier dependencies

Update coursier dependencies

---

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/PantsExport.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/PantsExportResult.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/PantsKeys.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/PantsPreferredJvmDistribution.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTarget.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/BloopGlobalSettings.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedCommand.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/ZipkinUrls.scala

More fixes for the Pants integration

---

build.sbt
metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/BloopGlobalSettings.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/ExportOptions.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedCommand.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/ZipkinUrls.scala
metals/src/main/scala/scala/meta/internal/zipkin/ZipkinUrls.scala
mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala

Small tweaks to Pants export

---

metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/PantsConfiguration.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/Project.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/RefreshCommand.scala
metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedCommand.scala

Small changes to Pants integration

---

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala

Remove .bloop symbolic link during Pants export

---

metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala

To avoid intellij auto refresh

Add disabled X-detectExternalProjectFiles flag

---

mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala

Fixes https://github.com/scalameta/metals/issues/1588

Fix `package` added artificially on imports from package objects

---

docs/editors/overview.md

- Installation is now limited to a package install like vscode or vim
- [LSP-metals](https://packagecontrol.io/packages/LSP-metals) has support for status bar

Update Sublime in the editors overview doc

---

metals/src/main/scala/scala/meta/internal/metals/NewFilesProvider.scala
tests/unit/src/test/scala/tests/NewFilesLspSuite.scala

Getting weird access denied exceptions. Might be a race condition between folder being opened and used.
```
INFO  Executing command [new-scala-file]
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[error] ==> X tests.NewFilesLspSuite.new-trait-new-dir  2.929s java.nio.file.AccessDeniedException: C:\Users\RUNNER~1\AppData\Local\Temp\metals14694223127987732815Baz.scala -> D:\a\metals\metals\tests\unit\target\e2e\new-files\new-trait-new-dir\a\src\main\scala\bar\Baz.scala
at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
[info] …
```

Fix NewFileLspSuite on Windows

---

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
tests/unit/src/test/scala/tests/ImplementationLspSuite.scala

This PR addresses https://github.com/scalameta/metals/issues/1464

goto Implementations with local alias types

---

mtags/src/main/scala-2/scala/meta/internal/metals/Trees.scala
tests/slow/src/test/scala/tests/feature/WorksheetCrossLspSuite.scala

update dialect of worksheet to scala213

---

build.sbt
metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolQuery.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala
tests/slow/src/test/scala/tests/feature/CompletionCrossLspSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
tests/unit/src/main/scala/tests/QuickBuild.scala
tests/unit/src/test/scala/tests/MessagesSuite.scala

Also bumps scalameta to 4.3.9 and Bloop to the newest snapshot.

Add support for Scala 2.13.2

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala
tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala

Add the code action "import all missing symbols that are unambiguous" for issue #1610

Feature : Code action Import all missing symbols

---

mtags/src/main/scala-2/scala/meta/internal/metals/MultilineStringFormattingProvider.scala
mtags/src/main/scala-2/scala/meta/internal/metals/Test.sc
tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala

* Indentation is not working correctly (but the test doesn't show the issue :(

Handle return to line in strings in OnTypeFormatting

---

mtags/src/main/scala-2/scala/meta/internal/metals/MultilineStringFormattingProvider.scala
mtags/src/main/scala-2/scala/meta/internal/metals/Test.sc
tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala

This is just to show how we could use onTypeFormartting to do some simple actions

Use onType formatting to create multiline string 

---

metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala

Fixes https://github.com/scalameta/metals/issues/1700

Update Mill version to 0.6.2

---

docs/editors/new-editor.md
docs/editors/vim.md

This adds in updated information about the Tree View Protocol support
in coc-metals and also more information about the ability to now set
things via `InitializationOptions`.

Add in some documentation for vim and `InitializationOptions`

---

build.sbt
metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/1714

When no build.properties is available run the recommended sbt version

---

mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-2/scala/meta/internal/pc/AutoImports.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala

This fix issue https://github.com/scalameta/metals/issues/1709 by better fixing old issue #1686 😁
I removed unused collectLast so we don't have extra code.

handle package object in autoImports

---

README.md
build.sbt

Krzysztof has already done a lot of good work in Metals including go to parent code lenses, a number of bugs and investigations.
I am happy to welcome him to the team!

Welcome Krzysztof to the team!

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/FileSystemSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/SemanticdbClasspath.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/Semanticdbs.scala
tests/slow/src/test/scala/tests/SymlinkedProjectSuite.scala

Fixes https://github.com/scalameta/metals/issues/1370

Fix issues with symlinks in source directories

---

metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
tests/unit/src/main/scala/tests/TestingClient.scala

Fixes https://github.com/scalameta/metals/issues/1801

Fix ammonite suite flakiness 

---

build.sbt

Fixes https://github.com/scalameta/metals-vscode/issues/208

Update directories to 12

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/NewFilesProvider.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/AmmoniteCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/FilenameCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
tests/slow/src/test/scala/tests/feature/CompletionCrossLspSuite.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/NewFilesLspSuite.scala

Also in this PR:
- fixes https://github.com/scalameta/metals/issues/1770
- adds ammonite script to new file provider
Completions:
cc @alexarchambault

Added completions for $file in ammonite scripts

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question.md
bin/merged_prs.py
build.sbt
website/blog/2020-06-27-lithium.md
website/blog/2020-07-01-lithium.md

The PR is ready to review! I think I added most important new features - the worksheet imports feature is kind of last minute, but I think it's important to highlight.
I mentioned that Ammonite support might need some improvements mostly due to the $file import issues, that I haven't managed to yet solve.

Add release notes for 0.9.1 version

---

metals-docs/src/main/scala/docs/BootstrapModifier.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala

Document -version flag and log clientType

Document -version flag and log clientType

---

metals/src/main/scala/scala/meta/internal/metals/ChosenBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/DismissedNotifications.scala
metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/DoctorResults.scala
metals/src/main/scala/scala/meta/internal/metals/HtmlBuilder.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/PopupChoiceReset.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala

Few questions:
- command in html will be only supported by vscode, does any other editor uses html? If so how to show that only for VSCode/editors supporting commands in html?
- I used `showMessageRequest` but would it be better to use quickpick?

Reset notifications popup

---

metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala
tests/unit/src/test/scala/tests/NewProjectLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/1889
I managed to find some more issues with the regex and made the tests more resilient.

Make sure we take into account all templates from the wiki page 

---

metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala
tests/slow/src/test/scala/tests/gradle/GradleLspSuite.scala

Makes some improvements to the gradle-bloop integration. There's more information in the commit messages :smile:

Improve gradle-bloop integration

---

tests/unit/src/test/scala/tests/TreeViewLspSuite.scala

I haven't noticed that the PR was aimed at master.

Merge from master to main

---

docs/editors/new-editor.md

This updates the documentation for new clients and is focused on
configuring the client with `InitializationOptions` rather than
properties. All of the properties that are able to be set but are
also able to be set via `InitializationOptions` have been removed
from the documentation. The same for values under `experimental`,
which are now under `InitializationOptions`.
Part of #1895

Update new-editor docs.

---

metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala

Better fix for https://github.com/scalameta/metals/pull/1936

Take into account server property in statusBarState

---

docs/editors/atom.md
docs/editors/eclipse.md
docs/editors/emacs.md
docs/editors/sublime.md
docs/editors/vim.md
docs/editors/vscode.md
metals-docs/src/main/resources/META-INF/services/mdoc.StringModifier
metals-docs/src/main/scala/docs/WorksheetModifier.scala

Add more documentation about worksheets.

---

metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala

Add CleanCompile to server commands documentation

---

metals/src/main/scala/scala/meta/internal/metals/AdjustLspData.scala
metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/Warnings.scala
tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala

Couple of issues I noticed only after merging the sbt support PR.

Adjust locations returned from the presentation compiler 

---

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/1975

Add checking exact name to all references() invocations

---

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala

Previously, we wouldn't always generate `metals.sbt` needed for the Bloop plugin to generate `.bloop` configuration. The logic especially broke if the `project` directory didn't exist. Now, we make sure that there is a corresponding `metals.sbt` file for each level of *.sbt files excluding `metals.sbt` themselves.
To clarify what's going on:
- `project/metals.sbt` is needed for the `.bloop` config used for Scala files
- `project/project/metals.sbt` is needed for the `project/.bloop` config used for `*.sbt` files and `project/*.scala` files
- `project/project/project/metals.sbt` is needed for the `project/project/.bloop` config used for `project/*.sbt` files and `project/project/*.scala` files
- etc.

Simplify logic to add metals.sbt files and make sure it's tested

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/AdjustLspData.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompilerInterfaces.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala/scala/meta/internal/metals/CompilerOffsetParams.scala
tests/mtest/src/main/scala/tests/BaseSuite.scala
tests/slow/src/test/scala/tests/feature/WorksheetCrossLspSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

CC @odersky 
Once I get the build green I will merge the PR and it will be available under snapshot. If there is any issues I can work on it next week, but overall I will most likely still try to tidy up things for the release and double check everything. I might have not had the time to do it yet.

Add support for worksheets in Scala 3

---

metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala

Change hardcoded $(info) icon to read from ClientConfig instead.

---

build.sbt
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
tests/unit/src/test/scala/tests/worksheets/WorksheetNoDecorationsLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/1752

Add types to worksheet values

---

docs/editors/overview.md
metals-docs/src/main/scala/docs/GenericModifier.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala

Resolves https://github.com/scalameta/metals/issues/1983

Update information about Sbt, Ammonite and worksheet support

---

metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala

I just hit on an issue where I continuously got "failed to connect to
build server" no matter what I tried (restart bloop, rm -rf .bloop,
reload window. The metals.log file contained these stack traces
https://gist.github.com/olafurpg/b41c4babb98dba05fe93af24ff3fe4b6
This commit adds a try/catch around the place where the uncaught
exception caused problems.

Add try/catch around unsafe code block.

---

metals/src/main/scala/scala/meta/internal/metals/FileSystemSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/FileWatcher.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala

Properly detect semanticdb target for Scala 3

---

docs/editors/vscode.md
tests/unit/src/main/scala/scala/meta/internal/metals/debug/TestDebugger.scala

Fixes https://github.com/scalameta/metals/issues/1807

Document how to run or debug applications

---

website/blog/2020-08-19-lithium.md

I thought it tested it, but must have missed it :/

Change link in blog post to absolute path

---

docs/build-tools/sbt.md
docs/editors/overview.md

Fixes https://github.com/scalameta/metals/issues/2023

Update sbt docs to better explain how to manually install Metals prior to 0.7.6 version

---

metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala

Managed to make it all work now out of the box with run and test available within seconds :tada:

Add Maven template to the curated list of templates

---

docs/editors/emacs.md

Update emacs docs to include latest lsp-metals changes

---

tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala

A lot has changed since #1801 was created. I'm going to run the tests on this a bit and see if this may have solved itself.

Look into ammonite flakiness in tests to see if we can remove it

---

build.sbt

Fixes https://github.com/scalameta/metals/issues/2076

Update mdoc version to 2.2.9

---

.github/workflows/ci.yml

I may or may not have missed this one...
However, the positive is that everything looks to have gone fine with the last one.

Bump other reference of coursier/cache

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question.md
bin/test-release.sh
build.sbt
docs/contributors/releasing.md
website/blog/2020-09-21-lithium.md

I still need to update last PRs, but since it's nothing major I will update it before merging.

Add release notes for v0.9.4

---

metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala

Add documentation for new parameter in GotoLocation

---

tests/unit/src/test/scala/tests/TreeViewLspSuite.scala

Trying to fix the CI, which might have been broken by recent JDK release.

Add JFR for non oracle JDK releases

---

metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala

I tested it locally but I'm not sure if it's possible to write a test on this thing.
I tried to comment [this line in SbtLspSuite](https://github.com/scalameta/metals/blob/73ac12e4d4b8f4146db0524c63e78ca960fe4bb9/tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala#L578) but it doesn't work 
Fix #2106

Fixed sbt completions coming from project/*.scala

---

metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala
metals/src/main/scala/scala/meta/metals/DownloadDependencies.scala

Fixes https://github.com/scalameta/metals/issues/2156

Make sure that default version is picked up for Scalafmt provider

---

metals/src/main/resources/millw
metals/src/main/resources/millw.bat

Based on recent changes https://github.com/lefou/millw/pull/9 and https://github.com/lefou/millw/pull/8

Update mill scripts

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Fixes https://github.com/scalameta/metals/issues/1431
After experimenting a bit this seems to fix the issue. Before the change I was able to quickly remove a bunch of imports and add them back, which would break the folding. Now, it works as expected.

Fix race condition while using textDocument/foldingRange

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
tests/mtest/src/main/scala/tests/BaseSuite.scala

This is done similarily to FormattingProvider.

Preload scalafix to optimize first organize imports run

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
tests/unit/src/test/scala/tests/ReferenceLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/2094

Make sure build server is connected or not available before parsing

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala

Connected to https://github.com/scalameta/metals/issues/2093
I am not a 100% sure about this solution, but this should help with flaky connection issues. It's also the way it's done with the language server in VS Code. Opinions? This should not change too much, it's more "just in case"

Add retry in case of timeout in build/initialize

---

website/blog/2020-11-06-sbt-BSP-support.md

So this is a stab at making sure the BSP thing is clear for users. I did my best to _very_ briefly outline what BSP is, what effect does this have on a Metals user, and how to try the new sbt BSP support if they like. Let me know what you think. Hopefully this can also allow for you to not have to write much about it in the release notes @tgodzik and instead just link to this.

Add in blog post about sbt BSP

---

docs/contributors/releasing.md

Noticed that we are a bit behind :sweat_smile:

Update release docs

---

website/blog/2020-11-10-lithium.md

CC @kurnevsky - what do you think?

Fix release notes to mention emacs

---

.github/workflows/ci.yml
build.sbt

Follow up from https://github.com/scalameta/metals/pull/2203

Add testing for DownloadDependencies

---

docs/build-tools/proxy.md

Follow up from https://github.com/scalameta/metals-vscode/issues/126#issuecomment-724153433
@gavares I added an additional section to troubleshooting.

Add additional troubleshooting section for mirrors

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
mtags/src/main/scala/scala/meta/internal/metals/PackageIndex.scala
tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala
tests/cross/src/test/scala/tests/pc/CancelCompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetNegSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/mtest/src/main/scala/tests/BaseSuite.scala

CC @smarter
Fixes https://github.com/scalameta/metals/issues/2214

Add 0.27.0-RC1 back to supported versions

---

project/plugins.sbt

Resolves merge conflict from: #2229

Update munit-docs, sbt-munit to 0.7.17

---

docs/editors/vscode.md

Follow up from https://github.com/scalameta/metals/pull/2254 after my breaking push :sweat: 
fix #2253
Thanks @bjornregnell !

Fix documentation about buildTarget

---

build.sbt
docs/contributors/getting-started.md
project/Welcome.scala
project/plugins.sbt

I tried to add a variety of commands that I used that could also help people new to sbt overall.

Add welcome view for new contributors

---

metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala

The template got recently updated.

Change lampepfl/dotty.g8 to lampepfl/scala3.g8

---

build.sbt
tests/slow/src/test/scala/tests/feature/AmmoniteSuite.scala

Bump Ammonite to the 2.13.4 published version.

---

metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala

Before this it wasn't being shown under the server commands in the docs.
I also ordered them to make it easier to dig through them since the order
matters in how they appear.

Add in CopyWorksheetOutput to all so it's in the docs.

---

docs/editors/vim.md

This just updates the recommended mappings to the latest from coc.nvim.
This also adds in reference to the new nvim-metals plugin since it's at
a point where it supports pretty much everything except code lenses, debugging,
and the tree view protocol.

Update Vim mappings and add reference to nvim-metals.

---

metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

Implicit symbol rename fix

---

docs/editors/overview.md

Just like VSCode organize imports it is available under LSP -> source action

Update editor overview doc (sublime)

---

metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala

There are two levels of possible failure on scalafix:
- The first one: Scalafix completely fails running because the interface is not called with the correct arguments, or the provided file to fix doesn't exit. So the possible errors here are : commandLine error, Nofile to fix. This is not supposed to happen with Metals. 
- The second level: Scalafix can fix multiple files. For each file, we store if scalafix run successfully or not. In Metals, we only run on one file, and the possible errors are ParseError (if the file cannot be parsed), StaleSemanticdbError, MissingSemanticdbError. Those errors may happen and we want to display them.
So this PR improves the errors displayed. thanks for your feedbacks

Provide a more specific error message when scalafix fails organizing imports

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Minor fix: remove usused parameter

---

docs/contributors/releasing.md
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersionSelector.scala
metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

Add configuration option for default Scala version

---

metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

Finally following up on  #2233.
I was not able to reproduce the issue but I agree with @tgodzik that it might be a race condition, that this MR wants to solve

Wait for compilation to finish before starting debug session #2233

---

website/blog/2018-12-14-iron.md
website/blog/2019-01-24-tin.md
website/blog/2019-02-01-tin.md
website/blog/2019-04-12-mercury.md
website/blog/2019-04-26-mercury.md

Being a Metallurgical Engineer, I love Metals. 
I wanted to make sure we didn't miss any elements.
Not tested.

Include the element in the version

---

mtags/src/main/scala-2/scala/tools/nsc/interactive/GlobalProxy.scala

It seems that the presentation compiler thread might have not been shutdown after replacing it with the Metals one. ~~As we are actually not doing any work on the presentation compiler thread, I shut it down at the start.~~
~~Also it seems that we are not actually able to shut down just the default thread, unless we also shutdown the whole compiler, so the workaround here was not working.~~
~~Having a separate compiler thread implementation was more important at the time of:
https://github.com/scalameta/metals/commit/42869b83115eddca3f0e0dd900947a31dff2b7b9#diff-595864b0c8640c58607d7984e12eba675a293acedb5950339d4f129e69598638R58~~
~~it should not be that important now and all features work with it shutdown.~~
Actually, we still do use `.interrupt`, so I followed @mlachkar advice from …

Try to fix memory leak in presentation compiler

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala

Fixes https://github.com/scalameta/metals/issues/2480

Remove unused val that may cause null pointer exceptions

---

docs/editors/emacs.md

I hope that these few comments in config can save someone a lot of time.
See some struggle related to that stuff https://github.com/emacs-lsp/lsp-ui/issues/571

Add few emacs config performance tuning tips to docs/editors/emacs.md

---

mtags/src/main/scala-3/scala/meta/internal/pc/CompilerInterfaces.scala

Fixes https://github.com/scalameta/metals/issues/2582

Set compilationUnit when using Dotty parser

---

docs/integrations/new-editor.md

Link to the actual metals client commands

---

docs/contributors/getting-started.md
docs/editors/vim.md
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java

Found some old dead links that needed an update

Update dead links

---

README.md
build.sbt

Vadim has added a lot of amazing contributions to Metals including the sbt support and numerous Scala 3 improvements. Please welcome him to the team! :tada:

Welcome Vadim to the team!

---

README.md
build.sbt

Adrien is a part of the Scala Center team and was essential in making BSP support in sbt happen including the recent work on having DAP also available for sbt. It's my pleasure to welcome him to the team! :tada:

Welcome Adrien to the team!

---

build.sbt

Bump amm version and amm scala 2.13 version

---

build.sbt

Geny is now also released for 2.11 :tada:

Update geny to 0.6.7

---

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala
metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Follow up to https://github.com/scalameta/metals/pull/2636
This make type decorations consistent with what can be expected to pop up in the code

Make sure that universal types deco are printed properly

---

tests/input3/src/main/scala/example/GivenAlias.scala
tests/unit/src/test/resources/documentSymbol-scala3/example/GivenAlias.scala
tests/unit/src/test/resources/semanticdb-scala3/example/GivenAlias.scala

Fixes https://github.com/scalameta/metals/issues/2533
The issue was fixed in 3.0.0-RC2

Add test to check for occurrences of anonymous using params

---

project/plugins.sbt

Supersedes https://github.com/scalameta/metals/pull/2646

Update sbt-ci-release to 1.5.7

---

website/blog/2021-04-06-tungsten.md

Pretty long release notes and mostly bugfixes. I haven't added a single new feature! :D

Add release notes for Metals v0.10.1

---

docs/editors/emacs.md

https://github.com/scalameta/metals/issues/2641

Update the documentation to recommend using company-capf

---

build.sbt

Bump sbt-debug-adapter

---

project/Welcome.scala

Connected to https://github.com/scalameta/munit/issues/348
So this is kind of a middle ground until we fix it in munit.

Add hint to welcome messages to use '-F' flag

---

.scalafmt.conf
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala

I just released the first release candidate that adds Scala 3 support. Let's test it out!

Update scalafmt to 3.0.0-RC1

---

mtags/src/main/scala-2/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala

Fixes https://github.com/scalameta/metals/issues/2686

Make insert type work with renamed imports

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala
tests/unit/src/test/scala/tests/codeactions/ImplementAbstractMembersLspSuite.scala

`ImplementAsbtractMembers` - support names with dots

---

metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala

Two things are done in this PR:
- make sure that if the custom configuration file doesn't exist that we will properly report it to the user
- make sure that Scalafix will always pick up the semanticdb file from the targetroot
The second problem popped up in cases that semanticdb started being written to a different directory (`/target/scala-2.13/meta/`), which meant that Scalafix could pick up the old stale files from .bloop directory.
The change most likely came from sbt, which might have started adding it as the default, but I am not entirely sure why.
Fixes https://github.com/scalameta/metals/issues/2748

[Scalafix] Report problems with invalid path and fix flaky behaviour

---

metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala

The previous test logic was based on downloading artifact from bintray that doesn't work anymore

Fix failing tests: SbtBloopSuite + FoldingRangeSuite (Windows)

---

metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala

Previously, I didn't take into account windows line endings.

Properly adjust folding range end on windows

---

mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

[Scala3] Completions - do not backtick NamedArg completion values

---

docs/troubleshooting/faq.md

Fixes https://github.com/scalameta/metals/issues/2798

Add FAQ entry about sbt Apple M1 issue

---

build.sbt

succeeds https://github.com/scalameta/metals/pull/2837

Update amonite to 2.3.8-124-2da846d2 and add support for 2.13.6

---

mtags/src/main/scala/scala/meta/internal/semver/SemVer.scala
tests/slow/src/test/scala/tests/feature/SyntaxErrorLspSuite.scala

[Scala3] Add test that checks that diagnostic for inline def usage works correctly

---

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersionSelector.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
metals/src/main/scala/scala/meta/internal/metals/debug/SetBreakpointsRequestHandler.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala
mtags/src/main/scala/scala/meta/internal/mtags/Mtags.scala
tests/unit/src/test/scala/tests/WorkspaceSymbolExpectSuite.scala

[Scala3] Provide correct dialect to `Mtags.allToplevels` calls.

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/debug/SetBreakpointsRequestHandler.scala
tests/slow/src/test/scala/tests/feature/CrossDebugSuite.scala
tests/unit/src/test/scala/tests/ClassBreakpointSuite.scala

Fixes https://github.com/scalameta/metals/issues/2893

Fix off by one error while setting DAP breakpoints

---

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala
metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/2905

Print type decorations for synthetic apply

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Fixes https://github.com/scalameta/metals/issues/2926

Wrap autofilled arguments with backticks

---

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
project/Welcome.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala

Fixes https://github.com/scalameta/metals/issues/2776

Do not use $TMPDIR to store sbt-launcher.jar

---

metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
tests/unit/src/test/scala/tests/worksheets/WorksheetLspSuite.scala

It seems the changes cause a bunch of issues and we need to approach it differently.
Fixes https://github.com/scalameta/metals/issues/2928

Revert "Merge pull request #2908 from tgodzik/reset-object"

---

mtags/src/main/scala-3/scala/meta/internal/pc/CompletionPos.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

[Scala3] Fix completions after newline + dot

---

mtags/src/main/scala-3/scala/meta/internal/pc/SymbolPrinter.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala

This was actually done badly* previously and not actual tests were present, which is why this issue sneaked trough
*Done badly by me :sweat_smile:

[Scala 3] Properly show enum on hover

---

website/blog/2021-08-14-tungsten.md

It's a draft. Will update Merged PR section after upgrading scalameta and merging 3.0.1 support

0.10.5 - release notes

---

.github/workflows/ci.yml
.github/workflows/release.yml

It includes a fix that should help with all the cache misses causing failures
we are seeing on the Steward prs.

Bump cache-action to latest.

---

metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/PatternMatchRefactor.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
tests/unit/src/test/scala/tests/codeactions/ConvertPatternMatchLspSuite.scala

Automatic refactor - pattern match with placeholder

---

.github/workflows/sourcegraph.yml
project/plugins.sbt

I tried sending in a pr against the sourcegraph branch to try to get the LSIF job to run, but it doesn't. I'm pretty sure this needs to actually be merged into main in order to pick it up.

Merge sourcegraph branch into main.

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
tests/unit/src/main/scala/tests/BaseRenameLspSuite.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

References - filter out wrong results from unrelated build targets

---

mtags/src/main/scala-3/scala/meta/internal/pc/IndexedContext.scala

The previous incorrect `scopeSymbols` implementation was the main contributor in #2956 issue.
Calling an empty completion leaded to that all chain of `IndexedContext` were starting initialization of `lazy val scopeSymbols` where `scopeSymbols` has been storing a duplicated subsequences of symbols on several layers.
For example, one of the last outer context imports `java.lang._`(~900 entries).
It means that each inner context was keeping a list of 900+ elements: 
`scopeSymbols = ${current ctx symbols} ++ .. ++ ${java.lang._ symbols}` .
So a lot of space were used by `scala.collection.immutable::`

[Scala3] Fix memory usage spike on empty completions

---

docs/editors/online-ides.md
docs/editors/vscode.md

This is in reference to https://github.com/scalameta/metals-feature-requests/issues/225

Add documentation about GitHub Codespaces and GitHub.dev support

---

metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala

Previously, we would try to relatavize a path even if it isn't contained in the workspace. This might cause tmp folder with the created semanticdb popping up in weird places. The reason for that is that we would get a path like `../../../../tmp/metals1945019806267779000.scala` and would resolve it from tmp directory. This sometimes would make the semanticdb file generated for warming up scalafix to show in workspace directory.
Now, we only try to resolve files for organize imports for workspace files and also create the temporary warmup files in `.metals` directory
This is blocking for the next release.

Fix issue with tmp directory popping up in random places

---

.github/ISSUE_TEMPLATE/bug_report.md

The latest one is `0.10.6` :sweat_smile:

bug report template - downgrade version

---

metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

Closes https://github.com/scalameta/metals/issues/1539
EDIT:[here](https://github.com/scalameta/metals/issues/1539#issuecomment-916886224) is a problem description and proposed solution

Fix renaming class hierarchy inside a method

---

metals/src/main/scala/scala/meta/internal/metals/formatting/IndentOnPaste.scala
tests/unit/src/test/scala/tests/rangeFormatting/IndentWhenPastingSuite.scala
tests/unit/src/test/scala/tests/rangeFormatting/MultilineStringRangeFormattingWhenPastingSuite.scala
tests/unit/src/test/scala/tests/rangeFormatting/MultilineStringRangeFormattingWhenSelectingSuite.scala

Previously, we would try to guess the current indentation for the user, but since we don't know exactly what is their intention, it was easy guess wrong. Now we use the current indentation to see what user intends.

Use the current indentation as reference when pasting

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbSymbols.scala
mtags/src/main/scala/scala/meta/internal/pc/MemberOrdering.scala
tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

Align completion items ordering with Scala2 implementation

[Scala3] Improve completions ordering

---

metals/src/main/scala/scala/meta/internal/metals/Doctor.scala

Added version to the doctor as discussed in https://github.com/scalameta/metals/issues/2200

Add build server version to the doctor view

---

metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersionSelector.scala

Previously, it would fail for scala files in /project.

Only set sbt dialect when file has indeed .sbt extension

---

build.sbt

@ckipp01 this should make expression evaluation works better thanks to @tdudzik

Bump Bloop and sbt-debug-adapter

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
mtags/src/main/scala-2/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala/scala/meta/internal/metals/CompilerOffsetParams.scala

RangeHover - fix NPE

---

metals/src/main/scala/scala/meta/internal/metals/debug/SourcePathAdapter.scala

Fixes https://github.com/scalameta/metals/issues/3262

Fix issues when source path is using Windows format

---

metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala
tests/slow/src/test/scala/tests/feature/CrossCodeLensLspSuite.scala

RunDebugLens - fix stale lens

---

metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala
tests/unit/src/test/scala/tests/FormattingLspSuite.scala

In Scalafmt `3.1.0` this setting becomes required.

Formatter: always specify global `runner.dialect`.

---

metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala

Related to https://github.com/scalameta/metals/issues/1697
Previously, setting output to `System.err` didn't seem to work. Tested it out a couple of times and it seems to be all reported correctly now.
```
14:18:15 INFO  Started: Metals version 0.10.10-SNAPSHOT in workspace '/home/tgodzik/Documents/workspaces/metals-sample' for client Visual Studio Code 1.61.2.
14:18:17 INFO  time: initialize in 1.43s
14:18:17 INFO  Attempting to connect to the build server...
14:18:17 INFO  skipping build import with status 'Installed'
14:18:17 ERROR Starting the bsp launcher for bloop...
14:18:17 ERROR Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher12057179593492280189/bsp.socket'...
14:18:17 ERROR Waiting for the bsp connection to come up...
14:18:17 ERROR error: …
```

Print Bloop logs when connection errored out

---

metals/src/main/resources/millw
metals/src/main/resources/millw.bat

Brings in a fix we should have for resolving snapshots.
https://github.com/lefou/millw/releases/tag/0.3.9

Update to latest millw 0.3.9

---

docs/editors/overview.md

https://github.com/sublimelsp/LSP/pull/1900 is now merged

Update sublime doc regarding Hover for selection

---

README.md
build.sbt

Kamil has done a lot of great work in Metals with features such as `decode tasty` and `rewrite placeholder` code action.
I am happy to welcome him to the team! 
PS: @kpodsiad  feel free to merge if you feel like it!

Welcome Kamil to the team!

---

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala

Previously, for mtags_2.12.8 we would download scala library 2.12.15. Now, we download the correct Scala version.
This popped up in https://github.com/scalameta/metals/pull/3278/files where we switched to downloadMtags method as default.

Fix issues with non-latest Scala versions

---

metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala
metals/src/main/scala/scala/meta/internal/implementation/Supermethods.scala
metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/DelegatingLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/NoopLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/findfiles/FindTextInDependencyJars.scala
metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileProvider.scala
tests/unit/src/main/scala/tests/TestingClient.scala

Fixes https://github.com/scalameta/metals/issues/3338
Should we add some tests for it?

Wrap quickpick and input box results into options

---

metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala

Mill `0.9.10+` and `0.10.0-M4+` have a new feature.
You can import plugins on the fly without modifying the build file, by passing `--import ivy:com.lihaoyi::mill-contrib-bloop:` where the missing version is automatically replaced by `$MILL_VERSION`.
This PR makes metals leverage this functionality in versions that support it.

Use Mill `--import` to import bloop when supported

---

metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala

Remove stray pprint

---

metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileProvider.scala
metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileTypes.scala
tests/unit/src/test/scala/tests/NewFileLspSuite.scala

Closes https://github.com/scalameta/metals-feature-requests/issues/246

Enable to create file with just package

---

README.md
build.sbt

Arthur has done a lot of great work in Metals and Bloop (especially great job with Gradle integration) with features such as decoding semanticdb, javap or decompiling. He has also done a lot of progress with the upcoming Java support.
I am happy to welcome him to the team!
PS: @Arthurm1 feel free to merge if you feel like it! You can also add a public email if you have one.

Add Arthur to the team!

---

docs/integrations/new-editor.md
metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/ClientExperimentalCapabilities.scala
metals/src/main/scala/scala/meta/internal/metals/Command.scala
metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala
metals/src/main/scala/scala/meta/internal/troubleshoot/ProblemResolver.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/clients/CommandSuite.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

Fix https://github.com/scalameta/metals-feature-requests/issues/242

Support sublime command links

---

metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/troubleshoot/ProblemResolver.scala
metals/src/main/scala/scala/meta/internal/troubleshoot/ScalaProblem.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

Detect missing src.zip in doctor

---

metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala

This seems to have sneaked in somehow.

Fix issue with imports

---

metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala
tests/slow/src/test/scala/tests/feature/CrossAnalyzeStacktraceSuite.scala
tests/unit/src/main/scala/tests/BaseAnalyzeStacktraceSuite.scala
tests/unit/src/test/scala/tests/AnalyzeStacktraceLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/3424

Fix analyze stacktrace when using toplevel methods

---

bin/update-millw.sh
metals/src/main/resources/millw
metals/src/main/resources/millw.bat

update: update millw and add script for it in the future

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeProvider.scala
metals/src/main/scala/scala/meta/internal/parsing/JavaFoldingRangeExtractor.scala
tests/unit/src/test/resources/foldingRange/expect/Main.java
tests/unit/src/test/resources/foldingRange/input/Main.java
tests/unit/src/test/scala/tests/FoldingRangeSuite.scala

Turns out there is also a Scanner we can use for Java files, which is handy for figuring out braces and comments in the code.

Add folding range for Java using Scanner

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala-3/scala/meta/internal/pc/IndexedContext.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Signatures.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

[Scala3] Fix autoimport with prefixes

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Index source files in parallel.
This implementation may be a little naive but as far as I tell `indexSourceFile` and `buildTargets.linkSourceFile` are thread safe as they only update `TrieMaps`.
Anecdotally - this drops my machine's time spent indexing Kafka from 52s to 32s and Metals from 23s to 14s.

parallelize source file indexing

---

metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
tests/unit/src/test/scala/tests/UserConfigurationSuite.scala

I changed the user config to group the java formatting settings but got the parsing of these settings wrong. This fixes that

fix user config for java formatting

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/mtags-auto-release.yml
build.sbt
website/blog/2022-01-17-aluminium.md

We need to do another release to fix the performance issues.

Add release notes for 0.11.1

---

build.sbt

I missed that ci-release also does additional things.
Let's try this way for while.
I'm going to look at ci-release plugin to find put changes it might require for our case. 
Currently the only way to configure it is to use env-variables but it would require to parse tag names in bash (before running sbt) that I want to avoid.

[Actions] Mtags release

---

build.sbt
project/Scala3NightlyVersions.scala

Previously it was selecting 5 oldest nightly version instead of latest.

release: fix last 5 nigtly version selection

---

mtags/src/main/scala-3/scala/meta/internal/pc/Signatures.scala
tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/hover/HoverDefnSuite.scala

Fixes https://github.com/scalameta/metals/issues/3566

fix: [Scala 3] Show exact literal type

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala

Discussed in https://github.com/scalameta/metals/pull/3554/files/fe689a716e4a700d180672158b146bf414e1c053#r794507049

refactor: `SemanticdbFeatureProvider` trait

---

.github/workflows/sourcegraph.yml

This will fix the error we are seeing that was reported here:
https://github.com/coursier/coursier/issues/2351

chore(ci): update setup-action

---

mtags/src/main/scala/scala/meta/internal/IdentifierComparator.scala
project/TestGroups.scala
tests/unit/src/test/scala/tests/IdentifierComparatorSuite.scala

fixes https://github.com/scalameta/metals/issues/2960

fix: compare long numbers in TVP

---

.scalafmt.conf
tests/unit/src/test/scala/tests/codeactions/CreateNewSymbolLspSuite.scala
tests/unit/src/test/scala/tests/testProvider/TestSuitesProviderSuite.scala

Follow up to https://github.com/scalameta/metals/pull/3610#discussion_r799466636

scalafmt - newlines.inInterpolation = avoid

---

metals-docs/src/main/scala/docs/Docs.scala
website/docusaurus.config.js
website/package.json

They will be available at `/metals/latest.json`.
That required to upgrade docusaurus

docs: provide latest versions

---

metals/src/main/resources/millw
metals/src/main/resources/millw.bat

https://github.com/lefou/millw/releases/tag/0.4.2

Update millw to 0.4.2

---

mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala

This is related to a couple of fixes I did in the compiler itself.

Fix issues in tests for Scala 3 Nightlies

---

metals/src/main/scala/scala/meta/internal/builds/BloopInstall.scala

Fixes https://github.com/scalameta/metals/issues/1923

Add current env variables to bloopInstall

---

metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/troubleshoot/ProblemResolver.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

fix: do not show test explorer related error for client which don't implement it

---

tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala

Fixes https://github.com/scalameta/metals/issues/1691

fix: Add test case when using Left class and Scala 3

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala

Sometimes test provider suites was failing with: obtained `"kind": "addTestCases"` expected `"kind": "addSuite"`. Tests checks only first event send to the client and if this event is `addTestCases` then something isn't right, it should be `addSuite` followed by the `addSuite`.
I think it was due to the following:
- when searching for the test suite, if one was found then it was added to cached test suites
- for junit suites test provider load semanticDB
- loading semanticDB was calling `onChange` which was sending `addTestCases` event
tldr; side effects, it's always side effect :p
I delayed the moment when suite is added to cached suites.

chore: fix flaky test provider suite

---

tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala

Fixes https://github.com/scalameta/metals/issues/1634
This needed to be fixed in the compiler: https://github.com/lampepfl/dotty/pull/14436

fix: Add tests for Scala 3 toplevel enums

---

tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala

Fixes https://github.com/scalameta/metals/issues/2561

fix: Add test case for topelevel tuple hover

---

tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/WorkspaceSymbolLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/3689

Fix flaky WorkspaceSymbolLspSuite test

---

docs/contributors/releasing.md

I hope it'll make release instruction easier to follow :)

docs: make release instruction more structured

---

tests/cross/src/test/scala/tests/pc/CompletionScala3Suite.scala

The issue has been fixed in the compiler.
Fixes https://github.com/scalameta/metals/issues/3625

fix: add test case for #3625

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionPos.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

fix: scala3 completion - fix isses with code indented using tabs

---

metals/src/main/scala/scala/meta/internal/metals/MutableMd5Fingerprints.scala

Previously, it was possible that for some files we would not load the current file contents especially with the file was not opened. Now, we will always try fallback to current text.
This might have caused previously a flaky warning related to snapshot text.

Fallback to current file contents always

---

build.sbt

Fixes https://github.com/scalameta/metals/issues/1683

Bump Bloop to the newest version with updated Zinc

---

metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/DoctorExplanation.scala
metals/src/main/scala/scala/meta/internal/metals/DoctorResults.scala
metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

This PR adds `Compilation status` column to the Metals doctor
I have to add some tests (to test both vscode and other clients) but I can't find any doctor-related test suite.

feat: add compilation status to the doctor

---

metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala
metals/src/main/scala/scala/meta/internal/troubleshoot/JavaProblem.scala
metals/src/main/scala/scala/meta/internal/troubleshoot/ProblemResolver.scala
tests/unit/src/test/scala/tests/JavaInteractiveSemanticdbSuite.scala

Warn users properly when wrong release flag was used

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala

Related to https://github.com/scalameta/metals-feature-requests/issues/258

Prefer Scala 2.13 version over older versions

---

docs/editors/vim.md

Signed-off-by: Georg Pfuetzenreuter <mail@georg-pfuetzenreuter.net>
Hi,
I figured this bit needed a little bit of clarification for people not that familiar with Neovim and/or vim-plug, as the configuration file differs, and needs a preceding Plug-call.
Best,
Georg

docs: Neovim and Plug clarification

---

tests/unit/src/test/scala/tests/CancelCompileLspSuite.scala

This is being ignored by people anyway.

Mark CancelCompileLspSuite as flaky

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala

resolves #3762 
https://user-images.githubusercontent.com/93259201/163993958-7f28c45d-5054-4869-bf68-7d31b1ab3267.mov

correct handling of end marker relocation on extract member

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala

fix: create comption object after end marker

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsBuildServer.scala
project/V.scala
tests/unit/src/main/scala/bill/Bill.scala

Fixes the issue with `cs install` - https://github.com/coursier/coursier/issues/2406

upgrade bsp4j version to a stable one

---

website/blog/2022-04-27-aluminium.md

minor release to fix issue with `cs install metals` https://github.com/scalameta/metals/pull/3872

0.11.4 release notes

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala

Previously, we would try to create a presentation compiler even if currently working on a Java file.
Now, we will return default values in case of Java files.
This showed up the mtags-interfaces, which show up as ScalaTargets (might be an issue in Bloop), but it doesn't contain Scala library on the classpath.

Don't create the Presentation Compiler for Java files

---

project/V.scala

This enables running single test case in munit

Update munit to newest milestone

---

sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala
sbt-metals/src/sbt-test/sbt-metals/java-semanticdb-test-srcs/project/plugins.sbt
sbt-metals/src/sbt-test/sbt-metals/java-semanticdb-test-srcs/src/test/java/foo/Bar.java
sbt-metals/src/sbt-test/sbt-metals/java-semanticdb-test-srcs/test

So far, added a test to reproduce the problem. Now, let's see if I can fix it too 🙃 
Edit: done. Fixes https://github.com/scalameta/metals/issues/3903

Add semanticdb-javac to `TestInternal`

---

project/V.scala

This adds support for Scala 3 expression evaluator

Update Bloop and Scala Debug adapter

---

.github/workflows/mtags-auto-release.yml

Started this brnach from v0.11.5 + backported changes from #3932

update `metals_ref` for mtags-release

---

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Previously, we would not take into account sythetics inside for comprehension trees, which could lead to missing decorations inside the yield statement. Now, we recursively go into those trees to get the yield statement.
Fixes https://github.com/scalameta/metals/issues/3938
I recommend reviewing without the whitespaces

Fix issues with synthetics in for comprehension's yield

---

metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala

fix: prevent npe in filewatcher

---

metals/src/main/scala/scala/meta/internal/metals/debug/SourcePathAdapter.scala

Previously, if something wasn't contained in sources set, we would assume that it's a dependency URI. IT seems however that in a rare scenario the set might not contain the specific source path while still being a valid workspace source.
Now, when that is the case we catch it in Try and fall back to just using it as a source.
I managed to reproduce it once, but not again. Not sure why the sources might be missing and it's probably safest to wrap it in Try

bugfix: Fallback to sourcepath if jar cannot be found

---

metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

This was reported by a student on EPFL. JSON doesn't allow for `\`
@tanishiking let's merge this before the release
Fixes https://github.com/scalameta/metals/issues/3968

bugfix: Escape java home path on windows

---

tests/unit/src/main/scala/scala/meta/internal/metals/debug/StepNavigator.scala

Not sure how this sneaked with tests passing in the first place, but this should fix it.

bugfix: Fix failing tests after refactor

---

.github/workflows/scala-steward.yml

Without this it won't be able to find the repos file.

fix: add checkout to steward job

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala
tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala

Fix auto implement abstract members for self-types

---

metals/src/main/scala/scala/meta/internal/metals/MetalsExperimental.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala
tests/unit/src/main/scala/tests/BuildServerInitializer.scala
tests/unit/src/test/scala/tests/QuickBuildSuite.scala

Fixes https://github.com/scalameta/metals/issues/4003
This seems to work, while the object approach looked to not be working before.
@ayoub-benali could you cofirm the fix?

bugfix: Properly send back experimental capabilities

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/FilenameCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionFilenameSuite.scala

Refer to #3952.
I would need some guidance on how I can write the tests by specifying a file name.

[Scala 3] Add file name completions

---

mtags/src/main/scala-3.0/scala/meta/internal/pc/MetalsSignatures.scala
mtags/src/main/scala-3.1/scala/meta/internal/pc/MetalsSignatures.scala
mtags/src/main/scala-3.2/scala/meta/internal/pc/MetalsSignatures.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SignatureHelpProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionBacktickSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpPatternSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala

Fixes tests failures in latest nightly
@tgodzik I rebased your branch

Adjust to signature help changes in scala3 compiler

---

metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/FlatMapToForComprehensionCodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/MetalsNames.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
mtags/src/main/scala-2.11/scala/meta/internal/jdk/CollectionConverters.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ConvertPatternMatchLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/FlatMapToForComprehensionSuite.scala
tests/unit/src/test/scala/tests/codeactions/InsertInferredTypeLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/RewriteBracesParensLspSuite.scala

Resolves https://github.com/scalameta/metals-feature-requests/issues/245#issue-1077898814
Demo:
https://user-images.githubusercontent.com/93259201/166265591-3da32c1a-af7d-434f-812e-ecd2e53ec738.mov
conditions support demo:
https://user-images.githubusercontent.com/93259201/166741364-2e228c01-578a-4678-b40d-5f67067e30ac.mov

flatMap to For Comprehension

---

mtags/src/main/scala-3/scala/meta/internal/pc/SignatureHelpProvider.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpPatternSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala

~~To account for https://github.com/lampepfl/dotty/pull/15517 when it gets merged~~
https://github.com/lampepfl/dotty/pull/15517  was merged!

bugfix: [Scala 3] Adjust changes for the most recent compiler version

---

metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
project/TestGroups.scala
tests/unit/src/test/scala/tests/BloopJavaHomeLspSuite.scala

@kpodsiad this should also fix the issue on windows, what do you think?

bugfix: Change Java home on startup if broken

---

website/blog/2022-07-04-aluminium.md

I totally missed this one and it would be good to properly explain it.

docs: Add missing release notes section

---

website/blog/2022-07-04-aluminium.md

I realzied that the wording here is quite poor and I haven't really explained that there might be some bugs

docs: Fix wording about the expression evaluation

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesIndex.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala

* check if md5 checksum of file changed
* use batched function to prevent race conditions
* additionally, remove unused code

chore: refactor update test cases

---

tests/unit/src/main/scala/tests/BaseRenameLspSuite.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

It seems that at some point we added abstract flga, but never actually created an implementation of that :O

bugfix: Reenable RenameLspSuite

---

.github/workflows/sbt-dependency-graph.yml

Publish full graph of dependencies, on all Scala versions

Bump sbt-dependency-submission

---

metals/src/main/scala/scala/meta/internal/metals/formatting/MultilineString.scala

optimise the call to wasTripleQuoted, so that it would only get called once
remove escaping of " for multilines

Multiline string enhance

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/KeywordsCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala

Solves https://github.com/scalameta/metals/issues/4182

Add match keyword completion

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/ScalaVersionSelector.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
mtags/src/main/scala-3/scala/meta/internal/pc/IndexedContext.scala
project/V.scala
tests/cross/src/main/scala/tests/BaseAutoImportsSuite.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala
tests/slow/src/test/scala/tests/feature/AmmoniteSuite.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala

Fixes https://github.com/scalameta/metals/issues/3071

feature: Update Ammonite runner for Scala 3 and latest Scala 2 versions

---

metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/4228

bugfix: Remove worksheet diagnostics on close

---

mtags/src/main/scala-2/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala

This reverts commit 6bf55ab632a900331720fd5f04e916596a3311f6 (PR https://github.com/scalameta/metals/pull/4236) that reverted the following PRs
- https://github.com/scalameta/metals/pull/4174
- https://github.com/scalameta/metals/pull/4223

Revert "[Scala 3] Revert type completions feature (#4236)"

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/NamedArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionScala3Suite.scala

Adds autofill named arguments with default values completion and completions for single named arguments, the same way we have for scala2.

Add autofill named arguments completion for scala3

---

project/V.scala
tests/unit/src/test/scala/tests/JavaDefinitionSuite.scala

https://github.com/eclipse/lsp4j/releases/tag/v0.15.0

Bump LSP4j to 0.15.0 that adds notebook support

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala

chore: mark buildTarget/javacOptions as unsupported for ammonite

---

.github/workflows/check_scala3_nightly.yml
build.sbt
project/Scala3NightlyVersions.scala

I decided to finally stop fixing the exiting logic written on a bash and
replaced it by a sbt command.

fix: check_scala3_nightly - switch from bash on Scala

---

mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala

The issues caused by https://github.com/lampepfl/dotty/pull/15877

chore: Fix nightlies after recent changes

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ConvertToNamedArguments.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ConvertToNamedArgumentsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ConvertToNamedArgumentsProvider.scala
tests/cross/src/test/scala/tests/pc/ConvertToNamedArgumentsSuite.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ConvertToNamedArgumentsLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ExtractValueLspSuite.scala

fixes https://github.com/scalameta/metals/issues/4276

fix ConvertToNamedArg for constructor invocations

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionBuilder.scala

I realized it is the opposite condition.

bugfix: Fix wrong condition for logging in CodeActionBuilder

---

.github/workflows/scala-steward.yml

https://github.com/scalameta/metals/issues/4333#issuecomment-1236264927

 fix: scala-steward cron (again)

---

metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala

I realized that it's hard for people to find it and this is the simples way to expose it.

feature: Add Analyze Stacktrace command to metals menu

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

- fixes completion for term symbol that aren't method
- allow object at type completion pos
should include a fix for #4224

fix: type completions additonal fixes

---

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala
mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
mtags/src/main/scala/scala/meta/internal/mtags/GlobalSymbolIndex.scala
mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala
mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala
tests/slow/src/test/scala/tests/feature/DefinitionCrossLspSuite.scala
tests/unit/src/main/scala/tests/ScriptsAssertions.scala

fix: scala3 - provide a correct defitions for symbols from `stdLibPatched` package

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

- Update the branch that handle file deletion on the `didChangeWatchedFiles`
- Create a new `onDelete` function that compiles the project
#4216

Compile project on file deletion

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Previously, we would only check if import was run manually and not check if it was run via message request. Now, we should not run import if the one from message request is already running.

bugfix: Always check if import is in progress

---

project/V.scala

Most recent version release failed and didn't manage to publish some of the artifacts:
https://github.com/com-lihaoyi/Ammonite/actions/runs/3060243875/jobs/4938520111

bugfix: Revert ammonite to 2.5.4-22-4a9e6989

---

project/V.scala

Ammonite has been released for those versions now.

chore: Bump Scala versions for Ammonite

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala-3.1/scala/meta/internal/pc/MetalsSealedDesc.scala
mtags/src/main/scala-3.2/scala/meta/internal/pc/MetalsSealedDesc.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala

fix https://github.com/scalameta/metals/issues/4430

Don't show private members in case completions

---

metals/src/main/scala/scala/meta/internal/builds/BloopInstall.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Moves `isImportInProgress` flag check to runUnconditionally, so setting the flag to `false` happens before compilation.

move isImportInProgress to runUnconditionally

---

build.sbt
tests/cross/src/main/scala/tests/BaseCompletionSuite.scala
tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionParameterHintSuite.scala
tests/cross/src/test/scala/tests/pc/MacroCompletionSuite.scala

This is needed to run Metals in the community suite.
@SethTisue This should allow running the tests in nightlies

chore: Allow to run tests with Scala nightlies

---

project/V.scala
tests/unit/src/main/scala/tests/QuickBuild.scala

Fixes https://github.com/scalameta/metals/issues/4449

chore: Update Bloop to newest version

---

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
metals/src/main/scala/scala/meta/internal/tvp/ScalacpCopyPaste.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala

Not adding any tests yet, since the feature is still not approved via SIP, but we will not get any errors thanks to this.

feature: Enable fewer braces for Scala 3 nightly versions

---

mtags/src/main/scala-2/scala/meta/internal/pc/ConvertToNamedArgumentsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ConvertToNamedArgumentsProvider.scala
tests/cross/src/test/scala/tests/pc/ConvertToNamedArgumentsSuite.scala

Add backticks where needed in "convert to named arguments"

---

project/Developers.scala

Jakub has contributed a lot of the features included in the last release including match case completions and extract method code action, which are clearly some amzing features.
I am happy to welcome him to the team!
@jkciesluk Feel free to merge when you feel like it!

chore: Welcome Jakub to the team

---

bin/merged_prs.sc
website/blog/2022-10-06-aluminium.md

This will also be useful for the release notes in VS Code and makes it similar to the default release notes.
I also added an example in the template generation.

feature: Add links for easier navigation in the blogpost

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/MillIvyCompletions.scala
mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
tests/cross/src/test/scala/tests/pc/CompletionMillIvySuite.scala

Adds completions for `ivy"dependency@@"` in `build.sc` file

Add mill ivy completions

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/SbtLibCompletions.scala
mtags/src/main/scala/scala/meta/internal/mtags/CoursierComplete.scala
tests/cross/src/main/scala/tests/BaseCompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSbtLibSuite.scala

Adds completions for dependencies in `.sbt` files

Add sbt lib completions

---

tests/unit/src/main/scala/tests/BaseScalaCliSuite.scala

In the meantime I am slowly working on figuring it out.

bugfix: Set connecting-scalacli test as flaky

---

metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/4554

bugfix: Also rename companion when renaming renamed import

---

project/V.scala

This new major version of the scala-debug-adapter brings a number of new features including:
- Step filtering for Scala 2 and Scala 3
- Better expression evaluation for Scala 3
- Configuration of the ScalacOptions of the expression compiler
- Show returned value of method call
- Log-points
- Conditional breakpoints
- Restart top frame of the call stack
- Filtering of class loading
To learn more about those new features you can refer to the [release notes](https://github.com/scalacenter/scala-debug-adapter/releases/tag/v3.0.1)

Use new scala-debug-adapter 3

---

mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala

Fixes #4357
Related changes #3632

Fix go to in external classes in jars with special chars

---

mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala

fixes https://github.com/scalameta/metals/issues/4591

fix: exhaustive match on renamed symbol

---

mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala

Resolves #4570
I have same issue described in https://github.com/scalameta/metals/pull/4560#issuecomment-1288173038
It's a workaround. It's still not clear where the root issue.

Workaround fix for double escaping % for jar URIs

---

mtags/src/main/scala/scala/meta/internal/mtags/CoursierComplete.scala

fixes https://github.com/scalameta/metals/issues/4593

bugfix: Deduplicate coursier completions

---

metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala

Instead of creating a temp dir for millw for Mill users this instead
uses a more stable location of just sticking it in `.metals/millw`. This
_should_ help with some changes coming in Mill and millw spawning from https://github.com/com-lihaoyi/mill/discussions/2079.

refactor: change where we stick millw

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcDocumentHighlightProvider.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala

Moved from https://github.com/scalameta/metals/pull/4542

bugfix: Highlight for named arg in case class constructors

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala

fixes https://github.com/scalameta/metals/issues/4082

fix: implementAll with type aliases and higher kind type

---

mtags/src/main/scala/scala/meta/internal/mtags/CoursierComplete.scala
tests/cross/src/test/scala/tests/pc/CompletionScalaCliSuite.scala

Fixes https://github.com/scalameta/metals/issues/4594

feature: Add completions for plugins in ScalaCLI

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala

fixes https://github.com/scalameta/metals/issues/4636

fix: prevent NPE in import missing symbol code action

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/ShortenedNames.scala
tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala

Fixes https://github.com/scalameta/metals/issues/4668

fix: implement methods with path-dependent type arguments

---

tests/cross/src/test/scala/tests/pc/CompletionScalaCliSuite.scala

this came up over at scala/community-build#1618

exempt Scala nightlies from a test

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/StringActions.scala
tests/unit/src/test/scala/tests/codeactions/StringActionsLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/4678

bugfix: Take into account the length of interpolator

---

metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
tests/unit/src/test/scala/tests/ScalaVersionsSuite.scala

Recommend newer RC Scala versions when project is using a RC

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/main/scala/tests/BaseDocumentHighlightSuite.scala
tests/cross/src/test/scala/tests/highlight/Scala3DocumentHighlightSuite.scala

Highlight using presentation compiler wasn't working correctly for extension method parameter

fix highlight for extension methods

---

metals/src/main/scala/scala/meta/internal/implementation/Supermethods.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/callHierarchy/CallHierarchyItemInfo.scala
metals/src/main/scala/scala/meta/internal/metals/callHierarchy/CallHierarchyProvider.scala
tests/unit/src/test/scala/tests/CallHierarchyLspSuite.scala

Resolves https://github.com/scalameta/metals/issues/4488

Call hierarchy incoming calls include also incoming calls of super methods

---

metals/src/main/scala/scala/meta/internal/metals/callHierarchy/CallHierarchyHelpers.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/FlatMapToForComprehensionCodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/InsertInferredType.scala
project/TestGroups.scala
project/V.scala
tests/input/src/main/scala/example/MacroAnnotation.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala
tests/unit/src/main/scala/tests/BaseCallHierarchySuite.scala
tests/unit/src/test/resources/definition/example/MacroAnnotation.scala
tests/unit/src/test/resources/documentSymbol/example/MacroAnnotation.scala
tests/unit/src/test/resources/mtags/example/MacroAnnotation.scala
tests/unit/src/test/resources/semanticdb/example/MacroAnnotation.scala
tests/unit/src/test/resources/workspace-symbol/example/MacroAnnotation.scala
tests/unit/src/test/scala/tests/CallHierarchyLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/4584

chore: Bump Scalameta to 4.7.0

---

metals/src/main/scala/scala/meta/internal/metals/JavaDocumentHighlightProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala
tests/unit/src/test/scala/tests/DocumentHighlightLspSuite.scala

Bring back previous document highlighting mechanism for Java files

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/metals/Main.scala
metals/src/main/scala/scala/meta/metals/MetalsLanguageServer.scala

closes https://github.com/scalameta/metals/issues/4828
@ckipp01 can you try this?

fix: properly shut down Metals server

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala

PReviously, we would not log issues with BSP if there was no failure handler defiend for a particular request. Now, we properly log it with a default message.

improvement: Always log issues with BSP requests

---

mtags/src/main/scala-2/scala/meta/internal/pc/SemanticTokenProvider.scala

These are two small changes which greatly improve performance of `SemanticTokensProvider` on big files.
First change is using shared `nodesIterator`. Both lists of tokens and symbols are sorted, so we can advance in them in parallel instead of going through the whole list each time.
Second change is using `SortedSet` for collecting `NodeInfo`.

improvement: Improve performance of `SemanticTokens`

---

metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala

fix: ensure doctor reports that diagnostics in sbt targets work

---

project/V.scala

We won't have to remoev and add it to the list anymore, just set it
to None when there is none.

refactor: make scala3RC easier to work with

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala

fixes https://github.com/scalameta/metals/issues/4869

fix: Implement all members for case classes in Scala 3

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala

fixes https://github.com/scalameta/metals/issues/4869
continuation of https://github.com/scalameta/metals/pull/4923
As mentioned in the comment in the issue above
```scala
sealed trait Demo {
def implementMe: Int
}
case class <<ADemo>>(value: Int) extends Demo
```
path to `ADemo` starts with `method apply` and is followed by `TypeDef ADemo$`. We have to find definition tree `TypeDef ADemo` using fallback method.
If companion object is defined, the `apply` method is moved there and path is correct.

fix: Fix insert abstract members for case classes in scala 3

---

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
tests/unit/src/test/scala/tests/ImplementationLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/4945

bugfix: Also accept interfaces for go to implementation

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
tests/unit/src/test/scala/tests/RenameFilesLspSuite.scala

Connected to https://github.com/scalameta/metals/issues/4888

bugfix: Don't change packages in files if they move outside workspace

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala

Improves exhaustive match completion for intersections and union types.

improvement: Add better exhaustive completions for &, | types

---

mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala

Removes leftover method from https://github.com/scalameta/metals/pull/4954, so it doesn't depend on scalameta
https://github.com/scalameta/metals/pull/4954/files#diff-082b8a291ea56c1da81d068ffff542d31e47a7f3c015560fb3cdc7e2031ad474L112

fix: remove leftover from PR #4954

---

metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala
sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala

My Java home is  `~/.cache/coursier/jvm/adopt@1.8.0-275/jre` and `MetalsPlugin` could not find the associated JDK version.
This fixes the bug:
- try to read the `$javaHome/../release` file if the `$javaHome/release` file does not exist
- try to read the `$javaHome/lib/rt.jar` file if the `$javaHome/jre/lib/rt.jar` does not exist.

[sbt-metals] Fix JDK version when Java home is jre folder

---

tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

Adds a test to close https://github.com/scalameta/metals/issues/4730

improvement: Add test for type completion out of scope

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
metals/src/main/scala/scala/meta/internal/worksheets/DecorationWorksheetPublisher.scala
metals/src/main/scala/scala/meta/internal/worksheets/MdocEnrichments.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorkspaceEditWorksheetPublisher.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/4886

bugfix: strip ANSI colours before printing worksheet results

---

metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala

I got a frozen Metals instance and it seems to have been stuck on cancel:
```
java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait(java.base@17.0.2/Native Method)
- waiting on
at java.lang.Object.wait(java.base@17.0.2/Object.java:338)
at sun.nio.fs.AbstractPoller$Request.awaitResult(java.base@17.0.2/AbstractPoller.java:201)
- locked <0x00000000d7e62158> (a sun.nio.fs.AbstractPoller$Request)
at sun.nio.fs.AbstractPoller.invoke(java.base@17.0.2/AbstractPoller.java:230)
at sun.nio.fs.AbstractPoller.cancel(java.base@17.0.2/AbstractPoller.java:138)
at sun.nio.fs.LinuxWatchService$LinuxWatchKey.cancel(java.base@17.0.2/LinuxWatchService.java:136)
at com.swoval.files.NioPathWatcherService$CachedWatchDirectory.close(NioPathWatcherService.java:126)
at …
```

improvement: Force closing thread if file watching cancel hanged

---

mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompletionItemResolver.scala
mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/IndexedContext.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/ShortenedNames.scala
tests/cross/src/test/scala/tests/hover/HoverDefnSuite.scala

resolves: https://github.com/scalameta/metals/issues/4686

bugfix: dealias applied type params

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala

Previously, while typing, if file ended with `def@@`, we would get index out of range.

fix: Check if span in def is correct

---

project/Developers.scala

Kasia has contributed a lot of new features and bugfixes across the repository including inline code action and extending workspace search to also find defs/vals/vars/types to name a few.
I am happy to welcome her to the team!
@kasiaMarek feel free to accept the invitation to the team and merge at your convenience :tada:

docs: Welcome Kasia to the team

---

mtags/src/main/scala-2/scala/meta/internal/pc/SignatureHelpProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/Signatures.scala
tests/cross/src/test/scala/tests/pc/HKSignatureHelpSuite.scala

Connected to https://github.com/scalameta/metals/issues/5055
We still need to fix sgnature help for Scala 3.

bugfix: Fix wrong default when named params are mixed

---

metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala

Previously, when sbt was available on the classpath `sbt bspConfig` would generate additional `-Dsbt.script` with spaces encoded, which would break running bsp server.
Now, we remove that property on Windows, which doesn't seems to cause any issues, since the boot jar is enough to start a server.
Fixes https://github.com/scalameta/metals/issues/5027
Another weird Windows whitespace issue :sweat:

bugfix: Fix running BSP sbt when it's installed in a directory with space

---

metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala
tests/unit/src/test/scala/tests/RenameFilesLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/5119

bugfix: add newline in new imports when moving files

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
tests/unit/src/main/scala/tests/BaseRenameFilesLspSuite.scala
tests/unit/src/test/scala/tests/RenameFilesLspSuite.scala

previously: when fixing imports for a moved file wildcard imports where not handled
now: wildcard imports are also handled
resolves: https://github.com/scalameta/metals/issues/4739

bugfix: handling wildcard imports for file rename

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala

Reload sbt after writing metals plugin

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags-shared/src/main/scala/scala/meta/internal/metals/ReportContext.scala
mtags/src/main/scala-2/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompilerSearchVisitor.scala
mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/unit/src/test/scala/tests/ReportsSuite.scala

Create a report when hover returns an empty result when metals in debug mode.
connected to: https://github.com/scalameta/metals/issues/5061

improvement: report on an empty hover

---

mtags/src/main/scala/scala/meta/internal/mtags/JavaToplevelMtags.scala
mtags/src/main/scala/scala/meta/internal/mtags/Mtags.scala
tests/unit/src/main/scala/tests/Library.scala
tests/unit/src/test/scala/tests/JavaToplevelSuite.scala
tests/unit/src/test/scala/tests/ToplevelLibrarySuite.scala

Implements a lighter version of java parser for extracting toplevel definitions as we do in Scala
Should fix #3815

feature: properly index Java sources

---

mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala

Follow up from https://github.com/scalameta/metals/pull/5042

improvement: Reduce IO when querying if file exists

---

architecture.md

Update docs after https://github.com/scalameta/metals/pull/5033.

docs: Update `architecture.md` after adding support for multi root

---

tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Add test to close  https://github.com/scalameta/metals/issues/4879

fix: Add test for arg completions with second arg first

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala

connected to: https://github.com/scalameta/metals/issues/2496

Backtick types

---

metals/src/main/scala/scala/meta/internal/metals/clients/language/ConfiguredLanguageClient.scala

During refreshing semantic tokens

improvement: Log message while unexpected error happens.

---

mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-2/scala/meta/internal/pc/HoverProvider.scala
tests/cross/src/test/scala/tests/hover/HoverDefnSuite.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

solves https://github.com/scalameta/metals/issues/2471

fix: Show hover when cursor is right after symbol

---

.github/workflows/ci.yml
build.sbt
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
mtags-java/src/main/scala/scala/meta/internal/pc/CursorPosition.scala
mtags-java/src/main/scala/scala/meta/internal/pc/Descriptor.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaHover.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaHoverProvider.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaMetalsGlobal.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaPresentationCompiler.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaTreeScanner.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaTypeVisitor.scala
mtags-java/src/main/scala/scala/meta/internal/pc/SourceJavaFileObject.scala
mtags-shared/src/main/scala/scala/meta/internal/pc/HoverMarkup.scala
project/JavaPcSettings.scala
tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/javapc/src/main/scala/tests/pc/BaseJavaHoverSuite.scala
tests/javapc/src/main/scala/tests/pc/BaseJavaPCSuite.scala
tests/javapc/src/test/scala/hover/HoverDefnSuite.scala
tests/javapc/src/test/scala/hover/HoverDependencySuite.scala
tests/javapc/src/test/scala/hover/HoverDocSuite.scala
tests/javapc/src/test/scala/hover/HoverTermSuite.scala
tests/mtest/src/main/scala/tests/PCSuite.scala
tests/mtest/src/main/scala/tests/TestHovers.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala

I’ve implemented a java hover feature for metals. My approach is based on building a java semantic tree via jdk compiler, then just going through this tree and fetching all necessary info for showing hover of a java element. I’ve already tested metals build with this feature on simple java sources. There are some examples:

Java hover

---

docs/contributors/updating-website.md

Edit button is actually at the bottom of the website

website fix

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala

This seems to me impossible, but it happened in https://github.com/scalameta/metals/issues/5277
Let's see if this helps.

bugfix: Make sure we don't fail when restarting the compiler

---

metals/src/main/scala/scala/meta/internal/builds/Digests.scala
metals/src/main/scala/scala/meta/internal/metals/DependencySources.scala
metals/src/main/scala/scala/meta/internal/metals/Fingerprints.scala
metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/Tables.scala
metals/src/main/scala/scala/meta/internal/metals/WorksheetDependencySources.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala
tests/unit/src/test/scala/tests/ResetWorkspaceLspSuite.scala

This command removes directories in .bloop, cleans most tables and restarts bloop server

feat: Add clean-all command

---

mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala

solves in metals: https://github.com/scalameta/metals/issues/5308

bugfix: make sure tmpl point is within source file bounds

---

metals/src/main/scala/scala/meta/internal/metals/SemanticTokensProvider.scala
tests/unit/src/test/scala/tests/SemanticTokensLspSuite.scala

Using directives allow values not wrapped in double quotes, and we should highlight them the same way
connected to https://github.com/VirtusLab/scala-cli/issues/2178

improvement: Semantic highlight for using directives

---

mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala

Connected to https://github.com/scalameta/metals/issues/5356

bugfix: Properly check symbol before invoking owner

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/unit/src/test/resources/workspace-symbol/example/ImplicitClasses.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

resolves: https://github.com/scalameta/metals/issues/5354

bugfix: emit symbols for vals in constructors

---

metals/src/main/scala/scala/meta/internal/metals/CompilerPlugins.scala

Fixes #5367
Required to support Mill `0.11`

Fix #5367: Support comma-separated paths in -Xplugin

---

mtags-shared/src/main/scala/scala/meta/internal/pc/CompilerAccess.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaCompilerAccess.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Scala3CompilerAccess.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala

connected to: https://github.com/scalameta/metals/issues/5217

improvement: Add error reports upon compiler access error

---

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala

Add restart build sever for `sbt` build server. Connected to: https://github.com/scalameta/metals/issues/5313

Improvement: restart sbt server

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala

fixes https://github.com/scalameta/metals/issues/5408

fix: Implement all members with end marker

---

metals/src/main/scala/scala/meta/internal/metals/ScalafmtConfig.scala
tests/unit/src/test/scala/tests/ScalafmtConfigSuite.scala

resolves: https://github.com/scalameta/metals/issues/5363

bugfix: adjust parsing `ScalafmtConfig` for `StandardConvention` layout

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala
mtags/src/main/scala/scala/meta/internal/metals/MetalsSymbolDocumentation.scala
tests/cross/src/test/scala/tests/hover/HoverDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala

Now, if docstring on apply method is empty, we try docstrings about object and case class, in that order

improvement: Docstring on apply method

---

mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala

resolves: https://github.com/scalameta/metals/issues/5486

bugfix: hover on nested selectable

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
metals/src/main/scala/scala/meta/internal/metals/ServerLivenessMonitor.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/DoctorResults.scala
tests/unit/src/main/scala/bill/Bill.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/test/scala/tests/ServerLivenessMonitorSuite.scala

Ping the server every minute and if it sends no response/sends no notifications in two minutes inform the user that it may need to be restarted.

improvement: monitor build server liveness

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/BuildTargetUpdate.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesIndex.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/JunitTestFinder.scala
tests/unit/src/test/scala/tests/testProvider/TestSuitesProviderSuite.scala

resolves: https://github.com/scalameta/metals/issues/5378

bugfix: accommodate junit encoded test names

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/Scala3DocumentHighlightSuite.scala

resolves: https://github.com/scalameta/metals/issues/5504

bugfix: highlight enum cases correctly

---

mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
tests/unit/src/test/scala/tests/MetalsEnrichmentsSuite.scala

Fix #5518: don't decode nor encode URIs

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/NamedArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

resolves: https://github.com/scalameta/metals/issues/5484

bugfix: suggest correct arg name completions for lambda expressions

---

mtags/src/main/scala/scala/meta/internal/mtags/DefinitionAlternatives.scala
tests/unit/src/test/resources/definition-scala3/example/NamedArguments.scala
tests/unit/src/test/resources/definition/example/NamedArguments.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala

closes https://github.com/scalameta/metals/issues/5510

fix: Go to definition for named constructor params

---

tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

Unignore tests after https://github.com/lampepfl/dotty/pull/18380.

chore: unignore tests for dotty pc after c90ad6b

---

metals/src/main/scala/scala/meta/internal/builds/BSPErrorHandler.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/test/scala/tests/BspErrorHandlerSuite.scala

resolves: https://github.com/scalameta/metals/issues/5629

improvement: have `Dismiss.` remember the bsp error and don't show it again

---

mtags-java/src/main/scala/scala/meta/internal/pc/JavaCompletionProvider.scala
mtags/src/main/scala/scala/meta/internal/mtags/JavaToplevelMtags.scala
tests/javapc/src/test/scala/pc/CompletionKeywordSuite.scala

resolves: https://github.com/scalameta/metals/issues/5599

bugfix: handle EOF in java completions

---

metals/src/main/scala/scala/meta/internal/builds/ScalaCliBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala

~I'm hoping this will help with flaky scala-cli tests.~  Evidently, not really.

bugfix: deduplicate auto connect requests for scala-cli

---

metals-docs/src/main/scala/docs/WorksheetModifier.scala

Fixes https://github.com/scalameta/metals/issues/2764

docs: Document AnyVal as not supported in worksheets

---

tests/cross/src/test/scala/tests/pc/CompletionMillIvySuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSbtLibSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionScalaCliSuite.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

This shouldn't happen too often.

bugfix: Fix completions tests after a new artifact starting with io.circ showed up

---

mtags-shared/src/main/scala/scala/meta/internal/mtags/CoursierComplete.scala
tests/cross/src/test/scala/tests/pc/CompletionMillIvySuite.scala
tests/cross/src/test/scala/tests/pc/CompletionScalaCliSuite.scala

Double colon before version is allowed only if there is also double colon before artifact
fixes https://github.com/scalameta/metals/issues/5717

bugfix: Dependency completions with double colon before version

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/MultilineCommentCompletion.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MultilineCommentCompletion.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

resolves: https://github.com/scalameta/metals/issues/5731

bugfix: add multiline comment completion

---

metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
tests/unit/src/test/scala/tests/DidFocusLspSuite.scala

connected to: https://github.com/scalameta/metals/issues/5759

improvement: recompile focused file if depends on last compiled bt

---

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/ScaladocDefinitionProvider.scala
tests/slow/src/test/scala/tests/feature/DefinitionCrossLspSuite.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala
tests/unit/src/test/scala/tests/ScaladocSymbolsSuite.scala

https://github.com/scalameta/metals/issues/5736

feature: add go to definition for scaladoc

---

build.sbt
mtags/src/main/scala-2.13.5/meta/internal/pc/Compat.scala
mtags/src/main/scala-2.13.6/meta/internal/pc/Compat.scala
mtags/src/main/scala-2.13.7/meta/internal/pc/Compat.scala
mtags/src/main/scala-2.13.8/meta/internal/pc/Compat.scala
mtags/src/main/scala-2.13/scala/meta/internal/pc/Compat.scala

https://github.com/scala/community-build/pull/1700#issuecomment-1783603649

chore: fix ci tests for 2.13.13

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
metals/src/main/scala/scala/meta/internal/metals/JavaTarget.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/TargetData.scala

There are two issues that we can quickly help with Gradle BSP:
- we should check if dependency sources are supported
- we should make sure that the class directory is a non empty string
We would still need much more to support it here, but it's a start.

chore: Minor refactor to help with edge cases in BSP

---

tests/javapc/src/test/scala/hover/HoverDocSuite.scala
tests/mtest/src/main/scala/tests/BaseSuite.scala

resolves: https://github.com/scalameta/metals/issues/5800

test: fix hover doc suite for jdk22

---

mtags/src/main/scala-3-wrapper/ScalaPresentationCompiler.scala

fix pc wrapper after: https://github.com/lampepfl/dotty/commit/e149e4c62206088d18e82b8b41932abc2a28f19d

fix: pc wrapper for dotty nightly

---

tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Looks like this sneaked in between the 2.11 PR and now

bugfix: Fix formatting after merge

---

tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala

It broke in https://github.com/scalameta/metals/pull/5844

chore: Fix decoration test for sbt

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcSyntheticDecorationsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcSyntheticDecorationProvider.scala
tests/cross/src/test/scala/tests/pc/SyntheticDecorationsSuite.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala

closes https://github.com/scalameta/metals/issues/5855

bugfix: Remove synthetic decorations for script wrapper

---

metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala

When running `scala-cli bsp` for scripts set `--workspace` arg to a tmp directory. On Windows if tmp dir and script roots are different fallback to creating `.metals-scala-cli` next to the script and delete on metals shutdown.

improvement: create `scala-cli` `.scala-build` in a tmp directory

---

tests/unit/src/test/scala/tests/NewProjectLspSuite.scala

If it happens more we'll switch to a more stable template

bugfix: Fix tests for new file provider due to changed template

---

tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Together with the changes to the compiler this should make the tests pass

bugfix: Fix some of the tests in the nightly CI

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcSyntheticDecorationsProvider.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/4970

bugfix: don't show implicit conversions for synthetics

---

tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala

Fixes https://github.com/scalameta/metals/issues/5916

chore: Ignore docs suite on Scala 2 nightlies

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala
tests/cross/src/test/scala/tests/tokens/SemanticTokensScala3Suite.scala
tests/cross/src/test/scala/tests/tokens/SemanticTokensSuite.scala

closes https://github.com/scalameta/metals/issues/5877

bugfix: Document highlight on generic class init in scala 3

---

mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/Scala3DocumentHighlightSuite.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala
tests/cross/src/test/scala/tests/pc/PcDefinitionSuite.scala

resolves: https://github.com/scalameta/metals/issues/5921

bugfix: fix workaround for wrong spans in extension method call

---

mtags-shared/src/main/scala/scala/meta/internal/pc/ExtractMethodUtils.scala
tests/cross/src/test/scala/tests/pc/ExtractMethodSuite.scala

resolves: https://github.com/scalameta/metals/issues/5936

fix: extract method with empty lines

---

bin/update-millw.sh
metals/src/main/resources/millw
metals/src/main/resources/millw.bat

There were a few fixes recently, the main one fixes Mill BSP import on Windows
https://github.com/lefou/millw?tab=readme-ov-file#millw-0411---2023-12-18
Fixes https://github.com/scalameta/metals/issues/5953

Update millw to 0.4.11

---

metals-docs/src/main/scala/docs/Snapshot.scala

Fixes https://github.com/scalameta/metals/issues/5952

bugfix: Retry check for the latest Metals version

---

metals/src/main/scala/scala/meta/internal/metals/MtagsResolver.scala

Previously, we would log an error and then try to download stable presentation compiler, which could be misleading. Now we only print an error if we fail to resolve any mtags.

improvement: Only log if failed to resolve mtags at all

---

metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala
tests/slow/src/test/scala/tests/feature/CrossAnalyzeStacktraceSuite.scala

Extracted from https://github.com/scalameta/metals/pull/5197

bugfix: Fix StacktraceAnalyser in case of empty package

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/InterpolatorCompletions.scala

Error 16 reported from Scastie using reporting mechanisms

bugfix: Don't call tail on an empty list

---

mtags/src/main/scala-3/scala/meta/internal/pc/CompilerSearchVisitor.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

resolves: https://github.com/scalameta/metals/issues/5992

bugfix: don't show given classpath search completions

---

tests/slow/src/test/scala/tests/bazel/BazelLspSuite.scala

Adjusts tests after merging https://github.com/scalameta/metals/pull/6020

chore: Adjust bazel tests

---

project/V.scala
tests/cross/src/test/scala/tests/pc/CompletionExtensionMethodSuite.scala
tests/cross/src/test/scala/tests/pc/HKSignatureHelpSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpPatternSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala

https://github.com/lampepfl/dotty/pull/19214

chore: test changes for upcoming changes in nightly

---

metals/src/main/scala/scala/meta/internal/metals/FileSystemSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
mtags/src/main/scala/scala/meta/internal/mtags/SemanticdbClasspath.scala
mtags/src/main/scala/scala/meta/internal/mtags/Semanticdbs.scala
tests/slow/src/test/scala/tests/scalacli/CodeLensesScalaCliSuite.scala

resolves: https://github.com/scalameta/metals/issues/6017

bugfix: show code lenses when shebang for Scala 2

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/DidFocusLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/5970

don't always trigger compilation on `didOpen`

---

metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClasses.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/MunitTestFinder.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/TreeUtils.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/WeaverCatsEffectTestFinder.scala
tests/unit/src/main/scala/tests/QuickBuild.scala
tests/unit/src/test/scala/tests/testProvider/TestSuitesProviderSuite.scala

resolves: https://github.com/scalameta/metals/issues/6052

improvement: add support for weaver cats effects

---

mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/Scala3DocumentHighlightSuite.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala
tests/cross/src/test/scala/tests/tokens/SemanticTokensScala3Suite.scala

fixes https://github.com/scalameta/metals/issues/6041

bugfix: Document highlight on extension methods with implicit arguments

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala

fixes https://github.com/scalameta/metals/issues/6067

bugfix: Extension completions in interpolated strings

---

tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala

https://github.com/scalameta/metals/issues/6083

chore: Mark scala CLI script test as flaky

---

metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala
metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala

resolves: https://github.com/scalameta/metals/issues/3153
The user might still need to add some ssl verification to global git config.

bugfix: pass proxy info to g8

---

tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

https://github.com/lampepfl/dotty/pull/19617

chore: unignore tests after backport to dotty

---

metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala

resolves: https://github.com/scalameta/metals/issues/6102

bugfix: don't rename package when it did not change

---

docs/build-tools/bazel.md
docs/build-tools/overview.md
website/i18n/en.json
website/sidebars.json

docs: Add warning about Bazel 7.0.0 and add bazel to sidebar

---

build.sbt
metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala
project/V.scala

Fixes https://github.com/scalameta/metals/issues/6146

improvement: Bump giter8 and make sure it gets updated automatically

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSearchVisitor.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
tests/unit/src/main/scala/scala/meta/internal/metals/debug/StepNavigator.scala

resolves: https://github.com/scalameta/metals/issues/6155

bugfix: make symbol search prefer results with scala version of document in focus

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/OrganizeImports.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliActionsSuite.scala

Fixed by https://github.com/scalacenter/scalafix/pull/1901

improvement: Allow running organize imports on scripts

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala

Error 01.11 reported from Scastie using reporting mechanisms

bugfix: Don't ask for override completions on null type

---

mtags-shared/src/main/scala/scala/meta/internal/pc/InterpolationSplice.scala

Error 02.05 reported from Scastie using reporting mechanisms

bugfix: Add additional check for InterpolatorSplice substring

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/InterpolatorCompletions.scala

Error reported from Scastie using reporting mechanisms

bugfix: Don't call tail on empty list

---

mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala

Error 03.06 reported from Scastie using reporting mechanisms

bugfix: Hover on not assigned type

---

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala

resolves: https://github.com/scalameta/metals/issues/6252

improvement: turn off formatting for `metals.sbt`

---

docs/troubleshooting/faq.md
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
tests/unit/src/test/scala/tests/worksheets/WorksheetInfiniteLoopSuite.scala

resolves: https://github.com/scalameta/metals/issues/4796

improvement: add timeout to worksheet evaluation

---

metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala
metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/DoctorResults.scala
tests/unit/src/test/scala/tests/JavaInteractiveSemanticdbSuite.scala

Add information about java used for project to doctor.

improvement: add project's java info to doctor

---

tests/unit/src/test/scala/tests/JdkVersionSuite.scala

I added `full` version string to JdkVersion, but that is only for `Doctor`.

test: fix JDK version test

---

metals/src/main/scala/scala/meta/internal/builds/BazelBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala

This is useful for testing locally

chore: Add all repos when resolving bazel

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Error 03.14 reported from Scastie using reporting mechanisms

bugfix: Arg completions on null symbol in Scala 2

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcInlayHintsProvider.scala
tests/cross/src/test/scala/tests/pc/InlayHintsScala3Suite.scala
tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala

Also moves Scala 3 specific inlay hints tests to separate suite
closes https://github.com/scalameta/metals/issues/6178

bugfix: Incorrect inlay hints inside quotes

---

metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala
tests/unit/src/test/scala/tests/RenameFilesLspSuite.scala

fixes: https://github.com/scalameta/metals/issues/6297

fix: don't remove package when target outside of root

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/mtags-auto-release.yml
bin/merged_prs.scala
build.sbt
website/blog/2024-04-11-thalium.md

chore: Add release notes for Metals 1.3.0

---

metals/src/main/scala/scala/meta/internal/builds/BloopInstallProvider.scala
metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
tests/slow/src/test/scala/tests/gradle/GradleLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/6253

fix: remove stale config files before `bloopInstall` for gradle

---

metals/src/main/scala/scala/meta/internal/builds/BloopInstall.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/WorkspaceReload.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

connected to: https://github.com/scalameta/metals/actions/runs/8738313853/job/23977093270?pr=6303#step:4:1997

fix: retry calculating build tool digest

---

docs/editors/overview.md
docs/troubleshooting/faq.md
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
tests/unit/src/test/scala/tests/worksheets/WorksheetInfiniteLoopSuite.scala

connected to: https://github.com/scalameta/metals/issues/4796#issuecomment-2067717984

improvement: add worksheet timeout setting

---

metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala
metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/FallbackMetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/FileSystemSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceFolders.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCliServers.scala
metals/src/main/scala/scala/meta/metals/MetalsLanguageServer.scala
tests/slow/src/test/scala/tests/gradle/GradleLspSuite.scala
tests/slow/src/test/scala/tests/maven/MavenLspSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala
tests/unit/src/main/scala/tests/BuildServerInitializer.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/SingleFileSuite.scala

mostly moved from: https://github.com/scalameta/metals/pull/5531
missing: https://github.com/scalameta/metals/pull/5531/commits/c9aedb282c8fbb0347efeab4cc32f5d9d42e2343
^-- I'd rather do this in a different PR, since it is only a refactor that will introduce a lot of noise to this PR

no workspace support

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

resolves: https://github.com/scalameta/metals/issues/6296

bugfix: don't show private apply as a completion

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/DefinitionResult.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ScaladocDefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala

connected to: https://github.com/scalameta/metals/issues/5892

fix: try pc symbol before symbol alternatives in go to definition

---

metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala

Follows https://github.com/scalacenter/scalafix/pull/1800 / https://github.com/scalameta/metals/pull/6199
Users on Scala 3.4+ with  `-Wunused:import` in their build will get unused imports cleaned up

improvement: remove unused imports on Scala 3.4+

---

metals/src/main/scala/scala/meta/internal/metals/WorkDoneProgress.scala

connected to: https://github.com/scalameta/metals/issues/6390

fix: send `end progress` if future finished with an exception

---

metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala

This might sometimes take a while.

improvement: Show progress when fetching classpath

---

metals/src/main/scala/scala/meta/internal/builds/BazelBuildTool.scala
tests/slow/src/test/scala/tests/bazel/BazelLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/6288

chore: Bump Bazel BSP and add tests about warnings

---

metals/src/main/scala/scala/meta/internal/metals/TargetData.scala

connected to: https://github.com/com-lihaoyi/mill/issues/3148

fix: `targetJarClasspath` for `mill-bsp`

---

metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala

connected to: https://github.com/scalameta/metals/issues/6370

fix: look for gradle wrapper at project root

---

metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala

resolves: https://github.com/scalameta/metals/issues/6294
partially reverts changes from: https://github.com/scalameta/metals/commit/2d1738a85910ab84b4528936cb42846776e07c5f#diff-f7151fff14758d45d6f0649c77804ac38e5af9b30bbba870988e656352498c85
We could encode/decode the path part manually but this might easily get hairy.

fix: getting top levels for filenames with ```

---

metals/src/main/resources/millw.bat

This was already done upstream.
Fixes https://github.com/scalameta/metals/issues/6445

bugfix: Fix millw script

---

mtags-shared/src/main/scala/scala/meta/internal/pc/ConvertToNamedArgumentsUtils.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ConvertToNamedArgumentsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ConvertToNamedArgumentsProvider.scala
tests/cross/src/test/scala/tests/pc/ConvertToNamedArgumentsSuite.scala

resolves: https://github.com/scalameta/metals/issues/6436

fix: Account for additional parenthesis around args in convert to named args

---

mtags/src/main/scala-2/scala/meta/internal/pc/ExtractMethodProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ExtractMethodProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcInlayHintsProvider.scala
tests/cross/src/test/scala/tests/pc/ExtractMethodSuite.scala

resolves: https://github.com/scalameta/metals/issues/6476

fix: handle implicit params in extract method

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ConvertToNamedArguments.scala
mtags-shared/src/main/scala/scala/meta/internal/pc/ConvertToNamedArgumentsUtils.scala
tests/cross/src/test/scala/tests/pc/ConvertToNamedArgumentsSuite.scala
tests/unit/src/test/scala/tests/codeactions/ConvertToNamedArgumentsLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ExtractValueLspSuite.scala

connected to: https://github.com/scalameta/metals/pull/6455/files#r1618968445

fix: convert block args to named args when in parenthesis

---

metals/src/main/scala/scala/meta/metals/SupportedScalaVersions.scala

A tiny change to try contributing to Metals
Code tested by running it locally

refactor: code duplication in SupportedScalaVersions

---

metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala

I wasn't able to figure out why this might be happening for people, but usually this happened if scalafix was invoked at a wrong time, running it later would work.
I also added reporting and a potential fix for Scalafix cache.
Related to https://github.com/scalameta/metals/issues/6501

improvement: Recreate classloader if scalafix classloading fails

---

mtags-shared/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/SingletonCompletions.scala
tests/cross/src/test/scala/tests/pc/SingletonCompletionsSuite.scala

https://github.com/scalameta/metals-feature-requests/issues/385

feat: add value completions for union types

---

docs/editors/vscode.md
metals-docs/src/main/scala/docs/TestFrameworksModifier.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/JvmOpts.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
tests/unit/src/test/scala/tests/SbtOptsSuite.scala

Should help with https://github.com/scalameta/metals/issues/6525

bugfix: Don't use everything in .jvmopts for tests

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
mtags-interfaces/src/main/java/scala/meta/pc/ReferencesRequest.java
mtags-shared/src/main/scala/scala/meta/internal/pc/ReferencesRequest.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcReferencesProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcReferencesProvider.scala

https://github.com/scalameta/metals/issues/6484

Queue pc references calls to prevent OOM

---

mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
tests/mtest/src/main/scala/tests/Assertions.scala
tests/unit/src/test/scala/tests/MetalsEnrichmentsSuite.scala

https://github.com/scalameta/metals/issues/6524

add test for `@` in path for Windows

---

metals/src/main/scala/scala/meta/internal/metals/ChosenBuildTool.scala

Might be related to https://github.com/scalameta/metals/issues/6459

improvement: Don't query database on each format

---

website/package.json

https://github.com/easyops-cn/docusaurus-search-local/issues/422 <- this bug has been bugging me

chore: Bump local search to fix it

---

metals/src/main/scala/scala/meta/internal/metals/ProjectMetalsLspService.scala

Should fix https://github.com/scalameta/metals/issues/6459

bugfix: Don't calculate digest every time build tool is used

---

metals/src/main/scala/scala/meta/internal/metals/debug/server/MetalsDebugToolsResolver.scala
project/V.scala

It has some nice improvements so worth bumping before the release

bugfix: Bump scala debug adapter

---

mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala

resolves: https://github.com/scalameta/metals/issues/6567

fix: use already imported package aliases for auto import

---

metals/src/main/scala/scala/meta/internal/metals/debug/server/DebugeeParamsCreator.scala
metals/src/main/scala/scala/meta/internal/metals/debug/server/MainClassDebugAdapter.scala
metals/src/main/scala/scala/meta/internal/metals/debug/server/TestSuiteDebugAdapter.scala
tests/slow/src/test/scala/tests/mill/MillDebugDiscoverySuite.scala

resolves: https://github.com/scalameta/metals/issues/6579

fix: correctly get build target deps for DAP

---

metals/src/main/scala/scala/meta/internal/metals/FallbackMetalsLspService.scala

fixes: https://github.com/scalameta/metals/issues/6571

fix: clear diagnostics after close for single file

---

metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala

fixes: https://github.com/scalameta/metals/issues/6598

fix: correctly handle `.scala` with shebang

---

metals/src/main/scala/scala/meta/internal/metals/MtagsResolver.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/ProblemResolver.scala
tests/unit/src/main/scala/tests/TestMtagsResolver.scala

Otherwise this timeouts tests and can actually hang metals totally.

improvement: Timeout when resolving mtags for a long time

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

resolves: https://github.com/scalameta/metals/issues/6643

fix: correctly handle odd formatting while indexing

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala

resolves: https://github.com/scalameta/metals/issues/6581
Needs also a fix in VSCode.

fix: delete test suites for deleted build targets

---

tests/unit/src/test/scala/tests/BaseNonCompilingLspSuite.scala
tests/unit/src/test/scala/tests/OutlineLspSuite.scala
tests/unit/src/test/scala/tests/best-effort/BestEffortCompilationSuite.scala

resolves: https://github.com/scalameta/metals/issues/6593

test: bump scala 3 BE version in test and add `imports-for-non-compiling`

---

metals/src/main/scala/scala/meta/internal/metals/WorkspaceFolders.scala

Related to https://github.com/scalameta/metals/issues/6665

improvement: Add debug messages for initializing folders

---

mtags/src/main/scala-2/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala

Previously, if we tried to calculate semanticdb for a file with parsing errors we would have an exception thrown.
Now, we just return an empty TextDocument and not reprot that to the user as it will already be reproted as a diagnostic.

bugfix: Catch possible syntax errors

---

metals/src/main/scala/scala/meta/internal/metals/JarSourcesProvider.scala

connected to: https://github.com/scalameta/metals/issues/6693#issuecomment-2301662426

improvement: add coursier repositories instead of overwrite

---

metals-docs/src/main/scala/docs/Docs.scala

resolves: https://github.com/scalameta/metals/issues/6703

fix: create `docsOut` directory

---

mtags-shared/src/main/scala/scala/meta/internal/pc/Keyword.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala

Fixes https://github.com/scalameta/metals/issues/6724

feature: Add opaque type completions

---

docs/build-tools/bazel.md

@ValdemarGr would you want to include more information here? Alternatively, we could try getting Mezel setup more automatic in Metals, though I might not have time to work on it.

docs: Update Bazel docs and add Mezel

---

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/6748

bugfix: Check if locally available sbt is actually a file

---

mtags/src/main/scala-3.2/scala/meta/internal/pc/Compat.scala
mtags/src/main/scala-3.3.1/scala/meta/internal/pc/Compat.scala
mtags/src/main/scala-3.3.2/scala/meta/internal/pc/Compat.scala
mtags/src/main/scala-3.3.3/scala/meta/internal/pc/Compat.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala

resolves: https://github.com/scalameta/metals/issues/5971

fix: do not show completions in comments

---

metals/src/main/scala/scala/meta/internal/builds/Digest.scala
metals/src/main/scala/scala/meta/internal/builds/MillDigest.scala
metals/src/main/scala/scala/meta/internal/metals/ScaladocDefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticTokensProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ConvertCommentCodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/MillifyDependencyCodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/StringActions.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
mtags/src/main/scala/scala/meta/internal/metals/docstrings/printers/MarkdownGenerator.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalametaCommonEnrichments.scala

Fixes https://github.com/scalameta/metals/issues/6808

improvement: Add Unreachable exception handling

---

mtags-shared/src/main/scala/scala/meta/internal/metals/ReportContext.scala

Helps with https://github.com/scalameta/metals/issues/6829
Fixes https://github.com/scalameta/metals/issues/6831

bugfix: Do not fail while creating reports

---

metals/src/main/scala/scala/meta/internal/metals/ProjectMetalsLspService.scala

It seems in some scenarios it might read too much into memory and go OOM

improvment: Limit number of read semanticdb files

---

tests/unit/src/main/scala/tests/codeactions/BaseCodeActionLspSuite.scala

I added it in a previous PR, but must have lost it during a rebase.

improvement: Retry code actions detection for Scala CLI

---

metals/src/main/scala/scala/meta/internal/metals/ZipReportsProvider.scala

Fixes https://github.com/scalameta/metals/issues/6870

bugfix: Create reports directory if it doesn't exist

---

project/V.scala

Fixes https://github.com/scalameta/metals/issues/6800

chore: Update Scalameta to 4.11.0

---

metals/src/main/scala/scala/meta/internal/metals/formatting/MultilineString.scala
tests/unit/src/test/scala/tests/rangeFormatting/MultilineStringRangeFormattingWhenPastingSuite.scala

Fixes https://github.com/scalameta/metals/issues/6798

bugfix: When determining indent first check for pipe

---

metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
tests/unit/src/test/scala/tests/scalafix/ScalafixProviderLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/6886

bugfix: Correctly check if a given config exists in scalafix.conf

---

metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugDiscovery.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliDebugSuite.scala

Fixes https://github.com/scalameta/metals/issues/6909

bugfix: Also discover synthetic mains such as scripts

---

tests/unit/src/main/scala/tests/JavaHomeChangeTest.scala

We could otherwise get spurious failures even if the test was not run.

chore: Only resolve jvm when running test

---

metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/clients/language/ConfiguredLanguageClient.scala

Fixes https://github.com/scalameta/metals/issues/6937

bugfix: Check if inlay hints refresh is enabled

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcInlayHintsProvider.scala
tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala

bugfix: Show implicit chained calls in inlay hints

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/debug/server/DebugeeParamsCreator.scala
metals/src/main/scala/scala/meta/internal/metals/utils/RequestRegistry.scala
tests/slow/src/test/scala/tests/mill/MillBreakpointDapSuite.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala

This should improve the tests and it's not something use will understand.

improvement: Don't ask for cancel for main and test clases

---

metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala

Couple of changes here:
- changed focusedDocument to AtomicReference, since while debugging I noticed that it stopped changing
- moved setting focusedDocument up just in case
- added to change focus onChange, since that would indicate properly something is being worked on when clients don't support metals/didFocus
- added older focused documents to active file queue
Hopefully those changes will fix an issue where focusedDocument stops changing.

bugfix: Try to make focused document more secure

---

metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

I don't think this changes anything as we did also set build server config, but just in case.

bugfix: Don't send best effort flag when disabled

---

metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala
tests/unit/src/main/scala/tests/BuildServerInitializer.scala
tests/unit/src/test/scala/tests/UserConfigurationSuite.scala

Will be useful in the inlay hints worksheet PR for sending configuration, since we always need user configuration to be sent.

improvement: Add toString to UserConfiguration

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala

It seems that we get two action symbols and their effectiveOwners are also separate symbols.

bugfix: Fix issue when  would be added as prefix

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionBuilder.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractMethodCodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/InsertInferredType.scala
metals/src/main/scala/scala/meta/metals/lsp/DelegatingScalaService.scala
metals/src/main/scala/scala/meta/metals/lsp/TextDocumentService.scala
tests/unit/src/main/scala/tests/TestingClient.scala

I changed one code action for now, but probably it would be good to change others also.

improvement: Use codeAction/resolve for code actions

---

metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala

resolves: https://github.com/scalameta/metals/issues/6772

improvement: by default support `scala-cli` power options

---

mtags/src/main/scala/scala/meta/internal/pc/ScriptFirstImportPosition.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliActionsSuite.scala

resolves comment: https://github.com/scalameta/metals/issues/7071#issuecomment-2577997104

fix: skip using directives for auto import position when missing newline

---

metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala

Might be easier for people to find.

improvement: Add switch command to metals tab

---

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/ConnectionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/ProjectMetalsLspService.scala
tests/slow/src/test/scala/tests/mill/MillLspSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala
tests/unit/src/main/scala/tests/TestingClient.scala

improvement: suggest bsp switch if bloopInstall fails + clean up sbt bloop plugins

---

tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala
tests/unit/src/test/scala/tests/CreateDirectoriesSuite.scala

Not sure why the order changes

bugfix: Fix cross tests

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/bsp/BspResolvedResult.scala
metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/builds/BazelBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/BuildServerProvider.scala
metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala

resolves https://github.com/scalameta/metals/issues/7149

fix: regenerate mill on incorrect version

---

metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsProjectDirectories.scala
metals/src/main/scala/scala/meta/internal/metals/Trace.scala

Fixes https://github.com/scalameta/metals/issues/6885

bugfix: Filter out cache directories containing null

---

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
tests/unit/src/test/scala/tests/StackTraceMatcherSuite.scala

#6995
Needs to be ported to bloop.

improvement: add file location also to stacktrace printed to stdout

---

tests/unit/src/main/scala/scala/meta/internal/metals/debug/TestDebugger.scala

I was too quick with merging that and the condition was wrong

chore: Fix issue with flakiness properly

---

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
tests/unit/src/main/scala/tests/TestingServer.scala

This also reduces the number of error reports we get running `DefnitionLspSuite`.

improvement: improve definition reports

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
project/V.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/7209

bugfix: Revert go to definition order for older scala version

---

project/Developers.scala

Michał is very active promoting and helping us out with Metals. He also contributed a number of features and improvements to metals

Add Michał to contributors

---

metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala

Not sure when this might happen, but we should not fail the whole action based on it.

bugfix: Don't fail when deleting temporary files

---

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/WorkspaceSymbolSearch.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/cross/src/test/scala/tests/pc/InfoSuite.scala
tests/slow/src/test/scala/tests/feature/ImplementationCrossLspSuite.scala
tests/unit/src/main/scala/tests/BaseImplementationSuite.scala
tests/unit/src/test/scala/tests/ImplementationLspSuite.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

closes #3808 
This PR is a result of joint work during the `Tooling Spree` of:
- @zainab-ali 
- @kasiaMarek 
- @KacperFKorban

Treat self types as parent types in go to implementation context

---

metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

connected to #7251
This doesn't fully resolve the issue, since for Scala 3 there is some other bug in presentation compiler.

fix: look for implementations in rename for possibly overridden type aliases

---

tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala
tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala
tests/unit/src/test/scala/tests/AutoImportLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/6331

tests: Add Scala 3 tests that use symbol search

---

metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala

Fixes https://github.com/scalameta/metals/issues/7264

improvement: Don't log noop compilation on info

---

build.sbt
mtags/src/main/scala-2/scala/meta/internal/pc/PcDefinitionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/PcDefinitionSuite.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala
tests/unit/src/test/scala/tests/worksheets/WorksheetLspSuite.scala

https://github.com/scalameta/metals/issues/7267

fix: go to def should lead to all apply, object and class (Scala 2)

---

bin/test.sh
metals/src/main/scala/scala/meta/internal/builds/BazelBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala
metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
tests/unit/src/test/scala/tests/CredentialsSuite.scala
tests/unit/src/test/scala/tests/GradleRepositoriesTest.scala

Based on https://github.com/coursier/coursier/pull/3327/files
This probably needs to be fixed at some point in coursier itself, though it's not clear how to do it properly.
Will most likely need to be tested by users for https://github.com/scalameta/metals/issues/7293

bugfix: Add credentials automatically for coursier API

---

metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala

Connected to https://github.com/scalameta/metals/issues/7293

improvement: Don't crash the server if failed to download java semanticdb

---

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala

Connected https://github.com/scalameta/metals/issues/7293

improvement: Log when setting credentials

---

.github/workflows/ci.yml
metals/src/main/scala/scala/meta/internal/builds/BazelBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala
metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
project/TestGroups.scala
tests/unit/src/test/scala/tests/FallbackDownloadSuite.scala

I also centralized downloading into Embedded to make it easier to fix things instead of having Fetch all over the place

improvement: Retry downloading dependencies using a local coursier

---

metals/src/main/scala/scala/meta/metals/DownloadDependencies.scala

Also add an option to copy those jars

improvement: Add scalafix and Scala 3 PC to DownloadDependencies

---

metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
tests/unit/src/test/scala/tests/RenameFilesLspSuite.scala

#7320 fix package rename

---

metals/src/main/scala/scala/meta/internal/metals/debug/server/MetalsDebugToolsResolver.scala
metals/src/main/scala/scala/meta/metals/DownloadDependencies.scala

Exclude manually the versions that don't exist / aren't supported.

feat: `DownloadDependencies` gets debug tools

---

tests/unit/src/test/scala/tests/TreeViewLspSuite.scala

I think there is some instability in the lsp4j deps, which caused this.

bugfix: Fixed changed deps in lsp4j

---

mtags/src/main/scala/scala/meta/internal/metals/SemanticdbDefinition.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala

Fixes https://github.com/scalameta/metals/issues/7372

bugfix: Fix issues with EOF during tokenization

---

metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala

improvement: make diagnostics and debugging not supported for sbt message more clear

---

metals/src/main/scala/scala/meta/internal/metals/CompilerConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala

fixes: https://github.com/scalameta/metals/issues/6756#issuecomment-2798829979

fix: add fallback presentation compiler for Java

---

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala

Fixes https://github.com/scalameta/metals/issues/7419

bugfix: Make sure cs is an actual executable file

---

metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CustomCodeActionKind.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala
tests/slow/src/test/scala/tests/feature/ImportMissingSymbolCrossLspSuite.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliActionsSuite.scala
tests/unit/src/test/scala/tests/BaseNonCompilingLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala

source command triggers
when triggering the source command it shows an additional 'Add all missing imports that are unambiguous in this file' which adds all missing imports in the file

AddMissingImports for the entire file using codeActionKind.source

---

mtags/src/main/scala-2/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcDocumentHighlightProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala

fixes: https://github.com/scalameta/metals/issues/7086 and https://github.com/scala/scala/pull/10991#issuecomment-2709088225

Prepare for Scala 2.13.17

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala
tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala

fix: Add type param inlay hint for constuctor calls

---

mtags/src/main/scala-2/scala/meta/internal/pc/SelectionRangeProvider.scala
tests/cross/src/test/scala/tests/pc/SelectionRangeSuite.scala

Adds more selection ranges corresponding to whole names.

feat: selection ranges for more names

---

metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala
tests/unit/src/test/resources/foldingRange/expect/Blocks.scala
tests/unit/src/test/scala/tests/FoldingRangeLspSuite.scala

This adds folding ranges around function application argument lists.

feat: folding ranges for function calls

---

metals-docs/src/main/scala/docs/RequirementsModifier.scala

Fixes https://github.com/scalameta/metals/issues/7465

bugfix: Fix versions to not include Right

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SignatureHelpProvider.scala

Closes https://github.com/scalameta/metals/issues/7463

bugfix: Calculate completion items eagerly

---

metals/src/main/scala/scala/meta/internal/builds/BloopInstallProvider.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/ConnectionProvider.scala
tests/slow/src/test/scala/tests/mill/MillServerSuite.scala

Mill 1.0.0 no longer supports Bloop.

improvement: Support Mill 1.0.0

---

metals/src/main/scala/scala/meta/internal/metals/mcp/MetalsMcpServer.scala
tests/unit/src/test/scala/tests/mcp/McpServerLspSuite.scala

Previously, we would just return strings and even if a potentially full name of library was set we wouldn't return the version. This confused agents and they though the version is part of the name that got returned.
Now:
- we return explicit result which says what was completed
- try to first complete the next step of the dependency string and only then fallback
The latter means that if for example we complete cats-core name, we will first try `org.typelvel:cats-core:` and if nothing is found complete `org.typevelel:cats-core`.

improvement: Return a better LLM compatible result from find-dep

---

bin/test.sh
build.sbt
docs/build-tools/sbt.md
metals-docs/src/main/scala/docs/Docs.scala
metals-docs/src/main/scala/docs/RequirementsModifier.scala
metals-docs/src/main/scala/docs/Snapshot.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
metals/src/main/scala/scala/meta/metals/SupportedScalaVersions.scala
tests/unit/src/test/scala/tests/GradleRepositoriesTest.scala
tests/unit/src/test/scala/tests/SupportedScalaSuite.scala

We now use central publishing and new locations for snapshots

bugfix: Fix functionality dependent on snapshots

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala

Fixes https://github.com/scalameta/metals/issues/7572

bugfix: Fix completions at the start of the file

---

metals/src/main/scala/scala/meta/internal/metals/PreviouslyCompiledDownsteamTargets.scala
tests/unit/src/test/scala/tests/DiagnosticsLspSuite.scala

possibly fixes: https://github.com/scalameta/metals/issues/7580

fix: correctly remove from previously compiled map

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionItemResolver.scala

Fixes https://github.com/scalameta/metals/issues/7605
I don't think we can get the underlying issue unfortunately, so this should be good enough for now.

improvement: Don't throw when unable to get docstrings, just show empty

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsPasteProvider.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags-interfaces/src/main/java/scala/meta/pc/VirtualFileParams.java
mtags/src/main/scala-2/scala/meta/internal/pc/DiagnosticsProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/test/scala/tests/pc/DiagnosticsSuite.scala
tests/unit/src/test/scala/tests/MetalsPasteSuite.scala

feat: add imports on Metals paste

---

metals/src/main/scala/scala/meta/internal/metals/debug/ExtendedScalaMainClass.scala
tests/unit/src/test/scala/tests/DebugDiscoverySuite.scala

Fixes https://github.com/scalameta/metals/issues/7601

bugfix: Escape $ in shell command

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/ZioTestFinder.scala
tests/unit/src/test/scala/tests/testProvider/ZioTestFinderSuite.scala

This PR is about making ZIO users be able to run specific `suite` and `suiteAll`
Before this PR ZIO users could just run specific test or all the tests in the file.
Tested all scenarios with ZIO2 project

Fix ZIO test support bug

---

metals/src/main/scala/scala/meta/internal/metals/MetalsSymbolSearch.scala

Should help with https://github.com/scalameta/metals/issues/7644

bugfix: Use toAbsolutePathSafe in symbol search

---

tests/unit/src/main/scala/tests/TestingServer.scala

It seems when checking files it would go to out mill directory which might be actively modified

improvement: Fix issues with races on CI

---

mtags/src/main/scala-2/scala/meta/internal/pc/SignatureHelpProvider.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpPatternSuite.scala

bugfix(Scala-2): add arg name to pattern match type hint

---

.github/workflows/ci.yml
tests/mtest/src/main/scala/tests/BaseSuite.scala
tests/unit/src/main/scala/tests/debug/BaseStepDapSuite.scala
tests/unit/src/test/scala/tests/FindTextInDependencyJarsSuite.scala
tests/unit/src/test/scala/tests/debug/CompletionDapSuite.scala

Fixes https://github.com/scalameta/metals/discussions/7742

improvement: Test metals on latest stable java version

---

metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala

Should help with https://github.com/scalameta/metals/issues/7761

improvement: Retry downloading with fallbacks for scalafmt

---

docs/editors/emacs.md

Fixes https://github.com/scalameta/metals/issues/7825

docs: Remove no longer relevant mention

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
mtags-interfaces/src/main/java/scala/meta/pc/VirtualFileParams.java
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/test/scala/tests/pc/DiagnosticsSuite.scala

Weirdly enough, it now started to work after my recent changes.Previously, even when using debugger I was seeing the Some(value: Boolean) to be ignored :O 
So better save than sorry, I just added it as a parameter

bugfix: Fix issues with didPaste functionality

---

docs/contributors/releasing.md
project/V.scala

- [chore: Update Bloop and introduce a newline to avoid conflicts](https://github.com/scalameta/metals/commit/78dd6fc8d795a1621b90d21b0f0447c2204e11a5)
- [chore: Also update release procedures](https://github.com/scalameta/metals/commit/2dfc9a2ecb814d386c27ae1639c7e9bf3b00e9ef)]

Update Bloop and docs

---

metals/src/main/scala/scala/meta/internal/metals/formatting/MultilineString.scala
tests/unit/src/test/scala/tests/rangeFormatting/MultilineStringRangeFormattingWhenPastingSuite.scala

Fixes https://github.com/scalameta/metals/issues/7873

bugfix: Fix issue with not adding | in the last line
