metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala

This is a quick follow-up to my comment in #2190 about showing the message to the user when they are using a worksheet but their Scala version isn't supported. So now instead of just logging it, we both log it and show it to the user.
Another question that I _think_ I remember being discussed somewhere, but I find it a bit unexpected that if I'm using 0.27-RC1 we show the message about what version they _should_ be using, but then instead of defaulting to that version, we default to 2.12.12. I'm assuming because we already have everything we need for it, but would it be possible to instead of defaulting to 2.12.12, we detect that the user wants a Scala 3 version and default to the recommended Scala 3 instead? Basically make the rambo compiler closer to what they want.

Show warning about unsupported Scala version in worksheets

---

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala
metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala
tests/unit/src/test/scala/tests/decorations/SyntheticHoverLspSuite.scala

While writing the release notes it dawned on me that the previous names might not be too clear, especially the `annotation` part.
It's not yet release so changing the names should not be a problem, what do you think?

Rename user configuration options for decoration provider

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question.md
bin/merged_prs.sc
bin/test-release.sh
build.sbt
website/blog/2020-11-10-lithium.md

It took me longer than expected, but it's here! :sweat_smile: 
After the release notes are approved I will release Metals together with the extension, merge @ckipp01's blog, update the link in the release notes and then merge the release notes. At least, this is the plan.
TODOS:

Add release notes for 0.9.5

---

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala

This is a quick fix for #2201. This was causing us to try and pull 0.27 from `org:scala-lang`,  which isn't where it lives. Also as a side now, we should add this as one of the checks we do on release to be sure this works. Better yet, we should test to ensure it's continually working.
Closes #2201

Fix scala3Dependency for various binary scala3/dotty versions

---

docs/editors/new-editor.md
metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala

Following up on a conversation from Gitter, I realized we didn't have this new option in the docs.

Update docs to mention `inlineDecorationProvider`

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

It seems if any previous content ends with a list, `*` gets treated as an another item.

Add additional newline to fix problems with markdown

---

.dependabot.yml

Essentially followed the instructions here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot
I figured this may be useful for keeping the workflows up-to-date

Configure dependabot to update github-actions

---

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala
metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala
tests/unit/src/test/scala/tests/decorations/SyntheticHoverLspSuite.scala

It seems a good next step after implicit parameters and inferred type. Should be useful in some cases, but I figured it would be good to have it under a separate option.
TODO:
- ~~add option in VS Code extension~~ https://github.com/scalameta/metals-vscode/pull/447
Actually seems to work pretty nice inside metals itself:

Add option to show implicit conversions as decorations

---

metals/src/main/scala/scala/meta/internal/bsp/BspSession.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala

So I've put more time into this than I care to admit. I'll be honest
that this isn't the fix that I really want, but sort of the fix that may
just makes the most sense at the moment.
This is an interesting one. So for a bit of background I'm assuming that
the `doCompile` was first added in the situation where a user opens up
their `build.sbt` while using Bloop, and then tries to open the tree
view. Without this compile request here, the tree view projects will be
empty. However, with it, it will trigger the necessary compilation and
populate the tree. However, subsequent compile requests or notifications
of compiles seem to cause no problems with Bloop. _Even_ though a
compile request _probably_ isn't needed here every time. However, with
sbt BSP, since loading the build up includes …

Fix continuous compilation when opening tree view in sbt BSP

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProtocol.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala

Just found out this is actually pretty simple to do and should work in all clients.

Add source and line to debug output in case of stack traces

---

docs/editors/overview.md
metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

This enables us to quickly toggle the decorations in the clients:
@ckipp01 I think since the settings are managed by the clients, we need to do the actual toggle command in the client. This will be most useful in VS Code and not sure if it will be helpful in other editors. Especially without decorations it doesn't change anything.

Refresh synthetics when user settings change

---

build.sbt
metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/metals/GlobalTrace.scala

So it looks like this changed namespaces from their personal one to a `dev.dirs` namespace. I just randomly came across this as I was poking around at some of the related code. So this just updates from `io.github.soc` -> `dev.dirs` and bumps the version to the latest.

New directories namespace `io.github.soc` -> `dev.dirs`

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/ScaladocCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionScaladocSuite.scala

This enables us to autocomplete empty scaladoc even if nothing is defined after the `/**`, like:
fix https://github.com/scalameta/metals/issues/1941

Autocomplete empty scaladoc if nothing is defined afterwards

---

build.sbt

This new version of swoval supports Apple silicon using arm64.

Bump swoval to latest version

---

build.sbt
sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala

This addresses the problem outlined in #2250 where the semanticdb compiler plugin was being added to a 2.10 projects as well as semanticdb related settings in both `scalacOptions` and `semanticdbOptions`. Now this just adds in a check to ensure we don't do any of that for projects on 2.10.x.
Closes #2250

Don't add semanticDB plugin for Scala 2.10 when using sbt BSP

---

website/blog/2020-11-26-lithium.md

Just a quick release for people to be able to sensibly work with 3.0.0-M2 without the need for a snapshot. If we don't release straightaway then people start asking questions :sweat_smile:

Add release notes for 0.9.7

---

docs/contributors/releasing.md

After thinking about a bit it turns out we actual isntructions still do not reflect the actual process:
- release notes should be agreed upon before actually running the release - we might discover that something is missing at that point
- we did not mention that VS Code release should be run via the release page.
- other small fixes

Update release instructions

---

metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
mtags/src/main/scala/scala/meta/internal/semver/SemVer.scala
tests/unit/src/test/scala/tests/ScalaVersionsSuite.scala
tests/unit/src/test/scala/tests/WarningsLspSuite.scala

This showed up as a warning when using 3.0.0-M1:

Compare release candidates and milestones in addition to major.minor.patch

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

Like we did to fix #2133, if the user is in a situation where they are
given a standalone compiler for worksheets, we then ensure that they not
only have Java sources available to them, but also Scala sources. We
default to the version of Scala in Metals itself.
I do have a check in there to make sure there is no "scala-library" in
sources, but that _probably_ isn't necessary as (in this scenario) the
only time that would happen would be if they have included it as an
import in their worksheet. However, just to be safe, I added it in.
I also moved the logic for this from the compilers to the
StandaloneSymbolSearch apply methods to ensure that we don't get hit on
this in the future if we use these elsewhere.
Closes #2266

Add in Scala Sources to standalone worksheets.

---

metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala

Follow up from https://github.com/scalameta/metals/pull/2294
It changed again and I haven't really noticed :sweat:

Scala 3 template was moved from lampepfl org

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala

Before this if a `.bsp/sbt.json` file existed and there was no `.bloop/`
yet then it would attempt to auto-connect to sbt. This behavior changes
this slightly now so that the behavior I just explains _only_ happens
if an explicit choice was made before, or if there is a `.bsp/<build-server>.json`
entry that is a Build Tool that Metals doesn't have Bloop support for.
This will supersede https://github.com/scalameta/metals/pull/2292 and closes #2291 
As always, my brain tried to over-complicate things when there was a simple solution. 😬

Fix auto-connect BSP server without explicit choice.

---

build.sbt

Without this being the latest users may be using certain new
settings that have been added which will cause a warning that
the rule can't be found, but it's just because the setting
doesn't yet exist with this version.
I found this when I found #2306, but this doesn't fix the the
underlying issue.

Bump version of organizeImportRule to latest

---

sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala

closes #2245
Thanks for your thorough issue @asflierl. What you mentioned as your _temporary_ fix is actually the way to go I think. Since if we don't duplicate those values in the semanticdbOptions, then when it's removed in `Test`, we no longer have the issue as you pointed out.

Make sure to not duplicate semanticdbOptions when using sbt BSP.

---

metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala

~Atm this is just here to show how https://github.com/scalameta/mdoc/pull/427 is meant to be used from the Metals side. I still need to add in some tests here, but I wanted to at least have this up to help with the mdoc review.~
~So when everything is fine and there are no error diagnostics the user will be able to just copy the output of a worksheet with a command like so:~
If there is a diagnostic error, then you won't be able to export
You can see what is needed for a client to implement this [here in coc-metals](https://github.com/scalameta/coc-metals/pull/360/files)
EDIT: The gifs are now out of date as the output are no longer on the same line, but all of them are under. Also, the full implementation of this is now done in Metals, no longer in mdoc.

Add in ability to export worksheet evaluations.

---

sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala

This addresses the first part of #2285, but there is still more work
to be done to get the sourceroot issue figured out.

Ensure semanticdb is enabled with sbt BSP and Scala 3.

---

metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala

I came across this today in an Ammonite script. I wanted to try
something out with 2.13 and I without really thinking put the following
at the top of my Ammonite script.
```scala
// scala 2.13.4
```
And it just showed me:
```
Error importing /Users/ckipp/Documents/scala-workspace/worksheets/tester.sc. See
the logs for more details.
```
When in reality, we have a much better message to show the user, since
we know the reason it failed is that the version of Ammonite we are
using isn't available for that Scala Version. So this change better
captures that exception, and actually shows it to the user. So now in
this same situation you'd instead see:
```
Error fetching Ammonite 2.3.8 for scala 2.13.4
```
Part of this is also because I'm seeing a pattern in the survey results
so far of people …

Add in better message for user if trying to fetch invalid Ammonite.

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Scala3CompilerWrapper.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
project/build.properties
project/plugins.sbt
sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala
tests/cross/src/main/scala/tests/pc/BaseHoverSuite.scala
tests/cross/src/test/scala/tests/pc/CancelCompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/mtest/src/main/scala/tests/BaseSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala

In order not to deprecate 0.27.0-RC1 and 3.0.0-M1 we needed to use an older munit version for those, as we needed to drop support for them in munit. There was also small needed fix, since typeRef was no longer available, but paramRef does invoke it underneath. 
Another issues that we faced was the fact the mtags no longer compiled on the 0.4.5 dotty plugin version and we needed to update both it and sbt, which caused some tests to fail and I ignored them for now until we can fix it in Bloop.

Add support for Scala 3.0.0-M3

---

.jvmopts

The CMS GC was deprecated in JRE 9 and it was removed in JRE 14. If one happens to attempt to launch SBT on the current JRE (15), it will fail due to this flag.
Further, if the running JRE supports the CMS GC and chooses to use it, `-XX:+CMSClassUnloadingEnabled` is enabled by default, so we shouldn't need to explicitly enable it in most cases anyway.
> -XX:+CMSClassUnloadingEnabled
>  Enables class unloading when using the concurrent mark-sweep (CMS) garbage collector. This option is enabled by default. To disable class unloading for the CMS garbage collector, specify -XX:-CMSClassUnloadingEnabled.
I realize that JREs 14/15 are not officially supported, but it is nice to be able to launch `sbt` without having to switch JREs even in this case.

Remove `-XX:+CMSClassUnloadingEnabled` From `.jvmopts`

---

mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala

In a very amusing situation, `setDeprecated` from `org.eclipse.lsp4j.CompletionItem` is now itself deprecated.
This commit updates the usage to the new form, using `setTags` to add a `deprecated` tag on the `CompletionItem`.

Update Deprecated Usage Of `setDeprecated` from `lsp4j`

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala

On 1.2.8 we are currently getting:
`[error] java.lang.NoSuchMethodError: sbt.Keys$.reresolveSbtArtifacts()Lsbt/SettingKey;`
I think it's fine to stop supporting 1.2.x in Bloop, since users can always use the older version and not much changes in the integration plugin. But inside Metals this might be problematic, because we force the Bloop version on users.
I am also not 100% how we could fix it in Bloop especially that we compile for 1.3.0 in reality.

Fix incompatibility between currently used Bloop and sbt versions < 1.3.0

---

docs/editors/overview.md
metals/src/main/resources/db/migration/V1__Create_tables.sql
metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/Debug.scala
metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala
metals/src/main/scala/scala/meta/internal/metals/Tables.scala
metals/src/main/scala/scala/meta/internal/metals/WorksheetDependencySources.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/WorksheetDependencySourcesSuite.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

This solves all issues connected to semanticdb in standalone files. It's now possible to find references, rename etc in standalone files. This was also helpful for testing out and fixing an issue with URIs being wongly produced for semanticdb files produced in the compiler.
Fixes https://github.com/scalameta/metals/issues/2340

Calculate semanticdb for standalone files

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
metals/src/main/scala/scala/meta/internal/troubleshoot/ProblemResolver.scala
metals/src/main/scala/scala/meta/internal/troubleshoot/ScalaProblem.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala
tests/unit/src/test/scala/tests/MessagesSuite.scala
tests/unit/src/test/scala/tests/WarningsLspSuite.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

The main goal of this refactor is to make sure we have just one category of problems that will be reported both in the message request and the doctor. Previously, both would need to be updated independently and testing for those was scarce. Thanks to having a single category of problems we can now properly unit test them to make sure every message is sensible. It's also easier now to see what each problem is caused by and what message will be displayed to the user.
Also, this should fix https://github.com/scalameta/metals/issues/2167 - sbt issues will now be reported separately, so that the users are not confused.

Refactor doctor and make sure issues with sbt are properly reported

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala

Previously, if the user switched an editor window the worksheet decorations would disappear and even when they went back, it would not appear until another evaluation was triggered. Now, it will just republish existing evalautions.

Make sure that worksheet decorations are shown again when the focused

---

mtags/src/main/scala-3/scala/meta/internal/pc/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/main/scala/tests/BaseCompletionSuite.scala
tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionBacktickSuite.scala

Related https://github.com/scalameta/metals-feature-requests/issues/112
Though there're still some things to do, I'm submitting a draft PR because I want to ask for advice around the failing tests :pray:, or want to at least have this as a reference implementation for people who want to implement arg completion in the future.
I think it's ideal to fix all tests implemented in `cross`, but it might be ok to ship it because it's better than nothing 😅
---
```scala
object Main {
1.until(@@)
}
```
We get empty completion because `methodSym` in `ArgCompletion` always `NoSymbol`.
I guess this is because `assert(@@)` and `1.until(@@)` have multiple overloaded methods like `until(end: Long)` and `until(start: Long, end: Long)`, and that's why we can't retrieve a specific symbol.
```scala
val …
```

Bare minimum arg completion for scala3

---

metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

This is mainly to just get a conversation going about the best way to handle this. I've been digging into #2384 a bit, and I'm really unsure of how to handle that situation. This is an attempt to just not throw a NPE and handle it a bit more gracefully. The idea is that for some reason if a user opens a standalone `*.scala` file that isn't in any type of a workspace, and no `rootPath` or `rootUri` is set, then we show them an error and the functionality that would be provided by Metals is very minimal. However minimal, this would be better than forcing an exit like we saw in #2384 which leaves the user with no way to tell what's going on.
Part of the trouble is that a lot of extensions/clients handle this differently.
- In VS Code, …

Avoid NPE when there is no `rootUri`.

---

metals/src/main/scala/scala/meta/metals/Main.scala

So _maybe_ not the most important pr, but I was working on a nice way in `nvim-metals` to show the users what exact version of Metals they are using and what Scala version are supported. `metals --version` actually works pretty nicely for this, but with the current output, if you screen is split or anything the display isn't that nice. With this change it clearly differentiates between the Scala 2.x, and 3 versions and displays them a bit differently.

Clean up --version output.

---

build.sbt
project/plugins.sbt
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala
tests/unit/src/main/scala/tests/QuickBuild.scala

Running it for now with a SNAPSHOT to make sure it makes sense to release a new semanticdb version.

Add support for Scala 2.12.13

---

sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala

This ensures that if a user is going to set the `semanticdbVersion`
locally with something like:
```
ThisBuild / semanticdbVersion := "4.4.6"
```
That they are still able to.
Closes #2395

Ensure semanticdbVersion can be overwritten.

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

The last couple versions of the LSP spec have included the clientInfo object
in the initializationParams. I think it's better if we just rely on this, especially
seeing that some clients won't have the client set via flags anymore, since it's
no longer necessary due to everything being configurable via intializationOptions.
Plus, doing it this way will also give us the version. All of the modern clients that
I looked into have these filled.

Look for clientInfo in intializeParams instead of serverConfig.

---

build.sbt
project/plugins.sbt
sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala
tests/slow/src/test/scala/tests/feature/AmmoniteSuite.scala
tests/unit/src/test/scala/tests/AmmoniteSuite.scala
tests/unit/src/test/scala/tests/codeactions/CreateNewSymbolLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala
tests/unit/src/test/scala/tests/debug/StepDapSuite.scala

Fixes https://github.com/scalameta/metals/issues/2403

Update Metals Scala 2.12 version to 2.12.13

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
tests/slow/src/test/scala/tests/feature/AmmoniteSuite.scala

We are pulling the version of Ammonite from buildInfo and the version
of Ammonite we are using isn't available for 2.12.13 yet. We did fix
this is in the Ammonite tests, but we forgot to actually change it where
we get Ammonite.
Also I did check and there still isn't a new version published for for Ammonite and 2.12.13.
This was originally reported by @soronpo on [Gitter](https://gitter.im/scalameta/metals?at=6007952bdfdbc1437f9d42a5)

Fix default version of Scala given to Ammonite.

---

metals/src/main/scala/scala/meta/internal/metals/debug/SourcePathProvider.scala

This fixes https://github.com/scalameta/metals/issues/2425 which was caused by a very specific scenario trying to debug a class from test that has an empty package.
I tried to reproduce it in the tests, however it proved to be a bit difficult, since `QuickBuild` doesn't have `test` and main separate targets and to reproduce this we would need to rework the infrastructure.

Prepend `_empty_/` when searching for symbol without a package

---

metals/src/main/scala/scala/meta/internal/metals/debug/SourcePathProvider.scala

It seems in cases where we have `package object myObject {}` inside `myObject.scala` file the path given to us will be `myObject/myObject`, but the actual symbol is `myObject/package.`. This normally works with a standard  naming where package objects are put into `package.scala` file, so the path would be `myObject/package`.
As a fallback for symbol search we also check workspace sources for the file, but we haven't done it transitively, so files in dependency project would not be found. This fixes it so that the fallback works in those cases too.

Search also transitive sources when falling back from symbol search

---

metals/src/main/scala/scala/meta/internal/metals/debug/SetBreakpointsRequestHandler.scala
tests/unit/src/main/scala/tests/BaseDapSuite.scala
tests/unit/src/test/scala/tests/debug/BreakpointDapSuite.scala

Breakpoints need to be registered for each class file separately, so Metals takes care of translating source file locations to separate class file names displayed as for example `dap-fqcn:packageName.objectName$`.
Breakpoints for each file are send from the DAP client (like for example VS Code) separately and because of that we would remove breakpoints for the previously send files upon receiving another breakpoint request. Now, it's changed, so that specific breakpoints for classfiles are remembered separately for each file. This helps to to recognize when an empty request needs to be sent for a certain classfile.
This one was a bit tougher, but thanks for reporting @shaofengjiang!

Fix issue with breakpoints in multiple files

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/bsp/BspResolvedResult.scala
metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/bsp/BspSession.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/troubleshoot/ProblemResolver.scala
tests/unit/src/test/scala/tests/BspSwitchLspSuite.scala

Previously if a user would issue a `bsp-switch` command and there was an
entry in `.bsp/` for a server, then no matter what, Bloop was offered as
a choice. However, there may be a situation where a workspace is a
workspace that does have a `.bsp/` entry, but the build tools is one
that Bloop doesn't work with. In this scenario, Bloop shouldn't be
offered since it doesn't know how to import from this build tool.
An example. Let's say we have build tool `xyz` and server `xyz` with a
corresponding `.bsp/xyz.json` file. If a user open Metals in this
workspace, it will auto-connect to `xyz`. If the user issues a
`bsp-switch`, they will just see a warning now that says:
> Unable to switch build server since there is only one supported build
> server 'xyz' detected for this workspace.
Fixes …

Ensure Bloop isn't offered as a server in an unsupported workspace.

---

docs/editors/vscode.md

Follow up of https://github.com/scalameta/metals-vscode/pull/493

Fix vscode.md (find-java-home has replaced by locate-java-home in metals-vscode v1.1.0)

---

build.sbt

So it seems with the previous change, the setting only changed for docs, which caused other projects to have the default name. This should finally fix it.

Make `munitBucketName` a global setting

---

mtags/src/main/scala-2/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala

Ensure that we have the correct dialect when creating semanticdb for
standalone .sc files. This was causing exceptions to be thrown for .sc
files since it wasn't recognizing the top level definitions.
Fixes #2430

Correct dialect for standalone scripts.

---

docs/integrations/decoration-protocol.md
docs/integrations/new-editor.md
metals-docs/src/main/scala/docs/UserConfigurationModifier.scala

This removes the generated system-properties fields for new user configuration
settings. The reason for this is that new user configuration settings aren't
actually available as system properties anymore.
This also adds in a small section about enabling inline decorations to the
decoration protocol page.
Fixes #2439

Update docs on system-properties and inline decorations.

---

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala
metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Icons.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/parsing/TokenEditDistance.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Previously, we added inferred type for synthetic types, however it's also possible to use semanticdb to get type of definitions.
To that end in this PR showing type was implemented in the following steps:
1. Trees for the file are taken from the cache.
2. Tree is searched for any definitions that do not have a declared type and ranges for those are returned.
2a. If the definition is a method we additionally calculate the position for the type to be shown.
3. We go through occurences and if a symbol is a definition and range was found previously to not contain declared type, the new decoration is added.
3a. For methods we use the position previously calculated to show the type.
A better type printing for tuples and functions was also added to show:
- `(Int, String)` instead of `Tuple2[Int, …

Add type decorations for definitions

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Totally forgot about adding those and turns out it's not that hard to do. `CaseGenerator` is coming from Dotty and will not work for a while, but should start once we get symbol information inside semanticdb generated by the Scala 3 compiler.
If anyone has any ideas, what we might be missing still, let me know!

Add support for type decorations in for comprehensions and patterns

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

-  added type decorations for function params
-  remove type decoration from bound patterns, which can cause duplication:
`a @ T.Comment()` would show `a: T.Comment @ T.Comment()`

Minor adjustements to type decorations

---

build.sbt
metals/src/main/java/scala/meta/internal/watcher/DirectoryChangeEvent.java
metals/src/main/java/scala/meta/internal/watcher/hashing/FileHasher.java
metals/src/main/java/scala/meta/internal/watcher/hashing/HashCode.java
metals/src/main/java/scala/meta/internal/watcher/hashing/Murmur3F.java
metals/src/main/scala/scala/meta/internal/metals/FileWatcher.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

As of https://github.com/scalameta/metals/pull/2014 we replaced the
directory watching functionality with that of Swoval. However, we do
re-use some of the functionality of directory-watcher, mainly the
DirectoryChangeEvent and some hashing utils that it utilizes. This
change removes the full directory-watcher dependency but copies over the
few necessary classes from that library into a
scala.meta.internal.watcher package.
Closes #2365

Remove dependency on io.methvin:directory-watcher.

---

metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala

Previously we would use string for `PresentationCompiler.semanticdbTextDocument` method, which is not neccessary as we need to turn it back into URI anyway. This seems to also cause possibly cause the issues with:
```
Feb 01, 2021 11:32:01 AM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: null
java.nio.file.ProviderMismatchException
at sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:200)
at sun.nio.fs.UnixPath.relativize(UnixPath.java:410)
at sun.nio.fs.UnixPath.relativize(UnixPath.java:43)
at scala.meta.internal.pc.SemanticdbTextDocumentProvider.$anonfun$textDocument$2(SemanticdbTextDocumentProvider.scala:38)
at scala.Option.map(Option.scala:230)
at scala.meta.internal.pc.SemanticdbTextDocumentProvider.textDocument(SemanticdbTextDocumentProvider.scala:37)
```
I also added a Try …

Pass URI to `semanticdbTextDocument` method and fix possible issues

---

metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala

For vscode extension, this configuration option is defined as `enum`.
In order to have a way to select `default` behavior where this Scala version might be inferred from build targets, I've added [`automatic`](https://github.com/scalameta/metals-vscode/pull/494/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R195) value.

Fallback Scala version - filter out `automatic` value

---

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala
metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Icons.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

While browsing Metals with the new feature I came upon some issues in non-obvious cases. I try to fix them all here:
- existential types are not that useful to show in the type decorations, so I changed to show the base type only. It happens in a situation like:
```scala
val job = ec.submit(new Runnable {
override def run(): Unit = {
launcher.runLauncher(
bloopVersion,
skipBspConnection = false,
Nil
)
finished.success(())
}
})
```
aside from existential type in the above example we also had an issue with a locally defined type. Instead of `local123` we now just print `_`, which is also returned by normal hover.
- structural types now show with `...` only if there is something contained in them
- with types like `new A with B {}` no longer show `AnyRef` as first type

Fix printed inferred type for complex types

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala
tests/unit/src/main/scala/tests/BaseRangesSuite.scala
tests/unit/src/test/scala/tests/ReferenceLspSuite.scala
tests/unit/src/test/scala/tests/WorkspaceSymbolLspSuite.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

This fixes a number of issues:
- we would throw an exception when interactive semanticdb passed a Scala file path to ReferencesProvider
- no updates on sbt files would get indexed
Now instead of throwing an exception we just forward the scala path and additionally the current workflow was changed to:
| standalone file change -> create a text document in InteractiveSemanticdb -> if succesfull pass information to semanticdbIndexer -> pass information to all the need text documents

Fix issues with references in standalone files

---

metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala

This is just a small docs update. I recently added an embedded doctor to `nvim-metals` and had to look this up again after realizing it wasn't in the docs anywhere.

Update the doctor docs in client commands

---

website/blog/2021-02-02-metals-retro-part1.md

So I want to get a bit of feedback on this. It's really important for me to make sure that we not only share some of the survey results, but also talk about some of the actions that came out of them.
My idea is to have a 2 part series where in part 1 we talk briefly about some of the results, address a couple things that stood out to me when reviewing the initial results, and talk a bit about some of the stuff that we've already done to address certain things. Or just address certain things that already exist that people may not be aware of. My plan would then be to cover the following in the next one, Part 2.
- Build Tool support - what does this look like moving foward
- BSP Server support - talk a bit about solidifying sbt BSP support and also introducing Mill BSP support
- Other large …

Add in part one of a metals retrospective blog post

---

tests/unit/src/test/scala/tests/TreeViewLspSuite.scala

Tt seems like animal-sniffer-annotations.jar disappeared from the libraries, which unexpected as we keep the same versions here, but it should not be caused by an issues on Metals side.

Fix TreeViewLspSuite

---

docs/integrations/new-editor.md
metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala
metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/CodeLensProvider.scala
metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/CodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/WorksheetCodeLens.scala

Previously, only way to discover the copy worksheet command would be to run it manually, which is always an additional barier. Now, it's possible to use the code lense that is shown at the top of the file.
This is how it looks in VS Code:
What worries me is that we rely on the name of the command in the client to be `metals` + the actual command id. Otherwise, the server command might be invoked without handling it properly. It's kind of implicit requirement for the clients and there is no way to discover if a client actually contributes it. I have no idea currently how to work around it :/

Add code lens to easily discover copy worksheet command

---

metals/src/main/scala/scala/meta/internal/bsp/BspSession.scala
metals/src/main/scala/scala/meta/internal/bsp/MetalsBspException.scala
metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/ImportedBuild.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
tests/unit/src/test/scala/tests/DebugProtocolSuite.scala

So there is no user facing change in this, it's mainly just moving stuff
around a bit, and then trying to improve some logging. This is in
response to #2347 and should close it, unless we really want to do some
more refactoring. Mainly in that ticket there was a situation where we
were unable to get sources for a build target, and therefore the
connection to the build server didn't work, and the message was that the
connection failed, and check the logs for more details. However, the
logs aren't helpful at all:
```
2021.01.05 16:37:03 ERROR Failed to connect with build server, no functionality will work.
org.eclipse.lsp4j.jsonrpc.ResponseErrorException:
at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
at …
```

A bit of refactoring around BSP connection and Build Import.

---

metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Command.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/InsertInferredType.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala-2/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/test/scala/tests/codeactions/BaseCodeActionLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/CreateNewSymbolLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/InsertInferredTypeLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/StringActionsLspSuite.scala

Inferred type code action is responsible for adding type annotations for any place that might need it such as:
- val/var declaration
- method declaration
- pattern matches
- lambdas
- for comprehensions
The code action itself has two steps:
1. Using the scalameta parser we check if there is a name at a given position and if it belongs to a tree node that doesn't have the type declared. If both is true we return code action with the `insert-inferred-type` command.
2. When the `insert-inferred-type` code action is run we use the presentation compiler and the new provider `InferredTypeProvider` to calculate the needed edits that actually add the type. This also includes any imports that are needed.
To that purpose there are two suites that test this behaviour:
- InsertInferredTypeSuite - …

Add insert inferred type code action

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

It seems that in some cases clients like VS Code might actually open a document that `didDefinition` is made on, which would previously make focusedDocument point to the wrong thing. Now we only change focusedDocument on `didOpen` if the client does not support the didFocusProvider.
The change was done in https://github.com/scalameta/metals/commit/679cde2c8f12e6e86d75ab84be57de35fd622285 probably to make sure that focused document is set on open, however didFocus is sent properly at that time, so it's not really needed.

Only set focusedDocument on `didOpen` without didFocusProvider

---

metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala
metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileProvider.scala
tests/unit/src/test/scala/tests/AddPackageLspSuite.scala
tests/unit/src/test/scala/tests/NewFileLspSuite.scala

Previously, we would not any backticks when generating files from the `New Scala File` command or when a file was created with a package name inserted automatically. Now, we wrap each part in backticks if needed.
Fixes #2375

Fix issues where created files should use backticks

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionItemResolver.scala

This probably isn't that important, but I noticed this recently and had
to fix it in a completion extension
https://github.com/hrsh7th/nvim-compe/pull/177.
The detail field is optional in the `CompletionItem` so it might be best
to just not set it if the detail is `""`. If not, it may cause weird
things like showing an empty resolve float if the client doesn't have
the logic to filter that out.

Don't populate completion detail if it's an empty string.

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

@tgodzik and I talked a bunch off line about this but the jist of the issue is that with this change if you open `test.worksheet.sc` directly now it won't evaluate. Even after that if you directly open another `second.worksheet.sc` it still won't evaluate since focused document isn't changed on the `didOpen` after the listed commit.
We need to rethink this a bit since the original issue with VS Code still exists.

Revert https://github.com/scalameta/metals/commit/519c6414797edcc35d5d714b220c7d7d140c4b4

---

metals/src/main/scala/scala/meta/internal/metals/ActiveFiles.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Some clients when using peek functionality might send didOpen and didClose notifications immediately one after the other. In this case we don't actually want to change the focused document so we revert to the one that was most recently focused.

Revert to recently focused document if the current one was immedietally closed

---

mtags/src/main/scala-2/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala-2/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/Signatures.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala
tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala
tests/unit/src/test/scala/tests/CompletionLspSuite.scala

A while ago there were some changes to the scalafix implementation of printing types, which is actually based off Metals. While investigating some issues with importing, I decide to backport those fixes to Metals. That backported code is mainly the `MetalsGlobal.shortType`, `ShortenedNames.nameResolvesToSymbol` and `ShortenedNames.tryShortenName` methods.
Besides that:
- changed the location of where we get context to the actual place of the cursor, while keeping a separate context for the imports
- made sure that stale symbols are to looked up in relevant situations, which is anything that inserts code
- fixed the tests to adhere to these changes, where you can see most of the improvements/changes
This also fixes https://github.com/scalameta/metals/issues/1253 and some issues with insert …

Improve short names when importing

---

build.sbt
metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala

- load [`sbt-debug-adapter`](https://github.com/scalacenter/scala-debug-adapter/releases/tag/v1.0.0) in the `sbt-metals` plugin 
- activate the `run` and `test` lenses on sbt
- add the `sbt-jdi-tools` plugin in the meta-meta build to ensure that the JDI jar is loaded in sbt. It's needed by `sbt-debug-adapter` as explained [here](https://github.com/scalacenter/scala-debug-adapter/releases/tag/v1.0.0).

Integration of sbt-debug-adapter

---

docs/editors/emacs.md

From your last blog I got you were missing an explanation on how to annotate stack traces. I did not know about this feature, and now I am using it! Also found there is likely a bug in lsp-mode.
Anyway any feedback for this documentation would be useful!

add explanation on how to annotate stack traces for Emacs

---

mtags/src/main/scala-2/scala/meta/internal/mtags/ScalaMtags.scala

To enable finding symbols in library sources we use the parser to find the exact symbol that we need. Previously it would not work for Scala 3 due to using the Scala213 dialect. Now, we fallback to Scala3 dialect in case of issues, which is a temporary workaround until https://github.com/scalameta/metals/issues/2493 is fixed.
I tried to do it here, but it turns out it's a much more compelx issue and would not want to merge it before the release.

Fallback to Scala3 dialects when parsing library sources

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersionSelector.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
tests/slow/src/test/scala/tests/feature/WorksheetCrossLspSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/ClassBreakpointSuite.scala
tests/unit/src/test/scala/tests/DocumentSymbolSuite.scala
tests/unit/src/test/scala/tests/FoldingRangeSuite.scala

In one of the previous PRs we changed the parser to take into account the real dialect of the code to parse based on the build target the file is located in. Recently, we also added the possibility to change the default Scala version, which allowed users to use standalone Scala 3 worksheets. We haven't however changed the parser dialect that is used for those worksheets, which results in Scala 3 specific code to be marked as an error. In this PR I am making the parser use the correct parser dialect.

Fix standalone Scala 3 worksheets

---

docs/editors/overview.md
metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala
mtags/src/main/scala/scala/meta/internal/pc/WorksheetSemanticdbProvider.scala
tests/cross/src/test/scala/tests/pc/PcSemanticdbSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
tests/unit/src/test/scala/tests/ReferenceLspSuite.scala

Thanks to the recent work on generating semanticdb for sbt, it's also possible to generate semanticdb for worksheets and in this way allow:
- references
- rename
- document highlight
The only thing missing is `Go to implementations` which doesn't work for anything that is not indexed globally. We don't want to index worksheets globally as their symbols are local to the file they exist in.
Fixes https://github.com/scalameta/metals/issues/2540

Fix rename/references for worksheets

---

metals/src/main/scala/scala/meta/internal/parsing/DocumentSymbolProvider.scala
tests/input3/src/main/scala/example/GivenAlias.scala
tests/unit/src/test/resources/documentSymbol-scala3/example/GivenAlias.scala

VSCode client throws an error when it receives a symbol with an empty name.
<details>
<summary>Log</summary>
```
[2021-02-23 20:09:09.612] [renderer1] [error] name must not be falsy: Error: name must not be falsy
at Function.validate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:546:315)
at new T (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:546:264)
at new T (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:531:904)
at asDocumentSymbol (/home/dos65/.vscode/extensions/scalameta.metals-1.9.13/node_modules/vscode-languageclient/lib/protocolConverter.js:462:22)
at asDocumentSymbol (/home/dos65/.vscode/extensions/scalameta.metals-1.9.13/node_modul …
```

DocumentSymbolProvider: set name as " " in case if it's empty.

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersionSelector.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/slow/src/test/scala/tests/feature/AmmoniteSuite.scala
tests/unit/src/test/resources/documentSymbol-scala3/example/Extension.scala
tests/unit/src/test/resources/documentSymbol-scala3/example/Ord.scala

Issues encountered during the update:
- Scala presentation compiler will no longer complete type symbols on `a.b.Name` in positions where type is not allowed, which is actually a bugix, but we needed to change some test
- Ammonite does not have support for 2.13.5 yet and even if it has we can't currently update. In order to make the experience smoother for the users I added the logic in VersionSelector that will fallback to the last Ammonite supported Scala version instead of just failing
- there was a fix in scalameta for indented regions that changed their ends, which needed to be updated in the expect tests
- one test started to fail with 2.13.5 - is unclear if the behaviour was ever fixed in Metals or whether we relied on the compiler #2546

Add support for Scala 2.13.5

---

metals/src/main/scala/scala/meta/internal/parsing/DocumentSymbolProvider.scala
tests/input3/src/main/scala/example/OrType.scala
tests/unit/src/test/resources/documentSymbol-scala3/example/OrType.scala

[Scala3] DocumentSymbols - use proper dialect for tree rendering

---

mtags/src/main/scala-2/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala

Fixes https://github.com/scalameta/metals/issues/2556
I am so so very sorry about that. Tried to squeeze in too much into one release.

Remove println in SemanticdbTextDocumentProvider

---

metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
tests/unit/src/test/scala/tests/worksheets/WorksheetLspSuite.scala

I ran across this today and I knew to look in the logs right away to see
why my worksheet wasn't working, but I imagine in the situation where
someone is trying to use a dependency in their worksheet and it's not
the correct dep, it fails silently without any indication that something
is going wrong. So this change just captures if it's a resolution issue,
grabs the first line from coursier and actually shows it to the user.

Show an error to the user if they are using a bad dep in a worksheet.

---

metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala

Fixes https://github.com/scalameta/metals/issues/2537
Previously, renames would not work, because we would group locations by URI string, which might sometimes, especially on windows, be different:
`"file:///c%3A/Users/Tomasz/Documents/Work/scala-example/src/main/scala/Base.scala"`
vs
`"file:///C:/Users/Tomasz/Documents/Work/scala-example/src/main/scala/Base.scala"`
This fixes the issue by grouping via AbsoluteFile, which is the same for both cases.

Fix issues with renames on Windows

---

metals/src/main/scala/scala/meta/internal/troubleshoot/ScalaProblem.scala

This was slightly confusing to see:

Update metals doctor hint to match exact 'Import build' instead of 'Build import'

---

.github/workflows/ci.yml
.github/workflows/release.yml

~Just checking how this will work out.~ `v6` should work better out-of-the-box with multiple jobs and matrices (better isolation between the jobs and the matrix entries).

Update cache-action to v6

---

.scalafmt.conf
mtags/src/main/scala-3.0.0-M1/scala/meta/internal/mtags/VersionSpecificEnrichments.scala
mtags/src/main/scala-3.0.0-M2/scala/meta/internal/mtags/VersionSpecificEnrichments.scala
mtags/src/main/scala-3.0.0-M3/scala/meta/internal/mtags/VersionSpecificEnrichments.scala
mtags/src/main/scala-3.0.0-RC1/scala/meta/internal/mtags/VersionSpecificEnrichments.scala
mtags/src/main/scala-3.0/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala

To test out the most recent version of scalafmt I created a standalone snapshot runner via these [instructions](https://scalameta.org/scalafmt/docs/installation.html#standalone)
The actual command was:
```
coursier bootstrap org.scalameta:scalafmt-cli_2.13:2.7.5+159-c8fb1659-SNAPSHOT \      
-r sonatype:snapshots --main org.scalafmt.cli.Cli \
--standalone \
-o scalafmt
```

Run recent snapshot of scalafmt on Scala 3 sources

---

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/1086
This however will not work the other way. Main parameter will not be renamed when rename is started from the named parameter. That needs to be fixed in https://github.com/scalameta/metals/issues/1553
At first I tried to change the occurrence of the named parameter inside scemanticdb, that however proved to be more difficult and I was not 100% sure if the current status is actually wrong. Since it involves quite a bit of changes for the other tools I decided against going that way.

Fix renaming named parameters in constructors

---

metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala

This occurs when Metals attempts to read the file while Bloop is still writing to it here...
https://github.com/scalameta/metals/blob/dc0da653ead60396832d8b783e152acae368b38f/metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala#L92
Linux/Mac seem to allow reading of the file but, as it's only partially written, `com.google.protobuf.InvalidProtocolBufferException` is thrown and handled by Metals
Windows doesn't allow access to a locked file so throws a different exception: `java.nio.file.FileSystemException` but this isn't handled.
I think this is just a case of having to handle `FileSystemException` in the same way as `InvalidProtocolBufferException`.
I've tried this PR locally and the exception no longer appears.  I guess there's a worry that handling this will mask …

Handle changed but locked files on Windows

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/InsertInferredType.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

Previously, we fixed renaming to also work with renamed imports in a local scope, however we haven't check if it works at the actual rename position. Now, the test is added and the case is fixed.

Fix renaming renamed imports when cursor is at the rename

---

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
tests/unit/src/test/scala/tests/ReferenceLspSuite.scala

Previously, we would search the current file, when searching for references, for alternative references such as object reference of a case class. This caused us to get different results depending on where we invoked textDocument/references. Now we check those alternatives in the definition file.
Additionally, we now also:
- check for case classes if searching from an object, which is synthetic
- check for field if searching from constructor parameter
Fixes https://github.com/scalameta/metals/issues/1553

Find alternative symbol references when not searching from the definition file

---

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
tests/unit/src/main/scala/tests/BaseRenameLspSuite.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

In cases where a symbol name is not valid we should automatically wrap it in backticks

Automatically backtick symbols when renaming

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
tests/unit/src/test/scala/tests/DebugDiscoverySuite.scala

Previously when there was no semanticdb found for the file you were
trying to test via `testFile` an exception would happen and the user
wouldn't be notified at all. Now they are shown a bit clearer message
similar to that of when navigation fails for a similar reason.
The second part of this adds in a check so when a user is using debug
functionality a check is made to ensure they have metals status enabled
before sending the status, and if not it handles messages and logs as
well.
Fixes #2598

Show better message if no semanticdb is found for testFile.

---

docs/integrations/new-editor.md
metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProtocol.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala

This is meant to address the situations where a DAP client may not be
able to handle color codes in the DAP output. Instead of trying to build
this into both sbt and Bloop I think it's just easier to strip it here
and put it behind a flag. The normal behavior is unchanged, but now a
client can set `stripDAPOutputColor = true` and get the color codes
stripped.
Closes #2061
This should also take care of:
- https://github.com/scalameta/nvim-metals/issues/107
- https://github.com/scalacenter/bloop/issues/1478

Add init option to strip color from DAP communication.

---

build.sbt
mtags/src/main/scala-2/scala/meta/internal/docstrings/ScaladocParser.scala
mtags/src/main/scala-2/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/Identifier.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala

While testing out https://github.com/scalacenter/scala3-migrate I decided to run it on mtags module to see if there is anything that we can improve.
This included:
- changes to scalac options for Scala 3
- scalafix rewrites that deals with 2.13 deprecations, which weren't sctrictly neccessary, but might be usful for the future if we decide to move some of the Scala 2 code
- I also added a test case for one of Scala 3 issues we had (hovers on extension methods)

Run Scala 3 migrate on mtags sources

---

build.sbt

It seems like the rule was not updated automatically and there are some incompatibilities with 0.4.4
https://github.com/liancheng/scalafix-organize-imports/releases/tag/v0.5.0

Update organize imports rule to 0.5.0

---

docs/editors/online-ides.md
website/i18n/en.json
website/pages/en/index.js
website/sidebars.json
website/static/css/custom.css

Update(@tgodzik)
This adds the additional `online-ides` page together with an ability to run a custom workspace from the start page.

Add documentation for online IDEs

---

metals/src/main/scala/scala/meta/internal/worksheets/WorksheetClassLoader.scala
tests/unit/src/test/scala/tests/worksheets/WorksheetLspSuite.scala

Instead of passing in `null` when we extend ClassLoader in our
MdocClassLoader this passes in the actual parent since on Java +9 when
using `null` that's the bootstrap classloader which doesn't contain
modules like java.sql.
Big thanks to @smarter pointing this out in https://github.com/lampepfl/dotty/pull/11658.
Fixes #2187

Use correct parent classloader for worksheets.

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala

Previously, if a symbol was already overriden, we would add the override flag twice. Now, we check if that flag is already containe din parent.

Do not insert override twice

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala

Previously for a higher kinded type like:
```scala
TypeRef(
pre = <noprefix>,
sym = class Resource,
args = List(
PolyType(
typeParams = List(type x),
resultType = TypeRef(
pre = <noprefix>,
sym = type F,
args = List(TypeRef(pre = <noprefix>, sym = type x, args = List()))
)
),
TypeRef(pre = <noprefix>, sym = class Unit, args = List())
)
)
```
we would print:
```scala
Resource[[x]F[x],Unit]
```
Which is nothing that can actually work in the code. Instead, it should just be `Resource[F, Unit]` as the type constructors can't really appear in signatures (I think)
Fixes https://github.com/scalameta/metals/issues/2558
I am not 100% sure of this solution, but I this seems to work now. I anyone has a better idea about `PolyType` or higher kinded types do let me know. As it stands, this should not …

Make sure higher kinded functions in signatures are inferred properly

---

docs/editors/user-configuration.md
docs/editors/vim.md
metals-docs/src/main/scala/docs/UserConfigurationModifier.scala
metals-docs/src/main/scala/docs/WorksheetModifier.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
website/i18n/en.json
website/sidebars.json

This makes a few changes to the docs. Noticeably it adds two things:
1. It adds a section for user configuration. I've gotten the request a
few times to add something like this and have gotten comments in
the past that it's not always clear what configuration options are
available. We did have these in the site, but they were buried
under integrating a new editor. I didn't remove them from there as
they are still useful to someone creating a new extension, but made
a more user-focused intro and added them to the forefront.
2. Just add in an example of scalac imports.
Let me know what you think of this.

A few changes to docs including a User Configuration section.

---

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
tests/unit/src/test/scala/tests/worksheets/WorksheetLspSuite.scala

It seems that somehow when using akka in worksheets the actual typesafe config lib that is being loaded is coming from mdoc, not from akka. Which means that akka will not work and throw ClassNotFound exceptions since mdoc has 1.2.1 version on the classpath. We should also fix it in mdoc, but I have currently no idea how to fix it (we should be using the correct classpath currently), so I decided to make the classpath a bit thiner as worksheets do not need everything that mdoc brings. Especially, as there are no config options, so no need for the typesafe config.
Fixes https://github.com/scalameta/metals/issues/2525 hopefully

Fix issues with old typesafe config in the worksheets

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/AdjustLspData.scala
mtags/src/main/scala-2/scala/meta/internal/pc/CompletionItemResolver.scala
mtags/src/main/scala/scala/meta/internal/metals/TextEdits.scala
mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
tests/cross/src/main/scala/tests/BaseCompletionSuite.scala

CompletionItem.textEdit is no longer just `TextEdit`, but now is `Either[TextEdit, InsertReplaceEdit]` - this was the main issue with migration.
Supersedes https://github.com/scalameta/metals/pull/2657 
Actually `0.12.0` just got released, so updating to that.

Update org.eclipse.lsp4j to 0.12.0

---

mtags/src/main/scala-2/scala/meta/internal/mtags/Scala3ToplevelMtags.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/ScalaMtags.scala
mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
tests/input3/src/main/scala/example/ToplevelDefVal.scala
tests/unit/src/test/resources/definition-scala3/example/ToplevelDefVal.scala
tests/unit/src/test/resources/documentSymbol-scala3/example/ToplevelDefVal.scala
tests/unit/src/test/resources/semanticdb-scala3/example/ToplevelDefVal.scala

`Paths.get("jar:file:...")` doesn't work on Windows.

Mtags: fix Scala3 parsing for Windows.

---

build.sbt
project/InputProperties.scala

Seeing that the old style is now deprecated in sbt moving forward, I
figured it'd be best to just align everything behind the unified slash
syntax right away. I was playing around with the scalafix rule for this
that was created, and thought Metals was a good test.

Get behind unified slash syntax.

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/StringActions.scala
tests/unit/src/test/scala/tests/codeactions/StringActionsLspSuite.scala

This pull request should close #2666, by adding two code actions: 
1. Quickly interpolate a string or a multiline string
2. Quickly remove an interpolated string, if the string doesn't contains "Splice" parts.
Fixed failing tests due to new code actions and also added some for the new features.

Add code action to add/remove string interpolation

---

metals/src/main/scala/scala/meta/internal/metals/ScalacDiagnostic.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/OrganizeImports.scala
tests/unit/src/test/scala/tests/codeactions/OrganizeImportsLspSuite.scala

This just re-uses a lot of the logic that already existed for organize
imports, but now we just do a check to see if the diagnostics in the
codeaction params contain a message about unused import, and if so,
offer this as a code action.
Fixes #2687  (This was a great one to do on stream 😆 )

Offer organize imports when on an unused import.

---

.github/ISSUE_TEMPLATE/bug_report.md
build.sbt
metals/src/main/scala/scala/meta/internal/metals/Warnings.scala

Previously, when checking for semanticdb if it was missing we would report it based on the classes directory. Now, we report it based on the actual place we are looking for it using targetroot.

Make sure that a correct targetroot is reported

---

build.sbt

I haven't noticed this one in the previous PR, because the failed test came from slow tests :/

Don't override testSettings in unit tests

---

build.sbt

I removed this in https://github.com/scalameta/metals/pull/2703 and shouldn't have. It's causing no test to be detected and ran.

Add testframeworks back in to ensure tests run.

---

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

Change 0.0.0.0 to 127.0.0.1 to avoid socket connection timeouts
Previously, tests would often fail for DAP and the only way to fix it seems to force 127.0.0.1, which seems a much safer option.
Thanks to @dos65 for the hint!

Fix issues with DAP tests

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala

I'm currently working on bloop config generation from bazel files.
And found difficulties with generated sources (scalapb for example).
Currently i'm attaching them as external dependencies with jars generated by bazel.
It's common in bazel world to place generated files inside `.srcjar` files but they are ignored by metals.
It's a bit hacky but i hope it will be accepted 😄

Treat .srcjar as jars

---

build.sbt
project/plugins.sbt

I previously removed a bunch of settings, but I forgot about the munit-sbt plugin, which now fails on CI.
Most recent failures: https://github.com/scalameta/metals/actions/runs/771330085

Remove munit sbt plugin to fix CI

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateNewSymbol.scala

Most clients don't have an issue with this, but I just hit on a case
where the server providing `null` here is causing issues when the client
then tries to encode the value to send back and it chokes on it. In this
specific case, we do this step later if it's passed in as null, but
since we already have what we need to fill in the parentUri where the
new file will be created, we just do that right away instead of passing
in `null`.

Add in the parentUri when offering the newSymbol code action.

---

metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

This fixes #2341, which causes a user to get an error message from Bloop
if the user attempts to use Metals for the first time on an sbt
workspace that already contains a `.bsp/sbt.json` file. The issue is
that Metals would think that since there is a `.bsp/<entry>` already
there, it's auto-connectable. So even though it realizes it should use
Bloop, instead of waiting for the users choice via the prompt, it will
try auto-connecting to Bloop right away causing the error outlined in
the issue.
We know add another check to ensure that if there is a `.bsp/sbt.json`
file in the workspace the first time Metals is opened that we don't
attempt to auto-connect _unless_ there was a specific decision made
(which will be never if it truly is the first time a user is opening
this workspace). Then …

Add extra check before auto-connecting to server.

---

docs/editors/emacs.md

- `lsp-metals` can install metals server automatically now.
- `lsp-metals-treeview-show-when-views-received` was removed.
- changing `eglot-server-programs` isn't necessary - it already has metals.
https://github.com/emacs-lsp/lsp-metals/pull/47

Update emacs documentation.

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/main/scala/tests/BaseAutoImportsSuite.scala
tests/cross/src/test/scala/tests/pc/AutoImportsIssueSuite.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala

Previously, we would not check if the file renames were all working with an actual symbol. This was not a problem previously, but recently we added a check that would always try to use renamed imports, which would break in case of a NoSymbol. Now, we jsut check it before adding to the renames map.
Fixes https://github.com/scalameta/metals/issues/2736

Fix wrong import when working with akka

---

metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionCommandData.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala
tests/slow/src/test/scala/tests/feature/CrossCodeActionLspSuite.scala
tests/unit/src/main/scala/tests/ResourceOperations.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/main/scala/tests/codeactions/BaseCodeActionLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/CreateNewSymbolLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ExtractRenameMemberLspSuite.scala

This pull request should close #2691 
The "Extract Class" code action will appear on classes if:
- There is more than one class definition in the file. Inner classes are not counted
- The class doesn't extends Traits/classes defined as `sealed`  
- The class itself isn't `sealed`
The new file will have the name of the Class, if doesn't exists already (otherwise the file creation will fail and every other TextEdit action should not happen)
In the new file there will be all the package definition and imports definition that appear before the class definition in the source file, in the same order.
Another code action is added, as suggested in the issue: "Rename file as class".
This code action appears when there is a single class definition in the file, that has a different name than the …

Code action to move classes to their own files if requirements are met

---

mtags/src/main/scala/scala/meta/internal/mtags/KeywordWrapper.scala

Most of the soft keyword do not need to be backticked. Follow issue for the more problematic ones  https://github.com/scalameta/metals/issues/2795

Remove most soft keywords from being backticked.

---

mtags/src/main/scala-3/scala/meta/internal/pc/CompletionProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Previously, methods would be shown before field. Now, class fields are first.

Fix field ordering in completions

---

mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompletionPos.scala
mtags/src/main/scala-3/scala/meta/internal/pc/NamesInScope.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

Fixes the following cases related to  `renameConfig` 
- incorrect owner edit in completion
```scala
object Main {
StringBuilder@@ // StringBuilder - scala.collection.mutable
}
// --apply--
object Main {
mutable.StringStringBuilder
}
```
- owner/renamed owner import duplication
```scala
import scala.collection.mutable
object Main {
StringBuilder@@ // StringBuilder - scala.collection.mutable
}
// --apply--
import scala.collection.mutable
import scala.collection.mutable
object Main {
mutable.StringBuilder
} 
```
~~Unfortunately, tests on these cases are ignored because it's needed to fix our `TextEdit.applyEdits` implementation. 
I've tried to fix it but it seems like a non-trivial task. I'm going to look at it but want to merge this PR to not include these bugs in the release.~~

[Scala3] Completions - fix `Renamed` and `specifyOwner` Autoimports application

---

bin/test-release.sh
build.sbt
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersionSelector.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/slow/src/test/scala/tests/feature/FoldingCrossLspSuite.scala

Scala 2.13.6 also includes the support for using some of the Scala 3 syntax. When the proper options is detected "-Xsource:3", we now change the dialect to be able to parse the enriched syntax. Additionally, we also now make it the default in case we don't know anything about the scalac options.

Add support for Scala 2.13.6

---

metals-docs/src/main/scala/docs/RequirementsModifier.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Group Scala versions in docs to make it easier to see which are supported

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

Previously, when the build was not imported and the fallback version set to Scala 3.0.0, we would get parsing errors in sbt files. Now, we added an explicit check to avoid it.
Fixes https://github.com/scalameta/metals/issues/2549

Publish scalameta parser diagnostics for Scala 3

---

metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClassesFinder.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

This PR should close #2766  .
It was added a simple message when trying to attach a debugging session without a buildTarget.
Previously it just threw a `NoSuchElementException` error visible in the metals.log, without any other information.
The draft of the new error message is 
> "Debugger configuration is missing 'buildTarget' param."

Fix error for remote debugging when missing build target

---

mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala

Previously, the new import might end up in the middle of the comment. Now, if no package or import is defined, we put it into the first line.

Fix issues when importing in an empty package

---

build.sbt

Newest pprint version now support 2.11, 2.12, 2.13 and 3.0.0. This also means that it will not work on the RC versions, but since we plan to remove those in the near future and CI tests do not add pprint, I think we are safe to simplify adding it.

Update pprint to newest version

---

metals/src/main/scala/scala/meta/internal/troubleshoot/ProblemResolver.scala

This has been causing some confusion, and we shouldn't warn about this. From what I can tell looking at the semanticdb related stuff in Scala3, this pretty much always seems to just be generated from the target and then made relative. From playing around, while this warning appears, it's often a red herring since everything is fine, but people assume something may be wrong or incorrectly blame the sourcepath not being set.
It doesn't mention anything about it [here in the docs](https://docs.scala-lang.org/scala3/guides/migration/tutorial-prerequisites.html#semanticdb) and the few places I see where it's used, it's often put together:
https://github.com/lampepfl/dotty/blob/b7d2a122555a6aa44cc7590852a80f12512c535e/compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala#L613 …

Don't warn about sourceroot for Scala 3

---

mtags/src/main/scala-3/scala/meta/internal/pc/Signatures.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SymbolPrinter.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

This improves a couple of things:
- show shorter type if it's importable (also needed further on)
- when hovering on package it's full path is shown (the change was needed due to the previous one)
- show final modifier
- show enum and case instead of final object and final val
The first change was needed also for properly writing types when doing inferred type action or overrides. The other changes stemmed from that. I think we can still further improve the hover information later on, but I don't want to do everything in one PR

Print better types on hover

---

build.sbt

Unfortunately, pprint `0.6.6` isn't published for RC* versions

Fix pprint dependency for Scala3 RC versions

---

build.sbt

~~We recently updated Bloop to use the scala-debug-adapter library, which seems to work correctly when terminated is set to false. Bloop always seemed to terminate the process irrelevant of the flag.~~
Ok, since it's failing in almost every PR and my change is not helping I will take a look at it later on.

Revert Bloop version upgrade

---

build.sbt
mtags/src/main/scala-3/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SymbolPrinter.scala
tests/cross/src/test/scala/tests/hover/HoverDefnSuite.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala

This also includes a bunch of fixes that were kind of a chain reaction due to some tests failing for 3.0.1-RC1
- print outer type instead of singleton type for objects
- make sure to take method signature into account when filtering symbols

Add support for Scala 3.0.1-RC1

---

metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/OrganizeImports.scala
tests/slow/src/test/scala/tests/feature/CrossCodeActionLspSuite.scala
tests/unit/src/main/scala/tests/codeactions/BaseCodeActionLspSuite.scala

Since 0.9.29 it's possible to use most of the existing rules on Scala 3 including organize-imports. This still have 2 caveats:
- unused imports will not be removed since we don't get that information from the compiler
- we will need to run 2.13 scalafix for Scala 3 sources until Scalafix is released for Scala 3. This is only a problem for ExplicitResultTypes, which anyway wouldn't work in Metals.
Fixes https://github.com/scalameta/metals/issues/2856

Enable organize imports for Scala 3

---

metals/src/main/scala/scala/meta/internal/metals/WorkspaceSearchVisitor.scala

Fixes flaky `ClasspathSymbolRegressionSuite.Map#Entry` test.
Testing classpath is messed by netty artifacts that spotted [this problem](https://github.com/scalameta/metals/pull/2814/checks?check_run_id=2763907639#step:5:1187):
- `io:netty.netty-all:4.0.43.Final` - `io.netty.util.collection.IntObjectMap#Entry`
- `io.netty.netty-common:4.1.17.Final` - `io.netty.util.collection.IntObjectMap#PrimitiveEntry`

WorkspaceSearchVisitior - make search more predictable.

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/Keywords.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala

This PR should close #2775, removing the completions when inside comment lines, either multiline like scaladoc or single line `//`.
I am not sure the solution is an optimized one, but I added a similar check to the `isScaladocCompletion` to check whether the cursor is currently in a comment line. In this case it will return a `CommentCompletion` created equally to the `NoneCompletion`, the need to differentiate occurs when checking for possible Keywords completions: if it's a `CommentCompletion` it shouldn't propose the keywords either.
~~+: I need to fix something wrong with Keywords, then should be ready~~

Don't offer completions inside scaladoc and comments

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/codeactions/InsertInferredType.scala
mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/NamesInScope.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Signatures.scala
tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala

This was actually easier to do for some parts, however there are some issues still:
- tuples are not shown correctly when using the presentation compiler, I am working around it by using scalameta to parse the tuple Val and match the type. This doesn't seem to be an issue for more advanced patterns.
- ~~import renames are not correctly picked up, we might need to still fix it in auto imports/signatures~~ this currently works
- type names in case of conflicts do not currently work, I will look into that later on 
Most other things seem to be working fine for now and I believe this is a good step forward.

[Scala 3] Enable inferred type code action

---

metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

This fixes #2866 where with a very fresh project if you don't do a
BloopInstall and then you do a `generate-bsp-config` the explicit choice
gets inserted but the value we have is still the old one. This will
lazily get it to ensure we have the latest.
Note I didn't add an explicit test for this since we do a `bloopInstall`
right away in the build initialize in the Testing Server so it's hard to
actually test without making some large changes to that (which I'd like
to do in a separate pr).

Lazily get explicit choice.

---

build.sbt

Show static variables to fix #2482 (when sbt is used as build server).
Another bump will be needed for Bloop.

Bump sbt-debug-adapter to 1.1.2

---

metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala

`coc-metals` was crazy lenient with this. Nvim core LSP, not so much. Just ensure that the path in the location we are returning is a valid URI.

Ensure a valid URI is returned for non-html analyze stacktrace.

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SelectionRangeProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SelectionRangeProvider.scala
tests/cross/src/main/scala/tests/pc/BaseSelectionRangeSuite.scala
tests/cross/src/test/scala/tests/pc/SelectionRangeSuite.scala
tests/mtest/src/main/scala/tests/BaseSuite.scala
tests/unit/src/main/scala/tests/RangesTextEdits.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/FoldingRangeSuite.scala
tests/unit/src/test/scala/tests/SelectionRangeLspSuite.scala

While I still have a couple things yet to figure out with this, I wanted to through it up here to get any thoughts. Mainly because I'm hitting on (what I would call) unclarity in the spec about how this is exactly supposed to work. The interesting part is that according to the [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_selectionRange), the client can send in multiple positions in the `selectionRangeParams`. From this point, things get interesting. I'll outline the two editors that I was testing in because they behave pretty differently even though the result is pretty much the same.
The steps it follows:
- Grabs the position your cursor is in, and sends that in as a single position
- The selection range is returned and …

Add support for `textDocument/selectionRange`.

---

build.sbt

This is already set in the shared settings for Scala 3, so we don't
need it here as well

Get rid of warning about setting -Xsemanticdb twice.

---

mtags/src/main/scala/scala/meta/internal/pc/CompilerJobQueue.scala
tests/cross/src/test/scala/tests/pc/CompilerJobQueueSuite.scala

Previously, it was possible that `CompilerJobQueue` might start a new `ThreadPoolExecutor` after `shutdown` call that lead to thread hanging and issue with server shutdown.
Fixes: #2820

Fix CompilerJobQueue concurrent access/shutdown

---

build.sbt

When importing Metals build with sbt as the build server, it creates:
- a `bench-jmh` build target, corresponding to the `bench / Jmh` scope
- many `<project>-scalafix` build targets, corresponding to the `<project> / Scalafix` scopes. 
Those are not very useful in the code editor because the user cannot really modify there sources, and the `bench-jmh` build target is very time consuming to import (it triggers the compilation of `bench` to generate the sources).
By setting `bspEnabled` in those scopes, we remove those build targets.
Before:
After:

Exclude Jmh and Scalafix from the list of build targets in sbt

---

docs/build-tools/sbt.md

A colleague of my pointed this out today about how this heading
doesn't make a lot of since. We say 'Install without Bloop', but then
go on to talk about Bloop. I also remove the sentence that says sbt
doesn't implement bsp.

Fix unclear heading in sbt docs.

---

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
tests/unit/src/test/scala/tests/WorkspaceSymbolLspSuite.scala

Resolves https://github.com/scalameta/metals-feature-requests/issues/211
Tried locally in VSCode and it works, though it shows local file results (in the same library file) before workspace ones despite me returning workspace references in a list specifically before local ones (and in tests they are returned in the correct order). Not sure if that's OK and how to fix it otherwise, may need some advice.

Search for symbol references in workspace

---

metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
tests/unit/src/test/scala/tests/worksheets/WorksheetLspSuite.scala

Previously, we would use the default mdoc modifier for worksheets, which uses a class to wrap statements. Now, we use `reset-object`, which wraps statements in an object and allows us to use some of the features not available in classes.
Fixes https://github.com/scalameta/metals/issues/2764 and fixes https://github.com/scalameta/metals/issues/2907

Wrap worksheets in object instead of a class

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcDefinitionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcDefinitionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbSymbols.scala
tests/cross/src/main/scala/tests/pc/BasePcDefinitionSuite.scala
tests/cross/src/main/scala/tests/pc/CrossTestEnrichments.scala
tests/cross/src/test/scala/tests/pc/PcDefinitionSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

Also, fixes `PCDefitionSuite`. Previsously the checking of non-local location wasn't total.

[Scala3] Use symbol search for PC `definitions`.

---

metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsBuildClient.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/OrganizeImports.scala
tests/unit/src/main/scala/tests/TestingDiagnostics.scala
tests/unit/src/test/scala/tests/codeactions/OrganizeImportsLspSuite.scala

I need to figure out a good way to test this as the current framework for code actions don't really have a good way to test stuff while the file isn't compiling, _but_ I wanted to throw this up here right away to get any feedback. The point of this pr is to try to avoid a user seeing an error message all the time about state semanticdb when they refactoring a file. The reason this happens is because they at one point in time had a compiling file which produced semanticdb, and then when they start to refactor and come across unused imports, it tries to calculate the scalafix diff and errors out on stale semanticdb. This makes two changes:
1. The first change has to do when seeing if organize imports can be contributed or not. When a user has `-Ywarn-unused:imports` on and then go over a …

Don't offer to organize imports when there is an error in the file

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcDefinitionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/PcDefinitionSuite.scala

At least fixes the following problem that happens in 2.12:
```scala
// Prevously retuned location was /*List.::*/
Option(1).@@toInt :: List(1,2,3)
```

[Scala2] PcDefinition fix

---

metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/OrganizeImports.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala
tests/unit/src/main/scala/tests/codeactions/BaseCodeActionLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/OrganizeImportsLspSuite.scala

Previously, our organize imports action supported only source.organizeImports kind (implemented in https://github.com/scalameta/metals/pull/1971) because code actions were filtered based on kind parameter (CodeActionProvider:50)
In order to show quickfix action vscode expects that kind of response is quickifx (hence in https://github.com/scalameta/metals/issues/2923 there was no action available although there was one in the response from the server but it was filtered out)
I extracted common logic to the abstract class and create a separate class per kind - IMO this is a good balance between DRY, single responsibility and code readability.   
Another option is to change `kind` in `CodeAction` to Set[String] and support multiple actions simultaneously but I'm not sure about this approach. …

Organize imports quickfix action

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala

This doesn't really cause problems per se, but I just hit on a case
where the completion given by Metals has an empty detail. Then when the
completionItemResolve request comes in, we actually make a check if
there detail is empty there, unless this check is false
https://github.com/scalameta/metals/blob/b5f79053b4e1f63259e9a044dcdef92f4937e43f/mtags/src/main/scala-2/scala/meta/internal/pc/CompletionItemResolver.scala#L15,
then we just return the item, which contains the empty `detail`. This
then results in an empty window appearing for some clients. I ended up
fixing this downstream, so it's not a huge deal, but there is no use in
including the `detail` if it's empty.
Before:
After:

Don't set detail in completion if it's empty.

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala

Due to https://github.com/scalameta/metals/pull/1846 we were actually filtering out a lot of ammonite completions, these were all the scope completions. Now we should properly filer out the wrong compiler completions after $file, because we are using a much more specific condition and the same that we use for AmmoniteFileCompletions.
Fixes https://github.com/scalameta/metals/issues/2973 and fixes https://github.com/scalameta/metals/issues/2122

Fix ammonite type completions

---

build.sbt

They come transitively from scalameta.
Fixes #2800

Mtags3 - exclude scala2 depedencies.

---

mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala

They are not needed for the presentation compiler and break completions.
Fixes https://github.com/scalameta/metals/issues/2977

[Scala 3] Filter out -print-lines and -print-tasty options

---

mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SymbolPrinter.scala
tests/cross/src/test/scala/tests/hover/HoverDefnSuite.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Previously, hover would show extension methods as a simple method. Now, we try to show the extension signature next to the actual extension method signature. This isn't yet perfect as it will not work if a method has a using param as the first one. This is not a big issue though as parameter in both places will work exactly the same.

[Scala 3] Support extension methods in hover

---

metals/src/main/scala/scala/meta/internal/metals/formatting/IndentOnPaste.scala
tests/unit/src/test/scala/tests/rangeFormatting/IndentWhenPastingSuite.scala

Previously, extension groups would not be picked up when pasting and the indentation would be wrong. Now they are handled in the regex. I also split the original regex to make it more readable.

Correctly paste extension groups

---

mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala

In Scala 2 when given the following piece of code and using the insert
inferred type functionality to insert the type of `x`, there is no issue
not including the parens.
This:
```scala
List(1, 2, 3).map{<<x>> => x * 2}
```
Becomes this:
```scala
List(1, 2, 3).map{x: Int => x * 2}
```
However in Scala 3 the compiler will error on this:
```
Diagnostics:
1. parentheses are required around the parameter of a lambda
This construct can be rewritten automatically under -rewrite -source 3.0-migration.
```
This change makes sure that in this scenario in Scala 3 that the parens
are added so that it becomes:
```scala
List(1, 2, 3).map{(x: Int) => x * 2}
```

Include parens on lambda in Scala 3 when inserting type in params with brace.

---

docs/editors/vim.md

Since these can easily get stale, I think we should instead just point
to coc.nvim to get the default mappings for coc.nvim users. This now
only includes the `coc-metals` specific mappings.
This is a follow-up to the convo in https://github.com/scalameta/metals/pull/2985

Point to coc.nvim for defaults rather than have them in here.

---

docs/editors/vscode.md

Just realized that we haven't actually put those anywhere in the docs.
Came up in https://github.com/scalameta/metals/discussions/2992

Mention new run/test commands in the VS Code editor page

---

metals/src/main/scala/scala/meta/internal/metals/formatting/FormatterParams.scala
metals/src/main/scala/scala/meta/internal/metals/formatting/MultilineString.scala
metals/src/main/scala/scala/meta/internal/metals/formatting/OnTypeFormattingProvider.scala
metals/src/main/scala/scala/meta/internal/metals/formatting/RangeFormattingProvider.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/formatting/OnTypeFormattingSuite.scala

Fixes #2502
Previously, newlines inserted by the editor (vscode) were misplacing brackets.
Now, after changes, brackets are indented correctly:
```scala
val before = """|{@@}"""
val shouldBe = """|{
|
|}""".stripMargin
```
```scala
val before = s"""|{@@}""".stripMargin
val shouldBe = """|{
|
|}""".stripMargin
```
```scala
val before = s"""|{@@}
|""".stripMargin
val shouldBe = """|{
|
|}
|""".stripMargin
```
Second commit fixes #2983

Support brackets in multiline strings

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/StringActions.scala
tests/unit/src/test/scala/tests/codeactions/StringActionsLspSuite.scala

Previously, we wouldn't do anything about $ which would break the code.

Automatically convert $ to $$ when changing to string interpolation

---

.github/workflows/sourcegraph.yml
project/plugins.sbt

So I wanted to throw this up here to get others thoughts on this. I've noticed myself a lot more recently relying on Sourcegraph to quickly browse through code online at times especially if looking at a pr. Currently when you're looking at the Metals codebase all the results you're seeing are search-base:
While this is already super helpful, it'd be amazing to have even [better code intelligence](https://docs.sourcegraph.com/code_intelligence/explanations/precise_code_intelligence) when on GitHub. If I'm understanding everything correctly, we can do this by utilizing sbt-sourcegraph to turn the semanticDB created into LSIF for the project, and then upload it to Sourcegraph. @olafurpg am I understanding this correctly?
The necessary stuff is pretty minimal, and I did the actual command in …

Add in sbt-sourcegraph to upload LSIF to Sourcegraph.

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala

Previously, `toFileOnDisk` was always updating dependency source files in
order to keep them up to date.
After introducing `.metals/readonly/dependencies/$jar-name` directories, it is possible to check if the source file is up to date and avoid non-necessary rewrites.
Now, this function also write `jar.meta` file that contains original jar path and modified time that is used for this purpose.
It should fix the flaky `WorkspaceLspSuite.dependencies.` [test](https://github.com/scalameta/metals/pull/2998/checks?check_run_id=3180754434).
I'm not totally sure, but it seems that the reason of failure was related to the concurrent file rewriting. It might happen in references search.
I think that there is chance to get `$path.exists == false` if the operation `Files.copy($jarPath, $path, …

Minimize file rewrites in `.metals/readonly/dependencies`

---

mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala
mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala

Previously, mtags used a hardcoded list of SemanticDB compiler options
to produce SemanticDB text documents from source. This commit makes the
options configurable via PresentationCompilerConfig. The motivation for
this change is that we recently started using mtags for LSIF indexing
Scala projects. To render Scala method/class signatures we need SemanticDB
`SymbolInformation`, which are not emitted by default in mtags since
they are not used by Metals.

Make the SemanticDB compiler options used by mtags configurable.

---

project/plugins.sbt

This version includes a fix so that cross-repo navigation should work
after https://github.com/sourcegraph/sourcegraph/pull/22984 is merged.

Upgrade to the latest sbt-sourcegraph

---

metals/src/main/scala/scala/meta/internal/metals/formatting/IndentOnPaste.scala
tests/unit/src/test/scala/tests/rangeFormatting/IndentWhenPastingSuite.scala

Previously, we would duplicate the rest of the line that was not included in the pasted snippet. Now, we properly format the entire line.

Fix indentation when pasting part of the line

---

build.sbt
project/TestGroups.scala

Previously, first shard would execute much longer than the second one because all new tests were run on it. Now, I added all the missing tests to project/TestGroups.scala and also added a warning that will inform a contributor that they should add it if possible.

Add tests explicitly to tests shard

---

metals/src/main/scala/scala/meta/internal/metals/Directories.scala
metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala
tests/unit/src/main/scala/tests/ResourceOperations.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/main/scala/tests/codeactions/BaseCodeActionLspSuite.scala
tests/unit/src/test/scala/tests/AddPackageLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/OrganizeImportsLspSuite.scala

Previously, if a file was not saved it wouldn't be possible to run the organize imports rule.
Now, we try to produce a new semanticdb, save it to disk and point scalafix to it. It might be better to transfer this directly, but scalafix is currently lacking an API for it. We can change once it's supported.
Fixes https://github.com/scalameta/metals/issues/2120

Allow organize imports on unsaved code

---

metals/src/main/scala/scala/meta/internal/metals/formatting/IndentOnPaste.scala
tests/unit/src/test/scala/tests/rangeFormatting/IndentWhenPastingSuite.scala
tests/unit/src/test/scala/tests/rangeFormatting/MultilineStringRangeFormattingWhenPastingSuite.scala
tests/unit/src/test/scala/tests/rangeFormatting/MultilineStringRangeFormattingWhenSelectingSuite.scala

There were several issues with ident on paste that is fixed by this
change:
- weird formatting if second line is empty of  overindented:
```scala
// original
trait X[A] {
def foo: X[A] // 4 spaces instead of 2
}
// pasted
object Main {
trait X[A] {
def foo: X[A]
}                // <- wrong formatted
}
```
- previous logic were removing all empty lines that wasn't convinient if
you copy a large block of code like:
```scala
// original
trait X[A] {
def foo: X[A]
}
def m1: Int = 32
// pasted without whitespace between `X` and `m1`
trait X[A] {
def foo: X[A]
}
def m1: Int = 32
```
- normalization from tabs to spaces didn't work correctly

Ident on paste - bunch of fixes

---

metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala

This fixes issues with organize imports in some projects such as Bloop.
Fixes https://github.com/scalameta/metals/issues/2903
Previously if there was a file on classpath that was not a jar Scalafix would fail. Now we filter the classpath to only send jars or directories.

Make sure that classpath does not contain invalid files

---

metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala
metals/src/main/scala/scala/meta/metals/Main.scala

Use `sys.exit(0)` to stop all threads to avoid hanged process.
In some cases (if metals was closed just right after build import/
during import) there is some thread from unknown thread pool that keep
process alive.
I've checked all places in our codebase but haven't found anything.
Probably it starts somwehere in dependency so `sys.exit(0)` is the only
solution here.

Fix process exiting

---

metals/src/main/scala/scala/meta/internal/metals/formatting/IndentOnPaste.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/rangeFormatting/IndentWhenPastingSuite.scala

Fixes https://github.com/scalameta/metals/issues/3108

Fix overindenting when the indentation is more than expected

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/formatting/IndentOnPaste.scala
metals/src/main/scala/scala/meta/internal/metals/formatting/RangeFormattingProvider.scala
tests/unit/src/test/scala/tests/rangeFormatting/IndentWhenPastingSuite.scala
tests/unit/src/test/scala/tests/rangeFormatting/MultilineStringRangeFormattingWhenPastingSuite.scala
tests/unit/src/test/scala/tests/rangeFormatting/MultilineStringRangeFormattingWhenSelectingSuite.scala

I think we pushed it too hard and although I am happy with the current state it's still a bit controvertial, so I'd rather have an easy way of turning it off and on.
Also it seems that turning off `Format on paste` doesn't do anything.
PS: The changes are mostly whitespace related, I recommend turning on `Ignore whitespace changes`

Add setting to enable indentation on paste

---

metals/src/main/scala/scala/meta/internal/metals/ScalaVersionSelector.scala
tests/unit/src/test/scala/tests/FormattingLspSuite.scala
tests/unit/src/test/scala/tests/HoverLspSuite.scala

The scala 3 compiler is more likely to be able to compile your scala 2
code than the reverse, so it makes sense to use scala 3 as the fallback.

Set the default fallbackScalaVersion to scala 3 instead of 2.12

---

metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala
metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
metals/src/main/scala/scala/meta/internal/metals/FileSystemSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/JavaBinary.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/process/SystemProcess.scala

Shows class files and semanticdb files in readable format.
This uses VSCode's Virtual Documents rather than the WebView as https://github.com/scalameta/metals/pull/3063 does for Tasty files.
There are pros and cons for both methods and I'm not sure what's best in this case.
Virtual Documents allow Metals to pass back only the plain text that should appear for the output from javap and metap in response to a command with a URI parameter.
This means no hyperlinks and no formatting, both of which the webview will allow but it does make it easily extendable to handle more file viewers (e.g. scalap?) without managing additional WebViews
Highlighting is done using textmate grammars which are pretty long-winded.  But I'm guessing this method is more portable across non-vscode clients?  Also - I …

add javap/semanticdb file viewer

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/RewriteBracesParensCodeAction.scala
tests/unit/src/test/scala/tests/codeactions/BracesParensLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ConvertPatternMatchLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/InsertInferredTypeLspSuite.scala

Aims to close https://github.com/scalameta/metals-feature-requests/issues/233.
I've found a scenario when rewrite parens action didn't work. Then I found an issue created by @agilesteel so I fed two birds with one seed :D

Support more scenarios with 'replace () with {}' code action

---

.github/workflows/sourcegraph.yml
project/plugins.sbt

The workflow was previously disabled due to 404s that I'm unable to
reproduce now.

Update Sourcegraph workflow to use `lsif-java index` command.

---

metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java
tests/cross/src/test/scala/tests/pc/PcSemanticdbSuite.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Previously, generated semanticdb would not contain symbol information. Now, it's enabled and allows for type decorations and implementations in worksheets, standalone files, dependencies and sbt files.
Should help with https://github.com/scalameta/metals-feature-requests/issues/190

Generate symbol information for standalone files, worksheets and sbt files

---

metals/src/main/scala/scala/meta/internal/metals/debug/SourcePathAdapter.scala

Previously, when running/debugging we would close previously opened source jars, which would cause all the existing paths to inside of that jar to stop working. Now we don't close them.

Don't close source jars

---

metals/src/main/scala/scala/meta/internal/metals/codelenses/SuperMethodCodeLens.scala
tests/unit/src/main/scala/tests/BaseCodeLensLspSuite.scala
tests/unit/src/main/scala/tests/CodeLensesTextEdits.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/CodeLensLspSuite.scala

Previously, we would point only to symbols in the commands for parent code lenses, which cannot work with the local symbols. Now, in case of local symbols we use the command to go to an exact position.

Fix go to parent code lenses for local symbols

---

metals/src/main/scala/scala/meta/internal/metals/debug/SourcePathAdapter.scala
tests/unit/src/main/scala/scala/meta/internal/metals/debug/StepNavigator.scala

Previously, we would only translate the URI to a local dependencies files. Now, we create the dependency file if it doesn't exist.

Create dependency files on step if they don't exist

---

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/SuperMethodCodeLens.scala

Previously, we would check all the symbols in a file if they don't have a parent, which is highly inefficient. Now, we only search in the local file, which contains all the definitions we are interested in. If there is no definition, we will never display those code lens.
This might have still been causing some issue for users. @kpodsiad reported an issue like that, this is probably the reason.

Don't search for all symbols in go-to-parent code lenses

---

metals/src/main/scala/scala/meta/internal/builds/MavenBuildTool.scala

Related to https://github.com/scalacenter/bloop/issues/1573
I haven't added a test for it, because protobuf mentioned in the issue needs to be installed locally.

Make sure generate-sources phase is always run for Maven

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala

This is a follow-up to the work done in https://github.com/scalameta/metals/pull/3060, but since
position is now optional, we need to ensure to use `getPosition`
instead of position like we did here. This was causing the following
exception to be throw:
```
Caused by: java.lang.IllegalArgumentException: Property must not be null: position
at org.eclipse.lsp4j.util.Preconditions.checkNotNull(Preconditions.java:29)
at org.eclipse.lsp4j.TextDocumentPositionParams.<init>(TextDocumentPositionParams.java:49)
at scala.meta.internal.metals.Compilers.withPCAndAdjustLsp(Compilers.scala:594)
at scala.meta.internal.metals.Compilers.hover(Compilers.scala:365)
at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$hover$1(MetalsLanguageServer.scala:1359)
at …
```

Avoid IllegalArgumentException when trying to get type of range.

---

metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala
tests/unit/src/test/scala/tests/AnalyzeStacktraceLspSuite.scala

This can happen at times when you are running tests and something explodes.
sbt will give you this information a la `[info]` instead of `[error]`. So
this allows the code lenses to work still without having to strip them out
manually

Strip out [info] for stacktraces.

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala

So I believe this has snuck under the radar for a long time until the
recent updates made in https://github.com/scalameta/metals/pull/3149
that does a much cleaner job at extracting the params. I believe this was
just a mistake with the `goto-position` server command and the
`goto-location` client command. The client one takes in the extra
boolean to represent `otherWindow`, however that setting doesn't apply
when it's the `goto-position` command being sent to the server. In the
past we sort of just let it slide and the boolean value was always
there, however according to our own spec, it shouldn't be. I found this
while using the `analyze-stacktrace` command since the code lenses it
provides have a `goto-position` command attatched to them that includes
the boolean. Since the boolean is …

Remove extra boolean from the `goto-position` server command in `StacktraceAnalyzer`

---

metals/src/main/scala/scala/meta/internal/metals/debug/SourcePathAdapter.scala

This seems to be causing an exception to happen later on for the older URIs from previously opened file system (at least as far as I understand it):
```
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(Str …
```

Don't create file system when debugging

---

metals/src/main/scala/scala/meta/internal/metals/debug/SourcePathAdapter.scala

While testing on windows I encounter still some issues for classes within `src.zip` JDK sources.
It was throwing FileSytemNotFound exceptions and I was not able to figure out what was going on.
This is a quickfix for this release so that it's possible to use breakpoints properly on Windows, the only thing this will do is that it might sometimes be impossible to go to JDK sources.

Add try in order not to break debugging session

---

mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbSymbols.scala

Encountered stack trace when trying empty scope completions
```
Exception in thread "pool-4-thread-1" java.util.NoSuchElementException: head of empty String
at scala.collection.StringOps$.head$extension(StringOps.scala:1129)
at dotty.tools.dotc.semanticdb.Scala3$StringOps$.isJavaIdent(Scala3.scala:405)
at scala.meta.internal.pc.SemanticdbSymbols$.addName$1(SemanticdbSymbols.scala:92)
at scala.meta.internal.pc.SemanticdbSymbols$.addDescriptor$1(SemanticdbSymbols.scala:127)
at scala.meta.internal.pc.SemanticdbSymbols$.addSymName(SemanticdbSymbols.scala:137)
at scala.meta.internal.pc.SemanticdbSymbols$.symbolName(SemanticdbSymbols.scala:79)
at scala.meta.internal.pc.CompletionProvider.visit$1(CompletionProvider.scala:116)
at scala.meta.internal.pc.CompletionProvider.$anonfun$5(CompletionProvi …
```

Fix issue with empty string in completions

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsHttpClient.scala
metals/src/main/scala/scala/meta/internal/metals/Trace.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
metals/src/main/scala/scala/meta/metals/Main.scala
tests/unit/src/main/scala/tests/BaseDapSuite.scala

Previously, in order to log JSON-RPC traces, one has to create proper files in the cache directory. What's important, those files are global for every metals server.
Now, there is an additional option available. One can create those files in the `.metals` directory and opt-in/out logging per project. No more reloading specific metals instance in order to see logs from it!
closes https://github.com/scalameta/metals/issues/3098

Take into account trace files in .metals directory

---

metals/src/main/scala/scala/meta/internal/metals/codelenses/SuperMethodCodeLens.scala
tests/unit/src/test/scala/tests/CodeLensLspSuite.scala

Previosuly, lenses wasn't erased if document was changed in buffer only.

SuperMethodCodeLens - do not show stale lenses

---

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
tests/unit/src/test/scala/tests/DebugDiscoverySuite.scala

This pr makes the check for errors in the build a bit more specific when
doing debug discovery. In the past if there was an error at all in the
build, we would error and notify the user they couldn't run/test the
file. However, instead of looking for errors in the entire build we can
instead use the build target and check that build target for errors
(which also checks the transitive build dependencies) which allows you
to run or test a file when there are unrelated errors.
Fixes #3219

Finer grained rules on build errors for debug discovery.

---

build.sbt
metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala
metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
tests/slow/src/test/scala/tests/feature/FileDecoderProviderLspSuite.scala

Adds a class file decompiler to the list of source analysis tools
@s5bug put me onto this while discussing an issue with Scala 3.  It was easier to understand what was going on than using `javap` so I thought it might help to integrate it into Metals
This includes a fix for using `javap` on java source files - it was looking in the wrong dir for the class file.  I haven't added any Java tests to `FileDecoderProviderLspSuite` because I don't think `didOpen` triggers a java file compilation with Metals yet, so it won't compile a single Java file and therefore can't test the analysis of the output - or am I wrong?
Other options besides [CFR](https://github.com/leibnitz27/cfr) are [fernflower](https://github.com/JetBrains/intellij-community/tree/master/plugins/java-decompiler/engine) and …

Add CFR class file viewer

---

metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala

This was a small change that clients didn't account for in
https://github.com/scalameta/metals/commit/84dbb851ad753c6ac79a410a1b8aa272853db1f1
where the custom `GoToSuperMethodParams` were removed and just replaced
with `TextDocumentPositionParams`. This pr just updates the docs to
ensure that it's clear that the commands use this, not the old format.
Changes for this will need to happen in the client repos.

docs: update commands that now use `TextDocumentPositionParams`

---

metals/src/main/scala/scala/meta/internal/metals/MetalsExperimental.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

A workaround for https://github.com/microsoft/language-server-protocol/issues/377 until it is resolved
this would allow LSP clients to explicitly know that they can send a range with `textDocument/hover` instead of a position
If someone has a better name for the field I am happy to change it :)
@ckipp01 should this be added to `new-editor.md` ?

Set rangeHoverProvider under experimental capabilities

---

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersionSelector.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala

Ammonite generates additional file which we use in the presentation compiler for anything that requires types, so we neeed to adjust all request to actually point to a position in that generated file.
Previously, we would not adjust ranges when invoking hover and only positions. Now, we adjust both.
Also fixed the fallback version in case of Scala 3 for ammonite to be the last Ammonite suppored Scala 2.13 version instead of hte last Scala 2.13 version.
Fixes https://github.com/scalameta/metals/issues/3300

Fix expression for selection range in Ammonite

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/MtagsBinaries.scala
metals/src/main/scala/scala/meta/internal/metals/MtagsResolver.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersionSelector.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
metals/src/main/scala/scala/meta/internal/metals/Warnings.scala
metals/src/main/scala/scala/meta/internal/troubleshoot/ProblemResolver.scala
metals/src/main/scala/scala/meta/internal/troubleshoot/ScalaProblem.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala
tests/unit/src/main/scala/tests/QuickBuild.scala
tests/unit/src/main/scala/tests/TestMtagsResolver.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

Prevously, the specific Metals version was able to work with only
specified list of Scala versions.
With these changes, in case if new Scala versions was released, we will
be able to realese only mtags artifact instead of making a full Metals
realease.
This isn't really usefull without additional release workflows but I'll
make separate PR for that later.

ScalaVersion - discover new mtags version by coursier

---

.github/workflows/ci.yml
build.sbt
project/Scala3NightlyVersions.scala

This introduces the following changes:
- every release supports up to 5 of latest NIGHTLY Scala3 versions.
Should be already valuable as every snapshot release will
automatically catch new NIGHTLY releases.
- `+cross/test` also run tests against the latest NIGHTLY release
that should help with spotting issues earlier.

Support Scala3-NIGHTLY releases

---

metals/src/main/scala/scala/meta/internal/bsp/BspConfigGenerator.scala
metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/builds/BuildServerProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/test/scala/tests/BillLspSuite.scala
tests/unit/src/test/scala/tests/BspSwitchLspSuite.scala
tests/unit/src/test/scala/tests/SelectBspServerSuite.scala

This relates to the conversation we had in
https://github.com/scalameta/metals/discussions/3255 and essentially
gets rid of the need for a user to remember they need to run
`metals.generate-bsp-config` if no `.bsp/sbt.json` exists. Now, instead
a user is able to use the `metals.bsp-switch` command and it will detect
if the build tool can be a build server even if there is no
`.bsp/<entry>` that exists, shows it to them during the user choice, and
then if selected generates the entry and then connects to it.
The old behavior of the `metals.generate-bsp-config` is still the same
and can be used _if_ you want a fresh `.bsp/<entry>`.
_notice sbt is given as a choice even though no `.bsp/sbt.json` exists`_.

Simplify usage of sbt server when no .bsp/sbt.json exists

---

docs/integrations/new-editor.md
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala

Noticed that it was missing while working on the sublime implementation of `analyze-stacktrace`

Add isCommandInHtmlSupported to InitializationOptions doc

---

metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala

I initially noticed that `ShowStacktrace` was missing but I added the other missing ones as well.

Add missing commands to client commands documentation

---

metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala

It seems that my previous PR https://github.com/scalameta/metals/pull/3315 broke the json rendering in the doc.
This is the current look

Fix json rendering in documentation

---

build.sbt
metals/src/main/scala/scala/meta/internal/bsp/BspConfigGenerator.scala
metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/builds/BuildServerProvider.scala
metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
mtags/src/main/scala/scala/meta/internal/semver/SemVer.scala
tests/slow/src/test/scala/tests/mill/MillServerSuite.scala
tests/unit/src/main/scala/tests/BuildServerInitializer.scala
tests/unit/src/main/scala/tests/BuildServerLayout.scala
tests/unit/src/test/scala/tests/ScalaVersionsSuite.scala

This adds the same type of functionality that we have with sbt where Mill can now also be a build server meaning that `metals.generate-bsp-config` and also `metals.bsp-switch` will apply to it. This also cleans up a few things that I did in #3304, fixes a bug in `Semver`, and also introduces a few small changes in `BuildServerProvider.scala` that are needed if a build tool and the name they use as a build server don't match.
Relates to https://github.com/com-lihaoyi/mill/issues/1546 and also closes #3307

Better support for mill BSP

---

docs/integrations/debug-adapter-protocol.md
metals/src/main/scala/scala/meta/internal/metals/config/RunType.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
tests/unit/src/test/scala/tests/DebugDiscoverySuite.scala

This will enable the possibility to run/debug without specifying the configuration in `launch.json`
Some further work can be done on the discovery so that we would be able to automatically feel new configurations for the user.
Related to https://github.com/scalameta/metals/issues/3272

Add option to run everything in the current file

---

README.md
build.sbt

There is a number of people, who haven't worked or interacted in any form with the Metals repository for over a year now. To avoid confusion and make it easier to know who can be pinged, I move them to a separate list.
I don't plan on modifying the permissions to go with it.

Move inactive maintainers to a separate list

---

mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/test/scala/tests/hover/HoverDocSuite.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala
tests/cross/src/test/scala/tests/hover/RangeHoverSuite.scala

Adapted the `seenFrom` logic from Scala2.
Now types in hover are close to be in pair in both implementations.

[Scala3] Hover - improve tpe selection for signature and expression

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaMtags.scala
tests/input3/src/main/scala/example/GivenAlias.scala
tests/unit/src/test/resources/definition-scala3/example/GivenAlias.scala
tests/unit/src/test/resources/documentSymbol-scala3/example/GivenAlias.scala
tests/unit/src/test/resources/expect/toplevels.expect
tests/unit/src/test/resources/semanticdb-scala3/example/GivenAlias.scala

In semanticdb given is a term if there is no type/using pameters,
otherwise it's a method.
Also, fixes name inference for anonymous givens.

[Scala3] Fix go to defition for givens

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

This is just a small change to improve the bsp-switch label that
includes the "(currently using)" message. Previously if you've never
made an explicit choice it wouldn't tell you which you were using. This
change defaults to the current connection if there is no explicit
choice made.

Improve the "(currently using)" message during bsp-switch.

---

.github/workflows/mtags-auto-release.yml
.github/workflows/release.yml
build.sbt

The goal of this PR is to simplify our release process.
Currently, Metals has a list of supported compiler versions and for every new compiler version, we have to make a new release of Metals.
That is a bit problematic because a full release preparation requires more actions than just adding support for a new compiler version: we need to check/do last fixes for all new merged features, prepare release notes, some tests should be reworked while overall it isn't required for having basic functionality. So all these things increase the delay between compiler release and when it will be supported by Metals.
The additional problem is that this mechanic doesn't allow us to support scala3-NIGHTLY releases.
I spit the required changes on several PR's:
- First one - [ScalaVersion - discover new …

Release process: publish `mtags` for the latest Metals release

---

docs/editors/overview.md
docs/editors/sublime.md

After https://github.com/scalameta/metals-sublime/pull/57 only ST4 will be supported
Also technically the version number is dropped from the name now it is simply Sublime Text.

Remove sublime version from the doc

---

tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/hover/HoverNegativeSuite.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala
tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionFilenameSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideAllSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideConfigSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionParameterHintSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionScaladocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetNegSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/HKSignatureHelpSuite.scala
tests/cross/src/test/scala/tests/pc/InterruptPresentationCompilerSuite.scala
tests/cross/src/test/scala/tests/pc/MacroCompletionSuite.scala
tests/cross/src/test/scala/tests/pc/PrettyPrintSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpPatternSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala

`test-mtags-dyn` might be called with a versions that isn't specified in
BuildInfo

Cross tests - fix ignorance for `test-mtags-dyn`

---

.github/workflows/mtags-auto-release.yml

Cross tests don't pass on jdk8.
The re some completions tests that contains some classes that aren't
presented in jdk 8

Actions - set jdk11  for mtags auto release

---

build.sbt
project/Welcome.scala

Currently running `+publishLocal` takes a significant amount of time.
Added this command to speed up the local development workflow.

[Build] Add  `quick-publish-local` command

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
mtags/src/main/scala/scala/meta/internal/mtags/IndexingExceptions.scala
mtags/src/main/scala/scala/meta/internal/mtags/InvalidJarException.scala
mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala

Previously, users would report an issue, but we would not be able to point to any particular path or dependency. Now, we try to print much more information for the users in exceptional cases.
The issue popped up for example here: https://gitter.im/scalameta/metals?at=61a8d7a98853d31640283bf5

Add information about source of exceptions

---

build.sbt

Without specifying scala version for `metals` its publishing in command
fails with the following error:
```
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/home/dos65/projects/metals/metals/"), "metals"):
[error]    org.scalameta:mtags _2.12.15, _2.12.14
```

[Build] Fix quick-publish-local

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Command.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Previously, we would only display types of anything that was shown in the implicit decorations. Now, instead we show a shorter clickable link that effectively does `go to definition`
Fixes https://github.com/scalameta/metals/issues/3359
Demo!

Add go to definition via links to synthetic decorations

---

metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala
metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/ClientExperimentalCapabilities.scala
metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/DelegatingLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/NoopLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/debug/ClientConfigurationAdapter.scala

Instead of the custom `metals-model-refresh`
Fix https://github.com/scalameta/metals/issues/3354

Send Code lens refresh when supported by client

---

mtags/src/main/scala-3/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/slow/src/test/scala/tests/feature/ImportMissingSymbolCrossLspSuite.scala

To get a proper results it's needed to specify buildTargetId from where
SymbolSearch is performed.

[Scala3] Fix ImportMissingSymbol code action

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Previously, we would only point to the first character, which would work differently to how normally go to definition works. Now, we point to the full range.

Use full range when using go-to definition for synthetics

---

build.sbt

It looks like both the scala-java8-compat and geny are both published for Scala 3
so we can just use those instead of utilizing for3Use2_13.

Move to Scala 3 published artifacts where possible

---

metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala

I think something like this should be right.
The only guaranteed file to exist in a Gradle project I think is `settings.gradle(.kts)` in the root. Subprojects can be nested arbitrarily + named anything:
https://docs.gradle.org/current/userguide/declaring_dependencies_between_subprojects.html#sec:project_jar_dependencies
Currently, Metals fails to detect Gradle projects like the ones created by `gradle init -> "Application (Scala)"` because the directory layout is:
```
settings.gradle(.kts)
/app
build.gradle(.kts)
/src
```

[UNTESTED] Fix Gradle detection, multimodule proj

---

metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

Previously, we would use message request when asking for user input about which main class to run. Now, we instead use quick pick to accomodate a larger number of main classes possible. This is also a much nicer UI in VS Code as there is no need to select anything with a mouse. Quick pick still falls back to messageRequests if the client doesn't support it.
https://user-images.githubusercontent.com/3807253/146952326-d398138c-1fda-401f-93d4-917681f5a37a.mp4

Use quick pick instead of message requests for debug discovery

---

metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafmtDialect.scala
tests/unit/src/test/scala/tests/FormattingLspSuite.scala

I've noticed that on snapshot version the wrong suggestion
about improper `.scalafmt.conf` appears in Metals repo.
Changes:
- support more dialects. Previsously any Scala2 target had `scala213` formatting dialect
- ignore sbt targets in rewrite `.scalafmt.conf` suggestions

[Scalafmt] Fixes for automatic dialect rewrite

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala

Upstream was incredibly responsive and provided a fix in file-tree-views 2.1.8 in record time.
This supersedes the workaround in PR #3404 for issue #3379.

Upgrade file-tree-views to 2.1.8. See #3379.

---

mtags/src/main/scala-2/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala

This just adds a check in the situation where a file has no existing import
and no package to look and see if there are `//` comments in the beginning
of the file and if so, skip over them before we add the import. The main reason
for this is to avoid braking directives in scala-cli.
We don't do a more advanced check for this for other types of comments mainly
because it'll be more difficult without more extensive parsing to know if a comment
is a header or a scaladoc for example. So for now we just do a more naive check
on `//`.
Closes #3399

fix: ensure autoimports don't break scala-cli directives

---

metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileTypes.scala

This pr adds the file ids and the label to the docs. I missed this in last PR where this changed from `worksheet` to `scala-worksheet` and this actually broke my implementation since I do have some commands that send in the filetype directly. Now these will be listed in the docs to be accessed without needing to dive into the code.

docs: add file ids to the docs for new file commands

---

.scalafmt.conf

`-XSource3` flag comes to sbt-metals from SbtPlugin and triggers Metals warning about improper configuration

[Scalafmt] set proper dialect for sbt-metals

---

build.sbt
project/Developers.scala

This pr just changes a few small things in the build:
- Moves the list of developers to `project/Developers.scala`
- Takes deps that we use in multiple places and give them a `V.name` variable to use
- Alphabetizes the versions in `V`
- Removes duplicated deps declared in both mtags and metals

refactor: small build cleanups

---

metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala
metals/src/main/scala/scala/meta/internal/metals/JsonParser.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersionSelector.scala
metals/src/main/scala/scala/meta/internal/metals/debug/SetBreakpointsRequestHandler.scala
mtags/src/main/scala-2/scala/meta/internal/docstrings/HtmlConverter.scala
tests/unit/src/main/scala/scala/meta/internal/metals/debug/Completer.scala
tests/unit/src/main/scala/scala/meta/internal/metals/debug/ExpressionEvaluator.scala
tests/unit/src/main/scala/tests/QuickBuild.scala

I through in `-deprecation` and took care of most of the deprecation warnings. There are still a couple left, but they are situations where we actually need to use the deprecated methods (since we don't support workspaceFolders for example) or other things that take more thought, like not using `thread.stop`.

refactor: take care of some deprecation warnings

---

mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SymbolPrinter.scala
tests/cross/src/test/scala/tests/hover/HoverErrorSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionErrorSuite.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala

Includes:
- print Any if type cannot be inferred
- don't show error methods on hover
This fixes https://github.com/scalameta/metals/issues/3422 and https://github.com/scalameta/metals/issues/3421

[Scala 3] Fix issues when type cannot be inferred by the compiler

---

.scala-steward.conf

We pinned eclipse deps versions and we aren't goint to update as long as we keep jdk8 support

Scala Steward - ignore org.eclipse updates

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
tests/unit/src/test/scala/tests/DebugDiscoverySuite.scala
tests/unit/src/test/scala/tests/DebugProtocolSuite.scala

This closes #3458 and reuses the logic we had in the run/test code lens
to special case the top level `@main` annotation. We now use the same
logic in both places and it's moved into the `DebugProvider`.

fix: reuse main annotation logic from code lens in debug provider

---

mtags/src/main/scala-3/scala/meta/internal/pc/IndexedContext.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala

Previously, we would treat Either type alias from Predef as a separate entity than scala.util.Either. Now, we also check type aliases for conflicting imports.
Fixes https://github.com/scalameta/metals/issues/3454

[Scala 3] Fix insert type in case of type aliases

---

mtags/src/main/scala-3/scala/meta/internal/pc/Signatures.scala

Instead of using `symbol.owner` since from the code:
> /** The owner of the symbol; overridden in NoDenotation */
we instead use `maybeOwner` which will not be overriden in
`NoDenotation`. This avoids the `NoDenotation.owner` assertion error.
I'm not 100% sure on a test for this or what a good example would be.
Closes #3461

fix: use maybeOwner instead of owner when looking for shortened name

---

README.md
docs/contributors/getting-started.md
docs/contributors/releasing.md
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala
website/docusaurus.config.js

Following the official announcement that Discord is now where the
official Scala chat is located, I think it makes sense to focus on
support efforts on Discord. Lately I've also noticed that our Gitter has
been much quieter with more people coming to Discord anyways. We don't
have to sunset Gitter or anything, but instead just remove the
references to it in various places since most seem to be heading to
Discord anyways.
What do you all think?

docs: migrate gitter references to Discord

---

website/docusaurus.config.js

According to the documentation of the [plugin-content-docs](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#editUrl),
the actual URL used is `computed by editUrl + relativeDocPath.`
When using a string value for the editUrl, then the edit URL is `editUrl` + `target/docs` + `docPath` in your case.
The `target/docs` is added but not needed.
Again, according to the [documentation](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#ex-config), is is possible
to use a function instead of a plan string for the `editUrl`, and this is what this change is all about: docusaurus now ignored the `target/docs` to construct the path.

Fix: Docusaurus Edit URL is broken

---

build.sbt

I have no idea how this has been working, since locally I couldn't run this for a while it seems, but it still seems to be working in ci 🤷🏼

fix: override pprint in docs

---

metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala

This updates the default fallbackScalaVersion which is Scala3, but we
are still showing Scala 2.12. This also updates the `testUserInface` to
only have the value since it's dynamically put together. Right now it
shows:
```json
{
"metals": {
"testUserInterface": { "testUserInterface" : "Test explorer" }
}
}
```
So this fixes that.

docs: update user config docs

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/DoctorResults.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
metals/src/main/scala/scala/meta/internal/troubleshoot/ProblemResolver.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

We haven't revamped the doctor in a while and I feel with the upcoming Java support this is as good a chance as any.
What was changed:
- instead of scala version we now have sbt version writen under `Type` in case of sbt targets
- Java targets were moved to another column instead of being a separate entity
- merged definition and completions into one column called `Interactive` to indicate that Scala version is supported
- renamed `references` to semanticdb since there is currently a huge number of features that actually depend on it
- added explanations for different statuses underneath
- added a deubgging column and marked it disable explicitely for sbt targets
I would love to hear your opinions especially:
- will it work with other editors
- what else could we add
- do the new names …

Show more information in the doctor

---

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/metals/DownloadDependencies.scala
mtags/src/main/scala-2/scala/meta/internal/metals/PositionSyntax.scala
mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala
project/TestGroups.scala
tests/unit/src/test/scala/tests/JavaDefinitionSuite.scala

Implemented using sourcegraph semanticdb compiler plugin.

[Java] Support go-to-definition for `*.java` dependency sources

---

metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala

This was caused by not rebasing https://github.com/scalameta/metals/pull/3470

Fixed compilation issue

---

metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/DoctorExplanation.scala
metals/src/main/scala/scala/meta/internal/metals/DoctorResults.scala

This is a follow-up to the work done in
https://github.com/scalameta/metals/pull/3426.
This extracts out the explanation logic into the `DoctorExplanation` ADT
so that we can re-use it both for html and for json.
The old output of the json doctor was:
```json
{
"title": "Metals Doctor",
"headerText": "Build server currently being used is Bloop v1.4.11.\n\nThese are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.",
"version": 1,
"targets": [
{
"buildTarget": "Sanity",
"targetType": "Scala 2.12.15",
"diagnostics": "✅ ",
"interactive": "✅ ",
"semanticdb": "✅ ",
"debugging": "✅ ",
"java": "✅ ",
"recommendation": ""
},
{
"buildTarget": "Sanity.test",
"targetType": …
```

feat(doctor): add in explanations to the json doctor output

---

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala
metals/src/main/scala/scala/meta/internal/metals/FileSystemSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
mtags/src/main/scala/scala/meta/internal/mtags/MD5.scala
mtags/src/main/scala/scala/meta/internal/mtags/Semanticdbs.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

This includes making sure that contructors are taken into account as well as some smaller overall improvements:
- fix inString method to not break if the text document string is empty
- log whenever text corresponding to semanticdb md5 string was not found

Fix issues with renames in Java files

---

metals/src/main/scala/scala/meta/internal/parsing/TokenEditDistance.scala

I haven't noticed that `toList` would previously do it on `ArraySeq`, which meant we had an Array under the java.List interface. It seems it might be causing perfomance regression in large inputs.

Use ArraySeq instead of List for Diffutils

---

metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
tests/slow/src/test/scala/tests/feature/FileDecoderProviderLspSuite.scala

In the "Metals Analyse Source" -> "Show decompiled with javap" and "... with javap verbose" currently `javap` is called without the `-private` option. This causes some missing members in the output. This PR adds the `-private` option to the `javap` calls.

Call javap with -private flag

---

metals/src/main/scala/scala/meta/internal/parsing/ClassFinder.scala
tests/unit/src/test/scala/tests/classFinder/FindAllClassesSuite.scala

When selecting "Metals Analyse Source", some inner classes/traits/objects has incorrect names like `A$B$B` instead of `A$B`. As a result, the editor can't open these, e.g., javap files. This PR fixes this.

Fix ClassFinder bug with inner classes

---

.github/workflows/check_scala3_nightly.yml

According to [maven-central](https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/) nightly versions
are published from 4:00AM to 4:30AM.
This job is scheduled at 5:00AM, to check if there were a nightly
release today and trigger mtags-publishing job.

[Actions] Trigger Scala3-nightly mtags publishing automatically

---

metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala

I've started to play around with this in nvim-metals and just hit
on this and realized in the docs we say Test explorer as an example
but then we check on an exact match of Test Explorer. This just
calls .toLowerCase on the value and then we check that.

refactor: check lowercase test-user-interface

---

.github/workflows/check_scala3_nightly.yml

I missed that `./coursier` is in `.gitignore`

[Actions] Install coursier for nightly checks

---

tests/unit/src/test/scala/tests/JavaDefinitionSuite.scala

Just an additional test that doesn't work on jdk11+ without `--patch-module $module` flag

[JavaInteractiveSemanticdb] Add test-case to cover --patch-module flag usage

---

mtags/src/main/scala/scala/meta/internal/mtags/Semanticdbs.scala

Previously, when semanticdb had md5 with lower case letters we would not find the snapshot text for semanticdb. Now, we convert it always to upper case.
Fixes https://github.com/scalameta/metals/issues/3539
PS: So the logging might be a bit excesive, but it did help to find an issue :man_dancing:

Compare only uppercase MD5

---

.github/workflows/check_scala3_nightly.yml

Having only `schedule` doesn't allow to trigger this job manually.

[Actions] One more fix to check_scala3_nightly job

---

docs/editors/overview.md
metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala

This also improves the message that a user sees if they accidentally try
to use one of these while in a worksheet or something. I hit on this
today and tried using cfr quickly while in a worksheet and all I saw as
an error that said:
```
Invalid extension
```

docs: add a small note about decode not working on extra file types.

---

.github/workflows/release.yml
build.sbt

Unfortunately, there is no way to make it work using on sbt side .
The problem is, that mtags release happens from latest release commit.
That means that there is no way to apply fixes for sbt-command.

[Actions] Mtags publishing - move all logic to ci-script

---

.github/workflows/mtags-auto-release.yml
.github/workflows/release.yml

Finally, there is a working [job](https://github.com/scalameta/metals/runs/4895558191?check_suite_focus=true) that released `3.1.2-RC1-bin-20220119-2849aed-NIGHTLY`.
Artifacts [were published](https://repo1.maven.org/maven2/org/scalameta/mtags_3.1.2-RC1-bin-20220119-2849aed-NIGHTLY/0.11.1/) and I checked that `v0.11.1` is able to work with them.
Changes:
- Added a `metals_ref` to `mtags-auto-release`.
Github action takes job configuration from the checkoutted commit.
That means if there were issues at release moment we can fix them and
change the base commit for mtags release.
I created `v0.11.1_mtags_release` that contains changes in `release.yaml`.
- Final adjustments to `release.yml`: fix version parsing, do not publish docs.

actions: mtags release adjustments

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/Keywords.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/KeywordsCompletions.scala
mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
mtags/src/main/scala/scala/meta/internal/pc/Keyword.scala
mtags/src/main/scala/scala/meta/internal/pc/MemberOrdering.scala
tests/cross/src/main/scala/tests/BaseCompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionParameterHintSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

This also tweaks a couple of things with Scala 2:
- allow import without package (since we can have those)
- allow more keywords in ammonite files
We also add new keywords for Scala 3 except the `then` keyword which is complicated to add and would require some by hand parsing.

feature: [Scala 3] Add keyword completions

---

metals/src/main/scala/scala/meta/internal/implementation/Supermethods.scala
metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala
metals/src/main/scala/scala/meta/internal/metals/Command.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala
metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileProvider.scala
tests/unit/src/main/scala/tests/TestingServer.scala

When reworking the links and adding support for Sublime I forgot to test out if the stacktrace opens files in another window and it turns out this got broken.
Because of that, I reworked the GotoLocation command to take in an additional parameter, which makes it a bit easier to handle and always send it tpo the client.
Needs https://github.com/scalameta/metals-vscode/pull/828

fix: Open other window when using Analyze Stacktrace

---

metals/src/main/scala/scala/meta/internal/metals/BatchedFunction.scala
metals/src/main/scala/scala/meta/internal/metals/Compilations.scala

`BatchedFunction` batches asynchronous requests but it hasn't offered any mechanism to execute callbacks after request is completed. This lead to executing `foreach` method on returned futures, which led to race conditions in `Compilations.scala` Side effects have been executing in parallel which was visible in the Test Explorer GUI.

fix: add possibility to define callback for `BatchedFunction`

---

mtags/src/main/scala-3/scala/meta/internal/pc/CompilerInterfaces.scala

Was digging around in here for something today and realized none of this was used. Can we just remove it all?

cleanup: remove unused stuff from CompilerInterfaces

---

metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
tests/unit/src/test/scala/tests/codeactions/OrganizeImportsLspSuite.scala

When using organize-imports on Scala 2 with `-Xsource:3` a crash would occur when using `as` import renaming:
```
2022.01.28 11:08:13 ERROR /..../ConfigReader.scala:8: error: } expected but identifier found
import pureconfig.{ConfigReader as PureConfigReader, ConfigSource}
```
This is because Scalafix tries to parse the file as Scala 2. Scalafix has support for `-Xsource:3` since https://github.com/scalacenter/scalafix/pull/1409 but it needs to be passed in the scalacOptions. With this fix `-Xsource:3` is passed to Scalafix if used, fixing the crash and letting Scalafix properly parse and fix the file.

Pass -Xsource:3 to scalafix organize-imports action if present

---

metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

Previously, we would focus diagnotics every time a compilation finished with an error, which means we could steal focus from the user multiple times. Now, the only palce we focus diagnostics is when running/debugging and the debug session failed to run due to compilation errors.
This has surfaced due to fixing an issue in the VS Code client.

Don't focus diagnotics if compialtion returned with error

---

docs/editors/overview.md

This comes from the comment in #2595. I add a small note about our
Ammonite not supporting multi-stage scripts and also not currrently
supporting Scala 3.
I also noticed we had a small "Unsupported features" section which was
out of date, but also very minimal. So I don't really think it's useful
unless we have a more exhaustive list of what is not supported.

docs(ammonite): add note about ammonite support

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Previously, we would GotoPosition, which is a server command and because of that got removed from the client. Now, we use GotoLocation instead, which serves the same purpose.

Fix goto definition for local synthetics

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/InsertInferredType.scala
tests/unit/src/test/scala/tests/codeactions/InsertInferredTypeLspSuite.scala

Previously, we would special case `case a @ b =>` to allow inserting type on b. This however was causing flakines in a tests (and possibly in real usage), it wasn't working properly and this edge case is unlikely (we would have a double pattern var). Now, we disable inferring type when parent of pattern variable is pattern bind.

Do not insert inferred type on variable bound to another

---

build.sbt
metals/src/main/resources/db/migration/V3__Jar_symbols.sql
metals/src/main/scala/scala/meta/internal/metals/Tables.scala

This version has removed support for all PageStore format, so a totally new file will get create. I also needed to add `unique` to id, which is used as a foreign key.

Migrate to the newest H2 version

---

mtags/src/main/scala/scala/meta/internal/mtags/GlobalSymbolIndex.scala
mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala

Adding range to symbol definition will allow tests provider to not load semanticDB per each test suite. Instead, the position can be obtained from the aforementioned symbol definition.
credits: @tgodzik

feat: add range to symbol definition

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala

Since we only list files in jars there should not be any possibility for it to break and these are not sueful to the user.
This only happens in jars that have `/home` directory in the jar.
Fixes https://github.com/scalameta/metals/issues/3594

Ignore UncheckedIOException coming from broken source jars

---

.scalafmt.conf
build.sbt
metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala
metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala
metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClassesFinder.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileProvider.scala
metals/src/main/scala/scala/meta/internal/worksheets/DecorationWorksheetPublisher.scala
metals/src/main/scala/scala/meta/metals/DownloadDependencies.scala
mtags/src/main/scala-2/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SelectionRangeProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SignatureHelpProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/FilenameCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/ScaladocCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompletionPos.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SelectionRangeProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbSymbols.scala
mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala
mtags/src/main/scala/scala/meta/internal/mtags/KeywordWrapper.scala
tests/cross/src/test/scala/tests/pc/CompletionParameterHintSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/TreeViewLspSuite.scala
tests/unit/src/test/scala/tests/testProvider/TestSuitesProviderSuite.scala

I mainly wanted to bump the scalafmt version that by default gets included in a new project if you don't have a .scalafmt file, since the 3.0.5 version has some issues with significant whitespace that I keep hitting on, so I always update it anyways.
Just to align them, I also then bumped the version that we are using for our project as well. There is only one place I really don't like the new formatting, but it does align with other formatting in the same file. I'll comment there.

chore(fmt): bump scalafmt to 3.4.0

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Java only targets don't get their dependency source jars indexed.  For comprehension didn't get past `scalaTarget <- buildTargets.scalaTarget(item.getTarget)`
I've assumed a 2.13 dialect for java-only targets - is that correct?

Index non-scala target dependency sources

---

metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
tests/slow/src/test/scala/tests/feature/FileDecoderProviderLspSuite.scala

There is an issue within ZipFileSytemProvider that will use the decoded path of the jar, which will not work in case of any special characters.
There is stack overflow question related to that:
https://stackoverflow.com/questions/9873845/java-7-zip-file-system-provider-doesnt-seem-to-accept-spaces-in-uri

Fix showing virtual docs in jars with paths that need escaping

---

.github/workflows/check_scala3_nightly.yml

The previous logic was invalid as usually nightly release date in version
doesn't match the today.
For example: `3.1.3-RC1-bin-20220214-4105afb-NIGHTLY` was released at
`2022-02-15`.
Also there might be more thant nightly release per day.
Now, the release will be triggered for all nightly versions that comes
after the last nightly mtags release.

fix: actions, discover new scala3 nigtly properly

---

.github/workflows/release.yml

Running this job in parallel leads to issues with publishing process.
Only one job was completed from the bunch of tags that was created for scala3-nightly: [#1004-#1015 runs](https://github.com/scalameta/metals/actions/workflows/release.yml)
Unfortunately, there is no way to configure this using std settings.
There is `job.concurrent` setting but it automatically [cancels all pending jobs](https://github.com/github/feedback/discussions/5435) from the same group.

fix: release workflow - prevent parallel publishing to sonatype

---

metals/src/main/scala/scala/meta/internal/metals/PresentationCompilerClassLoader.scala

There was an error during PC <init>: ` java.lang.NoClassDefFoundError: javax/tools/DiagnosticListener`.

fix: support Scala 2.11 PC on jdk higher than 8

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala
metals/src/main/scala/scala/meta/internal/metals/watcher/PathTrie.scala
tests/unit/src/test/scala/tests/PathTrieSuite.scala

Previously, on MacOS, the root of the workspace would be registered for
file watching. With this patch, up to 32 of the longest prefixes will be
registered.
This change improves the performance in large monorepos, where the
workspace is set to the root of the monorepo, but usually few
subdirectories are imported in the IDE.

Don't watch entire workspace on MacOS

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcDefinitionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcDefinitionProvider.scala
tests/cross/src/test/scala/tests/pc/PcDefinitionSuite.scala

Previously, Metals didn't go the definition of symbols that the
presentation compiler defines as synthetic. These symbols include
auto-generated case class `apply` methods and regular class
constructors. Now, we ignore the `isSynthetic` bit on the definition
symbol so that "Go to definition" works as expected for cases where it
didn't before.

Go to definition of synthetic symbols.

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionsProvider.scala
tests/cross/src/main/scala/tests/BaseCompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Fix https://github.com/scalameta/metals/issues/2400
- Check the parameter is synthetic by `.isSynthetic` instead of $
- Escape `$` from text edit. Otherwise, `$foo will be treated as a parameter in snippet mode.
- https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax

Fix named arg completion when parameter contains $

---

tests/slow/src/test/scala/tests/feature/DefinitionCrossLspSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala

Previously, we were not waiting for the compilation to finish which was causing the semanticdb not to be available. Now we properly use the for comprehension.
Fixes https://github.com/scalameta/metals/issues/3688

 Fix DefinitionCrossLspSuite

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
tests/unit/src/test/scala/tests/MetalsEnrichmentsSuite.scala

Yesterday on discord it was reported that an internal server error happens when Metals have to deal with a directory that contains spaces. The source of the problem was fact that Mtags and Metals xtension method for string differentiated in implementation.

fix: do not decode every URI when invoking `toAbsolutePath`

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
tests/unit/src/test/scala/tests/debug/CompletionDapSuite.scala

Previously, we would show completions for the previous statement. Now, we block it by adding `;`
Fixes https://github.com/scalameta/metals/issues/3381

Fix completions on dot in expression evaluator

---

mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala

This just aligns the usage of "using" since currently if you do a hover
on a method you'll see the implicit parameter using the "using" keyword
but then if you do a signature help on the same method you'll see
"implicit". This just ensure both are "using".

refactor: use "using" instead of "implicit" in Scala 3 signature help.

---

README.md

It's been a while since I've actively contributed to the project, let alone some reviews on the VS Code extension here and there.
I've also not been working with Scala at work for a while now, and I probably won't in the near future (I've been having lots of fun with design systems and UI architectures, in case anyone's curious 😅), so I haven't been able to justify much time spent on Scala OSS projects.
That said, nothing changes in practice (I'll be around Discord as always), but I think it's only fair to clarify my Metals maintainer status 🙂
Do absolutely feel free to keep asking for my review for the VS Code extension PRs if you feel it's valuable, I'll keep up with those as best as I can!

Move gabro to "past maintainers" in README

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala

Fix https://github.com/scalameta/metals/issues/2183
Previously, when a project generate sources at compile-time, for example, if `bench-jmh` project generate source files at compile time
- 1. Metals sends a compileRequest on bench-jmh
- 2. sbt replies that bench-jmh is compiled successfully
- 3. Metals sends a scalaMainClasses request on bench-jmh
- 4. sbt runs discoveredMainClasses that generates new sources
- 5. sbt replies that bench-jmh contains no Main classes
- 6. Metals detects the new generated sources and goes to step 1
This PR prevents metals from going to step 6, by stopping watching the file events fired from generated sources.
- We can tell the file is generated or not via BSP request `buildTarget/sources` which provides us whether the file/directory is generated or not. …

Exclude generated source items from FileWatcher (sbt BSP)

---

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
tests/unit/src/test/scala/tests/DebugDiscoverySuite.scala

This just ensures that when a user triggers a `runOrTest` for debug
discovery that if nothing is found the error is actually shown to the
user, which now it just quietly fails without notifying the user.

fix: Ensure the "no run or test" message is shown to user.

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

Currently if the current workspace has an error but there is still a
code lens to run the project, we just forward the params and try to
start the debug server. This then fails since there are errors in the
workspace and doesn't really show anything to the user. This is just a
slight change that adds a check before that to see if there are
workspace errors and if so, show the warning.
_Notice the user really has no feedback that something is wrong_.

fix: ensure user gets warned of workspace error when running with lens

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargetInfo.scala
metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
tests/slow/src/test/scala/tests/feature/FileDecoderProviderLspSuite.scala

Fix: https://github.com/scalameta/metals/issues/3718
With sbt BSP, `src_managed` directory has `(generated)` in `Source Directories` section for `metals-buildtarget`.
(bloop is not supported because it doesn't support [generated flag](https://build-server-protocol.github.io/docs/specification.html#build-target-sources-request) at this moment).
---
~Test with sbt server doesn't work now 🤔~

Add `generated` info to `Source Directories `section of `Display build target info`

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala

So the idea here is to ensure the user knows that something isn't going wrong as they are waiting for the debug server and to provide more feedback to them. There seems to be a couple places where we can add some status messages in to help with this. One is while we are starting the debug server since this may take some time to fully compile your project, and then second one is during the initialize request which seems to take between 3-5 seconds. This adds a status message into both of those places tracking the futures. Here is an example of what it looks like:
This is just a hello world project so the first message is quite quick, but this lengthens really quickly if you are developing in a real project. Either way, the entire time prior to this pr you don't get any feedback that …

feat: add more feedback to user when starting a debug session

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala

`mutable.Set.empty[FullyQualifiedName]` was always empty so every test suite in the build target was discovered even though it has been discovered in previous run already

fix: don't discover already discovered tests

---

metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
tests/slow/src/test/scala/tests/feature/FileDecoderProviderLspSuite.scala

Since this isn't supported for now we should correctly return an error
for this. Right now you can still trigger this in Scala 2 and it just
returns an empty string not really giving the user much information
about why it didn't work. This way clients can now handle this situation
better.

fix: return an error when trying to decode tasty in Scala 2

---

metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileProvider.scala
tests/mtest/src/main/scala/tests/Assertions.scala
tests/unit/src/test/scala/tests/NewFileLspSuite.scala

Previously there `New Scala File` -> `Empty File` were created with two
newlines between package and cursor instead of one

fix: create `new scala file` with a single NL

---

metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/DoctorResults.scala
metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
tests/slow/src/test/scala/tests/feature/FileDecoderProviderLspSuite.scala

Adds html links to build target info from the Doctor as in image above.
Does the command to navigate to a uri have to include location?  Or is there another command instead of `metals-goto-location`?  Ideally it would just open the URI.
@ckipp01 Is the addition of `gotoCommand` to the Doctor JSON the best way to handle non vscode clients?

add navigation from doctor to build target

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
tests/unit/src/test/scala/tests/DidFocusLspSuite.scala

Previously, Metals would only use the result of `buildTarget/sources` to
figure which target owns a given source file. Because
`buildTarget/sources` is issued as part of build import, the list of
sources (directories and files) returned by the build server could be
stored and re-used to immediately determine the owning target, given a
source file.
It turns out, however, that for some targets this knowledge can become
outdated. For instance, Bloop supports defining the source files as a
set of globs [1]. In this case, Bloop will respond to the
`buildTarget/sources` request issued during build import with the list
of files that match at this point in time. If the developer create a new
file which would be matched by Bloop's globs, Metals will be unable to
associate it with a target. …

Introduce uses of buildTarget/inverseSources

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargetInfo.scala
metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
metals/src/main/scala/scala/meta/internal/metals/URIEncoderDecoder.scala
tests/slow/src/test/scala/tests/feature/FileDecoderProviderLspSuite.scala
tests/unit/src/test/scala/tests/UriEncoderDecoderSuite.scala

This issues shows up for example in Mill projects which have the `[2.13.8]` added to indicate the version of the target.

Fix issues with non alpha numeric build target names

---

metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/DidFocusLspSuite.scala

Follow up for https://github.com/scalameta/metals/pull/3752
We encountered the flaky test result of `DidFocusLspSuite` in the PR, because
we expect the test suite invokes `didFocus("b/.../B.scala")`
**during the compilation by `server.didSave("a/.../A.scala")`**, and
didFocus triggers a compilation.
However, we didn't have a way to control the timing of compilation
start, end, and when we invoke `didFocus`. That's why the test was flaky.
see more details: https://github.com/scalameta/metals/pull/3752#issuecomment-1079878023
This PR ensure that we call `server.didFocus("b/.../B.scala")` during
the compilation by `server.didSave("a/.../A.scala")` by
- Adding 5 seconds of delay during the compilation
- to make sure we invoke `didFocus` before the compilation completed.
- Wait for 2.5 seconds …

Try to fix flaky test by adding a delay in compilation

---

mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
tests/cross/src/test/scala/tests/hover/HoverNegativeSuite.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala

Partially fix https://github.com/scalameta/metals/issues/1707 (hover part of the issue), taking over from https://github.com/scalameta/metals/pull/3743
FYI @tdudzik I opened a PR to fix the issue on the Hover part, if you're interested in working on go-to-definition part, please let me know :) 
This PR fixes Scala3 HoverProvider not to show a tooltip on hover if the cursor is not on a symbol by checking the `namePos` (for example, `namePos` of `def foo(x: Int) = { ... }` is a position of `def <foo>(...) = { ... }` part, not a entire `<def foo(x: Int) = { ... }>`) of the enclosing tree actually contains the cursor position.
Calculate the `namePos` using [SourceTree#namePos](https://github.com/lampepfl/dotty/blob/d8e50f249ce0206faae35d5d3d28f45f1e0f58d1/compiler/src/dotty/tools/dotc/interact …

[Scala3] Don't show a tooltip on hover if cursor is not on a symbol

---

build.sbt
tests/cross/src/main/scala/tests/BasePCSuite.scala

scala3 doesn't support `-Wconf=src` and compiling mtags on produced the following warnings:
```
[warn] Failed to parse `-Wconf` configuration: msg=parameter value .+ in anonymous function:silent,src=*.ScaladocParser.scala&msg=parameter value (pos|message) in method reportError:silent,src=*.Completions.scala&msg=parameter value (member|m) in method (isCandidate|isPrioritized):silent,src=*.JavaMtags.scala&msg=parameter value (ctor|method) in method (visitConstructor|visitMethod):silent,src=*.MtagsIndexer.scala&msg=parameter value owner in method visitOccurrence:silent,src=.*(CompletionProvider|ArgCompletions|Completions|Keywords|IndentOnPaste).scala&msg=The outer reference:silent
[warn] unknown filter: src
[warn] unknown filter: src
[warn] unknown filter: src
[warn] unknown filter: src …
```

fix: disable not supported Wconf for scala3

---

project/Scala3NightlyVersions.scala

It seems that the version is indeed listed on the maven central page, but nothing ever got released.

Remove broken nightly version

---

mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala

https://github.com/scalameta/metals/pull/3792#discussion_r845286402
e.g. interpolator-apply `num"... $foo"` has tree-like
```
Select(
Select(
Apply(
Ident(Xtension),
List(Apply(Select(Select(Select(Ident(_root_),scala),StringContext),apply),List(Typed(SeqLiteral(List(Literal(Constant(Hello )), Literal(Constant())),TypeTree[TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class scala)),object Predef),type String)]),TypeTree[AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class <repeated>),List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class scala)),object Predef),type String)))]))))
),
num
),
apply
),
```
(where `Select` is a subclass of NameTree). To check the position of `num`, we have to take a look at` select.qualifier`.

[Scala3] Fix hover on interpolator-apply

---

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala

- scalameta 4.5.1 supports [MatchType](https://dotty.epfl.ch/docs/reference/new-types/match-types.html) in SemanticDB  https://github.com/scalameta/scalameta/releases/tag/v4.5.1 
- The next version of Scala3 [will support MatchType](https://github.com/lampepfl/dotty/pull/14608) in SemanticDB
This PR should enable metals to show inferred `MatchType` with the latest Scala3 compiler.
I tried to test it locally, but I guess this change won't affect the behavior at this moment because
- `SemanticdbTreePrinter` is used only for showing the inferred type (in Scala3 at least, at this moment).
- However, I'm not sure about the situation where MatchType is inferred.
So this PR is safe to merge :)

Support MatchType in SemanticdbTreePrinter

---

metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala
metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala
metals/src/main/scala/scala/meta/internal/process/SystemProcess.scala

This PR redirects the stderr of BSP servers to the logs of Metals. It can be helpful when anything goes wrong with a BSP server, giving Metals users any message that the BSP server printed.

Log BSP server stderr

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargetInfo.scala
metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
mtags/src/main/scala-2/scala/meta/internal/metals/URIEncoderDecoder.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
tests/unit/src/test/scala/tests/MetalsEnrichmentsSuite.scala
tests/unit/src/test/scala/tests/UriEncoderDecoderSuite.scala

closes https://github.com/scalameta/metals/issues/3794

fix: uri encoding

---

mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala

Previously, in a number of scenarios this option would break the presentation compiler for Scala 3. Now we filter it out since it's not important for the frontend phases.

Remove -release option from the Scala 3 PC

---

mtags/src/main/scala-2/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala

fix: handle backticked names in inffered-type

---

.github/workflows/release.yml

Currently, github actions have some issues with filtering `runs`.
`gh api/repos/scalameta/metals/actions/workflows/release.yml/runs?status=in_progress` doesn't return any results.
There are several issues about that in github community forum - https://github.community/t/bug-we-are-having-problems-searching-workflow-runs-the-results-may-not-be-complete/244650
The only option for now is disable this lock logic.

fix: unblock release workflow

---

project/V.scala

This gets rid of the warnings about `-classpath` and `-bootclasspath`

Bump Bloop with a fix for #3766

---

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
tests/slow/src/test/scala/tests/feature/RenameCrossLspSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala

Fix https://github.com/scalameta/metals/issues/3133
This PR enables Metals to rename all extension parameters.
Previously, when metals rename `sbd`  in `double` method.
```scala
extension (sbd: String)
def double = sbd + sbd
def double2 = sbd + sbd
end extension
```
Metals couldn't rename `sbd` in `double2` method because `sbd` in `double` and `sbd` in `double2` have different (semanticdb) symbols.
This PR fixes the issue by
- Make `ReferenceProvider` return multiple `ReferenceResult` because `find-references` may find references for multiple symbols.
- For example, `sbd` in `extension (sbd: String)` is attached to two different symbols. see: https://github.com/scalameta/scalameta/issues/2443
- Now `reference` returns all references for all symbols.
- Therefore, this PR also fixes …

fix: Rename extension parameter in Scala3

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Looks like it was caused by the scalafmt update that happened in the meantime

Fix formatting after last merge

---

tests/cross/src/test/scala/tests/pc/CompletionScala3Suite.scala

resolve https://github.com/scalameta/metals/issues/2810
This issue is fixed by https://github.com/lampepfl/dotty/pull/14639 :tada: and it seems like released at least in 3.1.3-RC2 and newer.

test: Add test for completions of matchtype / higher-kinded type

---

mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcDefinitionProvider.scala
tests/cross/src/test/scala/tests/pc/PcDefinitionSuite.scala

https://github.com/scalameta/metals/issues/1707
Basically the same strategy as https://github.com/scalameta/metals/pull/3792
But this PR checks `isOnName` inside `enclosingSymbols` because this Metals-version of `enclosingSymbols` well deals with synthetic symbols like for-flatMap and caseclass-apply. We check `isOnName` only if it's not on synthetic symbols or special cases (e.g. `NameArg` and `Import`).
Maybe we can make hover (for Scala3) better using this Metals-version of `enclosingSymbols` and it handles the issue https://github.com/scalameta/metals/pull/3792#discussion_r845286402
---
Remained issues around `go-to-definition` and hover are
- https://github.com/scalameta/metals/pull/3792#discussion_r845713388
- Ignored tests in HoverTermSuite for Scala3

fix: (Scala3) Don't navigate to enclosing symbols on go-to-definition if cursor is not on symbol

---

metals/src/main/scala/scala/meta/internal/metals/doctor/ProblemResolver.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

Take scala version suffix in munit.
Do not show warning for sbt targets.

fix: show test explorer misconfigurations

---

metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala

It resolves #2697 
It is for getting bloop JVM settings from user config and then writing it in the global bloop json file.

bloop jvm settings

---

mtags/src/main/scala-2/scala/meta/internal/pc/SignatureHelpProvider.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpPatternSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala

Previously, we would always assume unapply returns a tuple, which would result in wrong signature help for single parameter unapply. Now, we take into account situations where the returned value is not an Option of tuple.

fix: Make signature help work properly with a non-tuple result

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
metals/src/main/scala/scala/meta/internal/metals/JavaTarget.scala
tests/slow/src/test/scala/tests/feature/FileDecoderProviderLspSuite.scala

Adds the classpath to the args of CFR so the decompile is more accurate.

Add classpath to CFR decompile

---

mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala

closes https://github.com/scalameta/metals/issues/3783

fix: infer jdk without jdk in name

---

metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
tests/slow/src/test/scala/tests/feature/FileDecoderProviderLspSuite.scala

Displays semantic db info on `java` and `scala` jar files using the internal interactive db info.  Jar files don't have a semanticdb file.
I've found this helpful when debugging goto/ref information on jar files.

Add semantic db info display on jar files

---

mtags/src/main/scala-2/scala/meta/internal/pc/SignatureHelpProvider.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpPatternSuite.scala

The only regression seems to be that a couple of test cases changed to `Any`, however this is a proper type and having `T` or `C[T]` probably looks a bit better, but doesn't actually show the real type.

Properly infer types for unapply signature help

---

metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala

Previously, when a Bloop JVM property was getting removed, if the new properties list were becoming empty, the Bloop settings were not getting updated!
This PR fixes that!

handles the removal of jvm properties case

---

bin/bloop.json
bin/test.sh
project/V.scala

.jvmopts is now deprecated and cannot be used
also bump Bloop to 1.5.0

Use bloop.json instead of .jvmopts for Bloop memory properties

---

docs/contributors/getting-started.md
docs/editors/overview.md
docs/editors/vim.md
docs/troubleshooting/proxy.md
metals-docs/src/main/scala/docs/WorksheetModifier.scala

As of this next release
[coc-metals](https://github.com/scalameta/coc-metals) will be officially
deprecated, meaning we shouldn't be pointing people to it in the docs,
and also shouldn't have all the features outlined be coc specific. This
makes those changes.
Note that this is much much more minimal than it previously was. This is
mainly because the docs for `nvim-metals` are pretty spread out, and I
don't have any intention of duplicating them.
- The main docs are in
https://github.com/scalameta/nvim-metals/blob/main/doc/metals.txt and
they are in a specific format necessary for Vim help docs.
- https://github.com/scalameta/nvim-metals/discussions/39 holds the
example configuration
- https://github.com/scalameta/nvim-metals/discussions/279 holds the
feature list and instructions on how …

docs: update vim docs to no longer point people to coc-metals

---

mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcDefinitionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
tests/cross/src/test/scala/tests/hover/HoverDefnSuite.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala

fix https://github.com/scalameta/metals/issues/3852
Before this change, https://github.com/scalameta/metals/pull/3792 made Metals to show the hover tooltip for "for-synthetic methods" such as "withFilter", "map", and "flatMap" even if the cursor is on methods.
When we hover on "<-" in for comprehension, Metals with Scala2 shows the tooltip for "map" method, but Metals with Scala3 didn't.
```scala
for {
x <@@- List(x).headOption
}
```
Now, when we hover on methods in for comprehension, Metals shows the tooltip for the correct symbol.
This PR also fixes missing "for-synthetic methods" tooltip in Scala3.
- Moved `enclosingSymbols` defined in `PcDefinitionProvider` to `MetalsInteractive` so that `HoverProvider` can use it too.
- Now, `HoverProvider` uses `MetalsInteractive.enclosingSymbols` …

[Scala3] Show correct tooltip on hover methods in for comprehension

---

.github/workflows/ci.yml
sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala
sbt-metals/src/sbt-test/sbt-metals/semanticdb/a/src/main/java/test/JavaSample.java
sbt-metals/src/sbt-test/sbt-metals/semanticdb/a/src/main/scala/test/ScalaSample.scala
sbt-metals/src/sbt-test/sbt-metals/semanticdb/build.sbt

In case of jdk17, semanticdb-plugin requires `-J*` flags otherwise
compilation fails. These flags can be passed only at the JVM start.
Her, we explictly define `javaHome` for jdk >= 17.
It forces sbt to use `ForkJavaCompiler` that accepts `-J` flags instead
of `LocalJavaCompiler` which ignores them.

fix: sbt-metals + java semanticdb issue on jdk17

---

metals-bench/src/main/scala/bench/ClasspathOnlySymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsSymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala
mtags-interfaces/src/main/java/scala/meta/pc/ParentSymbols.java
mtags-interfaces/src/main/java/scala/meta/pc/SymbolSearch.java
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala
mtags/src/main/scala/scala/meta/internal/pc/EmptySymbolSearch.scala
tests/cross/src/test/scala/tests/hover/HoverDocSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala
tests/mtest/src/main/scala/tests/TestingSymbolSearch.scala

Previously, we would only return docstring if the current method has them defined, which wouldn't work well in case of a lot of standard library methods. Now, we check parents for symbols so that we can print a proper scaladoc
Prompted by @kpodsiad , we can merge after https://github.com/scalameta/metals/pull/3865

Show parent scaladoc if implementation is returning empty

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala
metals/src/main/scala/scala/meta/internal/metals/TargetData.scala
metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala
metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcherEvent.scala

This PR replaces `FileTreeRepository` with `PathWatcher`. The former keeps a cached version of watched file trees while the latter does not. Since the implementation no longer hashes files, but looks only on modification time, we can only watch modifications without keeping any state.
This makes a huge difference especially on macOS, where in large projects the root of the project has to be watched. My motivation for this change is that from time to time, metals stopped working and threw OOM exceptions (I think I experienced something akin to https://github.com/scalameta/metals/issues/3020) and I had to delete the `.bloop` folder and restart metals. In a particular case, the cached paths took more than half of 4GB heap dedicated to metals.
Shoutout and huge thanks to @eatkins that fixed …

Reduce file watcher memory usage

---

metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala
tests/unit/src/test/scala/tests/StacktraceParseSuite.scala

Currently the stacktrace analyzer will not show links for jdk classes when the jdk has modules
So this would get a hyperlink...
```java
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
```
But this would not...
```java
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
```
Now the module is removed before the symbol is searched for and the jdk classes get hyperlinks.

Handle modules in stacktrace analyzer

---

metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala
tests/unit/src/main/scala/tests/BaseAnalyzeStacktraceSuite.scala
tests/unit/src/test/scala/tests/AnalyzeStacktraceLspSuite.scala

Handles following:
```scala
//> using scala "2.13.8"
//> using lib "org.typelevel::cats-effect:3.3.11"
package a
import cats.effect.IOApp
import cats.effect.IO
object Main extends IOApp.Simple {
val io = IO(5)
override def run: IO[Unit] = io
.map { _ => 
throw new Exception
()
}.void
}
```
```
java.lang.Exception
at a.Main$.$anonfun$run$1(Stacktraces.scala:12)
at apply @ a.Main$.<clinit>(Stacktraces.scala:9)
at map @ a.Main$.run(Stacktraces.scala:11)
at void @ a.Main$.run(Stacktraces.scala:11)
at run$ @ a.Main$.run(Stacktraces.scala:8)
```

feat: handle cats-effect async stacktrace in stacktrace analyzer

---

docs/editors/vim.md

Not sure why but an extra space is needed after the table to ensure the
next paragraph gets wrapped in a `<p>` and the markdown renders correctly.

fix: broken link display in vim docs

---

docs/integrations/new-editor.md
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala

Under https://scalameta.org/metals/docs/integrations/new-editor#discover-tests since there was no matching triplequote, some contents were unintentionally blocked.

docs: fix broken documents (Integrating a new editor)

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/MunitTestFinder.scala
tests/unit/src/test/scala/tests/testProvider/TestSuitesProviderSuite.scala

I decided not to store helper methods obtained from parent classes as it may introduce a bit complexity. Instead, these helpers are being cmputed each time and I think this should be fine because:
- testcases are discovered lazily
- testcases are updated only for already discovered files
- testcases can be updated only if necessary (store MD5?)
If this happen to be too compute intensive, this feature can always be disabled for a while.
I didn't test if this PR works in normal project, only created unit test for it hence it's draft. However, I would like to receive some feedback on it.

feat, test explorer: search for test methods in parent classes

---

mtags/src/main/scala/scala/meta/internal/metals/docstrings/ScaladocParser.scala

This is a follow-up for https://github.com/scalameta/metals/pull/3865 (I left the warning from Scala3).
```
[warn] -- Warning: /Users/tanishiking/src/github.com/tanishiking/metals/mtags/src/main/scala/scala/meta/internal/metals/docstrings/ScaladocParser.scala:1295:40 
[warn] 1295 |          Link(link, Option(title) map (Text) getOrElse Text(link))
[warn]      |                                        ^^^^
[warn]      |The method `apply` is inserted. The auto insertion will be deprecated, please write `scala.meta.internal.docstrings.Text.apply` explicitly.
```

refactor: fix warning from Scala3 in ScaladocParser.scala

---

metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala

I forgot to add some docstring and during this process I realized that regex is overcomplicated without reason so I simplified it a bit.

chore, docs: simplify cats-effect stacktrace regex, add docstring

---

project/Welcome.scala

Use current scala3 version instead of hardcoded `3.0.0`

chore: update scala3 version in welcome msg

---

mtags/src/main/scala/scala/meta/internal/metals/PackageIndex.scala
tests/unit/src/test/scala/tests/WorkspaceSymbolLspSuite.scala

Classpath search is based on filenames inside jars which might be
encoded. Like: `<:<` -> `$less$colon$less`.

fix: symbolSearch - support encoded names from classpath

---

docs/integrations/new-editor.md
metals-docs/src/main/scala/docs/BootstrapModifier.scala

Since Metals is now published for 2.13, this replaces the last remaining
places in the docs where it mentions 2.12 in any instructions.

chore(docs): ensure metals_2.12 is replaced with metals_2.13

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionItemResolver.scala
mtags/src/main/scala-2/scala/meta/internal/pc/Signatures.scala
mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompletionItemResolver.scala
mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbSymbols.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
mtags/src/main/scala/scala/meta/internal/pc/ItemResolver.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala
tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala

This code is mostly copied over from Scala 2 and adapted to Scala 3. I also moved a couple of parts to a common trait.
Now, in Scala 3 we get scaladoc and shows default values when moving accross completions. Previously, we would onlt show the ones from the compiler and eagerly, which is not needed.
You can see what is added on the right.

feature: [Scala 3] Add completion item resolution

---

mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
tests/cross/src/test/scala/tests/hover/HoverDocSuite.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala
tests/cross/src/test/scala/tests/hover/RangeHoverSuite.scala

Previously, when an expression was inlined and was transparent we would not show the proper type as indicated by transparent. Besides that no flags were shown for methods. Now, we also check for Inlined tree node when expanding and also show the proper flag string.
Fixes https://github.com/scalameta/metals/issues/3929

Fix expression type for inlined methods and show all flags for methods

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionItemResolver.scala
mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala
mtags/src/main/scala/scala/meta/internal/pc/CompletionItemData.scala
mtags/src/main/scala/scala/meta/internal/pc/ItemResolver.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideAllSuite.scala
tests/unit/src/test/scala/tests/codeactions/ImplementAbstractMembersLspSuite.scala

Previously, we would use x$0 etc for Java parameter names, which was caused by completions not resolving documentation by design. Now, we resolve the names for 'implement all' completion and always resolve docs for 'implement all' code action.
This turned out much harder to fix than I estimated.

Include proper names when using implement all completion and code action

---

mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpPatternSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala

Two main changes here:
- updates to the signature help and Scala 3 (a lot of fixes and a bug reported upstream)
- fixed the failing test for CompletionSuite (it will probably fail once again when the proper fix is introduced into Dotty, but I hoped the fix would be made much sooner)
- added testing for Scala 3 unapply signature help with some more bugs reported upstream

Fix nightlies tests and uncomment SignaturePat suite tests

---

mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbSymbols.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SignatureHelpProvider.scala
tests/cross/src/main/scala/tests/BaseSignatureHelpSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala

Previously, we wouldn't show any documentation for signature help. Now, we properly look for it the same way as in hover and completions
I also extracted signature help from the ScalaPresentationCompiler class.

feature: Show scaladocs for signature help

---

metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileProvider.scala
tests/unit/src/test/scala/tests/NewFileLspSuite.scala

So this isn't really a bug, but sort of an interesting difference in how
different editors handle \n -- whether they treat it as a line
terminator or an actual new blank line when at the end of a file.
Currently when you use the new scala file provider the text you end up
getting is just the package followed by multiple new lines. Some editors
will interpret this as the package line and then two new blank lines,
while others (like vim) will treat this as a package line, one blank
line, and then a line ending. Then when the Metals calculates the
position of the cursor it will be out of bounds for vim. This small
change just ensures the `@@` for the new blank file template is not on
the last line meaning it won't be out of bounds. There will be a slight
difference in VS Code though as there …

fix: avoid out of bounds for editors that treat \n as a line end

---

docs/integrations/test-explorer.md

This just adds an explicit note that if a client is trying to use the
test-explorer not only do they need the `initializationOption` set, but
they also need to ensure the `test-user-interface` user config is set to
`test explorer` or there will never be information about the tests sent
since the `TestSuitesProvider`'s check for `isEnabled` will be false.

docs(test-explorer): add note about test-user-interface

---

mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SignatureHelpProvider.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpPatternSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala

Previously, we would show the generic type of a method signature without trying to resolve the exact types. Now, we properly resolve types based on the qualifier.

feature: [Scala 3] Show correct inferred type in signature help

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/ProblemResolver.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/ScalaProblem.scala
project/V.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

Previously, this sbt version error in Metals Doctor was wrongly suggesting I upgrade sbt to 1.3.2:
This is also paired with a startup message saying "Multiple problems detected in your build."
~It looks like there was a bug where the sbt version check was doing the same thing as the Scala version check (checking `ScalaVersions.isDeprecatedScalaVersion(scalaVersion)`) . I updated this to check the `sbtVersion` against `1.3.2` as the error message implies.~
~**Note** I fixed the check for `UnsupportedSbtVersion` but removed the checks for `DeprecatedSbtVersion` and `FutureSbtVersion` since they were also broken and it isn't clear what those version bounds should be... I can add them back if those bounds exist~
---
Update: Turns out the message was just out of date and everything was working …

Fix SBT version check in Doctor

---

.github/workflows/release.yml

The issue on Github Api side related to filtering job by status was fixed

actions: return release job lock

---

docs/integrations/new-editor.md

This is documented, but looking at the implementation there is no
`status-bar` option anymore. This just removes this from the docs to not
confuse anyone.

docs: remove status-bar as option for slowTaskProvider

---

tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

The issue with missing members was fixed

fix: revert temporal changes in completions tests for 3.2.*-NIGHTLY

---

metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala

It seems to be breaking currently in worksheets and I don't think it's neccessary to fix that currently.

bugfix: Remove Wconf from scalac options in worksheets

---

website/blog/2022-05-31-aluminium.md
website/blog/2022-06-03-aluminium.md

If it's all good, I'm planning to release 0.11.6 next Tuesday (2022-05-31) (as I don't have much time until then).
```
❯ git show "v0.11.6"                                                      
tag v0.11.6
Tagger: Rikito Taniguchi <rikiriki1238@gmail.com>
Date:   Fri Jun 3 16:01:18 2022 +0900
v0.11.6
commit e716a55ac6a3aed8561c0d8e9308ab0eff74de38 (tag: v0.11.6, metals/main, main)
Merge: 56063859e1 6ed9732806
Author: Tomasz Godzik <tgodzik@users.noreply.github.com>
Date:   Thu Jun 2 16:46:45 2022 +0200
Merge pull request #3969 from tgodzik/fix-windows-escaping
bugfix: Escape java home path on windows
```
- before merging this
- after merging this

docs: release note for Metals 0.11.6

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/mtags-auto-release.yml
build.sbt

Bump the versions for v0.11.6, following the release guide https://scalameta.org/metals/docs/contributors/releasing
Let's merge after we confirm that v0.11.6 is out on Maven central.

chore: update version for v0.11.6

---

mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionsProvider.scala
tests/cross/src/main/scala/tests/BaseCompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetNegSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala

Previously, when completing a function we would only write the name even if the method needs parameters. Now if the client supports snippets we additionally add parenthesis where aplicable.
I also added a completion for apply in case of companion objects.
Fixes https://github.com/scalameta/metals/issues/3945

feature: [Scala 3] Add snippet completions

---

metals/src/main/scala/scala/meta/internal/metals/Configs.scala
project/V.scala

lsp4j 0.13.0 is compatible with LSP 3.17.0, which supports new features such as inlay hints.
From LSP 3.17.0, [SymbolInformation is deprecated](https://github.com/microsoft/language-server-protocol/issues/1389), but let's go with SymbolInformation for now (we can work on it in another PR).

chore: Update lsp4j to 0.14.0

---

.github/steward-repos.md
.github/workflows/scala-steward.yml

So this again is sort of temporary with the hopes that a public instance
gets added, but since we already have this up and running for Metals,
it's quite easy to just add the other scalameta repos into this job as
well. I copied the list of scalameta projects from
`scala-steward-org/repos`.

chore(deps): add in other scalameta repos to steward job

---

metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala
tests/unit/src/test/scala/tests/scalafix/ScalafixProviderLspSuite.scala
tests/unit/src/test/scala/tests/testProvider/TestSuitesProviderSuite.scala

Previously, it would not be possible to run sclafix inside metals aside from organize imports. Now, it's possible to run a list of predefined rules and ones added in settings.
Fixes https://github.com/scalameta/metals/issues/4005

feature: Allow to run all scalafix rules on a file

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Previously, no links would be shown for implicit parameter decorations in for comprehension. Now it's properly showed for the user.
The issue was that we were filtering synthatic decorations for a line based on the toplevel synthetic range, which in case of for comprehensions would be the full for comprehensions tree.
Fixes https://github.com/scalameta/metals/issues/3997

bugfix: Properly show links to implicit parameters in decoration hovers

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Previously, we would reset diagnotics when connecting to build server which cause issues if the build server published some diagnostics in the meantine, for example ScalaCLI will send info about any issues right away. Now, we only reset in one place before connecting to the build server.

bugfix: Reset diagnostics before connecting to new server

---

build.sbt
project/V.scala
tests/cross/src/test/scala/tests/pc/MacroCompletionSuite.scala

Previously, we were testing kind projector with `?` and since Scala 2.12.16 allows to use instead of `_`, the test stopped working. Now, the test case is updated to work with `*` instead and kind projector is updated to newest. I also the compiler plugins in tests to update automatically.

chore: Fix errors for kind projector

---

metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala

I also hit on this during work and it annoys me. If you have a build
that is using wartremover and you are using the default set of
`Warts.unsafe` it includes the `NonUnitStatements` rule. When this rule
is part of your `scalacOptions` when you attempt to create a worksheet
next to your sources it will never work due to the binder in mdoc.
You'll get the following error at the top of your file and nothing will
evaluate:
```scala
val x = 3 // example piece of code in your worksheet
```
```
Diagnostics:
scala.worksheet.sc:9 (mdoc generated code) [wartremover:NonUnitStatements] Statements must return Unit
val x = 3; $doc.binder(x, 1, 4, 1, 5)
```
This change just strips out that rule so it doesn't get passed in during
evaluation so that your worksheet can actually evaluate.

fix(worksheets): filter out NonUnitStatements wartremover in worksheets

---

metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
tests/unit/src/test/scala/tests/MillVersionSuite.scala

I just hit on this with https://github.com/com-lihaoyi/requests-scala
since they have a `mill` file which contains the default mill version
being used, but we only check for the version in the `.mill-version`
file. While most repos will have a `.mill-version` this adds an extra
fallback to check in the `mill` file to also grab it before we use the
default one we have. It can be the case that they are using an older
version of `mill` and our default version won't work to do the build
import. This guards against that.

feat(mill): also check default version in mill file

---

metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ConvertToNamedArguments.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala-2/scala/meta/internal/pc/ConvertToNamedArgumentsProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/test/scala/tests/pc/ConvertToNamedArgumentsSuite.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/main/scala/tests/codeactions/BaseCodeActionLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ConvertPatternMatchLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ConvertToNamedArgumentsLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ConvertToNamedArgumentsSuite.scala
tests/unit/src/test/scala/tests/codeactions/ExtractValueLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/InsertInferredTypeLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/RewriteBracesParensLspSuite.scala

@ maintainers thanks for all the work you do! This is my first PR, I appreciate any feedback :slightly_smiling_face: 
Fixes https://github.com/scalameta/metals-feature-requests/issues/229
Adds a code action which converts all positional arguments in the enclosing `apply` method to named args.
TODOS/open questions:
[ ] - Scala 3 support
[ ] - tests. I started by trying to extend `BasicCodeActionLspSuite`, but ran into this error with the presentation compiler. I'd appreciate some direction here :)
```
Caused by: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract java.util.concurrent.CompletableFuture convertToNamedArguments(scala.meta.pc.OffsetParams, int)' of abstract class scala.meta.pc.PresentationCompiler.
```
[ ] - Currently, if there are no args in the …

Add ConvertToNamedArguments code action

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala

Explained pretty well in https://github.com/com-lihaoyi/fansi/issues/46.
Full stacktrace of exception which was previously thrown:
```scala
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
at …
```

fix: do not fail when stripping ansi codes

---

build.sbt

All options were concatenated into a single string that might lead to
an incorrect values in important properties (`user.dir`, ...)

fix: remove improper javaOptions initialization

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionPos.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala

fix https://github.com/scalameta/metals/issues/4027
Before this commit, the code action always add indent with spaces, now
Metals support tab indent in implement-all code action.
If the class / object to implement is indented with tabs,
Metals will use tabs for indents instead of spaces.
As a limitation, Metals cannot infer the indent from the whole file:
for example
```scala
package foo
abstract class Foo:
\tdef foo: Int
class FooImpl extends Foo
```
we should implement `FooImpl` with tabs, but we can't
because Metals infers the indent from the line of `FooImpl`.
In this case, there's no indent, and fallback to space indent.

fix: support tab indent in implement-all code action

---

docs/contributors/releasing.md

Based on my experience of releasing 0.11.6, I added some words to release documentation that I couldn't understand.
- Add a link to GitHub API token page (at first glance, I couldn't understand which token do I need)
- add words which scopes are needed

docs: Update release documentation

---

README.md

I realized I'm not listed in the maintainer's section of README, let me in!

docs: Add Rikito Taniguchi to maintainers

---

mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/DotcPrinter.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/ShortenedNames.scala
tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideConfigSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala

https://github.com/scalameta/metals/issues/3928
This PR enables OverrideCompletions and implement-all abstract members' code action for Scala3 to import using preset renames like `java.util => ju`.
```scala
abstract class JUtil {
def foo: java.util.List[Int]
}
class Main extends JUtil {
def foo@@
}
```
completes
```scala
import java.{util => ju}
abstract class JUtil {
def foo: java.util.List[Int]
}
class Main extends JUtil {
def foo: ju.List[Int] = ${0:???}
}
```

feat: OverrideCompletion can handle symbolPrefix

---

metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/DismissedNotifications.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala

Previously, metals would suggest to update bloop.json file even if it was readonly and there would be no way to dismiss the notification forever. Now, we will not suggest to update the file if it's readonly and users can ignore the notification if they want to. It's also possible to later reset all the notification so that everything can pop up again.

feature: Don't update readonly bloop.json and allow to dismiss notifications

---

.github/workflows/sourcegraph.yml
.gitignore

The project was recently renamed to scip-java and lsif-java has been
[deprecated](https://github.com/coursier/apps/pull/153). I see we are
having an issue where no main class is being found, which was attempted
to be fixed [here](https://github.com/coursier/apps/pull/155), but I'm
still unable to run it locally. This just ensures that we are using the
most recent setup to ensure that our sourcegraph uploads are still
working.

fix: lsif-java -> scip-java

---

metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/Memory.scala

Previously, when Metals was run on JDK17 with `-Dstatistics=memory` one was getting multiple times:
```scala
java.lang.RuntimeException: Cannot get the field offset, try with -Djol.magicFieldOffset=true
at org.openjdk.jol.vm.HotspotUnsafe.fieldOffset(HotspotUnsafe.java:461)
at org.openjdk.jol.layouters.CurrentLayouter.layout(CurrentLayouter.java:70)
at org.openjdk.jol.vm.HotspotUnsafe.sizeOf(HotspotUnsafe.java:207)
at org.openjdk.jol.info.GraphWalker.walk(GraphWalker.java:97)
at org.openjdk.jol.info.GraphLayout.parseInstance(GraphLayout.java:54)
at scala.meta.internal.metals.Memory$.footprint(Memory.scala:31)
at scala.meta.internal.metals.Indexer.logMemory(Indexer.scala:179)
at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$4(Indexer.scala:155)
at …
```

chore: handle memory footprint errors on JDK17

---

mtags/src/main/scala-2/scala/meta/internal/pc/ScalaCompilerAccess.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Scala3CompilerAccess.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Scala3CompilerWrapper.scala
mtags/src/main/scala/scala/meta/internal/pc/CompilerAccess.scala
mtags/src/main/scala/scala/meta/internal/pc/CompilerJobQueue.scala
tests/cross/src/test/scala/tests/pc/CancelCompletionSuite.scala

Previously, if the compiler was stuck in an infinite loop we would not be able to invoke any methods on the compiler. For Scala 2 we had a separate presentation compiler thread, which would get properly interupted stopped. Now, ~~we interrupt the thread the compiler is running~~ we need to reset the job queue and in the local testing this has helped. Unfortunately, I don't know how to reproduce the infinite loop and this should no longer be an issue for later Scala 3 versions
I also added handling of compiler exceptions, since there are currently none that I know of that should just we thrown and hnadled specifically.

bugfix: Make sure that the Scala 3 compiler always retries properly

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
project/TestGroups.scala
tests/unit/src/test/scala/tests/scalafix/ScalafixProviderLspSuite.scala

Previously, if a user used an unknown rule we would fail and make them add the dependency manually. Now, we added all known hygiene rules from https://scalacenter.github.io/scalafix/docs/rules/community-rules.html by default.
I was also considering code generation rules, but we can add it later if needed.
This is a stop gap measure until it's possible to define dependencies in `.scalafix.conf` https://github.com/scalacenter/scalafix/issues/1625

feature: Add known scalafix rules' dependencies

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideConfigSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala

fix https://github.com/scalameta/metals/issues/4062
Implement-all code action for Scala3 infers the insert position based on the existing members if there are no braces.
Previously, Metals infer the insert position based on the class's constructor parameters and type parameters.
For example,
```scala
class Concrete[T] extends Base
```
Metals had been inferring the position based on `T` and we end up
inserting stub implementation in the wrong positions.
This commit excludes type params from the "existing declaration".
Extension methods shouldn't have an `override` keyword. For example, the following code will be invalid.
```scala
class Concrete extends Base:
override extension (x: Int) def foo: Int = ???
```
This commit excludes the `override` keyword if the completing method is an …

fix: (scala3) insert correct position for implement-all code action on class with type parameters

---

.github/workflows/sbt-dependency-graph.yml

Could be useful to submit the dependency graph of Metals to Github to find vulnerabilities.
But also I would like to test the sbt-dependency-graph-action on a project with many cross Scala versions.

Add sbt-dependency-graph workflow

---

.github/workflows/sbt-dependency-graph.yml

Exclude the test projects to avoid resolving the snapshot version of mtags

Fix sbt-dependency-graph workflow

---

metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/BuildTargetUpdate.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/JunitTestFinder.scala
tests/unit/src/test/scala/tests/testProvider/TestSuitesProviderSuite.scala

needs https://github.com/scalameta/metals-vscode/pull/1043
VS Code updates range of test suite using their own heuristic but sometimes it yields wrong results. This should be handy also for potential non-vscode clients.
Todo: 
I want to do some cleanup in Test Explorer, get rid of ballast code but this will happen on subsequent PRs.

feat: update test suite location

---

mtags/src/main/scala-3.2/scala/meta/internal/pc/MetalsSignatures.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionPos.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/ScaladocCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionScaladocSuite.scala

close https://github.com/scalameta/metals/issues/3955
Overview, basically the same with Scala2 implementation:
- if the cursor follows `/**`, insert `*/` on the cursor and compile it using `InteractiveDriver`
- We need to close the multiline comment, otherwise, the following code will be commented out, and we can't retrieve the tree of the code under `/**`.
- Find the class/method definition we're documenting
- the class/method that defined just below the cursor
- (I simplified the algorithm than Scala2 one. In Scala2, we try to find the class/method that is defined closest to the cursor)
- Extract the method or class constructor parameters, and construct the text.

feat: ScaladocCompletion for Scala3

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Previously, we would not clean out decorations if all decorations where switched off, which would cause sticky decorations. Now, we properly send empty decorations when refreshing.
We will not be sending empty messages when the document changes with the additional `isSyntheticsEnabled` flag being checked.

bugfix: Refresh decorations even if empty to clear them out

---

mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala

Previously, metals saw mill build.sc as ammonite script, now we filter it out in isAmmoniteScript so that it's fixed
fixes https://github.com/scalameta/metals/issues/4035

bugfix: Build.sc was seen as Ammonite script

---

mtags/src/main/scala-3/scala/meta/internal/pc/printer/DotcPrinter.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/ShortenedNames.scala
tests/cross/src/test/scala/tests/hover/HoverDefnSuite.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala

Previously, we would print constant types as for example `1: Int` which is not correct Scala code. Now we simply print the literal type itself `1`
Also, we used to previously print refined types as `Foo{T = scala.Int}`, which is not correct Scala code. Now, we print it correctly as `Foo{type T = Int}`.
These two issues were predominatly popping up in Scala 3 inferred type provider.
Fixes https://github.com/scalameta/metals/issues/4113

bugfix: [Scala 3] Improve constant and refined types printing

---

metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala
metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/ProblemResolver.scala
tests/unit/src/test/scala/tests/JdkVersionSuite.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

java version through shell

---

docs/troubleshooting/faq.md
metals/src/main/scala/scala/meta/internal/metals/MetalsLogger.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala

Seems the main idea behind scribe is to make it easy to define in the code, so I decided to add an new metals property.
One issue is that Flyway debug logs still seem to end up in whichever handler is defined first, but this should not be an issue in most cases, since those logs are not super interesting.

feature: Add a way to turn on debug logging and fix scalafix warmup

---

docs/build-tools/maven.md

I was confused why the command from the docs wasn't working at all
What complicated things is that `maven-bloop` is somehow impossible to find on https://mvnrepository.com, even though it's indexed on https://index.scala-lang.org/scalacenter/bloop/artifacts/maven-bloop/1.5.2

[docs] Update Maven integration launcher to 2.13

---

metals/src/main/resources/db/migration/V4__Fingerprints.sql
metals/src/main/scala/scala/meta/internal/metals/Fingerprints.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/MutableMd5Fingerprints.scala
metals/src/main/scala/scala/meta/internal/metals/Tables.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/FingerprintsLspSuite.scala

Previously, if a user reloaded a broken workspace they would keep getting the dreaded "Could not load snapshot text for". Now, we save the fingerprints between restarts to improve the probability of finding the correct text, which corresponds to a semanicdb document.
It shouldn't save too much, since fingerprints are only updated for open files and we clean it after each reload.

bugfix: Save fingerprints between restarts

---

metals/src/main/scala/scala/meta/internal/metals/DocumentHighlightProvider.scala
tests/unit/src/test/scala/tests/DocumentHighlightLspSuite.scala

Previously occurrences of `var` in methods as reference and assignment were different, now we have separate logic for them, so that it highlights all occurrences properly
fixes https://github.com/scalameta/metals/issues/4093

bugfix: Occurence highlight did not work for local vars

---

metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
tests/slow/src/test/scala/tests/feature/FoldingCrossLspSuite.scala

fix https://github.com/scalameta/metals/issues/4133
Previously, Metals recognise only `-Xsource:3`, but it doesn't for
`-Xsource:3.0` (`-Xsource:3.x.x`) even though it is valid in Scala2
compiler.
see: https://github.com/scala/scala/blob/d23424cd3aa17f7ad95b81018c70ceed2566962b/src/compiler/scala/tools/nsc/settings/ScalaSettings.scala#L105
This commit change Metals to understand `-Xsource:3.x.x` in addition to
`-Xsource:3` scalacOption.

fix: Dialect should be scala21xSource3 for `-Xsource:3.x.x`

---

.git-blame-ignore-revs

Follow up of https://github.com/scalameta/metals/pull/4050. 
As you can see on e.g. [build.sbt on my branch](https://github.com/kpodsiad/metals/blame/94dfeaab7bbd522d61749e2e182c26f8cf2600f7/build.sbt) it works.

chore: update git-ignore-revs

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala

Added some more debug logs for:
- RenameProvider, since sometimes it fails without any messages and it's super hard to reproduce
- ConvertToNamedArguments command instead of Future.filter, which would throw an exception.

refactor: Show more debug messages

---

metals/src/main/scala/scala/meta/internal/metals/ScalacDiagnostic.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ImplementAbstractMembers.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala

fix: https://github.com/scalameta/metals/issues/4052
Now, implement all abstract members code action is
available for given instance:
When we have
```scala
trait Foo:
def bar: Int
def baz: String
given Foo
```
the code action will implement the given instance like
```scala
given Foo with
override def bar: Int = ???
override def baz: String = ???
```

feat: Adding stub implementations for abstract given instances 

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/InterpolatorCompletions.scala
tests/cross/src/main/scala/tests/BaseCompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala

Previously, when trying to provide inside a string we would not get completions from the workspace. Now, we properly add them.
Related to https://github.com/scalameta/metals/issues/2105 but it still needs a fix for Scala 3

bugfix: [Scala 2] Automatically import types in string interpolations

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
tests/unit/src/main/scala/scala/meta/internal/metals/debug/Completer.scala
tests/unit/src/test/scala/tests/debug/CompletionDapSuite.scala

Previously, I assumed that only single line is allowed when using expression evaluator, which turned out to be false. Now, we should provide proper completions even if the expression is multiline.
Unfortunately the logic is not as clear as I would like it to be, but making it work was not fun. The API for those completions is much worse than the normal one.

bugfix: Allow completions in multiline expressions when debugging

---

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
project/V.scala
tests/slow/src/test/scala/tests/feature/WorksheetCrossLspSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

Mdoc is currently being released for Scala 3.1.x, which means that if we use mdoc for worksheets it will not be able to run with a classpath containing any Scala 3.2.0 code. However, since mdoc should be comptable with any future Scala 3 version, we can force a later compiler version to run with it.
This efectively fixes the worksheet issue for later Scala 3 versions. That is until the interfaces change, but hopefully we use a very limited api, so this should never be an issue.
Fixes https://github.com/scalameta/metals/issues/4138

bughack: Force specific Scala 3 compiler for worksheets

---

metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ConvertToNamedArguments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ConvertToNamedArgumentsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/test/scala/tests/pc/ConvertToNamedArgumentsSuite.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala

Closes https://github.com/scalameta/metals/issues/4059
Add Scala 3 support for https://github.com/scalameta/metals/pull/3971

Add convertToNamedParameters support for Scala 3

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/metals/JavaFormattingProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/formatting/OnTypeFormattingProvider.scala
metals/src/main/scala/scala/meta/internal/metals/formatting/RangeFormattingProvider.scala
metals/src/main/scala/scala/meta/internal/parsing/ClassFinder.scala
metals/src/main/scala/scala/meta/internal/parsing/TokenEditDistance.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala/scala/meta/internal/metals/TextEdits.scala
mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
tests/cross/src/main/scala/tests/pc/BaseSelectionRangeSuite.scala
tests/mtest/src/main/scala/tests/RangeReplace.scala
tests/mtest/src/main/scala/tests/TestHovers.scala
tests/unit/src/main/scala/bill/Bill.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/FindTextInDependencyJarsSuite.scala
tests/unit/src/test/scala/tests/JavaDefinitionSuite.scala

Previously, we would be getting a lot of messages such as:
```
Caused by: java.lang.IllegalArgumentException: 76 is not a valid line number, allowed [0..72]
at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
```
which most likely are cause by the fact that input is not the same as the one used for position (most likely file changed and wasn't reparsed again)
Now, we explicitely handle any issues when the position is not available.

bugfix: Include method signature in the label

---

build.sbt

After updating sbt to 1.7.0, we started to get the following warnings
on startup of sbt.
```
/Users/tanishiking/src/github.com/tanishiking/metals/build.sbt:57: warning: method sonatypeRepo in class ResolverFunctions is deprecated (since 1.7.0): Use sonatypeOssRepos instead
resolvers += Resolver.sonatypeRepo("public"),
^
/Users/tanishiking/src/github.com/tanishiking/metals/build.sbt:58: warning: method sonatypeRepo in class ResolverFunctions is deprecated (since 1.7.0): Use sonatypeOssRepos instead
resolvers += Resolver.sonatypeRepo("snapshot"),
^
```
As the original PR to sbt/librarymanagement says, `sonatyOssRepos` add
`https://s01.oss.sonatype.org` in addition to
`https://oss.sonatype.org`.
https://github.com/sbt/librarymanagement/pull/393
for more information: …

chore: use sonatypeOssRepos instead of sonatypeRepo

---

metals/src/main/scala/scala/meta/internal/metals/ScalacDiagnostic.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala
mtags/src/main/scala/scala/meta/internal/mtags/MtagsIndexer.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/slow/src/test/scala/tests/feature/ImportMissingSymbolCrossLspSuite.scala
tests/unit/src/main/scala/tests/codeactions/BaseCodeActionLspSuite.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

refer https://github.com/scalameta/metals-feature-requests/issues/141
This PR enables Metals to auto-import missing extension method **from the workspace (it doesn't support import from third-party libraries).**
This is done by
- Index extension methods by `ScalaToplevelMtags`
- Show AutoImport code action for `value xxx is not a member of yyy`.
- Auto import given instances
- Auto import implicit classes
- completion for extension method and auto-import
- I'll open an feature-request-issue

feat: Import missing extension method

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
tests/unit/src/test/scala/tests/InverseDependenciesSuite.scala

Previously, when project contained module which was aggregating all other modules Metals might omit some build targets when computing `inverseDependenciesAll`.
In the following example, Metals were omitting build targets `D` and `E` (maybe not always as this might be non deterministic).
(note: this graph shows dependency relation between projects)
[![](https://mermaid.ink/img/pako:eNpNjkEOwiAQRa9C_rq9AAsTW3oCXRk2kzJaokCDsDBN7y6KJsxqXt5LZjbMwTAkbpHWRZyV9qLMUfT9QQwVhi9cWjNWGFtTQbUwVVA1QwfH0ZE15d72URppYccasqyG4l1D-710eTWUeDI2hQh5pceTO1BO4fTyM2SKmf-RslR-d79qfwO_1jrn)](https://mermaid.live/edit#pako:eNpNjkEOwiAQRa9C_rq9AAsTW3oCXRk2kzJaokCDsDBN7y6KJsxqXt5LZjbMwTAkbpHWRZyV9qLMUfT9QQwVhi9cWjNWGFtTQbUwVVA1QwfH0ZE15d72URppYccasqyG4l1D-710eTWUeDI2hQh5pceTO1BO4fTyM2SKmf-RslR-d79qfwO_1jrn)
Now, …

fix: return all inversed dependencies in `inverseDependenciesAll`

---

mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
tests/cross/src/test/scala/tests/hover/HoverDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Previously, we would show params in Java methods as $x0 etc. Now, we show the correct name based on the information cached in Metals.

bugfix: [Scala 3] Show correct param names in java methods

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/clients/language/DelegatingLanguageClient.scala
tests/unit/src/main/scala/tests/TestingServer.scala

Use `workspace/configuration` call to the client to sync userConfiguration before starting an actual server
initialization.
`didChangeConfiguration` notification call happens after `initialized`
that leads that server uses a default config during connecting to the
build server and doesn't use the actual value of `bloopVersion` setting

fix: request configuration before connecting to build server

---

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala
metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Previously, we would not print local type names properly and instead just print "_". Now we search for the display name of that local type alias and display it instead.
Fixes https://github.com/scalameta/metals/issues/4186

bugfix: Print local type aliases properly

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/cross/src/test/scala/tests/pc/AutoImportExtensionMethodsSuite.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

Previously, ScalaToplevelMtags didn't parse inline extension methods
```scala
extension (num: Int) def incr = ???
```
As a result, we couldn't auto-import those extension methods that are
written in inline style.
This commit fixes to parse those extension methods, and also, added some
pc tests for auto-import extension methods.

fix: index inline extension methods in ScalaToplevelMtags

---

project/V.scala

Bump dependency to latest stable (to not always override it in SBT dependencies).
Also, I see that metals is missing from the list of projects covered by new public instance of Scala Steward: https://github.com/VirtusLab/scala-steward-repos/blob/main/repos-github.md Should I create a PR there for it to be added. I can see steward config in the repo, and I guess it was using old instance (hosted by the creator of scala steward), which is now decommissioned.

Update debug adapter to 2.2.0 stable (dependency update)

---

metals-bench/src/main/scala/bench/ClasspathOnlySymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsSymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
mtags-interfaces/src/main/java/scala/meta/pc/SymbolSearch.java
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionsProvider.scala
mtags/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolQuery.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
mtags/src/main/scala/scala/meta/internal/pc/EmptySymbolSearch.scala
tests/cross/src/test/scala/tests/pc/CompletionExtensionMethodSuite.scala
tests/mtest/src/main/scala/tests/TestingSymbolSearch.scala
tests/mtest/src/main/scala/tests/TestingWorkspaceSearch.scala
tests/slow/src/test/scala/tests/feature/CompletionCrossLspSuite.scala
tests/unit/src/main/scala/tests/MetalsTestEnrichments.scala

https://github.com/scalameta/metals-feature-requests/issues/282
<details>
<summary>outdated screen record</summary>
</details>
Thanks to https://github.com/scalameta/metals/pull/4141, now extension methods are indexed by `MetalsSymbolSearch.`
This PR enables Metals to enrich completions by `enrichWithSymbolSearch,` which includes the extension methods found by symbol search.
Note that, we index extension methods in `val inWorkspaceMethods: TrieMap[Path, Seq[WorkspaceSymbolInformation]]` which is newly created in this PR.
see more details: https://github.com/scalameta/metals/pull/4183#issuecomment-1197614724
When `completion.kind == Method`, now Metals search for the extension methods from by `SymbolSearch#searchMethods`.
In `MetalsSymbolSearch`, it implements `searchMethods` to search for …

feat: Auto complete (missing) extension methods

---

mtags/src/main/scala/scala/meta/internal/pc/CompilerAccess.scala

Scala 3 compiler doesn't operate on a separate thread the same way as Scala 2 does, so interrupt will cause it to close all the channels while not actually stopping any computation by the compiler.
Fixes https://github.com/scalameta/metals/issues/4196
I tried reopening, but that's not really possible, so best is to not interrupt the thread.

bugfix: Don't use interrupt for the Scala 3 compiler

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala

it **partially** resolves #3954 
it **partially** resolves #3956
-  **filtering out invalid trait, object, class, import, or apply method completions** according to position for scala 3.
-  adding **square bracket suffix** where relevant for type, new, and instantiation completions, for scala 3.
-  adding **curly brace suffix** in new completions of trait, abstract, java interface types for scala 3.
-  applying **filtering** without enriching with symbols on the **interpolate completions**
**Not covered in the PR:**
https://github.com/scalameta/metals-feature-requests/issues/292
- member completion for Scala 3 as in:
```
object A {
new scala.Iterable@@
}
```
Covering it requires covering the case for `CompletionKind.Members` in `enrichWithSymbolSearch` and **filtering out the …

Scala 3 type completion

---

mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala

Previously, we would not show anything when selectDynamic or applyDynamic methods were used. Now, we look up the refinement to get the proper signatures.
Fixes https://github.com/scalameta/metals/issues/4192

bugfix: Print correct method signature for Selectable

---

.github/workflows/ci.yml
metals/src/main/resources/gradle/wrapper/gradle-wrapper.properties
metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala

It should be enough to mostly test on JDK 17 with a couple tests also running on JDK 8.

chore: Switch to JDK 17 for most tests

---

.github/workflows/sourcegraph.yml

You can read morea about his in https://about.sourcegraph.com/blog/announcing-scip

chore(ci): small changes to account for migration from LSIF -> SCIP

---

mtags/src/main/scala-2/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Previously we would not show package completions in a number of places, which is useful when using for example pprint. Now we properly show them in probably all the situations.
Looks like we didn't have tests for these.
Scala 2 tests have an additional completion, but that seems to be ignored by VS Code, though I wonder if this is an issue for other editors :thinking: 
@tanishiking Let's merge it before the release.

bugfix: Show package completions

---

mtags/src/main/scala-2/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala

This PR reverts the following changes.
- https://github.com/scalameta/metals/pull/4174
- https://github.com/scalameta/metals/pull/4223
Context: https://github.com/scalameta/metals/pull/4234#issuecomment-1208922560 we encounter some regressions related to the type completions feature. We revert those changes because we're going to release a new version of Metals, and it would be safer not to include those features in the new release https://github.com/scalameta/metals/pull/4214

[Scala 3] Revert type completions feature

---

website/blog/2022-08-10-aluminium.md

I (@tanishiking) misplaced the v0.11.8 tag to
https://github.com/scalameta/metals/pull/4214/commits/51260e5415e2cf7304703c87c0eeb70f4865b588
and generated the release note.
However, that commit is squashed and the previous release note was
something wrong with its metadata such as
- contributors (my commit numbers was wiredly bigger than actual number)
- Commits since last release contained the number of commits in the
release note PR
I re-tagged v0.11.8 to
https://github.com/scalameta/metals/commit/6bf55ab632a900331720fd5f04e916596a3311f6
and re-generated the release note.

docs: fix release note metadata

---

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
tests/unit/src/test/scala/tests/ImplementationLspSuite.scala

closes https://github.com/scalameta/metals-feature-requests/issues/289
It's a one liner and because of that it needs many lines of description ;)
---
```
// local symbols inheritance should only be picked up in the same file
(loc.symbol.isLocal && loc.file != currentPath)
```
Let's consider following example (from `ImplementationLspSuite`)
```
/a/src/main/scala/a/Main.scala
package a
trait Ap@@p
object outer{
abstract class <<State>> extends App
val app = new <<>>State{}. // local0
}
/a/src/main/scala/a/Other.scala
package a
object Other{
def main(){
trait Inner // local0
object InnerImpl extends Inner // local1 which extends local0
}
}
```
App is extended by `outer.State`, which is extended by `local0` in `Main.scala`. This is important because …

feat: include anon classes (val x = new Trait {}) in 'find all implementations'

---

.github/workflows/ci.yml
.github/workflows/mtags-auto-release.yml
.github/workflows/release.yml
tests/unit/src/test/scala/tests/FindTextInDependencyJarsSuite.scala
tests/unit/src/test/scala/tests/WorkspaceSymbolLspSuite.scala

I'd like to see if this works. There were a couple coversations a while back about
using setup-scala vs setup-java and it seems that many repos have migrated to just
using setup-java since it does offer sbt support, has a ton of users, and also
built-in sbt caching which simplifies a few things in our actions.
If you're rather just leave it as is since it is working fine, no
worries, I just really like that the setup-java offers built-in caching
for sbt.

chore(ci): migrate to actions/java to use built-in sbt caching

---

metals/src/main/scala/scala/meta/internal/metals/ScalacDiagnostic.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/InsertInferredType.scala
mtags/src/main/scala-2/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/InsertInferredTypeLspSuite.scala

Previously, if the type was wrong user would need to remove the type and invoke insert type code action again or just do it all manuall. Now, we suggest fixing the type whenever a type mismatch error is encountered.
Fixes https://github.com/scalameta/metals/issues/4217

feature: Adjust type if mismatch

---

metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala
tests/unit/src/test/resources/foldingRange-scala3/expect/BlockWithNoBraces.scala
tests/unit/src/test/resources/foldingRange-scala3/input/BlockWithNoBraces.scala

Previously, if a template was ended by EOF we would throw IndexOutOfBounds exception, however with optional braces it can end at EOF token, which doesn't correspond to any char. Now, we added a size check for that case.
Fixes https://github.com/scalameta/metals/issues/4243
We could try and adjust end pos to previous character, but that's also not that great since `)` doesn't really end a block

bugfix: Don't throw exception if template ends at EOF

---

mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/AmmoniteFileCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionsProvider.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala

It resolves #4201 
- It takes the workspace path of the `ScalaPresentationCompiler` and provides it to` CompletionsProvider` and ultimately the `AmmoniteFileCompletions`
- It utilises the same logic and code as in Scala 2 AmmoniteCompletions with the goal of making the tests for `Ammonite3Suite` pass

adding AmmoniteFileCompletions for scala 3

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Sometimes typedTreeAt can't insert type correctly, now as a fallback we search for the symbol in metalsScopeMembers.
Fixes https://github.com/scalameta/metals/issues/4244

Fix ArgCompletions for nested apply

---

mtags/src/main/scala-2/scala/meta/internal/pc/SignatureHelpProvider.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala

Previously, we would show a wrong parameter, when named params were present, in two ways:
- use wrong position for checking current highlighted param - this is due to the fact that all the params are synthetic in such situation
- use wrong order of params for the parameters present in the correct place
Now, those two issue are handled properly by:
- first, correct position was already calculated, but not used
- second, by adjusting the sorting
Fixes https://github.com/scalameta/metals/issues/4249
I added more docs than code since the behaviour was a little unclear

bugfix: Fix signature help when named params are present

---

build.sbt
metals/src/main/scala/scala/meta/internal/bsp/MetalsBspException.scala
metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala
metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/metals/DismissedNotifications.scala
metals/src/main/scala/scala/meta/internal/metals/ImportedBuild.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsBuildServer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
metals/src/main/scala/scala/meta/internal/process/SystemProcess.scala
metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
project/V.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
tests/unit/src/main/scala/tests/BaseRangesSuite.scala
tests/unit/src/main/scala/tests/BaseScalaCliSuite.scala
tests/unit/src/main/scala/tests/FileLayout.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/JdkVersionSuite.scala
tests/unit/src/test/scala/tests/ScalaCliSuite.scala
tests/unit/src/test/scala/tests/SystemProcessSuite.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

This PR makes Scala CLI support more reliable in two ways:
- it makes scripts (`.sc` files) work better in Scala CLI projects, by having Metals be aware of the way Scala CLI "wraps" those before passing them to scalac -  this is achieved by using a custom BSP endpoint, and relying on past work for Ammonite, in the commit `Handle pre-processed sources via BSP` (currently, https://github.com/scalameta/metals/pull/3790/commits/42253f62e19683ccb1a71aba311fc65fb7ec96a2)
- it adds non-BSP discovery based support for Scala CLI (that works alongside the existing 100% BSP-based one), in commit `Add non BSP-based Scala CLI project support` (currently, https://github.com/scalameta/metals/pull/3790/commits/6352c6d1027f2a909c43915a34cf5a6148bbf3d8)
Before these two commits, …

Add better Scala CLI support

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/Compilations.scala

Previously, we would not check if a build target can be compiled before sending a compile request. Now, we will not send the compile request if the build tool specifies a target as a one that can't be compiled.
Fixes https://github.com/scalameta/metals/issues/4254

bugfix: Check if the target can be compiled

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/CompanionObjectSuite.scala

Currently when you're in a large file with possible nested classes and
you trigger a code action you just see the `Create companion object` as
the code action title, but you don't get an indication of what you'll be
creating the companion object for. We do have that information so this
small change just adds the name of the thing we'll be creating a
companion object for in the code action title.

refactor: include the companion object name in code action title

---

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
tests/slow/src/test/scala/tests/feature/DefinitionCrossLspSuite.scala

Previously, we would show "Preparing presentation compiler" message, but since it seems to be on a critical path, it sometimes popped up and would not stop. Also the current place this is in is not actually downloading anything. Now, I decided after multiple iterations to just not show the message. If anything breaks we will show a proper message, but otherwise the message didn't add anything and might cause issues for the users.

bugfix: Don't show preparing PC message

---

build.sbt

In #4221 we started releasing artifacts from jdk17

fix: specify  `--release 8` flags

---

build.sbt

Follow up to #4267
I haven't properly checked it - interfaces doesn't use `sharedSettings`

fix: release 8 for mtag-interfaces

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala

Previously, we could get stale information in the worksheet, because we would not fully restart the worksheet presentation compilers. Now, we remove old compilers the same as with normal PC.

bugfix: Properly restart worksheet presentation compiler

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/InterpolatorCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala

Previously, when autocompleting inside a string, no workspace completions would be suggested. Now, they are added correctly.
It might be good to do some refactorings later on in the completions once we have everything in place.
Fixes https://github.com/scalameta/metals/issues/2105

bugfix: [Scala 3] Auto import symbols in string interpolation

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractValueCodeAction.scala

When extracting from block apply, like `Future { ...@@ }` we have to extract as method, not as a value, to not change the logic. Also improves titles, from `{ \n <<code>>` to `code`.
Connected to https://github.com/scalameta/metals/issues/4207

Better title for `extract value` code action

---

.github/workflows/mtags-auto-release.yml
.github/workflows/release.yml

Starting from 1.7.0 version sbt has more strict checks for crossVersions.
If a specific version isn't defined in `crossScalaVersion ` it can be passed only with force sign - `!`

Fix mtags release

---

mtags/src/main/scala-3/scala/meta/internal/pc/MetalsDriver.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Scala3CompilerAccess.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Scala3CompilerWrapper.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala

If the content didn't change since the last `driver.run`, do not compile
because the compilation unit should have the up to date typed tree.
Skip compilation saves up much of CPU usage when users are reading
source code (and hover on symbols) without modifying the source code.
---
What happens if we change in a file affect another file's type
information?
For example, when we have the following source files, if we hover on
`B.foo` in `A.scala`, Metals shows the symbol's type is `Int`.
```scala
// A.scala
def main = println(B.foo)
// B.scala
object B:
def foo: Int = ???
```
When we modify `B.scala` to `def foo: String = ???`, what happens to
`A.scala`?
You may think that, Metals keep using the old compilation
unit that shows `B.foo` as `Int` instead of `String` because Metals
invalidates …

Don't run InteractiveDriver.run if the content didn't "change"

---

.github/workflows/check_scala3_nightly.yml

Now this worklofw fails with:
```
Usage: cs List(complete) format index ...args...
Usage: cs List(complete) format index ...args...
No new releases found
```
In the latest version of `cs` the command `complete` was renamed to `complete-dep`.

ci: fix check_scala3_nightly workflow

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala

fix: https://github.com/scalameta/metals/issues/4232
We had a pc test
https://github.com/scalameta/metals/blob/ae5c4650aefb6e6228ad77991c5813c299e860ed/tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala#L220-L236
but the error position is different in Scala.
`<<new>> Foo` instead of `new <<Foo>>`
This PR fixes the issue, and added a LSP test.

fix: fix implement-all members for anonymous class

---

metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala

The change in question is in https://github.com/VirtusLab/scala-cli/pull/1262
This change should future proof Metals

chore: Adjust ScalaCLI version detection to new changes

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala

Previously, if ScalaCLI was not started from `.bsp` it would not be possible to run or debug. Now, we also check if we can run using built in ScalaCLI

bugfix: Allow to run/debug in ScalaCli when started from Metals

---

metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClasses.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/MunitTestFinder.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/ScalatestTestFinder.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/TreeUtils.scala
tests/unit/src/main/scala/tests/QuickLocation.scala
tests/unit/src/test/scala/tests/testProvider/ScalatestFinderSuite.scala
tests/unit/src/test/scala/tests/testProvider/TestSuitesProviderSuite.scala

needs https://github.com/scalameta/metals-vscode/pull/1117
Supports:
- `AnyFunSuite`
- `AnyPropSpec`
- `AnyFlatSpec`
- `AnyFunSpec`
- `AnyWordSpec`
- `AnyFreeSpec`
Example:

feat: implement basic Text Explorer support for scalatest

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/ScalatestTestFinder.scala

For every base class like `AnyFunSuite` there is also trait `AnyFunSuiteLike` which also can be used when writing tests. Previously, inferring styles wasn't working with those traits, this PR fixes it.

chore: improve scalatest style inferring

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/InterpolatorCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala

Previously, extension methods would only be available outside string itnerpolations. Now it's also available inside.
It would be probably be better to handle it together with normal extension methods, but since it's the two combined it might be difficult to do it sensibly.

feature: Automatically add extension methods in string interpolation

---

metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
metals/src/main/scala/scala/meta/internal/metals/TargetData.scala
tests/unit/src/main/scala/tests/MetalsTestEnrichments.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

In the last release of Mill they added better support for producing
SemanticDB for clients like Metals without needing any changes in your
build. However the way it's done is a bit different and unlike the other
build servers meaning that you can't detect it by looking at the
scalacOptions. This changes special-cases Mill for now when a user is
using mill-bsp in a version >= 0.10.6. Mainly this is so users don't see
a big red X mark next to semanticdb in the doctor. There still will be
one for Java support as currently there is no semanticdb being produced
for Java targets in Mill.

feat: better mill-bsp semanticdb support

---

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/DefinitionResult.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala

Previously, DefinitionProvider would just look for the definition of object. Now, it also checks if the object is not a synthetic apply and in that case it tries to find that exact apply in addition to the object.
Fixes https://github.com/scalameta/metals/issues/1809

bugfix: Find correct definition of apply when using case classes

---

mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/IndexedContext.scala

Sometimes `indexedContext.scopeSymbols` gave us symbols from an old version of the file, which was a problem in some tests, like here https://github.com/scalameta/metals/blob/cf2e8c0f977b6eb34aa95b9fd0cf3176be41ba17/tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala#L56-L59
Works the same as for scala2
https://github.com/scalameta/metals/blob/cf2e8c0f977b6eb34aa95b9fd0cf3176be41ba17/mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala#L689-L692

add isStale filter in IndexedContext

---

metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/cross/src/main/scala/tests/BaseAutoImportsSuite.scala
tests/cross/src/test/scala/tests/pc/AutoImportExtensionMethodsSuite.scala

close https://github.com/scalameta/metals/issues/4212
In https://github.com/scalameta/metals/pull/4141 we started indexing the
extension methods (for auto-import missing extension methods) in
`workspaceSymbolIndex` where we should index only top-level symbols.
Later in https://github.com/scalameta/metals/pull/4183 we decided to index
those extension method symbols in a separate index
(see more details around here: https://github.com/scalameta/metals/pull/4183#pullrequestreview-1050733868).
This PR refactor import missing extension method to use
the index only for extension method symbols.
This change slightly improve the performance of symbol search
and reduce the memory footprint for symbol index.

refactor: Do not index extension methods in workspaceSymbolIndex

---

mtags/src/main/scala-2/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala/scala/meta/internal/pc/ScriptFirstImportPosition.scala
tests/cross/src/main/scala/tests/BaseAutoImportsSuite.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala

Scala-cli wraps `.sc` files in a similar way as ammonite - puts it in
object so the resulting code in pc is:
```
object main {
/*script*///> using directive
//> using directive
...
}
```

fix: don't break using-directives by an auto-import for `.sc` in scala-cli

---

metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileProvider.scala
metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileTypes.scala
tests/unit/src/test/scala/tests/NewFileLspSuite.scala

A script file might be either ammonite or scala-cli.
Changed name and label just to be more explicit +an additional promotion point for scala-cli

chore: mention Scala CLi in new file provider

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionBuilder.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ConvertToNamedArguments.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateCompanionObjectCodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateNewSymbol.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractValueCodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/FlatMapToForComprehensionCodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ImplementAbstractMembers.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/InsertInferredType.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/OrganizeImports.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/PatternMatchRefactor.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/RewriteBracesParensCodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/StringActions.scala

Avoid repeating code when creating a lsp code action.
I've made a slight change to the code specified in the issue. Instead of passing a single `workspaceEdits` params in the `ActionCodeBuilder`, I have chosen to separate it in two parameter to handle the case where we can get an `Either` in the `ExtractRenameNumber` code action file without duplicating the `build` function.
Related to issue #4154

Issue#4154: Add builder for lsp code actions

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractValueCodeAction.scala
tests/unit/src/test/scala/tests/codeactions/ExtractValueLspSuite.scala

Previously we couldn’t extract value from
```scala
new Car(<<"red">>)
```
This pr enables it

fix extract value for `new` keyword

---

.github/workflows/scala-steward.yml
.scala-steward.conf

This commit makes Scala-steward to
- Run scala-steward more frequently (twice a week)
- Create only 5 PRs to scalameta/metals at a time
Previously, scala-steward runs only 1st and 15th of a month,
and steward creates a bunch of PRs (around 10~PRs at a time).
However, scalameta/metals CIs are heavy (it has 20 workflows and
each takes around 20-30 minutes), and as a result, CI stucks every
scala-steward days.
This commit makes scala-steward to run more frequently, and limit
the number of PRs steward creates at a time.
This change would limit the number of PRs steward creates and makes
CIs work smoothly for library updates.
---
What do you think about this update?

refactor: update scala-steward configs (run more frequently and limit number of PRs)

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionBuilder.scala

Previously, we would set both and a language client will choose only one of them, so if they are set and empty it will apply empty changes. Now, only one of those is set.

bugfix: Always set changes or document changes

---

.github/workflows/scala-steward.yml

https://github.com/scalameta/metals/actions/runs/2978475788
- Use single-quote instead of double quote
- Previously we run scala-steward every hour on Monday and Friday

fix: scala-steward cron

---

.github/workflows/scala-steward.yml

first step for https://github.com/scalameta/metals/issues/4333
Thit commit let scala-steward PRs put
Github labels such as `semver-spec-patch`, which will be
useful for mergify.
see:
https://github.com/scala-steward-org/scala-steward/pull/2523
https://github.com/scala-steward-org/scala-steward-action/pull/387

refactor: Add labels to scala-steward PRs

---

mtags/src/main/scala-3.2/scala/meta/internal/pc/MetalsSealedDesc.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala

By refactoring `visit` method we enable completions with `enum` cases.

Enable enum completions in pattern matching

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala

This pr adds case completions for single case classes and not sealed traits.
It's mostly for 
```scala
case class Foo(a: Int, b: Int)
List(Foo(1,2)).map { case@@} 
```

Add case completions for single case classes in Scala3

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala

fixes https://github.com/scalameta/metals/issues/4352
Also, I haven't realised before that test for scala enum in exhaustive match was broken and it is fixed now

Fix case completions for enum with params

---

.github/workflows/auto-approve.yml

part of https://github.com/scalameta/metals/issues/4333
- Auto-approve the PRs that is created by `scalameta-bot` and has label `semver-spec-patch`.
- `scalameta-bot` will approve the PR
Added this auto-approve workflow because scalameta/metals
requires PRs to receive at least one approval from authorized users
(maintainers) to merge.
Therefore, until someone approve the PR, mergify cannot merge the PR.
This workflow will self-approve (by `scalameta-bot`) and enable mergify
to auto-merge the library update PRs.
---
- I didn't use mergify's auto-review functionality, because mergify
cannot specify a user who approve the PR (with a free OSS plan)
- https://docs.mergify.com/actions/review/
- This action doesn't depends on other workflows result, which means will auto-approve even if the CIs …

Auto approve PR by scalameta-bot

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala

It moves the place where we add `space` at the end of completion.
It is mostly for pattern only completions
```scala
// while triggering completions here 
List(Option(1)).map{ case So@@ => }
//previously we got double space
List(Option(1)).map{ case Some(value) $0 => }
//now 
List(Option(1)).map{ case Some(value)$0 => }
```
It also adds `space` after every case in exhaustive pattern match, not only after the first one, although I'm not sure if its correct

Change adding space after case completions

---

.github/workflows/auto-approve.yml

part of https://github.com/scalameta/metals/issues/4333
Sorry for messing the actions so many times 😓 
---
Previously, the `auto-approve` code action tried to automatically approve PRs that is created by `scalameta-bot` and labeled with `semver-spec-patch` (on PR is created).
However, it didn't work in the following PR and github action
https://github.com/scalameta/metals/pull/4364
https://github.com/scalameta/metals/runs/8261788560?check_suite_focus=true
Because it seems like, there's no label information available on PR is created by `scalameta-bot`
It looks like scala-steward does
- create a pull request
- and then add labels to pull request
- because [create pull request doesn't support label](https://docs.github.com/ja/rest/pulls/pulls#create-a-pull-request) I guess.
- That's why …

fix: Detect pull_request label event for auto-approve

---

metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala

Connected to https://github.com/scalameta/metals/issues/2151
Now we can't force multiple build import using `Import Build` command

Limit running multiple import build

---

metals/src/main/scala/scala/meta/internal/builds/BloopInstall.scala

Connected to https://github.com/scalameta/metals/issues/2547
Previously, reloading editor while import build prompt was open resulted in prompt not reappearing. Now the prompt reappears, but only if it was not answered. If user closes it or chooses any option it works the same as before (closing dismisses it for 2 minutes).

Request import build after restart

---

build.sbt
mtags/src/main/scala-2/scala/meta/internal/pc/completions/AmmoniteCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
tests/slow/src/test/scala/tests/feature/AmmoniteSuite.scala

Hi, I've been playing around with Ammonite ivy import completions in metals (heavily inspired by https://github.com/com-lihaoyi/Ammonite/pull/957) using the awesome coursier api, demo:
https://user-images.githubusercontent.com/17688577/189854045-ea525c33-29a3-40d3-935f-56857652366f.mp4
It works very similarly to the existing completions for `$file`s, essentially we just ask `coursierapi.Complete` for completions.  Additionally, when we're at `import $ivy.|` we return a snippet to handle backticks, and when we're at `group:|` we make sure to get scala verion-specific (e.g. `%%`) completions also (hopefully these are both clear from the video).
There are a few TODOS/stuff I'm not 100% about:
- Scala 2 only atm
- ~the Scala version used by the coursier api is currently hard-coded (I'm unsure …

Add Completions for ivy Imports (Ammonite)

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/StringActions.scala

Previously, we would use generic `rewrite` type, but since recently VS Code started showing refactor types separately, so I think now would be a good time to change it to `rewrite.refactor`

improvement: Change string actions to RefactorRewrite

---

docs/editors/emacs.md
website/docusaurus.config.js

Hi!  I found that you can enable syntax highilghting for Elisp snippets fairly easy with Docusaurus:
This PR also fixes some amiss formatting of snippets, mainly that closing parenthesis shouldn't go on new lines (https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html second to last if you're interested :slightly_smiling_face:).
I hope this is helpful, there are a lot of comments so I find being able to differentiate them from code quite useful :slightly_smiling_face:.

Add Highlighting and Fix Formatting for Emacs Snippets in Documentation

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala
tests/unit/src/main/scala/tests/ScriptsAssertions.scala

Found this issue by running locally `tests.ScaCliSuite` - in my case a test with `.sc` file was flaky.
The problem is that scalaCli provides a semanticdb db for generated file from `.sc` that has a different positions (includes generated code) that then will be indexed by metals and break go-to-definition.

fix: use proper semanticdb document for `.sc` in scala-cli

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionPatternSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Adds a cross tests suite to check if we cover all cases like `case _: @@`, `case xxx @ So@@` etc.
Also fixes sorting completions when `CaseKeywordCompletions` are not exclusive. 
Edit: I moved all extractors to one place

Add cross tests for pattern only case completions, fix for typed case completions

---

bin/test-release.sh
project/V.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

Also, remove support for Scala 2.12.8 since that is 10 versions ago

chore: Add support for Scala 2.12.17

---

mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala

Most of similar files in mtags2/3 have the same name. This additional `s` often annoys me when I do file search in VSCode

chore: rename CompletionProvider

---

tests/slow/src/test/scala/tests/feature/AmmoniteSuite.scala

PReviously, no circe native was avaialable. Now. circe being also being released for native, so we need to adjust the test.

bugfix: Fix tests using circe for completions

---

mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Previously, Metals compute docstrings of the method using `symbolSearch.symbolDocumentation` from `defaultMethodSignatures`.
This is for two reasons:
- replace java parameters such as `x$1` with the one from the document
- to print default parameters
However, it will be covered by `documentItem/resolve` so we don't need to compute them on `textDocument/completion`.
Also, I profiled Metals and realized `symbolSearch.symbolDocumentation` takes much of the time of code completion. This change may significantly improve the response time of `textDocument/completion`, especially in the large repositories.
---
(sorry for the large screen shot of `async-profiler`)
paramsDocs part will disappear

fix: [Scala3] Don't compute docs on textDocument/completion

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/AmmoniteCompletions.scala

Hi!  This is a small PR which fixes TextEdit ranges when `-` appears in a dependency used for ivy completions.  Previously for example, selecting `io.get-coursier` at `io.get-coursi|` would leave you with `io.get-io.get-coursier`.
I tried to find out if there were any other chars that potentially could appear in artefact ids, https://maven.apache.org/guides/mini/guide-naming-conventions.html is not overly specific: ` then you can choose whatever name you want with lowercase letters and no strange symbols` :laughing: 
Also snuck in: remove setting the Scala binary version when creating the coursier api which is no longer needed since https://github.com/scalameta/metals/pull/4390 (mentioned in previous PR).

Ivy Completions Dash Fix

---

metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
tests/unit/src/test/scala/tests/DebugProtocolSuite.scala

Previously, only the test suite name was sent via BSP. Now we also add env variables and jvmopts.
Fixes https://github.com/scalameta/metals/issues/4374

bugfix: Allow to add jvmopts and env variables when running tests

---

mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbSymbols.scala
tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala

It was affecting woskpace completions: type symbol were converted into a term one and then filtered out.

fix: Scala3 properly inverse semanticdb type symbol

---

.mergify.yml

This change has been made by @tanishiking from https://mergify.com config editor.
> The repository configuration doesn't allow merge commits. The merge method configured in Mergify configuration must be allowed in the repository configuration settings.
https://github.com/scalameta/metals/pull/4400/checks?check_run_id=8431753248
I guess we need to use squash instead, sorry for messing up PRs 😅

ci(Mergify): configuration update / use squash

---

tests/slow/src/test/scala/tests/gradle/GradleLspSuite.scala
tests/slow/src/test/scala/tests/maven/MavenLspSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala

It seems that we might have a race condition, which causes the build import not to run the second time if it hasn't yet finished

bugfix Try to fix flaky import tests

---

mtags/src/main/scala-2/scala/meta/internal/pc/Keywords.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/KeywordsCompletions.scala
mtags/src/main/scala/scala/meta/internal/pc/Keyword.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala

https://github.com/scalameta/metals-feature-requests/issues/68
related: https://github.com/scalameta/metals/pull/4193
This commit implements `extends` keyword completion.
The `extends` keyword will be completed only if the leading tokens are
like
`(class|trait|object) <identifier> ext@@`
We check the scalameta tokens because we get nothing from the AST
when we type `class Foo ext@@` which is an incomplete class declaration
statement.
---
~we can implement for Scala3 in the same way.~ Scala3 is also supported

feat: extends keyword completion

---

.mergify.yml

This change has been made by @tanishiking from https://mergify.com config editor.
mergify was double checking
- listed checks passed
- the number of check-success=21
but, https://github.com/scalameta/metals/pull/4424 didn't merge because now we have one more additional check (by mergify), and the `#check-success>=22` is required.
It looks like `#check-success=21` seems fragile. Therefore this PR removes the condition, it should be fine as we still have conditions for required checks.
**ref**
> There is no such thing as "every status check" in GitHub.
> ...
> Those three facts make it mandatory to write explicitly the checks that are expected for your condition to be valid. Therefore you must list explicitly every status check that is expected, …

ci(Mergify): Don't check the number of check-success

---

build.sbt
mtags/src/main/scala-2.11/scala/meta/internal/pc/Compat.scala
mtags/src/main/scala-2.12/scala/meta/internal/pc/Compat.scala
mtags/src/main/scala-2.13.9/meta/internal/jdk/CollectionConverters.scala
mtags/src/main/scala-2.13.9/meta/internal/pc/Compat.scala
mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
project/V.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/mtest/src/main/scala/tests/Compat.scala
tests/unit/src/test/resources/definition/example/Scalalib.scala
tests/unit/src/test/resources/semanticdb/example/Scalalib.scala
tests/unit/src/test/scala/tests/DiagnosticsLspSuite.scala

Due to https://github.com/scala/scala/pull/9754 it was required to add additional compat method to filter out non relevant type completions.

Scala 2.13.9

---

metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

There were two remaining cases where cancllables were never removed from a queue:
- in shell runner
- debug sessions
Now, they are properly removed after finishing.
Follow up to https://github.com/scalameta/metals/pull/4421

bugfix: Remove all cancallables on finish

---

metals/src/main/scala/scala/meta/internal/metals/BatchedFunction.scala
metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
tests/unit/src/test/scala/tests/BatchedFunctionSuite.scala
tests/unit/src/test/scala/tests/CancelCompileLspSuite.scala

Previously, cancel would not be propagated through all the future trnasformations. Now, instead we have a separate queue of ongoing requests, which can be cancelled explicitely all at once. This approach is a bit more simple and doesn't require figuring out all the possible Future chains coming from compile.
Fix https://github.com/scalameta/metals/issues/3801 
Fix https://github.com/scalameta/metals/issues/3754

bugfix: Properly cancel all current compilations

---

mtags/src/main/scala/scala/meta/internal/pc/ScriptFirstImportPosition.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala

Hi!  This PR changes auto imports with Ammonite scripts so that if a script does not already contain an import, the first import is added after any [Ammonite headers](https://scalameta.org/metals/docs/troubleshooting/faq#how-do-i-use-scala-2xx-for-my-script), since these comments need to appear at the top of the file.
The implementation is otherwise similar to how `// using` comments are skipped in scala cli scripts.  Thanks!

Auto-Import After Ammonite Headers

---

mtags/src/main/scala-2.11/scala/meta/internal/pc/Compat.scala
mtags/src/main/scala-2.12/scala/meta/internal/pc/Compat.scala
mtags/src/main/scala-2.13.9/meta/internal/pc/Compat.scala
mtags/src/main/scala-2.13/scala/meta/internal/pc/Compat.scala
mtags/src/main/scala-2/scala/meta/internal/pc/Signatures.scala
tests/unit/src/test/scala/tests/codeactions/ImplementAbstractMembersLspSuite.scala

Previously, we would print constant types as `String("mode")`. Now, we print only the underlying `"mode"`.
Fixes https://github.com/scalameta/metals/issues/4411

bufix: Properly write constant types in signatures

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/AmmoniteCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
tests/slow/src/test/scala/tests/feature/WorksheetCrossLspSuite.scala
tests/unit/src/test/scala/tests/worksheets/WorksheetLspSuite.scala

Futher refactor is being done in https://github.com/scalameta/metals/pull/4417 so I will hold off for now, but the IvyCompletions could be taken out of AmmoniteCompletions trait.

feature: Add Ammonite completions to worksheets

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala

feature request https://github.com/scalameta/metals-feature-requests/issues/302
This adds exhaustive match completions for partial functions.
User can find this completion both by typing
```scala
List(Option(1)).map { match@@}
```
and 
```scala
List(Option(1)).map { case@@}
```
with result 
```scala
List(Option(1)).map { 
case None =>
case Some(value)
}
```

Offer exhaustive completions for map and other methods

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionSuffix.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/InterpolatorCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala

related to https://github.com/scalameta/metals/issues/4358
This commit refactors `findSuffix` to return `CompletionSuffix` that has information about what kind of completion suffix will be added: does compeltion suffix contains `()`, `[]`, or `{}`? where are we gonna move the cursor to?
This refactoring is required for improving the completion (with suffix)'s label.
see: https://github.com/scalameta/metals/pull/4369

refactor: [scala3] findSuffix to return a data structure so we can tell what kinds of suffix will be added to the edit.

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcDocumentHighlightProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcDocumentHighlightProvider.scala
tests/cross/src/test/scala/tests/highlight/SyntheticsDocumentHighlightSuite.scala

Previously, document highlight in for comprehensions would not highlight both the definition and the usages in yield. This was caused by the fact that these two are really just separate symbols in separate anonymous functions. Now, we try to relate the two owner functions based on their point position, which seems to work correctly.
It's a bit different in case of Scala 3, since there seem to be more trees with the particular symbol generated, but still path will point us to different symbol than the one being used.

bugfix: Fix document highlight in for comprehensions

---

sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala
sbt-metals/src/sbt-test/sbt-metals/semanticdb/build.sbt

https://github.com/scalameta/metals/issues/4449
Previously, requiresSemanticdb will be false if the given scala version is not yet listed in the `supportedScalaVersion` which comes from the BuildInfo of Metals.
This means, we have to wait for the next release (or using the snapshot build) for downloading the semanticdb-plugin for the latest scala compiler.
(For example, in order to use 2.13.9, we had to wait for the build that supports scalac 2.13.9).
With this change, Metals try to download the semanticdb-plugin anyway, and users won't need to wait for the next build for using the latest scala compiler.

fix: Try to download semanticdb even if it might not be supported

---

metals/src/main/scala/scala/meta/internal/metals/doctor/ProblemResolver.scala

This usually shows up for people who are unable to update it and running test is possible for them, so this is not critical.
It will still show up properly in recommendation in the doctor.
Prompted by reports of people unable to update while being confused by the error.

feature: Don't show misconfigured test message

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

related https://github.com/scalameta/metals/issues/2376
Previously, Metals says
"code navigation does not work for the file ... because the SemanticbDB file ... doesn't exist. There can be many reasons for this error."
When users try to go to definition and the target file doesn't have SemanticDB. This log message is a bit misleading.
- code navigation should work even if there's no semanticdb file
- because Metals fall back to presentation-compiler-based navigation
- https://github.com/scalameta/metals/blob/f48987e43d3b36c530da396ba94290d25e3332f9/metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala#L96-L99
- if the code navigation actually doesn't work, it's PCDefinitionProvider's issue.
- SemanticDB not found is also an issue though
As a result, even if it might be …

refactor: Don't log "navigation doesn't work" if fallback to compiler based navigation

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
tests/unit/src/main/scala/tests/BaseScalaCliSuite.scala

Fixes #4447 - use correct semanticdb root for bsp connection.
Also don't import a full directory if it conflicts with the sourceItems from the main build tool

fix: bunch of fixes for ScalaCli scripts import

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala

The workaround was needed until 2.12.8 and 2.13.0, which are no longer supported.
I was waiting on this for 3 years :sweat_smile:

chore: Remove old workaround

---

metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

Previously, when renaming variables we would check if the existing name would correspond to symbol name to make sure that we are not renaming soemthing by mistake. Now, we also take into account that the symbol might have the additional `_=`.
Fixes https://github.com/scalameta/metals/issues/4467

bugfix: Fix issues when renaming variables

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala

Previously, we would import all cases, which is not the usual way of dealing with enums. Now, we always specify the owner enum.

improvement: Always specify enum owner

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala

Previously exhaustive match completion on enum created multiple imports of enum owner
```scala
package withenum {
enum Color(rank: Int):
case Red extends Color(1)
case Blue extends Color(2)
case Green extends Color(3)
}
package example
object Main {
val x: withenum.Color = ???
x match@@
}
```
Resulted in 
```scala
import withenum.Color
import withenum.Color
import withenum.Color
package withenum {
enum Color(rank: Int):
case Red extends Color(1)
case Blue extends Color(2)
case Green extends Color(3)
}
package example
object Main {
val x: withenum.Color = ???
x match@@
}
```
Now, we do `distinct` on additional edits so duplicates will be removed

Fix: Remove multiple enum owner imports

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala

Continuation of https://github.com/scalameta/metals/pull/4475
Now we import enum owner also in single case completions.
Also, apply the same import logic to java enums

Import enum owner in case comp and in java enum match

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/InterpolatorCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala

Visual Studio code seems to have issue filtering text in string interpolations, which doesn't seem to be a problem in any other editors.

bugfix: Properly import extension methods in string interpolation

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala

Previously, if there was a parsing issue reported by the default Scala version it would not be cleaned out after importing the script. Now, we reparse the file with the proper dialect after importing.
Fixes https://github.com/scalameta/metals/issues/4482

bugfix: Clean diagnostics after importing a script

---

metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala
mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
tests/unit/src/main/scala/tests/BaseScalaCliSuite.scala

Previously, if a user opened metals and then run .bsp generation they would need to restart metals or manually connect to build server. Now, we start watching for .bsp when no build tool exists and when it shows up we connect to the build server defined there.

feature: Connect automatically when `.bsp` folder shows up

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala

Previously, if we used `inString` with a range that spans multiple lines, we would get a wrong substring. Now, we correctly handle end offset.
Fixes https://github.com/scalameta/metals/issues/4487
Unfortunately, I don't have a test case for that.

bugfix: Properly extract multiline ranges

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ScalaCliCompletions.scala
mtags/src/main/scala/scala/meta/internal/mtags/CoursierComplete.scala
tests/cross/src/test/scala/tests/pc/CompletionScalaCliSuite.scala

Now in `//> using lib "io.circe:@@"` scala completions (with adding second `:`) will show before java completions.
Also, fixes some issues e.g. showing completions after closing `"`

Show Scala completions first in ScalaCli using directives

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala

Previously, we would match on completion value in multiple places, which makes it hard to modify a behaviour for single type of completion. Now, I moved most logic into specific CompletionValue.
There might be some additional things to refactor, but we can do it later on.
Additionally, this fixes the added type in CaseKeyword completions, which was especially visible in the added test case.

refactor: Move calculating description, kind and label to CompletionValue

---

mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala/scala/meta/internal/mtags/KeywordWrapper.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionBacktickSuite.scala

Hello 🖖🏻 
This PR resolves https://github.com/scalameta/metals/issues/4348
I cannot think of any cases where soft keywords should be backticked, since these words are allowed to be identifiers as well.
Therefore removing soft keywords "inline" and "extension" from the list of keywords seemed to be the right thing to do
Please, let me know if that's not an appropriate solution

fix: soft-keyword-matching autoimports in Scala 3

---

tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/MacroCompletionSuite.scala

- make CompletionTest always work in future versions of Scala 2
- ignore MacroCompletionSuite in nightlies

chore: Fix issues within the community suite for Scala 2

---

metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala

Hi, this PR updates a few parts of the user config options documentation:
- Say paths may either be relative or absolute instead of just absolute (it was a bit confusing before since all the examples given for paths were relative - AFAICS looking at the source, relative paths can be used too)
- Fix out of date link in the remote language server option doc
- Specify all valid values for test user interface option and point to further documentation for it.
I saw some of the user config titles start with "Should" I can change this in this PR also if you want?  Otherwise, I hope this is helpful :slightly_smiling_face:

Update User Config Options Doc

---

metals/src/main/scala/scala/meta/internal/metals/callHierarchy/OutgoingCallsFinder.scala
tests/unit/src/test/scala/tests/CallHierarchyLspSuite.scala

This will fix #4489 by simply don't search for outgoing calls in the case of declaration.

Fix show declaration type on outgoing calls request

---

mtags/src/main/scala-3/scala/meta/internal/pc/CompilerSearchVisitor.scala

It seems that it can sometimes throw an exception, which will make no completions show up for example in some scope completions in metals codebase.
Related to https://github.com/lampepfl/dotty/issues/16175

bugfix: Wrap `isPublic` in try

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-3.1/scala/meta/internal/pc/MetalsSealedDesc.scala
mtags/src/main/scala-3.2/scala/meta/internal/pc/MetalsSealedDesc.scala
tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala

This only shows up if we don't have a specific implementing class within a library and only local variable exists.
Related to https://github.com/scala/scala/commit/14fa7bef120cbb996d042daba6095530167c49ed

bugfix: Filter out <local child> symbol for exhaustive matches

---

.scala-steward.conf
build.sbt

It seems that undertow is now compiled with JDK 11, so we need to ignore it until we drop support for JDK 8.

bugfix: Revert undertow and ignore

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala

fixes https://github.com/scalameta/metals/issues/4515
Now we check if the next `case` will be in different line than the previous one

fix: incorrect case completion position

---

project/V.scala
tests/unit/src/main/scala/bill/Bill.scala

In bsp4j `2.1.0-M2` was added function `buildTargetOutputPaths`  to exclude compilation artifacts from searchable files, more info you can find [here](https://github.com/build-server-protocol/build-server-protocol/issues/205).
By default, `metals` skip `output path` for build tools such as `sbt`, so if I'm right, `metals` don't have to add support for this function.

Update bsp4j to 2.1.0-M3

---

metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala

Previously, worksheets would not work for backpublished versions. Now they should work correctly in their case.
The check is not needed since most binary versions should be supported until there is a breaking change.

bugfix: Remove to check for Scala versions in worksheets

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcDocumentHighlightProvider.scala
tests/cross/src/test/scala/tests/highlight/Scala3DocumentHighlightSuite.scala

I will see if we can change the DeepFolder upstream

bugfix: Highlight transparent inline usages correctly

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/AmmoniteCompletions.scala
mtags/src/main/scala/scala/meta/internal/mtags/CoursierComplete.scala
tests/slow/src/test/scala/tests/feature/AmmoniteSuite.scala

Hi, I thought it would be more helpful if more up to date versions are shown first for version completions:
So this PR reverses the sort when the completion items are versions.
Thanks!

Sort versions in reverse for coursier completions

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaMtags.scala
tests/slow/src/test/scala/tests/feature/DefinitionCrossLspSuite.scala
tests/unit/src/test/resources/definition-scala3/example/Extension.scala
tests/unit/src/test/resources/mtags-scala3/example/Extension.scala

Previously, when indexing Scala files we would not add the package part for toplevel methods, which would make it impossible to find them. Even without package you need `_empty_/`. Now, we propely append them.
Fixes https://github.com/scalameta/metals/issues/4531

bugfix: [Scala 3] Properly prepend package to toplevel methods

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala

Previously, in both Scala 2 and Scala 3 in code like 
```scala
sealed trait TestA
case object Foo extends TestA
case object Bar extends TestA
sealed trait TestB
case object Baz extends TestB
case object Goo extends TestB
object Main {
def testExhaustive[T <: TestA with TestB](test: T): Boolean =
test ma@@
```
We would get  
```scala
test match {
case Foo => 
case Bar =>
case Baz =>
case Goo =>
}
```
Which is incorrect, because these objects don't have type `TestA with TestB`.
Now, we show only only classes extending all "parent" types e.g.
```scala
case object Both extends TestA with TestB
```

Fix `exhaustive match` completion for type `TypeA with TypeB`

---

metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/ScalacDiagnostic.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ActionableDiagnostic.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionProvider.scala
tests/unit/src/main/scala/tests/BaseScalaCliSuite.scala
tests/unit/src/main/scala/tests/codeactions/BaseCodeActionLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ActionableDiagnosticsSuite.scala

This PR adds support for actionable diagnostic from `scala-cli`. These are diagnostics that contain information that allows users to fix some configs/directives by `Quick Fix` actions in metals.
For now, in `scala-cli` there is only implemented actionable diagnostics for updating lib in using directives, and it works in this way with metals:
https://user-images.githubusercontent.com/46607934/186489738-71ed74df-2ed0-4ce3-8466-b21d4674c2c0.mov
I added `didSave` flag to `check` method, because when actionable diagnostics were applied in unit tests and saved content to the file, the `scala-cli` reload bsp server and at the same time metals expect to get `Compile Result` from server but fail, because bsp server is down. I attach error logs:
```
2022.08.23 14:48:03 INFO  Disconnecting from …
```

Scala cli actionable diagnostic

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala
mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
tests/unit/src/main/scala/tests/BaseScalaCliSuite.scala

It seems that there was a race condition between when `.bsp` directory was created and the actual json creation.
Now we wait until the json file is created

bugfix: Try to fix flaky ScalaCLI test

---

metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala
mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala

A `ZipException` can happen if the jar file is an empty file.

Fix #4532: catch ZipException when opening jar files

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/AmmoniteFileCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/AmmoniteIvyCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/AmmoniteIvyCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/ScalaCliCompletions.scala
project/V.scala
tests/slow/src/test/scala/tests/feature/AmmoniteSuite.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
tests/unit/src/test/scala/tests/worksheets/WorksheetLspSuite.scala

Adds ammonite ivy imports completions for Scala 3.
Also refactors these completions for Scala 2 to use `CoursierComplete`.
Fixes https://github.com/scalameta/metals/issues/4551

Add Ammonite Ivy completions for Scala 3

---

mtags/src/main/scala-2/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImportsProvider.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala

Previously, the behaviour for auto-import action wasn't specified for
`import <<$SYMBOL>>` case.
Now in imports the required symbol using specifying full name in case if it's missing in scope as we do that in completions

fix: add special case for autoimport inside Import tree

---

metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala

This relates to the grand plan of
https://github.com/lampepfl/dotty/issues/14904 and recently forwarding
the `diagnosticCode` has been merged in
https://github.com/lampepfl/dotty/pull/15565 and also backported so it
should show up in the 3.2.x series. While this pr isn't super exciting,
it's just making sure we capture the code and forward it, this should
unlock _much_ better ways to determine what code actions are available
for a given diagnostic. Meaning we don't have to do lovely things like
regex on the diagnostic message for Scala 3 diagnostics.
NOTE: that this does need some more changes in the build servers before
this is usable. So we can wait for those to be merged in if you'd like.
Now if you look at the trace file for a diagnostic you'll see the
addition of the code:
``` …
```

feat: capture and forward `diagnosticCode`

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala
tests/unit/src/main/scala/tests/BaseCodeLensLspSuite.scala
tests/unit/src/test/scala/tests/CodeLensLspSuite.scala

Hi, this PR makes individual test cases runnable by exposing them as lenses.  This is (mainly) done by making `TestSuitesProvider` implement `CodeLens`, related is https://github.com/scalameta/metals-feature-requests/issues/216.
If a user has their `testUserInterface` configuration option set to `code lenses` then these new lenses should show up on test cases, otherwise if the option is set to `test explorer` then the existing behaviour remains, 
Thanks!

Expose Test Cases as Separate Lenses

---

docs/editors/overview.md
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala-2/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcDefinitionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcDefinitionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/main/scala/tests/pc/BasePcDefinitionSuite.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala
tests/cross/src/test/scala/tests/pc/PcDefinitionSuite.scala
tests/cross/src/test/scala/tests/typedef/TypeDefinitionSuite.scala

This approach uses is a slight modification of definition provider, where we try to additionally find the type symbol of the definition symbol. It seems to work ok and doesn't require too many changes.
In some cases it might not be clear where to go for the type definition, but I think most cases covered by tests make sense. For example the type definition for type is the same as definition.
There is a small bug for named parameters in Scala 2, but that is unrelated to this PR and can be fixed later.
Fixes https://github.com/scalameta/metals/issues/4510

feature: Add support for type definition

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala

Hi, this PR picks up on an oversight in https://github.com/scalameta/metals/pull/4569 (apologies), which resulted in test case code lenses showing in the event that `testUserInterface` was set to `test explorer`.

Fix Test Case Code Lenses Appearing with Test Explorer

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
mtags/src/main/scala/scala/meta/internal/pc/CompletionItemData.scala

Moving some of the logic from CompletionProvider to CompletionValue allows us to simplify the code a bit and have a single place dedicated to calculating all the elements of completions.
I want to further change that, but I don't want to do that allow at once.

refactor: Move some logic from CompletionProvider 

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

Previously, configuration items could return a null and we would invoke getAsJsonObject() on it. Now, we first check if it's a null.
Fixes https://github.com/scalameta/metals/issues/4577

bugfix: Handle null being sent in the user configuration

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala

Mosty moving cases to `OverrideCompletions` to clean up in `Completions`. Also moves adding auto imports inside `OverrideCompletions`

Refactor override completions, move auto import generator

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala

LSP spec mentions that `workspace/configuration` can return array containing null if client can’t provide a configuration setting.
Fixes scalameta#4577
The object in question has type JsonNull instead of Null, so we need to check it explicitly.

bugfix: Check if client returned null in configuration

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala

Previously, we would only start Ammonite when the file was opened. If the start failed user would need to reopen the file. Now, if the file changed and no ammonite session was started we will attempt to run it again.
Fixes https://github.com/scalameta/metals/issues/4581

bugfix: Retry starting Ammonite when file changed

---

tests/cross/src/test/scala/tests/hover/HoverDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

We no longer run cross tests on JDK 8 so it's safe and clearer to ignore failing tests explicitely
Fixes https://github.com/scalameta/metals/issues/4585

chore: Ignore failing tests on Java 8

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala

Previously we would be using .name on package object and we would get `package`, which is not the correct name. Now, we look for the actual name of the package that this package object is accompanying.

bugfix: Fix wrong namePos on package objects

---

mtags/src/main/scala-2/scala/meta/internal/pc/Keywords.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/KeywordsCompletions.scala
mtags/src/main/scala/scala/meta/internal/pc/Keyword.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala

Maybe it would better to use something like `additionalFilter` instead of `reveresedTokensPredicate` for `extension`, but since there are only two keywords using that, it should be ok
fixes https://github.com/scalameta/metals/issues/4419

fix: don't show incorrect `extension` keyword completion

---

metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala

There is an official one now supported in the com-lihaoyi org. I think we
should switch out ours for this one. Then we can actually just archive
the one we have with a message to use the com-lihaoyi instead. Less
repos to maintain ha.

chore: swap scalameta Mill g8 for com-lihaoyi one

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/InterpolatorCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

fixes https://github.com/scalameta/metals/issues/4066
Previously, when choosing apply method completion we would import incorrect symbol, now we import companion object.

fix: correctly import companion object for apply method

---

docs/editors/emacs.md

I think the suggested default configuration for Emacs should include `(setq lsp-keep-workspace-alive nil)` because that's the behavior I would expect by default from LSP: shutting down the metals server when I close all buffers of a project. For me, without anything special in my Emacs configuration, the variable was set to true by default.

Add lsp-keep-workspace-alive to emacs config

---

.github/workflows/mtags-auto-release.yml

This is needed so that the new nightlies don't fail.

chore: Update nightly release branch to use Scala 3.3.x fixes

---

mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala

fixes https://github.com/scalameta/metals/issues/3597
connected to https://github.com/scalameta/metals-vscode/pull/1216
Edit: The tests are ok, so this change shouldn't break anything

add showing semanticdb for sbt files and worksheets

---

metals/src/main/scala/scala/meta/internal/metals/MtagsResolver.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/DoctorExplanation.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/DoctorResults.scala
tests/unit/src/main/scala/tests/TestMtagsResolver.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

Previously, we would report issues with Java support and semanticdb, which isn't true, since semanticdb is generated and Java is not supported. Now, we correctly show that in the doctor.
Fixes https://github.com/scalameta/metals/issues/3305

bugfix: Correctly display statuses for Ammonite scripts in Doctor

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala

Partially resolves https://github.com/scalameta/metals/issues/3928
I've noticed that `sym.info` works fine in `MetalsPrinter.completionSymbol`, so I used as a fallback if type is erroneous

fix: more accurate signature on error in override comp

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala

Partially solves https://github.com/scalameta/metals/issues/3928
Previously 
```scala
trait A {
def close: Unit
}
trait B extends A{
override def close : Unit = {}
}
class C extends B{
close@@
}
```
would result in 
```scala
override override def close: Unit = ???
```
Also fixes not showing completions on not completed method names like in
```scala
class C extends B{
clos@@
}
```

fix: complete already overridden symbols in scala 3

---

metals-docs/src/main/scala/docs/BootstrapModifier.scala

This is no longer used and doesn't need to be listed
in the bootstrap instructions

docs: remove old resolver in docs

---

mtags/src/main/scala-3.0/scala/meta/internal/pc/printer/RefinedDotcPrinter.scala
mtags/src/main/scala-3.1/scala/meta/internal/pc/printer/RefinedDotcPrinter.scala
mtags/src/main/scala-3.2/scala/meta/internal/pc/printer/RefinedDotcPrinter.scala
mtags/src/main/scala-3.3/scala/meta/internal/pc/printer/RefinedDotcPrinter.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/DotcPrinter.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala

Previously, toTextRefinement would return `Closed` type and now it returns `Text`, which is causing the compilation issues.
Now, since the printer prints the types for refinments correctly, we can avoid overriding the method altogether.
The type is printer a bit differently, but it does compile, so let's keep it in line with the compiler.

bugfix: Fix compliation issues with 3.3.x

---

.github/ISSUE_TEMPLATE/bug_report.yml

It's been archived for a while now so we can remove this.

chore(ci): remove coc-metals from issue template

---

metals/src/main/resources/millw
metals/src/main/resources/millw.bat
tests/slow/src/test/scala/tests/mill/MillServerSuite.scala

When I opened https://github.com/com-lihaoyi/mill/issues/2123 it made me wonder why we didn't hit on this in our tests, but then I realized we were actually never testing the initialization with Mill server. This adds some more tests to ensure we're not only testing the generation of the BSP config file, but also connection to the build server.
~**NOTE** Marking this as a draft for now because it's expected that 0.10.9 (which is our default right now) will fail. There should be a new release of millw soon with a fix, which should fix this. When that happens I'll add another commit to this adding in the new millw and showing that the tests all pass.~

refactor: ensure we're testing the connection with Mill

---

metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala

This is a follow-up to https://github.com/scalameta/metals/pull/4649 since it didn't actually fix the issue since `isScalaCli` was looking for the connection name to be `ScalaCli`, however it's actually `scala-cli` when you look at the value of `name` when that check is done. You can also see this in the `build/initialize`.
```
[Trace - 11:38:07 am] Received response 'build/initialize - (1)' in 615ms
Result: {
"displayName": "scala-cli",
"version": "0.1.17",
...
```
CC @lwronski

fix: ensure name for scala-cli is correct

---

mtags/src/main/scala-3/scala/meta/internal/pc/ExtractMethodProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/main/scala/tests/BaseExtractMethodSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala
tests/cross/src/test/scala/tests/pc/ExtractMethodSuite.scala
tests/cross/src/test/scala/tests/pc/NoIndentSuite.scala

fixes https://github.com/scalameta/metals/issues/4624

fix: match completion with -no-indent option

---

metals/src/main/scala/scala/meta/internal/metals/doctor/DoctorExplanation.scala

Super small change that I'm currently hitting on in Neovim. When
consuming the json output for the doctor there used to not be any
newlines in the output. Once we added the Java problems we have one
value that has multiple lines. Not all clients will be able to handle
new lines here, so this small change instead just splits on the newline
and gives them back as two items in the array. Again, this only happens
when using the json output.

refactor: avoid newlines in json doctor output

---

docs/integrations/new-editor.md
metals-docs/src/main/scala/docs/BootstrapModifier.scala

Previously, it was pointing to the latest snapshot version, which meant that it was not possible to properly boostrap without adding a repo. Now, we point to latest release and the commands work.
Related to https://github.com/scalameta/metals/discussions/4670

docs: Point bootstrap commands to latest release version

---

metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala

Previously, we would only use Input.Ammonite for scripts, but not `build.sc`, which meant we were parsing Mill build files wrong. Now, we use Input.Ammonite for both.
Fixes https://github.com/scalameta/metals/issues/4682

bugfix: Make multistage Mill scripts work

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ScalaCliCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/ScalaCliCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionScalaCliSuite.scala

Previously, we were asuming that the file we are operating on will be empty, but that was not true (or it changed) and it's actually a converted script file. Now, we properly handle it when the extension is .sc.scala.

bugfix: Fix coursier completions in ScalaCli scripts

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/AmmoniteIvyCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
tests/slow/src/test/scala/tests/feature/AmmoniteSuite.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala

Hi! This PR improves ivy completions in some circumstances by returning completions on all parts of the group id without backtics being present, probably best explained by a snippet:
https://user-images.githubusercontent.com/17688577/201718881-1d251a70-356d-4f78-a637-11bf4b78d3ce.mp4
Previously, you would get no completion after `import $ivy.org.|`

Improve Behaviour of Initial ivy Completions (scala 2)

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala
tests/unit/src/main/scala/tests/BaseRenameFilesLspSuite.scala
tests/unit/src/main/scala/tests/TestRanges.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/NewFileLspSuite.scala
tests/unit/src/test/scala/tests/RenameFilesLspSuite.scala

This PR implements https://github.com/scalameta/metals/issues/4664 by adding support for [workspace/willRenameFiles](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_willRenameFiles) LSP request. 
Feature is developed with an eye on VS Code as it has support for `willRenameFiles` request. The request is sent before files/directories are renamed/drag-and-dropped. As a response to this intent a language server proposes corresponding file edits.
Semantics of the feature is reflected in the test suite.
Implementation tries to provide as much refactorings as possible: 
- single/multi-package statements
- package objects
- various kinds of imports: single/multiple/wildcard/rename
- new imports when definitions are moved out of scope, etc. …

feat: Refactor package definition when moving files between packages

---

metals/src/main/scala/scala/meta/internal/metals/AdjustLspData.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/metals/callHierarchy/CallHierarchyItemBuilder.scala
mtags-interfaces/src/main/java/scala/meta/pc/HoverSignature.java
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala-2/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala/scala/meta/internal/pc/HoverMarkup.scala
mtags/src/main/scala/scala/meta/internal/pc/ScalaHover.scala
tests/cross/src/main/scala/tests/pc/BaseHoverSuite.scala
tests/mtest/src/main/scala/tests/TestHovers.scala

Relates to: https://github.com/scalameta/metals/issues/4473
Change so `PresentationCompiler` returns a custom instance of Hover (instead of `org.eclipse.lsp4j.Hover`). Now the fields are accessible instead of being clumped into a markdown.

`PresentationCompiler` returns custom `Hover`

---

metals/src/main/scala/scala/meta/internal/metals/AdjustLspData.scala

I haven't noticed that it caused tests to fail. We should always adjust position of anything coming from the compiler as it might been wrapped with additional code such as in case of sbt with additional imports.

bugfix: Fix adjusting range for hovers

---

metals/src/main/scala/scala/meta/internal/bsp/BspSession.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala

Previously, we would not refresh any build targets after reloading sbt, which meant no new libraries or scala versions would available. Now, we properly reindex the new build configuration.
Fixes https://github.com/scalameta/metals/issues/2328

bugfix: Properly reindex build after reloading sbt

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcRenameProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcRenameProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/main/scala/tests/BasePcRenameSuite.scala
tests/cross/src/test/scala/tests/pc/PcPrepareRenameSuite.scala
tests/cross/src/test/scala/tests/pc/PcRenameSuite.scala
tests/unit/src/test/scala/tests/RenameLspSuite.scala

Connected to https://github.com/scalameta/metals/issues/4644
Previously (since https://github.com/scalameta/metals/pull/4542), we were using presentation compiler for renaming local symbols, but the project still had to compile, because both `prepare rename` and `rename` were using semantic db first. Now, in both we start by checking if the symbol can be renamed via presentation compiler (is defined inside a method or in a worksheet, maybe there are also other cases?) and use semantic db as a fallback.

Improve `rename` for local symbols and worksheets

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/NamedArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Previously, we wouldn't show named argument completions after (\n due to CURSOR being added and not stripped. Now, we properly show those completions.
I additionally had to change the sorting a bit to make NamedArguments show first, which is the same logic as with Scala 2. Together with making those completions symbolic it seems we got almost the same sorting as with Scala 2.
Issue reported by @prolativ

bugfix: Show completions in parens after newline
