scalameta/metals

vscode-extension/src/extension.ts
After #22 server subproject is renamed to metaserver and published with this name. So I changed it in the client code as well.
=> Updated server artifact name

metaserver/src/main/scala/scala/meta/languageserver/Compiler.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/SymbolIndexer.scala
Just an experiment for now. Some things are better (e.g. generics are correctly inferred), but some just got weird, and that's probably me knowing nothing about the compiler's api.
=> Use presentation compiler for type at point information

metaserver/src/main/scala/scala/meta/languageserver/Main.scala
Having a log file the in root of every project is not very Git-friendly 😄 (sure I added it to the global gitignore, but still). So I moved it to `target/`. This is also convenient because you can reset logs when running `clean` in sbt.
I also changed stderr log file, but probably you want to have them together.  Also, what does `pc` in the name stand for?
=> Moved server logs to target/

metaserver/src/main/scala/scala/meta/languageserver/Compiler.scala
Apparently `toLongString` handles a bunch of edge cases on top of `.widen`. Thanks @olafurpg for the tip.
https://github.com/scala/scala/blob/07d61ecf134dbba143531f5a1bd3c1289c437296/src/reflect/scala/reflect/internal/Types.scala#L953-L964
=> Use .toLongString instead of .widen.toString in typeOfTree

metaserver/src/main/scala/scala/meta/languageserver/ScalametaEnrichments.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/SymbolIndexer.scala
WIP fix for #33.
Here's how it looks with 379a735:
The problem is, it shows only one level of nesting, which is wrong. I compared the responses with other servers (TypeScript and Python) and didn't find any difference: `containerName` just matches the corresponding symbol's `name` field, nothing special.
=> Fixing symbols hierarchy

metaserver/src/main/scala/scala/meta/languageserver/CompilerConfig.scala
=> Use java.home Java property for JDK source detection

.travis.yml, build.sbt
Fixing what didn't work in #46:
- [missing](https://travis-ci.org/scalameta/language-server/jobs/306019884#L967) `scmInfo` key
- `deploy` block should be triggered only in one CI job (otherwise it'll try to deploy second time after scalafmt check and fail)
=> Fix sbt-release-early CI deploy

CONTRIBUTING.md, build.sbt, metaserver/src/main/scala/scala/meta/languageserver/Compiler.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/storage/Bytes.scala, metaserver/src/main/scala/scala/meta/languageserver/storage/LevelDBMap.scala, metaserver/src/test/scala/tests/search/SymbolIndexTest.scala, metaserver/src/test/scala/tests/storage/LevelDBMapTest.scala, project/plugins.sbt
This PR makes the server start much faster after the first run. There are still some issues with the implementation in this PR that I plan to address in the future (to avoid making this PR huge!). This PR is already a big enough improvement over master.
One big question is where to store the cache. Should we share cache across workspaces or have one cache per workspace. In this PR I use a global cache since I think that makes sense in the long run. However, it seems leveldb doesn't permit two concurrent connections (unless I'm missing some options to allow it), which makes it problematic to share the cache globally. I'm interested to hear what you think.
=> Use leveldb to cache computation of ctags indices

build.sbt, languageserver/src/main/scala/langserver/core/LanguageServer.scala, languageserver/src/main/scala/langserver/messages/Commands.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala
Fixes #30 
The problem is in the scala-json-rpc way of handling commands (requests) and notifications. It doesn't allow them to have an empty or absent `params` key:
https://github.com/dhpcs/scala-json-rpc/blob/c25cda4b6a39441bbe4ce25f57ab88e3db5ef635/scala-json-rpc/src/main/scala/com/dhpcs/jsonrpc/MessageCompanions.scala#L66-L71
While the [LSP spec for `shutdown`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#shutdown-request) says explicitly:
> Request:
> * method: 'shutdown'
> * params: void
Same about `shutdown` response and `exit` notification. These are the only messages in LSP that don't have parameters, so I'm adding a special `read`override to handle these messages.
=> Fixing shutdown routine

languageserver/src/main/scala/langserver/core/Connection.scala, languageserver/src/main/scala/langserver/core/LanguageServer.scala, languageserver/src/main/scala/langserver/core/MessageReader.scala, languageserver/src/main/scala/langserver/core/MessageWriter.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala
I removed message headers logging and changed a bit how incoming/outcoming messages are logged (from reader/writer):
```
01:50:25.578 INFO  s.m.l.Compiler - Loading new compiler from config CompilerConfig(sources={+1}, scalacOptions=-Yrangepos -P:semanticdb:sourceroot:/Users/laughedelic/dev/laughedelic/language-server/test-workspace -Xplugin:/Users/laughedelic/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.3/2.1.2/semanticdb-scalac_2.12.3-2.1.2.jar, dependencyClasspath={+2}, classDirectory=/Users/laughedelic/dev/laughedelic/language-server/test-workspace/a/target/scala-2.12/test-classes, sourceJars={+13})
01:50:26.134 DEBUG l.core.MessageReader - <--  {"jsonrpc":"2.0","id":3,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///Users/l …
```
=> Improve logging

metaserver/src/main/scala/scala/meta/languageserver/Compiler.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/compiler/HoverProvider.scala, metaserver/src/test/scala/tests/hover/HoverTest.scala
I discovered that #38 wasn't such a good idea. For some cases the "long string" isn't what we want on hover, e.g. for
```scala
val x = List(1, 2, 3)
<<x>>.mkString
```
the result is `a.x.type (with underlying type List[Int])`, whereas we would just like `List[Int]`.
In this PR I've added a few tests (built on the infrastructure of #51) that also highlight the failing cases.
I intend to fix them in this PR and I think the simplest solution is to go back to using `.tpe.widen` and maybe handling a few edge cases manually.
By the way, 👏 @olafurpg for the testing infra with chevrons: really handy to use!
=> Add Hover Test and fix broken cases

languageserver/src/main/scala/langserver/core/LanguageServer.scala, languageserver/src/main/scala/langserver/messages/Commands.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala
Minor changes to the default implementations in the `languageserver` bindings. They seem less arbitrary now.
=> Less arbitrary defaults in LanguageServer

metaserver/src/main/scala/scala/meta/languageserver/Effects.scala, metaserver/src/main/scala/scala/meta/languageserver/Linter.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/compiler/ScalacProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/search/SymbolIndex.scala, metaserver/src/test/scala/tests/search/SymbolIndexTest.scala
This commit reorganizes the flow of effects in the application. Most
notably,
- scalac provider no longer handles indexing of classpath sources,
SymbolIndex handles all indexing.
- Observable[Effect] no longer leak into utilities like
Scalafix/ScalacProvider, these stay only within ScalametaLanguageServer.
=> Refactor the flow of effects.

project/build.properties, project/plugins.sbt
sbt 1.0.4 has been [released recently](https://developer.lightbend.com/blog/2017-11-27-sbt-1-0-4-hotfix-and-performance-fixes/index.html) and is supposed to fix the continuous compilation problem.
=> Updated sbt and plugins

build.sbt
This PR enables semanticdb-scalac plugin on all the subprojects. This means that we can effectively use all the features of language-server while developing the language-server itself.
=> Enable the semanticdb-scalac plugin on metaserver and langserver

metaserver/src/main/scala/scala/meta/languageserver/Buffers.scala, metaserver/src/main/scala/scala/meta/languageserver/OutlineProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/Parser.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaEnrichments.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/DocumentSymbolProvider.scala
This is a follow-up of #34. Previous PR was OK as a first try, but had a lot of problems:
* listing symbols inside of defs, vals and vars (and misplacing their children)
* used ineffective traversal: collecting all named nodes and then trying to get up their lineage with different conditions (what seemed to me as a light and smart solution at first, was actually clumsy and bug-prone)
* while the buffer was in unparseable state, outline became empty
This PR solves all these problems (and hopefully doesn't introduce new ones):
* outline provider is implemented using `Traverser`
* parsed `Source`s are stored and old ones are reused while buffer is not parseable
It seems to work well, but I have a couple of doubts about code organization:
* where should I put `OutlineProvider`? is it ok in …
=> Symbols outline rework

build.sbt, metaserver/src/main/scala/scala/meta/languageserver/Buffers.scala, metaserver/src/main/scala/scala/meta/languageserver/Effects.scala, metaserver/src/main/scala/scala/meta/languageserver/ErrorReporter.scala, metaserver/src/main/scala/scala/meta/languageserver/Linter.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/Semanticdbs.scala, metaserver/src/main/scala/scala/meta/languageserver/compiler/ScalacProvider.scala
This PR uses the new `InteractiveSemanticdb` facility (introduced by Scalameta 2.1.3) to produce an `Observable` of semantic dbs as you type.
This `Observable` is merged with the file system one (fed by semanticdb files written on disk by `semanticdb-scalac`).
The net result is that now Scalafix runs also as you type. Demo:
I think it still needs some polishing (sometimes the PC dies in an unexpected way, causing an exception to be thrown and the Observable to die) and ideally some tests.
=> Produce a stream of semanticdbs as you type

build.sbt, languageserver/src/main/scala/langserver/core/Connection.scala, languageserver/src/main/scala/langserver/core/LanguageServer.scala, languageserver/src/main/scala/langserver/core/Main.scala, languageserver/src/main/scala/langserver/messages/Commands.scala, languageserver/src/main/scala/langserver/types/types.scala, metaserver/src/main/scala/scala/meta/languageserver/Main.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/DocumentFormattingProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/DocumentSymbolProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/SignatureHelpProvider.scala, metaserver/src/test/scala/tests/compiler/SignatureHelpTest.scala
Previously, all messages were handled synchronously.  This made it
tricky to implement desirable features like request cancellation and
restarting crashing presentation compiler. This commit is the first
step towards making it easier to fix these problems by porting to
monix Task[T]. The main motivation to use monix task instead of stdlib
Future is cancellation and overflow strategies (drop old messages with
configurable buffer size) are provided out of the box. Monix
TestScheduler makes it also easy to test the server synchronously.
Task[T].runAsync returns a stdlib future which makes it fit perfectly
into the existing code with language-server, we never need to block.
=> Move all requests to Task[T]

languageserver/src/main/scala/langserver/core/Connection.scala, languageserver/src/main/scala/langserver/core/LanguageServer.scala, metaserver/src/main/resources/logback.groovy, metaserver/src/main/scala/scala/meta/languageserver/LSPLogger.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/test/scala/tests/search/SymbolIndexTest.scala
The combination of #104 #103 and #100 made the server almost unusable. This PR tries to repair a bit of the damage by
- pushing notifications and commands onto the `Scheduler` instead of main thread. Commands were accidentally running on the main thread because I used `Task.now` 😅 . Notifications were also blocking the main thread because we compile on every change after #100.
- disable interactive semanticdb #100, scalac and scalafix were racing to publish diagnostics making red squigglies jitter in the editor. I propose we dedicate a PR to fix that issue, this PR is only about returning the server to a functioning state for people who checkout master.
- reduce the logging noise to the clients from #103 by skipping Message{Reader/Writer} entries. Maybe there's a better way to implement …
=> Get server back into working state

metaserver/src/main/scala/scala/meta/languageserver/mtags/ScalaMtags.scala, metaserver/src/test/scala/tests/mtags/ScalaMtagsTest.scala, metaserver/src/test/scala/tests/search/SymbolIndexTest.scala, test-workspace/src/test/scala/example/UserTest.scala
Given 
```scala
package object K {
val x = 42
}
```
the symbol for `x` should be `_root.K.`package`.x`. Right now it's `_root_.K.x`
=> ScalaMtags computes a wrong symbol for members in package objects

vscode-extension/package.json, vscode-extension/src/extension.ts
This is a client-specific command to help with debugging, especially while we're dealing with PC issues that may stall the server.
Example:
=> Add command in VSCode extension to restart the server

metaserver/src/main/scala/scala/meta/languageserver/providers/HoverProvider.scala, metaserver/src/test/scala/tests/hover/HoverTest.scala
This partially addresses #125. We are still missing hovers in some obvious spots, but at least we're not returning `<notype>` to the client.
=> Avoid ever returning `<notype>` to the client

build.sbt, languageserver/src/main/scala/langserver/core/LanguageServer.scala, languageserver/src/main/scala/langserver/messages/Commands.scala, languageserver/src/main/scala/langserver/types/types.scala, languageserver/src/main/scala/langserver/utils/JsonRpcUtils.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/WorkspaceCommand.scala, vscode-extension/package.json, vscode-extension/src/extension.ts
=> Add workspace/executeCommand and clearIndexCache command

metaserver/src/main/scala/scala/meta/languageserver/Main.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, vscode-extension/src/extension.ts
The logs are emitted in `<working directory>/.metaserver/metaserver.log`
I didn't use the `directories` project to get the path because it
assumes you want a different location for config/cache and there is no
log-specific option. I personally want all metaserver files to be
bundled in the same directory so I can `rm -rf .metaserver`.
Fixes #112 
I'm itching to start using the plugin for my development but I found this issue made it awkward to start the server from neovim.
=> Remove unnecessary -Dvscode.workspace argument.

languageserver/src/main/scala/langserver/core/Connection.scala, languageserver/src/main/scala/langserver/core/LanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala
This PR implements the CancelRequest(id) message. It doesn't seem
like this has any immediate effect on the server since our Task[T] are
quite shallow. When we do `.cancel()`, monix will not interrupt an
ongoing step, it will only stop executing a Task between map/flatMap/...
Good motivation for us to write more inside Task.
Only relevant commit is d61f1ef
=> Implement $/cancelRequest, fixes #118.

metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/WorkspaceCommand.scala, metaserver/src/main/scala/scala/meta/languageserver/compiler/CompilerConfig.scala, metaserver/src/main/scala/scala/meta/languageserver/compiler/ScalacProvider.scala, project/ScalametaLanguageServerPlugin.scala, vscode-extension/package.json, vscode-extension/src/extension.ts
Previously, we didn't keep track of active presentation compilers so the first commit re-organized handling of PC instances. I tried this locally and the UX wasn't stellar, red squigglies are not refreshed and there is no notification when the PC has been reloaded, completions just suddenly start picking up the latest classpath changes. 
Note that askReload only makes the PC pick up latest classpath changes. If you add a new class in module `a` and want it to appear in a file in module `b` that depends on `a`, then you must first re-compile module `a` via sbt and then "Reload presentation compilers".
=> Add command to reset presentation compiler

build.sbt, languageserver/src/main/scala/langserver/core/LanguageServer.scala, languageserver/src/main/scala/langserver/messages/Commands.scala, languageserver/src/main/scala/langserver/types/types.scala, metaserver/src/main/scala/org/langmeta/semanticdb/SemanticdbEnrichments.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/search/InMemorySymbolIndex.scala, metaserver/src/main/scala/scala/meta/languageserver/search/SymbolIndex.scala, metaserver/src/test/scala/tests/search/SymbolIndexTest.scala, test-workspace/src/main/scala/example/User.scala
I found this functionality desperately missing while trying out the plugin. The current implementation builds on top of our existing semanticdb symbol index.
I left two improvements for future PRs
- https://github.com/scalameta/language-server/issues/139 - semanticdb-free indexing
- https://github.com/scalameta/language-server/issues/138 - better fuzzy search
=> Workspace symbols

metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/compiler/ScalacProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/mtags/MtagsIndexer.scala, metaserver/src/main/scala/scala/meta/languageserver/mtags/ScalaMtags.scala, metaserver/src/main/scala/scala/meta/languageserver/search/InMemorySymbolIndex.scala, metaserver/src/main/scala/scala/meta/languageserver/search/SymbolIndex.scala, metaserver/src/test/scala/tests/mtags/ScalaMtagsTest.scala
Fixes #134. I noticed that the new "clear index" command doesn't cleanup the in-memory `indexedJars` map forcing me to restart the server to re-index.
This is my first PR developed (almost) entirely through vscode 🎉
=> Index class primary constructor parameters

BETA.md
The `project` part seems to be not needed
=> Fixed location of the plugin for 0.13

.scalafmt.conf, languageserver/src/main/scala/langserver/core/Connection.scala, languageserver/src/main/scala/langserver/core/LanguageServer.scala, languageserver/src/main/scala/langserver/messages/Commands.scala, languageserver/src/main/scala/langserver/types/types.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/Semanticdbs.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/RenameProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/refactoring/Backtick.scala, metaserver/src/test/scala/tests/refactoring/BacktickTest.scala, test-workspace/src/main/scala/example/User.scala
This commit implements renaming for local symbols. An error message is
presented to the user in case the symbol is global or the new name is
not a valid identifier.
Fixes first part of https://github.com/scalameta/language-server/issues/149
=> Implement textDocument/rename for local symbols.

languageserver/src/main/scala/langserver/core/LanguageServer.scala, languageserver/src/main/scala/langserver/messages/Commands.scala, metaserver/src/main/scala/scala/meta/languageserver/Configuration.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, vscode-extension/package.json, vscode-extension/src/extension.ts
Closes #6 
The purpose of this PR is purely to provide the infrastructure for this feature.
The configuration is decoded and logged, but not yet used.
It's also interesting to note that (at least in VSCode) the language client will send the current configuration right away when starting the server.
=> Add support for configuration

build.sbt, metaserver/src/main/scala/org/langmeta/languageserver/InputEnrichments.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaEnrichments.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/DefinitionProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/DocumentHighlightProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/ReferencesProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/search/BinarySearch.scala, metaserver/src/main/scala/scala/meta/languageserver/search/InMemorySymbolIndex.scala, metaserver/src/main/scala/scala/meta/languageserver/search/MatchingToken.scala, metaserver/src/main/scala/scala/meta/languageserver/search/SymbolIndex.scala, metaserver/src/main/scala/scala/meta/languageserver/search/TokenEditDistance.scala, metaserver/src/test/scala/tests/search/SymbolIndexTest.scala, metaserver/src/test/scala/tests/search/TokenEditDistanceTest.scala
Fixes #130. We currently only use this new feature for go-to-definition.
It only works if the definition is in another file with up-to-date semanticdb, otherwise stale positions are used for the definition. We should follow-up by using it for references as well.
I wanted to open this PR before it gets any bigger.
Hover will also benefit from this PR once we move away from the PC for
hover.
=> Implement edit-distance for stale semanticdbs.

metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/HoverProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/RenameProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/search/InMemorySymbolIndex.scala, metaserver/src/main/scala/scala/meta/languageserver/search/SymbolIndex.scala, metaserver/src/test/scala/tests/hover/BaseHoverTest.scala, metaserver/src/test/scala/tests/hover/HoverTest.scala, metaserver/src/test/scala/tests/search/BaseIndexTest.scala
Fixes #148 
Instead of showing only the type I opted to do the same as the Java Language Server and also include modifiers like `implicit val` or `final class` or `private object`. It's sometimes a bit weird, like variables bound in patterns get `val`, but I personally find this a nice improvement.
=> Move hover to semanticdb.

build.sbt, languageserver/src/main/scala/langserver/core/Connection.scala, languageserver/src/main/scala/langserver/core/LanguageServer.scala, languageserver/src/main/scala/langserver/messages/Commands.scala, languageserver/src/main/scala/langserver/types/types.scala, metaserver/src/main/scala/scala/meta/languageserver/Main.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaEnrichments.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/WorkspaceCommand.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/CodeActionProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/refactoring/OrganizeImports.scala, metaserver/src/main/scala/scala/meta/languageserver/refactoring/TextEdits.scala, metaserver/src/main/scala/scalafix/languageserver/ScalafixEnrichments.scala, metaserver/src/main/scala/scalafix/languageserver/ScalafixPatchEnrichments.scala, metaserver/src/test/scala/tests/compiler/CompilerSuite.scala, metaserver/src/test/scala/tests/refactoring/RemoveUnusedImportsTest.scala
This PR implements a codeAction to remove unused imports with scalafix. The patch produced by scalafix is converted to precise `TextEdit` per changed token, instead of sending a single TextEdit to replace the whole file as we do with scalafmt.
codeActions appear as lightbulbs above the cursor and when the lightbulb is clicked a dialogue opens with a list of commands to run (not shown in gif).
All of `ScalafixPatchEnrichments` is copy pasted from the scalafix sources, with the next release of scalafix this file will no longer be necessary since in master we have an API to get `List[TokenPatch]` from a `Patch`
=> Implement textEdit/codeAction

metaserver/src/main/scala/scala/meta/languageserver/Configuration.scala, metaserver/src/main/scala/scala/meta/languageserver/Formatter.scala, metaserver/src/main/scala/scala/meta/languageserver/Main.scala, metaserver/src/main/scala/scala/meta/languageserver/MonixEnrichments.scala, metaserver/src/main/scala/scala/meta/languageserver/PlayJsonEnrichments.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/Semanticdbs.scala, metaserver/src/main/scala/scala/meta/languageserver/compiler/ScalacProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/DocumentFormattingProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/SquiggliesProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/search/InMemorySymbolIndex.scala, metaserver/src/main/scala/scala/meta/languageserver/search/SymbolIndex.scala, metaserver/src/test/scala/tests/compiler/SquiggliesTest.scala, metaserver/src/test/scala/tests/search/BaseIndexTest.scala, metaserver/src/test/scala/tests/search/SymbolIndexTest.scala, test-workspace/src/main/scala/example/User.scala, vscode-extension/package.json
This turned out to be a bit larger than I imagined, so I'm opening the PR although it's not completely done.
Some highlights:
- we now produce an `Observable[Configuration]` that gets passed around to providers
- as a result, providers are now in charge of instantiating whatever resource they need, using the configuration (e.g.  `DocumentFormattingProvider` creates a `Formatter`, instead of receiving it as input). I think this makes more sense in term of ownership and the `ScalametaLanguageServer` is now only managing providers, instead of all their dependencies)
- since now most providers' actions require accessing the configuration via `lastL`, they now return a `Task` directly, which again I think it makes sense. _"Task all the things!"_ (cit)
- I've decided to use `lastL` and not …
=> Refactor server around configuration Observable

jsonrpc/src/main/scala/org/langmeta/jsonrpc/BaseProtocolMessage.scala, jsonrpc/src/main/scala/org/langmeta/jsonrpc/BaseProtocolMessageParser.scala, jsonrpc/src/main/scala/org/langmeta/jsonrpc/MessageWriter.scala, jsonrpc/src/main/scala/org/langmeta/jsonrpc/Services.scala, lsp4s/src/main/scala/org/langmeta/lsp/LanguageClient.scala, lsp4s/src/main/scala/org/langmeta/lsp/LanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/Main.scala, metaserver/src/test/scala/tests/search/SymbolIndexTest.scala
I'm experimenting with Jorge with a bloop integration and we are trying
to share some code. In Bloop they have their own custom logging
infrastructure so this commit makes it possible to inject custom
loggers into the core jsonrpc classes.
=> Make it possible to inject custom logger to jsonrpc/lsp.

.travis.yml, build.sbt, jsonrpc/src/main/scala/org/langmeta/jsonrpc/JsonRpcClient.scala, jsonrpc/src/main/scala/org/langmeta/jsonrpc/MessageWriter.scala, jsonrpc/src/main/scala/org/langmeta/jsonrpc/RequestId.scala, lsp4s/src/main/scala/org/langmeta/lsp/LanguageClient.scala, metaserver/src/main/scala/scala/meta/languageserver/Configuration.scala, metaserver/src/main/scala/scala/meta/languageserver/Models.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaServices.scala, metaserver/src/main/scala/scala/meta/languageserver/WorkspaceCommand.scala, metaserver/src/main/scala/scala/meta/languageserver/sbtserver/Sbt.scala, metaserver/src/main/scala/scala/meta/languageserver/sbtserver/SbtServer.scala, metaserver/src/test/scala/tests/sbtserver/SbtServerTest.scala, project/build.properties, test-workspace-sbt-1.1/a/src/main/scala/a/A.scala, test-workspace-sbt-1.1/build.sbt, test-workspace-sbt-1.1/project/build.properties, tests/integration/src/test/scala/sbtserver/SbtServerTest.scala, vscode-extension/package.json, vscode-extension/src/extension.ts
Fixes #169. 
This PR adds an integration to connect to sbt 1.1 language server
to compile via sbt on file save and publish error messages as
diagnostics. We reuse the LanguageServer and LanguageClient
utilities but we are now a client instead of server, compared to when
connecting to editors.
This PR adds a new SbtConnect command to re-estabilish a connection
with sbt in case of a disconnection, for example if you exit sbt and
open again. Ideally, we can figure this out automatically in the future,
but a manual approach is a good start.
There are two new settings to control this new feature
- sbt.enabled, must be true to use this feature, false by default.
- sbt.command, which command to execute on file save. This makes it
possible to for example run or test instead of compile or select
a …
=> Integrate with sbt language server

jsonrpc/src/main/scala/org/langmeta/jsonrpc/MessageWriter.scala
Basically `withObject` is `flatMap` and `mapObject` is `map`.
They both resolve to an identity function in case the `Json` is not a `JObject`.
=> Replace withObject with mapObject

jsonrpc/src/main/scala/org/langmeta/jsonrpc/BaseProtocolMessage.scala, jsonrpc/src/main/scala/org/langmeta/jsonrpc/BaseProtocolMessageParser.scala
This is a more general API that allows us to play nicer with other
inputs than InputStream, for example
https://github.com/brettwooldridge/NuProcess which may be necessary
for #174. The internal implementation is still naive and copies a lot,
but that can be optimized later without changing the API.
=> Read Observable[ByteBuffer] instead of Array[Byte]

README.md, build.sbt
Jorge has been following the project from the early days providing
valuable feedback both offline and online. I am also very excited to see
what comes out of #174.
=> Invite Jorge to the team.

jsonrpc/src/main/scala/org/langmeta/jsonrpc/JsonRpcClient.scala, jsonrpc/src/main/scala/org/langmeta/jsonrpc/MessageWriter.scala, lsp4s/src/main/scala/org/langmeta/lsp/LanguageClient.scala, lsp4s/src/main/scala/org/langmeta/lsp/MonixEnrichments.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaServices.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/DocumentFormattingProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/providers/SquiggliesProvider.scala, metaserver/src/main/scala/scala/meta/languageserver/search/InMemorySymbolIndex.scala
This refactoring makes it easier to emit jsonrpc
requests/response/notifications to consumers such as nuprocess
that don't operate on java.io.OutputStream
=> Refactor from OutputStream to Observer[ByteBuffer].

benchmarks/src/main/scala/benchmarks/HotBaseProtocolMessageParserBench.scala, build.sbt, jsonrpc/src/main/scala/org/langmeta/jsonrpc/BaseProtocolMessage.scala, jsonrpc/src/main/scala/org/langmeta/jsonrpc/BaseProtocolMessageParser.scala, jsonrpc/src/main/scala/org/langmeta/jsonrpc/Message.scala, jsonrpc/src/main/scala/org/langmeta/jsonrpc/MessageWriter.scala, lsp4s/src/main/scala/org/langmeta/lsp/LanguageServer.scala, metaserver/src/main/scala/scala/meta/languageserver/MSchedulers.scala, metaserver/src/main/scala/scala/meta/languageserver/Main.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaServices.scala, metaserver/src/main/scala/scala/meta/languageserver/sbtserver/Sbt.scala, metaserver/src/test/scala/tests/DiffAsserts.scala, metaserver/src/test/scala/tests/MegaSuite.scala, metaserver/src/test/scala/tests/jsonrpc/BaseProtocolMessageTest.scala, metaserver/src/test/scala/tests/search/SymbolIndexTest.scala, project/plugins.sbt
The header parser previously didn't have any unit tests because it just worked with vscode. However, with us relying more on the JSON-RPC implementation for bsp and sbt server integration I feel comfortable with having at least a couple unit tests.
It turned out to be quite tricky to unit test the current implementation because it forced the Observable to run on a custom Scheduler. We replace that with a `.exectuteWithFork` and add a new `MSchedulers` helper to keep track of Schedulers in the application.
The last commit adds a `benchmarks` project to lower the barrier for writing benchmarks, in case someone is interested. I have a hunch that a lot of parts in the codebase are ripe for optimizations, but I don't want to try an optimize anything without bringing accompanying benchmarks.
=> Add unit tests and benchmark suite for LSP base protocol parser

metaserver/src/main/scala/scala/meta/languageserver/providers/DocumentFormattingProvider.scala
Fix #185 
We have three cases to handle:
1) a. user specified a custom path and it exists, or
b. user didn't specify a path and the default path .scalafmt.conf exists
2) user specified a custom path and it doesn't exist
3) user didn't specify a custom path and .scalafmt.conf doesn't exists
---
1. and 3. should not return an error and fallback to the default
Scalafmt configuration is .scalafmt.conf doesn't exist
2. should return an error
This PR handles 3., which currently returns an error
Tested locally with `publishLocal`
=> Use default scalafmt conf is .scalafmt.conf file is missing

.travis.yml, build.sbt, jsonrpc/src/main/scala/org/langmeta/jsonrpc/Services.scala, lsp4s/src/main/scala/org/langmeta/lsp/LanguageServer.scala, lsp4s/src/main/scala/org/langmeta/lsp/Types.scala
This required:
- using a few explicit trait instantiations instead of SAMs
- removing one dangling comma
- using `-Ywarn-unused-imports` instead of `-Ywarn-unused:imports`
=> Cross build lsp4s for Scala 2.11/2.12

metaserver/src/main/scala/scala/meta/languageserver/ScalametaServices.scala, vscode-extension/package.json, vscode-extension/src/extension.ts
This is a continuation of #180
It only takes into account the VSCode extension, but it has one breaking change: the prefix name of the configuration, which is `"metals"` instead of `"scalameta"`.
Other client implementations will potentially break if they implemented the configuration API. @laughedelic does the atom extension support configuration?
=> s/scalameta/metals in VSCode extension

lsp4s/src/main/scala/org/langmeta/lsp/Commands.scala, lsp4s/src/main/scala/org/langmeta/lsp/Endpoints.scala, lsp4s/src/main/scala/org/langmeta/lsp/Enums.scala, metaserver/src/main/scala/scala/meta/languageserver/Configuration.scala, metaserver/src/main/scala/scala/meta/languageserver/ScalametaServices.scala, vscode-extension/package.json
Several related changes here:
- added LSP v3 `TextDocumentSyncOptions` (instead of simple `TextDocumentSyncKind`)
- added [`textDocument/willSave`](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#willsavetextdocument-notification-arrow_right) notification
- added [`textDocument/willSaveWaitUntil`](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#willsavewaituntiltextdocument-request-leftwards_arrow_with_hook) which is useful to format the file right before it's saved
- added `scalameta.scalafmt.onSave` config parameter (false by default) to control this feature
I hoped to use it in Atom, but unfortunately it doesn't support `willSaveWaitUntil` request yet (although it has "format _after_ saving" feature). So I tried …
=> Added TextDocumentSyncOptions and format on save

metals/src/main/scala/scala/meta/metals/Configuration.scala, vscode-extension/package.json
Fixes #43 
I've tried turning the option back on and it just seems to work.
Tested locally by:
- enabling the `index JDK` test (currently ignored because it's slow)
- publishing locally and successfully jumping to a JDK file.
=> Re-enable indexJDK

metals/src/main/scala/scala/meta/metals/Configuration.scala, metals/src/main/scala/scala/meta/metals/Linter.scala, metals/src/main/scala/scala/meta/metals/providers/SquiggliesProvider.scala, metals/src/test/scala/tests/compiler/SquiggliesTest.scala
This is another step towards #161.
Not strictly necessary, but I took the opportunity to make Linter expose a `Task` directly.
=> Honor metals.scalafix.confPath

metals/src/main/scala/scala/meta/metals/Configuration.scala, metals/src/main/scala/scala/meta/metals/Effects.scala, metals/src/main/scala/scala/meta/metals/ScalacErrorReporter.scala, metals/src/main/scala/scala/meta/metals/ScalametaServices.scala, metals/src/main/scala/scala/meta/metals/providers/DocumentHighlightProvider.scala, vscode-extension/package.json
This fixes some points in #161:
- respect hover.enabled for tooltips on hover
- respect scalac.enabled for diagnostics, completions and signature help
- add an option to control symbol highlights (`textDocument.documentHighlight`)
Some things for discussion:
- I think that the features provided by presentation compiler should have their own switches. Although their stability depends on the state of PC, even if they do work, they may work differently and have different value for the user. So user may want to enable only some of them. 
- I got confused by the `PublishSquigglies` vs. `PublishScalacDiagnostics`. Isn't it all just diagnostics? Also I'm not sure I handled `scalac.enabled` for the diagnostics well. If I disable `sbt.enabled` and `scalac.enabled`, but enable `scalafix.enabled`, I …
=> Respect more configuration options

vscode-extension/package.json
[VSCode extensions should rely on the integrated DocumentFormatting API](https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices), which include the `editor.formatOnSave` settings.
Note that it's fine to keep the option on the server, as other editors without integrated support for formatting can use it.
=> Remove metals.scalafmt.onSave option from VSCode extension

metals/src/main/scala/scala/meta/metals/Configuration.scala
Hover uses SemanticDB and token-edit-distance (same as definition)
so it should be fairly robust. The only known caveat of hover is that it
shows generic types of symbols (not expressions), which can be annoying
when working with generic code (tuples, collections, ...).
=> Enable hover by default.

CONTRIBUTING.md, bin/start-server.sh, build.sbt
A minor change to avoid bumping this version after each release. It is used only for local publishing. All artifacts published to Bintray have unique versions based on Git describe.
=> Change version for local publishing to SNAPSHOT

.travis.yml
I was getting these CI failures on my fork:
```
0.02s$ if [ $TRAVIS_PULL_REQUEST = 'false'  ]; then openssl aes-256-cbc -K $encrypted_df92ba612cfd_key -iv $encrypted_df92ba612cfd_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d; tar xv -C travis -f travis/secrets.tar; fi
iv undefined
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
The command "if [ $TRAVIS_PULL_REQUEST = 'false'  ]; then openssl aes-256-cbc -K $encrypted_df92ba612cfd_key -iv $encrypted_df92ba612cfd_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d; tar xv -C travis -f travis/secrets.tar; fi" failed and exited with 2 during .
```
Because this pre-install script shouldn't run on a fork which doesn't have those encrypted env vars.
I have no idea if this is an …
=> Change condition for decrypting env vars for releases

project/plugins.sbt
This version does not depend on python to integrate protobuff on Windows
=> update sbt-protoc version

metals/src/main/scala/scala/meta/metals/Configuration.scala, metals/src/main/scala/scala/meta/metals/MetalsServices.scala, metals/src/main/scala/scala/meta/metals/sbtserver/Sbt.scala, metals/src/main/scala/scala/meta/metals/sbtserver/SbtServer.scala, metals/src/test/scala/tests/compiler/DiagnosticsTest.scala, vscode-extension/package.json
Fixes #228, #250:
* add `sbt.diagnostics.enabled = true`, ~~while keeping general `sbt.enabled = false` (as suggested by @gabro in https://github.com/scalameta/metals/issues/228#issuecomment-379285363)~~ (see discussion below: https://github.com/scalameta/metals/pull/263#discussion_r179914418)
* set `sbt.command = ""`
* simply skip `sbt/exec` if the passed command is empty
* don't autoconnect to the sbt server
=> Improve sbt server configuration

lsp4s/src/main/scala/org/langmeta/lsp/Enums.scala, metals/src/main/scala/org/langmeta/semanticdb/SemanticdbEnrichments.scala, metals/src/main/scala/scala/meta/metals/ScalametaEnrichments.scala, metals/src/main/scala/scala/meta/metals/providers/CompletionProvider.scala, metals/src/test/scala/tests/compiler/CompletionsTest.scala
Closes #259
I added the new lsp CompletionItemKinds and SymbolKinds.
For CompletionItemKinds I only mapped TypeParameter and Function, but I'm not sure if you want Function mapped because it's not a new CompletionItemKind, and it wasn't previously mapped. I also think the Function case is dead-code cause when trying to complete a symbol that's a function it'll probably go into the val case.
For SymbolKinds I'm not convinced that I did the additions to ScalametaEnrichments correctly. I'm not sure if documentSymbol() adds Type.Param and Lit.Null to the list that it builds, so those additional cases might be pointless.
Finally the issue mentions Constant in CompletionItemKind. I'm not sure how to map that cause doesn't CompletionItemKind.Value cover that, or does Constant mean something …
=> Issue 259: use enhanced (CompletionItem|Symbol)Kinds

build.sbt, docs/installation.md, metals/src/main/scala/scala/meta/metals/MetalsServices.scala, metals/src/main/scala/scala/meta/metals/sbtserver/SbtServer.scala
This is a proof-of-concept integration with [load-plugin](https://github.com/scalacenter/load-plugin).
It eliminates the need to add global sbt-metals in case of sbt 1. On every connection to the sbt server Metals will load sbt-metals and run `semanticdbEnable` automatically.
Next steps:
=> load-plugin integration

lsp4s/src/main/scala/org/langmeta/lsp/Endpoints.scala, metals/src/main/resources/logback.groovy, metals/src/main/scala/scala/meta/metals/LSPLogger.scala
This does not address https://github.com/scalameta/metals/issues/227. It only
* adds missing log levels to the `showMessage`/`logMessage` notifications
* adds `showMessageRequest` request
* fixes log levels and simplifies formatting of the messages that are sent to the LSP client:
(before all these messages were sent with the `log` level)
=> LSP logging improvements

docs/installation.md
As per gitter discussion - a small installation guide update pointing out the user will need to manually install the VSCode plugin manually.
=> Add note on VSCode status to installation instructions

metals/src/test/scala/tests/CompilerSuite.scala, metals/src/test/scala/tests/provider/BaseHoverProviderTest.scala, metals/src/test/scala/tests/provider/CompletionsProviderTest.scala, metals/src/test/scala/tests/provider/DiagnosticsProviderTest.scala, metals/src/test/scala/tests/provider/HoverProviderTest.scala, metals/src/test/scala/tests/provider/SignatureHelpProviderTest.scala, metals/src/test/scala/tests/refactoring/RemoveUnusedImportsTest.scala, metals/src/test/scala/tests/search/BaseIndexTest.scala
This pr just updates test file locations to match code under test packages along with the associated import changes (some import orders are changed due to IJ organize import functionality).
=> Move provider tests into provider package

BETA.md
I see no value in keeping this redirect around, so I've removed it.
=> Remove obsolete BETA.md

vscode-extension/src/extension.ts
I'm not particularly fluent with JS nor VSCode APIs so this is a fairly basic implementation. It can definitely be refined further, such as @laughedelic suggestion of a progress bar. 
However I would say that its an improvement vs status quo; definitely better to have some feedback to user whether the metals server has been resolved successfully or not.
I have manually tested both the Happy and Unhappy paths.
Fixes #303
=> Coursier resolve to validate serverVersion, log to console if correct/incorrect

vscode-extension/package.json, vscode-extension/yarn.lock
Fixes #308 
Tested locally, after removing `node_modules` and re-running the installation steps, `npm run build` works again.
=> Bump minimum required vscode version

lsp4s/src/main/scala/org/langmeta/lsp/Commands.scala, metals/src/test/scala/tests/search/SymbolIndexTest.scala
According to the specification, the processId parameter is optional.
Some LSP clients (for example, vim-lsp) do not provide this parameter.
Currently, Metals fails to initialize for those clients. Making this
parameter optional allows initialization to continue.
This parameter appears to be unused, so only the type has been changed.
https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#initialize
=> Parameter processId to initialize is optional

vscode-extension/src/extension.ts
We've never used these options, they were copy-pasted from dragos' original implementation of the extension, and they've caused me an hour of headache because the JVM tried to bind the port 8000 (which was already bound on my computer) and failing with a cryptic error.
=> Remove debug options from vscode extensions

metals/src/main/scala/scala/meta/metals/providers/DocumentFormattingProvider.scala
Just a simple hack to calculate the end range.
Note: Did not find any tests for DocumentFormattingProvider.scala, so did not add any.
Fixes #315
=> Calculate correct range from input file chars

build.sbt, docs/editors/atom.md, docs/editors/vim.md, metals-docs/src/main/scala/docs/BootstrapModifier.scala, metals-docs/src/main/scala/docs/Docs.scala, metals-docs/src/main/scala/docs/RequirementsModifier.scala, metals-docs/src/main/scala/docs/Snapshot.scala, metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala, metals/src/main/scala/scala/meta/internal/metals/GlobalTrace.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
- use latest published SNAPSHOT version. While Metals is
changing frequently at every commit I think it's best to advertise
SNAPSHOT versions instead of stable releases which will be less
frequent.
- use latest vim-lsc plugin version
=> Clarify installation docs

build.sbt, mtags/src/main/scala/scala/meta/internal/mtags/DefinitionAlternatives.scala, mtags/src/main/scala/scala/meta/internal/mtags/InverseLegacyToken.scala, mtags/src/main/scala/scala/meta/internal/mtags/JavaMtags.scala
This module will be used by almond which requires 2.11 support.
=> Cross-build mtags for Scala 2.11

build.sbt
This setting is required to publish sbt plugins to Maven Central.
Previously the plugin was published "ivy-style", which results in
resolution errors
```
:: org.scalameta#sbt-metals;0.2.0+3-82fa2560-SNAPSHOT: not found
```
=> Publish sbt-metals maven style

CONTRIBUTING.md, README.md
Fixes #349 
This is a super lazy fix, I think generally the README could use some refactoring, but at least links are not broken now.
=> Fix 404 links

metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala
Previously, users would get resolution errors if trying out the snapshot
releases.
=> Use snapshot resolver when sbt-metals is a snapshot

metals/src/main/scala/scala/meta/internal/metals/MetalsHttpClient.scala
The change to `case class Command` broke the http button.
=> Fix HTTP execute command interface

docs/editors/new-editor.md, metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
The --verbose flag in bloop produces a lot of logs that are not relevant
unless you are troubleshooting issues. This commit disables --verbose
but allows users to turn it on if something is amiss.
cc/ @coreyoconnor
=> Add -Dmetals.verbose to enable verbose logging

build.sbt, tests/unit/src/main/scala/tests/QuickBuild.scala
The v1.1.0 Bloop release will soon be out, this commit upgrades to the
latest Bloop nightly.
=> Bump dependencies to prepare for Bloop v1.1.0

metals/src/main/scala/scala/meta/internal/metals/BuildTools.scala, tests/unit/src/test/scala/tests/SbtDetectionSuite.scala
The previous logic assumed all sbt builds have `build.sbt` but that is
not correct. This commit changes the logic to guard against
`project/build.properties` with a `sbt.version` key. This key is
used by the sbt launcher and the sbt launcher generates this file
when `project/build.properties` is missing.
=> Refine sbt build detection

metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, tests/slow/src/test/scala/tests/SbtSlowSuite.scala, tests/unit/src/main/scala/tests/BaseSlowSuite.scala, tests/unit/src/main/scala/tests/TestingClient.scala
- Add "Diagnostics" and "Goto definition" columns to Doctor table,
remove "SemanticDB". This is more helpful for users trying to
understand the implications of the warning sign. Also makes it clear
that diagnostics still work for 2.10/2.13.
- Explain what the table lists, previously it was just a raw html table
with no explanation.
- Use `th` for header row and align icons in the center, makes it more
readable.
- Use clearer language in the import build warning message.
- Add test for `executeClientCommand`.
=> Refine doctor messages.

metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala, metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsHttpClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/Urls.scala, test-workspace/build.sbt, tests/slow/src/test/scala/tests/SbtSlowSuite.scala
This commit adds two changes:
- `metals-doctor-reload` client command to trigger a reload if a doctor
window, if such a window exists.
- a new `showMessage` information message to inform the user when build
mis-configuration has been fixed.
Demo of the auto-reloading doctor window, recorded before the `showMessage` got added.
Thanks to @jvican for the idea!
=> Inform the user when doctor problems have been fixed

roadmap.md
`roadmap.md` points to a 404, as reported by @lambdista on Twitter.
In general, we had a few markdown files scattered around before we had a website and we subsequently added pointers to them for retro-compatibility.
I think this specific document can go, users can refer to the website for up-to-date information.
=> Remove old roadmap.md document

metals-docs/src/main/scala/docs/UserConfigurationModifier.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
Fix for https://github.com/scalameta/metals/pull/387#discussion_r240047421
The `"settings"` key is part of the protocol, so it's already de-serialized by lsp4j.
=> Fix handling of didChangeConfiguration payload

metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, tests/unit/src/test/scala/tests/UserConfigurationSuite.scala
Previously, we would accept `javaHome=Some("")`, which would
then result in trying to read the empty path directory `""`.
=> Filter out empty config strings

docs/editors/atom.md, docs/editors/sublime.md, docs/editors/vim.md, docs/editors/vscode.md, metals-docs/src/main/resources/META-INF/services/mdoc.StringModifier, metals-docs/src/main/scala/docs/BootstrapModifier.scala, metals-docs/src/main/scala/docs/Docs.scala, metals-docs/src/main/scala/docs/GenericModifier.scala, metals-docs/src/main/scala/docs/ReleasesModifier.scala, metals-docs/src/main/scala/docs/Snapshot.scala
Followup on feedback from several people for things that can be clearer in the docs.
I'm not too happy about the readability of the markdown sources with the `mdoc:generic` modifiers. I can live with it however, since it avoids copy-pasting a lot of text. I want to try and have each editor page be fully self-contained even if it comes at the price of duplicated content.
=> Update editor installation instructions based on feedback

metals/src/main/scala/scala/meta/internal/metals/MetalsLogger.scala
A lot of stack traces that have been reported in issues
include ansi escape codes
```
23 ^[[0m^[[31m[E]^
```
The logs are still readable without color so let's remove them.
The logs look like this now
```
INFO  tests.TestingServer#didOpen
INFO  time: compiled a in 0.51s
INFO  time: compiled c in 0.5s
```
=> Remove colors from metals.log

docs/editors/new-editor.md, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, metals/src/main/scala/scala/meta/internal/metals/RecursivelyDelete.scala, metals/src/main/scala/scala/meta/internal/metals/Tables.scala, tests/unit/src/main/scala/bill/Bill.scala, tests/unit/src/main/scala/tests/BaseSlowSuite.scala, tests/unit/src/main/scala/tests/DirectoryExpectSuite.scala, tests/unit/src/test/scala/tests/BaseTablesSuite.scala, tests/unit/src/test/scala/tests/FileWatcherSlowSuite.scala
Fixes #406.
- first try `AUTO_SERVER=true`
- in case of errors, try `AUTO_SERVER=false`
- in case of errors (due to multiple servers in the same workspace), use
in-memory database.
This commit adds a new `-Dmetals.h2.auto-server=false` option to disable
`AUTO_SERVER=true`, for users who do not want H2 to speak via TCP to
concurrent Metals servers.
=> Make H2 database connection establishment more robust

docs/editors/emacs.md
This PR makes a refactor of Emacs Editor documentation.
- Avoid using `require`.
- Enable `defer` by default for `use-package`.
- Enable `ensure` by default for `use-package`.
- Use `:hook` instead of `add-hook` function.
- Use `:load-path` for `lsp-scala`.
=> Improve Emacs docs

.scalafmt.conf, build.sbt, metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/metals/FilterMatcher.scala, metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, test-workspace/.scalafmt.conf, test-workspace/src/main/scala/example/User.scala, tests/unit/src/main/scala/tests/InputFile.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/FormattingSlowSuite.scala
This PR implements `textDocument/formatting` using Scalafmt.
Notable points:
- Scalafmt is classloaded, so that users can choose a version
- By default, Scalafmt won't run if no config file is found. This prevents users from accidentally formatting a file with the default config, although they can opt-in to this behavior
- Users can specify a custom Scalafmt config path
=> Implement textDocument/formatting using Scalafmt

metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala
Minor follow up of #429 
Example:
=> Add log when skipping formatting of a file due to Scalafmt configuration

docs/editors/emacs.md
Supersedes #433. I squashed the commits to remove the large GIF file from git history.
=> Add note to Emacs docs about Eglot usage

appveyor.yml
The first time I tried to run sbt on appveyor the build had failed 5 times in a row with the same error `[Not found]file:/C:/Users/appveyor/.sbt/preloaded/org.scala-lang/scala-compiler/2.12.6/jars/scala-compiler.jar`. From the log I can see that `robocopy` task and `sbt publishLocal` were running almost in parallel. I have added a dumb init, so if sbt fails the first time, the robocopy has a chance to catch-up. 
Related: #435
=> Preinit sbt on appveyor, because it usually fails the first time

build.sbt, docs/build-tools/new-build-tool.md, docs/build-tools/overview.md, docs/contributors/getting-started.md, docs/editors/overview.md, project/plugins.sbt, website/package.json
It seems that relative `.md` links works now after the docusaurus upgrade, no more dead link warnings 🎉
=> Upgrade to mdoc v1.0.0

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/StatusBar.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, tests/unit/src/main/scala/tests/BaseSlowSuite.scala, tests/unit/src/main/scala/tests/BaseSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/CascadeSlowSuite.scala, tests/unit/src/test/scala/tests/CurrentProjectCompileSlowSuite.scala, tests/unit/src/test/scala/tests/InverseDependenciesSuite.scala, tests/unit/src/test/scala/tests/StatusBarSlowSuite.scala, tests/unit/src/test/scala/tests/UserConfigurationSuite.scala
Previously, we showed a single "Compiling $project" message when
compiling a project regardless if that project triggered compilation
in other projects in the workspace. With this commit, we now add
a "Compiling $project" status bar message for each unique project
that's compiled.
For example, if you open `core-test` with one transitive dependency you
get two status bar updates.
- "Compiling core": the main sources.
- "Compiling core-test": the test sources.
=> Improve compilation tracking in the status bar.

build.sbt, docs/editors/new-editor.md, docs/editors/overview.md, metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/DelegatingLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsHttpClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, metals/src/main/scala/scala/meta/internal/metals/NoopLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/PositionSyntax.scala, test-workspace/.scalafmt.conf, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/test/scala/tests/BspCli.scala, tests/unit/src/test/scala/tests/FormattingSlowSuite.scala, tests/unit/src/test/scala/tests/StatusBarSlowSuite.scala
The classloading parts have been merged into Scalafmt so they
can be used by all build tools and editor plugins:
https://scalameta.org/scalafmt/docs/installation.html#standalone-library
=> Use scalafmt-dynamic module to simplify formatting implementation.

docs/editors/emacs.md
This PR improves `eglot` documentation for metals. It has been tested locally, to make sure it works.
- Add `scala-mode` setup in `eglot` section.
- Add `sbt-mode` setup in `eglot` section.
- Set `scala-mode` server for `eglot` in `:config` section.
- Use `:hook` feature of `use-package` instead of `add-hook` to automatically start `metals`.
=> Improve eglot documentation

tests/slow/src/test/scala/tests/SbtSlowSuite.scala
Maybe this helps remove flaky tests. Related discussion:
https://github.com/scalameta/metals/issues/435
=> Disable SbtSlowSuite in Appveyor CI.

docs/editors/new-editor.md, metals-docs/src/main/scala/docs/BootstrapModifier.scala
Fixes #454.
I don't think Metals will need more than 100mb even for very large
projects, even after we implement "find references". We remove the
maximum heap size so it can fit the computer's configuration.
=> Lower recommended memory settings.

docs/editors/vim.md, metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala
Fixes #463
- clear status bar with empty text to avoid hanging "Compiling core"
- use 'Log' level to avoid colorful info background
- recommend vim-lsc users to configure log_level `Log`, will be
required once https://github.com/natebosch/vim-lsc/pull/135 is merged.
=> Improve the status bar redirection to window/logMessage

docs/build-tools/new-build-tool.md, metals/src/main/scala/scala/meta/internal/metals/BuildTools.scala, metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLogger.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala, metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala, metals/src/main/scala/scala/meta/internal/metals/Warnings.scala, tests/unit/src/main/scala/tests/BaseSuite.scala
Fixes #425. Fixes #415.
This error can happen for several reasons. Previously, we only reported
a "No SemanticDB" warning but now we try to automatically detect the
most common cases and report more specific advice if possible.
=> Improve "No SemanticDB" error message

metals/src/main/scala/scala/meta/internal/metals/BatchedFunction.scala, metals/src/main/scala/scala/meta/internal/metals/CancelableFuture.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, tests/unit/src/test/scala/tests/BatchedFunctionSuite.scala, tests/unit/src/test/scala/tests/CancelCompileSlowSuite.scala, tests/unit/src/test/scala/tests/CascadeSlowSuite.scala, tests/unit/src/test/scala/tests/CurrentProjectCompileSlowSuite.scala, tests/unit/src/test/scala/tests/UserConfigurationSuite.scala
- cascade compile compiles inverse dependencies of the open buffers.
This is both helpful to see if API changes have compile errors in
downstream projects and is required to implement "find references".
- cancel compile is helpful to clear the compile queue for long-running
compilations.
- we trigger cascade compile on the first compile after build import
because users have an expectation that the CPU is busy during this
period so it's useful to take advantage of it :)
Towards https://github.com/scalameta/metals/issues/338
=> Add "Cascade compile" and "Cancel compile" tasks.

metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/WorkspaceSymbolSlowSuite.scala
Previously, the classpath search included duplicate results for project
sources that were depended on by other build targets in the workspace.
=> Limit classpath search to jars.

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala, test-workspace/src/main/scala/example/User.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/main/scala/tests/TestingWorkspaceSymbolProvider.scala, tests/unit/src/test/scala/tests/WorkspaceSymbolSlowSuite.scala
Fixed #474.  Previously, if you navigated to a library dependency source
via workspace/symbol then you couldn't use "goto definition" from that
source. With this change, we keep track of where workspace/symbol
dependency sources origin from so we can query what build target it came
from.
=> Support navigation for visited dependency sources via workspace/symbol.

metals-bench/readme.md, metals-bench/src/main/scala/bench/Inflated.scala, metals-bench/src/main/scala/bench/ServerInitializeBench.scala, metals/src/main/scala/scala/meta/internal/metals/JvmOpts.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/PackageIndex.scala, metals/src/main/scala/scala/meta/internal/metals/SbtOpts.scala, mtags/src/main/scala/scala/meta/internal/mtags/Mtags.scala, tests/unit/src/main/scala/tests/DiffAssertions.scala
Previously, we indexed the same jars multiple times for
workspace/symbol causing significant slowdown when importing
multi-module builds with large classpaths. With this change indexing the
prisma/server sbt build takes 11.5s instead of 23s.
=> Avoid duplicate classpath indexing.

build.sbt, metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala, metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/StatusBar.scala, metals/src/main/scala/scala/meta/internal/metals/TaskProgress.scala, metals/src/main/scala/scala/meta/metals/Main.scala, tests/slow/src/test/scala/tests/SbtSlowSuite.scala, tests/unit/src/main/scala/tests/BaseSlowSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/CancelCompileSlowSuite.scala, tests/unit/src/test/scala/tests/CascadeSlowSuite.scala, tests/unit/src/test/scala/tests/DiagnosticsSlowSuite.scala, tests/unit/src/test/scala/tests/QuickBuildSuite.scala, tests/unit/src/test/scala/tests/SyntaxErrorSlowSuite.scala
This Bloop release has many improvements:
- no-op compilation still clears fixed errors
- fixed errors cleared faster
- range positions have correct start offsets
- compile progress is reported at 5% intervals
- new --cascade compile option for native cascade compilation
Fixes #470.
Fixes #468.
The new compilation progress for long-running compiles.
=> Upgrade to Bloop v1.2.4

docs/editors/emacs.md
Since https://github.com/rossabaker/lsp-scala/pull/19 , `lsp-scala` does not work with stable `lsp-mode` version.
This PR updates Emacs setup to be up-to-date with the one proposed in `lsp-scala`.
@rossabaker
=> Update Emacs docs

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala, metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala, metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala, metals/src/main/scala/scala/meta/internal/metals/Memory.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, metals/src/main/scala/scala/meta/internal/metals/SbtDigest.scala, metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala, tests/unit/src/test/scala/tests/SbtDigestSuite.scala
While writing a blog post on bloom filters I enountered several small
nits that are fixed here.
- remove --cascade flag, it breaks persistent incremental compile cache
- give Bloop up to 100ms time to complete shutdown
- cleaner logging output for statistics
- don't block workspace/symbol by compilation, only indexing
- bump sbt checksum version
=> Polish before v0.4 release.

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, metals/src/main/scala/scala/meta/internal/metals/DidFocusResult.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, tests/unit/src/main/scala/tests/BaseSlowSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/DidFocusSlowSuite.scala, tests/unit/src/test/scala/tests/InverseDependenciesSuite.scala
Previously, we always triggered a compile on didFocus events. With this
commit, we only trigger a compile on didFocus if the focused path may be
affected by the last compilation.
=> Avoid redundant didFocus compiles, fixes #483.

test-workspace/.jvmopts, test-workspace/build.sbt, test-workspace/src/test/scala/example/UserTest.scala
It previously had unused dependencies and the tests didn't compile.
=> Simplify test-workspace build.

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, tests/unit/src/test/scala/tests/DidFocusSlowSuite.scala
Fixes #497. Previously, we did not trigger didFocus compiles if there
was an ongoing compilation that might affect the focused buffer. This
could results in missing compilation when fixing an error in main and
then instantly focus on a file in tests before the main compilation
finished.
=> Trigger didFocus when current compile may affect focused buffer.

metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala
Fixes #504. The `pluginCrossBuild` setting came in 0.13.17, so currently users get a
compile error when opening older sbt builds on their machine as long as
they have used Metals in at least one sbt 0.13 build. After this commit,
users no longer get a compile error even if they're on an older sbt version. Instead, they the following runtime exception in case they start `sbt` with the environment variable `METALS_ENABLED=true`.
```
[error] java.lang.NoSuchMethodError: sbt.Keys$.pluginCrossBuild()Lsbt/TaskKey;
```
=> Reference pluginCrossBuild via reflection to support older sbt 0.13.

metals/src/main/scala/scala/meta/internal/metals/FileWatcher.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, tests/unit/src/main/scala/tests/BaseSuite.scala, tests/unit/src/test/scala/tests/FileWatcherSlowSuite.scala
The original behavior of the FileWatcher is to create all directories defined in unmanagedSourceDirectories so that it can monitor them for file changes. For example if the project has only a src/main/scala directory, the FileWatcher will create src/main/scala-2.12 and src/main/java. The reason it does this is that it can't monitor changes underneath those directories if they don't exist.
This PR changes that behavior so that it monitors all parents of directories defined in unmanagedSourceDirectories, the events generated arefiltered out if they did not occur under any of the directories in unmanagedSourceDirectories. This way source directories can get created and/or removed we still receive notifications for file changes in them.
=> Change behavior of FileWatcher so that it doesn't create non-existing source directories

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala, mtags/src/main/scala/scala/meta/internal/mtags/DefinitionAlternatives.scala, tests/input/src/main/scala/example/Vars.scala, tests/unit/src/test/resources/definition/example/Vars.scala, tests/unit/src/test/resources/documentSymbol/example/Vars.scala, tests/unit/src/test/resources/expect/toplevels.expect, tests/unit/src/test/resources/mtags/example/Vars.scala, tests/unit/src/test/resources/semanticdb/example/Vars.scala, tests/unit/src/test/resources/workspace-symbol/example/Vars.scala, tests/unit/src/test/scala/tests/ReferenceSlowSuite.scala
Previously, "goto definition" for var setters would jump to the
enclosing class of the var instead of the var itself. Find references
on vars also didn't include locations where the setter was referenced.
=> Fix navigation bug for var setters.

metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/FormattingSlowSuite.scala
Previously, we only looked for `.scalafmt.conf` in the `rootUri`
directory. After this fix, we fallback to `workspaceFolders` if we don't
find a `.scalafmt.conf` file. In the case of formatting, it's not big
trouble to support multiple workspace roots. In the general case it may
be tricker, for example I have no idea how we would handle two separate
sbt builds. We can take it case-by-case.
=> Respect workspace folders for Scalafmt formatting, fixes #509.

build.sbt
It includes a fix for stale diagnostics.
=> Upgrade to Bloop v1.2.5

build.sbt, metals/src/main/scala/scala/meta/internal/metals/SbtDigest.scala, tests/unit/src/test/scala/tests/SbtDigestSuite.scala, website/blog/2019-02-01-tin.md
Semanticdb was out of sync with the scalameta version, causing the 0.4.1 (and 0.4.2) releases not to benefit from the recent semanticdb improvements.
This PR defaults the semanticdb version to the scalameta version, and it does the same for sbt-bloop to bloop following the same logic.
We still keep them separated since it makes it easier to test latest changes while developing.
=> Fix semanticdb version and prepare for 0.4.3 release

docs/editors/emacs.md
emacs lsp-mode use flymake by default.
I felt the need to add this setting. metals emacs document is recommending to flycheck.
=> Update Emacs documentation to recommend flymake instead of flycheck

README.md, build.sbt
Johan has contributed improvements to Metals startup times, file
watching and markdown rendering of javadoc/scaladoc. Thank you!
@mudsam feel free to merge this PR once you have accepted the collaborator invite.
=> Welcome Johan Mudsam to the team!

build.sbt
Previously, the module only published for 2.11.12 and 2.12.8.
=> Cross-publish mtags for all supported Scala versions.

docs/editors/new-editor.md, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/Configs.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java, mtags/src/main/scala/scala/meta/internal/mtags/MtagsEnrichments.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala, mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala, test-workspace/src/main/scala/example/User.scala, tests/cross/src/main/scala/tests/BaseCompletionSuite.scala, tests/cross/src/main/scala/tests/BasePCSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionParameterHintSuite.scala
Previously, completing a method like `println($0)` didn't automatically
trigger parameter hints, which would be really nice in my opinion. This
commit implements infrastructure to allow editors to opt-into triggering
parameter hints after selecting a completion item. We make it work out
of the box with VS Code.
Fixes #551
=> Trigger parameter hints command after completion, if supported.

mtags/src/main/scala/scala/meta/internal/metals/Fuzzy.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionFuzzy.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/Identifier.scala, test-workspace/src/main/scala/example/User.scala, tests/cross/src/main/scala/tests/BaseCompletionSuite.scala, tests/cross/src/main/scala/tests/BasePCSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionBacktickSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
Previously, completions did not correctly handle identifiers that need
to be wrapped in backticks resulting producing code that does not parse.
This commit fixes that issue for all different kinds of completions that
Metals supports, including scope, type members and interpolators.
Fixes #547
=> Wrap identifiers in backticks when necessary.

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
I tried to manually validate the fix by publishing 0.5.0-SNAPSHOT to
sonatype but wasn't able to get it working for some reason. Let's
merge this commit and see if it did the trick after CI has released a
fresh snapshot.
=> Resolve mtags from Sonatype Snapshots, fixes #554.

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
This mirrors the behavior in IntelliJ and fixes an annoying situation
where `List(1).map(_<TAB>)` completes to `_root_`.
Thank you @jvican for reporting!
=> Remove root package from completion results.

docs/editors/overview.md
Atom IDE doesn't have UI for `workspace/symbol`. Metals extensions are partially supported.
=> Update Atom info

metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
Two main changes:
1. When connecting to the bsp server the isOk and onSuccess method have been merged. We try to open the socket and reuse it if the socket is ok. This alleviates the instability issue on Windows and makes the startup faster.
2. When checking if we have an installed bloop we connect to the bloop port instead of firing up the python script. This saves startup time especially on Windows.
There's also a bug fix in the logic of picking the socket type. Previously if we had chosen windows domain socket the code would also try connecting to a unix socket, now it will pick one of the three; windows , tcp or unix socket.
Question, should we add the bloop server port to configuration? Currently it's hard-coded to 8212.
=> Make bloop server startup more robust, reuse sockets wherever possible.

.gitignore, build.sbt, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/Configs.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java, mtags/src/main/scala/scala/meta/internal/mtags/MtagsEnrichments.scala, mtags/src/main/scala/scala/meta/internal/mtags/Symbol.scala, mtags/src/main/scala/scala/meta/internal/pc/CompilerThrowable.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionItemData.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionItemResolver.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/Identifier.scala, mtags/src/main/scala/scala/meta/internal/pc/MemberOrdering.scala, mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala, mtags/src/main/scala/scala/meta/internal/pc/Signatures.scala, test-workspace/src/main/scala/example/User.scala, tests/cross/src/main/scala/tests/BaseCompletionSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionOverrideConfigSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionParameterHintSuite.scala, tests/cross/src/test/scala/tests/pc/PrettyPrintSuite.scala, tests/unit/src/main/scala/tests/BaseCompletionSlowSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/CompletionSlowSuite.scala, tests/unit/src/test/scala/tests/UserConfigurationSuite.scala
This commit implements a new completion feature to override methods from
a supertype.
```scala
new Iterable[Int] {
// before completion
def iterat<COMPLETE>
// after completion
def iterator: Iterator[Int] = ???
}
```
Fixes #540
=> Implement `override def` completions.

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java, mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala, tests/unit/src/main/scala/tests/TestingServer.scala
Previously, we only restarted the presentation compiler for build
targets that successfully compiled. After this commit, we also restart
the pc in the following situations:
- if a transitive dependency build target compiled successfully
- if the current build target failed to compile
This commit also fixes a regression we introduced in a recent PR that
made the tests around configuration flaky.
=> Restart the presentation compile more aggressively.

docs/editors/overview.md, docs/editors/sublime.md
Support for `workspace/symbol` is released for the LSP plugin ([0.8.2](https://github.com/tomv564/LSP/releases/tag/0.8.2))
@olafurpg feel free to change the gif if you like
=> Update Sublime Text doc regarding Goto symbol in workspace

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags/src/main/scala/scala/meta/internal/metals/ClasspathSearch.scala, mtags/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolQuery.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/Signatures.scala, test-workspace/build.sbt, test-workspace/src/main/scala/example/User.scala, test-workspace/src/test/scala/example/UserTest.scala, tests/cross/src/main/scala/tests/BaseCompletionSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala, tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala, tests/mtest/src/main/scala/tests/BaseSuite.scala, tests/mtest/src/main/scala/tests/DiffAssertions.scala, tests/mtest/src/main/scala/tests/TestCompletions.scala, tests/unit/src/main/scala/tests/BaseCompletionSlowSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/CompletionSlowSuite.scala
Previously, Metals inserted a fully qualified name at the completion
position. With this commit, we now insert a local import in the nearest
enclosing block. Down the road, we can add a code action to "Move import
to global scope" to clean up local imports inserted by Metals.
Other improvements in this commit:
- we render the package name in the completion item label so that it's
more visible what you are importing.
- we no longer use insert text, which is a deprected LSP feature and
has unclear semantics between editors. Instead, we only use `textEdit`.
=> Insert local import when completing workspace symbol.

mtags/src/main/scala/scala/meta/internal/pc/CompletionItemResolver.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, test-workspace/src/main/scala/example/User.scala, tests/cross/src/test/scala/tests/pc/CancelCompletionSuite.scala
Previously, we only showed the method signature as "detail", which is
not always visible in editors. This commit moves the method signature
into the label so that it's more prominently displayed. This change
makes it easier to read the completion results, especially for
overloaded methods.
Before:
After:
=> Include method signature in completion item label.

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
These methods are noisy because they appear on everything.
=> Filter out ensuring and -> extension methods from Predef.

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, mtags/src/main/scala/scala/meta/internal/pc/Signatures.scala, test-workspace/src/main/scala/example/User.scala, tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
Previously, auto-import and completions could generate non-compiling
code due to lack of backtick escaping in qualifier paths. With this
commit, we properly escape package names like `type` in backticks
so that the generated code compiles.
=> Escape keyword identifier in packag prefixes.

metals/src/main/scala/scala/meta/internal/metals/Configs.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java, mtags/src/main/scala/scala/meta/internal/pc/CompletionItemResolver.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala, mtags/src/main/scala/scala/meta/internal/pc/SignatureHelpProvider.scala, test-workspace/src/main/scala/example/User.scala
This commits adds three server property settings to disable the features
- `CompletionItem.detail`: because the detail contains duplicate
information from the completion label, which can be annoying in editors
like Sublime where both are displayed next to each other.
- `CompletionItem.documentation`: if the docstring is rendered in noisy
way for some reason.
- `SignatureHelp.documentation`: if the docstring is rendered in noisy
way for some reason.
Here's how the new completions look in Sublime
Previously, the signature was duplicated. Thanks @ayoub-benali for reporting!
=> Add server property config to disable features.

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, tests/cross/src/test/scala/tests/pc/CompletionSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
Now that we include method signatures and fully qualified names in
completion items we need to explicitly set the filter text to avoid
undesirable client-side filter behavior.
Before:
After:
Big thanks to @jvican for reporting!
=> Explicitly set filter text for all completions.

mtags/src/main/scala/scala/meta/internal/pc/SignatureHelpProvider.scala, tests/cross/src/test/scala/tests/pc/SignatureHelpPatternSuite.scala
Previously, signature help (parameter hints) didn't work when
deconstructing a tuple. This commit fixes that bug. The bug happened
because we first perform a syntactic pass where we narrowed to the
synthetic `TupleN.apply(...)` tree node. We now guard against that
pattern so that we show the signature of the enclosing method call.
=> Fix signature help bug for tuple patterns.

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala, metals/src/main/scala/scala/meta/internal/metals/Warnings.scala, tests/unit/src/test/scala/tests/ScalaVersionsSuite.scala
Drop the vendor suffix since unofficial Scala versions are typically
compatible. If there are syntactic incompatibilities as seen with
Typelevel Scala, support for these must be added to SemanticDB.
See also https://github.com/scalameta/scalameta/pull/1846
=> Add support for non-Lightbend compilers

mtags/src/main/scala/scala/meta/internal/pc/SignatureHelpProvider.scala, tests/cross/src/test/scala/tests/pc/SignatureHelpPatternSuite.scala
Previously, we showed `unapply[A, B](x$1: Left[A, B]): Option[A]`
and now we show `unapply(value: A): Some[A]` where `value: A` is the
field on the `Left` case class.
We can still do much better for custom extractors but that can be left
for a separate PR. This is a bugfix.
=> Handle generic unapply signatures in signature help.

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, test-workspace/src/main/scala/example/User.scala, tests/cross/src/main/scala/tests/BaseCompletionSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
See individual commits. We now try to reuse existing braces `{` and parens `(` when possible.
=> Polish snippets when completing with existing parentheses and braces

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java, mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala, mtags/src/main/scala/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala, tests/slow/src/test/scala/tests/DefinitionCrossSlowSuite.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/DefinitionSlowSuite.scala, tests/unit/src/test/scala/tests/HoverSlowSuite.scala
Previously, we only supported navigation inside library dependencies
with Scala version 2.12.8, after this commit it works with all Scala
versions including 2.11.x.
- Supported: definition, hover, signature help
- Not supported: completions, references
Fixes #473
=> Support navigation for library dependencies in Scala versions.

mtags/src/main/scala/scala/meta/internal/pc/HoverMarkup.scala, mtags/src/main/scala/scala/meta/internal/pc/HoverProvider.scala, project/project/plugins.sbt, tests/cross/src/test/scala/tests/hover/HoverNamedArgSuite.scala, tests/unit/src/test/scala/tests/CompletionSlowSuite.scala
Previously, hover used signature help as a fallback when the cursor was
over a named argument. After this commit, we show the method signature
instead. It would be nice to show only the parameter signature in the
future but this is commit is just to fix a bug that resulted in wrong
results.
Fixes #601
=> Remove signature help fallback in hover.

metals/src/main/scala/scala/meta/internal/metals/EmptyScalafmtReporter.scala, metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags/src/main/scala/scala/meta/internal/metals/Testing.scala, tests/mtest/src/main/scala/tests/BaseSuite.scala
This lowers the risk of timing out for the first "format on save" request.
Fixes #544
=> Eagerly load Scalafmt during initialized

build.sbt, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/StatusBar.scala, test-workspace/build.sbt, test-workspace/src/main/scala/example/User.scala, test-workspace/src/test/scala/example/UserTest.scala, tests/unit/src/test/scala/tests/StatusBarSuite.scala
Previously, we waited until the first completion/hover/signatureHelp
request to load the presentation compiler. After this commit, we load
the compiler eagerly and display a "slow task" status with timer so that
it's more clear that we're downloading artifacts from the internet.
Scalafmt also uses slow tasks now, for consistency.
Fixes #543
=> Eagerly load presentation compiler for open buffers.

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
Previously, we always eagerly loaded the presentation compiler to
improve the out-of-the-box experience for new Metals users. However,
this behavior is undesirable for tests because it triggers a lot
of unnecessary computation on every test.
It's generally undesirable to customize the runtime for running tests
but in this particular case I feel it's justified.
=> Don't eagerly load presentation compiler during tests.

mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
Previously, we returned no completions in specific cases due to a null
pointer exception caused by a type error. Now we gracefully handle
type errors so that completions are still returned even when `Tree.tpe`
is null.
=> Handle exceptions when computing completion position.

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, test-workspace/src/main/scala/example/User.scala, tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
Previously, selecting a completion item would remove the trailing
identifier.
```scala
// before
List(1).m@@flatMap { x => Nil }
// after
List(1).map$0 { x => Nil }
```
This behavior was at best buggy and at worst surprising in cases where
it was working as intended.
Now, completions never strip the suffix unless the completed identifier
is identical to the suffix.
```scala
// before
object Foo extends Fut@@ure[Int]
// after
import scala.concurrent.Future
object Foo extends Future$0[Int]
```
Additionally, snippets like `($0)` and `[$0]` are now disabled
when editing inside an existing expression. For example,
```
// before
Syst@@println()
// old behavior
System$0()
// new behavior
System.$0println()
```
=> Improve completion snippets, fixes #610.

metals/src/main/scala/scala/meta/internal/metals/CompilerPlugins.scala, mtags/src/main/scala/scala/meta/internal/pc/CompilerAccess.scala, tests/cross/src/test/scala/tests/pc/MacroCompletionSuite.scala
Previously, we tried to expand macro annotations so that
completions/hover/signatureHelp would take the expanded code in the
current source file into account. This approach didn't work:
- the presentation compiler crashed frequently in macro-paradise
on the second request for completions.
- completions/hover/signatureHelp don't work at all inside macro
expanded code because macroparadise doesn't respect
-Ymacro-expand:discard.
Now with macroparadise disabled, completions work as expected inside a
class with the `@react` annotation in https://github.com/shadaj/slinky.
Note that completions/hover/signatureHelp will continue to take macro
expanded code into account from other source files. It is only for
expanded code in the current open buffer where we won't take macro
expanded signatures …
=> Disable macro-paradise compiler plugin, fixes #622.

mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/MemberOrdering.scala, mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, tests/cross/src/main/scala/tests/BaseCompletionSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
Previously, we sorted global symbols defined in the current file in the
same group as global symbols from the root scope. Now, we priotize
symbols in the current file.
This change has the nice side-effect that `::` no longer appears at the
top of all completions in an empty scope without a prefix.
=> Sort symbols defined in the current file to the top, fixes #618.

mtags/src/main/scala/scala/meta/internal/metals/Fuzzy.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/SignatureHelpProvider.scala, tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSuite.scala, tests/cross/src/test/scala/tests/pc/MacroCompletionSuite.scala, tests/unit/src/main/scala/tests/BaseCompletionSlowSuite.scala, tests/unit/src/test/scala/tests/CompletionSlowSuite.scala
Fixes #620 
Previously, the following completion returned empty results
```scala
class Foo { def getTimeStamp: Int = 42 }
new Foo().time@@
```
Now, the completion results include `getTimeStamp`.
Since we started allowing fuzzier results, we needed better sorting of
completion items in the same category. For example, in the following
example
```scala
class Foo {
def toInt: Int = 42
def instance: Int = 42
def intNumber: Int = 42
}
new Foo().int@@
```
we want the results sorted in the following order
```scala
intNumber // because prefix match
toInt     // because literal substring match
instance  // last fallback
```
This improvement in sorting benefitted non-fuzzy non-type members too.
Previously, the query `Iterator` returned the order
`BufferedIterator,Iterator` because they were sorted …
=> Provide fuzzier type member matching and more polished sorting.

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala, mtags/src/main/scala/scala/meta/internal/metals/PackageIndex.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, tests/cross/src/main/scala/tests/BasePCSuite.scala, tests/unit/src/main/scala/tests/BaseCompletionSlowSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/CompletionSlowSuite.scala
Previously, completions/hover/signatureHelp didn't work in source files
that didn't belong to any build target. Now, we fallback to a 2.12.8
presentation compiler that only has scala-library on the classpath. This
makes it possible to user Metals on source files without a build tool.
Fixes #613
=> Use fallback presentation compiler for missing build target.

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/DocumentHighlightProvider.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags/src/main/scala/scala/meta/internal/mtags/MtagsEnrichments.scala, tests/cross/src/main/scala/tests/pc/BaseHoverSuite.scala, tests/mtest/src/main/scala/tests/RangeReplace.scala, tests/unit/src/main/scala/tests/TestHighlights.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/DocumentHighlightSlowSuite.scala
Previously, we didn't support documentHighlighting from metals lsp server and symbols were only highlighted based on their name.
Now we highlight only the same symbols.
=> Implement textDocument/documentHighlight

mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala
Previously, we sorted named argument `foo =` completions over scope
identifiers with the exact same name as the argument. Now, we sort
exact matching identifiers over named arguments thanks to the new
ability in CompletionPosition to arbitrarily sort completion items.
=> Give CompletionPosition finer control over sorting, fixes #619.

metals/src/main/scala/scala/meta/internal/metals/Directories.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/WorkspaceSearchVisitor.scala, metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala, mtags/src/main/scala/scala/meta/internal/metals/TrigramSubstrings.scala, mtags/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolQuery.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/WorkspaceSymbolSlowSuite.scala
Previously, workspace/symbol often showed too many results from library
dependencies when most of the time you are only interested in symbols
defined in the workspace. Now, workspace/symbol searches only in the
workspace by default. Library dependencies are searches only when
- the search query contains a semicolon character `;`, or
- workspace contains no results
To improve discoverability of this new behavior, we include a dummy
result "Add ';' to search library dependencies".
=> Improve quality and performance of workspace/symbol, fixes #639.

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, tests/cross/src/test/scala/tests/pc/CancelCompletionSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionOverrideConfigSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
Fixes #631. Previously, we needed to write def <COMPLETE> to autocomplete an override, now we can write a start of the 'override' word or a combination of letters in the def/val name and it will trigger the proper completion. When starting with override word it will add it to method even if overriding abstract methods.
Also fixes a bug with not autocompleting when overriding vals from traits.
=> Make completions work on overr<COMPLETE> and def<COMPLETE>

metals-bench/src/main/scala/bench/ClasspathOnlySymbolSearch.scala, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsSymbolSearch.scala, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java, mtags-interfaces/src/main/java/scala/meta/pc/SymbolSearch.java, mtags/src/main/scala/scala/meta/internal/mtags/MtagsEnrichments.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/EmptySymbolSearch.scala, mtags/src/main/scala/scala/meta/internal/pc/HoverProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, mtags/src/main/scala/scala/meta/internal/pc/PcDefinitionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala, project/project/plugins.sbt, tests/cross/src/main/scala/tests/BaseCompletionSuite.scala, tests/cross/src/main/scala/tests/BasePCSuite.scala, tests/cross/src/main/scala/tests/pc/BasePcDefinitionSuite.scala, tests/cross/src/test/scala/tests/pc/PcDefinitionSuite.scala, tests/mtest/src/main/scala/tests/TestingSymbolSearch.scala
Fixes #548. Previously, goto definition worked only for identifiers that
had successfully compiled in the build. Now, goto definition also works
for identifiers that you just typed in the buffer even if you haven't
saved the file.
=> Implement goto definition fallback with the presentation compiler.

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala, mtags-interfaces/src/main/java/scala/meta/pc/DefinitionResult.java, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java, mtags/src/main/scala/scala/meta/internal/pc/DefinitionResultImpl.scala, mtags/src/main/scala/scala/meta/internal/pc/HoverProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, mtags/src/main/scala/scala/meta/internal/pc/PcDefinitionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala, tests/cross/src/main/scala/tests/pc/BasePcDefinitionSuite.scala, tests/cross/src/test/scala/tests/pc/PcDefinitionSuite.scala, tests/mtest/src/main/scala/tests/BaseSuite.scala, tests/slow/src/test/scala/tests/SbtSlowSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/DefinitionSlowSuite.scala, tests/unit/src/test/scala/tests/ReferenceSlowSuite.scala
A last-minute change in 6c501e51b9d0d0937646e01fdc8a25c26372ed2a made
the goto definition fallback integration with LSP no longer work.  This
PR fixes the issue and adds a test to prevent further regressions.
=> Hook goto definition fallback with compiler into LSP.

website/pages/en/index.js
Previously, it showed the hover GIF.
=> Use correct GIF for signature help on landing page.

mtags/src/main/scala/scala/meta/internal/metals/JavadocIndexer.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, tests/cross/src/test/scala/tests/pc/CompletionOverrideConfigSuite.scala
Previously when showing details for overriding it showed unicode mode if it was enabled. Now it shows the full signature to override. The unicode character should only be shown in the list, so that it is easier to read it.
Previously:
Now:
=> Make detail view in override not show unicode character.

docs/editors/new-editor.md, docs/editors/vim.md, metals-docs/src/main/scala/docs/BootstrapModifier.scala, metals-docs/src/main/scala/docs/TextEditorModifier.scala, metals/src/main/scala/scala/meta/internal/metals/Configs.scala, metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, metals/src/main/scala/scala/meta/internal/metals/StatusBarConfig.scala, mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala
closes #650 
There are two things that I couldn't figured out yet so any help will be much appreciated:
- LSP logs at the bottom below the status bar. Messages such as "running bloop install", "compiling foo..", "indexing..." , etc. It worked using `vim-lsc` but I don't know yet how to get it working with `coc.nvim.`
- Folding range: I haven't used this feature but there's a related key mapping: `command! -nargs=? Fold :call     CocAction('fold', <f-args>)`. If anyone has got this working please share your config :pray: 
I replaced the static image of searching Document Symbols with a custom gif I made using `coc.nvim`. Let me know if that's okay or if you guys prefer to leave it blank (the instructions might be enough).
I also excluded the `<tab>` mapping to navigate completions because …
=> Documenting coc.nvim as the recommended LSP client for Vim

docs/editors/vscode.md
Fixes #673. We can add more details to this section, this is just a basic start.
=> Add "Coming from IntelliJ" section to VS Code docs.

metals-bench/src/main/scala/bench/CompletionBench.scala, metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala, metals/src/main/scala/scala/meta/internal/metals/CompilerPlugins.scala, metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala, metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala, metals/src/main/scala/scala/meta/internal/metals/StatisticsConfig.scala, metals/src/main/scala/scala/meta/internal/metals/Trees.scala, tests/unit/src/main/scala/bill/Bill.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/test/scala/tests/BillSlowSuite.scala, tests/unit/src/test/scala/tests/DefinitionSlowSuite.scala, tests/unit/src/test/scala/tests/DiagnosticsSlowSuite.scala
Previously, we could occasionally get in a state where Metals published
stale diagnostics from an old build server.  Now, when we disconnect
from a build server we unpublish the diagnostics from that server. If we
connect to a new server, the errors will get re-published if they are
still relevant.
=> Clear diagnostics on build import, fixes #644.

metals/src/main/scala/scala/meta/internal/metals/DocumentSymbolProvider.scala, tests/input/src/main/scala/example/nested/LocalDeclarations.scala, tests/unit/src/test/resources/definition/example/nested/LocalDeclarations.scala, tests/unit/src/test/resources/documentSymbol/example/Locals.scala, tests/unit/src/test/resources/documentSymbol/example/PatternMatching.scala, tests/unit/src/test/resources/documentSymbol/example/StructuralTypes.scala, tests/unit/src/test/resources/documentSymbol/example/nested/LocalClass.scala, tests/unit/src/test/resources/documentSymbol/example/nested/LocalDeclarations.scala, tests/unit/src/test/resources/expect/toplevels.expect, tests/unit/src/test/resources/mtags/example/nested/LocalDeclarations.scala, tests/unit/src/test/resources/semanticdb/example/nested/LocalDeclarations.scala, tests/unit/src/test/resources/workspace-symbol/example/nested/LocalDeclarations.scala
Before this PR, we would only consider document symbols defined as children of classes, objects, or traits.
This caused interesting symbols not to appear in the editor outline.
For example, consider this (quite common) pattern:
```scala
trait A {
def m(): Unit
}
object A {
def create: A = new A {
def m(): Unit = ()
}
}
```
Prior to this PR, we would show a document symbol for the *declaration* of `m`, but not for its *definition*.
This PR adds document symbols defined in defs, vals, vars, and `new` definitions.
Here's a fairly exhaustive example.
A few things to notice about the anonymous `new` definitions:
- if the template node has >= 1 inits (e.g. `new Foo with Bar {}`) we show `new Foo with Bar` (see the `create` and `createWithLogging` examples in the screenshot above)
- if the …
=> Handle document symbols for nested declarations

mtags/src/main/scala/scala/meta/internal/pc/AutoImports.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, mtags/src/main/scala/scala/meta/internal/pc/Signatures.scala, tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionOverrideConfigSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
Fixes #675. Previously, workspace completions inserted local imports,
which requires a lot of manual work to move local imports into the
toplevel. Now, completions insert imports at the toplevel in the
global scope.
Note that this implementation has the following known limitations:
- inserted imports make no effort to respect the existing coding style
with respect to blank lines, import ordering or grouping with curly
braces.
- inserted imports may break code in other scopes where the same
identifier is referenced via a local wildcard import.
=> Insert global imports instead of local imports.

metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/DiagnosticsSlowSuite.scala, tests/unit/src/test/scala/tests/WorkspaceSymbolSlowSuite.scala
Fixes #693.
Previously, renaming a file would cause workspace/symbol to return
duplicate results: one result for the new file and one result for the
deleted file. Now, we filter out results for deleted files.
=> Don't return workspace/symbol results for deleted files.

build.sbt, docs/contributors/getting-started.md, docs/editors/overview.md, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala, metals/src/main/scala/scala/meta/internal/metals/Warnings.scala, tests/unit/src/main/scala/tests/BaseSlowSuite.scala, tests/unit/src/test/resources/semanticdb/example/StructuralTypes.scala, tests/unit/src/test/resources/semanticdb/example/nested/LocalDeclarations.scala, tests/unit/src/test/scala/tests/CancelCompileSlowSuite.scala, tests/unit/src/test/scala/tests/DidFocusSlowSuite.scala, tests/unit/src/test/scala/tests/WarningsSlowSuite.scala
- Fixes #699
- Fixes #697
While improving the warning messages for deprecated Scala versions I
additionally improved the output of the doctor to show more helpful
information:
- add new columns to table of features: completions, find references
- show custom message if there are no build targets in the workspace
=> Upgrade to latest Scalameta.

build.sbt, metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala, metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala, metals/src/main/scala/scala/meta/internal/metals/FileWatcher.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/Tables.scala, metals/src/main/scala/scala/meta/internal/metals/ThreadPools.scala, mtags/src/main/scala/scala/meta/internal/pc/InterruptException.scala, mtags/src/main/scala/scala/meta/internal/pc/SignatureHelpProvider.scala, tests/cross/src/main/scala/tests/BaseSignatureHelpSuite.scala, tests/slow/src/test/scala/tests/SbtSlowSuite.scala, tests/unit/src/main/scala/tests/QuickBuild.scala, tests/unit/src/test/scala/tests/BuildServerConnectionSlowSuite.scala, tests/unit/src/test/scala/tests/ReferenceSlowSuite.scala, tests/unit/src/test/scala/tests/WarningsSlowSuite.scala
- bump local publish version to 0.6.0-SNAPSHOT
- upgrade lsp4j dependency
- make "connect to build server" more robust to errors
- drop support for deprecated Scala versions
- avoid log messages with noisy stack traces when running full test
suite.
- fix potential flakiness issues in ReferenceSlowSuite
=> Miscellaneous improvements

docs/editors/vim.md
I noticed that the blocking form of manually importing a build could result in a completely unresponsive UI for an extended period of time. Simply changing to the async version of the call works (for me) and is a much more pleasant user experience.
=> Use CocRequestAsync in Vim docs

metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala, tests/slow/src/test/scala/tests/GradleSlowSuite.scala
Previously, when scala dependency in Gradle project was specified transitively it was not picked and used for the semanticDB plugin.
Now we look through all dependencies in order to properly search for scala library.
=> Fix transitive scala library dependency in Gradle builds.

docs/editors/sublime.md
Metals is now a default server in the LSP package since https://github.com/tomv564/LSP/pull/571 and a [release](https://github.com/tomv564/LSP/releases/tag/0.8.3) have been made.
So no need to configure it anymore.
=> Update sublime doc

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala, metals/src/main/scala/scala/meta/internal/metals/BuildTargetClasses.scala, metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala, metals/src/main/scala/scala/meta/internal/metals/CodeLensProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Command.scala, metals/src/main/scala/scala/meta/internal/metals/Compilations.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, tests/unit/src/main/scala/tests/CodeLensesTextEdits.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/CodeLensesSlowSuite.scala
Previously, metals did not provide any code lens for running the main classes.
Now, we have the whole infrastructure for providing those code lenses set up. We will just have to enable them once we can actually run the main classes.
When this is merged, #652 should be updated to reflect the need of enabling this feature
=> Implement textDocument/codeLens to run main function

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/metals/FileWatcher.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, tests/cross/src/test/scala/tests/pc/CompletionFilenameSuite.scala
- clear diagnostics on file delete events
- don't crash completions when editing the last character in a file
- don't display "$(sync)" for "Downloading Bloop" message
=> Miscellaneous polish fixes

website/blog/2019-04-26-mercury.md
=> Fix blogpost typo

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLogger.scala, tests/unit/src/main/scala/bill/Bill.scala, tests/unit/src/test/scala/tests/BillSlowSuite.scala
Previously, we risked connecting to a new build server before completing
the shutdown for the old build connection resulting in the following
sequence of requests:
```
metals ---shutdown----> bloop (old connection)
metals ---initialize--> bloop (new connection)
metals <--shutdown----- bloop (old connection)
```
Now, Metals waits for the `shutdown` response from the old connection
before sending `initialize` for the new connection.
This bug was introduced by a recent refactoring of how we shut down
the build server connection. This commit adds a new test case to
prevent similar regressions in the future.
=> Ensure build server shuts down before starting new build connection.

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
Previously we could download a wrong version of scala-compiler as a transitive dependency, now we make sure we have the right one.
=> Enforce scala version for embedded bloop server

metals/src/main/scala/scala/meta/internal/metals/BatchedFunction.scala, metals/src/main/scala/scala/meta/internal/metals/BuildTargetClasses.scala, metals/src/main/scala/scala/meta/internal/metals/CancelableFuture.scala, metals/src/main/scala/scala/meta/internal/metals/Compilations.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/Pauseable.scala, metals/src/main/scala/scala/meta/internal/metals/WindowStateDidChangeParams.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/BatchedFunctionSuite.scala, tests/unit/src/test/scala/tests/WindowStateDidChangeSlowSuite.scala
Closes #668. Previously, Metals would continue to run compile-on-save even if the editor application window was not focused. For example, checking out a different branch in the terminal would immediately trigger compilation in Metals.
Now, editors can send a new `metals/windowStateDidChange` notification to express when the editor window is in focus and out of focus. When the editor window is out of focus, Metals pauses compile-on-save changes until the window is re-focused.
=> Pause compile-on-save while the editor window is not focused

build.sbt, docs/contributors/getting-started.md
Previously, contributors needed to manually run scalafmt and scalafix
when opening pull requests in order to make the CI green. Now, we
automatically install git hooks so that scalafmt and scalafix are always
run before pushing a commit.
To speed up the `sbt scalafixAll` command, we use the experimental
`-client` flag which delegates the command to a running sbt server
instance if one exists. In my local experiments, this makes the pre-push
hooks run in ~5 seconds if the project is already compiled.
Related to #672
=> Setup git hooks for scalafmt and scalafix.

build.sbt, docs/contributors/getting-started.md
The `sbt -client` command was timing out on Linux.
=> Remove Scalafix from pre-push git hook.

metals/src/main/resources/millw, metals/src/main/resources/millw.bat, metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala, metals/src/main/scala/scala/meta/internal/builds/Digest.scala, metals/src/main/scala/scala/meta/internal/builds/GradleDigest.scala, metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/MillDigest.scala, metals/src/main/scala/scala/meta/internal/builds/SbtDigest.scala, metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala, metals/src/main/scala/scala/meta/internal/metals/Configs.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, tests/slow/src/test/scala/tests/MillSlowSuite.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/test/scala/tests/MillDigestSuite.scala, tests/unit/src/test/scala/tests/RelatedSuite.scala
Previously mill builds would have to be imported manually via bloop and now we add automatic mill import to metals whenever the workspace is detected.
Also, moved build tools digest calculation to separate files.
=> Add automatic Mill import to metals

docs/build-tools/gradle.md, docs/build-tools/maven.md, docs/build-tools/mill.md, docs/build-tools/overview.md, metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
Previously we recommended rerunning another import for maven workspaces, which would not help. Now we include a link to the full documentation
We will need to add a full documentation during the release - will take care of it.
=> Add better hint in the doctor for Maven workspaces

metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala, metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/MavenBuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala, metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, tests/slow/src/test/scala/tests/BaseImportSuite.scala, tests/slow/src/test/scala/tests/GradleSlowSuite.scala, tests/slow/src/test/scala/tests/MavenSlowSuite.scala, tests/slow/src/test/scala/tests/MillSlowSuite.scala, tests/slow/src/test/scala/tests/SbtSlowSuite.scala, tests/unit/src/main/scala/tests/TestingClient.scala
Previously tool names and executable names were not differentiated, now we make sure they are correctly written.
I think this is the last PR I want to merge before release.
=> Fix names to be uppercase when needed

docs/contributors/releasing.md, website/i18n/en.json, website/sidebars.json
I've completely missed the `RELEASING.md` document today when I was looking on info for making the release. I think having it on the website alongside the rest of the contributors' docs makes more sense. /cc @olafurpg @tgodzik
=> Move releasing info to the website

docs/editors/sublime.md
I found that I needed to open a Scala file before LSP would prompt me to "Import Changes". I added a clarifying sentence to the Sublime documentation to explain this.
I ran the website locally and verified changes were present.
=> Added clarification to the sublime documentation

mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala
Previously, triggering completions on a type that had recursive type
aliases would make Metals get stuck in an infinite loop. Now, we prevent
infinite loops by adding a cache to what types we have tried to shorten.
=> Avoid inifinite loop when shortening types, fixes #749.

metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
in `def textDocument`, `textDocumentCache.computeIfAbsent` calls `compile` which modifies `textDocumentCache`, java 8 fails to detect this but java 11 detects correctly.
=> Fix concurrent modification

metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala
Previously we searched classpath for plugin splitting on ':', which didn't work on Windows.
Now, we use the files collection on the configuration and search it.
=> Fix wrong windows SemanticDB file path

metals/src/main/scala/scala/meta/internal/builds/SbtDigest.scala, tests/unit/src/test/scala/tests/SbtDigestSuite.scala
As agreed on gitter, only .sbt files should be digested at workspace level
=> Digest only sbt files at workspace level

metals/src/main/scala/scala/meta/internal/metals/BloopSocket.scala, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags/src/main/scala/scala/meta/internal/metals/PackageIndex.scala, mtags/src/main/scala/scala/meta/internal/mtags/ClasspathLoader.scala, mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala, tests/cross/src/main/scala/tests/BasePCSuite.scala, tests/cross/src/test/scala/tests/pc/HKSignatureHelpSuite.scala, tests/unit/src/main/scala/bill/Bill.scala, tests/unit/src/main/scala/tests/BaseExpectSuite.scala
This updates https://github.com/scalameta/metals/pull/739, tests still fail on java11, but no longer from  `Caused by: java.lang.NoClassDefFoundError: javax/tools/ToolProvider`
```
sbt:default-40f014> unit/testOnly -- tests.DocumentHighlightSlowSuite.single
[info] Compiling 1 Scala source to /c/Users/Eric Peters/IdeaProjects/metals/metals/target/scala-2.12/classes ...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/c/Users/Eric%20Peters/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.8/4.1.9/semanticdb-scalac_2.12.8-4.1.9.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use …
```
=> Factor out a ClasspathLoader.getURLs(classLoader) helper for java9+ compatability, update usages

metals/src/main/scala/scala/meta/internal/metals/DocumentSymbolProvider.scala, tests/input/src/main/scala/example/Miscellaneous.scala, tests/unit/src/test/resources/definition/example/Miscellaneous.scala, tests/unit/src/test/resources/documentSymbol/example/Miscellaneous.scala, tests/unit/src/test/resources/mtags/example/Miscellaneous.scala, tests/unit/src/test/resources/semanticdb/example/Miscellaneous.scala, tests/unit/src/test/resources/workspace-symbol/example/Miscellaneous.scala
Fixes https://github.com/scalameta/metals/issues/760.
The issue is that `val _ =` was not added since it has no symbol and the body was actually empty.
=> Fix an issue when `val _ = ()` is the only thing in the block

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/DefinitionSlowSuite.scala, tests/unit/src/test/scala/tests/QuickBuildSuite.scala
This PR adds a feature that fallbacks to "show usages" from "goto definition" if the symbol at the given text document position represents a definition itself, which is proposed in https://github.com/scalameta/metals/issues/755.
Now, Metals returns the reference locations instead of definition location for `textDocument/definition` if the symbol at the given text document position represents the definition itself.
In this recording, I used only "go to definition".
<details>
<summary>Here's the pieces of JSON RPC logs while recording</summary>
```
{
"jsonrpc": "2.0",
"id": 51,
"method": "textDocument/definition",
"params": {
"textDocument": {
"uri": "file:///home/tanishiking/dev/src/github.com/tanishiking/metals/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala" …
```
=> Fallback to "show usages" from "Goto definition" if the symbol represents a definition itself

mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, tests/cross/src/test/scala/tests/hover/HoverNamedArgSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
Working on https://github.com/scalameta/metals/issues/753
`TypeRef(NoPrefix, sym, Nil)` cuases us to include parent object, which i turn breaks auto importing. Checking if I didn't break anything in the process.
@gabro Did you mean something like this?
=> Fix importing nested objects

mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala
`JAVA_HOME` is an environment variable and `System.getProperty("JAVA_HOME")` seems always return `null`.
`JdkSources` had been working correctly because `candidates` [deals with `java.home` system property properly](https://github.com/scalameta/metals/blob/cee748a957645b2e0b6ad8ae5762624754631069/mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala#L30-L32).
- https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html
- https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#getProperty-java.lang.String-
=> Fix JdkSources not to ignore JAVA_HOME environment variable

mtags/src/main/scala/scala/meta/internal/pc/AutoImports.scala, tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala
Previously when using imports with braces in the last import position auto imports would be added to a wrong place.
Now in case of braces we search for the closing brace and add the import afterwards.
Fixes https://github.com/scalameta/metals/issues/783
=> Make sure we add an autoimport in the correct line

mtags/src/main/scala/scala/meta/internal/pc/SignatureHelpProvider.scala, tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala
Previously, running parameter hints after the closing parenthesis in
`List(1)@@` or between curried arguments `Option(1).fold(1)@@(_ + 1)`
would trigger a false-positive signature help (resulting in noisy
popups). Now, we exclude the last characters such as closing `)` and
`]` to avoid returning parameter hints when the cursor is not inside
the argument position.
Thanks to Sébastien Doeraene (@sjrd) for catching this bug!
=> Fix off-by-one for parameter hints.

metals-bench/src/main/scala/bench/MetalsBench.scala, metals/src/main/scala/scala/meta/internal/metals/Trees.scala, mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala, tests/unit/src/test/scala/tests/SyntaxErrorSlowSuite.scala
Fixes #787 
This PR switches to the 2.13 Scalameta dialect for parsing buffers.
It's important to notice that we always the 2.13 dialect even for 2.12 or 2.11 builds, which means that in this case:
```scala
val x: Option["lit"] = Some("lit")
```
we won't be reporting an error as you type for 2.12 / 2.11 builds.
The error is still reported after compilation (i.e. on file save) so this should be an acceptable compromise.
=> Use 2.13 dialect for syntax errors

metals-bench/readme.md, metals-bench/src/main/scala/bench/ClasspathIndexingBench.scala
Previously, we only benchmarked the performance for responding to search
queries but not the time it took to build the classpath index. Metals
builds the classpath index quite frequently so this commit introduces a
new benchmark to measure the time it takes to index a ~200mb classpath
containing.
Related #792
=> Add a benchmark for classpath indexing performance.

build.sbt, metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
Added `might` in order not to scare 2.11 people too much.
=> Fix an issue with wrong deprecation warning for 2.11 and update snapshot version

bin/test-release.sh, docs/contributors/releasing.md
Previously, we used the `-r sonatype:public` resolver by default which
passed even if the artifacts hadn't synced t Maven Centra. This resulted
in many users getting resolution errors if they updated Metals right
after the release announcement (which is easy to do with VS Code
auto-update).
=> Make test-release.sh script check that artifacts have synced to Maven

appveyor.yml, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala
Previously, completions after a comment and newline would yield no results.
Now we remove the comment from the name that PC gives us and this causes us to get all completions.
This is connected to a presentation compiler bug that would include comment as a legal identifier. We will try to fix that inside the compiler - the implementation here might not be most efficient, but it only happens in case of comments.
Fixes https://github.com/scalameta/metals/issues/813
=> Fix issue with missing completions after comment and newline.

metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
Mill 0.4.2 is the first version that supports scala 2.13.0.
=> Bump mill version

metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
This fixes incorrect messaging in Metals Doctor. When Scala version is 2.13.0, it currently recommends "Upgrade to Scala 2.12.8 to enjoy the latest compiler improvements".
=> Update the list of supported Scala binary versions

docs/build-tools/gradle.md, docs/build-tools/maven.md
Fixes https://github.com/scalameta/metals/issues/819
=> Fix versions in docs - wrong number of @ was used

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
A last minute change in the Tree View PR to fix a navigation bug when
browsing library dependenency sources from the tree view resulted in a
performance regression when editing standalone Scala files.
Previously, we tried to infer the build target using an expensive
classloading technique on every completion/hover/signatureHelp request
in standalone files. Now, the expensive technique is only used for files
in the `.metals/readonly` directory.
=> Don't infer build target for non-readonly files.

build.sbt, tests/unit/src/test/scala/tests/FormattingSlowSuite.scala
=> Use Scalafmt 2.0.0 when setting the version in .scalafmt.conf

metals/src/main/scala/scala/meta/internal/metals/Tables.scala
Not a great style, but the properties API isn't super great.
=> Setting h2.bindAddress to avoid exposing open ports

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, tests/slow/src/test/scala/tests/SymlinkedProjectSuite.scala, tests/unit/src/main/scala/tests/BaseSlowSuite.scala, tests/unit/src/main/scala/tests/FileLayout.scala
Previously, we were using paths from the clients without resolving symlinks to real paths. 
This made resolving build targets impossible whenever workspace or one of its ancestors were a symlink.
Now, we dealias paths coming from the client.
closes #823
=> resolve symlinks from client requests

metals/src/main/scala/scala/meta/internal/builds/Digests.scala, metals/src/main/scala/scala/meta/internal/metals/ChosenBuildServers.scala, metals/src/main/scala/scala/meta/internal/metals/Configs.scala, metals/src/main/scala/scala/meta/internal/metals/DismissedNotifications.scala, metals/src/main/scala/scala/meta/internal/metals/Time.scala, tests/unit/src/main/scala/tests/FakeTime.scala, tests/unit/src/test/scala/tests/DigestsSuite.scala
`nanoTime` is not actually time in nanos from 1970, but is used to measure difference. So all timestamps would be quite random since they can repeat themselves. We can't use them as timestamps for sure.
Also add pom.xml to be watched, since I must have forgot about it previously.
=> Timestamps should use currentTimeMillis 

mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, tests/cross/src/test/scala/tests/pc/CompletionBacktickSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
Fix multiline edits by switching from long single edit to multiple edits in the document.
Long edits spanning multiple lines are not supported by some of the LSP clients.
Fixes https://github.com/scalameta/metals/issues/774
=> Fix multiline edits

docs/editors/emacs.md
Updated installation section for `lsp-mode` and `eglot`.
`(require 'package)` is needed else it throws error.
=> Install use-package if not already installed

tests/unit/src/test/scala/tests/TreeViewSlowSuite.scala
The test seems to have a random number of libraries shown, which is pretty weird.
I added the exact current libraries to see next time what changes.
=> Add exact libraries that are expected and fix the test

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala
Previously Metals was directories with names starting with `jdk` as proper jdk home candidates.
Now, we consider those **containing** `jdk`, since java-8-openjdk would obviously fail the test.
Also, we notify the user that the sources were not found and that the java symbols will not be available.
=> Improve handling of the java sources

docs/editors/overview.md
With the new [release](https://github.com/tomv564/LSP/releases/tag/0.8.5) of LSP, auto import for sublime now works thanks to @tomv564
=> Update sublime doc regarding autoimport

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
Previously we would report that SemanticDB file does not exist in case when symbol was correctly not found (Ctrl on an empty place), now we check if SemanticDB really exists.
=> Report an issue only if SemanticDB file doesn't really exist.

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, metals/src/main/scala/scala/meta/internal/metals/FileWatcher.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags/src/main/scala/scala/meta/internal/mtags/ListFiles.scala, mtags/src/main/scala/scala/meta/internal/mtags/MtagsEnrichments.scala, tests/unit/src/main/scala/tests/QuickBuild.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/DiagnosticsSlowSuite.scala, tests/unit/src/test/scala/tests/FileWatcherSlowSuite.scala
Fixes #770
Reopened the PR here. I fixed the suggestions:
- added a file watcher which only reports on the specific file
- if a source file item does not exist we then create the parent dir and watch it then delete it afterwards as with the source directories
- renamed isSourceItem to isSource
=> Add support for non-directory sources

.scalafmt.conf, build.sbt, tests/unit/src/test/scala/tests/FormattingSlowSuite.scala
I just released scalafmt v2.0.1 that contains the [change](https://github.com/scalameta/scalafmt/pull/1467) which fixes https://github.com/scalameta/scalafmt/issues/1442
Some tests are failing, but they seem to have nothing to do with this change.
=> Update scalafmt to 2.0.1

tests/unit/src/test/scala/tests/TreeViewSlowSuite.scala
This should fix the current failures, but it's definitely not permanent, given the nature of the fix.
Any idea on how to make these more stable, @tgodzik / @olafurpg?
=> Fix TreeViewSlowSuite tests

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala, mtags/src/main/scala/scala/meta/internal/mtags/MtagsEnrichments.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/test/scala/tests/AddPackageSlowSuite.scala
Implements https://github.com/scalameta/metals/issues/860
=> Automatically add package declaration when creating a file

metals/src/main/scala/scala/meta/internal/metals/DocumentHighlightProvider.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/OnTypeFormattingProvider.scala, tests/unit/src/main/scala/tests/TestMultilineStrings.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala
Partially solves #859. Doesn't work for copypasted strings yet, though.
The behaviour isn't identical to that demonstrated in gifs under issue #859. For now, before making a TextEdit, Provider checks whether there was a pipe in the last line, even, if it's the first line of the string. It doesn't yet add .stripMargin after the end of the string, either. So we might want to expand on that.
=> Insert pipe character when editing multiline strings

build.sbt, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
Fixes #868 
Same as https://github.com/scalameta/metals/pull/871, but open against the right repo.
=> Make presentation compiler work on 2.12.9

mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala
> ⚠️ This is a test, to see how the CI likes it.
Early initializers are deprecated in 2.13 in favor of trait parameters (landing in
2.14). For the time being, we replace them using an intermediate class
workaround
=> Remove use of early intializers

build.sbt, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala, tests/cross/src/main/scala/tests/BasePCSuite.scala, tests/mtest/src/main/scala/tests/BaseSuite.scala, tests/unit/src/main/scala/bill/Bill.scala, tests/unit/src/main/scala/tests/Library.scala
Previously, we used `scala.util.Properties.versionNumberString`
to find the current Scala version of the running classloader. This
approach had the problem where we would pick up a more recent Scala
version than expected. For example, the Metals server depended on an
`mtags_2.12.8.jar` and `scala-library_2.12.jar` (compiled by 2.12.9)
causing `Properties.versionNumberString` to return "2.12.9" instead of
the expected "2.12.8".
Now, we use a `BuildInfo.scalaCompilerVersion` that is generated by the
build to ensure we get "2.12.8" even if scala-library.jar on the
classpath comes from 2.12.9.
Fixes #868.
=> Use BuildInfo.scalaCompilerVersion over Properties.versionNumberString

metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala, metals/src/main/scala/scala/meta/internal/builds/Digest.scala, metals/src/main/scala/scala/meta/internal/builds/GradleDigest.scala, metals/src/main/scala/scala/meta/internal/builds/MavenDigest.scala, metals/src/main/scala/scala/meta/internal/builds/SbtDigest.scala, metals/src/main/scala/scala/meta/internal/metals/BspServers.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/tvp/ClasspathSymbols.scala, mtags/src/main/scala/scala/meta/internal/metals/PackageIndex.scala, mtags/src/main/scala/scala/meta/internal/metals/RecursivelyDelete.scala, mtags/src/main/scala/scala/meta/internal/mtags/ListFiles.scala, mtags/src/main/scala/scala/meta/internal/mtags/MtagsEnrichments.scala, mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala, mtags/src/main/scala/scala/meta/internal/mtags/WalkFiles.scala, project/plugins.sbt, tests/unit/src/main/scala/tests/QuickBuild.scala, tests/unit/src/main/scala/tests/TestingServer.scala
Should fix a bug reported on Gitter https://gitter.im/scalameta/metals?at=5d68316b2f10da7cb357a62e
Would be good to include this fix in the upcoming release
cc/ @several27
=> Avoid file leaks when digesting Gradle builds

metals/src/main/scala/scala/meta/internal/builds/GradleDigest.scala, metals/src/main/scala/scala/meta/internal/builds/SbtDigest.scala, mtags/src/main/scala/scala/meta/internal/mtags/ListFiles.scala
This fixes the issue that we had when not closing streams when looking for subdirectories. 
We might add same method to WalkFiles and simplify a lot of the code. I don't really think we need a whole new library here.
=> Fix not closing streams when using Files.list

mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala
I talked around in the office and someone said it would be useful to have something that autofills named parameters. After tinkering a bit with possibilities I come up with:
What does anyone think? I was pretty easy to implement, but not sure about the ideal functionality.  I am not sure about default arguments.
All suggestions are welcome.
=> Add automatic value completions on named arguments

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
Found two issues with how we create presentation compiler:
- we don't check if semanticDB version in scalac options is a correct one
- when downloading dependencies for PC we don't make sure correct Scala compiler version is downloaded
This should fix both.
=> Fix more possible presentation compiler classpath issues

build.sbt, metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala, project/build.properties, sbt
Let's give this a spin.
I've also taken the chance to upgrade the `recommendedVersion` in `SbtBuildTool`
=> Update sbt to 1.3.0

metals/src/main/scala/scala/meta/internal/builds/Digest.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/OnTypeFormattingProvider.scala, tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala
Fixes https://github.com/scalameta/metals/issues/893
=> Check for stripMargin when adding |

project/plugins.sbt
Now, `sbt ci-release` will automatically close stale staging
repositories.
=> Upgrade to latest sbt-sonatype for faster and more stable releases

build.sbt, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
Seems that it was not neccessary. @olafurpg can you confirm? No tests seem to fail.
Fixes https://github.com/scalameta/metals/issues/920
=> Remove dealias to properly support type

build.sbt, metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala
Seems this got a bit broken in the last PR when used in VS Code. Should work properly now.
=> Fix indentation when adding pipes in multiline string.

tests/unit/src/test/scala/tests/ReferenceSlowSuite.scala
Flaky tests cause more harm than good to the project. This test case was failing the CI for #907
=> Disable flaky test.

metals/src/main/scala/scala/meta/internal/metals/DocumentSymbolProvider.scala, tests/input/src/main/scala/example/TryCatch.scala, tests/unit/src/test/resources/definition/example/TryCatch.scala, tests/unit/src/test/resources/documentSymbol/example/TryCatch.scala, tests/unit/src/test/resources/expect/toplevels.expect, tests/unit/src/test/resources/mtags/example/TryCatch.scala, tests/unit/src/test/resources/semanticdb/example/TryCatch.scala, tests/unit/src/test/resources/workspace-symbol/example/TryCatch.scala
Fixes https://github.com/scalameta/metals/issues/879
Edit: Removed the additional block, it could be problematic to present in some clients
=> Make sure we continue searching for symbols in try.

mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala
- alternatives now start with ???
- it only shows up when using named parameters or is explicitly called
- doesn't auto-fill default arguments
After suggestion from @olafurpg  also:
- add subtypes as valid values
=> Refactor autofill option

metals/src/main/scala/scala/meta/internal/metals/DocumentSymbolProvider.scala, tests/unit/src/test/resources/documentSymbol/example/StructuralTypes.scala, tests/unit/src/test/resources/documentSymbol/example/TypeParameters.scala
I was looking earlier through the available SymbolKind and I think this makes more sense when it comes to `Type`
=> Swap field to type parameter for scala Type

README.md
All ENSIME repos have been archived and a notice has been placed on the website advising everybody to use Metals: https://ensime.github.io/
Therefore, ENSIME is not an alternative.
=> ENSIME is not an alternative

bin/test-release.sh, build.sbt, mtags/src/main/scala-2.13/scala/meta/internal/pc/Compat.scala, mtags/src/main/scala/scala/meta/internal/pc/Keywords.scala, sbt, tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala, tests/cross/src/test/scala/tests/pc/MacroCompletionSuite.scala
Getting things ready.
As soon as 2.13.1 is out, we need to merge https://github.com/scalameta/scalameta/pull/1901, backpublish Scalameta 4.2.3 for 2.13.1 and then we can test this one.
=> Add support for 2.13.1

.github/workflows/ci.yml, azure-pipelines.yml, mtags/src/main/scala/scala/meta/internal/metals/PackageIndex.scala, tests/unit/src/test/scala/tests/TreeViewSlowSuite.scala
On GitHub Actions we have OpenJDK 8 installed, which doesn't have issues with the nuprocess library that we're using. The tests in https://github.com/scalameta/metals/pull/942#issuecomment-535468094 are failing because Azure uses Zulu JDK which doesn't support the same JNA APIs that are used by nuprocess.
=> Replace Azure pipelines with GitHub Actions

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, tests/unit/src/main/scala/tests/QuickBuild.scala, tests/unit/src/test/scala/tests/BuildTargetsSlowSuite.scala, tests/unit/src/test/scala/tests/DiagnosticsSlowSuite.scala, tests/unit/src/test/scala/tests/FileWatcherSlowSuite.scala
Previously, if two build targets in the repo were eligible for a source
file, Metals would sometimes prioritize a target with an unsupported
Scala version over a target with a supported Scala version. This
resulted in completions/hover/parameterHints not to work while editing
cross-built sources.
This PR introduces a change to the logic where we select a build target
for a given source file. Now we sort the elibible candidates by two
criteria: the Scala version and the platform (JVM/JS/Native). This
change takes the first step towards
https://github.com/scalameta/metals-feature-requests/issues/13, which is
about making this logic configurable.
=> Prioritize build targets with supported Scala versions.

metals/src/main/scala/scala/meta/internal/metals/FileWatcher.scala, tests/unit/src/main/scala/bill/Bill.scala
The Scala compiler supports a feature where it compiles the output
classfiles directly to `*.jar` files. This feature is used in build
tools like Pants and Bazel.
Previously, Metals would crash on build targets that used this feature
of the compiler. Now, we don't do anything even if it means missing file
watching notifications that are needed for the "find symbol references"
index.
Thank you @illicitonion for reporting this issue!
=> Don't file watch inside jar files.

build.sbt
See https://github.com/sbt/sbt-buildinfo/issues/152 for a discussion on
how sbt-buildinfo uses the same target directory for compiling a project
across different Scala versions. Sharing the target directory is safe
under normal usage of the sbt task engine but it's risky when using
`State`. An example of a failed CI job caused by this bug is
https://travis-ci.org/scalameta/metals/jobs/590512863
This commit reduces the risk of race conditions during sbt-buildinfo
code generation by forcing the `publishLocal` steps for Scala 2.11 and
Scala 2.13 to run synchronously, instead of in parallel.
=> Avoid race conditions during slow/test command.

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala
Previously: In some cases Metals crashed on openhtmltopdf jars if they contain /Users directory or at any other entry without attributes.
Now: It doesn't - it displays warning instead.
=> Warn when a source jar is corrupted

docs/build-tools/gradle.md, docs/build-tools/maven.md, docs/build-tools/mill.md, docs/build-tools/sbt.md
After the next release I will remove the old instructions, since they will no longer be needed.
However, currently the instructions differ if you use snapshots.
Fixes https://github.com/scalameta/metals/issues/958
=> Change manual instalation section for sbt, gradle and maven

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala, metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala, tests/unit/src/test/scala/tests/ImplementationSuite.scala
=> Fall back to mtags position occurrences

metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala, metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala, tests/slow/src/test/scala/tests/sbt/SbtSlowSuite.scala
=> Add .bloop and .metals paths to gitignore automatically

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/DocumentHighlightProvider.scala, tests/unit/src/main/scala/tests/TestingServer.scala
=> Enable goToDefinition when cursor is at end of symbol

metals/src/main/scala/scala/meta/internal/metals/Warnings.scala
Previously, we reported a warning "No SemanticDB" in the status bar when
Metals couldn't find a SemanticDB file for a given source file. Now, we
only log the warning without updating the status bar because this
problem is quite harmless in most situations.
It's difficult to say what the root cause of this problem, my theory is
that it happens in some of the following cases:
- new Bloop BSP connection with an empty class directory
- git checkout to a new branch where new files got added and the file
hasn't been compiled yet.
Either way, it's not the end of the world when the SemanticDB file
doesn't exist. Most functionality including completions, type at
point,parameter hints and goto definition should continue to work.
cc/ @bishabosha
=> Tone down "No SemanticDB" warning

metals-docs/src/main/scala/docs/GenericModifier.scala, metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala, metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala, tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala
Previously, we automatically added metals files to gitignore, now we leave it to the user to decide.
Turns out most people are either opposed to this change or have a different opinion on how it should work, so we decided not to introduce this altogether.
Fixes https://github.com/scalameta/metals/issues/966
=> Remove automatic gitignoring.

docs/editors/emacs.md
it seems that the regex of the docu for the scala-mode is too much general for emacs so swap files (starting with .#) are compiled by metals and this one crashes, throwing a runtime exception, when the swap file is not there
this new regex is maybe too restrictive but seems to be valid for most of usecases
=> (Spac)Emacs continuously crashing due to compilation of swap files

metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala, metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala, website/core/Footer.js
The Gitter UX is quite bad to the point where I don't enjoy using it
much anymore. I suspect GitHub will sooner or later release a community
chat solution judging by
https://spectrum.chat/spectrum/general/spectrum-is-joining-github~1d3eb8ee-4c99-46c0-8daf-ca35a96be6ce/
However, until then I think it's worth a try to keep the conversation
going on Slack under the #scalameta-metals channel in the new
"scala-lang" organization.
Live demo is here https://olafurpg.github.io/metals/ I'm unable to make the Slack badge clickable however 🤔 any idea how to fix it? Docs are here https://github.com/rauchg/slackin
=> Add link to new Discord server in the website footer.

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
This is intended to be used in the Bloop sbt build that uses a custom
way to install the sbt-bloop plugin.
=> Add system property to disable project/metals.sbt generation

docs/editors/emacs.md
Corrected errors in installation tutorial
=> Clarify Emacs installation instructions

.gitignore, metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala, tests/unit/src/test/scala/tests/RangeFormattingSuite.scala
Fixes #952 
I left a comment on the issue as I wasn't sure the way to go about testing this -- mainly where to put the test or if I should tack it on to another. Any pointers there would be helpful. I also may have missed some helper methods or ways I could have reused stuff, so please let me know! I figured I'd make the pr right away in order to get some feedback.
=> Add automatic formatting of multi-line `stripMargin` strings on paste

docs/editors/vscode.md
The current documentation suggests that Java 11 is supported, but it actually needs to be manually configured at the moment. This PR hopefully makes that more clear.
See https://github.com/scalameta/metals/issues/762 and https://twitter.com/andyczerwonka/status/1184560663215034369 for details.
=> A documentation change in support of Java 11 configuration

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
This allows clients to optionally choose whether to include a
`"metals."` prefix or not. Fixes #838.
=> Strip "metals." prefix from `workspace/executeCommand` requests.

tests/unit/src/main/scala/tests/BaseLspSuite.scala
Previously, shutdownNow would cause multiple threads to be interrupted, which would show up as a large number of exception. Now, we use shutdown(), so that threads can finish orderly.
=> Switch shutdownNow to shutdown due to excessive exceptions being logged

metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala, tests/unit/src/test/scala/tests/TreeViewLspSuite.scala
Fixes #846. Previously, Metals didn't send tree view update
notifications on no-op compilations under the assumption that the tree
view wouldn't change since it was an empty compilation. However, this
assumption was wrong when an empty compilation is the first compilation
of a build server connection because the Bloop build server may have
copied over classfiles to the BSP session class directory.
Now, Metals will send a tree view update compilation for the first
compiation even if it's empty ensuring the tree view properly picks up
the latest outlines from the project.
=> Send Tree View update notification on first no-op compilation.

metals/src/main/scala/scala/meta/internal/metals/BuildTargetClasses.scala, metals/src/main/scala/scala/meta/internal/metals/CodeLensProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Compilations.scala, metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, tests/unit/src/main/scala/tests/BaseLspSuite.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/CodeLensesLspSuite.scala
Closes #992 
Previously, code lens would not disappear when recompilation would fail.
Now, we refresh the code lenses in an open tab also after failure
=> Keep code lenses after error until next successful compilation

metals/src/main/scala/scala/meta/internal/metals/ClientExperimentalCapabilities.scala, metals/src/main/scala/scala/meta/internal/metals/CodeLensProvider.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, tests/unit/src/main/scala/tests/TestingServer.scala
Closes #1006
Previously, code lenses related to run/test action would be sent to the clients even if it didn't support running the code.
Now, in such case, Metals is not sending those lenses.
=> Suppress code lenses if debugging is not supported

docs/editors/vim.md
This pull request is intended to resolve problem I've stumbled upon - after installing this plugin it didn't load coc-settings.json from ~/.config/nvim/coc-settings.json. Upon further inspection it turns out that this tutorial was outdated. For reference: https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim.
=> Resolve problem with coc.nvim installation

metals/src/main/scala/scala/meta/internal/builds/Digest.scala, tests/unit/src/main/scala/tests/BaseDigestSuite.scala, tests/unit/src/test/scala/tests/BaseDigestSuite.scala, tests/unit/src/test/scala/tests/digest/DigestsSuite.scala, tests/unit/src/test/scala/tests/digest/GradleDigestSuite.scala, tests/unit/src/test/scala/tests/digest/MavenDigestSuite.scala, tests/unit/src/test/scala/tests/digest/MillDigestSuite.scala, tests/unit/src/test/scala/tests/digest/SbtDigestSuite.scala
Fixes #1009. Previously, when the user loaded the workspace to a docker
container then Metals would fail to connect to the Bloop build server
without providing an explanation what might be wrong. Now, Metals will
prompt the user to re-import the build.
=> Encode the workspace path directory in build digests

mtags/src/main/scala/scala/meta/internal/pc/HoverProvider.scala
This is based on stack traces I had while working on Metals:
```
Oct 28, 2019 6:42:47 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: null
java.lang.NullPointerException
at scala.meta.internal.pc.HoverProvider.seenFromType(HoverProvider.scala:106)
at scala.meta.internal.pc.HoverProvider.hover(HoverProvider.scala:42)
Oct 28, 2019 6:44:16 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: null
java.lang.NullPointerException
at scala.meta.internal.pc.HoverProvider.hover(HoverProvider.scala:37)
```
Might be connected to the bug report we clsoed previously.
=> Add guards against nulls that happened in the HoverProvider code

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala, metals/src/main/scala/scala/meta/internal/metals/debug/EndpointLogger.scala, metals/src/main/scala/scala/meta/internal/metals/debug/RemoteEndpoint.scala, metals/src/main/scala/scala/meta/internal/metals/debug/SocketEndpoint.scala, tests/unit/src/main/scala/scala/meta/internal/metals/debug/RemoteServer.scala
closes #1022
Previously the dap messages were were not being traced.
Now, we trace them on both ends in: `dap-client.trace.json` and `tap-server.trace.json` files
=> trace the debug adapter protocol messages

metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/DelegatingLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsHttpClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/NoopLanguageClient.scala, metals/src/main/scala/scala/meta/metals/Main.scala, tests/slow/src/test/scala/tests/BaseImportSuite.scala, tests/unit/src/main/scala/tests/BaseLspSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/UnsupportedDebuggingLspSuite.scala
closes #1016 
Previously, model-refresh command was sent to the client even though it didn't support debugging.
Now, metals will refrain from sending in in such cases.
=> Suppress model-refresh if debugging is unsupported

docs/editors/emacs.md
See issue #1027. AutoSave files in source directories break the
compile and in Emacs can cause error highlighting to vanish in some
sourc files.
This change also shows a work-around to prevent the SBT 1.3 supershell
from killing sbt-mode.
=> Update sample Emacs configuration to avoid AutoSave files in src dir

project/build.properties
After removing metals-plugin we can finally switch to the newest sbt version.
=> Update sbt version to 1.3.2

.github/workflows/ci.yml
Only run tests on master branch or in PRs, previously it would run twice on a push to forked branch.
Finally figured out why we were getting 2x test notifications. Noticed that when upgrading to new sbt. I think it makes sense to still run tests on master - we can track any issues - and obviously on PRs.
=> Only run tests on master branch or in PRs

docs/build-tools/overview.md, website/pages/en/index.js
Previously, the website made it appear as if Bloop was an implementation
detail of Metals. Now, the website tries to give Bloop more visibility
and advertise it as an essential part of the Metals user experience (low
latency diagnostics, testing, running, soon debugging).
Metals still continues to work with other BSP servers. Nothing changes on the implementation side.
=> Give Bloop more visibility on the website.

mtags/src/main/scala/scala/meta/internal/pc/AutoImports.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/Signatures.scala, tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionOverrideConfigSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
This will close #1054
Checks to see if there are any imports and if not, but there is a package declaration, it will add an extra new line to add padding between the package declaration and the first import.
=> Add an empty line after the package declaration before import

mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala
Fixes #1029 
Previously we would prevent overriding `var` members altogether, recently there seems to be been a regression where we suggest `def` completions for `var` members (#1029); now we allow overriding abstract `var` members, while still rejecting concrete `var` overrides.
=> Handle abstract var overrides

metals/src/main/scala/scala/meta/internal/implementation/ClassLocation.scala, metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala, metals/src/main/scala/scala/meta/internal/implementation/MethodImplementation.scala, metals/src/main/scala/scala/meta/internal/metals/Buffers.scala, metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala, mtags/src/main/scala/scala/meta/internal/metals/TextEdits.scala, mtags/src/main/scala/scala/meta/internal/mtags/MtagsEnrichments.scala, tests/cross/src/main/scala/tests/BaseCompletionSuite.scala, tests/cross/src/main/scala/tests/pc/BasePcDefinitionSuite.scala, tests/unit/src/main/scala/tests/TestRanges.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/FoldingRangeSuite.scala, tests/unit/src/test/scala/tests/RenameSuite.scala
Previously, rename was not supported in any way. User would have to manually rename everything by hand and that could prove really tedious. Now, we offer renaming of any symbol with a small number of exclusions:
- unapply
- equals
- hashCode
- unary_!
- !
We can also add/remove other exclusions if needed.
There are also some special cases and several approaches that need to be mentioned:
1. When apply is renamed we add full name to each invocation
2. Symbols can't be renamed while compiling, since we need full and correct semanticDB information - an error will pop up as a message.
3. Methods ending with colon can only be renamed to another name ending with colon. 
4. Renaming an overriden method will rename both parent symbol and current symbol:
5. Symbols from outside workspace cannot be …
=> Implement textDocument/rename

.gitignore, metals/src/main/scala/scala/meta/internal/metals/Configs.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala, tests/cross/src/main/scala/tests/BasePCSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionOverrideAllSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala
So I believe I have the implemented correctly now that it will work for all abstract members -- defs, vals, and vars. If you have 5, but 2 implemented, then the implement all will implement the remaining 3.
I am not sure about a few things though...
1) The way I did the actual text edit with the strings of the other text edits
2) I wasn't positive about what you mentioned in the issue about this https://github.com/scalameta/metals/issues/1008#issuecomment-544505366, but I made a test with that scenario, and it seems to work as expected?
3) Other tests that I may be missing.
This should close #1029 and also address #1008. However, regarding #1008, I'm not sure if we also want to implement it as well where if you are instantiating a class or something that has the abstract members, it will …
=> Add completion to add all abstract members

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala, mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala, tests/cross/src/test/scala/tests/pc/CompletionSnippetNegSuite.scala
Fixes #1055 
Previously we always used snippets in completion items, regardless of whether the client declared that it supported them. Now we respect the capabilities declared by the client.
=> Respect client capabilities for completion item snippets

metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
I was doing some testing with this pr https://github.com/tomv564/LSP/pull/772 to see how it would work with the new "implement all memebers" and it seems that Submlime does put in the auto-ident just like VS-Code and Atom does. I originally had this marked to false for Sublime causing it to look like so in Sublime
```
object Main {
trait Foo {
def foo: Int
def bar: Int
def car: Int
}
val x = new Foo {
def foo: Int = ???
def bar: Int = ???
def car: Int = ???
}
}
```
This will fix that.
=> Update Sublime settings since it does have auto-indent

docs/editors/emacs.md
This will close #1045 which was an inaccurate description of what was actually happening. It was bugging me since I know we came across the "magic" indentation of some editors, but with emacs, it seemed odd that the last `}` was never being indented correctly. Plus, after @gabro made the  #1057 fix, I didn't understand why it seemed that emacs lsp-mode was saying it supported snippets, when they obviously weren't working right. Turns out lsp-mode has a configuration option `lsp-enable-snippet` which is on by default. This then requires you to use the `yasnippet` package, or snippets won't work correctly, and also some of the indentations will be wrong. An emacs buff may have known this, but I am anything but an emacs buff. Either way, I think we should mention this in the docs as it may …
=> Update emacs docs to include yasnippet

build.sbt
Previously, the CI would occasionally fail with a "could not copy ..."
error during compilation caused by
https://github.com/sbt/sbt-buildinfo/issues/152. This commit changes the
`publishLocal` step for mtags so that 2.13 and 2.11 publish sequentially
instead of in parallel.
=> Force sequential publishLocal for mtags 2.11/2.13.

metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala, tests/unit/src/test/scala/tests/RenameLspSuite.scala, tests/unit/src/test/scala/tests/RenameSuite.scala
Fixes #1074 
Previously we would rename files whose name partially matched the symbol being renamed. Now we compute those renames using an exact match, to avoid e.g. renaming a file named `FooBar.scala` when renaming the symbol `Bar` in that file.
=> Use exact match when computing file renames

docs/editors/vim.md
Part of this is related to #1081 since `onTypeFormatting` wasn't working as expected with coc.nvim. There are some extra configuration settings that are needed to ensure this works as expected which aren't clearly documented. There was also a small bug in coc.vim that they fixed really quickly. So props to them. This now works as expected like so:
I also added a few custom commands into the configuration and updated the vim docs to utilize them. They will make manually triggering build imports, connecting to the build server, and running doctor much easier by providing `:MetalsDoctor`, `:MetalsImport`, and `:MetalsConnect` commands like so:
=> add in more documentatin for vim setup

build.sbt, project/plugins.sbt, project/project/plugins.sbt
It's not necessary since sbt 1.3.x, that uses coursier automatically.
=> Remove sbt-coursier

.github/workflows/ci.yml
This release automatically sets the environment variable `CI=true` so
that CI-related logic gets picked up the same way it does on Travis.
I'm surprised this variable is not set by default in GitHub Actions.
=> Update to the latest setup-scala.

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala, tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala
Previously, no source dependencies would be downloaded due to a typo and a misconfiguration.
Now, the typo is fixed and proper Bloop settings applied to all projects.
=> Fix issue with no source dependencies being downloaded by Bloop

tests/cross/src/test/scala/tests/pc/MacroCompletionSuite.scala
The issue seems to have migrated - not exactly sure why. It happened after a coursier upgrade - classpath issue? However, since it's for older Scala versions I am inclined to just fix it here.
=> Fix cross macro tests for older Scala versions

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala
When I first came across this I found it really hard to understand at first glance until @olafurpg kindly explained it to me. If I understood him correctly, I _believe_ this will work as expected and I think it's much more readable.
=> Decode for better readability

docs/editors/sublime.md
Since release [0.9.1](https://github.com/tomv564/LSP/releases/tag/0.9.1) of LSP, there is no need for the user to edit the `prefer_label_over_filter_text` setting as it is removed.
See https://github.com/tomv564/LSP/pull/772 for more details.
=> Update sublime documentation

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala, tests/unit/src/main/scala/tests/TestingServer.scala
Previously, all closed files would be updated just during the rename, which could produce false positive compiler errors while the opened files are not saved. Now, we delay changing the close files until the first save is hit.
=> Delay renaming in closed files until the first save is run 

metals/src/main/scala/scala/meta/internal/metals/BspServers.scala
Previously, we used `Paths.get(..)` directly on the path returned by the
jvm-directories libraries, which could crash on some Windows
installations. Now, we fallback to silently ignoring the issue.  It's
fine to silently ignore this issue since users can still configure
custom BSP servers via the local directory. The BSP server discovery
spec says that KNOWNFOLDERID should be used on Windows to determine the
global directory, if the running computer does not support that feature
then we can't support it in Metals.
=> Gracefully handle jvm-directories failures, fixes #1085.

.github/workflows/ci.yml, build.sbt, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/RenameLspSuite.scala
The PR #1108 introduced an uncaught regression on macOS. 
```
Exception in thread "pool-2-thread-2" java.lang.NoSuchFieldError: SIZE
at com.zaxxer.nuprocess.osx.OsxProcess.createPosixSpawnFileActions(OsxProcess.java:191)
at com.zaxxer.nuprocess.osx.OsxProcess.createPosixPipes(OsxProcess.java:150)
at com.zaxxer.nuprocess.osx.OsxProcess.start(OsxProcess.java:58)
at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:34)
at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
at scala.meta.internal.process.SystemProcess$.run(SystemProcess.scala:27)
at scala.meta.internal.pantsbuild.Filemap$.fromPants(Filemap.scala:40)
at scala.meta.internal.pantsbuild.BloopPants$.$anonfun$bloopInstall$1(BloopPants.scala:133)
at …
```
=> Revert "Update directory-watcher to 0.8.3"

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala, metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala, tests/unit/src/test/scala/tests/ImplementationLspSuite.scala, tests/unit/src/test/scala/tests/RenameLspSuite.scala
Previously, renames would not work correctly in case of macro annotations - it would not find annotated classes definition and create an additional reference pointing to the annotation itself.
Now, we always try to find the definition separately for non local symbols and we check all references to be at the right names.
=> Fix renames in case of macro annotations

build.sbt
This reverts commit a99afaf97204e1710d334c85dd8abec2f9072770.
This upgrade caused the same regression on macOS as the directory-watcher upgrade. The PR https://github.com/scalameta/metals/pull/1131 was merged this morning before we enabled the macOS CI.
=> Revert "Update jna, jna-platform to 5.5.0"

build.sbt, metals/src/main/resources/db/migration/V3__Jar_symbols.sql
Followup of #1101 fixing a trailing comma syntax error.
Sadly, this change means that the flyway migration will fail for all users when they upgrade and `.metals/metals.h2.db` will be dropped and recreated from scratch 😟
=> Upgrade to h2 v1.4.200.

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala, metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala, tests/unit/src/test/scala/tests/RenameLspSuite.scala
Fixes #1072 
Previously we would rename all references of a symbol, including synthetic ones. This resulted in bugs such as #1072. Now we ignore synthetics references when performing a rename.
=> Avoid renaming synthetic occurrences

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
In JDK11 a method on `String` was added named `lines` which returned a `java.util.stream.Stream`. This collided with the enrichment method from Scala's `StringOps` class by the same name which returned an `Iterator`. The result, for metals, is that it was not possible to build metals using JDK11 or greater.
This commit uses the new enrichment method `linesIterator` which was added to the Scala standard library as a replacement. This now enables metals to compile on JDK11.
See: https://github.com/scala/bug/issues/11125
=> Remove Deprecated Usage Of String#lines Method

tests/unit/src/main/scala/scala/meta/internal/metals/debug/DebuggeeOutput.scala, tests/unit/src/main/scala/scala/meta/internal/metals/debug/Debugger.scala, tests/unit/src/main/scala/scala/meta/internal/metals/debug/RemoteServer.scala, tests/unit/src/main/scala/scala/meta/internal/metals/debug/TestDebugger.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/DebugProtocolSuite.scala
Previously, waiting for output containing new lines was system dependent - we were expecting `\n` even on windows. Now, we are automatically adapting unix new lines to the underlying OS.
=> [DAP-tests] Adapt new lines to the underlying OS

.github/workflows/ci.yml
On advice from https://github.com/dwijnand/sbt-dynver/issues/133#issuecomment-561585983
=> Use git fetch --unshallow to restore version number

build.sbt
This reverts commit a6278fbf6cc4e9fb7317b6999f5e6c38ed8b5270.
I'm still hitting on crashes when running the tests locally on my computer
```
Exception in thread "pool-2-thread-2" java.lang.NoSuchFieldError: SIZE
at com.zaxxer.nuprocess.osx.OsxProcess.createPosixSpawnFileActions(OsxProcess.java:191)
at com.zaxxer.nuprocess.osx.OsxProcess.createPosixPipes(OsxProcess.java:150)
at com.zaxxer.nuprocess.osx.OsxProcess.start(OsxProcess.java:58)
at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:34)
at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
at scala.meta.internal.process.SystemProcess$.run(SystemProcess.scala:27)
at scala.meta.internal.pantsbuild.Filemap$.fromPants(Filemap.scala:40)
at …
```
=> Revert "Update directory watcher to 0.9.6"

tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/main/scala/tests/TestingServer.scala
In 4d78f9cf5a2e6c49d8a6e2474a49a8bbb99e216c a usage of the deprecated method `lines` on `StringOps` was changed to `linesIterator` to allow for compilation on JDK>=11. Two other invocations were also present in the code, but missed in that PR.
=> Remove Two More Usages Of Deprecated `lines` Method

mtags/src/main/scala/scala/meta/internal/docstrings/HtmlConverter.scala
An `asInstanceOf` was being used to case a value to a subtype, but a pattern match had already safely created a typed value.
This commit also removes two unused named variables pattern matches in `HtmlConverter.scala`
=> Remove Unnecessary `asInstanceOf` And Unused Values

metals-bench/src/main/scala/bench/ClasspathIndexingBench.scala, metals-bench/src/main/scala/bench/CompletionBench.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala, mtags/src/main/scala/scala/meta/internal/metals/ClasspathSearch.scala, tests/cross/src/main/scala/tests/BasePCSuite.scala, tests/unit/src/main/scala/tests/TestingWorkspaceSymbolProvider.scala
The parameter `packagePriority` in `ClasspathSearch` is unused.
=> Remove Unused `packagePriority` Parameter From ClasspathSearch

mtags/src/main/scala/scala/meta/internal/docstrings/MarkdownGenerator.scala
* `blocksToMarkdown` had an unused parameter `listLevel`. It appears as though the intent was to pass this value to the `blockToMarkdown` function which also has a parameter by the same name to keep track of indentation level. This is now the case. As a result of this change, there is now no situation in which the default argument value of `listLevel` in the function `blockToMarkdown` is used, thus it was removed.
* In the function `blockToMarkdown` the matches on `UnorderedList` and `OrderedList` are identical code, except for choosing a different bullet character, either `-` or `*`, based on the type. This logic was factored out into two new functions, `listBlockIndent` and `listBlocksIndent` which allow for a reduction in repeated code in the body of `blockToMarkdown`.
=> Cleanup MarkdownGenerator

.github/workflows/ci.yml, build.sbt, metals/src/main/resources/pants, metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala, metals/src/main/scala/scala/meta/internal/builds/PantsBuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/PantsDigest.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/Args.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/Cycles.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/Filemap.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/Graph.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsConfiguration.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/Tarjans.scala, tests/slow/src/test/scala/tests/pants/PantsLspSuite.scala, tests/unit/src/test/scala/tests/PantsDigestSuite.scala, tests/unit/src/test/scala/tests/TreeViewLspSuite.scala, tests/unit/src/test/scala/tests/UserConfigurationSuite.scala, tests/unit/src/test/scala/tests/digest/PantsDigestSuite.scala
Previously, Metals didn't work with the Pants build tool https://www.pantsbuild.org/. This PR adds support for Pants that works similarly to the build tool support with sbt, Gradle, Maven and Mill.
* the user needs to configure the `pants-targets` setting to specify what parts of their Pants build should be exported to Metals/Bloop.
* the user is prompted to import a Pants workspace on first startup
* when `BUILD` files change, Metals will prompt to the user to "import changes"
This PR is still a WIP. There are several issues related to handling large number of individual source files that belong to a Pants target.
=> Add basic support for the Pants build tool

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
Following up on https://github.com/scalameta/metals/pull/935#discussion_r354406977
=> Use atomic file move operations.

build.sbt, metals-bench/src/main/scala/bench/CompletionBench.scala
A path to file needed to run the `CompletionBench` benchmark was hard coded as scala `2.12.8`. Since this is no longer the version of Scala used to compile `metals` this fails at runtime.
This was changed to use sbt-buildinfo to populate the correct version of scala for the given build from the build definition directly.
=> Fix Runtime Error In Metals Bench

.gitattributes, .github/workflows/ci.yml
Add a `.gitattributes` file to prevent end of line (EOL) conversion on the `/.jvmopts` file. This was the causing windows based CI failures as the JVM options were being parsed with a carriage return at the end of them.
This commit also re-enables use of the `.jvmopts` file in the Windows CI environment.
----
#
=> Disable EOL Conversion On /.jvmopts

.github/workflows/ci.yml
Just some proposed changes for (I think) clarity.
We may also take the chance to rename the `slow` project into `lsp` or `integration`. Thoughts?
=> Minor tweaks to CI jobs names

.jvmopts, tests/mtest/src/main/scala/tests/BaseSuite.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala, tests/unit/src/test/scala/tests/BspSwitchLspSuite.scala, tests/unit/src/test/scala/tests/BuildTargetsLspSuite.scala, tests/unit/src/test/scala/tests/CompletionLspSuite.scala, tests/unit/src/test/scala/tests/FoldingRangeSuite.scala
BspSwitchSuite is consistently failing on CI for Windows, but FoldingRangeSuite might be reenabled after recent fixes to the reliability of the directory watcher within tests.
=> Ignore flaky BspSwitchSuite and reenable FoldingRangeSuite on Windows.

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/Filemap.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsConfiguration.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsExport.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsKeys.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsLibrary.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsScalaPlatform.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTarget.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTargetType.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/TargetType.scala
Previously, the Pants to Bloop export step was implemented with fairly
tricky code that was difficult to reason about. This commit cleans up
the implementation so that it's more correct, easier to maintain and it
also runs faster.
=> Improve Pants to Bloop export step.

metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/QuickFix.scala, metals/src/main/scala/scala/meta/internal/metals/QuickFixes.scala, metals/src/main/scala/scala/meta/internal/metals/ScalacDiagnostic.scala, mtags-interfaces/src/main/java/scala/meta/pc/AutoImportsResult.java, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java, mtags/src/main/scala/scala/meta/internal/pc/AutoImportsProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/AutoImportsResultImpl.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala, mtags/src/main/scala/scala/meta/internal/pc/WorkspaceSymbolSearch.scala, tests/cross/src/main/scala/tests/BaseCodeActionSuite.scala, tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/CodeActionLspSuite.scala
This is draft PR to validate a possible architecture for code actions (aka refactors).
For now, I'm focusing on code actions that resolve existing diagnostics (i.e. quickfixes), but the architecture could be expanded to more general refactors.
This PR implements a working prototype ~(although it's a bit of a hack)~ for the "add missing import" quickfix, which gets triggered by the relevant compiler error.
If we're happy with the general structure, I can move on with the testing infrastructure for code actions and refining the actual implementation.
=> Implement code action for importing missing symbols

metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala
Fixes #1182 
Previously, a race condition could cause Metals to prompt the user twice to import build changes. The duplicate prompt could cause some test suites like `PantsLspSuite` to become flaky. Now, we synchronize on the method that prompts the user to ensure that we finish writing the digest notification status in the H2 database before sending the next prompt.
I'm not sure if this fixes the flaky test failure, but I struggle to see why the Pants build digest should be any more flaky than the other build tool digests.
=> Hopefully fix flaky test failure

.github/workflows/ci.yml, build.sbt, metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala, metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/worksheets/WorkspaceEditWorksheetPublisher.scala, mtags/src/main/scala/scala/meta/internal/semver/SemVer.scala, tests/mtest/src/main/scala/tests/BaseSuite.scala, tests/slow/src/test/scala/tests/feature/CompletionCrossLspSuite.scala, tests/slow/src/test/scala/tests/feature/DefinitionCrossLspSuite.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala, tests/unit/src/test/scala/tests/TreeViewLspSuite.scala
Another instance of the deprecated `lines` method was recently added to the code base. This method causes metals to be not build on JDK >= 11.
This commit also updates the CI to build with JDKs 8 and 11 using AdpotOpenJDK. The majority of tests are JDK 11 as default, with a single test using JDK8 as a legacy compatibility smoke test. This should help prevent future additions of this method.
Finally, this commit drops cross building with deprecated scala versions, as they are unable to parse class files generated with bytecode for JDKs > 8.
See: ce9c890c27efec49fd8ad78746e2f406bfd89d3b and 4d78f9cf5a2e6c49d8a6e2474a49a8bbb99e216c for more context.
=> Remove Usage Of Deprecated `lines` Method

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsExport.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsGlobs.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsScalaPlatform.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTarget.scala
See individual commits for details. In summary:
* faster `bloop test` for ScalaTest targets
* increased compatibility with older versions of Pants
* improved UX for Pants targets that use recursive `**/*.scala` globs
=> Several improvements to Pants export step

metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTarget.scala
Previously, Bloop would trigger a re-compilation after restarting the
server. Now, the newly started Bloop server re-uses the cached
compilation.
Related PR https://github.com/scalacenter/bloop/pull/1129
=> Avoid re-compilation when restarting Bloop in Pants workspace

.github/workflows/ci.yml
Previously, we could observe ambiguous names of the unit test jobs:
Now, we include the jdk version in the name of those jobs
=> Include jdk in the job name

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala
Previously, the working directory would default to the base directory of
the Pants target (directory containing BUILD file). Now, the working
directory will be the root of the Pants build, reproducing the Pants
behavior for run/test.
=> Set the working directory to the workspace in Pants export.

metals/src/main/scala/scala/meta/internal/pantsbuild/PantsExport.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTarget.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTargetType.scala
Previously, we created Bloop projects for "files" targets with an empty
classpath and `*.java` and `*.scala` files resulting in false compile
errors. Now, we ignore those targets since they're not compiled by Pants
anyways.
=> Don't create Bloop projects for Pants targets of type "files".

docs/contributors/updating-website.md, docs/editors/new-editor.md, docs/editors/overview.md, docs/editors/vim.md, metals-docs/src/main/scala/docs/Image.scala, metals-docs/src/main/scala/docs/UserConfigurationModifier.scala, website/i18n/en.json, website/package.json
Hopefully, this will help with the review of `coc-metals`. I did my best to update all of the documentation and include images of all the new things that `coc-metals` offers vim users.
I think it's at a point where it's very stable for downloading new versions, managing configuration options, and using commands to restart the server etc. I've found the experience much more pleasant than managing it by hand. I think it'd be cool to have this included in the next release.
I think that the extension should probably be looked at by someone on the team first to make sure it's sane, but everything seems to be working alright, and the code is very similar to that of the vs code extension. In the future, we may be able to extract out a common module to publish and share as well between the two of …
=> add in documenation for coc-metals

metals/src/main/scala/scala/meta/internal/pantsbuild/Args.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala
The edit/compile/test feedback loop with the new JUnit test runner.
=> Continued improvements to Pants export

mtags/src/main/scala/scala/meta/internal/pc/Completions.scala
This PR is just a minor fix on scaladoc :)
The scaladoc for the `contribute` method looks like for `isPrioritize` method.
=> Fix scaladoc for methods in Completions

metals/src/main/scala/scala/meta/internal/pantsbuild/Args.scala
Just removing a small block that was unreachable since it was duplicated from a few lines above.
=> Remove unreachable code

docs/editors/new-editor.md, docs/editors/sublime.md, metals/src/main/scala/scala/meta/internal/metals/MetalsHttpClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
Previously LSP displayed a dialog box for `window/showMessage`, latest version (0.9.3 via PR https://github.com/tomv564/LSP/pull/811) displays that in the status bar.
Additionally: 
- make `metals/status` go as `window/showMessage`
- removed some outdated comments.
=> Update Sublime settings regarding window/showMessage

docs/editors/vim.md, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
Updates to vim documentation
- Added in information about alternative ways to install
- Changed out Doctor information for an embedded version
- A new section about statusline integration
- Fixed some typos
=> Updates to vim section

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
Fixes #1220 
This is a temporary fix that discards the `code` property from BSP diagnostics. If we decide to change the `code` property semantics in BSP, then we can revert this fix. See the discussion here https://github.com/scalacenter/bloop/pull/1135
=> Discard 'code' from BSP diagnostics

tests/slow/src/test/scala/tests/pants/PantsLspSuite.scala
See https://github.com/scalameta/metals/issues/1182
=> Disable flaky test cases

metals/src/main/scala/scala/meta/internal/worksheets/MdocEnrichments.scala, metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala, mtags/src/main/scala/scala/meta/internal/mtags/MtagsEnrichments.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
Previously, worksheets did not gracefully handle diagnostics that had no
positions resulting in hanging "Evaluating worksheet" notification
windows. Now, we filter out such diagnostics so that the worksheet
finishes evaluation. We also ensure that unexpected exceptions no longer
cause hanging "Evaluating worksheet" notification windows.
=> Fix issue #1236, make worksheets handle unpositioned diagnostics.

metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala, tests/unit/src/test/scala/tests/RangeFormattingSuite.scala
Closes #1244 
When I originally worked on this (my first Metals ticket 🎉 ), I totally forgot about the case where you paste on the first line of the multi-line string. This adds in a check for that and also a test for it.
=> Fix multi-line range formatting when on first line

tests/unit/src/test/scala/tests/RangeFormattingSuite.scala
Just for good measure, I've added in another test to ensure that this is working in both situations where there is a pipe on the first line and when there isn't a pipe.
=> add in another test for multi-line string formatting

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
I don't think this has any practical impact, but it's technically slightly more compliant with the spec.
All the clients I've checked support code action literals anyway.
=> Slightly more compliant initialization of codeActionProvider

tests/cross/src/main/scala/tests/BaseCompletionSuite.scala, tests/cross/src/main/scala/tests/BasePCSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala, tests/mtest/src/main/scala/tests/BaseSuite.scala, tests/mtest/src/main/scala/tests/Tag.scala, tests/mtest/src/main/scala/tests/TestOptions.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala, tests/unit/src/test/scala/tests/BuildTargetsLspSuite.scala, tests/unit/src/test/scala/tests/CompletionLspSuite.scala, tests/unit/src/test/scala/tests/CompressionSuite.scala
Following an offline conversation with @olafurpg, this is a stab at "failing tests", inspired from https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests
=> Failing test case for #1253

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala
This update includes several improvements like
* ScalaTest suites that have an explicit `@RunWith` annotation no longer
get noisy "Executed no tests" message.
* Nicer pretty-printing of test results.
=> Upgrade Pants sbt testing interface.

metals/src/main/scala/scala/meta/internal/metals/debug/SetBreakpointsRequestHandler.scala, tests/unit/src/main/scala/tests/BaseDapSuite.scala, tests/unit/src/test/scala/tests/debug/BreakpointDapSuite.scala
Previously, setting breakpoints in java static methods or nested/anonymous classes didn't work.
=> Support breakpoints in java static methods and nested classes

metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala, metals/src/main/scala/scala/meta/internal/metals/CodeLensProvider.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/debug/DebugProtocol.scala, metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala, tests/unit/src/main/scala/scala/meta/internal/metals/debug/Debugger.scala, tests/unit/src/main/scala/scala/meta/internal/metals/debug/Stoppage.scala, tests/unit/src/main/scala/scala/meta/internal/metals/debug/TestDebugger.scala, tests/unit/src/main/scala/tests/CodeLensesTextEdits.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/CodeLensesLspSuite.scala, tests/unit/src/test/scala/tests/debug/BreakpointDapSuite.scala, tests/unit/src/test/scala/tests/debug/StepDapSuite.scala
Closes #1188 
Previously, there was no way to run program and ignore the breakpoints.
Now, we introduce a separate command `StartRunSession` which ignores the breakpoint requests altogether.
Both commands (`StartRunSession` and `StartDebugSession`) are shown to the user as separate code lenses.
TODO: rebase after #1010 gets merged
=> Add separate "debug" code lens

metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/Args.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/VSCode.scala
Previously, it required several manual steps to use Metals with Pants.
Now, users can run the exporter tool with the --vscode flag to have
everything setup automatically, including installation of the Metals VS
Code extension.
While working on this feature, I hit on a bug in the Doctor where it
would report a warning about non-Scala targets. This commit fixes that
bug by removing non-Scala targets from the doctor list.
=> Add --vscode flag to Pants export tool.

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/VSCode.scala
* Use absolute path to `code` binary so that it works even if it's not
on $PATH
* Rename `LaunchIntellij` into `IntelliJ` for consistency with `VSCode`
=> Further polish to --vscode flag

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/Filemap.scala, metals/src/main/scala/scala/meta/internal/process/SystemProcess.scala
Previously, it was not possible to build a native-image for the
command-line interface. With this commit, it's possible to build a
standalone binary with native-image.
=> Use scala.sys.Process for BloopPants command-line.

metals/src/main/scala/scala/meta/internal/metals/MetalsHttpClient.scala
This is change which I described in my gitter comment:
https://gitter.im/scalameta/metals?at=5e15799ba1e15049012067bf
> I forked coc.nvim and added TreeViewProtocol support for metals. But there is one thing which requires small change in metals. When user clicks on node with class/trait/object, this class should be opened in editor. Coc.nvim sends "workspace/executeCommand" with command "metals.goto". Metals sends empty response and usually sends notification "metals/executeClientCommand" with "metals-goto-location". But option isHttpEnabled of MetalsServerConfig is activated for coc.nvim and as result MetalsHttpClient does nothing for executeClientCommand.
=> Send notification 'metals/executeClientCommand' on command metals.goto

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala, mtags/src/main/scala/scala/meta/internal/mtags/MtagsEnrichments.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/DocumentSymbolSuite.scala, tests/unit/src/test/scala/tests/FoldingRangeSuite.scala, tests/unit/src/test/scala/tests/MtagsEnrichmentsSuite.scala, tests/unit/src/test/scala/tests/WorkspaceSymbolLspSuite.scala, tests/unit/src/test/scala/tests/codeactions/BaseCodeActionLspSuite.scala, tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala
Fixes #1283 
Previously we computed the 'Import missing symbol' code action for a single diagnostic under the cursor. Now we compute all diagnostics whose range overlap with the code action range sent by the client. This allows computing auto-imports for all diagnostics in a range at once.
This is especially relevant for clients like Vim, which - by default - sends a code action request for the entire line.
Here's how it looks like in VS Code:
=> Compute 'Import missing symbol' code actions for all diagnostics in range

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala
Previously, user could dismiss the notification about reconnecting to the build server forever. Now it's possible only for 5 minutes.
@olafurpg is this alright?
=> Allow only to dismiss build server reconnection for 5 minutes

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, mtags/src/main/scala/scala/meta/internal/pc/ScaladocCompletion.scala, mtags/src/main/scala/scala/meta/internal/pc/ScaladocCompletions.scala, tests/cross/src/test/scala/tests/pc/CompletionScaladocSuite.scala
Closes #1252
This PR enables the metals server to auto-complete scaladoc for **method definition** and **class definition** on type `/**`
- Enable to fire `textDocument/completion` on type `*` by setting `triggerCharacters` on `initialize`.
- If the line only have a `/**`, try to complete scaladoc
- Close the comment by inserting `*/` behind the cursor before adding the source to the compilation unit, so that metals can traverse whole AST in the source.
- Find an associated member definition by traverse the AST for the source, and ~collect all `MemberDef` that is defined below the `/**`.~, and get the closest `MemberDef` that is defined below the `/**` as an associated definition.
- Generate scaladoc based on the definition.
<details>
<summary>Outdated :)</summary>
~Currently, after the …
=> Support scaladoc auto completion on type `/**`

metals/src/main/scala/scala/meta/internal/metals/MetalsLogger.scala
This removes noisy logs like this
```
INFO  Creating Schema History table "PUBLIC"."flyway_schema_history" ...
INFO  Current version of schema "PUBLIC": << Empty Schema >>
INFO  Migrating schema "PUBLIC" to version 1 - Create tables
INFO  Migrating schema "PUBLIC" to version 2 - Server discovery
INFO  Migrating schema "PUBLIC" to version 3 - Jar symbols
INFO  Successfully applied 3 migrations to schema "PUBLIC" (execution time 00:00.053s)
```
=> Silence noisy FlywayDB logs

website/blog/2020-01-10-cobalt.md
This PR updates the screen-record of the Scaladoc auto-completion section in v0.8.0's release note.
The previous screen record came from the [Pull Request](https://github.com/scalameta/metals/pull/1250), but it is a bit different from real behavior: we don't add `* @constructor` line for scaladoc on a class definition. Sorry for the confusion!
(the behavior had updated in https://github.com/scalameta/metals/pull/1250/commits/cf8e6070092ac693251e01568b009a7f1bfce601, but I didn't update the screen-record.)
=> Update screen-record of Scaladoc auto-completion in v0.8.0 release-note.

docs/build-tools/sbt.md, metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
This is my first contribution attempt, let me know if this corresponds to the issue (#1142).
At the moment, the only test I've carried on is using my local version:
- with VSCode (`publishLocal`)
- compiling a `build.sbt` file with `javacOptions.in(Global) ++= Seq("-Dbloop.export-jar-classifiers=\"sources\"")`
=> Use bloop.export-jar-classifiers property

website/blog/2020-01-10-cobalt.md
Previously, the gif was showing a wrong extension.
=> Fix worksheet gif for cobalt release notes to show proper extension

docs/build-tools/sbt.md
Minor, but it currently shows the snapshot version which does not exist, since we stopped publishing `sbt-metals`.
=> Fix version of sbt-metals for pre 0.8.0 instructions

mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala
That require was causing some issue when `utf-8` was used and it actually doesn't cause the presentation compiler to break.
Fixes https://github.com/scalameta/metals/issues/1303
=> Change require to warning for the presentation compiler

metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/MavenBuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala, metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsSymbolSearch.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
Previously, there was not way to override all of the build plugins Bloop versions. Now we add a unified setting for doing so - one setting should be enough since for each workspace we can only use one build tool. 
Or do we want to have a separate setting for each build tool? That would be for 3 different ones: Sbt, Gradle and Maven.
I also promoted some setting to LSP ones.
=> Add an override for build tool plugin version and promote LSP settings

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala
fixes #1311 
We never hit this previously since we never were using this on the top level. However, now that we do in `.sc` files, we run into this. Just a quick fix to account for the beginning being 0, which it is when it's on the top level.
I also took out the comment since it was specific to VS Code settings, which imo didn't belong there.
=> Add in fix for onTypeFormatting on top level multi-line strings

docs/editors/vim.md, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
There has been some updates to the recommended mappings both from `coc.nvim` and a change in the way I do expands for worksheets.
While changing this up, I noticed this is a huge chunk of stuff to copy here in the docs. In the readme of `coc-metals` I ended up taking this out and instead just linking to a [recommended mapping file](https://github.com/scalameta/coc-metals/blob/master/coc-mappings.vim). Do you think that would be a good idea here to not clog up the docs so much, or do you think it's a good idea having this all right in the docs on the site?
=> Update recommended mappings with the latest

metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
As of recent versions of mill, the `$ivy` importers support
substituting `$MILL_VERSION` with the current version of mill.
The changes presented here modify the predef import to use the literal
`$MILL_VERSION` instead of a the value read from mill's version
file. While both these values are usually equivalent, they can differ
when using a local mill wrapper script (e.g. when developing and
testing mill locally).
In essence, the changes ensure that the correct bloop plugin will
always be used.
=> Use actual mill version in predef

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala, tests/unit/src/test/scala/tests/ImplementationLspSuite.scala
Previously, we would get implementation for if a parent local symbol name matched any other local symbol name. Now, we check if those are in the same file.
=> Fix issues when go to implementation resolves local symbols

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
fixes #1304
This will fix the warning that users are getting for example about a missing `/Users` directory or other superfluous warnings coming from non fatal errors when we scan the jar files. 
I went ahead and changed this to debug which was mentioned in the issue. If there is a scenario where you think this isn't ideal, what would that scenario be, and what is an alternative way to do this?
=> Change the non-fatal jar error to debug rather than log warning

metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
Fixes #1341 
`getBooleanKey("bloop-sbt-already-installed").getOrElse(true)` would always be setting this value to true unless the user specifically said they didn't have it installed via the setting. The fix will change this to get the setting or default to `false` which will correctly allow Metals to create the `metals.sbt` file that is needed for bloop.
=> fix logic for detected if bloop-sbt is already installed

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsExport.scala
Previously, the Bloop classpath would point to `z.jar` files under the
`.pants.d/` directory. This caused problems since those `z.jar` files
would later get overwritten by `./pants compile` tasks. Now, we copy
those files over to the `.bloop/` directory so that the Bloop classpath
is stable regardless of what Pants commands the user runs.
This commit also filters out classpath entries to jars that don't exist.
=> Copy jars from Pants export-classpath into Bloop directory.

metals/src/main/scala/scala/meta/internal/metals/Synthetics.scala, tests/unit/src/test/scala/tests/ReferenceLspSuite.scala
This would cause `_` below be showed as referenced
```scala
trait Document
class DD extends Document
trait Hello[T <: Document] {
implicit class Better[T <: Document](doc: T) {
def other() = {}
}
}
class He@@y extends Hello[DD] {
Some(new DD()).map(<<_>>.other())
}
```
reported to me offline - more coworkers using Metals! Yay!
As far as I checked this should not cause any regressions.
=> Do not accept synthetic symbol with matching qualifier

docs/build-tools/proxy.md, website/i18n/en.json, website/sidebars.json
Closes https://github.com/scalameta/metals/issues/1315
There is no perfect way to setup proxies for Bloop from Metals, so I decided to at least create a doc explaining different ways to setup your environment. This is a summary of Bloop, Coursier and Metals solutions.
=> Add documentation for using proxy and mirrors

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
Previously, when worksheet was created outside a build target it was not evaluated. Now, it's evaluated with the default Scala version, but without any classpath.
=> Add support for rambo worksheets without build target

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala
This release includes a critical fix for an issue that makes the Bloop
server unresponsive https://github.com/scalacenter/bloop/issues/1155
=> Upgrade to the latest junit-interface.

tests/slow/src/test/scala/tests/gradle/GradleLspSuite.scala, tests/slow/src/test/scala/tests/maven/MavenLspSuite.scala, tests/unit/src/test/scala/tests/BspSwitchLspSuite.scala
Based on empirical data from our CI, these tests are causing the build
to fail. See https://scalameta.org/metals/docs/contributors/tests.html
```
Name                                         Passed Failed
==========================================================
tests.BspSwitchLspSuite.switch               22     2
tests.gradle.GradleLspSuite.different-scala  11     2
tests.maven.MavenLspSuite.error              6      1
```
=> Mark flaky tests as flaky.

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala, metals/src/main/scala/scala/meta/internal/metals/Warnings.scala, metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala, metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala, tests/unit/src/main/scala/tests/MetalsTestEnrichments.scala, tests/unit/src/main/scala/tests/TestingServer.scala
Previously, we had to check if `ScalaTarget` is a Scala target, which was a bit confusing. Now, we include the target inside the ScalaTarget class and avoid running `asScalaBuildTarget` unneccessarily.
Overall, I think this makes sense and it annoyed me a bit when dealing with it. :sweat_smile:
=> Include ScalaBuildTarget in ScalaTarget 

metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala, tests/unit/src/test/scala/tests/RenameLspSuite.scala
Previously, if a symbol was renamed that wasn't a top-level definition in the file but had a matching name, the file could be renamed. Now, the file will only be renamed if the symbol is only enclosed by a package.
=> Rename file only if renamed symbol is directly enclosed by a package (closes #1380)

metals/src/main/scala/scala/meta/internal/pantsbuild/PantsConfiguration.scala
Previously, when exporting a large number of Pants targets, the export
step would fail with an "File name too long" error. Now, we guarantee
the name is always short so the error doesn't happen.
=> Avoid long filename for Pants output file.

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala
Previously, when exporting the Pants build to a separate directory the
`.scalafmt.conf` file in the original build did not get detected in the
exported build. Now, we insert a symbolic link to the config in the
original Pants build.
=> Add .scalafmt.conf symbolic link when exporting Pants build.

mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala
The exhaustive match completion was handling Java enums as if they were
types, whereas they should be matched as values, just like Scala modules
are. That is, the cases should have the form:
case MyEnumValue =>
Rather than the current, invalid:
case _: MyEnumValue =>
=> Fix exhaustive match completion on Java enums

build.sbt
Previously, we used the default MUnit test arguments when testing in CI.
In some cases, the CI logs haven't included recently what test suite
is failing so this change is an attempt to try and fix that by enabling
verbose loggers and telling MUnit to use the sbt loggers instead of
`System.out.println()`.
=> Enable verbose sbt loggers in CI.

metals/src/main/scala/scala/meta/internal/pantsbuild/Args.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/Cycles.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/Graph.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsConfiguration.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsExport.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTargetType.scala
There are cases where we automatically merge multiple Pants targets into
a single Bloop project. For example, this is needed for Pants targets
that use the `java_sources` option since those dependencies translate
into cyclic dependencies in the output of `./pants export`.
Previously, the logic for merging targets did not always work correctly.
This commit fixes several issues in the logic so that we can merge
almost any two targets more reliably.
Merging targets is not always be safe, for example when two targets
have dependencies with conflicting binary APIs. However, merging targets
can be helpful to either improve compilation performance (reduced number
of targets) or improve the IDE experience (IntelliJ doesn't support multiple
targets in the same directory)
=> Improve logic to merge Pants targets.

docs/editors/vim.md
This pr adds in vim documentation about the newly added Tree View Protocol implementation in coc-metals.
I plan to cut a release of coc-metals at the end of the week pending me not finding any other issues with the TVP new implementation. This is ready to be reviewed, but I'm going to leave it as a draft until I release. Then I'll turn it into a proper PR and hopefully merge it in to coincide with the release.
=> Add in tree view protocol docs for vim

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
Fixes #1258 
~This may not be the most elegant solution, but it seems to do the trick. This PR introduces a private`clientSupportsDidFocus` var in `MetalsLanguageServer` that defaults to false. This will help clients that don't support `didFocusTextDocument` to be able to move back and forth between scala files and worksheets correctly. In it's current state, this won't work once you leave the worksheet. This fixes that issue.~
~It does feel a bit eh doing it like this, so one alternative would be to just make this a client config value which defaults to false, and then for example in `coc-metals` and `vs code` we can have it set to true. Then, any other client that starts to support this, like the `lsp-mode` emacs folks https://github.com/emacs-lsp/lsp-mode/pull/1353, then they'd also …
=> Remove check for focused document on non-supporting editors

metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala
For build import: choose workspace Gradle wrapper if present over downloading version 5.3.1
Update minimum Gradle version to 4.3 as that is the minimum Bloop now supports
=> Use workspace level Gradle wrapper if present

metals-docs/src/main/scala/docs/UserConfigurationModifier.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfigurationOption.scala
This pr changes the way the available config options for metals is displayed in the vim editor page. They are displayed with dashes by default, but when a user is setting them using `coc-metals` they are displayed in camel-case when in `:CocConfig`. This was on oversight when I re-did the docs. This corrects that (only on the vim editor page).
=> Change config options to match coc

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala, metals/src/main/scala/scala/meta/internal/metals/debug/MetalsDebugAdapters.scala, metals/src/main/scala/scala/meta/internal/metals/debug/SetBreakpointsRequestHandler.scala
I'm trying to launch debugger from vim. I use this plugin
https://github.com/puremourning/vimspector
It starts and does first initialization query:
```
{
  "type": "request",
  "seq": 1,
  "command": "initialize",
  "arguments": {
    ....
    "pathFormat": "path",
    ....
  }
}
```
But even if it sets `pathFormat` to "path", metals returns path as URI in stackTraces (I get this log from dap-client.trace.json):
```
{
  "type": "response",
  "command": "stackTrace",
  "body": {
    "stackFrames": [
      {
        "id": 1,
        "source": {
          "name": "Test.scala",
          "path": "file:///home/dbykov/reps/test/src/main/scala/test/Test.scala",
          "sourceReference": 0
        },
      },
      ....
   ]
}
```
This breaks vimspector. I check dap-client.trace.json from …
=> Send stackTraces as paths rather than URIs

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
Previously, we would only send edits for open files when renaming. This causes an issue if the user wants to see a preview of all files.
Now, this changed to return up to threshold number of files for VS Code, so that preview can work correctly. The behavior is unchanged for other editors, since it might be problematic to save all files there.
Tested on ZIO and Akka, where there were over 200 files changed. It seems VS code is much more optimized now.
ZIO example:
=> Return all rename file changes up to a threshold

mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/MetalsGlobal.scala, mtags/src/main/scala/scala/meta/internal/pc/SignatureHelpProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/completions/ArgCompletions.scala, mtags/src/main/scala/scala/meta/internal/pc/completions/Completions.scala, mtags/src/main/scala/scala/meta/internal/pc/completions/FilenameCompletions.scala, mtags/src/main/scala/scala/meta/internal/pc/completions/InterpolatorCompletions.scala, mtags/src/main/scala/scala/meta/internal/pc/completions/MatchCaseCompletions.scala, mtags/src/main/scala/scala/meta/internal/pc/completions/NewCompletions.scala, mtags/src/main/scala/scala/meta/internal/pc/completions/NoneCompletions.scala, mtags/src/main/scala/scala/meta/internal/pc/completions/OverrideCompletions.scala, mtags/src/main/scala/scala/meta/internal/pc/completions/ScaladocCompletions.scala, mtags/src/main/scala/scala/meta/internal/pc/completions/TypeCompletions.scala
> split Completions.scala into smaller files, it's at ~1.6k lines now with a lot of unrelated functionality grouped in one place
https://github.com/scalameta/metals/issues/672
---
This PR split `Completions.scala` into smaller files and reduced the size of `Completions.scala` from 1.6K lines to around 800 lines.
- move each concrete class of `CompletePosition` (e.g. `MatchKeyword`, `InterpolatorType`) into another files.
- We already split some of them into smaller files
- ScaladocCompletions.scala https://github.com/scalameta/metals/pull/1250#discussion_r363080599
- OverrideCompletions.scala https://github.com/scalameta/metals/pull/1379
- move those files into `mtags/src/main/scala/scala/meta/internal/pc/completions/*.scala`
---
BTW, I used `ImportMissingSymbol` feature of Metals a lot …
=> Refactor: split Completions.scala into smaller files

metals-docs/src/main/scala/docs/BootstrapModifier.scala
`https://git.io/coursier` is 404
new get url is `https://git.io/coursier-cli`
ref https://get-coursier.io/docs/cli-overview.html#linux-macos
=> Fix download URL for Coursier command-line interface

docs/editors/emacs.md
While trying to configure LSP client Eglot I had an error when opening emacs, then I found the reason why:
https://github.com/melpa/melpa/issues/6091#issuecomment-477348940
=> Add missing config in Eglot

metals/src/main/scala/scala/meta/internal/metals/FileWatcher.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala, metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala
Previously, if the overflow event had a null path we wouldn't some references might get lost and things like renames wouldn't work properly. Now, when we are faced with an OVERFLOW event we reindex all build targets.
=> Make sure we properly handle overflow events even if the path is null

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala, metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala, tests/unit/src/test/scala/tests/RenameLspSuite.scala
Previously rename would not work with backticks. Now, the reference provider returns proper ranges not including the backticks, we an exact match is needed for renames.
Fixes https://github.com/scalameta/metals/issues/1421
=> Use proper range for references with backticks

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
Previously, if we had two targets for one file, like for example JS and JVM, we would get duplicated results due to 2 different semanticDB files being created. Now we check if a given file was already processed.
Prematurely closed https://github.com/scalameta/metals/pull/1450
There is actually another simple way to fix it.
=> Record visited Scala files to make sure they are not duplicated

metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
I went a little crazy with #1414 and since we aren't going to merge in https://github.com/scalameta/metals-vscode/pull/207 or https://github.com/scalameta/coc-metals/pull/74 until we do a release, these will need to stay in here. If not, when a user is using a snapshot of Metals, they won't have the necessary values set since they aren't being passed via experimental yet until those are merged. So, we need these for now.
=> add properties back in

docs/editors/overview.md
As a follow-up to the comment in the feature request about debug support with `dap-mode`, https://github.com/scalameta/metals-feature-requests/issues/84#issuecomment-589452103, I've gone ahead and updated the overview table to reflect that you can now run/debug in emacs.
=> add in checkmark for debug on emacs

metals/src/main/scala/scala/meta/internal/builds/PantsBuildTool.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTarget.scala, tests/slow/src/test/scala/tests/pants/PantsLspSuite.scala
This commit fixes some IntelliJ regressions that were caused by the
changes in https://github.com/scalameta/metals/pull/1452
=> Fix issues discovered while testing out IntelliJ integration.

docs/editors/new-editor.md, docs/editors/overview.md, metals/src/main/scala/scala/meta/internal/metals/ClientExperimentalCapabilities.scala, metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/DelegatingLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/JsonParser.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, metals/src/main/scala/scala/meta/internal/metals/NewFilesProvider.scala, metals/src/main/scala/scala/meta/internal/metals/NoopLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/test/scala/tests/NewFilesLspSuite.scala
After new-scala-file command has been added to metals https://github.com/scalameta/metals/pull/1339 , client-side service was discussed https://github.com/scalameta/metals-vscode/pull/183 , and it was decided to move and implemet quick-pick communication to server.
=> Add new LSP extension 'metals/pickInput' to implement the "Create Scala file" command

metals/src/main/scala/scala/meta/internal/metals/ClientExperimentalCapabilities.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
This setting was merged in right around when I was doing #1414, so I didn't include it. However, this can also go into `ClientExperimentalCapabilities`. It's also very VS Code specific, so we may be able to just fully remove it from the ServerConfig options.
To summarize, this pr moves the `metalsconfig.openFilesOnRenames` to an experimental provider. I'll also add this into the vscode extension.
=> add openFilesOnRenameProvider to experimental

metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/MavenBuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala, metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
Previously. the warning about Bloop version change would pop up always when starting the workspace when the user had a non default setting. Now, the default is changed to None, which stops the consistent warning.
=> Fix issue when warning about Bloop version change 

metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
Now that #1414 is merged and we have versioned, these properties are being set in experimental capabilities via the client. They are no longer needed to be set here.
=> Remove properties that are no longer needed

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala, mtags/src/main/scala/scala/meta/internal/metals/ScaladocIndexer.scala, tests/unit/src/test/scala/tests/HoverLspSuite.scala
Fixes https://github.com/scalameta/metals/issues/1471
Since the cache in `scala.meta.internal.metals.Docstrings` never expired, once the docstring for the symbol has cached, it won't update until the metals server restart.
That's why even if we update Javadoc comments, the change won't reflect the docstrings showed on hover as https://github.com/scalameta/metals/issues/1471.
- Implemented `Docstrings#didChange(symbols: Seq[String]): Unit` that expires the cache for the docstrings of given (scalameta) symbols.
- Call `Docstrings#didChange` method on save (from `indexSourceFile`).
=> Expire docstrings' cache on save

docs/editors/vim.md
This pr adds in some new documentation on the statusline integration in the last release of coc-metals, which now supports the `metals/status`.
=> Add in new statusline info from latest release

metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala, tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala
This prs adds in logic that will protect from getting indexOutOfBounds exceptions when the user is at the beginning of a file and inserts a new line.
Closes #1469
=> Add in math max when looking for lastIndex

metals/src/main/scala/scala/meta/internal/implementation/ClassLocation.scala, metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala, metals/src/main/scala/scala/meta/internal/implementation/MethodImplementation.scala, tests/unit/src/test/scala/tests/RenameLspSuite.scala
Currently rename doesn't find proper top level class when generics are involved in inheritance hierarchy.
Added test describes problematic scenario. 
`AsSeenFrom` values were not translated during searching for a top level class and in resolving this map wrong `ClassSignature` was provided.
After changing those 2 issues test passes and rename works properly in VSCode.
=> Fix rename for hierarchy with generics

metals/src/main/scala/scala/meta/internal/implementation/MethodImplementation.scala, tests/unit/src/test/scala/tests/RenameLspSuite.scala
Fixes  #1474
Currently we check in rename that both methods must have strictly same return type.
In overridden method is is possible to return subtype of a type returned in parent. We could check if a return type of overridden method is subtype of returned parent type.
But it is not needed as return type is not used in scala for method comparison which means there is no possibility to define 2 methods being only different by return type. 
Scala will not compile such situation therefere it is okay to omit checking return type in rename because either methods will match or file will not compile.
=> During rename matching methods ignore return type

build.sbt, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedCommand.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/ZipkinUrls.scala
We currently can only submit traces to Bloop's default of `http://127.0.0.1:9411/api/v2/spans`, unless we manually write to `~/.bloop/.jvmopts`. This change will allow `BloopPants` to write to `~/.bloop/.jvmopts` automatically. Binary versions of `fastpass` can be built with the correct server url statically embedded.
=> Add ability to specify zipkin url for fastpass

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala
Followup on https://github.com/scalameta/metals/pull/1467
fixes the glob to actually delete the other json files
=> Don't delete bloop.settings.json when exporting Pants builds

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala
Previously, Metals deleted the `bloop.settings.json` file after
exporting a Pants build.
=> Don't delete bloop.settings.json when exporting Pants builds.

metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/ExportOptions.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedCommand.scala
Users will now be able to optionally specify a path to their `coursier` binary to skip downloading it.
=> Skip coursier download in fastpass create with --coursier-binary option

build.sbt, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
Fixes #1456. Previously, fatal exceptions were not caught while
evaluating worksheet making them stay stuck in "evaluating". Now,
fatal exceptions are caught in mdoc and are reported inline
in worksheets like normal non-fatal exceptions.
=> Handle fatal exceptions when evaluating worksheets.

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/ExportOptions.scala
In some cases, metals generate synthetic '*-project-root' modules. The
new `--no-root-project' unconditionally prevents from it.
=> New `create` option:--no-root-project option

metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/test/scala/tests/BuildServerConnectionLspSuite.scala
Previously, we were being asked to restart Bloop each time we opened a new window and the Bloop default version was changed. This is due to the fact that those settings are only being sent later on and not part of the default settings. Now, we only ask to restart if we know that the running version is different than the one specified. There might be a race condition, where those settings are sent after the connection to Bloop is established, but there is really no way around it.
I was sure I fixed it previously, but this was not the case.
There are be 3 scenarios when we ask to restart Bloop:
- bloop version is too old - that's a separate case after establishing a connection
- if the version doesn't correspond to the one set in the settings - nothing happens if no setting for Bloop was …
=> Fix Bloop sending a restart message when custom version of Bloop is used

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/ExportOptions.scala
Don't generate synthetic '*-project-root' modules. Their only purpose
was to help improve the "Project Files" view in IntelliJ.
According to https://github.com/scalameta/metals/pull/1490#pullrequestreview-374238184
=> Do not generate synthetic modules

build.sbt, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala, metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala, metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala, metals/src/main/scala/scala/meta/metals/DownloadDependencies.scala
Previously, there was no convenient way to build a Docker image with all
of Metals dependencies pre-cached. This commit adds a new
`DownloadDependencies` main entrypoint that downloads artifacts that
Metals is likely to depend on.
You can launch this tool with the following script (requires Java 8 installation or newer), which should work on Linux and macOS.
```sh
METALS_VERSION=0.8.2 # Not released yet
curl -Lo coursier https://git.io/coursier-cli
chmod +x coursier
./coursier launch org.scalameta:metals_2.12:$METALS_VERSION --main scala.meta.metals.DownloadDependencies
```
We can't guarantee Metals will always work offline after running this
method. For example, the following cases are not handled:
* user opens Metals in a Gradle/Maven/Mill/sbt build.
* user has configured an older …
=> Add helper to pre-download Metals dependencies.

metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala, tests/unit/src/test/scala/tests/RangeFormattingSuite.scala
This pr changes the way we check for the default indent when doing onTypeFormatting. Instead of checking all the text on the page, we just check a substring of the text from the previous line. Then we grab the first index of the pipe to ensure we are actually getting the pipe from the multiline rather than a pipe that might be in the string. This also works in worksheets when on the first line, since the position of the onTypeFormatting will start on the second line, so there should be no worry there to get a indexOutOfBounds exception. I also added a couple tests to test when we have multiple multiline strings in a file.
Closes #1477
=> Only check relevant text for default indent

bin/test-release.sh, build.sbt, mtags/src/main/scala/scala/meta/internal/pc/completions/Completions.scala, project/plugins.sbt, sbt, test-workspace/build.sbt, tests/cross/src/main/scala/tests/BaseCompletionSuite.scala, tests/slow/src/test/resources/test-pom.xml, tests/slow/src/test/scala/tests/SymlinkedProjectSuite.scala, tests/slow/src/test/scala/tests/gradle/GradleLspSuite.scala, tests/slow/src/test/scala/tests/mill/MillLspSuite.scala, tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala, tests/unit/src/main/scala/tests/QuickBuild.scala, tests/unit/src/test/scala/tests/SyntaxErrorLspSuite.scala, tests/unit/src/test/scala/tests/digest/MillDigestSuite.scala
This PR adds support for Scala 2.12.11, ~~however we need to wait with the stable release until https://github.com/scalameta/scalameta/pull/2004 is merged.~~
~~Semanticdb is causing Bloop to behave rather flakily, but that is under 4.3.4 version too.~~
Updated to 4.3.6, which should have everything fixed.
=> Add support for Scala 2.12.11

metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/OpenCommand.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/OpenOptions.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedCommand.scala
Previously, it was not possible to export a Pants build and launch
IntelliJ with a custom IntelliJ version (for example, 2020.1 EAP).
Now, the `--intellij-launcher APP` flag allows users to pass in a custom
launcher.
=> Use a custom IDEA launcher under a new flag.

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/metals/RamboSymbolSearch.scala, metals/src/main/scala/scala/meta/metals/DownloadDependencies.scala, mtags/src/main/scala/scala/meta/internal/metals/PackageIndex.scala, tests/slow/src/test/scala/tests/feature/CompletionCrossLspSuite.scala, tests/unit/src/test/scala/tests/DefinitionLspSuite.scala, tests/unit/src/test/scala/tests/HoverLspSuite.scala
Previously. the 2.12.10 library was indexed in a target even if the target used only 2.13.1 Scala version. Now, only the right libraries are included.
=> Do not include scala boot library

build.sbt, metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala
This PR is regarding https://github.com/scalacenter/bloop/issues/1182 i.e. bloop can run custom refresh project command before requesting build targets which is implemented in https://github.com/scalacenter/bloop/pull/1195 this PR adds logic to generate the config file with refresh command that will invoke fastpass.
=> Generate bloop.settings.json with project refresh command

metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala
Commit da56189c introduced a hack, that was applicable for IntelliJ
2019.3. It required to open the root's parent directory instead of the
root directory, except the first time, when the project was imported.
In IntelliJ it's safe to always open the root directory. What is more,
opening the parent directory couses that, the project is not
identified as BSP-based.
=> Always launch IntelliJ in the project's root directory

build.sbt
Currently, users get the following warning
> You are using a legacy Scala version 2.12.10, which might not be
> supported in future versions of Metals. Please upgrade to Scala 2.12.11.
Scala 2.12.11 just came out, we should wait at least a few months before
calling it "legacy".
=> Undeprecate 2.12.10.

build.sbt, docs/editors/decoration-protocol.md, metals/src/main/scala/scala/meta/internal/decorations/DecorationClient.scala, metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala, metals/src/main/scala/scala/meta/internal/worksheets/DecorationWorksheetPublisher.scala, mtags/src/main/scala/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala/scala/meta/internal/pc/HoverMarkup.scala, mtags/src/main/scala/scala/meta/internal/pc/HoverProvider.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
Since there was a couple issues that mentioned things that LSP 3.15 supports (such as progress), I figured it'd be a good idea to update to the latest 0.9.0 if lsp4j which implements most of 3.15. I also went through and removed/updated a few of the deprecated things.
In short this pr:
- updates the lsp4j library
- removes and replaces some deprecation with the lsp4j update
=> Update lsp4j to enable more 3.15 support

metals/src/main/scala/scala/meta/internal/metals/NewFilesProvider.scala, tests/unit/src/test/scala/tests/NewFilesLspSuite.scala
Closes #1524 
Previously we would offer the choice to create:
- class
- object
- trait
- package object
- worksheet
now we also include "case class" right after "class"
=> Add "case class" option in NewFilesProvider

build.sbt, tests/cross/src/main/scala/tests/BasePCSuite.scala, tests/mtest/src/main/scala/tests/BaseSuite.scala, tests/unit/src/main/scala/tests/BaseLspSuite.scala, tests/unit/src/test/scala/tests/CompletionLspSuite.scala
The pr updates to the latest munit. It follows the new pattern of using `TestTransforms` that this commit demonstrates and outlines https://github.com/scalameta/munit/commit/f2d277df78d159ef644727416fdf8281e1e1e4f2.
Closes #1527
=> Update to latest munit

metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateNewSymbol.scala, tests/unit/src/test/scala/tests/codeactions/CreateNewSymbolLspSuite.scala, tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala
Previously we would only add "Create new symbol" actions if the diagnostic range enclosed the code action range.
Now we suggest the action if the ranges overlap, which means we can suggest the action multiple times (one per missing symbol in the range).
This also fixes https://github.com/scalameta/coc-metals/issues/134 /cc @ckipp01
=> Allow multiple "Create new symbol" actions on a range

metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
I just realised that I was totally mistaken before and the code lenses will work without the VS Code release.
@kpbochenek To confirm.
=> Change go to parent lenses to true by default

build.sbt, metals/src/main/scala/scala/meta/internal/metals/NewFileTemplate.scala, metals/src/main/scala/scala/meta/internal/metals/NewFilesProvider.scala, metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala, tests/unit/src/test/scala/tests/NewFileTemplateSuite.scala
Closes #1529 
Previously we would set the cursor position at the beginning of the file when creating a new file. Now we place the cursor in a more convenient position, depending on the type of file.
Demo:
=> Specify cursor position when creating new files

metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTargetType.scala
These targets have no source code and are not supposed to be compiled by
Bloop. These targets have conflicting base directories with other
targets causing highlighting bugs in IntelliJ.
=> Remove Pants targets of type 'target'

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala, tests/mtest/src/main/scala/tests/Assertions.scala, tests/unit/src/main/scala/tests/BaseRangesSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/ImplementationLspSuite.scala, tests/unit/src/test/scala/tests/ReferenceLspSuite.scala
This is a naive approach to close #1520 which sorts the references before they are returned. @tgodzik you mentioned changing to a sorted collection, but I wasn't sure how to do a sorted builder, or if that was what you actually meant. I didn't want to get rid of the builder as I assumed that it was used for performance. So this approach just sorts the collection right as it's about to be returned.
=> Sort references before returning them

build.sbt, docs/contributors/remote-language-server.md, metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/DefinitionResult.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsHttpServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, metals/src/main/scala/scala/meta/internal/remotels/RemoteLanguageServer.scala, metals/src/main/scala/scala/meta/internal/remotels/RemoteLocationResult.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/remotels/RemoteLanguageServerLspSuite.scala, tests/unit/src/test/scala/tests/remotels/TestingRemoteLanguageServer.scala, website/sidebars.json
Previously, Metals only supported responding to definition/requests from a local index that was built by Metals. For some large codebases it's not practical to index all the code locally making it difficult to use Metals.
Now, Metals supports querying a remote language server as a fallback when the local index is not able to respond to definition/references requests. This feature is especially helpful in a large monorepo where there exists a lot of code but the user is only actively working on a small part of the codebase. With a remote language server, users can query the remote language server for source files that the user is not editing without building a local index.
Big thanks to @ShaneDelmore who has implemented a remote language server that is backed by a SQL index of SemanticDBs. …
=> Add support to query remote language server as fallback.

tests/unit/src/test/scala/tests/HoverLspSuite.scala
This test has been failing quite often on windows. Following up on the comment on one of the recents prs, I'm marking the `basic-rambo` test in the hover suite as `FlakyWindows`
=> Add FlakyWindows tags to the hover suite

build.sbt, tests/unit/src/test/scala/tests/NewFileTemplateSuite.scala
Followup of https://github.com/scalameta/metals/pull/1546#discussion_r399216837
I was a bit too eager to add Scalacheck to test the new MUnit module, but it wasn't really necessary.
=> Remove scalacheck

.scalasteward.conf
This pr adds in a conf file for scalasteward. I recently added metals back in [here](https://github.com/scala-steward-org/repos/pull/253). I figured setting the frequency to weekly? to start out with was a good middle ground? What do you guys think? Also, is there any dependencies we want ignored by steward? You can see the configuration options [here](https://github.com/fthomas/scala-steward/blob/master/docs/repo-specific-configuration.md).
=> Add in the scala steward conf file

metals/src/main/scala/scala/meta/internal/implementation/Supermethods.scala, metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/NewFilesProvider.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/Graph.scala, metals/src/main/scala/scala/meta/internal/worksheets/WorkspaceEditWorksheetPublisher.scala, mtags/src/main/scala/scala/meta/internal/mtags/ScalaMtags.scala, tests/unit/src/main/scala/tests/TestingServer.scala
A bit more house-keeping.
This pr removes a couple of the other deprecations from the lsp4j update recently. I also just went ahead and updated the other stuff that I noticed when adding the `-deprecation` flag. However, the two that I didn't update seem to be a bit more involved, so I left them as is.
The remaining deprecated warnings are:
1. The usage of `Thread.stop()` if various places
2. The usage of `PlatformTokenizerCache.megaCache.clear()`
=> Remove deprecations

metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala, metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala, mtags/src/main/scala/scala/meta/internal/semver/SemVer.scala, tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala, tests/unit/src/test/scala/tests/BillLspSuite.scala, tests/unit/src/test/scala/tests/MessagesSuite.scala, tests/unit/src/test/scala/tests/ScalaVersionsSuite.scala, tests/unit/src/test/scala/tests/WarningsLspSuite.scala
Previously, we would recommened Scala 2.12.11 even if the user is already using 2.13. Also, when using an unsupported Scala version we would just say that project is misconfigured, which is the same in case of a missing semanticDB. 
Now, we recommend the last version for each binary except 2.11. And we also display if any Scala version is unsupported in the warning.
Closes https://github.com/scalameta/metals/issues/1548
=> Fix recommendations for Scala versions and add better messages.

mtags/src/main/scala/scala/meta/internal/pc/HoverProvider.scala, tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala
Previously, when using hover over the Scala App trait no information would be returned. Now, it's properly displayed with all needed docs. This also works with a number of other cases in for example Play projects.
Removing the condition altogether would cause anonymous classes to be shown like, so I just changed it to detect the specific scenario.
=> Make sure we detect scala App trait when using hover. 

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsExport.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsKeys.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTarget.scala
Previously, the exported Bloop projects had an empty Scalac options
list. Now, we forward compiler options like warning about unused
imports.
=> Forward compiler options in Pants export.

metals/src/main/scala/scala/meta/internal/implementation/SuperMethodProvider.scala, tests/unit/src/test/scala/tests/SuperMethodLspSuite.scala
Forgot to include ` "scala/Any#"` in list of ignored parent classes
@tgodzik thanks for reporting!
=> Fix: don't show super lenses on synthetic methods e.g. toString

metals/src/main/scala/scala/meta/internal/worksheets/DecorationWorksheetPublisher.scala, metals/src/main/scala/scala/meta/internal/worksheets/MdocEnrichments.scala, metals/src/main/scala/scala/meta/internal/worksheets/WorkspaceEditWorksheetPublisher.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
This pr adds in a way to signify in worksheets that a lint is truncated or continued. For example instead of just ending, you'll now see that the line will end in a `...`. It's not added to the end to lengthen the line, but if what we are showing is not complete, we drop the last 3 chars and replace them.
Closes #1575
=> Add in ... to signifigy truncation in worksheets

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsExport.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsKeys.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/PantsTarget.scala
Previously, we did not export custom JVM options that are defined in Pants to Bloop. Now, those JVM options are forwarded to Bloop so that bloop test respect original Pants configuration like memory settings or GC flags.
=> Support `extra_jvm_options` from Pants

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/ExportOptions.scala
I deleted the `-project-root` generation code as I thought because it could be detected by IntelliJ Scala Plugin as a parent target for a test during test run. Now, after the target detection in the plugin was improved, it seems to be safe to generate these modules.
=> Project root again

metals/src/main/scala/scala/meta/internal/pantsbuild/PantsGlobs.scala
Previously, targets with only recursive globs like `**.scala` got
translated into Bloop globs that eventually get expanded into a list of
individual files in BSP. Now, these entries get expanded into
directories so that they become BSP directories.
=> Convert recursive Pants globs into directory entries.

metals-docs/src/main/resources/META-INF/services/mdoc.StringModifier, metals-docs/src/main/scala/docs/VersionedDocsModifier.scala, mtags/src/main/scala/scala/meta/internal/semver/SemVer.scala, website/i18n/en.json
This PR adds a custom mdoc modifier that inserts a warning about unreleased features in the documentation.
The idea is that we can freely merge documentation for unreleased features, and the warning will be displayed until we release a stable version.
Assuming the latest stable is 0.8.3, the demo shows how the warning is displayed when using `mdoc:since:0.8.4` but it's not displayed when using `mdoc:since:0.8.2`
=> Add VersionedDocsModifier

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala, tests/unit/src/test/scala/tests/RangeFormattingWhenPastingSuite.scala, tests/unit/src/test/scala/tests/RangeFormattingWhenSelectingSuite.scala
The goal is to list the tests we would like to see working.
In the gif below, I listed all cases that work/don't work
closes #1509
=> fix indentation for multiline string when using format selection

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, metals/src/main/scala/scala/meta/internal/metals/Compilations.scala, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java, mtags/src/main/scala/scala/meta/internal/pc/CompilerAccess.scala, mtags/src/main/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala, tests/unit/src/test/scala/tests/CompilersLspSuite.scala, tests/unit/src/test/scala/tests/InverseDependenciesSuite.scala
Previously, Metals didn't correctly reset all presentation compiler
after a successful compilation. Users could observe this bug when
completions don't return symbols from other files that have been
recently changed.
Now, Metals resets all presentation compilers that may be affected by a
successful compile notification making it less likely that
completions/hover/signatureHelp return stale results.
This root cause of this bug was discovered in #1523 by Tomasz. The
problem was that Metals only collected the leaf build targets that
depend on the compiled target. Now, we reset all inverse dependencies
regardless if they're leaf targets or not.
=> Fix bug around resetting presentation compilers.

metals/src/main/scala/scala/meta/internal/metals/NewFilesProvider.scala, tests/unit/src/test/scala/tests/NewFilesLspSuite.scala
This will allow us to have the `New Scala File` option also when right clicking on a file.
=> Create a new file next to an existing one if user selected a file 

metals/src/main/scala/scala/meta/internal/pantsbuild/commands/BloopGlobalSettings.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/BloopZipkinTraceProperties.scala, metals/src/main/scala/scala/meta/internal/zipkin/Property.scala, metals/src/main/scala/scala/meta/internal/zipkin/ZipkinProperties.scala, metals/src/main/scala/scala/meta/internal/zipkin/ZipkinUrls.scala
This change adds the properties introduced in https://github.com/scalacenter/bloop/pull/1231 to fastpass.
=> Add properties for bloop zipkin tracing to fastpass

metals/src/main/scala/scala/meta/internal/metals/MetalsHttpClient.scala
To fix https://github.com/scalameta/metals/issues/1605 .
Sublime client has `isHttpEnabled` configuration `on` by default, and this prevents the language server from sending `metalsInputBox` request, even if `metals.input-box` is set to `on`.
Changed the Http client (layer) to delegate the method to it's underlying client (which, by the way, in practice happens to be a `ConfiguredLanguageClient`, that does the configuration check).
=> Http client delegates `metalsInputBox` to the underlying client

metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala
=> Don't generate timestamp in `.bsp/bloop.json` file.

metals/src/main/scala/scala/meta/internal/metals/MetalsLogger.scala
I think it can be useful to show date in metals logs
```
2020.04.16 11:31:34 INFO  Connected to Build server v1.4.0-RC1-162-888454e1
2020.04.16 11:31:34 INFO  time: indexed workspace in 0.54s
2020.04.16 11:31:51 INFO  shutting down Metals
```
=> Show date in logs

metals/src/main/scala/scala/meta/internal/metals/FileWatcher.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, tests/unit/src/test/scala/tests/MetalsEnrichmentsSuite.scala
The issue was that we create directories recursively, but we delete only the child one.
fixes #1609
=> Delete all created folders created for the FileWatcher

metals/src/main/scala/scala/meta/internal/metals/BuildTargetClasses.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, tests/slow/src/test/scala/tests/feature/CrossCodeLensLspSuite.scala, tests/unit/src/main/scala/tests/BaseCodeLensLspSuite.scala, tests/unit/src/test/scala/tests/CodeLensLspSuite.scala
Previously, code lenses were only available on classes, now we also show them for main methods.
I am wondering if this should actually be generated differently in Dotty.
@bishabosha Main methods symbol is now shown as `foo/Foo$package.main().` while this is not something that can actually be run. I propose a bit of a hack here to generate a potential main method symbol. I am not sure if that is the right solution though. How is it being done in Dotty itself? Should we generate a different symbol for semanticDB if it's a main method?
=> Detect Scala 3 main outer methods to create code lenses

metals/src/main/scala/scala/meta/internal/pantsbuild/commands/BloopGlobalSettings.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedCommand.scala, metals/src/main/scala/scala/meta/internal/zipkin/Property.scala
Previously, properties could only be read statically, as that was necessary for linking the properties statically during native-image build. 
This change will allow users to set a `fastpass/fastpass.properties` file in the root of their workspace to pass along zipkin properties for Bloop. It's meant to solve the problem posed by running `fastpass` via `coursier` as in: https://github.com/pantsbuild/intellij-pants-plugin/pull/516
=> Dynamically read fastpass zipkin properties from fastpass/fastpass.properties

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, tests/slow/src/test/scala/tests/feature/FoldingCrossLspSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/FoldingRangeLspSuite.scala
Previously, we would only download mtags module and reuse the semanticDB jars on the classpath, but that can cause other libraries not be fetched and cause unpredictable or easy to miss runtime issues.
Now, we fetch all the transitive dependencies of mtags.
Fixes https://github.com/scalameta/metals/issues/1647
=> Remove optimisation to reuse semanticdb jar from the classpath

docs/editors/new-editor.md, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/DelegatingLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala, metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/StatusBar.scala, mtags/src/main/scala/scala/meta/internal/pc/CompilerInitializationOptions.scala, mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala, tests/unit/src/test/scala/tests/StatusBarSuite.scala
fixes https://github.com/scalameta/metals/issues/1614
Migrated from `clientExperimentalCapabilities`
Migrated from server properties 
The following have been left out because they are none boolean settings so we have to decide on a priority if setting is set both ways: 
- icons
- glob-syntax
- completionCommand
- signature-help.command
- overrideDefFormat
=> Handle initialization options

metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
For several commands the `arguments` field was left with its default value `null`
while the description mentioned arguments to be sent as seen bellow:
=> Properly set the arguments field in sever commands documentation

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala, tests/slow/src/test/scala/tests/feature/RenameCrossLspSuite.scala, tests/unit/src/main/scala/tests/BaseRenameLspSuite.scala, tests/unit/src/test/scala/tests/RenameLspSuite.scala
Previously, we would use GlobalSymbolIndex, which might not always work for Scala 3 in case of non-parsable code. Now, we use the definitionProvider, which will in turn ask the PresentationCompiler if the definition is missing. For Scala 2 it will still work mostly the same.
The test might fail locally due to issue being fixed https://github.com/scalacenter/bloop/pull/1253, which makes the test fail on even tries :sweat_smile:
=> Use DefinitionProvider instead of index in RenameProvider 

metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, tests/unit/src/test/scala/tests/CodeLensLspSuite.scala
Turning them off until we can get the situation under control.
=> Turn off go to parent code lenses by default

metals/src/main/scala/scala/meta/internal/metals/BuildTargetClassesFinder.scala, metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsBuildClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala, tests/unit/src/test/scala/tests/DebugProtocolSuite.scala
Previously, run/debug would hang if run in a broken workspace. Now, we display all issue about why we weren't able and make sure that we only allow run on a clean workspace.
Fixes https://github.com/scalameta/metals/issues/1641
When running in a workspace with errors:
When running non existing class:
When running non exiting target:
When running class not in a target, but the target was defined:
=> Make sure that the workspace contains no errors when running 

metals/src/main/scala/scala/meta/internal/zipkin/ZipkinProperties.scala
This change allows fastpass to configure additional Bloop Zipkin properties, specifically with trace verbosity and setting the `debug` sampling flag.
=> Add Bloop zipkin trace debug and verbose settings

metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/process/SystemProcess.scala
Previously, fastpass printed a large non-helpful stacktrace when the
Pants export-dep-as-jar command failed (which happens frequently). Now,
fastpass prints a more readable message without a stacktrace
making it easier to find the Pants error message.
=> Improve rendering of Pants command errors.

metals/src/main/scala/scala/meta/internal/metals/DismissedNotifications.scala, metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
When "Format on Compile" or "Format on Save" is enabled in the editor-wide settings, Metals asks `.scalafmt.conf` creation every time. It would be nice if the dialog has a volatile "Don't ask again" option for `.scalafmt.conf` creation.
=> Don't ask .scalafmt.conf creation again

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala, metals/src/main/scala/scala/meta/internal/implementation/SuperMethodProvider.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/codelenses/SuperMethodCodeLens.scala
Currently when we search for a symbol definition we firstly check if it exists in current document.
We do that by going one by one and comparing. It is okay for single pass, but checking multiple symbols is very inefficient. This converts list of symbols to a map [symbol -> symbolinformation].
When we found parent class for given method we fetched each method of parent class and checked if it is super method. We compared method 'f' to X#aaa(), X#bbb(), X#f(), but it is easy to see don't need to fetch methods and compare types if names don't match.
Added a map to memoize SymbolInformation for single request. I will verify how much it actually helps but wanted to get your opinion what you think.
Added logging if lenses generation takes longer than 1s.
=> Improve code lens generation time

metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala, metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala
Previously debuggingProvider, decorationProvider, openFilesOnRenameProvider,
and treeViewProvider were only able to be set via `ClientExperimentalCapabilities`.
Now these are also able to be set via `InitializationOption`, which for some clients
are much easier to set. This is the case for the built-in LSP support in Nvim
=> Move additional settings to InitializationOptions

mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala, mtags/src/main/scala-2/scala/meta/internal/pc/AutoImports.scala, tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala, tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala
fixes https://github.com/scalameta/metals/issues/1669
The tree is read from ground to top and get the first package he sees which is a package object in our case. Reversing the tree should do the trick. 
I'm not totally sure, sounds too easy :)
=> fix auto import position when package object inside package

metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala, metals/src/main/scala/scala/meta/internal/metals/BspServers.scala, metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala, metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, metals/src/main/scala/scala/meta/internal/metals/Compilations.scala, metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala, metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala, metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala, metals/src/main/scala/scala/meta/internal/tvp/TreeViewNode.scala, metals/src/main/scala/scala/meta/internal/tvp/TreeViewProvider.scala, tests/unit/src/main/scala/bill/Bill.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/BillLspSuite.scala, tests/unit/src/test/scala/tests/TreeViewLspSuite.scala
Previously, we would only reconnect if the user asked for it and often this would not show up quickly.
Now, we make the reconnection work better by:
- reconnecting as soon as the build server is disconnected (fixes https://github.com/scalameta/metals/issues/1354)
- making reconnection automatic unless the user specifically asks for it not to be via system property `metals.ask-to-reconnect=true`
- moving compilation outside the initial build server connection - longer running compilations would then produce invalid exceptions and break the next connection
- reindexing and compiling the workspace on reconnection (this is needed since workspaces would not have all the classpath updated)
Also in this PR:
-  a new clean-compile command was introduced, which together with the restart bloop …
=> Reworked Bloop connection and Tree View

build.sbt, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/metals/DownloadDependencies.scala
Previously, we would try to download mtags for Scala 0.24 etc. which does not exist. Now we make sure that we only download proper dependencies.
=> Make sure we don't download invalid dependencies for Scala 3 

metals/src/main/resources/millw.bat, metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
This pull request fixes two problems:
1) Issue 1: In some Windows environments (e.g. WSL or cygwin) running mill results in an error: Failed to connect to server. The workaround as indicated on http://www.lihaoyi.com/mill/index.html is to run mill in interactive mode using `-i` option. As explained by @lefou on the referenced issue, it is safe to always run with this option.
2) Issue 2: The millw.bat takes an option "--mill-version" in order to download the specified version of mill. millw afterwards executes mill by passing all the same options including the "--mill-version". This option, however, is not known by mill, so it must be stripped before passing the remaining options.
Fixes #1710
=> Always run mill in interactive mode and strip the '--mill-version'

metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala
My previous pull request https://github.com/scalameta/metals/pull/1607 contains a trivial issue that dismisses forever when we close the format dialog without choosing any action. It should do nothing in this case.
=> Fix behavir when the format dialog is closed without choosing action

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProtocol.scala, metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala, tests/unit/src/main/scala/tests/BaseDapSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/DebugProtocolSuite.scala, tests/unit/src/test/scala/tests/debug/BreakpointDapSuite.scala, tests/unit/src/test/scala/tests/debug/StackFrameDapSuite.scala, tests/unit/src/test/scala/tests/debug/StepDapSuite.scala
Trying to fix the issues with the DAP Suites:
- we now print the DAP traces on failures
- added System.exit(0) to all main methods to avoid [this issue](https://stackoverflow.com/questions/2225737/error-jdwp-unable-to-get-jni-1-2-environment), which caused rare but consistent failures
=> Try to fix Debug Adapter Suites

metals-bench/src/main/scala/bench/MetalsBench.scala, metals/src/main/scala/scala/meta/internal/builds/Digest.scala, metals/src/main/scala/scala/meta/internal/builds/MillDigest.scala, mtags/src/main/scala-2/scala/meta/internal/docstrings/MarkdownGenerator.scala, mtags/src/main/scala-2/scala/meta/internal/metals/MultilineStringFormattingProvider.scala, mtags/src/main/scala-2/scala/meta/internal/metals/TokenEditDistance.scala, mtags/src/main/scala-2/scala/meta/internal/metals/Trees.scala, mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala, mtags/src/main/scala-2/scala/meta/internal/mtags/ScalaMtags.scala, tests/slow/src/test/scala/tests/feature/DefinitionCrossLspSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/DefinitionSuite.scala
Fixes https://github.com/scalameta/metals/issues/1664
Previously, we would use 2.12 parser and tokenizer by default. Now we define the default dialect as 2.13 in one place and make sure it's used everywhere.
=> Fix issues in files with Scala 2.13 specific syntax

metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala
This will be consumed by pants plugin to handle automatic fastpass updates.
=> Expose fastpass metadata in .bsp/bloop.json

metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
This PR provides an escape hatch to Emacs users who find the beahvior documented in
formatting can opt-in to this behavior.
My main concern is that this change appears not backwards compatible. I am not familiar
with Metals JSON deserialization system. Ideally the `InitializationOptions` would
default to `true` for `provideRangeFormater` if it is not present in the JSON payload
from the `initialize` request.
I will make a corresponding change to https://github.com/emacs-lsp/lsp-mode to support
this new configuration option.
Thank you for your time.
I tried to test this locally, but after running `sbt +publishLocal`, I can't build a Scala-metals binary as described under the vim section of the contributing docs (there is no Emacs section):
```
~/projects/metals/coursier bootstrap \ …
```
=> teach metals to accept configuration of range formatting

mtags/src/main/scala-2/scala/meta/internal/metals/MultilineStringFormattingProvider.scala, tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala, tests/unit/src/test/scala/tests/RangeFormattingWhenPastingSuite.scala
Missing condition on when to stop formatting a string
fixes  #1712
=> Bugfix - formatting for multilines adds pipe in the wrong place

metals/src/main/scala/scala/meta/internal/builds/PantsBuildTool.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/Export.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/IntelliJ.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/CreateCommand.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/ExportOptions.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/Project.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/ProjectRoot.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/RefreshCommand.scala, metals/src/main/scala/scala/meta/internal/pantsbuild/commands/SharedCommand.scala
Previously, we didn't export library dependency sources with Pants since
it wasn't possible with the Pants v1.25 `export-dep-as-jar`. Now, we can
use `--export-dep-as-jar-libraries-sources` that got added in Pants
v1.26.
=> Export Pants 3rdparty sources

mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala, tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala
Fixes #1759
Not sure if this is a bug or intended behaviour but `flagString` generates modifiers like `protected[package x.y.z]` and they need to be stripped manually.
=> Keep modifiers when implementing abstract members

mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala, mtags/src/main/scala/scala/meta/internal/mtags/ClasspathLoader.scala, tests/unit/src/test/scala/tests/JdkSourcesSuite.scala
Previously, we would not find any java files from dependencies in java modules. Now, we make sure we java symbols are added as non-trivial for java modules.
Fixes https://github.com/scalameta/metals/issues/1514
=> Support java files inside java modules for go to definition

metals/src/main/scala/scala/meta/internal/metals/debug/SetBreakpointsRequestHandler.scala, tests/unit/src/test/scala/tests/debug/StackFrameDapSuite.scala
It seems that the reason for some of the DAP issues with breakpoints is that the source is not set when sending back results of the breakpoint request to the client. I have no idea how it's possible, but to be on the save side I added an additional print statement and I copy the original source.
The failure in question with the logs is here:
[step-dap-suite.txt](https://github.com/scalameta/metals/files/4635973/step-dap-suite.txt)
=> Try to fix breakpoint DAP suites

metals/src/main/resources/db/migration/V1__Create_tables.sql, metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala, metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala, metals/src/main/scala/scala/meta/internal/metals/ChosenBuildTool.scala, metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/Tables.scala, tests/slow/src/test/scala/tests/MultipleBuildFilesLspSuite.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/test/scala/tests/ChosenBuildToolSuite.scala, tests/unit/src/test/scala/tests/DetectionSuite.scala
Previously this always defaulted to the first found, many times leading
to an SBT build if a workspace had both a `build.sbt` and a `build.sc`
file. Now both are grabbed and the user is prompted to choose whether
the space if for build tool A or build tool B. This choice is remembered
and they are not asked about this again.
I went back and forth on how the flow should go for this. I really wanted that when it was detected that multiple build definitions were found that it'd prompt like the following:
```
New workspace found. Would you like to import:?
1. Import sbt build
2. Import mill build
3. Not now
4. Don't show again
```
However, after doing that it was quite messy since you have to carry a list of `BuildTool` round to multiple methods, which all would have to handle if there was …
=> Handle workspaces with multiple build files.

metals/src/main/scala/scala/meta/internal/metals/FileWatcher.scala
Previously, watching a single source file would result with getting updates for the entire directory. Now, since adding Ammonite scripts it's more important to only follow updates on certain files. Especially when we create *.sc files at a root of a workspace.
=> Add file watcher for the standalone ammonite scripts

mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala, mtags/src/main/scala/scala/meta/internal/mtags/ClasspathLoader.scala
Previously, we would if a class was not found and in most cases this is not an issue, since it's only needed for checking Java 9 + modules. Now, we only return an Option.
Previously I thought this would be under the debug flag, but this might have changed recently and these logs will not be too useful or even confuse the user.
=> Remove logging from ClasspathLoader 

metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala
I'm a bit embarrassed to admit this, but somehow when I rebased #1758 after the amm branch got merged in, the persisting of the users choice of what build tool the want was removed.... This caused workspaces with both an builds.sbt and build.sc file to ask the user to choose every time they opened the workspace. This pr fixes that by _actually_ persisting the change.
=> Make sure to persist users choice of build tool

metals/src/main/scala/scala/meta/internal/metals/BuildTargetClassesFinder.scala, metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala, tests/unit/src/test/scala/tests/DebugProtocolSuite.scala
This PR addresses 2 small issues:
- Add automatically `-J` for Bloop so that users don't have to remember about it - fixes https://github.com/scalameta/metals/issues/1765
- Make sure that we use a more relevant build target if none was specified, which was an issue in scalameta. When running tests we would pick up js tests first, which are not supported on the same level as jvm ones.
=> Automatically add -J to jvm properties and make sure run JVM targets fists

docs/editors/vim.md
This pr is to address what https://github.com/scalameta/metals/pull/1774 was created for. It adds in a small reference to a setting in the docs to help Vim recognize `*.sc` as Scala files.
=> Add in setting to vim docs to help recognize *.sc as Scala files

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java, mtags/src/main/scala-2/scala/meta/internal/metals/MultilineStringFormattingProvider.scala, mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala, mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala, project/plugins.sbt, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala, tests/unit/src/test/scala/tests/UserConfigurationSuite.scala
By default, strip margin is added, but it's configurable with 
`   "metals.enable-strip-margin-on-type-formatting" : true `
=> Use onTypeFormatting to create multiline string

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala, tests/unit/src/test/scala/tests/ReferenceLspSuite.scala
Fix for one aspect of #1553:
References to case-classes via synthetics (`apply` , `unapply`) occurring in compilation units that neither define not explicitly import the class - these will now be found as expected. 
This fix results in more semanticdb lookups since we now include all those that might contain any of the alternative in addition to just the main type symbol.
The other aspect that isn't fixed just as yet: when starting the search *from* a synthetic the search results won't include the class definition itself as one of the expected references results (though other matching synthetics are returned). - for now the failing tests that demonstrate this issue are coaxed so they'll pass anyway - I'll work on this next.
=> fix missing synthetic references 

mtags/src/main/scala-2/scala/meta/internal/metals/MultilineStringFormattingProvider.scala, tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala
Bug-fix: onTypeFormatting is adding .stripMargin even if it's present
fixes #1804
=> Bug-fix: onTypeFormatting is adding .stripMargin even if it's present

mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala, tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala
Allow for exhaustive pattern matching in case of sealed upper bound types
Changes:
* added a test to check exhaustive match with upper type bounds
* update match case completion
* handle refinement type
fixes #1066
=> Allow for exhaustive pattern matching in case of sealed upper bound types

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala, mtags/src/main/scala-3/scala/scala/meta/internal/metals/ClassFinder.scala, mtags/src/main/scala-3/scala/scala/meta/internal/pc/ScalaPresentationCompiler.scala, tests/cross/src/main/scala/tests/BasePCSuite.scala, tests/cross/src/test/scala/tests/pc/ClassBreakpointSuite.scala, tests/slow/src/test/scala/tests/feature/CrossDebugSuite.scala, tests/unit/src/main/scala/tests/BaseDapSuite.scala, tests/unit/src/test/scala/tests/debug/BreakpointDapSuite.scala
Addresses one of the points in https://github.com/scalameta/metals/issues/1705
Previously, we did't stop at breakpoints inside toplevel methods when debugging. Now, we use a proper name for a class name generated from an outer method
=> Add support for breakpoints in toplevel methods in Dotty

docs/editors/emacs.md
I had an issue using the metals backend this morning, and I solved by requiring the metals backend for lsp-mode. I think it would be useful to have it in the docs.
=> Add lsp-metals as required dependency in Emacs docs

metals/src/main/scala/scala/meta/internal/metals/BuildTargetClassesFinder.scala
I missed that when testing it in https://github.com/scalameta/metals/pull/1781 - sortBy will give us the lowest numbers first. 
Did some manual tests, which should be enough here, since unit testing this might prove very difficult.
=> Pick the most valued build target instead of least for running or debugging

mtags/src/main/scala-2/scala/meta/internal/mtags/Semanticdbs.scala, tests/slow/src/test/scala/tests/feature/CrossReferenceSuite.scala, tests/unit/src/main/scala/tests/BaseRangesSuite.scala
Previously, we would not find semanticdb file if the relative path was done with `\\`. Now, we make sure that the slash is used all the time.
=> Fix issues with semanticdb on windows

build.sbt, tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
Previously, ammonite would remove all directories inside the target, which would cause the file watching to break. Now it only removes relevant files. This might also help with the ammonite suite flakiness.
=> Update ammonite to fix issues with file watching

metals/src/main/scala/scala/meta/internal/metals/BuildTargetClasses.scala, tests/slow/src/test/scala/tests/gradle/GradleLspSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/debug/BreakpointDapSuite.scala
Previously, Metals would filter out main classes from non-scala targets. Now, we also allow to run in the java only build target.
Fixes https://github.com/scalameta/metals/issues/1815
Together with scalameta/metals-vscode#300 it will allow users to just click run for Scala configuration even if Metals was not activated in the workspace.
=> Make sure we also are able to run/debug in java-only build targets

tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
It seems to mostly fail on Windows, if this happens more often on other system, I will just mark it as flaky altogether.
https://github.com/scalameta/metals/issues/1801
Edit: Looking more at recent failures, it seems to fail also on linux. We will need to investigate, but I don't really want to spend more time on it now.
=> Mark ammonite suites flaky

docs/editors/new-editor.md, metals/src/main/scala/scala/meta/internal/builds/BloopInstall.scala, metals/src/main/scala/scala/meta/internal/builds/BloopInstallResult.scala, metals/src/main/scala/scala/meta/internal/builds/BloopPluginBuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala, metals/src/main/scala/scala/meta/internal/builds/PantsBuildTool.scala, metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala, metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala, metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala, metals/src/main/scala/scala/meta/internal/metals/Icons.scala, metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala, metals/src/main/scala/scala/meta/internal/metals/Warnings.scala, metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala, mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala, tests/unit/src/main/scala/tests/BaseLspSuite.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/NewFilesLspSuite.scala, tests/unit/src/test/scala/tests/NewProjectLspSuite.scala, tests/unit/src/test/scala/tests/UnsupportedDebuggingLspSuite.scala
In this PR we introduce the way to quickly create a new project based on the existing g8 templates.
User can choose from curated Metals templates, write a custom template or use the existing list in the documentation  https://github.com/foundweekends/giter8/wiki/giter8-templates.md
We can also pick the name for the new project, directory where it should be located and at the end we can open a new window or stay in the current and open the new project there.
This command will also work with an empty workspace, clicking on the the "New Scala Project" will activate Metals and run the command.
PR to VS Code: https://github.com/scalameta/metals-vscode/pull/300 
This should also work without it.
=> Use g8 templates to provide "New Scala Project"

metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Icons.scala
Since VS Code is the only one using an actual icon for spacing it's
better to put the spacing there since we are doing a replace on the
icon and times producing labels that have one empty space and other
times two empty spaces causing odd spacing in other clients. This
change will allow for more consistent spacing in those clients while
keeping the same spacing in VS Code.
For example what this looks like in coc-metals without the change :(
And after the change :)
=> Add in spacing in vscode icons only.

metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsHttpClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
This has multiple changes to account for the case where a client may
have `isDecorationProvider` and also `isHttpEnabled` both set to true.
- Checks to make sure that `isHttpEnabled` wins before sending doctor
- Makes sure the publishDecorations is forwarded
=> Changes for decorationProvider if `isHttpEnabled` is true.

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
This pr changes the way Metals sets the `TextDocumentSync` in `ServerCapabilities`. We used to just send a 1 for this to signify a "full" synchronization. However, there are also other fields in the `TextDocumentSyncOptions` which state that if they aren't present, then they should be set to false. There seems to be some inconsistency with how clients handle this. One of those options is `save` and there really isn't anything explicitly saying that the `textDocument/didSave` events should be fired. So some clients (nvim for example), don't send them unless it is explicitly stated in the `TextDocumentSyncOptions`. This change creates a `TextDocumentSyncOptions` object  with the `change` still set to `TextDocumentSyncKind.Full`, but it also explicitly tells clients that we want `save` …
=> Add in explicit `TextDocumentSyncOptions`.

build.sbt, metals/src/main/scala/scala/meta/internal/metals/Messages.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
We run a separate ammonite bsp server per workspace. Previously, there was no way to limit the memory used by it. Now, users can specify configuration options that limit the memory or make other changes to the JVM used by ammonite. Alternatively, .jvmopts will also be picked up as is the case with Metals server itself.
VS Code PR: https://github.com/scalameta/metals-vscode/pull/337
=> Add jvm parameters configuration for Ammonite

build.sbt, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala, metals/src/main/scala/scala/meta/internal/worksheets/WorksheetClassLoader.scala, metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala, mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
Previously, worksheets didn't allow any additional dependencies, only the ones in the workspace. Now, it's possible to bring in additional deps like:
```scala
import $dep.`com.lihaoyi::scalatags:0.9.0`
import scalatags.Text.all._
val htmlFile = html(
body(
p("This is a big paragraph of text")
)
) // TypedTag("html",List(WrappedArray(TypedTag("body",List(WrappedArray(TypedTag("p", List(WrappedArray(StringFrag("This is…
htmlFile.render // "<html><body><p>This is a big paragraph of text</p></body></html>"
```
=> Update mdoc to 2.2.3 and power completions with worksheet's classpath

.gitignore, metals-docs/src/main/scala/docs/GenericModifier.scala
It is more optional than `.metals` or `.bloop` because not everyone uses ammonite scripts but I thought it might be good to ignore `.ammonite` by default.
=> Gitignore .ammonite directory + update docs

build.sbt
The idea behind this is to simplify the process for a contributor
to prepare their code for a pull-request. Currently a person has to
both execute the bin/scalafmt and also run scalafix via sbt. This
simplifies this to one step so a contributor can just run
`sbt preparePr` to run scalfix and then scalafmt.
The idea for this comes from #672 
> add a prePR command to run scalafmt+scalafix before a PR, currently you need to run the steps separately (scalafixAll in sbt shell and ./bin/scalafmt --diff from the terminal)
An alternative approach would be to just add the scalafmt-sbt plugin and use that, but I wasn't sure if there was opposition to that since we are using the `bin/scalafmt` route.
I also looked into added scalafix-cli in bin, but afaik including the `OrganzeImports` dependency …
=> Add in a preparePr alias.

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
Previously the edit for autoImports when triggered from a code action would contain
reference to the position the presentation compiler had for the generated Scala
file that the Ammonite script created. Like other functionality that we have that
interacts with the Presentation compiler while dealing with Ammonite we ensure that
the edits have positions that are adjusted to ensure they land in the correct place
in the script, not the generated Scala file.
Fixes #1870 
Behavior explained in the issue:
Behavior after the change:
=> Ensure the edit positions are correct for autoImports with Ammonite.

metals/src/main/scala/scala/meta/internal/metals/Compilations.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala, tests/unit/src/main/scala/tests/TestingClient.scala
In https://github.com/scalameta/metals/commit/a821715e949ca87e48cc5b41fe70815789eae405 
There was added a flag 'buildChanged' for a command `RefreshModel` sent from metals to clients.
It was done according to description to get rid of flakiness of ammonite tests but it will be also visible by all clients.
Even though adding a parameter is not a problem, problem is it is undocumented and not mentioned anywhere.
Because it is only used in ammonite test which is marked as 'flaky' I think it makes sense to revert this for now and look at it later after release.
Unless you feel it makes sense to keep it then let's add documentation for it and put that in Release Notes.
Fixes: #1863
=> Revert adding buildChanged flag to RefreshModel command

metals/src/main/scala/scala/meta/metals/Main.scala
I am using metals for emacs on a few systems. And more often than not, I am not sure which version is currently installed, or whether I should run `coursier bootstrap ...` to generate a new script.
This PR adds a `--version` command line option, which can also be called as `-v` or `-version` showing the current version of metals and additionally the supported Scala versions.
=> Add `--version` command line option

website/blog/2020-07-01-lithium.md
Mainly this just switches the `$dep` syntax to `$ivy` to not confuse people.
It also just corrects a few typos.
=> Show  imports in worksheet dependency example.

tests/unit/src/test/scala/tests/TreeViewLspSuite.scala
Fixes #1885 
Adapt `TreeViewLspSuite` to handle the presence of `jfr.jar` bundled along Oracle JDK 8 libraries
=> Fix unit test failure on Oracle JDK 8

.gitignore, docs/editors/new-editor.md, metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala, metals/src/main/scala/scala/meta/internal/metals/ClientExperimentalCapabilities.scala, metals/src/main/scala/scala/meta/internal/metals/ConfiguredLanguageClient.scala, metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala, metals/src/main/scala/scala/meta/internal/metals/JsonParser.scala, metals/src/main/scala/scala/meta/internal/metals/StatusBar.scala, metals/src/main/scala/scala/meta/internal/metals/StatusBarState.scala, mtags/src/main/scala/scala/meta/internal/pc/CompilerInitializationOptions.scala, mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala, tests/slow/src/test/scala/tests/feature/DefinitionCrossLspSuite.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/FormattingLspSuite.scala, tests/unit/src/test/scala/tests/NewFilesLspSuite.scala, tests/unit/src/test/scala/tests/NewProjectLspSuite.scala
While this is a bit more verbose than what we had, it allows this to be
much more explicit and represent what we actually want to do. When this
was first done (https://github.com/scalameta/metals/pull/1674) I had a
bunch of issues with `null` being set for values that didn't exist, not
easily being able to use `Option` in the structure, and also needing
default constructors in order for it to work correct. I didn't love it,
and have wanted to revisit this for a while. I also figured this was a
good idea to take care of as a precursor to
https://github.com/scalameta/metals/issues/1895
By doing it the way we previously did it caused us to have to check
configuration like this:
1. Is `InitializationOptions` set to a non-default value?
2. Is `ClientExperimentalCapabilities` set to a …
=> Remove gson runtime reflection with manual reads for configuration.

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala, tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala
Previously, we would treat named parameters for methods defined later in the code as local forward references. Now, we make sure that named parameters are not filtered out in that case.
Fixes https://github.com/scalameta/metals/issues/1845
=> Don't filter out named parameters for methods defined later in a class

.scalafmt.conf, build.sbt, metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala, mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala, tests/unit/src/test/scala/tests/FormattingLspSuite.scala
Since we're probably releasing today I figured it'd be a good idea to bump the version of scalafmt that the server recommends for people if they don't have it set in their conf file. I also bumped it for the codebase, which only caused one small change.
=> Bump scalafmt version up to 2.6.3.

build.sbt
This reverts commit 36513652eb73cfc64e10858cc61320a4c048f6a9.
Fixes https://github.com/scalameta/metals/issues/1925
The previous PR haven't run the checks - some issues with github actions.
=> Reverting "Update interface to 0.0.24 (#1918)"

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
Partly fixes #1814
I couldn't reproduce any other issues.
=> Make sure a file exists when searching for definition

bin/test.sh
This should help address the `Out of memory` issues we've been seeing.
=> Add Bloop jvmopts in tests to limit memory used by it

docs/editors/new-editor.md, docs/editors/overview.md, docs/editors/vim.md, docs/editors/vscode.md, metals-docs/src/main/resources/META-INF/services/mdoc.StringModifier, metals-docs/src/main/scala/docs/NewProjectModifier.scala, metals-docs/src/main/scala/docs/ParentLensesModifier.scala, metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
This PR adds the following:
- new Scala project documentation for vim and VS Code
- parent code lenses documentation for vim and VS Code
- fixes a number of smaller issues
- moves versions to a more prominent location
=> Add missing docs and move versions to a more prominent location.

build.sbt, metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala, mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
Import suggestions are not used currently and might cause additional overhead for the presentation compiler.
Suggested by @smarter
=> Add -Ximport-suggestion-timeout 0 to the presentation compiler options 

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
This will allow users to enter a parameter or two, step out, and then back
in and still get signature help. Currently, if you leave the parameters
and step back in, you will no longer get signature help. Also some clients
won't update and send another request to the server while you are in the
parameter group and hit ,. Now with this being explicit they will.
Just some examples. In VS Code before:
In VS Code after:
In coc-metals before:
In coc-metals after:
Closes https://github.com/scalameta/coc-metals/issues/264
=> Add in , as a trigger for SignatureHelp.

website/blog/2020-07-23-configuring-a-client.md
This pr is a blog post mean to give a bit of history and insight into how Metals has historically been configured and also to highlight that the now recommended way for clients to configure Metals is via `InitializationOptions`.
This is the final part of #1895
=> Add in blog post about configuring Metals.

tests/unit/src/test/scala/tests/BillLspSuite.scala
It seems it is currently consistently failing on Windows, though I cannot reproduce it on my machine.
=> Mark BillLspSuite.automatic-reconnect as flaky

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala, tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala
Previously, the enableStripMargin setting was not being updated. Now, it's evaluated lazily.
Fixes https://github.com/scalameta/metals/issues/1943
=> Fix enableStripMargin setting

metals/src/main/scala/scala/meta/internal/metals/CodeAction.scala, metals/src/main/scala/scala/meta/internal/metals/codeactions/CreateNewSymbol.scala, metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala, tests/unit/src/test/scala/tests/codeactions/BaseCodeActionLspSuite.scala, tests/unit/src/test/scala/tests/codeactions/CreateNewSymbolLspSuite.scala, tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala
Previously, when diagnostics were showing the same symbol code actions were duplicated. Now we make sure the for each unique symbol we have a single code action.
Fixes https://github.com/scalameta/metals/issues/1900
=> Fix duplicated code actions

build.sbt
I didn't realize this before I cleaned and then tried to compile again and then kept hitting on this:
```
[error] -- [E006] Not Found Error: /Users/ckipp/Documents/scala-workspace/scalameta-org/metals/mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala:100:47
[error] 100 |      if (SemVer.isCompatibleVersion("0.25.0", BuildInfo.scalaCompilerVersion))
[error]     |                                               ^^^^^^^^^
[error]     |                                               Not found: BuildInfo
[error] one error found
```
We didn't have the `BuildInfo` plugin enabled for `mtag3` which is causing this to fail for someone if they do a fresh check and try to build or if you clean everything locally and try to build again since we are accessing `BuildInfo` here …
=> Enable BuildInfo for mtags3

build.sbt, metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
I know we talked about this before. It's maybe not the cleanest, but it will allow for Scalasteward to just pick these up in the future.
=> Bump default mill version and also add it to BuildInfo

.scalafmt.conf, mtags/src/main/scala-0.24/scala/meta/internal/metals/ClassFinder.scala, mtags/src/main/scala-0.24/scala/meta/internal/pc/Symbols.scala, mtags/src/main/scala-0.25/scala/meta/internal/metals/ClassFinder.scala, mtags/src/main/scala-0.25/scala/meta/internal/pc/Symbols.scala, mtags/src/main/scala-0.26/scala/meta/internal/metals/ClassFinder.scala, mtags/src/main/scala-0.26/scala/meta/internal/pc/Symbols.scala, mtags/src/main/scala-3/scala/meta/internal/pc/Scala3CompilerAccess.scala, mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala, mtags/src/main/scala-3/scala/meta/internal/pc/SymbolPrinter.scala
While starting to poke around the Scala3 code I notice we have started to use the Dotty syntax for implicits, but only in some places. I'm sort of in favor of unifying the way we approach it. In Scala3 stuff I think it makes sense to be consistent and just fully switch over to the given/using syntax. What do you think?
=> Change implicits to Dotty syntax.

mtags/src/main/scala-2/scala/meta/internal/pc/completions/InterpolatorCompletions.scala, tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
Fixes #1703.
It seems, that this problem happened because of the `filterText` value in completion item that started with `$` or `${`.
For example:
```scala
// input
val fooBar = "test"
"${fooBa@@"
// returned completion item
CompletionList [
isIncomplete = false
items = SeqWrapper (
CompletionItem [
label = "fooBar"
kind = Value
tags = null
detail = ": String"
documentation = null
deprecated = null
preselect = true
sortText = "00000"
filterText = ""${fooBar " // should be "fooBar"
... 
```
=> Fix `filterText` value for completion item in string interpolation

build.sbt, metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala, metals/src/main/scala/scala/meta/internal/metals/AdjustLspData.scala, metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala, metals/src/main/scala/scala/meta/internal/metals/BspConnector.scala, metals/src/main/scala/scala/meta/internal/metals/BspServers.scala, metals/src/main/scala/scala/meta/internal/metals/BspSession.scala, metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala, metals/src/main/scala/scala/meta/internal/metals/BuildTargetClasses.scala, metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, metals/src/main/scala/scala/meta/internal/metals/Compilations.scala, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/FileSystemSemanticdbs.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala, metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala, metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala, mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala, mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala, tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala, tests/unit/src/main/scala/tests/BaseLspSuite.scala, tests/unit/src/main/scala/tests/QuickBuild.scala, tests/unit/src/main/scala/tests/ScriptsAssertions.scala, tests/unit/src/main/scala/tests/TestingDiagnostics.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/main/scala/tests/TestingWorkspaceSymbolProvider.scala, tests/unit/src/test/scala/tests/BuildServerConnectionLspSuite.scala
This PR fixes https://github.com/scalameta/metals/issues/1838 by establishing additional BSP connection for each Sbt meta project.
It adds the following for Sbt:
- completions
- go to definition
- hover
Doesn't yet add:
- diagnostics
- references
- rename
=> Sbt support - multiply bsp connections

docs/editors/new-editor.md, metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala, metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
While working on https://github.com/scalameta/metals-languageclient/pull/163 I noticed a few things in the docs that were missing. This addresses those missing pieces.
=> Add in a few missing docs on the extensions and commands.

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala, metals/src/main/scala/scala/meta/internal/metals/AdjustLspData.scala, metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala, metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala, mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala, tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
Fixes https://github.com/scalameta/metals/issues/1981
=> Fix go to defintion for Sbt's Scala sources

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala
Previously, Sbt support would only work for `*.sbt` files, now it also works for `project/*.scala` ones.
=> Add support for Sbt's Scala files

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala, metals/src/main/scala/scala/meta/internal/metals/Compilations.scala, metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala, metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClasses.scala, metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClassesFinder.scala, metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
Previously, we would only allow running main classes defined inside workspace source, which information was supplied by Bloop. Now, we also try to find the class inside dependencies to allow running things like Play framework server:
Fixes https://github.com/scalameta/metals/issues/1667
=> Allow running main classes from dependencies

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
Previously, compilation would be run twice for each file saved in the editor. Now, it's only run once. 
If the file is open in the editor it should be the one responsible for the content, not the file watcher. 
Fixes https://github.com/scalameta/metals/issues/1836
=> Make sure we don't compile twice for open files

metals/src/main/scala/scala/meta/internal/metals/debug/SetBreakpointsRequestHandler.scala, tests/unit/src/main/scala/tests/BaseDapSuite.scala, tests/unit/src/test/scala/tests/debug/BreakpointDapSuite.scala
Previously, if all breakpoints were removed for a class this event would not be registered by the debug server. Now, we make sure to send an additional empty request for each removed class/object.
How does it work:
- Breakpoint request is sent per file for example `Main.scala`.
- We partition the request based on where a breakpoint is located, for example `dap-fqcn:Main` for class Main and `dap-fqcn:Main$` for object Main.
- Breakpoints are sent to Bloop and set internally by microsoft debug server per path.
- When updated breakpoints are sent, we do not know which ones were removed and we cannot just use the file path, since that is not used by the server itself. This is why I added an internal list of uris that were specified previously and send an additional empty request for any that …
=> Allow to remove all breakpoints when debugging

metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala, metals/src/main/scala/scala/meta/internal/metals/ClientExperimentalCapabilities.scala, metals/src/main/scala/scala/meta/internal/metals/CodeLensProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Directories.scala, metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala, metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala, metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala, metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala, metals/src/main/scala/scala/meta/internal/metals/codelenses/SuperMethodCodeLens.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/AnalyzeStacktraceLspSuite.scala, tests/unit/src/test/scala/tests/StacktraceParseSuite.scala
Stacktrace analyzer PoC
It creates `.metals/stacktrace.scala` file with stacktrace (provided in command, in vscode PR taken from clipboard like in Intellij)
Because stacktrace lines are in format: `scope.class.method(filename:line)` I try to convert `scope.class.method` into symbol and look for definition of it. If found I use path where definition is located and set line from stacktrace.
For very simple stacktraces it works okay, there might be issues with annonymous classes etc. (to be tested further).
If you are on a given line you can do action 'go to definition' that will move cursor to place where stacktrace line points to.
For every located symbol also there are added code lenses. 
For `goto-location` I added optional parameter `otherWindow` which says to client that it would be …
=> Analyze stacktrace

metals/src/main/scala/scala/meta/internal/metals/MutableMd5Fingerprints.scala
Not sure why this part of code was commented out, but it resulted in fingerprints never getting cleared, which means we had copies of all revisions in memory.
=> Clear fingerprints when semanticdb hash matches

build.sbt, tests/unit/src/main/scala/tests/TestingServer.scala
It seems 1GB for a fork was not enough on MacOS. And since we do not have multiple forks running it should be fine.
Current xmx for each process:
- bloop 2GB
- sbt 1GB
- test fork 2GB
With max 7GB it leaves 2GB spare for class space, which should be enough.
=> Bump memory for test forks to 2GB

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala, tests/unit/src/test/scala/tests/worksheets/WorksheetLspSuite.scala
The sources and classpath was not forwarded to the symbol search for worksheets outside build targets.
Fixes https://github.com/scalameta/metals/issues/2029
=> Fix auto imports and go to sources for worksheets outside sources

metals-docs/src/main/scala/docs/UserConfigurationModifier.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, website/package.json
This pr corrects the way that values are displayed in the docs when we are showing UserConfiguration examples. Instead of always wrapping the examples in `""` in the modifier, instead we do that in the actual example. This will make sure that boolean values and arrays display better.
Before:
After:
Before:
After:
I also made sure this displays correctly in the "adding a new client" section:
Thanks for pointing this out @kpbochenek. 
Closes #2044
=> Correct the way userConfig examples are displayed.

metals/src/main/scala/scala/meta/internal/tvp/ClasspathSymbols.scala, tests/unit/src/test/scala/tests/TreeViewLspSuite.scala
Previously if we were looking for members underneath `_empty_` we ended up
looking for them in `<uri>/_empty_` rather than just looking for them in the
root where they are stored. This adds in another check where when we look to
see if a symbol is in the root package, we also check to see if it's an empty
package, and if so, then just return the root value to look for it.
Closes #1648
=> Fix missing classes from _empty_ package in treeView.

build.sbt
This version contains a fix for #1852 so incorrect $file imports
now give diagnostics.
Closes #1852
=> Add in new version of Ammonite

metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala, tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
Up to this point we search for all types of code lenses even in Ammonite scripts
where there won't be any run or test code lenses that appear. This will save us a
bit as we won't look through all the symbols in the textDocument for the main method.
It's probably not a huge deal, but no need to do it.
=> Don't search for runTest code lenses in Ammonite scripts and worksheets.

.scalafmt.conf, build.sbt, mtags/src/main/scala-0.27/scala/meta/internal/pc/Symbols.scala, mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala, tests/cross/src/test/scala/tests/pc/CancelCompletionSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSnippetNegSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSuite.scala, tests/mtest/src/main/scala/tests/BaseSuite.scala, tests/slow/src/test/scala/tests/feature/WorksheetCrossLspSuite.scala, tests/unit/src/main/scala/tests/BaseRangesSuite.scala, tests/unit/src/main/scala/tests/BaseRenameLspSuite.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala, tests/unit/src/main/scala/tests/QuickBuild.scala, tests/unit/src/test/scala/tests/ImplementationLspSuite.scala, tests/unit/src/test/scala/tests/RenameLspSuite.scala
The updated mdoc now uses `toString` and inbuilt mechanism for reporting types, which solves the issue with pprint dependency.
Fixes https://github.com/scalameta/metals/issues/2024
=> Add support for dotty 0.27.0-RC1 and update mdoc

metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
I haven't noticed that the test position were actually bad. They should point to 0 line after adjustments.
=> Fix wrong definition position for worksheets

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/NewFilesProvider.scala, metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala, tests/unit/src/test/scala/tests/NewFilesLspSuite.scala
This changed the current functionality of the new-scala-file command to allow
for another argument in the third position, which signifies the file type. Previously,
we allowed for the name of the file to be in the args in the second position, but now
we also allow the file type to allow for a client to create a file with a single command.
This mainly will allow for the quick-creation of worksheets which can be bound to an
editor action or command.
This also changes up the NewFilesLspSuite to cover the other arguments. Previously the
functionality of the name being passed in wasn't covered. Now, that functionality and
also providing the fileType is also covered in the tests.
Ideally the args for this command would have been an JSON object allowing for the necessary
keys to be set or not, …
=> Change new-scala-file to enable quick creation of a file.

metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala, tests/unit/src/test/scala/tests/AnalyzeStacktraceLspSuite.scala
So in some clients (VS Code), the stacktrace will be printed without any
prefaces, which allows for the stacktrace to be correctly parsed and the lenses
created for them when utilyzing the stacktrace-anlyzer functionality. However,
for some clients that don't have a nice built-in way to run the application
in the client, they may be resorting to run via their build tool or with the
bloop-cli. This change ensures that a person can copy the stacktrace from
sbt or from bloop cli and still utilize the functionality.
Note that nothing special for Mill was needed since Mill also doesn't preface
the stacktrace output with any `[E]` or anything.
=> Strip out `[E]` or `[error]` from stacktrace in analyzer.

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala, metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileProvider.scala, metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileTemplate.scala, metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileTypes.scala, project/TestGroups.scala, tests/unit/src/test/scala/tests/NewFileLspSuite.scala, tests/unit/src/test/scala/tests/NewFileTemplateSuite.scala
Today I sat down to write an Ammonite script and when I used the
new-scala-file command I saw the following message:
```
Enter the name for the new ammonite
```
This bugged me a bit since I wanted it to say "for the new Ammonite
Script". The same thing happens when you try to create a case-class. The
message that you see is:
```
Enter the name for the new case-class
```
I think it's nicer to show "Case Class" here. This along with a couple
other small things I noticed when I did
https://github.com/scalameta/metals/pull/2075 like just matching against
strings to get the fileType and not really having any sort of ADT for
the new filetypes. So I made some opinionated choices and refactored
some stuff related to the new-scala-file command into its own package.
This _I hope_ makes it a bit …
=> Refactor NewFileProvider

.github/workflows/ci.yml, .github/workflows/release.yml
Thanks for point this out in https://github.com/scalameta/metals/pull/2084 @kpbochenek. This utilizes the built-in way to make sure you get all the history for branches and tags without having to issue any of your own git commands. https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
This also bumps the coursier cache action version.
=> Use built-in fetch depth and bump coursier cache

metals/src/main/scala/scala/meta/internal/metals/ExcludedPackagesHandler.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, tests/cross/src/main/scala/tests/BasePCSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSuite.scala, tests/slow/src/test/scala/tests/feature/ClasspathSymbolRegressionSuite.scala, tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala, tests/unit/src/test/scala/tests/CompletionLspSuite.scala, tests/unit/src/test/scala/tests/codeactions/CreateNewSymbolLspSuite.scala
Closes #2090
As discussed in the issue, the exclusion of javax isn't probably a great default anymore.
We even use some javax imports ourselves in Metals!
This PR removes `javax` from the default set of excluded packages. Users can opt-in to the exclusion using the recently released setting.
=> Remove javax from default excluded packages

build.sbt, docs/editors/overview.md, metals/src/main/scala/scala/meta/internal/metals/Buffers.scala, metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Embedded.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, metals/src/main/scala/scala/meta/internal/metals/codeactions/OrganizeImports.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/UserConfigurationSuite.scala, tests/unit/src/test/scala/tests/codeactions/BaseCodeActionLspSuite.scala, tests/unit/src/test/scala/tests/codeactions/CreateNewSymbolLspSuite.scala, tests/unit/src/test/scala/tests/codeactions/OrganizeImportsLspSuite.scala
This PR request the new interfaces of Scalafix. The review is still on-going on scalafix side. 
It's a draft, some values are hard-coded. Only working for scala 2.12 projects.
The default [organize config](https://github.com/liancheng/scalafix-organize-imports) is used for now, which is:
```
OrganizeImports {
coalesceToWildcardImportThreshold = 2147483647 # Int.MaxValue
expandRelative = false
groupExplicitlyImportedImplicitsSeparately = false
groupedImports = Explode
groups = ["re:javax?\\.", "scala.", "*"]
importSelectorsOrder = Ascii
importsOrder = Ascii
removeUnused = true
}
```
We can think about taking the config found in .scalafix.conf if it exists, if not we will need to choose some default config for organize import code action. 
This is how it works (a shortcut is already bound …
=> Implement organize import using scalafix

metals/src/main/scala/scala/meta/internal/metals/BspConnector.scala, metals/src/main/scala/scala/meta/internal/metals/BspServers.scala, metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
No logic was changed in this PR (hopefully :D )
Added displaying BuildServer that is currently used and one that will be used after restart of metals.
To make it reliable I extracted resolving it to single method.
=> Display used BuildServer in Doctor

tests/mtest/src/main/scala/tests/TestHovers.scala
While tinkering, I've noticed a deprecation warning due to a usage of `MarkedString`.
In `TestHovers` we still handled the case in which we returned a `MarkedString` or a `String` in `Hover` (now deprecated in lsp4j), but in the implementation we actually just use `MarkupContent` so that code branch is effectively unused.
I think it's safe to remove it, let's see whether the CI thinks otherwise
=> Simplify TestHovers and remove warning

build.sbt
Partially addresses #2099 by adding 2.11 support for organize imports (the error reporting part is still missing)
=> Update organize-import rule to add Scala 2.11 support

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala, mtags/src/main/scala-2/scala/meta/internal/pc/Keywords.scala, mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala, tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
This adds some some somewhat sensible top-level completions when you attempt to
trigger a completion in an empty file. For example `p@@` will produce:
- package
- private
- protected
- import
All which would be valid compared to the behavior previously where nothing was
recommended.
Closes #1663
=> Add in top level-completions for empty file.

metals/src/main/scala/scala/meta/internal/metals/PopupChoiceReset.scala
I randomly noticed this tonight when using the interactive reset choice functionality. According to [the spec](https://microsoft.github.io/language-server-protocol/specification.html#window_showMessageRequest), the showMessage request can return a `MessageActionItem` or `null`. We weren't accounting for the `null` and I was seeing null pointer exceptions being thrown when I cancelled the request. This just adds in a check.
=> Account for possible null value on PopupChoiceReset message request

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala, metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala, metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala, metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/MutableMd5Fingerprints.scala, metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, mtags/src/main/scala-2/scala/meta/internal/metals/TokenEditDistance.scala, mtags/src/main/scala-2/scala/meta/internal/mtags/Md5Fingerprints.scala, tests/unit/src/main/scala/tests/TestingClient.scala, tests/unit/src/main/scala/tests/TestingServer.scala, tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala, tests/unit/src/test/scala/tests/decorations/SyntheticHoverLspSuite.scala
Resolves https://github.com/scalameta/metals/issues/2009
Some issues that I found when working on this:
- hovers on decorations inside text will pop up only before that decoration - https://github.com/microsoft/vscode/issues/105302
- not sure how to do go to definition for the implicits - I was thinking of maybe adding code lenses above or adding an option in definitionProvider to also search for synthetics if the cursor matches the end of sythetic occurence. I decided that we can work on it later
This also requires a PR for VS Code: https://github.com/scalameta/metals-vscode/pull/413
=> Show implicit arguments and type annotations for Scala files 

metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala, metals/src/main/scala/scala/meta/internal/metals/Compilations.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala, metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala, metals/src/main/scala/scala/meta/internal/metals/codeactions/OrganizeImports.scala, metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
This fixes both:
- reporting errors - fixes https://github.com/scalameta/metals/issues/2102
Unfortunately we currently do not have any more information about the actual error message, it will need to be worked on further in scalafix. This hopefully enough for now, most error will be connected to semanticdb not being produced.
- making sure that compilation is run when using scalafix - fixes https://github.com/scalameta/metals/issues/2100
We are not yet able to organize imports in an unsaved file, but I will follow up with an issue for that.
=> Make sure files are compiled when running scalafix 

docs/editors/debug-adapter-protocol.md, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala, metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala, metals/src/main/scala/scala/meta/internal/metals/debug/DotEnvFileParser.scala, tests/unit/src/test/scala/tests/DebugProtocolSuite.scala, tests/unit/src/test/scala/tests/debug/DotEnvFileParserSuite.scala
This PR adds support for loading environment variables from .env files.
This is still a WIP, but I wanted to make sure this approach is ok before I spend more time on implementing more tests and cleaning up the code.
I added a new `envFile` parameter to `DebugUnresolvedMainClassParams` which allows you to specify either a relative (to your project workspace) or an absolute path to an `.env` file in the `launch.json` config, e.g.:
```diff
"version": "0.2.0",
"configurations": [
{
"type": "scala",
"name": "Debug ",
"request": "launch",
"mainClass": "Main",
+     "envFile": ".env"
}
]
}
```
If the path is present, the file is parsed and the env variables are prepended to the env variables defined in the `env` object introduced in #2118 with the intention of making `env` override any …
=> Add support for loading env variables from a .env file.

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
Fixes https://github.com/scalameta/metals/issues/2128
=> Use 127.0.0.1 address always for DebugProvider

.github/workflows/ci.yml, .github/workflows/release.yml
We are getting a bunch of warnings in CI
```
The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
I was hoping this might get rid of some of them, but I'm assuming the changes may need to actually happen in the actions themselves. I'll take a peak, but either way, good to upgrade.
=> Bump setup-scala and cache-action actions

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala, metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala, tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
EDIT: This pr has changed a bit since I first started due to me totally overthinking what the actual issue was. So the aim for this now is to address two separate things.
1. Add java sources to the StandaloneSymbolSearch when we have a standalone worksheet so goto definition works on Java sources as you'd expect.
2. Close #1433 by checking to see if a worksheet belongs to a build target. If so, check to see if that build target has been compiled at all, and if not, compile it first.
~Now that you're able to put imports directly in your worksheet, I've
started to more often put worksheets either at the root of project, or
even in a directory of their own. I've started to keep worksheets and
just stick them in a `/worksheets` directory so I can refer to them
later on or share them. However, …
=> Add java sources to standalone worksheets and run compilation before evaluation if necessary.

mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java, mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala, mtags/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala, tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala, tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala, tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala
Fixes https://github.com/scalameta/metals/issues/1502
We only add the default prefixes if there is a conflicting symbol in scope. However, if the user intentionally modified the prefixes we always use the modified ones.
=> Don't import {java.util => ju} when no conflicting symbols are available

metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala
It seems some users were experiencing a lot of such messages as this situation might happen normally. File created or modified events will be sent also in cases that a file wasn't finished writing. In that case we should not show the error.
=> Mute InvalidProtocolException which might happen normally

metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
I discovered this while playing around with the Mill BSP support since some of the build targets don't always have the `baseDirectory` set as it can be absent [according to the spec](https://build-server-protocol.github.io/docs/specification.html#build-target). This was throwing a null pointer exception when we then tried to order by the base dir in the Doctor. In the case of `null` I just set it to an empty `""` which only affects the ordering of the target in the Doctor or tree view.
=> Account for possible null value in ScalaTarget's baseDirectory

metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala, metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala, tests/unit/src/test/scala/tests/FormattingLspSuite.scala, tests/unit/src/test/scala/tests/codeactions/BaseCodeActionLspSuite.scala, tests/unit/src/test/scala/tests/codeactions/OrganizeImportsLspSuite.scala
This changes `metals.scalafixConfigPath` and `metals.scalafmtConfigPath` to use absolute path instead of a relative one. I found the previous behaviour to be problematic because:
- to set global config user would need to set each workspace to a different relative path and it's much more often that people have one global config than that they have a different naming scheme in each workspace they work in
- for scalafmt we would search the defined relative path in each workspace folder, while we currently do not support multiple workspace folders, so it might be quite random which config we choose.
It's important to note it's still possible to specify the path as for example `project/.scalafix.conf`, which will work the same way as previously. @olafurpg not sure why it was a relative path in …
=> Change scalafix and scalafmt conf to absolute path 

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
Ach.... this was wrong, I had the one from bloop in instead of this one for our snapshots.
=> Fix resolver for sbt-metals snapshot

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
Depending on the size of the project, when the decision to use sbt server is made, it may take a bit of time to start sbt before the bsp connection can be made. This shows the process in the status bar so the user has an idea of what's going one instead of not having a clue what's happening for that time.
=> Track and show progress to user about connecting to sbt

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala, metals/src/main/scala/scala/meta/internal/metals/Doctor.scala, metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/PopupChoiceReset.scala
This pr adds in an `(Reset)` option in the html view of the doctor to reset your build server choice. The button is only shown if you've _explicitly_ chosen a build server. So for a user that just connects and uses the default, they will see that they are using Bloop as their build server, but won't be able to reset it, because there is no choice made.
So after making a choice if they do a `bsp-switch`, they the flow would look like this if they wanted to use Doctor to switch back and forth.
Closes #2171
=> Allow for reset in html doctor

mtags/src/main/scala/scala/meta/internal/metals/PackageIndex.scala
So this error was actually introduced by me in the previous PR, since I readded `Testing.isEnabled` flag, which hasn't been used for a while.
=> Remove condition for jfr, since it's now reliably available on CI

metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala, metals/src/main/scala/scala/meta/internal/metals/Timed.scala, metals/src/main/scala/scala/meta/internal/metals/TimerProvider.scala
This doesn't add in any new functionality, but we have  a few timer
related methods floating around in `MetalsLanguageServer`, and I've
started to really notice how much stuff we have stuck in there. I'd like
to slowly start moving some stuff out, and these were easy to move out.
Plus some of other methods that use these I plan on moving out as well,
so it will be helpful to have these in their own class to make that
easier instead of passing them from `MetalsLanguageServer` into
other classes.
I ended up deleting the `Timed` class as well since it wasn't being used
at all.
Also this relates to some overdue work in listed in here https://github.com/scalameta/metals/issues/672
=> Add in timer methods to a new timerProvider.

sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala
So in the same project, this is the diff I got from before these changes and after, which match the desired outcome of #2189 
```diff
sbt:dotty-test> show Test / scalacOptions
[info] * -bootclasspath
[info] * /Users/ckipp/.sdkman/candidates/java/8.0.242-librca/jre/lib/resources.jar:/Users/ckipp/.sdkman/candidates/java/8.0.242-librca/jre/lib/rt.jar:/Users/ckipp/.sdkman/candidates/java/8.0.242-librca/jre/lib/sunrsasign.jar:/Users/ckipp/.sdkman/candidates/java/8.0.242-librca/jre/lib/jsse.jar:/Users/ckipp/.sdkman/candidates/java/8.0.242-librca/jre/lib/jce.jar:/Users/ckipp/.sdkman/candidates/java/8.0.242-librca/jre/lib/charsets.jar:/Users/ckipp/.sdkman/candidates/java/8.0.242-librca/jre/lib/jfr.jar:/Users/ckipp/.sdkman/candidates/java/8.0.242-librca/jre/classes
[info] * -Ysemanticdb
[info] * …
```
=> Ensure scalacOptions for Test are correct for sbt BSP.
