build.sbt
docs/build-tools/maven.md
metals-docs/src/main/scala/docs/Docs.scala
metals/src/main/scala/scala/meta/internal/builds/MavenBuildTool.scala
project/V.scala

This replaces the usage of the old `maven-bloop_2.13` plugin with the
`bloop-maven-plugin`. All of the behavior should remain the same.

refactor: use the newly published bloop-maven-plugin

---

metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
tests/slow/src/test/scala/tests/feature/CrossCodeLensLspSuite.scala
tests/unit/src/test/scala/tests/CodeLensLspSuite.scala

Hi!  This PR makes it so that `@main` lenses with scala cli scripts (e.g. files ending in `sc`) are shown.  They appeared previously only for scala cli files with the `.scala` extension, so the second added test would pass already, but the first wouldn't (though I'm unsure whether to put the new tests in `CodeLensLspSuite` or `CrossCodeLensLspSuite`).
I think this happened because the main (toplevel) function symbols for `sc` files typically have the form `_empty_/main.main().`, whereas `.scala` files would have the corresponding form `_empty_/main$package.main().`, and only the second form was accepted by `DebugProvider.dropSourceFromToplevelSymbol`.
Thanks

Show @main lenses with scala cli scripts

---

metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala

This was a mistake that I made earlier that I didn't think about.
This can be either a String or an Int and ours are always Strings
so I need to check left for '-1'. The check I had before didn't
make any sense as I was comparing against an either

fix: check for the left in diagnosticCode

---

.github/workflows/check_scala3_nightly.yml

It seems that `gh` command now requires `GH_TOKEN` This should fix this workflow failure - https://github.com/scalameta/metals/actions/runs/3737671059

ci: fix check_scala3_nightly

---

docs/contributors/getting-started.md

Previously, we would always explain the commit style for each contributor separately. Now, we state the best practices in the contributors guide.
This is really a suggestion, but I believe we will benefit from a clear style of commits

chore: Explain how to write messages for commits

---

.github/workflows/check_scala3_nightly.yml

More info for example here: https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp

bugfix: use GITHUB_TOKEN instead, which is the default env variable

---

.github/workflows/mtags-auto-release.yml
.github/workflows/release.yml

It seems we had two palces where we used the custom token and it's not recommended to set one yourself.

bugfix: Update all GH_TOKEN refs to GITHUB_TOKEN

---

metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
tests/unit/src/test/scala/tests/MetalsEnrichmentsSuite.scala

Previously, we were encoding characters such as whitespaces or + when encountered in string, however it seems those escaped characters with % are treated literally by windows. Now, we specially decode % escaped characters to make sure windows can correctly read them.
Fixes https://github.com/scalameta/metals/issues/4747
Tested manually, not sure how to do a proper test for it since the windows images we test on seem fine.

bugfix: Don't encode paths on Windows

---

.github/workflows/mtags-auto-release.yml

The default github tokens will not be able to invoke another workflow, which is an intended limitation. Instead I specified a fine grained token to use for that purpose.

chore: Use repository scoped token for pushing tags

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractValueCodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/MetalsNames.scala
tests/unit/src/test/scala/tests/codeactions/ExtractValueLspSuite.scala

In this PR connected two issues of extracting value code action are solved.
1. Previously, the `newValue` definition was inserted in the line above the one a user was making changes on. This was error prone. E.g. extracting `2 + a` from
```
def m(i : Int) : Int = ???
val a = 1; val m1 = m(2 + a)
```
results in:
```
def m(i : Int) : Int = ???
val newValue = 2 + a
val a = 1; val m1 = m(newValue)
```
2. Values in bodies of lambda functions were not handled properly. For a value in the body of  `Term.Function` the scope was found incorrectly and no necessary brackets were inserted. E.g. extracting `x+1` from
```
def m(i: Int): Int = ???
val newValue: List[Int] = ???
val m1 = newValue.map(x => m(x + 1))
```
results in:
```
def m(i: Int): Int = ???
val newValue: List[Int] = ???
val newValue1 = …
```

Fixes for the extract value feature

---

project/V.scala

Backpublish for 0.11.9 is already running.

chore: Add support for Scala 3.2.2-RC2

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala

This should print the actual messages aside from `Message could not be parsed`

improvement: Add log when message could not be parsed

---

mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
tests/unit/src/test/scala/tests/MtagsEnrichmentsSuite.scala

We should have a sensible default way of getting the name instead of relying always on Java API.
Connected to https://github.com/scalameta/metals/issues/4600
Possibly we will need something more to solve it.

bugfix: Make finding filename more reliant

---

website/blog/2023-01-02-aluminium.md

Let me know if anyone wants to fill in a section. In the meantime I am looking at some issue with Bloop that seem to be happening for me on JDK 8 and scalameta issue with diagnostics

chore: Add release notes for Metals 0.11.10

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionPatternSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Makes match-case completions in Scala 2 work like in Scala 3.
Improvements include:
- pattern only completions, i.e. completions in:
```scala
Option(1) match {
case No@@
case _: So@@
```
- completions like:
```scala
case class Foo(a: Int, b: Int)
List(Foo(1,2)).map{ case F@@ }
List(Foo(1,2)).map{ case Foo(a,b) => } // useful for single case classes
``` 
- exhaustive match completions in anonymous functions:
```scala
List(Option(1)).map { case@@ }
List(Option(1)).map {
case Some(value) => 
case None =>
}
```

feat: Improve match-case completions in Scala 2

---

website/blog/2023-01-02-aluminium.md

A whitespace character between the square brackets and the parenthesis caused the link to not be rendered correctly.

fix(website): Make sure Markdown link is rendered correctly in Metals v0.11.10 announcement

---

project/V.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

This should reduce the cross test times a bit and it's fine to deprecate and remove some older versions.

chore: Deprecate and remove more Scala versions

---

mtags/src/main/scala/scala/meta/internal/mtags/CoursierComplete.scala
tests/cross/src/test/scala/tests/pc/CompletionScalaCliSuite.scala

Not all dependencies have version names in the same format, so previous way of sorting was causing exceptions. Now we use basic sorting on String as a fallback
fixes https://github.com/scalameta/metals/issues/4799

fix: correctly sort dependency completions

---

docs/features/scripts.md
website/docusaurus.config.js
website/package.json

We were on a beta version before so I thought it would be a good idea
to bump up to an actual stable version. Not much changes at all in appearance.
The only notable difference is that you can no lnoger customize the light/dark
toggle without doing a 'swizzle', which is way more work and not worth it
in my opinion. I also needed to add the `appId` for algolia and it looks
like the `customCss` is calculated from a different root since it was erroring
out and not finding it without changing what we had.

chore(site): bump docusaurus to 2.2.0

---

mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala
tests/unit/src/test/scala/tests/BuildIssueLspSuite.scala

Previously, I tried fixing an issue when your jars were located under a path with spaces. I realized that we should not encode spaces etc. in these situation. Turns out that for normal paths we have to encode them.
Now, we go back to encoding normal paths.
Should fix https://github.com/scalameta/metals/issues/4801

bugfix: Fix issues with spaces in workspace path

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcRenameProvider.scala
tests/cross/src/test/scala/tests/pc/PcRenameSuite.scala

Previously, rename would not work using the presentation compiler inside lambdas, which should not require semanticdb for rename. Now, we also check if one of the owners of the renamed symbol is an anonymous function, since that symbol will be local.
For Scala 3 this seems to work correctly already since `ow.is(Method)` is true for lambdas.

improvement: Allow compiler rename in lambdas

---

build.sbt

This is just a follow-up to
https://github.com/scalameta/metals/pull/4812 to ensure that it will
always be updated by Steward.

chore: ensure semanticdb-java gets updated by Scala

---

metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/JavaTarget.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
metals/src/main/scala/scala/meta/internal/metals/TargetData.scala

This is a follow-up to the work that I've done in
https://github.com/scalameta/metals/pull/4295. At that time I only
applied the changes to Scala Targets since Semanticdb was only produced
there when using Mill as your build server. Now that https://github.com/com-lihaoyi/mill/pull/2227
is merged Java Targets and mixed targets will now also produce
semanticdb. We now add the extra check for Mill and its version when we
check for semanticdb java support. This will ensure that users won't get
the error in the Doctor about lacking support.
CC @lefou

refactor: improve reporting on Semanticdb from Mill for Java Modules

---

metals/src/main/scala/scala/meta/internal/metals/debug/ExtendedScalaMainClass.scala
tests/unit/src/test/scala/tests/CodeLensLspSuite.scala

Previously, we would not escape Java path, classpath or java properties, which meant that whenever spaces were involved things would not work on Windows (possibly on some other systems too). Now, we properly escape all those things.
I tested both by hand and added a test case, which proved to be a pain to write :/
Fixes https://github.com/scalameta/metals/issues/4801

bugfix: Fix running when spaces are involved on windows

---

metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClasses.scala

Previously, we would always request jvmEnvironment for all build targets even if some of them were not available. Now, we properly only query the right targets.
Fixes https://github.com/scalameta/metals/issues/4824

bugfix: Only request build targets from a connection

---

architecture.md

closes https://github.com/scalameta/metals/issues/4802
It seems that there are some additional changes after I formatted document in vscode.

docs: update `architecture.md` after #4776 (split MetalsLanguageServer` into separate two parts)

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala

Previously highlight and other pc collector features in
```scala
object A {
val a = {
val a = 1
@@a + 1
}
val b = a + 1
}
```
On inner `a` would highlight all occurences of both variables `a`

fix: fix name shadowing in pc collector

---

metals-bench/src/main/scala/bench/CompletionBench.scala
metals-bench/src/main/scala/bench/PcBenchmark.scala
metals-bench/src/main/scala/bench/SemanticHighlightBench.scala
tests/unit/src/main/scala/bench/Corpus.scala

They can be run using:
```
sbt bench/jmh:run -i 10 -wi 10 -f1 -t1 .*SemanticHighlightBench
```
I also reworked the CompletionBenchmark a bit since it needs a lot of the same elements.

improvement: Add benchmarks for SemanticHighlight

---

build.sbt

Previously, this was ignored, but with a recent merge this started to actually be calculated, but unfortunately it fail for out specific scenario. Now, I disable -Wunused:all until https://github.com/lampepfl/dotty/issues/16650 is fixed.

bugfix: Disable -Wunused:all for Scala 3

---

metals/src/main/scala/scala/meta/internal/metals/clients/language/ConfiguredLanguageClient.scala

Previously when we'd go from the quickpick params to a
showMessageRequest we wouldn't set the type. All of the usecases were
Info, so it was easy to add this in.
Fixes #4839

fix: ensure when we go from quickpick to showMessageRequest we include type

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/pc/PcRenameSuite.scala

It seems we forgot to include a check whether classOf actually contains a symbol we are interested in.
Fixes https://github.com/scalameta/metals/issues/4844

bugfix: Properly check symbol in classOf

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/Scala3DocumentHighlightSuite.scala

Fixes https://github.com/scalameta/metals/issues/4848
Turns out that the symbols on different extension methods are different despite being in the same group and it's hard to find all those symbol, but their definition should be in the same exact place.

bugfix: Make sure that correct extension param is highlighted

---

mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala

Related to https://github.com/scalameta/metals/issues/4837

bugfix: Check if symbol exists before invoking .owner

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala

fixes https://github.com/scalameta/metals/issues/4768

improvement: Allow extracting member when file contains  toplevel `val`|`def`|`given` etc.

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

This caused an issue in scastie resulting in no diagnostics, because we tried to read from a directory like from scala/java file

fix: In bloop directories were seen as scala/java files

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/NamedArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Reported in https://github.com/scalacenter/scastie/issues/711

bugfix [Scala 3]: Don't show named argument completions on infix methods

---

metals/src/main/scala/scala/meta/internal/metals/AdjustLspData.scala
metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
metals/src/main/scala/scala/meta/internal/metals/clients/language/ConfiguredLanguageClient.scala
tests/mtest/src/main/scala/tests/TestSemanticTokens.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
tests/unit/src/test/scala/tests/SemanticHighlightLspSuite.scala

Previously, semantic tokens would not work for files ending with `.sc` or `.sbt`. Now they properly work with correct types inferred by the compiler.
Main parts were:
- discarding any tokens that were added to the file, this required making sure that adjust position would return lines < 0, so that we can recognize those tokens
- make sure that the first token had the correct deltas
- worksheets need to have semantic tokens refreshed after downloading all dependencies etc.
- added tests for all the possibilities including Ammonite scripts, worksheets, sbt files within sbt BSP and Bloop

feature: Add semantic tokens for sbt and script files

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

Previously, we would have one command and we would parse the arguments to figure out what we need to do. This meant we couldn't use the ParametrizedCommand etc. and this one command had multiple behaviours. Now, I split all possible arguments into separate commands, which share the id, but thanks to using unapply of ParametrizedCommand we are able always end up at the correct case.
One issue is that we need to keep the in the same order, but this was exactly the same previously. As an added bonus I had to document all the possible commands we have.

refactor: Split DebugAdapterStart command into separate commands

---

mtags/src/main/scala-2/scala/meta/internal/pc/Keywords.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionPos.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/KeywordsCompletions.scala
mtags/src/main/scala/scala/meta/internal/pc/Keyword.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

resolves https://github.com/scalameta/metals/issues/3057
Added `*` as a completion suggestion in imports in Scala 3 (as a keyword)

Fix: add star to import completions in Scala 3

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala

This pr consists of two changes:
1. Previously, exhaustive case completion in 
```scala
List(Option(1)).map{
cas@@
} // resulted in
List(Option(1)).map{
case Some(value) => 
case None =>
}
// now results in 
List(Option(1)).map{
case Some(value) => 
case None =>
}
```
2. Previously cases in exhaustive-case completion in Scala 3 were not sorted, now we sort them the same way as for exhaustive match

improvement: Better exhaustive-case completion

---

metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala
project/V.scala
tests/unit/src/test/scala/tests/GradleRepositoriesTest.scala

previously: metals run gradle bloopInstall using generated init script with only mavenCentral() repository
now: user can customise the repositories
resolves https://github.com/scalameta/metals/issues/2535

fix: init script repositories for gradle

---

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
tests/cross/src/main/scala/tests/BasePcRenameSuite.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala

Previously, if the code never compiled, we would miss semanticdb and we often wouldn't be able to navigate to a symbol from outside the current file. Now, instead we will try to use the symbol search to find the symbol matching the current name.
This solution might cause some false positives with the same names, but I think overall this might help users a lot and avoid having broken metals in case of not compiling workspace.
This should also improve a lot with https://github.com/scalameta/metals/pull/4798

improvement: Fallback to symbol search as the last possibility for definition

---

mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala

parents are now a LazyTreeList, which is doesn't have any List methods.

bugfix: Fix compilation with newest nightlies

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/debug/ExtendedScalaMainClass.scala

Previously, we would use the classpath as string which might be too long on some systems for example on Windows. Now, we define it using jar with the classpath defined inside its manifest. This also benefits other system since it makes the path shorter.
The jar will only be created once per classpath change and deleted on exit.
Fixes https://github.com/scalameta/metals/issues/4827

bugfix: Use classpath jar for defining run classpath

---

.git-blame-ignore-revs
.scalafmt.conf
mtags/src/main/scala-3/scala/meta/internal/pc/ConvertToNamedArgumentsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbSymbols.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/NamedArgCompletions.scala
project/V.scala

It looks like the most recent scalafmt got released on JDK 11 which makes the tests for Scalafmt hang indefinetely.

Revert scalafmt update

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/StatusBar.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
project/TestGroups.scala
tests/unit/src/test/scala/tests/FormattingLspSuite.scala
tests/unit/src/test/scala/tests/debug/DebugProtocolCancelationSuite.scala

Previously, users would need to wait until the session times out, which would mean that it might be too long for some users and too little for some other. Now, we offer to cancel the session within a slow task.
This gives the control to the user instead of arbitrary timeout.
Fixes https://github.com/scalameta/metals/issues/4864

improvement: Allow manual cancel of starting debug session

---

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala

Previously, we would suggest both object and class even if it clearly could not be a class. Now, we add some heuristics to minimize false positives.

chore: Choose object when using symbol search as fallback

---

.github/workflows/ci.yml

It looks like we're currently running out scripted tests twice when we
don't need to. We're running it in the sbt integration job and also in
the sbt-metals/scripted job. This remotes the scripted stuff from the
sbt integration job and just relies on it running in the scripted one.

fix(ci): don't run scripted tests twice

---

metals/src/main/scala/scala/meta/internal/metals/Trace.scala

So this was a total oversight of mine that has sort of existing for quite some time since it looks like it was changed in https://github.com/scalameta/metals/commit/1559f52e0f78e027519272414a8dde05ac355ac4. I've randomly had people in nvim-metals mention that they sometimes get `.metals/` dirs created where they didn't expect, but never had a good reproduction to really dig into. However today when trying to reproduce https://github.com/scalameta/nvim-metals/issues/530 I realized that this was happening.
The issue is that in editors like VS Code you almost always have a "workspace" since you open a "workspace". In editors like nvim, this concept is artificial and we instead have to rely on the client sending in the correct `rootUri`. Relying on the `cwd` is unsafe since if you have a …

fix: ensure a new `.metals/` dir isn't create when/where undesired

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionPos.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/InterpolatorCompletions.scala

For https://github.com/scalameta/metals/issues/4837
There are some other places that access span, but most of them seem safe.

bugfix: Add checks if span exists

---

metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala

Previously, Metals would fail to read files from jars when they contained +. Now, we added a couple of fallbacks to make sure that works correctly.
Fixes https://github.com/scalameta/metals/issues/4896

bugfix: Fix issues with jars containing + on windows

---

project/V.scala

3.3.0-RC1 was broken so this can land straight in deprecated.

chore: Add support for Scala 3.3.0-RC2

---

mtags/src/main/scala-2/scala/meta/internal/pc/SemanticTokenProvider.scala

Previously, we could get an exception:
```
java.lang.UnsupportedOperationException: Position.start on NoPosition
at scala.reflect.internal.util.Position.fail(Position.scala:24)
at scala.reflect.internal.util.UndefinedPosition.start(Position.scala:101)
at scala.reflect.internal.util.UndefinedPosition.start(Position.scala:97)
at scala.meta.internal.pc.SemanticTokenProvider.$anonfun$ord$1(SemanticTokenProvider.scala:41)
at scala.meta.internal.pc.SemanticTokenProvider.$anonfun$ord$1$adapted(SemanticTokenProvider.scala:40)
at scala.math.Ordering$$anon$4.compare(Ordering.scala:316)
at scala.collection.immutable.RedBlackTree$.upd(RedBlackTree.scala:415)
at scala.collection.immutable.RedBlackTree$.update(RedBlackTree.scala:175)
at scala.collection.immutable.TreeSet.incl(TreeSet.scala:163)
at …
```

bugfix: Always check if position is defined

---

mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala

Previously, we would always treat path as file if they had a scala or java extension even if that would be directory. Now, we also check if it's a file.

bugfix: Always check if a scala/java file is actually a file

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcDefinitionProvider.scala
tests/cross/src/test/scala/tests/pc/PcDefinitionSuite.scala

Previously, when some nodes were absent from the typed tree we wouldn't be able to find the definition. Now, we try to find them in the untyped tree, which sometimes might have symbols already present, since the full typer phase was already done.
Fixes https://github.com/scalameta/metals/issues/4903

bugfix: Fix issues with go to definition in derived clauses

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionPatternSuite.scala

Previously:
```
case abc@@
```
created an empty pattern.
Now: it creates the desired pattern "abc".
Note: this is broken for keywords in Scala 3 (https://github.com/scalameta/metals/issues/4367).

bugfix: case pattern completions for bind

---

tests/unit/src/test/scala/tests/FindTextInDependencyJarsSuite.scala

Not sure why this changed for windows, but I think this is not important enough to dig in.

chore: Update test for Windows

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala

For expressions like (1 + 2).toString, span was incorrect, because they were treated as right associative infix operators.

bugfix: Fix `select.nameSpan` for expressions in parentheses

---

docs/integrations/debug-adapter-protocol.md
metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala
metals/src/main/scala/scala/meta/internal/metals/clients/language/ConfiguredLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala
tests/unit/src/main/scala/tests/BaseWorkspaceSymbolSuite.scala
tests/unit/src/test/scala/tests/RunProviderLensLspSuite.scala

Previously, to run the code clients would need to support DAP, which is quite heavywight and not needed at all times. Now, we add `runProvider` that can be used to indicate that the editor only wants to support `run` lenses. The editor can later use the `shellCommand` field to run the code. This was suggested a while ago by @ayoub-benali and could possibly be used for sublime (and not only).

improvement: Add the possibility to only support running the code

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
mtags-interfaces/src/main/java/scala/meta/pc/DisplayableException.java
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala-2/scala/meta/internal/pc/ConvertToNamedArgumentsProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ConvertToNamedArgumentsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala/scala/meta/internal/pc/CodeActionError.scala
tests/cross/src/test/scala/tests/pc/ConvertToNamedArgumentsSuite.scala

previously: it was possible to convert to named arguments for a Java defined class, which resulted in invalid code
now: upon choosing convert to named arguments on a Java defined class no text edits are performed and a message "Cannot convert to named arguments for a Java class." is displayed instead
resolves https://github.com/scalameta/metals/issues/4851

fix: do not convert to named arguments for a Java class

---

.github/workflows/ci.yml
build.sbt
docs/contributors/releasing.md
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
project/plugins.sbt

Previously, we would change the presentation compiler interfaces whenever needed, but because of that we wouldn't be able to for example load an older mtags version or  move parts of Scala 3 mtags to the compiler.
Now, we add Mima and we will require some basic implementation, which enables us to
- whenever we depracate Scala version we can hardcode the last supported mtags
- allow the Scala 3 compiler to use the same interfaces

improvement: Add Mima for mtags Java interfaces

---

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
tests/mtest/src/main/scala/tests/RangeReplace.scala
tests/slow/src/test/scala/tests/feature/CrossReferenceSuite.scala
tests/unit/src/main/scala/tests/TestRanges.scala

Previously:
for `import p.{A as B}` for B would not show any references.
Now: finds all the references same as for A.
The PR contains also a fix for adding ranges markings in tests. Previously it would apply the second range marking in the same line without the necessary adjustment (shift).
resolves https://github.com/scalameta/metals/issues/4562

fix: show references for renamed import

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SemanticTokenProvider.scala
tests/cross/src/test/scala/tests/tokens/SemanticTokensSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
tests/unit/src/test/resources/semanticTokens/example/MacroAnnotation.scala
tests/unit/src/test/resources/semanticTokens/example/TryCatch.scala

Previously `SemanticTokenProvider` had its own tree traverser for collecting all symbol occurrences.
This PR changes it to use `PcCollector`, which should make optimisation and bugfixes easier. It should also simplify adding `SemanticTokens` for Scala 3

improvement: Use PcCollector for SemanticTokenProvider

---

metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala

Stumbled across an exception when the `message` in `build/taskStart` notification is `null` and according to [BPS specs](https://build-server-protocol.github.io/docs/specification/#task-started) it may be a valid case.

Add message not null checks

---

mtags/src/main/scala-2/scala/meta/internal/pc/AutoImportsProvider.scala

Helps with https://github.com/scalameta/metals/issues/4906
This shouldn't happen because auto import position is always defined except for when in imports, but we later have a condition that should deal with that.

improvement: Print information if compiler failed to infer edits for import

---

tests/unit/src/test/scala/tests/FindTextInDependencyJarsSuite.scala

This looks like JDK being slowly updated on different machines, so this started failing only after some time on all sytems.

chore: Fix expected line in FindTextInDependencyJarsSuite

---

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MtagsResolver.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/ProblemResolver.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/ScalaProblem.scala
metals/src/main/scala/scala/meta/metals/DownloadDependencies.scala
project/TestGroups.scala
project/V.scala
tests/unit/src/main/scala/tests/TestMtagsResolver.scala
tests/unit/src/test/scala/tests/MessagesSuite.scala
tests/unit/src/test/scala/tests/RemovedScalaLspSuite.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

Previously, whenever we would drop support for a particular Scala version we would no longet support it in any way (no hover etc.). Now, thanks to having MiMa, we can always point to the last supported version and allow users to use it at their own risk.
This also addresses issues when some courses might be outdated and users would loose their support in Metals, which would be really bad for language adoption.

improvement: Allow users to use older Scala support

---

metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala

There is no need to check for any specific markers, we should just try our best to find a symbol.
For example:
```
[T] java.nio.file.FileSystemException:/Users/kpodsiadlo/.../.bloop/common/bloop-bsp-clients-classes/classes-bloop-cli-vSjz_SG8RNKglt17I28D_A==/com/evolution/.../data/macros/WeightsMacros.class: Invalid argument
[T]     java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
[T]     java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[T]     java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[T]     java.base/sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:246)
[T]     java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603)
[T] …
```

improvement: Remove check for stacktrace markers

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcDocumentHighlightProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcRenameProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcValReferenceProviderImpl.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SemanticTokenProvider.scala

Benchmarks for semantic tokens were broken because of some null symbols, now we replace them with `NoSymbol`.
It happened in https://github.com/scalameta/metals/pull/4867#discussion_r1089739671 while dropping `Option`
Also, changes how we use `fallbackSymbol`. Instead of creating `Ident(sym)` tree, we add parameter to `collect`

improvement: Add null check in SemanticTokenProvider

---

metals/src/main/scala/scala/meta/internal/metals/Directories.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/main/scala/tests/TreeUtils.scala

Previously, the exception could break anthing trying to use Trees and since it's an error in the parser we shouldn't break metals. Now, we catch the exception instead and print the code it failed on.
Related to https://github.com/scalameta/metals/issues/4837

bugfix: Catch StackOverflowException from the parser

---

tests/unit/src/test/resources/semanticTokens/example/Definitions.scala
tests/unit/src/test/resources/semanticTokens/example/MacroAnnotation.scala
tests/unit/src/test/scala/tests/SemanticTokensExpectSuite.scala

Previously, we didn't add classpath so some tokens were inferred wrong. Now, we use the input project classpath properly.

improvement: Add classpath to expect semantic tokens suite

---

tests/unit/src/main/scala/scala/meta/internal/metals/debug/TestDebugger.scala

It seems this is ignored in scala-debug-adapter tests and VS Code doesn't seem to have a problem like the tests do. I think it's safe to ignore those timeout for the sake of less flakiness.

improvement: Don't fail on no shutdown message

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala

Previously, we would check for specific build servers and versions if they support scala-debug-adapter with the new version. However, this might lead to disallowing using debugger if the name just mismatched. Now, we only ban older bloop server versions instead. Anything new supporting DAP will most likely use newest DAP.
Fixes https://github.com/VirtusLab/scala-cli/issues/1831

bugfix: Support scala command as BSP server for debug

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala

Previously, we merging different auto imports into one, we would us uri to get the changes from the single action. That uri might have been encoded/decode which might be different from what there is in a map of changes.
Now, instead we just merge all the changes to avoid any issues with url decoding or encoding. Those changes cannot come from different files, so this will not be an issue.
Fixes https://github.com/scalameta/metals/issues/4906

bugfix: Fix issues with auto imports not showing up

---

mtags/src/main/scala-2/scala/meta/internal/pc/SemanticTokenProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala
tests/cross/src/test/scala/tests/pc/PcRenameSuite.scala

In Scala3, in cases like
```scala
def m(
a: Int,
b: <<Int,>> // this gets highlighted with the comma
) = ???
```
It was an issue in semantic tokens support for scala3, when we need positions to be the same.
Also, now we use `PcCollector.adjust` in `SemanticTokenProvider`

fix: Adjust position in PcCollector for trailing comma

---

mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala

Previously, we would use scalameta parser to correctly insert type in some places. Now, we removed it to enable easier migration of the module to scala3-compiler

improvement: Remove scalameta parsing in InferredTypeProvider

---

tests/unit/src/main/scala/scala/meta/internal/metals/debug/TestDebugger.scala

Previously, if the debugee process closed before sending the terminate message, we would still wait to get all output for terminated promise in tests. Now, when timed out on terminated we fullfill the promise, so that anything waiting on it (for example allOutput) can proceed.

bugfix: Set terminated to true when timeout

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/AmmoniteIvyCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/InterpolatorCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/NamedArgCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
mtags/src/main/scala/scala/meta/internal/pc/InterpolationSplice.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionBacktickSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

Previously: If a prefix of the word to be completed was a keyword it was be handled incorrectly in Scala 3. E.g, for
```
val newObject = 3
new@@
```
the completion `newObject` wasn't produced.
The compiler assumed the current word to be an indeed a keyword and constructed the typed tree accordingly.
Now: We artificially add "CURSOR" value after the cursor position for compilation.
resolves: https://github.com/scalameta/metals/issues/4367
touches on: https://github.com/scalameta/metals/issues/3915

bugfix: completions for keyword lookalikes

---

docs/integrations/debug-adapter-protocol.md
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

Previously, the only possibility to discover the main class to run was to try and run it. Now, we can also ask for it so that client editor can use that shell command.
Needed for https://github.com/scalameta/metals-vscode/pull/1298

feature: Add the possibility to discover the main class to run

---

metals/src/main/scala/scala/meta/internal/metals/GithubNewIssueUrlCreator.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala

An improvement to "create GitHub issue" command.
Previously: it just redirected to the GitHub new issue creator.
Now: redirects and fills in basic information (metals version, os, editor/extension, java version).
connected to: https://github.com/scalameta/metals/issues/4924
https://github.com/scalameta/metals/issues/new?body=%3C%21--%0A++++++++Describe+the+bug+...%0A%0A++++++++Reproduction+steps%0A++++++++++1.+Go+to+...%0A++++++++++2.+Click+on+...%0A++++++++++3.+Scroll+down+to+...%0A++++++++++4.+See+error%0A--%3E%0A%0A%23%23%23+Expected+behaviour%3A%0A%0A%3C%21--+A+clear+and+concise+description+of+what+you+expected+to+happen.+--%3E%0A%0A**Operating+system%3A**%0AMac+OS+X%0A%0A**Java+version%3A**%0A17.0.1%0A%0A**Editor%2Fextension%3A**%0AVisual+Studio+Code+v1.75.1%0A%0A**Metals+version%3A** …

Improvement: adds details to github issue

---

.github/workflows/check_scala3_nightly.yml

This might cause the nightlies to be discovered much later.

improvement: Don't use cache when querying for Scala nightlies

---

mtags/src/main/scala-2/scala/meta/internal/pc/SemanticTokenProvider.scala
tests/cross/src/test/scala/tests/tokens/SemanticTokensSuite.scala

```scala
package example
import util.{Failure => NoBad}
import math.{floor => _, _}
class Imports {
// rename reference
NoBad(null) // we have two symbols here: `Failure` class and `apply` method
max(1, 2)
}
```
From two symbols on `NoBad`, we were first trying to pick the one with name matching text, but the name is `Failure`, not `NoBad`. This issue only appeared when imported name was the same length as `apply` (5 letters)

fix: Wrong semantic token for renamed imported classes

---

mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala

Fixes https://github.com/scalameta/metals/issues/4989

bugfix: Always check if a Scala file is an actual file

---

metals/src/main/scala/scala/meta/internal/metals/ScalacDiagnostic.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

Previously, auto imports in worksheets would have unnecessary indent.
```scala
val a = SortedSet@@ 
//completion would result in
import scala.collection.immutable.SortedSet
val a = SortedSet
```
Solves issue mentioned in https://github.com/scalameta/metals/issues/4793

fix: Remove additional indent for imports in worksheets

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/Scala3DocumentHighlightSuite.scala

Previously, Metals would have a hanging thread when for example in github.com:Atry/scalajs-all-in-one-template. Now, it doesn't end up in an infinite loop.
I haven't been able to find a proper test for it aside from the very complex example with macros, but we shouldn't need to traverse expansion as it's the tree that is not in the original code.
Fixes https://github.com/scalameta/metals/issues/4987

bugfix: Don't collect symbols from Inline expansion

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionScala3Suite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/slow/src/test/scala/tests/feature/CompletionCrossLspSuite.scala
tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala

Previously, auto imports would only work with new + classname or with objects. Now, since Scala 3 allows omitting new, we also suggest classes that can be constructed without the new keyword.
Fixes https://github.com/scalameta/metals/issues/4988

bugfix: Suggest class constructors when importing symbols

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/MunitTestFinder.scala
tests/unit/src/test/scala/tests/testProvider/TestSuitesProviderSuite.scala

Fixes https://github.com/scalameta/metals/issues/5001

bugfix: Fix infinite loop when searching for munit test cases

---

mtags/src/main/scala-2/scala/meta/internal/pc/ExtractMethodProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ExtractMethodProvider.scala
tests/cross/src/test/scala/tests/pc/ExtractMethodSuite.scala

Previously: extract methods code action would ignore inner methods.
Now: it takes the inner methods as params.
resolves: https://github.com/scalameta/metals/issues/4360

bugfix: inner methods passed as params for extract method code action

---

tests/unit/src/main/scala/tests/BaseLspSuite.scala

Previously, when FileWatcher tests would be retried on MacOS (where it is most flaky) we would get an exception that the server is alreayd initialized. Now, we cancel the old server properly and create a new one for the retried tests.

bugfix: Cancel and create new server in test retry

---

project/V.scala

I wanted to quickly send this in to try and get it into the release. With this
new version Gradle 8 _should_ be supported which will be nice to have for Gradle
users

dep: bump gradleBloop from 1.5.8.to 1.6.0

---

build.sbt
project/V.scala

This is an attempt to force Scala Steward to update the scala-debug-adapter version in:
https://github.com/scalameta/metals/blob/34b3cc8f38792be4170344bb4bb685ba15dc3c2a/project/V.scala#L22
It used not to do it because this version was not used in any `libraryDependencies` setting. It was only used in the `buildInfoKeys`:
https://github.com/scalameta/metals/blob/34b3cc8f38792be4170344bb4bb685ba15dc3c2a/build.sbt#L462

Force update of scala-debug-adapter by Scala Steward

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Previously: we'd perform `substituteTypeVars` for select only if the member had any ages lists.
Now: we check if it's a method, to make this work for methods with no args lists.
connected to: https://github.com/scalameta/metals/issues/3030

bugfix: perform `substituteTypeVars` also for methods with no args

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

Previously tokens were alligned incorrectly, because of additional indent.

fix: Fix semantic tokens for worksheets in Scala 3

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala

Previously, it seems in some cases tokenization would hang at EOF judging from the stacktrace:
```
"pool-1-thread-57" #225 prio=5 os_prio=31 tid=0x00007f80a80f6800 nid=0x12107 runnable [0x0000700017937000]
java.lang.Thread.State: RUNNABLE
at scala.meta.internal.mtags.ScalaToplevelMtags.valIdentifiers(ScalaToplevelMtags.scala:622)
at scala.meta.internal.mtags.ScalaToplevelMtags.emitTerm(ScalaToplevelMtags.scala:470)
at scala.meta.internal.mtags.ScalaToplevelMtags.$anonfun$loop$10(ScalaToplevelMtags.scala:225)
at scala.meta.internal.mtags.ScalaToplevelMtags$$Lambda$6359/1132081275.apply$mcV$sp(Unknown Source)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.meta.internal.mtags.MtagsIndexer.withOwner(MtagsIndexer.scala:48)
at …
```

bugfix: Make sure that tokenizing doesn't hang

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/Scala3DocumentHighlightSuite.scala

Fixes span for extension methods with specified argument type i.e. 
`(1: Int).foo()` resulted in highlighting `<<(1:>> Int).foo()`
Connected to https://github.com/scalameta/metals/issues/5026

bugfix: Fix span for extension methods

---

metals/src/main/scala/scala/meta/internal/metals/SemanticTokensProvider.scala
tests/unit/src/test/resources/semanticTokens/example/ImplicitConversions.scala
tests/unit/src/test/scala/tests/SemanticHighlightLspSuite.scala
tests/unit/src/test/scala/tests/SemanticTokensExpectSuite.scala

In order to do that, we need to parse each using directive and add semantic tokens. For now, using directives can only appear before any scala code.
solves https://github.com/scalameta/metals/issues/5013

improvement: Add semantic highlight for using directives

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala
mtags/src/main/scala/scala/meta/internal/mtags/SemanticdbClasspath.scala
mtags/src/main/scala/scala/meta/internal/mtags/SemanticdbPath.scala

I was really annoyed when I found that https://github.com/scalameta/metals/pull/5042 is not working as expected because Test Explorer onDelete was called only with semanticDB files..
Value classes ftw!

chore: use value class to for new semanticDB path type

---

metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
tests/slow/src/test/scala/tests/feature/WorksheetCrossLspSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

Previously, when Ycheck-reentrant was included the worksheets would not show any results. Now they do.
It seems this might be caused by the fact that an exception is thrown from the compiler instead of a diagnostic.
```
2023.03.16 16:04:12 ERROR possible data race involving globally reachable mvariable ma in mpackage mcom.rmet.scala3seedling: Int
use -Ylog:checkReentrant+ to find out more about why the variable is reachable.
```

bugfix: Filter out -Ycheck-reentrant

---

metals/src/main/scala/scala/meta/internal/decorations/SemanticdbTreePrinter.scala
metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

Previously: all method synthetic decorations were printed in the same manner.
Now: for constructors we print the class name instead on method name ("<init>").
Resolves: https://github.com/scalameta/metals/issues/4698

bugfix: print better constructors in synthetic decorator

---

mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala

Path for selectDynamic changed, now it starts with Select(_, selectDynamic). We had to adjust `fallbackToDynamics` to match also new path. Also, now  `MetalsInteractive.enclosingSymbolsWithExpressionType` returns `selectDynamic` symbol.
Fixes nightly cross tests.

fix: Fix select dynamic hover tests for 3.3.1-RC1

---

docs/contributors/updating-website.md
website/docusaurus.config.js
website/package.json

We've been working on updating the algolia index for scalameta sites. However, there's been a lot of trouble keeping the algolia keys up to date, and the search function sometimes goes down.
see:
https://github.com/scalacenter/scalafix/issues/1514 https://github.com/scalameta/metals/pull/3604
https://github.com/scalameta/scalameta/pull/2569
This commit switches the search function from algolia to one of the
local search indexes
https://github.com/easyops-cn/docusaurus-search-local
chosen from
https://docusaurus.io/community/resources#search
I picked easyops-cn/docusaurus-search-local because
- it seems to be well maintained
- it works without server setup (unlike typesense)
- looks prettier than cmfcmf/docusaurus-search-local (original one)
but, other suggestions are welcome :)
--- …

docs: Switch from algolia to easyops-cn/docusaurus-search-local

---

metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/data/ClassName.scala
metals/src/main/scala/scala/meta/internal/metals/data/FullyQualifiedName.scala
metals/src/main/scala/scala/meta/internal/parsing/ClassFinder.scala
metals/src/main/scala/scala/meta/internal/parsing/finder/ClassKind.scala
metals/src/main/scala/scala/meta/internal/parsing/finder/MangledClassName.scala
tests/unit/src/main/scala/tests/BaseClassFinderSuite.scala
tests/unit/src/test/scala/tests/classFinder/ClassBreakpointSuite.scala
tests/unit/src/test/scala/tests/classFinder/FindAllClassesSuite.scala
tests/unit/src/test/scala/tests/classFinder/TastyNameResolverSuite.scala

classes like `implicit class FooOps(private val foo: Int) extends AnyVal` produces two class files: FooOps.class and FooOps$.class. This PR:
- does some refactor in ClassFinder
- thanks to modifications, it's easier to add companion object for implicit, anyval classes
- EDIT: case class companion object was missing too, added

feat: find companion object of AnyVal, implicit class in class finder

---

bin/merged_prs.sc
docs/contributors/releasing.md

This is mainly due to an error that I'm seeing in the Steward logs at https://github.com/scalameta/steward/actions/runs/4506533671/jobs/7933423154#step:4:516
so I figured I'd just update this.

refactor: use scala-cli for script instead of Ammonite

---

mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala

Previously hover didn't work on structural types in Scala 3, e.g. type User = { def name: String}, changing unapply method fixes it.

feat: Hover on structural types in Scala 3

---

metals/src/main/scala/scala/meta/internal/metals/SemanticTokensProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala

Previously, semantic highlighting would be broken inside Metal's build.sbt file. This was caused by the fact that start/end is validated to always be `start <= end`, so we need to change it together instead one after another. Another issue was if we haven't find the literal name inside the source code we would get another exception.
Now, both cases are handled and this was tested manually for metals build file. This wasn't breaking in smaller test cases.
Also, when no semantic tokens are returned, we return an empty list not to interfere with the default highlighting.

bugfix: Fix semantic highlight in sbt files

---

mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala

Previously: the inferred type was not dealiased.
Now: if the inferred type is not in the scope we dealias (keeping opaque types).
Note 1: This is very binary, since we either don't dealias anything or dealias all (also stripping annotations) if any of the aliases is not in scope:
```
object M:
type T1 = Int
object R:
type T2 = String
def get: Either[T1, T2] = ???
val m = R.get //inferred type: Either[Int, String]
```
We could strip only the ones not in scope instead.
Note 2: Alternatively we could present the user with options.
Resolves: https://github.com/scalameta/metals/issues/4858

improvement: dealias inferred types if not in scope

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/MillifyScalaCliDependencyCodeAction.scala
tests/unit/src/test/scala/tests/codeactions/MillifyScalaCliDependencyCodeActionSuite.scala

This PR is somewhat complimentary to https://github.com/scalameta/metals/pull/4465
It introduces the code action that would convert SBT style imports to Mill style in scala-cli `using (dep | lib | plugin)` directives. Dependencies in project readme docs usually are SBT style so I think it might be useful.
It's a draft, LSP tests are still in progress but since this is my first contribution please let me know if it's the right direction.

Code action to convert dependencies from sbt to mill style

---

mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala
tests/cross/src/test/scala/tests/pc/PcDefinitionSuite.scala

In some case [TypeTest](https://dotty.epfl.ch/docs/reference/other-new-features/type-test.html) will be used in pattern match and it actually changes the case to a new unapply. Previously, we wouldn't be able to figure out the initial type.
Now, we special case TypeTest and find the exact typeSymbol we need.
Fixes https://github.com/scalameta/metals/issues/5102
There are two connected fixes here in two commits.

bugfix: Fix go to definition and hover for TypeTest

---

metals-bench/src/main/scala/bench/SemanticTokensBench.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticTokensProvider.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
tests/unit/src/test/resources/semanticTokens/example/Imports.scala
tests/unit/src/test/resources/semanticTokens/example/MacroAnnotation.scala
tests/unit/src/test/resources/semanticTokens/example/Miscellaneous.scala
tests/unit/src/test/resources/semanticTokens3/example/Imports.scala
tests/unit/src/test/resources/semanticTokens3/example/Miscellaneous.scala
tests/unit/src/test/resources/semanticTokens3/example/NamedArguments.scala
tests/unit/src/test/resources/semanticTokens3/example/StructuralTypes.scala
tests/unit/src/test/scala/tests/RemovedScalaLspSuite.scala
tests/unit/src/test/scala/tests/SemanticTokensLspSuite.scala

When we can't match any node with scalameta ident token, we make it either `class` or `variable`, if it starts with upper or lower case. Now this `variable` will have `readonly` modifier, since it's rarely mutable (e.g. self types, wildcard imports).
Solves https://github.com/scalameta/metals/issues/5052

improvement: Make fallback semantic tokens readonly

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala

Previously, we would only show lenses if the name of the Scala server was scala-cli. We now also support plain `scala`.
I also adjusted when searching for ScalaCLI on PATH to use plain `scala`
Fixes https://github.com/scalameta/metals/issues/5116

bugfix: Show lenses when BSP server is plain Scala

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala

Hi!  This is a PR attempts to address the issue in which test case code lenses may not initially appear for a file and you would need to re-open to obtain to obtain test case lenses (https://github.com/scalameta/metals/issues/5115).
The proposed fix is to call `client.refreshModel` after test discovery (`workspace/codeLens/refresh`).
Thanks!

Refresh test case code lenses after discovery

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/TypeDocumentHighlightSuite.scala

Previously, when using document highlight on the type parameter in the primary constructor, we would only get that specific parameter highlighted. This is because those were treated as different symbols with one having constructor parent and the other trait param.
Now, we properly match them as the same symbol from the user perspective.
This seems to be handled the other way already.

bugfix: Show document highlight with cursor on primary cosntructor

---

docs/editors/overview.md

- worksheets with decoration protocol are fully supported
- lsp-metals supports quite a lot of metals extensions
- source file analyzer commands are supported

Update emacs support table

---

metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala

While we can generate `.bsp/bazelbsp.json` by
`cs launch org.jetbrains.bsp;bazel-bsp:2.6.1 -M org.jetbrains.bsp.bazel.instal.Install` https://github.com/JetBrains/bazel-bsp#easy-way-coursier
Metals couldn't connect to the bazel-bsp because it wan't autoConnectable. This change enable Metals to see bazel-bsp as autoConnectable, and Metals will spawn and connct to bazel bsp if there's `.bsp/bazelbsp.json`.
As @kpodsiad did in
https://github.com/scalameta/metals/pull/3233
we should
- reindex if the build configuration changed
- I'm wondering we should check all *.bzl files and WORKSPACE and BUILD / BUILD.bazel files. And maybe we should honor the project view settings.
- Auto install bazel-bsp when we see `WORKSPACE` file.
https://github.com/scalameta/metals/issues/5138
partially fix for …

Auto spawn/connect to bazel-bsp if it's installed

---

.github/workflows/mtags-auto-release.yml

The current nightly release is failing.

chore[skip ci]: Switch nightly releases to branch with fixed test

---

tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala

I didn't realize at the time that the error was related, but it's due to a larger amount of commands being invoked, which looks correct.

bugfix: Fix test after changes in #5124

---

architecture.md

This PR adds some sentences about MtagsIndexer in `architecture.md`.
(context: @kasiaMarek and I talked a bit about `MtagsIndexer`, and I thought that these modules are worth documenting)

Add a description about MtagsIndexer in architecture.md

---

.gitignore
bin/merged_prs.scala
docs/contributors/releasing.md

Previously, I only quickly switched the Ammonite script to Scala CLI, but I might have not actually tested it out properly. Now, I was able to generate release notes. I switched to a normal Scala file since this allows us to have sensible arguments

bugfix: Fix Scala CLI script for release notes

---

.github/workflows/release.yml

It seems we can use select, then .id and then pipe it with |

chore: Add back locking mechanism with using jq syntax for selection

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/NamedArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Previously: no arguments name completions should be provided inside of a contractor invocation both for Scala 2 and 3
Now: name completions are correctly provided
resolves: https://github.com/scalameta/metals/issues/5168

bugfix: arguments name completions for constructors

---

metals/src/main/scala/scala/meta/internal/metals/SemanticTokensProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/TypeDocumentHighlightSuite.scala
tests/cross/src/test/scala/tests/tokens/SemanticTokensScala3Suite.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
tests/unit/src/test/scala/tests/SemanticTokensLspSuite.scala

Touches https://github.com/scalameta/metals/issues/5065
I couldn't reproduce broken semantic highlights in the whole file, but this PR solves issue with no highlight/semantic highlight on `@@` (and other symbols containing `@`, `!` etc)
Name for `@@` is "$at@at", which doesn't match string "@@". Now we match on decoded name, which is "@@".
Also, changes `soughtFilter` to be easier to use

fix: Fix PcCollector for `@@` symbol

---

metals/src/main/scala/scala/meta/internal/metals/SemanticTokensProvider.scala
tests/unit/src/test/scala/tests/SemanticTokensLspSuite.scala

Previously semantic tokens were incorrect for multiline comments with empty lines

fix: Fix semantic tokens for multiline comments

---

mtags/src/main/scala-3/scala/meta/internal/pc/SelectionRangeProvider.scala
tests/cross/src/test/scala/tests/pc/SelectionRangeCommentSuite.scala

solves https://github.com/scalameta/metals/issues/3615
only works with pure scala 3 project,doesn't seem to work with worksheet 
There's redundancy in code but I'm not sure how to reduce it :
```scala
val tkSrc = programStr.parse[Source].toOption.map(_.tokens)
val tkExpr = programStr.parse[Stat].toOption.map(_.tokens)
val tkType = programStr.parse[Type].toOption.map(_.tokens)
val tokens = tkSrc orElse tkExpr orElse tkType
```

fix:selection expansion in comments

---

build.sbt

A user reported very poor performance for directory/file registration on Windows (https://github.com/swoval/swoval/issues/161). This new version potentially addresses the cause of a performance regression that may have been introduced in v2.1.8.

Bump swoval version

---

metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
tests/unit/src/main/scala/tests/BaseScalaCliSuite.scala

Previously, Metals would report issues when shebang is preset. Now, instead we comment the shabangs line, which should work correctly since we replace the exact same number of characters.
Potentially this could be fixed in scalameta, but I feel like like this might be much more work than needed here.
Fixes https://github.com/scalameta/metals/issues/5179

bugfix: Auto comment shebang for scripts

---

project/V.scala

Previously, since Metals only knows about minimum supported Scala version, we would basically guess the recomended sbt version to update to. Now, instead we clearly state that the support depends on the specific Scala version that sbt is using.

improvement: Fail the build if supported sbt version wasn't updated

---

docs/build-tools/mill.md
metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala

The bloop contrib module was moved to the bloop package as part of 0.9.3. 
Without adding the bloop package, the bloop install command doesn't work on the latest milestone releases.
Ref: https://github.com/com-lihaoyi/mill/pull/992

fix: Add bloop package for bloop command

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
mtags/src/main/scala/scala/meta/internal/mtags/IndexingExceptions.scala
mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala

Passing the cause exception to the `Exception` contructor makes it easier for users to know what's going on: the JVM or the `printStackTrace` method will print the current exception and its cause (and the cause's cause, etc.). That way, we know in more detail what the underlying cause of the exception is.

Keep exception cause in some mtags exceptions

---

metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/BuildTargetUpdate.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/testProvider/TestSuitesProviderSuite.scala

Previously: Test cases were identified by build target and fully-qualified identifier.
Now: They are also identified by folder information (name & uri).
resolves: https://github.com/scalameta/metals/issues/5189

bugfix: send folder name and uri with information about tests

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/NamedArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Previously no argument name completion would be shown for parameters, that are context functions.
Now argument name completions are shown correctly.
resolves: https://github.com/scalameta/metals/issues/5165

bugfix: argument name completion for context function parameter

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcDocumentHighlightProvider.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala
tests/cross/src/test/scala/tests/pc/PcRenameSuite.scala

Previously, if for-comprehension contained lines with `=`, highlight and rename haven't always seen symbols in unapply (eg. (a,b) <- List((1,2)))

fix: Fix highlight and rename for unapply in for-comp

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/MillifyScalaCliDependencyCodeAction.scala
tests/unit/src/test/scala/tests/codeactions/MillifyScalaCliDependencyCodeActionSuite.scala

Previously, we would always update the first line whe updating using directive, which was caused by wrong positions in the Comment token since we only tokenized the current line for efficiency sake. Now, we properly adjust the range with the line number at which the cursor is at.

bugfix: Always change the correct comment when changing to mill syntax

---

metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala

Previously, when reconnecting we wouldn't actually reindex semanticdb, which could cause refrences to stop working. This wasn't an issue in Bloop since it copies a lot and we would be notified by those semanticdb files again. Now, we correctly index semanticdb files on connection.
Might be connected to https://github.com/scalameta/metals/issues/5176

bugfix: Correctly index semanticdb when reconnecting

---

mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionBacktickSuite.scala

In Scala 3, we don't have to backtick soft keywords in things like `a.end`

fix: Don't backting soft keywords in Select

---

metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/clients/language/ConfiguredLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/clients/language/NoopLanguageClient.scala

Connected to https://github.com/scalameta/metals/issues/5193
1. We don't refresh tokens if they are not enabled
2. We ignore the exception in refreshSemanticTokens since it might cause the server not to init (not exactly sure which flow)

improvement: Don't fail on refreshing semantic tokens

---

mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala

Previously, if there was an issue indeing a file we would fail searching for the particular query. Now, we pack it into try an retry in case of errors such as filesystem ones.
Fixes https://github.com/scalameta/metals/issues/5231

improvement: Retry indexing source file

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/tokens/SemanticTokensScala3Suite.scala

Adjust was broken for files starting with a symbol, eg. annotation, now we check if position is > 0

fix: Fix semantic highlight in files starting with annotation

---

mtags-shared/src/main/scala/scala/meta/internal/pc/SemanticTokens.scala
tests/cross/src/test/scala/tests/pc/PcRenameSuite.scala
tests/cross/src/test/scala/tests/tokens/SemanticTokensSuite.scala

In Scala 2, when for-comprehension includes `=` line, we get `scala.x$#` symbols on variables.
We don't want to highlight them as a `scala` package, so `namespace` needs to have lower priority that `variable`.
I've noticed this when looking at https://github.com/scalameta/metals/issues/2679, which was solved when we started using presentation compiler for local renames. I've added a test so we can close it.

fix: Semantic highlight on for-comp with `=` line

---

metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionExtensionMethodSuite.scala

Closes #4215
Seems like just removing `if query.nonEmpty` works.
I couldn't find any places where [MetalsSymbolSearch.searchMethods](https://github.com/scalameta/metals/blob/main/metals/src/main/scala/scala/meta/internal/metals/MetalsSymbolSearch.scala#L103-L113) or any of the subsequent calls would fail on empty query.
Please correct me if I'm wrong.
```scala
package a
extension (num: Int)
def ++ = num + 1
```

Provide extension method code completions when typing `xxx.@@`

---

metals/src/main/scala/scala/meta/internal/metals/clients/language/ConfiguredLanguageClient.scala

`handle` on CompletableFuture is invoked every time, so we should only log if an error is actually present.

bugfix: Only log message if it's not null

---

metals-bench/src/main/scala/bench/MetalsBench.scala
metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsSymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSearchVisitor.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala
mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala
mtags/src/main/scala/scala/meta/internal/metals/SemanticdbDefinition.scala
mtags/src/main/scala/scala/meta/internal/mtags/Mtags.scala
mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/mtest/src/main/scala/tests/DelegatingGlobalSymbolIndex.scala
tests/mtest/src/main/scala/tests/PCSuite.scala
tests/mtest/src/main/scala/tests/TestingSymbolSearch.scala
tests/mtest/src/main/scala/tests/TestingWorkspaceSearch.scala
tests/unit/src/main/scala/tests/MetalsTestEnrichments.scala
tests/unit/src/main/scala/tests/TestingWorkspaceSymbolProvider.scala
tests/unit/src/test/scala/tests/DefinitionDirectorySuite.scala
tests/unit/src/test/scala/tests/DefinitionSuite.scala
tests/unit/src/test/scala/tests/JdkSourcesSuite.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

Previously:
In ScalatopLevelMtags we expected an identifier after `given` keyword, so we would fail on `given [A]...`.
Now:
1. We check if it's an identifier and emit a term only if after the identifier there is a colon with only args and params in between.
2. We don't throw exceptions in `ScalatopLevelMtags` on an error, instead we create a report and keep indexing.

buigfix: given scala toplevel mtags

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala

Not sure what case was causing this, but I noticed it in `MetalsLspService`

bugfix: NoPosition on Bind in semantic tokens for scala 2

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
project/TestGroups.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/test/scala/tests/scalafix/ScalafixRunOnlyLspSuite.scala

Hi!  This PR implements a new command `scalafix-run-only` which can be used to run a subset of your project's scalafix rules.  You may either specify the rules in the command input, else the command prompts the user from a list of rules.
The command is similar to `scalafix-run`, though I was unsure on how that command could be modified in a backward compatible way and keep the behaviour where no rules specified = prompt user.
Anyway, let me know what you think!

Add Command for Running Specified Scalafix Rules

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Previously: for some completions we'd try to `backtickify` package object symbol type, which would in an error.
Now:
1. We make sure to never `backtickify` package object symbol type (the name there is always `package`)
2. We filer package object as a potential completion
fixes: https://github.com/scalameta/metals/issues/5250

bugfix: skip package objects as completions & never `backtickify` package objects

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

fixes https://github.com/scalameta/metals/issues/5156
Sometimes on nested apply we get `method.tpe == null`, for which we have fallback way to get parameters. The cases were in wrong order, since for classes (and now case classes) there is a simpler way.

fix: Arg completions for case class in nested apply

---

docs/contributors/getting-started.md

this clarifies how to  do Manual tests

website : clarify Manual tests

---

mtags/src/main/scala-3/scala/meta/internal/pc/ExtractMethodProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/ShortenedNames.scala
tests/cross/src/test/scala/tests/pc/CompletionTypeSuite.scala

Previously, if we would try to show shorter type without packages in type bounds we would get an exception since type bounds require TermType.
Now, I switched TermType to be used for Pretty type and changed to default to long name in case of errors. I haven't seen issues related to TypeType, so we should be fine there, but we will get a nice error reprot if this happens.
Fixes https://github.com/scalameta/metals/issues/5225
CC @rochala

bugfix[Scala 3]: Fix issues when shortened type is used in type bounds

---

mtags/src/main/scala-3/scala/meta/internal/pc/IndexedContext.scala

Previously, everything would break is `isAccessibleFrom` threw an exception. Now, we default to false, which is the safer option.
Connected to https://github.com/scalameta/metals/issues/5268

improvement: Make sure 'isAccessibleFrom' always succeeds

---

build.sbt
metals-bench/src/main/scala/bench/MetalsBench.scala
mtags/src/main/scala-3.3/scala/meta/internal/pc/MetalsNavigateAST.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcDefinitionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SelectionRangeProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/AmmoniteFileCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/AmmoniteIvyCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala
mtags/src/main/scala/scala/meta/internal/mtags/JavaToplevelMtags.scala
mtags/src/main/scala/scala/meta/internal/mtags/SemanticdbClasspath.scala
mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala
project/InputProperties.scala
tests/input/src/main/scala-3/example/LocalDeclarations.scala
tests/unit/src/main/scala/tests/BaseExpectSuite.scala
tests/unit/src/main/scala/tests/InputProperties.scala
tests/unit/src/test/resources/definition-scala3/example/LocalDeclarations.scala
tests/unit/src/test/resources/documentSymbol-scala3/example/LocalDeclarations.scala
tests/unit/src/test/resources/mtags-scala3/example/LocalDeclarations.scala
tests/unit/src/test/resources/semanticTokens3/example/LocalDeclarations.scala
tests/unit/src/test/resources/semanticdb-scala3/example/LocalDeclarations.scala

Since we now have unused warnings for Scala 3 I used this oportunity to clean up a bit. I also changed LocalDeclarations and turns out we broke the save-expect command, which I fixed right away.

refactor: Remove all warnings from the code

---

metals/src/main/scala/scala/meta/internal/metals/SemanticTokensProvider.scala
tests/unit/src/test/scala/tests/SemanticTokensLspSuite.scala

This pr adds semantic highlights for docstrings.
It also improves highlight in using directives - they are now highlighted everywhere, not only at the beginning of the file.

improvement: Add semantic highlight for docstring

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
tests/unit/src/test/scala/tests/FileWatcherLspSuite.scala

Previously: we did not handle properly `deletions`, which caused metals to try and read an non-existing file.
Now: we also handle `deletion` in `didChangeWatchedFiles`.

bugfix: handle delete file events notifications

---

build.sbt

It seems there is an issue where `-release` is set and using the additional compiler modules.
This essentially reverts https://github.com/scalameta/metals/pull/5177
Fixes https://github.com/scalameta/metals/issues/5280
Ideally once we run on a single Java version this is no longer needed.

chore: Fix issues with Bloop and new Java module

---

metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/PopupChoiceReset.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/clients/language/MetalsHttpClient.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/DoctorResults.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/HeadDoctor.scala

Previously: For each workspace folder a separate http server was created and a separate doctor result was produced.
Now: Only a single http server is created and information from doctors is collected into a single doctor result.
resolves: https://github.com/scalameta/metals/issues/5129

feature: create single http server and doctor result

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
project/V.scala
project/plugins.sbt

https://github.com/scalacenter/scalafix/releases/tag/v0.11.0
Closes #5121 through https://github.com/scalacenter/scalafix/commit/97b20e56b8260a429dd55f13398d8a65c76d3cb3

Scalafix 0.11.0

---

mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbSymbols.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/cross/src/main/scala/tests/BaseCompletionSuite.scala
tests/cross/src/main/scala/tests/BaseDocumentHighlightSuite.scala
tests/cross/src/main/scala/tests/BasePcRenameSuite.scala
tests/cross/src/main/scala/tests/BaseSignatureHelpSuite.scala
tests/cross/src/main/scala/tests/pc/BaseSelectionRangeSuite.scala
tests/cross/src/test/scala/tests/pc/CancelCompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionExtensionMethodSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
tests/cross/src/test/scala/tests/pc/InterruptPresentationCompilerSuite.scala
tests/mtest/src/main/scala/tests/PCSuite.scala

solves https://github.com/scalameta/metals/issues/5241
The problem was not connected to packages being in the same file, but to `extensions` being defined in package at the toplevel. This PR contains multiple fixes:
1. For `val/def/extension/...` defined inside `package`, their owner is `module class <filename>$package$`, not the package directly, so in `inverseSemanticdbSymbol`, we have to look inside `module class`es too.
2. Previously regions based on indent were working incorrectly if colon was not followed directly by a newline.
3. We were not always using correct region after escaping from indented region.

fix: Regions based on indent

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala

Previously:
If compilers were reloaded (e.g. when doing `import build`) `worksheetsDigests` would fall out of sync with dependencies in the presentation compiler.
Now: 
1. Moved `worksheetsDigests` to compilers so it's reset with presentation compilers too.
2. Still evaluated worksheets get out of sync w/ `pc`s, so if there is no `pc` for `worksheet` we ask `WorksheetProvider` to produce one if it has this worksheet evaluated in `cache`.
should fix: https://github.com/scalameta/metals/issues/5199

bugfix: keep evaluated worksheets synced with dependencies in presentation compiler

---

metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala

I get exceptions in https://github.com/scalameta/metals/blob/8283260dc275a82dea0261ad3aaec632892014b2/metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala#L87
This is with Windows + Scala 3 + a Java file
I'm a bit confused about what `TextDocument.uri` should actually contain.  It's a `String` but various code usage suggests that it should contain ideally a workspace relative path or fallback to an absolute path.
`JavaInteractiveSemanticDB` returns it as a URI (e.g. `file:///c:/blah`) so any attempt to get the workspace relative location or this `TextDocument.uri` throws an exception.
So here I've changed `JavaInteractiveSemanticDB` to return a relative path.
Am I correct in what `TextDocument.uri` should contain?  If so then this PR should solve my issue …

use relative uri for interactive java TextDocument

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala

I noticed this today while working on something in Metals that when trying to add another case into:
```scala
val codeActions = params
.getContext()
.getDiagnostics()
.asScala
.groupBy {
c<_CURSOR_>
case ScalacDiagnostic.ScalaAction(textEdit) =>
Some(textEdit)
case _ => None
}
```
I was getting the following in the logs:
```
Jun 14, 2023 2:24:02 PM scala.meta.internal.pc.completions.Completions completionPosition
SEVERE: Cannot invoke "scala.reflect.internal.Types$Type.memberType(scala.reflect.internal.Symbols$Symbol)" because "pre" is null
java.lang.NullPointerException: Cannot invoke "scala.reflect.internal.Types$Type.memberType(scala.reflect.internal.Symbols$Symbol)" because "pre" is null
at scala.meta.internal.pc.MetalsGlobal.metalsSeenFromType(MetalsGlobal.scala:946)
at …
```

fix: add in a null check after calling `stabilizedType`

---

mtags-shared/src/main/scala/scala/meta/internal/mtags/CoursierComplete.scala
mtags-shared/src/main/scala/scala/meta/internal/semver/SemVer.scala
mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/DependencyCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/MillIvyCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/SbtLibCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/ScalaCliCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionScalaCliSuite.scala

In Scala 2 completions for dependencies where sorted in wrong order

fix: Fix reversed version order in dep completions in scala 2

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/CodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/ProblemResolver.scala
metals/src/main/scala/scala/meta/internal/tvp/ClasspathSymbols.scala
metals/src/main/scala/scala/meta/internal/tvp/ScalacpCopyPaste.scala
metals/src/main/scala/scala/meta/internal/tvp/TreeViewProvider.scala

It seems that the new warnings were caused by two things:
- new false positive warnings in for comprehesnions (disabled altogether by `in anonymous function is never used`)
- changed messages for other  warnigns (updated)
- actual real unusused param in for comprehension (updated the code)

chore: Update warnings list after Scala version bump

---

mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbSymbols.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

resolves: https://github.com/scalameta/metals/issues/5341
The issue is was only present for package names, since `DescriptorParser` can deal with backticks.

bugfix: handle backticks in inverse semanticdb path

---

metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/parsing/TokenEditDistance.scala
tests/slow/src/main/scala/tests/scalacli/BaseScalaCLIActionSuite.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliActionsSuite.scala

Hi!  This PR addresses the issue where ranges for scala-cli update dependency diagnostics span the whole line instead of the dependency in question. For example below:
Only the `os-lib` dep is out of date, but the range has been expanded to the whole line (and as a result is also out of sync with the code action range).
The proposed fix is to add a new parameter to `TokenEditDistance.toRevised`, which when true will attempt to adjust the new range to match the start/end offsets in the matching token (if applicable):
Thanks!

fix: Shorten Dep Diagnostic Ranges for scala-cli

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionScala3Suite.scala

resolves: https://github.com/scalameta/metals/issues/5361

bugfix: Scala 3 adjust edit range for override completions starting w/ def

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

Emit cases for enums in Scala 3 in `ScalaTopLevelMtags`, as discussed in: https://github.com/scalameta/metals/pull/5358/files#r1239566678

bugfix: emit cases for enum

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
tests/slow/src/test/scala/tests/feature/CompletionCrossLspSuite.scala

This seems to have caused the issues in https://github.com/scalameta/metals/issues/5293 by bringing in snapshot version of the scala 3 library
Fixes https://github.com/scalameta/metals/issues/5293

bugfix: Make mtags-shared published with full scala version

---

mtags-shared/src/main/scala/scala/meta/internal/pc/MemberOrdering.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionSuffix.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

As described in https://github.com/scalameta/metals/issues/4358.
Some details:
1. I sort by adding a penalty for non-types on type position. I chose the penalty value to outweigh the `notGetter` penalty types get.
resolves: https://github.com/scalameta/metals/issues/4358

improvement: Refactor type completions to provide both type symbol and object

---

mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala
tests/unit/src/test/scala/tests/HoverLspSuite.scala

Fixes #5374.  I hope - can't run the tests locally as they're flakey on Windows

Check parent docs even when class is indexed

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
tests/slow/src/test/scala/tests/feature/SyntaxErrorLspSuite.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala

Previously: If no bsp configuration and no build tool detected metals would not work.
Now:
We fallback to:
1. generating `scala-cli` configuration if the user `scala-cli` installed (or scala in correct version).
2. otherwise we use a jvm-based `scala-cli` to start a  bsp server w/o producing a configuration.

improvement: if no build tool fallback to scala-cli

---

metals/src/main/scala/scala/meta/internal/metals/BatchedFunction.scala

Seems I am having an issue from time to time, which I can't reproduce. The debug might help out here.

improvement: Show current compilation queue when debugging flag is on

---

metals/src/main/scala/scala/meta/internal/metals/JavaBinary.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

Previously, we would just use the Java Home string as is, which might have been set wrong by the user.
It would fail if the java home was incorrect, which would make it impossible to use metals.
Now, we check if the potential java home can actually be used.
Should fix https://github.com/scalameta/metals/issues/5230

improvement: Check if possible java home is a correct path 

---

mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbSymbols.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

``` File.scala
//File.scala
package a
type Cow = Int
object Cow 
```
for object symbol we'd emit in `ScalaTopLevelMtags`:
`"a/Cow."`
which inconsistent w/ Scala 3, where the symbol is `"a/File$package/Cow."`
Previously:
`inverseSemanticdbSymbol` wasn't able to find the correct symbol
Now:
~fixed symbols emitted by `ScalaTopLevelMtags`~
added a fallback in `inverseSemanticdbSymbol` to also look for the symbol in the synthetic object ending w/ "$package".
resolves: https://github.com/scalameta/metals/issues/5366

bugfix: find correctly symbols for type companion objects

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/ScalacDiagnostic.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ActionableDiagnostic.scala
mtags-shared/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
project/V.scala

This pr bumps the version of BSP to the latest that includes the changes necessary for the new `ScalaDiagnostic` that is included in the `data` field of the Diagnostic coming over BSP. These include actions coming straight from the Scala 3 compiler.
Here are some examples using sbt 1.9.0 and the code changes in [here](https://github.com/lampepfl/dotty/pull/17561):
Supersedes https://github.com/scalameta/metals/pull/5173 since the shape is a bit different now than originally planned. Since this is the shape already baked into BSP, I'll do a follow-up in scala-cli to also update the top level `TextEdit` that it uses to instead use `ScalaDiagnostic` in `data`.

feat: account for `ScalaDiagnostic` in diagnostic data

---

metals/src/main/scala/scala/meta/internal/metals/JavaBinary.scala

Super tiny change. I just saw this in the logs today and wasn't 100%
what the boolean value printed out was meaning until I looked at the
code. This just adds a tiny change to the logs to make it explicit that
the boolean being printed out refers to whether or not the path exists.

refactor: a bit more details in logs about whether the java path exists

---

mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala

Otherwise this gets printed many times and is not very useful.

chore: Change information about finding java home to debug

---

metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
tests/unit/src/test/scala/tests/MillVersionSuite.scala

With the new version of Mill it's also a possibility to define your
version in `.config/mill-version`. This changes makes sure that we also
double-check there to pull the mill version of a project.

feat: make sure we capture `.config/mill-version` for Mill builds

---

metals/src/main/scala/scala/meta/internal/metals/BatchedFunction.scala
metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClasses.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala
tests/unit/src/test/scala/tests/BatchedFunctionSuite.scala

It was a bit much when printing every time, that would just be an empty string most of the time.

chore: Only print debug compile queue if not empty

---

metals/src/main/scala/scala/meta/internal/parsing/DocumentSymbolProvider.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/test/scala/tests/DocumentSymbolLspSuite.scala

Scripts are parsed into `MultiSource` tree, which was not handled when collecting documentSymbols.
resolves: https://github.com/scalameta/metals/issues/5411

bugfix:  `textDocument/documentSymbol` for scripts

---

metals/src/main/scala/scala/meta/internal/metals/LoggerContext.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceFolders.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/logging/MetalsLogger.scala
metals/src/main/scala/scala/meta/internal/metals/utils/LimitedFilesManager.scala
metals/src/main/scala/scala/meta/metals/MetalsLanguageServer.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/ReportContext.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/utils/LimitedFilesManager.scala
tests/unit/src/test/scala/tests/LogBackupSuite.scala
tests/unit/src/test/scala/tests/ReportsSuite.scala

When log file bigger than 3MG backup the log file.
resolves: https://github.com/scalameta/metals/issues/5395

bugfix: backup log files instead of truncating

---

build.sbt
project/V.scala

Thanks to shading added to scalameta we can now update the dependencies.
Thanks @kitbellew !

chore: Update lihaoyi's and scalameta dependencies

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ScalaCliCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/ScalaCliCompletions.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala

In Scala-Cli 1.0.1 the top wrapper changed, so dep completions stopped working

fix: Fix scala-cli dep completions for scala-cli 1.0.1

---

mtags-shared/src/main/scala/scala/meta/internal/mtags/CoursierComplete.scala
mtags-shared/src/main/scala/scala/meta/internal/semver/SemVer.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/MillIvyCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/SbtLibCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionMillIvySuite.scala
tests/cross/src/test/scala/tests/pc/CompletionScalaCliSuite.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliActionsSuite.scala

Scala CLI and mill support syntax <org>::<name>::<version> for scala native and scala js dependencies. We can default to it in Scala CLI and maybe in mill too?
Also fixes version sorting for  `cats-core` , since there was a version `1.0.0-MF`, which was causing an exception

improvement: Dependency version completions for scala native 

---

mtags/src/main/scala/scala/meta/internal/metals/ScaladocIndexer.scala
mtags/src/main/scala/scala/meta/internal/metals/docstrings/MarkdownGenerator.scala
mtags/src/main/scala/scala/meta/internal/metals/docstrings/ScaladocParser.scala
tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala
tests/unit/src/test/scala/tests/HoverLspSuite.scala
tests/unit/src/test/scala/tests/JavadocSuite.scala

Previously, parameters in markdown generated from scaladoc were in random order

fix: Correctly sort params in markdown

---

metals/src/main/scala/scala/meta/internal/metals/MtagsResolver.scala

It seems currently it will span the users and it's not really useful information.

refactor: Reduce the level when mtags was found to debug

---

mtags-shared/src/main/scala/scala/meta/internal/metals/ReportContext.scala
mtags-shared/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
mtags-shared/src/main/scala/scala/meta/internal/pc/CompilerAccess.scala
mtags-shared/src/main/scala/scala/meta/internal/pc/CompilerThrowable.scala

1. added printing stacktrace
2. added offset/range markers to printed text
3. make` trimStacktrace` include a line from `ScalaPresentationCompiler`

Improvement: compiler access error reporting

---

mtags/src/main/scala-2/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcDefinitionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala

connected to https://github.com/scalameta/metals/issues/5438
In Scala 2.13.12 `namePos` method is added for `NamedTree`, which shadowed our `namePos` extension method

refactor: Change namePos to namePosition

---

metals/src/main/scala/scala/meta/internal/metals/BloopDir.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/test/scala/tests/ResetWorkspaceLspSuite.scala

Now user is asked for confirmation before clearing .bloop directory. 
Adds additional checks for non-existing files, since it used to fail both on `.toList` and `delete`. 
Also, the `ResetWorkspaceLspSuite` was flaky before, now it should work correctly

fix: Make ResetWorkspace more stable

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/mtags-auto-release.yml
bin/merged_prs.scala
bin/test-release.sh
build.sbt
website/blog/2023-07-19-silver.md

Let me know if I should improve  or add something!
@adpi2 do you want to add a section on debugging? I updated to latest Bloop with the latest scala-debug-adapter. I am also thing of doing another release with a couple of fixes, so I could include next version if you want to release it?

docs: Add release notes for Metals 1.0.0

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/JavaBinary.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

If `java_home` in `bsp/sbt.json` config is outdated restart sbt server on connect.
resolves: https://github.com/scalameta/metals/issues/5313

improvement: restart sbt after java home change

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

NamedArgParam is based on actual symbol, in the following case the valid symbol `param` and correspoding NamedArgParam(`param`) were clashing
```
def foo(param: Int): Int = {
foo(para@@)
}
```

Scala2 - deduplicate NamedArgParams with Def params

---

metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/Tables.scala

When running unit tests, connections with database were not correctly closed, which resulted in memory leak and not killing all threads. First, database connection was closed correctly, but Indexer shedules removal of unused jars from cache after 2 seconds, which was creating new database and never closing it.

fix: Fix memory leak in tests

---

mtags-java/src/main/scala/scala/meta/internal/pc/JavaCompletionProvider.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaKeyword.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaLabels.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaPresentationCompiler.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaScopeVisitor.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaTypeAnalyzer.scala
tests/javapc/src/main/scala/tests/pc/BaseJavaCompletionSuite.scala
tests/javapc/src/test/scala/pc/CompletionIdentifierSuite.scala
tests/javapc/src/test/scala/pc/CompletionKeywordSuite.scala
tests/javapc/src/test/scala/pc/CompletionMemberSelectSuite.scala

Finally java completion feature is available for metals. It's based on Java Compiler API as [Java Hover](https://github.com/scalameta/metals/pull/5024) feature.

Add java completion

---

tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala
tests/unit/src/test/scala/tests/CodeLensLspSuite.scala
tests/unit/src/test/scala/tests/DebugDiscoverySuite.scala
tests/unit/src/test/scala/tests/DebugProtocolSuite.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala
tests/unit/src/test/scala/tests/FindTextInDependencyJarsSuite.scala
tests/unit/src/test/scala/tests/ImplementationLspSuite.scala
tests/unit/src/test/scala/tests/NewProjectLspSuite.scala
tests/unit/src/test/scala/tests/QuickBuildSuite.scala

It seems with newer JDK version there is a special additional check that fails with the jar of scalactic at the previous version.
Let's see if updating it helps.
Related to https://github.com/openjdk/jdk/commit/fff7e1ad00be07810bf948b8a6f94e83c435fa1f

bugfix: Bump scalatest to fix zip issue

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/NamedArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

1. in Scala 3 added fallback for arg completions for overloaded methods (previously no arg completion would be visible):
- collects methods w/ matching name
- uses a heuristic to determine if the provided arguments match the method's signature
2. in Scala 2:
- handle `OverloadedType`
- in fallback collect args from all matching overloaded methods. We use a heuristic do check if the method matches, it is less accurate than the one used for Scala 3.

improvement: show args completions for all matching overloaded methods

---

mtags-java/src/main/scala/scala/meta/internal/pc/JavaCompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/NamedArgCompletions.scala
tests/javapc/src/main/scala/tests/pc/BaseJavaCompletionSuite.scala
tests/javapc/src/test/scala/pc/CompletionMemberSelectSuite.scala

Previously, if there was anything following the place you were trying to get a completion in, you would not get any suggestions since the following names would be take into account. Now, we add `;` after anything you are trying to complete if the next symbol is a whitespace to separate the current completion from the following statements.
I also noticed that we don't set proper snippet format for the items, so I added that.

improvement: Automatically add colon to get better completions for Java

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaCompletionProvider.scala
tests/unit/src/test/scala/tests/debug/CompletionDapSuite.scala

Previously, when trying completions in Java files these would hang and not return anything. Now, we complete correctly as in Scala files.
This is not yet super useful, but we should get also expression evaluation for Java files soon.

improvement: Make debug completions work for Java files

---

mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags-java/src/main/scala/scala/meta/internal/pc/JavaCompletionProvider.scala
tests/javapc/src/main/scala/tests/pc/BaseJavaCompletionSuite.scala
tests/javapc/src/test/scala/pc/CompletionMemberSelectSuite.scala

Previously, Java completions would show keywords even in select position, which would always be invalid.
Now, we only show them on scope completions and also filter out constructors

bugfix: Don't show keywords or constructors on select

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Connected to https://github.com/scalameta/metals/issues/5182
Completions with `CURSOR` could be seen not only in `for-comprehension` with `=` lines, but also is more random places and issues with them are hard to reproduce. I think it's better to not show them at all

fix: Don't show completions ending with CURSOR

---

mtags-java/src/main/scala/scala/meta/internal/pc/JavaCompletionProvider.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaMetalsGlobal.scala
tests/javapc/src/main/scala/tests/pc/BaseJavaCompletionSuite.scala
tests/javapc/src/test/scala/pc/CompletionMemberSelectSuite.scala

Previously, we would show all members irrelevant if they were actually declared in the class or parents such as Object. Now, we show direct members first.
Also, changed the compielr to not report errors while typing.

improvement: Show direct members first

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaMtags.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala
tests/input/src/main/scala-3/example/TypeEnum.scala
tests/slow/src/test/scala/tests/feature/DefinitionCrossLspSuite.scala
tests/unit/src/test/resources/definition-scala3/example/TypeEnum.scala
tests/unit/src/test/resources/documentSymbol-scala3/example/TypeEnum.scala
tests/unit/src/test/resources/expect/toplevels-scala3.expect
tests/unit/src/test/resources/mtags-scala3/example/TypeEnum.scala
tests/unit/src/test/resources/semanticTokens3/example/TypeEnum.scala
tests/unit/src/test/resources/semanticdb-scala3/example/TypeEnum.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

1. emit type and params for enum cases when it has some parameters' list in `ScalaMtags`
2. emit type and and val params for enum cases when it has some parameters' list in `ScalaTopLevelMtags`
3. when finding a correct file in symbol index fallback to companion class as alternative
resolves: https://github.com/scalameta/metals/issues/5494

bugfix: emit type for enum cases when needed

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/debug/ClientConfigurationAdapter.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
tests/unit/src/test/scala/tests/debug/CompletionDapSuite.scala

Previously, we set the wrong start of the expression since we actually need to calculate that when insertText is used. Now, we calculate it based on the current identifier.
We should use TextEdit in the future, which should work better. I also realized that start actually needs to take into account if the client starts at 1 or 0.

bugfix: Fix issues with select in debugger completions

---

docs/contributors/releasing.md

Trying to formalize the versioning strategy, opinions? Should we add something more? I think we can go with a Metal per release as it's more fun :D

docs: Add info about the versioning strategy

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/DoctorExplanation.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/ProblemResolver.scala
tests/slow/src/test/scala/tests/feature/FileDecoderProviderLspSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala
tests/unit/src/main/scala/tests/BuildServerInitializer.scala

Previously, because sbt doesn't implement javacOptions endpoint we would not provide support for Java files. Now, we fallback to the information provided from the Scala build target, which should be enough for the current features.

bugfix: Support Java when using sbt server via BSP

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionSuffix.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/ShortenedNames.scala
tests/cross/src/main/scala/tests/BasePCSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala

This PR contains the following changes:
1. better printing of type params when there is a bracket suffix. We also print the bounds now and keep the original type param names.
2. we don't print the type params coming from bracket suffix in some situations, e.g. for types, where it is printed anyway
3. add completion suffix to `Scope` completions

improvement: print better bracket suffix in label, Scala 3 completions

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Buffers.scala
metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeProvider.scala
metals/src/main/scala/scala/meta/internal/parsing/JavaTokens.scala
metals/src/main/scala/scala/meta/internal/parsing/TokenEditDistance.scala
tests/unit/src/test/scala/tests/DiagnosticsLspSuite.scala
tests/unit/src/test/scala/tests/parsing/JavaEditDistanceSuite.scala

Previously, we would log tokenizer errors as stale. Now, we only report stale errors if not match could be found, but still would be tokenized.
I added a more explicit return type when creating EditDistance, it's not neccessary to change it everywhere right now I think.

bugfix: Don't report tokenizer errors as stale

---

metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala

I had it one for the last half a year and it's been pretty stable. Also it seems most editors require you to turn it on separately, co this only causes additional confusion.
Related https://github.com/scalameta/metals-vscode/pull/1416

improvement: Set semantic highlighting to true by default

---

tests/unit/src/test/scala/tests/FindTextInDependencyJarsSuite.scala

We should match on java version exactly here, should safe us from problems in the future.

chore: Fix lines numbers for CI testing

---

mtags/src/main/scala-2/scala/meta/internal/pc/HoverProvider.scala
tests/cross/src/test/scala/tests/hover/HoverDefnSuite.scala
tests/cross/src/test/scala/tests/hover/HoverNegativeSuite.scala

Previously there was no hover shown on class/object/type definition.

feat: Add hover on class,object,type def in Scala 2

---

.github/workflows/mtags-auto-release.yml

Started getting errors that main is not recognized despite the fact that `fetch-depth: 0` should address that. As we only need it in the hook, this should be fine.

chore: Don't try formatting in auto releases

---

metals/src/main/scala/scala/meta/internal/metals/MtagsResolver.scala
project/V.scala

If everything goes right this should be the last RC version we should release Metals for.

chore: Add support for Scala 3.3.1-RC5

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/CompletionLspSuite.scala

Symbols in compiler have encoded names (eg. `$at$at` instead of `@@`) so we need to encode semanticdb symbols before matching on name.
Fixes https://github.com/scalameta/metals/issues/5469 and https://github.com/scalameta/metals/issues/5065

fix: InverseSemanticdbSymbols for symbolic names

---

metals/src/main/scala/scala/meta/internal/metals/SemanticTokensProvider.scala
tests/unit/src/test/scala/tests/SemanticTokensLspSuite.scala

closes https://github.com/scalameta/metals/issues/5553

fix: Semantic tokens misaligned in triple quote s-string

---

metals/src/main/scala/scala/meta/internal/metals/logging/MetalsLogger.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/ReportContext.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/TimeFormatter.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/utils/LimitedFilesManager.scala
tests/unit/src/test/scala/tests/LogBackupSuite.scala
tests/unit/src/test/scala/tests/ReportsSuite.scala

Previously, reports have had only timestamp in milliseconds, which didn't tell the user anything about when the report was created.

improvement: Add date and time to reports and backup log files

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/ServerLivenessMonitor.scala
tests/unit/src/test/scala/tests/ServerLivenessMonitorLspSuite.scala
tests/unit/src/test/scala/tests/ServerLivenessMonitorSuite.scala

Just after metals comes out of idle state, we might have new outgoing messages but no responses to those messages yet.
This PR makes sure we don't report this as unresponsive build server.

bugfix: don't show build server not responding error just after coming out of idle

---

tests/unit/src/main/scala/tests/TestingServer.scala

It seems that while listing files we are getting an exception, because one of the files was temporary. Since we should get IOException there and just are interested about RuntimeException this is fine to wrap in try.
The stack trace in question:
```
[error] ==> X tests.sbt.SbtStepDapSuite.step-into-scala-lib-virtualdoc  28.064s java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home/runner/work/metals/metals/tests/slow/target/e2e/sbt-debug-step/step-into-scala-lib-virtualdoc/target/scala-2.13/test-classes.bak
[error]     at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87)
[error]     at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103)
[error]     at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1855) …
```

chore: Try to fix issues with sbt integration tests

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala
tests/cross/src/test/scala/tests/pc/PcRenameSuite.scala

We don't want rename/highlight and other PC features to include occurrences in for-comp

fix: Don't collect map, flatMap, withFilter in for-comprehension

---

metals/src/main/scala/scala/meta/internal/bsp/BspConfigGenerator.scala
metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/bsp/ScalaCliBspScope.scala
metals/src/main/scala/scala/meta/internal/builds/BuildServerProvider.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
metals/src/main/scala/scala/meta/internal/builds/ScalaCliBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala
tests/unit/src/main/scala/tests/TestingClient.scala

Sometimes users compile a single file using `scala-cli`, which as a side effect creates a `bsp` config for a single file.
Now when the user opens a file, that is not in the `scala-cli` build server scope (according to config) we asks the user if the want to amend that configuration and restart build server.
connected to: https://github.com/scalameta/metals/issues/4741

improvement: offer amend to handle single file scala-cli config on new file

---

metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
tests/slow/src/test/scala/tests/feature/CrossDiagnosticsSuite.scala

Previously, the default Scala3 dialect would assume kind projector syntax, but that is only true if the proper setting is on.
Now, we only turn it on if defined in scalac options to be on a safe side. There is no current features that depend on it, but it's probably better to have the right trees.
Fixes https://github.com/scalameta/metals/issues/5573

bugfix: Don't enable * kind project syntax by default

---

metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/parsing/JavaFoldingRangeExtractor.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaCompletionProvider.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaHoverProvider.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaMetalsGlobal.scala
tests/unit/src/test/scala/tests/JavaInteractiveSemanticdbSuite.scala

Should be faster and easier to test/debug and brings it into line with using same JDK compiler as other Java handling code.
Because this runs in process (instead of running an external javac process), Metals needs to start with the same options as the SCIP plugin so even more `-add-exports`...
Currently has...
```
--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED
--add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
```
needs also...
```
--add-exports jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
```
Is there a process for notifying the client maintainers?  Or shall I just raise a PR in vscode-metals and assume they will check there?
Also - …

create java semanticdb info using JDK instead of javac CLI

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ScaladocCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionScaladocSuite.scala

Previously we were providing docstring template even if next def was not directly after comment
closes https://github.com/scalameta/metals/issues/5577

bugfix: Incorrect docstring completions

---

metals/src/main/scala/scala/meta/internal/metals/Trace.scala

This is a bug in ProjectDirectories, which seems to be super hard to fix, so instead we can special case it. This is not super important to use that directory anyway, we fall back to local workspace.
Fixes https://github.com/scalameta/metals/issues/5590

bugfix: Don't use cache directory with `null` in it's path

---

mtags-shared/src/main/scala/scala/meta/internal/pc/AutoImportPosition.scala
tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/5567

bugfix: skip empty lines when calculating indent for auto import

---

.github/workflows/release.yml

I realised we were not releasing fully :sweat: 
Will go ahead and merge quickly as it's needed for us.

bugfix: Release mtagsShared together with mtags when running single version release

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClasses.scala
project/V.scala
tests/slow/src/test/scala/tests/mill/MillServerCodeLensSuite.scala
tests/unit/src/main/scala/tests/BaseCodeLensLspSuite.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala
tests/unit/src/main/scala/tests/BuildServerLayout.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/CodeLensLspSuite.scala

Previously, we would show test code lense for Mill BSP, which did not work and not show run lenses which could work with newer Mill versions. Now, we only show run code lense, which can change id debug is supported by mill or we implement an alternative way of running tests.

bugfix: Allow run in Mill BSP and remove non working test lenses

---

metals/src/main/scala/scala/meta/internal/builds/BloopInstall.scala

Just opening a draft PR, this would've helped me out a bunch when I accidentally had VSCode Notifications silenced (which is a questionable UI decision on VSCode's part but 🤷‍♀️)
Relatedly, it may be worth mentioning in Troubleshooting how easy it is to silence notifications which are needed by Metals for importing projects. If you click the crossed-out bell icon as shown in this screenshot, the prompts are silenced:

improvement: log awaiting user response in BloopInstall

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ServerLivenessMonitor.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala

Start liveness monitor only for main bsp connection.
Add restart bsp server to not responsive bsp notifications options.

improvement: start liveness monitor only for main bsp connection

---

tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala

I think the [flakiness of this test](https://github.com/scalameta/metals/actions/runs/6159488594/job/16714404940?pr=5640#step:4:6098) might be connected to the fact that the checked message is added through `status bar`, which won't show the message right away when something is already there. So I've removed that part from test. Without this part it still tests the functionality correctly.

test: `single-file-config`

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala
tests/unit/src/main/scala/tests/FileLayout.scala
tests/unit/src/test/scala/tests/codeactions/ExtractRenameMemberLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/5632

bugfix: extract member with associated comments

---

build.sbt

This release fixes slow performance on Windows for listing deeply nested directories. See https://github.com/swoval/swoval/issues/161. The user confirmed that the performance goes from about 14 minutes to 10 seconds to initialize file watching in their repo after this change.

Bump swoval to v2.1.11

---

mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/Scala3DocumentHighlightSuite.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala
tests/cross/src/test/scala/tests/pc/PcDefinitionSuite.scala

Workaround for missing span in:
```Demo.scala
class MyIntOut(val value: Int)
object MyIntOut:
extension (i: MyIntOut) def <<uneven>> = i.value % 2 == 1
val a = MyIntOut(1).un@@even
```
to provide correct:
1. semantic highlighting,
2. highlight,
3. go to definition.
https://github.com/scalameta/metals/issues/5630

bugfix: workaround for missing span in reference to an extension method defined in the companion object

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
project/SemanticDbSupport.scala
project/V.scala
sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala
sbt-metals/src/sbt-test/sbt-metals/semanticdb/build.sbt
tests/unit/src/main/scala/tests/QuickBuild.scala
tests/unit/src/test/scala/tests/FormattingLspSuite.scala

Previously, we would fail if our version of semanticdb was not supported for a specific scala version. Now, we calculate last supported version for each scala version when compiling.
Potentially this means we could get a new semanticdb version automatically, but that should not be an issue as semanticdb is well tested in scalameta itself
This is needed for the sbt-metals plugin

improvement: Automatically calculate last supported versions for semanticdb

---

build.sbt
project/Scala3NightlyVersions.scala
project/SemanticDbSupport.scala
project/Version.scala

PReviously, we were using the latest published scalameta version, which was caused by me setting first latest semanticdb version (that is not an issue), but then I also added the same scalameta version in order to not have potential mismatches between the two. This caused a breaking change in scalameta internal code to break metals CI. Now, we set the maximum version to be V.scalameta

bugfix: Make sure we are using latest known scalameta version

---

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

resolves: https://github.com/scalameta/metals/issues/5670
Still having "(" won't work but that needs an upstream fix. I still left "(" in special characters since now it just incorrectly ignores the test and before it would fail on creating a regex pattern.

bugfix: escape special chars in test names

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala
metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/Icons.scala
metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
metals/src/main/scala/scala/meta/internal/metals/ServerLivenessMonitor.scala
metals/src/main/scala/scala/meta/internal/metals/StatusBarConfig.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/clients/language/ConfiguredLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/clients/language/MetalsLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/test/scala/tests/ServerLivenessMonitorLspSuite.scala
tests/unit/src/test/scala/tests/ServerLivenessMonitorSuite.scala

Previously a message request would pop up when the build sever was not responding. Now we make this into a status.
Changes in the client API:
- Adds `bspStatusBarProvider` field to initialisation params, same as `statusBarProvider` has possibile values "on", "off", "log-message", "show-message". Default being "show-message".
- Adds `level` field to `MetalsStatusParams`, possible values "info", "warn", "error" (can be mapped by client to e.g. color)
- Adds `commandTooltip` field to `MetalsStatusParams`.
BSP status in VSCode:
- connected
- no response
- default behaviour if the client doesn't support bsp status

improvement: move bsp responsiveness into status

---

mtags/src/main/scala-3/scala/meta/internal/pc/IndexedContext.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/5682

bugfix: add `moduleClass` imported symbols in `IndexedContext`

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

Previously: resolving main class or test suite was not properly adjusted for multiple workspace folders, the future failed with a `ClassNotFoundException` when the class was found in a workspace folder.
Now: We only fail the future if for *all* workspace folder the class is not found.
resolves: https://github.com/scalameta/metals/issues/5512

bugfix: fix resolving main class/ test suite for multi-root projects

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala

This seems to happen consistently in our Scala CLI tests, since it first needs to resolve a bunch of things.

bugfix: Wait longer to connect to build tools other than Bloop

---

tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala

Connected to: https://github.com/scalameta/metals/actions/runs/6353179361/job/17257344448?pr=5696#step:4:3174
It only fails sometimes, since showing bsp status as request messages doesn't always work.

test: fix `ScalaCliSuite.connecting-scalacli`

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceFolders.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/metals/MetalsLanguageServer.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/ReportContext.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/utils/LimitedFilesManager.scala
tests/slow/src/main/scala/tests/scalacli/BaseScalaCliSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/TreeViewLspSuite.scala
tests/unit/src/test/scala/tests/WorkspaceFoldersSuite.scala
tests/unit/src/test/scala/tests/testProvider/TestSuitesProviderSuite.scala

Previously: We had no distinction between workspace folders that are `Scala` projects and those that aren't.
Now: We create `MetalsLspService` only for `Scala` projects.
I consider something to be a Scala (metals) project if there is:
1. `.metals` folder
2. a toplevel scala+ (`.scala`, `.sc`, `.sbt`) file
3. a scala+ file in `.\src`, `.\it` , `.\test`, `.\*\src`, `.\*\it` , `.\*\test`
4. a scala+ file that belongs to that workspace folder was opened
resolves: https://github.com/scalameta/metals/issues/5558

improvement: don't create service for folders w/ non-Scala projects

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

For multiline strings, we highlight the entire line, so we need to adjust the length by removing additional indent

bugfix: Semantic tokens for  multiline strings in Scala3 worksheets

---

project/V.scala

The newest snapshot seems the only one that support all the possible Scala versions

chore: Update ammonite to the newest snaphot

---

mtags-shared/src/main/scala/scala/meta/internal/pc/HoverMarkup.scala

resolves: https://github.com/scalameta/metals/issues/5679

improvement: trim hover body

---

metals/src/main/scala/scala/meta/internal/builds/BSPErrorHandler.scala
metals/src/main/scala/scala/meta/internal/metals/DismissedNotifications.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
tests/unit/src/test/scala/tests/BspErrorHandlerSuite.scala

Add possibility to stop showing bsp errors.

improvement: add do not show bsp errors option

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/ServerLivenessMonitor.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/test/scala/tests/ServerLivenessMonitorLspSuite.scala
tests/unit/src/test/scala/tests/ServerLivenessMonitorSuite.scala

Previously:
after a no response error, if the build server started responding, we'd have to wait a minute for the status to get fix.
Now: the moment when we get a message from build server we fix the status.

improvement: show bsp as connected after the first message from build server

---

tests/slow/src/test/scala/tests/mill/MillServerCodeLensSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala

My guess is that the test failed because it takes a while for the build server to connect. Let's see if this helps.

bugfix: Try to fix Mill flaky test

---

metals/src/main/scala/scala/meta/internal/bsp/BspConfigGenerator.scala
metals/src/main/scala/scala/meta/internal/builds/BloopInstall.scala
metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala
metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfigurationSync.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceFolders.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/clients/language/ConfiguredLanguageClient.scala

resolves: https://github.com/scalameta/metals/issues/5699
Previously:
- common config for all workspace folders
- for initial sync we used `workspace/configuration` if supported by the client
- next updates done `DidChangeConfiguration`
Now:
- a config for each workspace folder
- for initial sync `workspace/configuration` if supported by the client
- next updates triggered by `DidChangeConfiguration`
- `workspace/configuration` used if supported
- info from `DidChangeConfiguration` notification used otherwise

User configuration per workspace folder

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala

It doesn't reproduce in tests, but for case classes/objects defined inside an object we get stale symbols and filter out the not-stale ones

bugfix: exhaustive match on stale symbols

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfigurationSync.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceFolders.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala

Previously: metals would hang on `initialize`. We used `MetalsLspService .onUserConfigUpdate` for initial user config sync (before calling initialise), which in some cases could wait for `buildServerPromise`. 
It work before https://github.com/scalameta/metals/pull/5709, since `didChangeConfiguration` would always execute first, so the initial sync detected no changes (thus never waited for the build server promise). After that PR, on `didChangeConfiguration` we make a call to the client, so it takes longer and the initial sync executes first.

bugfix: hang on `initialize`

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala

resolves: https://github.com/scalameta/metals/issues/5712

bugfix: match completions for type aliases scala 3

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/LoggerContext.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/DoctorResults.scala
metals/src/main/scala/scala/meta/internal/metals/logging/MetalsLogger.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
metals/src/main/scala/scala/meta/metals/MetalsLanguageServer.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags-shared/src/main/scala/scala/meta/internal/metals/ReportContext.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/utils/LimitedFilesManager.scala
mtags-shared/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
mtags-shared/src/main/scala/scala/meta/internal/pc/CompilerAccess.scala
mtags/src/main/scala-2/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompilerSearchVisitor.scala
mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/main/scala/tests/TreeUtils.scala
tests/unit/src/test/scala/tests/LogBackupSuite.scala
tests/unit/src/test/scala/tests/ReportsSuite.scala

resolves: https://github.com/scalameta/metals/issues/5672

Add error reports info to metals doctor

---

metals/src/main/scala/scala/meta/internal/metals/MtagsResolver.scala

Previously, we would log every time a presentation compiler was used.

improvement: Only log messages on resolution

---

README.md
docs/acknowledgements/development.md
website/sidebars.json

This came from a conversation offline with @tgodzik about the current company efforts towards maintaining Metals. This makes a couple changes:
- Tries to accurately show what companies are currently backing Metals
- Moves the acknowledgements and current team to the website instead of the readme. Arguably a lot of people may not ever see the readme, and this way this information can be more widely accessed by people viewing the website, not just the code.

docs: Move acknowledgements/team to the website

---

metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalametaCommonEnrichments.scala

Previously, we would assume that any file that we want to calculate InteractiveSemanticdb for exists on the filesystem, which is not true. For example renamed files if renamed from terminal will stick in the editor and cause exceptions to be throw. Now, we also try to read it from buffers and from filesystem as a fallback if it exists on the filesystem.

bugfix: Don't read file for InteractiveSemanticdbdb if it doesn't exist

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

resolves: https://github.com/scalameta/metals/issues/5750
The config carried by `didChangeConfiguration` is no longer used by metals (only as fallback), the notification is only used as information for metals to update the config, which is done using the `workspace/configuration` request ([more](https://github.com/scalameta/metals/pull/5709)).  In https://github.com/scalameta/metals/issues/5750 the response to `workspace/configuration` comes after the request for semantic tokens, so the `default` config instead of a user specified one is used.
I just wonder if this can happen for other things aside for semantic tokens too (`initialized` waits for config sync to succeed). I considered lifting `userConfig` to `Future` in all places but that seems lika a bit of a problematic refactor. …

bugfix: add user config promise

---

metals/src/main/scala/scala/meta/internal/builds/BuildToolSelector.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

If we get to the state that selected build tool is no longer available, Metals would crash. This happend in `MetalsLspService.buildTool` if `BuildToolSelector.checkForChosenBuildTool` returned Future(None).
connected to https://github.com/scalameta/metals/issues/5761

bugfix: Future filter error during connecting to build server

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/Signatures.scala

Previously, we would use PrettyType to get any string output we wanted, however that broke if the type w read by the compiler. Now, we use standard compiler types to achive the same.
fixes https://github.com/scalameta/metals/issues/5756 and https://github.com/scalameta/metals/issues/5755

bugfix: Remove PrettyType which might often fail in the compiler

---

metals/src/main/scala/scala/meta/internal/metals/ScalacDiagnostic.scala
tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala

This fixes the bug where the user has `-explain` `scalac` flag set
and executing Code Actions on a missing symbol did not offer to import
the symbol, due to extra text the regex previously failed to parse.

bugfix: fix SymbolNotFound regex

---

metals/src/main/scala/scala/meta/internal/bsp/BspConfigGenerator.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala

Bugfix for moving the generated bsp configuration from custom project root to workspace root. The tests were only for `bloop`.

bugfix: move bsp config for detected project root

---

metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
tests/slow/src/test/scala/tests/feature/Scala211ActionsLspSuite.scala

Previously, we would use the latest scalfix version by default, which doesn't support Scala 2.11 by default. Now, we fall back to the latest version that supported it.

bugfix: Add back unintentionally removed support for 2.11.x

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargetInfo.scala
tests/slow/src/test/scala/tests/feature/FileDecoderProviderLspSuite.scala

So I noticed that when using the "Show build target info" feature while
using scala-cli it would show individual files under the "Source
Directories". I know it's a bit of a nit, but I thought it might be
nicer to rename this to "Sources" and then do a better job at indicating
which are files, which are directories, and which ones don't exist. If
we agree this is better I can fix the related tests as well.
_Before_
_After_

refactor: differentiate between files and directories in sources

---

metals/src/main/scala/scala/meta/internal/builds/NewProjectProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/newScalaFile/NewFileProvider.scala
tests/unit/src/test/scala/tests/NewFileLspSuite.scala

In case no `directoryUri` provided and no current `focusedFile` ask user where to create new file. Previously `workspace` was used as fallback. In preparation for single file support we can't depend on that strategy anymore. Connected to: https://github.com/scalameta/metals/pull/5531.

improvement: make new file independent of workspace root

---

.github/workflows/ci.yml
.github/workflows/release.yml

Previously, when specifying job concurrency we would only do it for branches so that jobs on main branch are not cancelled, which would happen (github was not queueing jobs). It seems that now it will properly queue the jobs so we simplify it all similar to how Scala CLI does things

refactor: Use default concurrency queue

---

metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala

build progress from sbt is not being reported. Its notification has a `"compile-progress"` datakind field, but is formatted the same as `"bloop-progress"` except for one thing, the `"current"` field is actually the percentage, so we use `100` for the total.

report sbt's build progress

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala

For methods with multiple parameter lists and default args, the tree looks like this:
`Block(List(val x&1, val x&2, ...), Apply(<<method>>, List(x&1, x&2, ...)))`, so we need to extract this `Apply`.
Also, if rhs of named argument is complex, the position is often incorrect, so we need to use `include` for `namedArgCache`
fixes to https://github.com/scalameta/metals/issues/5779

bugfix: Document highlight on named arguments

---

metals/src/main/scala/scala/meta/internal/decorations/SyntheticsDecorationProvider.scala
metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala

Previously, we would try to remove semanticdb files from indexes while we used the actual source file. Now, we properly remove files in all indexes and also from interactive semanticdb.
Related to https://github.com/scalameta/metals/issues/5748

bugfix: Remove old semanticdb files when not needed

---

metals/src/main/scala/scala/meta/internal/metals/Directories.scala
metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
tests/unit/src/test/scala/tests/FormattingLspSuite.scala

Scalafmt needs to habe a config file to run formatting. Previously, metals required it to be in the main workspace directory or to be defined via configuration. Now, we will also try to use the default scalafmt config from Scala CLI

improvement: Try to use scala CLI format if it exists

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionPos.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Back-backport the changes in dotty which will match the completion behaviour for Scala 2 and Scala 3. Related PR https://github.com/lampepfl/dotty/pull/18803

Completions should prepend instead of replace to match Scala 2 behaviour

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala

We shouldn't show case completions for tuple type if query doesn't match label. 
Also, sometimes label contained `x$1` symbol (eg. `(x$1: (Int, Int)) @unchecked scala`, which we don't want to show to the user.
I think the simplest way to detect it is just by looking if label contains `x$1`
connected to the issue found in https://github.com/scalameta/metals/pull/5196#discussion_r1203629508

bugfix: Case completions for tuple type

---

build.sbt
mtags-shared/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala

Change required to work with `-Yexplicit-nulls` according to https://github.com/lampepfl/dotty/issues/18775
This is a blocker for adding `-Yexpliict-nulls` in the presentation compiler module that will guarantee soundness. https://github.com/lampepfl/dotty/pull/18776
This also may require a minor release.

Change method to work with explicit nulls

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcDocumentHighlightProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcInlineValueProviderImpl.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcRenameProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcSemanticTokensProvider.scala
tests/cross/src/test/scala/tests/pc/PcRenameSuite.scala
tests/input/src/main/scala-3/example/EndMarker.scala
tests/unit/src/test/resources/definition-scala3/example/EndMarker.scala
tests/unit/src/test/resources/documentSymbol-scala3/example/EndMarker.scala
tests/unit/src/test/resources/expect/toplevels-scala3.expect
tests/unit/src/test/resources/mtags-scala3/example/EndMarker.scala
tests/unit/src/test/resources/semanticTokens3/example/EndMarker.scala
tests/unit/src/test/resources/semanticdb-scala3/example/EndMarker.scala
tests/unit/src/test/resources/toplevel-with-inner-scala3/example/EndMarker.scala

resolves: https://github.com/scalameta/metals/issues/5797

bugfix: rename end marker for local definitions

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/NamedArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

If we have
```scala
def foo(aaa: Int, bbb: Int, ccc: Int) = ???
val x = foo(
bbb = 123,
ccc = 123,
@@
)
```
we want to get `aaa` completion

bugfix: Completions for named args in wrong order

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
tests/slow/src/test/scala/tests/mill/MillServerSuite.scala

It was there already for bloop and sbt, but not for mill. Because of this, presentation compiler didn't see symbols from workspace.
fixes https://github.com/scalameta/metals/issues/5774

bugfix: Add output classes directory to classpath for PC

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargetInfo.scala
metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala

mill-build build target display name ends with `/` and build target info for it was not displayed.

bugfix: BuildTargetInfo for mill-build

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

Fixes https://github.com/scalameta/metals/issues/5843

bugfix: Don't show synthetics if not an inline decorations provider

---

metals/src/main/scala/scala/meta/internal/tvp/ClasspathTreeView.scala
metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala
tests/unit/src/test/scala/tests/TreeViewLspSuite.scala

Previously, only some nodes would have their icons set, which would result with some having folder icons added by VS Code but not all. Now, we set icons for each node manually.
The only problem I have is with packages, which doesn't really have a great icon anywhere. symbol-package is the same as symbol-object, which is too similar. So I decided to go with folder, which seems the next best thing.

improvement: Set icons properly for all parts of tree view

---

mtags/src/main/scala-3/scala/meta/internal/pc/PcSemanticTokensProvider.scala

It was a leftover after merging PC decorations and could cause a slowdown.

chore: remove leftover distinct

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala
tests/cross/src/test/scala/tests/tokens/SemanticTokensSuite.scala

Anonymous function parameters with type annotation have incorrect name position on definition, so we need to handle them separately.
Closes https://github.com/scalameta/metals/issues/5840 and https://github.com/scalameta/metals/issues/5837

bugfix: Fix PcCollector for Scala 2 in anon-fun parameters

---

metals/src/main/scala/scala/meta/internal/metals/JavaBinary.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala

This started shwoing up for me, but can't reproduce it.
I also removed debug about missing java home, since it shows a lot and doesn't help. We already show the candidates in the doctor if no src zip was found.

improvement: Add debug information when no references are shown

---

metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClassesFinder.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
tests/unit/src/test/scala/tests/DebugDiscoverySuite.scala
tests/unit/src/test/scala/tests/DebugProtocolSuite.scala

Previously, we would not show the errors coming from debug discovery and no errors would be forwarded to the client.
Now, we do those two things:
- we no longer hide the discovery errors, but in case no folder contained valid run configuration, we try to show the most relevant error
- instead of throwing a random exception we use LSP build-in one, which is sent back to the client properly and will be displayed
Closes scalameta/metals-vscode#1438

 improvement: Forward DAP errors properly to the client

---

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala

Previously, we would use the first occurrence we found for a couple of things such as definition, which could result in a wrong symbol being picked up (symbol definition for anonymous class).
Now, we filter out empty occurrences since they should not be used for those purpose while still being useful for finding implementations.
Fixes https://github.com/scalameta/metals/issues/5833
I can't reproduce it reliably enough to add a test, but this is super minor.

bugfix: Don't search for symbol occurrence with empty position

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcSemanticTokensProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcSemanticTokensProvider.scala
tests/cross/src/test/scala/tests/tokens/SemanticTokensSuite.scala
tests/unit/src/test/resources/semanticTokens3/example/GivenAlias.scala

eg. in `val Foo = List`, syntax highlighting on Foo will be the same as on List. 
This was already true for `val`s defined in `predef.scala`

improvement: Color vals of module type as classes

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala

Previously anonymous function params with the same name were not distinguished

bugfix: Document highlight on anon-fun parameters in Scala 2

---

mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala

Connected to: https://github.com/scalameta/metals/issues/5869. This is fixed in dotty (probably the incorrect position was fixed in the compiler) and works for current nightly.

fix: workaround for wrong span in hover scala 3.3.1

---

mtags/src/main/scala-2/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala

resolves: https://github.com/scalameta/metals/issues/5869

bugfix: hover for select chains ending with function Scala 2

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcSyntheticDecorationsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcSyntheticDecorationProvider.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalametaCommonEnrichments.scala
tests/cross/src/test/scala/tests/pc/SyntheticDecorationsSuite.scala
tests/unit/src/test/scala/tests/SkipCommentsSuite.scala
tests/unit/src/test/scala/tests/decorations/SyntheticDecorationsLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/5835
There seems to be no reasonable way to distinguish  `t` from `t1` in `val t @ (t1, t2,) = (1,2)` in typed trees. We could do this on untyped but I think it will be faster this way.

bugfix: don't show inferred type for val def bind

---

mtags/src/main/scala/scala/meta/internal/pc/ScriptFirstImportPosition.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliActionsSuite.scala

fixes https://github.com/scalameta/metals/issues/5854

bugfix: Adjust auto import position for shebang

---

mtags/src/main/scala/scala/meta/internal/mtags/Semanticdbs.scala

This used to break after renaming file.
connected to https://github.com/scalameta/metals/issues/5834

improvement: Check if Scala file exists before calculating md5

---

metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

Previously, we would publish dependency diagnsotics as info diagnostics, but that has never proved useful and it might be false positive as we don't have the full build definition of dependencies. Now, we don't publish them at all.

improvement: Don't publish diagnostics for dependencies

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala

fixes https://github.com/scalameta/metals/issues/5881

bugfix: Inconsistent highlight on class constructor

---

metals/src/main/scala/scala/meta/internal/metals/SemanticTokensProvider.scala
tests/unit/src/test/scala/tests/SemanticTokensLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/5433
The choice of `{ type: "operator", modifier: "documentation" }`, is fairly random, I don't want to use keyword, which is already used for `$` in string interpolators. I'm open to suggestions on that matter.

improvement: add semantic tokens for escape sequences

---

tests/cross/src/test/scala/tests/pc/SyntheticDecorationsSuite.scala

closes https://github.com/scalameta/metals/issues/2555
It was fixed by moving synthetic decorations to presentation compiler

chore: Add test to close issue 2555

---

metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala

This causes issues with semanticdb, because source root is also set to that build directory and semanticdb ends up in the wrong place.

Revert creating .scala-build in temporary directory

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractRenameMember.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/5824

Extract member action for opaque type

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
tests/cross/src/test/scala/tests/pc/CompletionExtensionMethodSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

When symbol with the same name as extension method was present in scope, completion edit would insert full symbol name of this method, which was incorrect.
```scala
package example
|import example.enrichments.*
object enrichments:
extension (num: Int)
def plus(other: Int): Int = num + other
def main = {
val plus = 100.plus(19)
val y = 19.pl@@ // resulted in
val y = 19.example.enrichments.plus($0)
}
```

bugfix: Extension method completion with name conflict

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/Tables.scala

resolves: https://github.com/scalameta/metals/issues/5447
Do we want to fallback to deleting the db if this mechanism fails?

chore: upgrade h2 database

---

build.sbt
metals-bench/src/main/scala/bench/ClasspathFuzzBench.scala
metals-bench/src/main/scala/bench/WorkspaceFuzzBench.scala
metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/ImportedBuild.scala
metals/src/main/scala/scala/meta/internal/metals/JarSourcesProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSearchVisitor.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliActionsSuite.scala
tests/unit/src/main/scala/tests/BaseWorkspaceSymbolSuite.scala
tests/unit/src/main/scala/tests/Library.scala
tests/unit/src/main/scala/tests/debug/BaseStepDapSuite.scala
tests/unit/src/test/scala/tests/JarSourcesProviderSuite.scala

When build server fails to provide dependency sources for a build target metals will try to resolve/download the missing sources.
resolves: https://github.com/scalameta/metals/issues/4780

improvement: fetch missing dependency sources

---

metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala

Previously, there was no easy way to run verbose compilation and see what is going on underneath in Zinc. Now, it's possible, which might be super useful for debugging incremental compilation issues.
Closes https://github.com/scalameta/metals/issues/5773

feature: Add option to run verbose compilation

---

metals/src/main/scala/scala/meta/internal/bsp/ConnectionBspStatus.scala
metals/src/main/scala/scala/meta/internal/metals/ClientCommands.scala

These commands that are attached to status' are meant for the client to execute and send to the server. I noticed this because in nvim-metals I've gotten multiple reports of these commands not working when they arrive since normally the client commands are prefaced with `metals-` whereas the server ones aren't. I'm not sure how this was working in VS Code or if it was, but I believe this change is correct.

fix: use client commands inside of BSP status

---

metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala

Connected to: https://github.com/scalameta/metals/issues/4814
Honestly not sure if that makes it much better.

improvement: log when invalid `textDocument` uri in `build/publishDignostics`

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/builds/BloopInstall.scala
metals/src/main/scala/scala/meta/internal/builds/BloopInstallProvider.scala
metals/src/main/scala/scala/meta/internal/builds/BspOnly.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
metals/src/main/scala/scala/meta/internal/builds/Digest.scala
metals/src/main/scala/scala/meta/internal/builds/GradleBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/MavenBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/ScalaCliBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/VersionRecommendation.scala
metals/src/main/scala/scala/meta/internal/metals/Configs.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/PopupChoiceReset.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
tests/slow/src/test/scala/tests/MultipleBuildFilesLspSuite.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/test/scala/tests/BillLspSuite.scala

Previously: For custom BSP we would still use some other build tool if discovered.
Now: Custom BSP is in itself treated as a build tool, we look for `.bsp` configs in:
1. root directory,
1. custom project root directory,
1. `bspGlobalInstallDirectories`.
As a followup we should deduplicate code in build servers and build tools discovery and selection: 
1. `BspServers.findAvailableServers` repeats a lot from `BuildTools.loadSupported`,
1. build tool selection adjust build server selection when needed and the other way around.

improvement: add custom bsp as possible build tool

---

metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala
metals/src/main/scala/scala/meta/internal/parsing/JavaFoldingRangeExtractor.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaCompletionProvider.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaHoverProvider.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaMetalsGlobal.scala
mtags-java/src/main/scala/scala/meta/internal/pc/JavaPresentationCompiler.scala
tests/slow/src/test/scala/tests/feature/CompletionCrossLspSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/CompletionLspSuite.scala

Previously, we wouldn't include the classpath, so completions/hover would only work locally.
Now, we add the compiled classpath, so things should work as expected.
Fixes https://github.com/scalameta/metals/issues/5829

bugfix: Fix java support for different files

---

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
tests/unit/src/test/scala/tests/ImplementationLspSuite.scala

Previously, for all types we would try to dealias them, but if the type was abtract we would get Any, which is the parent of all classes, which would not be useful. Now, we will show implementations of that abstract type.

bugfix: Don't show all classes when searching for implementations of abstract type

---

mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
tests/cross/src/test/scala/tests/highlight/Scala3DocumentHighlightSuite.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala
tests/cross/src/test/scala/tests/tokens/SemanticTokensScala3Suite.scala

closes https://github.com/scalameta/metals/issues/5977
closes https://github.com/scalameta/metals/issues/5976

bugfix: Wrong span in extension methods in context functions

---

metals/src/main/scala/scala/meta/internal/bsp/BspConfigGenerator.scala
metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/builds/BloopInstall.scala
metals/src/main/scala/scala/meta/internal/builds/BuildServerProvider.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

It was causing issues in case of mill, where bsp name differs

bugfix: Use buildServerName instead of executableName in BSP

---

metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/CancelableFuture.scala
metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/DismissedNotifications.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
metals/src/main/scala/scala/meta/internal/metals/utils/FutureWithTimeout.scala
metals/src/main/scala/scala/meta/internal/metals/utils/RequestRegistry.scala
metals/src/main/scala/scala/meta/internal/metals/utils/Timeouts.scala
tests/unit/src/test/scala/tests/RequestRegistrySuite.scala
tests/unit/src/test/scala/tests/TimeoutSuite.scala

In some erroneous situations build server fails to respond, which in metals for e.g. compilation blocks the queue. This PR adds timeout to the requests, so in such situations we can recover.

improvement: add timeout to requests

---

metals-bench/src/main/scala/bench/ClasspathOnlySymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsSymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/ClasspathSearch.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/Fuzzy.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/PrefixCharSequence.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolQuery.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionPatternSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/mtest/src/main/scala/tests/TestingSymbolSearch.scala
tests/slow/src/test/scala/tests/feature/ClasspathSymbolRegressionSuite.scala
tests/unit/src/test/scala/tests/CompletionLspSuite.scala
tests/unit/src/test/scala/tests/FuzzySuite.scala

resolves: https://github.com/scalameta/metals/issues/5619
Previously: for query shorter than 3, we'd only show exact matches in completions (for classpath/workspace symbols), now we show all that have the correct prefix. Not exact matches from classpath are capped at 10, additionally we cap workspace symbols for those short queries at 100. If no prefix matches are found, we retry allowing for full fuzzy match.
Also fixes sorting in Scala 3, so keyword completions are offered before workspace/classpath ones.

improvement: show workspace completions for short queries

---

mtags-shared/src/main/scala/scala/meta/internal/pc/CompilerAccess.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaCompilerAccess.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Scala3CompilerAccess.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala

Related to https://github.com/scalameta/metals/issues/5272

chore: Add more information about classpath and compiler options when severe error happens

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProtocol.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugRunner.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala
tests/unit/src/main/scala/scala/meta/internal/metals/debug/RemoteServer.scala
tests/unit/src/main/scala/tests/BaseCodeLensLspSuite.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/CodeLensLspSuite.scala
tests/unit/src/test/scala/tests/DebugProtocolSuite.scala
tests/unit/src/test/scala/tests/debug/DebugProtocolCancelationSuite.scala

This works by doing the bare minimum that DAP requires and forwarding the logs from the build server.
We can later use this minimal DAP server to also run quicker test instead of setting up the entire debugging session
Resolves https://github.com/scalameta/metals-feature-requests/issues/325

feature: Add support for running Native and JS

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionPos.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionScala3Suite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

resolves: https://github.com/scalameta/metals/issues/5991

bugfix: don't show scope completions for multi-imports

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/NamedArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala

This also caused:
```
java.base/java.util.TimSort.mergeLo(TimSort.java:781)
java.base/java.util.TimSort.mergeAt(TimSort.java:518)
java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
java.base/java.util.TimSort.sort(TimSort.java:254)
java.base/java.util.Arrays.sort(Arrays.java:1233)
scala.collection.SeqOps.sorted(Seq.scala:727)
scala.collection.SeqOps.sorted$(Seq.scala:719)
scala.collection.immutable.List.scala$collection$immutable$StrictOptimizedSeqOps$$super$sorted(List.scala:79)
scala.collection.immutable.StrictOptimizedSeqOps.sorted(StrictOptimizedSeqOps.scala:78)
scala.collection.immutable.StrictOptimizedSeqOps.sorted$(StrictOptimizedSeqOps.scala:78)
scala.collection.immutable.List.sorted(List.scala:79)
scala.meta.internal.pc.completions.Completions.completions(Completions …
```

bugfix: Don't show default argument values if type is Any

---

mtags-shared/src/main/scala/scala/meta/internal/pc/InterpolationSplice.scala
tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala

The only issue here is the exception thrown, but it's better to fix it.

bugfix: Don't try to add interpolation completions at a wrong position

---

mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ExtractMethodProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcInlineValueProviderImpl.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcSyntheticDecorationProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala

https://github.com/lampepfl/dotty/pull/12783 has been fixed for a very long time and this method caused multiple crashes according to reports.

Remove context of path wrapper which caused multiple compiler crashes

---

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
tests/unit/src/main/scala/scala/meta/internal/metals/debug/Completer.scala
tests/unit/src/main/scala/scala/meta/internal/metals/debug/DebugStep.scala
tests/unit/src/main/scala/scala/meta/internal/metals/debug/Debugger.scala
tests/unit/src/test/scala/tests/debug/CompletionDapSuite.scala

Currently, There is some DAP client ([nvim-dap](https://github.com/mfussenegger/nvim-dap)) which doesn't send `CompletionsRequest. arguments.line` field to *metals*.
https://github.com/mfussenegger/nvim-dap/blob/9adbfdca13afbe646d09a8d7a86d5d031fb9c5a5/lua/dap/repl.lua#L477-L480
This is fine since `line` is an optional argument and according to DAP specification, when `line` is not sent as part of `CompletionsArguments`, the DAP server should assume `line` to be `1`.
However, *metals* is not working correctly when `line` is not being set. This PR aims to fix this bug by handling the case where `line = null` properly

bugfix: incorrect debug completion when line is not sent from DAP client

---

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/metals/formatting/OnTypeFormattingProvider.scala
metals/src/main/scala/scala/meta/internal/metals/formatting/RangeFormattingProvider.scala
metals/src/main/scala/scala/meta/internal/parsing/TokenEditDistance.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
tests/slow/src/test/scala/tests/feature/SyntaxErrorLspSuite.scala
tests/unit/src/test/scala/tests/scalafix/ScalafixProviderLspSuite.scala

Previously, when sending diagnostics we would always tokenize the file even if it was the same and this actually was causing some OOM if there were to many diagnostics sent.
This doesn't seem necessary at all and was most likely done to satisfy some tests.

bugfix: Don't tokenize if the source hasn't changed

---

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
tests/unit/src/main/scala/scala/meta/internal/metals/debug/Debugger.scala
tests/unit/src/main/scala/scala/meta/internal/metals/debug/RemoteServer.scala
tests/unit/src/main/scala/scala/meta/internal/metals/debug/TestDebugger.scala
tests/unit/src/main/scala/tests/BaseDapSuite.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/debug/CompletionDapSuite.scala

Some DAP client, when receiving Stoppage event, will get a list of all threads and iterate through that list to get each thread's stack-trace eagerly. One example of this is [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/components/threads.lua#L71-L75).
Since **metals** maintains only the latest stack-trace response to use for frame-searching during debug-completion, debug-completion won't work if the frame-id in debug-completion request is not in the latest stack-trace response.
IMO, the behavior of debug-completion shouldn't depends on the order of stack-trace requests. And ideally, DAP server shouldn't even depends on the stack-trace being requested at all for debug-completion to work. However, since **metals** is currently just a proxy for …

bugfix: debug-completion depends on order of stackTrace being requested

---

metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala

Previously, if a build tool didn't generate semanticdb we would not get any scalafix, including organize imports, working. Now, we fallback to having semanticdb generated by the presentation compiler.
Also, a small fix to make sure we don't try to index source jars that don't exists (happened in case of Bazel)

improvement: Generate semanticdb if not found

---

metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala

We use DAP in that case anyway, so the run capability for client is not needed.
We could resign from running via shell maybe if it's quick enough :thinking:

bugfix: Show non jvm lenses even if client is not a run provider

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala

connected to https://github.com/scalameta/metals/issues/5339

improvement: Add `case` keyword completion

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaMtags.scala
tests/input/src/main/scala-3/example/dotted.filename.scala
tests/unit/src/test/resources/decorations3/example/dotted.filename.scala
tests/unit/src/test/resources/definition-scala3/example/dotted.filename.scala
tests/unit/src/test/resources/documentSymbol-scala3/example/dotted.filename.scala
tests/unit/src/test/resources/expect/toplevels-scala3.expect
tests/unit/src/test/resources/mtags-scala3/example/dotted.filename.scala
tests/unit/src/test/resources/semanticTokens3/example/dotted.filename.scala
tests/unit/src/test/resources/semanticdb-scala3/example/dotted.filename.scala
tests/unit/src/test/resources/toplevel-with-inner-scala3/example/dotted.filename.scala

resolves: https://github.com/scalameta/metals/issues/6051

correctly backtick toplevel source object when needed in mtags

---

docs/editors/overview.md

It seems we should escape `*` at least in those positions

bugfix: Fix the scaalfix job

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/ServerLivenessMonitor.scala
tests/unit/src/main/scala/bill/Bill.scala

`workspace/buildTargets` was causing unnecessary operations in bazelbsp. This new method should be faster and doesn't require any actions from the build server

improvement: Change BSP ping message to empty buildtarget/compile

---

metals/src/main/scala/scala/meta/internal/builds/BazelBuildTool.scala

This is needed so that if a codebase has a more complex logic for specifying rules, we will still be able to get information about scala.

bugfix: Add enabled-rules to make sure Scala is always detected

---

metals-bench/src/main/scala/bench/ClasspathSymbolsBench.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/tvp/IndexedSymbols.scala
metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaMtags.scala
tests/unit/src/test/scala/tests/TreeViewLspSuite.scala

Previously, Metals would need semanticdb for project view, which means when using build tools that don't provide it, no files would be shown. Now, we just use the usual ScalaMtags for those files.

improvement: Don't require compilation for semanticdb

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

I noticed in a Bazel workspace that we also save other files, which is not neccessary for semanticdb.

improvement: Only save scala or java fingerprints

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

Aligns labels in completions for methods from workspace is Scala 3 to work the same as for Scala 2. 
Previously the label did not contain information about the source of the method.

improvement: Better labels for workspace methods completions

---

mtags/src/main/scala/scala/meta/internal/mtags/JavaToplevelMtags.scala
mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/3815
This will slow down indexing, since now we read in java files, which we weren't doing before. However, [go to implementation for dependency sources](https://github.com/scalameta/metals/pull/5623), will require of us to read in those files anyway.

bugfix: handle nested java jars

---

docs/build-tools/bazel.md
docs/build-tools/overview.md

So that the docs don't stay only on the release notes.

docs: Add documentation about Bazel

---

.github/workflows/ci.yml
.scalafmt.conf
mtags/src/main/scala-2.11/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/slow/src/test/scala/tests/feature/CompletionCrossLspSuite.scala

Previously, Scala presentation compiler for Scala 2.11 would not work if used on a newer JDK. Now, since the fix was small and there are no plan on releasing Scala 2.11.13 I shadowed the problematic class and that should fix the issue.

bugfix: Allow Scala 2.11 to be run on newer JVMs

---

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala

https://github.com/scalameta/metals/issues/6104
This is a quick fix for a breaking change on WIndows. We might want to find the correct executable in "PATH" on Windows in the future.

bugfix: revert back to using embedded `sbt` launcher for Windows

---

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala

resolves: https://github.com/scalameta/metals/issues/2494
Sometimes there are multiple occurrences in the same location, e.g. import can be both occurrence of the object and class, in case of `find references` that may lead to duplication in results.

bugfix: deduplicate references results

---

mtags/src/main/scala-2/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala
mtags/src/main/scala/scala/meta/internal/pc/ScriptFirstImportPosition.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

Previously the import would be inserted above using directives
fixes https://github.com/scalameta/metals/issues/6027

bugfix: Auto imports in worksheets in Scala 3

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala

resolves: https://github.com/scalameta/metals/issues/2869
It turns out, that VSCode is able to deal with this if only metals supports text document version.

bugfix: use text document version for initial package edit

---

docs/build-tools/bazel.md
metals/src/main/scala/scala/meta/internal/process/SystemProcess.scala

Previously, the PWD given to Metals server would be that of user home. Now, we override it to always point to the current project directory.
Fixes https://github.com/scalameta/metals/issues/6094

bugfix: Fix restarting bazel

---

metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala

When jobs isn't specified this will default to 1 [disabling parallel task execution](https://mill-build.com/mill/Intro_to_Mill.html#_parallel_task_execution). This can cause really slow import times for big builds. For example on my modern M1 macbook, it takes around 20 minutes to import the Mill codebase. The docs linked say the following:
> To use as many threads as your machine has (logical) processor cores use --jobs 0.
So we switch it to that.

refactor: generate mill BSP file with `--jobs 0`

---

metals/src/main/scala/scala/meta/internal/builds/BazelBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala

Partly fixes https://github.com/scalameta/metals/issues/6131
It seems that Bazel BSP creates empty projectview if it doesn't exist.

improvement: Regenerate Bazel files if any are missing

---

mtags/src/main/scala-3.0/scala/meta/internal/pc/MetalsSealedDesc.scala
mtags/src/main/scala-3.1/scala/meta/internal/pc/MetalsSealedDesc.scala
mtags/src/main/scala-3.2/scala/meta/internal/pc/MetalsSealedDesc.scala
mtags/src/main/scala-3.3/scala/meta/internal/pc/MetalsSealedDesc.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionMatchSuite.scala

closes https://github.com/scalameta/metals-feature-requests/issues/371

improvement: Match completions on union types

---

metals/src/main/scala/scala/meta/internal/builds/BloopInstall.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/ScalaCliBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
tests/slow/src/test/scala/tests/PreferredBuildServer.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala
tests/unit/src/main/scala/tests/BuildServerInitializer.scala

resolves: https://github.com/scalameta/metals-feature-requests/issues/358

feat: add setting to choose preferred build server

---

metals/src/main/scala/scala/meta/internal/metals/JsonParser.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DapJsonParser.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProtocol.scala

I want to use [presentationHint](https://github.com/eclipse-lsp4j/lsp4j/blob/88868d3506d317b12cf0bfd1e82a254489f8c47b/org.eclipse.lsp4j.debug/src/main/java/org/eclipse/lsp4j/debug/DebugProtocol.xtend#L2979) in DAP messages but I can't because the current JSON parser does not handle Java enums correctly. It should be serialized to `"presentationHint": "deemphasize"` and not `"presentationHint": "DEEMPHASIZE"`.
lsp4j has two different enum type handlers for DAP ([here](https://github.com/eclipse-lsp4j/lsp4j/blob/88868d3506d317b12cf0bfd1e82a254489f8c47b/org.eclipse.lsp4j.jsonrpc.debug/src/main/java/org/eclipse/lsp4j/jsonrpc/debug/json/DebugMessageJsonHandler.java#L34-L35)) and for LSP ([here](https://github.com/eclipse-lsp4j/lsp4j/blob/88868d3506d317b12cf0bfd1e82a254489f8c47b/org.eclipse.lsp4 …

Fix parsing of enum in DAP messages

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/CompilerInlayHintsParams.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/CompilerSyntheticDecorationsParams.scala
tests/slow/src/test/scala/tests/feature/InlayHintsFallbackSuite.scala
tests/unit/src/main/scala/tests/BaseInlayHintsLspSuite.scala
tests/unit/src/main/scala/tests/TestMtagsResolver.scala
tests/unit/src/test/scala/tests/inlayHints/InlayHintsLspSuite.scala

For Scala 3.nightly, it maps old synthetic decorations to inlay hints. Its needed because inlay hints are not available for every Scala version

improvement: Add fallback for inlay hints

---

build.sbt

Previously, we would get all the messages up to debug level from flyway, which added a lot of overhead. It seems that this is due to the fact that flyway has issues detecting slf4j loggers and especially scribe, which implements it. Changing to slf4j2 helped here and we get much less data.

chore: Change to slf4j2 to avoid too much logging in flyway

---

metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProtocol.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
metals/src/main/scala/scala/meta/internal/metals/debug/MetalsDebugAdapter.scala

Follow up of the implementation of hot code replace (HCR) in the scala-debug-adapter ([link](https://github.com/scalacenter/scala-debug-adapter/pull/553)) and in the vscode extension ([link](https://github.com/scalameta/metals-vscode/pull/1419)). Trigger a 2nd compilation (after the first one due to saving) to ensure that HCR does not happen during compilation

Trigger HCR after compilation

---

mtags/src/main/scala-3.3.3/scala/meta/internal/pc/Compat.scala
mtags/src/main/scala-3.3.3/scala/meta/internal/pc/printer/RefinedDotcPrinter.scala
project/V.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionPatternSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionScalaCliSuite.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala
tests/mtest/src/main/scala/tests/BaseSuite.scala

Scala 3.3.2 was broken so we put it straight away to deprecate

chore: Add support for Scala 3.3.3

---

tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionPatternSuite.scala

Fix for tomorrow breaking change in nightly CI: https://github.com/lampepfl/dotty/pull/19614/

Fix CI to make up for latest changes in dotty

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/unit/src/test/scala/tests/Example.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

connected to: https://github.com/scalameta/metals/pull/6156#issuecomment-1973407601

bugfix: emit as extension method if member of implicit class with val in constructor

---

mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ConvertToNamedArgumentsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ExtractMethodProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcInlayHintsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SemanticdbTextDocumentProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/OverrideCompletions.scala

The issue showed up in https://github.com/scalameta/metals-vscode/discussions/1470#discussioncomment-8722769

improvement: Check if compiled unit is available before using

---

metals/src/main/scala/scala/meta/internal/bsp/BspConfigGenerator.scala
metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/ScalaCliBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/Directories.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalametaCommonEnrichments.scala
tests/slow/src/test/scala/tests/bazel/BazelLspSuite.scala
tests/unit/src/main/scala/bill/Bill.scala
tests/unit/src/main/scala/tests/BuildServerInitializer.scala
tests/unit/src/test/scala/tests/BillLspSuite.scala
tests/unit/src/test/scala/tests/BspStatusSuite.scala
tests/unit/src/test/scala/tests/BspSwitchLspSuite.scala
tests/unit/src/test/scala/tests/ServerLivenessMonitorLspSuite.scala

I also added a small refactor to not use plain strings for the two directories being removed.

improvement: Remove bazel specific directories when running full clean

---

metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
tests/slow/src/test/scala/tests/feature/WorksheetCrossLspSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/6192

bugfix: fix worksheets with `3.4.0`

---

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
metals/src/main/scala/scala/meta/internal/implementation/InheritanceContext.scala
metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
tests/unit/src/main/scala/tests/BaseRangesSuite.scala
tests/unit/src/test/scala/tests/ImplementationLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/6206

bugfix: go to implementations for multi-module projects

---

tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala

https://github.com/scala/scala3/pull/19921

chore: unignore tests after backport

---

metals/src/main/scala/scala/meta/internal/metals/CodeLensProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/CodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/SuperMethodCodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/WorksheetCodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClasses.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/testProvider/TestSuitesProvider.scala

Previously, we would eagerly request jvmEnvironment for all known main classes, which in case of Bazel might cause a lot of queries. This might also not be efficient in some other cases. Now, we only request and cache jvmRunEnvironment when needed.

improvement: Request jvmRunEnvironment lazily

---

metals-bench/src/main/scala/bench/ClasspathSymbolsBench.scala
metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/BuildTargetInfo.scala
metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/ImportedBuild.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/TargetData.scala
metals/src/main/scala/scala/meta/internal/metals/debug/SourcePathAdapter.scala
metals/src/main/scala/scala/meta/internal/tvp/IndexedSymbols.scala
metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala

Previously, we would assume that the source jar is in the same directory as the normal jar. Now we use dependencyModules for that and only fallback to the previous logic if we can't find the jar in dependency modules.
This extracts part of the lazy classpath PR
Fixes https://github.com/scalameta/metals/issues/6182

improvement: Use dependencyModule for resolving sources

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/ScalatestTestFinder.scala
tests/unit/src/test/scala/tests/testProvider/ScalatestFinderSuite.scala

improvement: support "behavior of" syntax in ScalaTest's FlatSpec style

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala

Error 3.15 reported from Scastie using reporting mechanisms

bugfix: Case completions in summonFrom

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

resolves: https://github.com/scalameta/metals/issues/6220

fix: take last change in `didChange`

---

metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala

fixes: https://github.com/scalameta/metals/issues/6250

bugfix: fix table name

---

metals/src/main/scala/scala/meta/internal/metals/debug/ClientConfigurationAdapter.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProtocol.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala

Use `presentationHint` to deemphasize/collapse skipped frames.

Collapse skipped frames

---

metals/src/main/scala/scala/meta/internal/metals/MtagsResolver.scala

Previously, we would have a lot of fallbacks that would be used if mtags was not avaiable. Now, each version of the compiler has a stable version of the compiler being released so there is no longer a reason to handle it via fallback. Instead we want to be explicit about what we are resolving.
It seems that previous way was flaky and while I can't reproduce the issues people had, I think simplifying it would help out at lest to get the exact failure of what is going on.

improvement: Simplify resolving presentation compiler

---

metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala
metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/JavaBinary.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala
mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala
tests/slow/src/test/scala/tests/mill/MillServerSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala
tests/unit/src/main/scala/tests/JavaHomeChangeTest.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/test/scala/tests/BloopJavaHomeLspSuite.scala
tests/unit/src/test/scala/tests/Java8Suite.scala

Aim of this PR is to separate java used by Metals from java used for the project.
- Adds `-release` option to scalac options when project's jvm version < Metals jvm version to offer correct completions. Note that this works only for Scala 2 compiler completions. (For workspace completions we already index correct java sources)
- Starts bloop with the same JDK that Metals is started with.
- On user java home config update (java home that should be used for the project) propagates that change to build server (working for bloop, sbt and mill):
- for Bloop done via reimport,
- for sbt we restart the build server.
https://github.com/scalameta/metals/issues/3923
resolves: https://github.com/scalameta/metals/issues/5959 (now we will always run `bloop` with Metals java)

improvement: handle java home setting

---

tests/unit/src/test/scala/tests/worksheets/WorksheetInfiniteLoopSuite.scala

This test seems to fail on Mac OS quite a lot. Eval worksheet reaches timeout, so I'm increasing timeout and adding retry.
https://github.com/scalameta/metals/actions/runs/8525141762/job/23351371215?pr=6273#step:4:7995

test: increase timeout on worksheet inf loop test

---

metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/builds/BspOnly.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
tests/slow/src/test/scala/tests/MultipleBuildFilesLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/6261
This resolves two issues:
1. fixes connecting to custom bsp in presence of multiple bsp configs and a known build tool (e.g. `sbt`) in workspace
2. allows for `<name>.json` to differ from `"name"` in bsp config

bugfix: allow for mixed multiple custom and known build servers

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

Previously, we would only search through some directories to check if a project is a Scala one. Now, we also check for focused document.
This should work since focused document will only really get Scala file updates and the server will only start if any Scala files were opened. And it's basically a fallback.
The other solution would be to search more directories instead of the standard ones
Fixes https://github.com/scalameta/metals/issues/6280

improvement: Also start Scala CLI if the focused file was Scala

---

metals-bench/src/main/scala/bench/InlayHintsBench.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/InlayHintsOptions.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
mtags-interfaces/src/main/java/scala/meta/pc/InlayHintsParams.java
mtags-shared/src/main/scala/scala/meta/internal/metals/CompilerInlayHintsParams.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcInlayHintsProvider.scala
tests/cross/src/main/scala/tests/BaseInlayHintsSuite.scala
tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala
tests/slow/src/test/scala/tests/feature/InlayHintsFallbackSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtBloopLspSuite.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala
tests/unit/src/main/scala/tests/BaseInlayHintsExpectSuite.scala
tests/unit/src/main/scala/tests/BaseInlayHintsLspSuite.scala
tests/unit/src/test/resources/inlayHints/example/Miscellaneous.scala
tests/unit/src/test/resources/inlayHints3/example/Miscellaneous.scala
tests/unit/src/test/resources/inlayHints3/example/PatternMatching.scala
tests/unit/src/test/scala/tests/inlayHints/InlayHintsHoverSuite.scala
tests/unit/src/test/scala/tests/inlayHints/InlayHintsLspSuite.scala

Adds new user configuration for inlay hints, with a fallback to old settings. 
Also adds separate option for inlay hints inside pattern match.

improvement: New inlay hints options

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

Error 01.11 reported from Scastie using reporting mechanisms

bugfix: CompletionPosition inferStart should not crash

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

fixes: https://github.com/scalameta/metals/issues/6274

fix: check that implicit method owner is static in completions

---

metals/src/main/scala/scala/meta/internal/metals/Messages.scala

Previously, it would say that no navigation is supported, however go to definition does work. Now, it points to the exact features that do not work.

chore: Improve Bazel navigation message

---

tests/cross/src/main/scala/tests/BaseCompletionSuite.scala

resolves: https://github.com/scalameta/metals/issues/6295
I added a generic filter, so we don't have to be bothered with this when adding new test cases.

tests: filter out `java.lang.classfile` for JDK 22

---

metals-bench/src/main/scala/bench/MetalsBench.scala
mtags/src/main/scala/scala/meta/internal/mtags/JavaToplevelMtags.scala

fixes: https://github.com/scalameta/metals/issues/6314
I just added a catch clause since there isn't a good way to fix this. It's a generated file that simply doesn't parse:

improvement: do not throw on failed java indexing

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

connected to: https://github.com/scalameta/metals/issues/6315#issuecomment-2062661332

fix: handle `type T = Object.type` in type hierarchy indexing

---

docs/integrations/debug-adapter-protocol.md

I'm not sure, what the line number 356 in `extension.ts` used to show.
If someone happens to know, I could link to the exact line as well.

docs: Fix links to Typescript code

---

mtags/src/main/scala-3/scala/meta/internal/pc/printer/MetalsPrinter.scala
tests/cross/src/test/scala/tests/pc/CancelCompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala
tests/slow/src/test/scala/tests/feature/Scala3CodeActionLspSuite.scala

fixes: https://github.com/scalameta/metals/issues/6292

fix: include `inline` when printing param names

---

metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala

I haven't managed to figure out why exactly scalafix is failing, but it seems organize imports would not work in Metals if we loaded scalafix eagerly. My guess is that we would somehow get two different classloaders somewhere, but I can't figure out where.

bugfix: Don't preemptively load scalafix

---

metals/src/main/scala/scala/meta/internal/metals/FileSystemSemanticdbs.scala

I noticed it happening in a bazel project for a couple of targets. This is most likely a bug in Bazel BSP, but digging into that could take a while, so to make sure that this will show up properly I added a log statement.

chore: Report if target root is missing

---

metals/src/main/scala/scala/meta/internal/metals/CompilerConfiguration.scala

It's not important for presentation compiler and causes a warning when wrongly paired with release option. It's easier to just ingore it.

bugfix: Don't include target option for PC

---

docs/contributors/releasing.md
metals-docs/src/main/scala/docs/RequirementsModifier.scala
metals/src/main/scala/scala/meta/metals/Main.scala
metals/src/main/scala/scala/meta/metals/SupportedScalaVersions.scala
tests/unit/src/test/scala/tests/SupportedScalaSuite.scala

This will check maven central for stable releases and sonatype snapshots for snapshot ones.
There are two way new mechanism for checking supported Scala will be used:
- `metals --versions` which will show all supported versions for the current server
- in the docs, where we will show support for the latest stable version. It will get updated after any back publish of Scala version when the website is updated after any PR.
Supersedes https://github.com/scalameta/metals/pull/4606

improvement: Show actual Scala versions supported by Metals

---

mtags/src/main/scala/scala/meta/internal/mtags/JavaToplevelMtags.scala
tests/unit/src/test/scala/tests/JavaToplevelSuite.scala

Turns out one lbirary released broken source without ending quote and this caused the infinite indexing.
Fixes https://github.com/scalameta/metals/issues/6418

bugfix: Fix infinite indexing

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/builds/BazelBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/BuildServerProvider.scala
tests/slow/src/test/scala/tests/bazel/BazelLspSuite.scala

This makes sure Metals will use the newest BSP at all times with all the fixes.

improvement: Automatically update bazel bsp

---

mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala

For Windows users oldPath would always return as an empty string. This is because we're using "PATH" instead of "Path". Being's that would always return as an empty string, the newPath would always be the javaBin string. When storing in the map, we used the OS specific Path/PATH but with the wrong information.

Fixed issue where oldPath wasn't using OS specific spelling for Path/PATH

---

metals-bench/src/main/scala/bench/PcBenchmark.scala
metals/src/main/scala/scala/meta/internal/metals/CompilerConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/Embedded.scala
tests/unit/src/main/scala/tests/TestScala3Compiler.scala

I think this was done by mistake in https://github.com/scalameta/metals/pull/2417 but very rarely caused any issues.
Previous to that PR we would only get Scala jars from ScalaBuildTarget.getJars method and after we would use the full classpath.
This never happened in the latest Scala version as we would just start mtags via new ScalaPresentationCompiler and it would happen randomly for some other versions.
Now, since we always use mtags artifacts they always contain the needed Scala jars (unless there would be a custom platform) so there is no need to add anything more.
This might have caused https://github.com/scalameta/metals/issues/5272

bugfix: Don't start mtags with full classpath

---

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProtocol.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala

Previously we would use LaunchRequestArguments, but those are actually not used and what is actually returned is a Map. This become a problem after the fix that deserialized arguments to correct params.
Now, we use Map instead.
Raised the issue here https://github.com/eclipse-lsp4j/lsp4j/issues/842
Also fixed tests to use newest toolkit instead.

bugfix: Use actual method arguments from DAP server interface

---

tests/unit/src/main/scala/tests/BaseLspSuite.scala
tests/unit/src/main/scala/tests/TestMtagsResolver.scala
tests/unit/src/main/scala/tests/TestScala3Compiler.scala
tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala

The tests often timeout if coursier with retries is involved and besides mtags are not published aside from 2.13.x so this will always fail.

refactor: Don't try to download artifacts in ProblemResolverSuite

---

metals/src/main/scala/scala/meta/internal/worksheets/WorksheetProvider.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala

Since we didn't put synthetic `|` on every new line, `.stripMargin` was stripping `|` from the actual code.
resolves: https://github.com/scalameta/metals/issues/6361

fix: pc functions for multiline strings in worksheets in scala 3

---

metals/src/main/scala/scala/meta/internal/metals/DiagnosticCodes.scala
metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala

~waiting for: https://github.com/scala/scala3/pull/19780~
For now this will only work for scala3 as scala2 does not emit errorCodes. 
Regex based support for this feature in scala2 will be added as a follow-up. 
cc @rochala

feat: Set unused tag for unused diagnostics

---

metals/src/main/scala/scala/meta/internal/metals/AdjustLspData.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/IdentifierIndex.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
mtags-shared/src/main/scala/scala/meta/internal/pc/SymbolInfo.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcReferencesProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/WorkspaceSymbolSearch.scala
mtags/src/main/scala-3/scala/meta/internal/pc/SymbolInformationProvider.scala
tests/slow/src/test/scala/tests/feature/PcReferencesLspSuite.scala
tests/slow/src/test/scala/tests/feature/RenameCrossLspSuite.scala
tests/unit/src/test/scala/tests/ReferenceLspSuite.scala

Previously we would run recompile for inverse build targets after `go to references` to find if there are no new references. This would cause a lot of recompilations in presence of compilation errors. Since now we use `pc` as fallback for finding references we can use it always for files that have stale semanticdb.
resolves: https://github.com/scalameta/metals/issues/6348
Since now a lot more tests use `pc` for references this showed a few issues with that. The fixes probably have to also be migrated to Scala 3 pc.

improvement: don't run `compileAndLookForNewReferences `

---

mtags/src/main/scala-3/scala/meta/internal/pc/IndexedContext.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionScala3Suite.scala

resolves: https://github.com/scalameta/metals/issues/6477

fix: correctly auto import when there is a renamed symbol with the same name in scope

---

metals/src/main/scala/scala/meta/internal/bsp/ConnectionBspStatus.scala
metals/src/main/scala/scala/meta/internal/metals/Warnings.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

resolves: https://github.com/scalameta/metals/issues/6387
For clients that do not support status bar `showMessageRequest` is used, and the appropriate command is executed on option chosen:
https://github.com/scalameta/metals/blob/0c8159200e7da4a1792e017e0f3f99c052f0950a/metals/src/main/scala/scala/meta/internal/metals/clients/language/ConfiguredLanguageClient.scala#L60-L82
Previously:
We'd use client command `metals-doctor-run` for running doctor in status bar. When status bar not supported this command would be send with empty args to client, which caused https://github.com/scalameta/metals/issues/6387.
Now:
We use server command `doctor-run` instead. If status bar not supported the command will be executed on the server without clients involvement.
@ckipp01 Will this change cause issues …

fix: use server command for doctor run in status bar

---

metals-docs/src/main/scala/docs/RequirementsModifier.scala
metals/src/main/scala/scala/meta/metals/Main.scala
metals/src/main/scala/scala/meta/metals/SupportedScalaVersions.scala
tests/unit/src/test/scala/tests/SupportedScalaSuite.scala

Previously, we would check mtags links one by one, which would be slow as there are a number of online requests.
Now, we run all the requests parallel and also use a timeout, which will print defaults.
```
~ metals --version
Checking available versions on https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/
metals 1.3.1+39-99831afc-SNAPSHOT
- Scala 2.11:
2.11.12
- Scala 2.12:
2.12.12, 2.12.13, 2.12.14, 2.12.15, 2.12.16, 2.12.17, 2.12.18, 2.12.19
- Scala 2.13:
2.13.7, 2.13.8, 2.13.9, 2.13.10, 2.13.11, 2.13.12, 2.13.13, 2.13.14
- Scala 3:
3.3.1, 3.2.2, 3.3.2, 3.1.3, 3.3.3
Scala 3 versions from 3.3.4 are automatically supported by Metals.
Any older Scala versions will no longer get bugfixes, but should still
work properly with newest Metals.
```
Fixes …

improvement: Run mtags check parallel and set maximum timeout

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala

resolves: https://github.com/scalameta/metals/issues/6488

improvement: don't delete classpath jars for running main from `.metals/.tmp` before server shutdown

---

metals/src/main/scala/scala/meta/internal/bsp/BspSession.scala
metals/src/main/scala/scala/meta/internal/builds/BazelBuildTool.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/ProjectMetalsLspService.scala
tests/slow/src/test/scala/tests/bazel/BazelLspSuite.scala

Previously, it was possible that the file would get delete and recreated by Bazel BSP automatically. In that case it will end up empty and no targets would be imported,
Now, we make sure that it's not possible to have empty projectview be it because of  Bazel BSP or because of user changes,

improvement: Make sure we always have correct projectview file

---

metals/src/main/scala/scala/meta/internal/builds/BuildToolSelector.scala
metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
metals/src/main/scala/scala/meta/internal/builds/ScalaCliBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/ProjectMetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala
tests/unit/src/main/scala/tests/TestingClient.scala
tests/unit/src/test/scala/tests/FileWatcherLspSuite.scala

Since we already cache a list of build tools and that is actually updated on build related changes then it's better to use current whenever possible
Fixes https://github.com/scalameta/metals/issues/6459

chore: Don't recalculate build tools every time

---

mtags-shared/src/main/scala/scala/meta/internal/metals/TrigramSubstrings.scala
tests/slow/src/test/scala/tests/feature/ImportMissingSymbolCrossLspSuite.scala
tests/unit/src/test/scala/tests/TrigramSubstringsSuite.scala

resolves: https://github.com/scalameta/metals/issues/6475

fix: prefer latter fully qualified name parts when building trigrams for fuzzy search

---

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala

resolves #6026
Tested locally on a side-project, but not sure how to write tests here, haven't found example-tests that cover `DebugProvider`.
--
And am I correct, that it is beneficial to propagate to `startTestSuite` not only sbtOpts, but environmment as well (envFromFile ...)?
If yes, will update the PR.
Please review!

fix: propagate jvmopts to tests

---

metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/Doctor.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/DoctorExplanation.scala
metals/src/main/scala/scala/meta/internal/metals/doctor/ProblemResolver.scala
tests/slow/src/test/scala/tests/bazel/BazelLspSuite.scala
tests/unit/src/main/scala/tests/BaseImportSuite.scala

It's not possible to see if a user has semanticdb enabled in Bazel, so instead we already show if the semanticdb is currently present. This makes the warning message sometimes invalid, so instead I added further explanation to the doctor.

improvement: Don't show bazel navigation issue always

---

metals/src/main/scala/scala/meta/internal/builds/ScalaCliBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCliServers.scala

resolves: https://github.com/scalameta/metals/issues/6508
This is the case where paths totally don't match and compiler panics and creates `semanticdb` next to the sources. Adding `--semanticdb-sourceroot` flag will cause it create it in the correct place for `.scala` files.
However, we don't actually use semanticdb for single files anyway, since the paths will still be broken for scripts. Maybe instead of `--semanticdb-sourceroot`, we could have a flag that stops semanticdb from being produced all together?
CC: @tgodzik @Gedochao

fix: don't create `semanticdb` next to user sources for single files

---

metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala

This might cause issues with for example Bazel as it might be restarted on terminal

bugfix: Don't override JAVA_HOME if it already exists

---

metals/src/main/resources/shared-db/migration/V1__Jar_type_hierarchy.sql
metals/src/main/scala/scala/meta/internal/metals/H2Connection.scala
metals/src/main/scala/scala/meta/internal/metals/H2ConnectionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/SqlSharedIndices.scala
metals/src/main/scala/scala/meta/internal/metals/Tables.scala
mtags/src/main/scala/scala/meta/internal/mtags/GlobalSymbolIndex.scala
mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala
mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala
tests/mtest/src/main/scala/tests/DelegatingGlobalSymbolIndex.scala
tests/mtest/src/main/scala/tests/PCSuite.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala
tests/unit/src/test/scala/tests/ImplementationLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/6304

improvement: add jdk indexing

---

metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
tests/unit/src/test/scala/tests/ScalaVersionsSuite.scala

Previously, we would identify any jar with 3.0 as Scala 3. Now we require _ as is always added to scala libraries
Fixes https://github.com/scalameta/metals/issues/6533

bugfix: Always require _ to calculate scala version from jar

---

metals/src/main/scala/scala/meta/internal/builds/BazelBuildTool.scala

bugfix: Show errors for Scala 3 in Bazel correctly

---

tests/slow/src/test/scala/tests/mill/MillLspSuite.scala

Since `0.11.8` there is also a build target for mill build (after import to bloop). Find references, shows references between user created `build.sc` and generated `build.sc`.

chore: move mill test to newest mill version

---

project/V.scala
tests/slow/src/test/scala/tests/mill/MillServerCodeLensSuite.scala
tests/slow/src/test/scala/tests/mill/MillServerSuite.scala
tests/unit/src/main/scala/tests/BuildServerLayout.scala

Looks like using latest might be causing some issues, especially mtags not being resolved and causing a lag in the tests.

bugfix: Use latest stable mill version

---

metals/src/main/scala/scala/meta/internal/metals/DelegateSetting.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ProjectMetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceFolders.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
tests/slow/src/test/scala/tests/sbt/WorkspaceFolderSuite.scala

resolves: https://github.com/scalameta/metals/issues/6497
I think this is still rarely used so maybe we can just delete the old setting? We can also leave a transition period.

fix: change project ref setting to support VSCode workspace folder reload

---

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala

Fixes https://github.com/scalameta/metals/issues/6553

bugfix: Don't search for stacktrace line if at word is not present

---

build.sbt

Since it seems we can't just remove the explicit dependencies let's at least use the usual way of not bringing in transitive dependencies.

chore: Try to use intransitive instead

---

project/V.scala
tests/unit/src/test/scala/tests/worksheets/WorksheetLspSuite.scala

Fixes https://github.com/scalameta/metals/issues/6499 and https://github.com/scalameta/metals/issues/6500

chore: Update mdoc to 2.5.4

---

metals/src/main/scala/scala/meta/internal/metals/MtagsResolver.scala

I totally forgot that the current state is from 3.3.4 full versions and we count 3.3.4-RC1 as being before it.
Will release separate for the last two metals versions

chore: Add support for Scala 3.3.4-RC1

---

metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala

fixes: https://github.com/scalameta/metals/actions/runs/10003222130/job/27649766803#step:4:1457
It seems `sourceBuildTargets` returns something mutable.

fix: by-max on empty

---

metals/src/main/scala/scala/meta/internal/metals/BloopDir.scala

It seems there is a race when shutting down and some directories are also being deleted by Bloop. The retry should be enough to help out.
Fixes https://github.com/scalameta/metals/issues/6612

bugfix: Retry deleting Bloop folders

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/MunitTestFinder.scala
tests/unit/src/test/scala/tests/testProvider/TestSuitesProviderSuite.scala

Previously, we would treat any string literal inside the apply of a test function as a name of such function, but each test name can actually be any kind of expression, so we would not detect the correc tname always.
Now, we only detect names of tests if they are of an expected format, either simple string, select or a tag.
Fixes https://github.com/scalameta/metals/issues/6617

bugfix: Only detect 100% sure test names

---

build.sbt
project/V.scala

Turns out sbt reports a bunch of warnings in this case and there is no other way to deal with it :/

improvement: Move jdt dependencies outside of build.sbt

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/codelenses/RunTestCodeLens.scala
metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClassesFinder.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugDiscovery.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DiscoveryFailures.scala
tests/unit/src/test/scala/tests/DebugDiscoverySuite.scala
tests/unit/src/test/scala/tests/DebugProtocolSuite.scala

Previously, it was not possible to get a command to run if one only input the main class name. Now it works the same as a discovery of main class to run within a file.
Fixes https://github.com/scalameta/metals/issues/6239

improvement: Also run from Java when running from config

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/ParamDefinitionCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionKeywordSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

resolves: https://github.com/scalameta/metals/issues/6623

fix: don't suggest completions for param names in definition

---

tests/slow/src/test/scala/tests/feature/CrossReferenceSuite.scala
tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
tests/unit/src/main/scala/tests/BaseLspSuite.scala
tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
tests/unit/src/test/scala/tests/FileWatcherLspSuite.scala
tests/unit/src/test/scala/tests/SingleFileSuite.scala

Thanks to this we should get less timeouts as we will not try to resolve Scala 3, which will not be available anyway.

improvement: Fall back to current Scala version in unit tests

---

metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
tests/unit/src/test/scala/tests/best-effort/BestEffortCompilationSuite.scala

Looks like sometimes best effort artifacts are being produced despite the fact that compilation finished successfully. I think this actually causes downstream module to fail the compilation.
I've put it into server config mostly because I don't really want users to have to tinker with that. Once it works it should be enabled always.
Helps with https://github.com/scalameta/metals/issues/6628

bugfix: Disable best effort compilation by default

---

mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionValue.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala

resolves: https://github.com/scalameta/metals/issues/6622

fix: disambiguate workspace completions for vals in Scala 3

---

metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala

Previously, we would wait for full compilation for debugger and scalafix, however that is not needed, we only need to compile the current target in that case.
Now, we specify it explicitly.
The change is really small, ignore whitespaces option will show it.

improvement: Specifically choose which targets to compile

---

metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala

Empty array is a default value, so this would start Bloop with no options as default.

bugfix: Use default bloop properties if provided empty array

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionBuilder.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/OrganizeImports.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/codeactions/OrganizeImportsLspSuite.scala

Rather than having Metals show a warning message, leave it to the client to decide on what to do with the reason for why they are disabled, and if/how it should be displayed.
Fixes https://github.com/scalameta/metals-zed/issues/14
Then it looks like this in VS Code:

Disable OrganizeImports commands if they are not available

---

metals/src/main/scala/scala/meta/internal/metals/FallbackDefinitionProvider.scala
mtags-shared/src/main/scala/scala/meta/internal/mtags/KeywordWrapper.scala
mtags/src/main/scala/scala/meta/internal/mtags/Symbol.scala
tests/slow/src/test/scala/tests/feature/DefinitionCrossLspSuite.scala

Couple of related improvements:
- escape operators, they are escaped for semanticdb symbols ( otherwise ??? will not be found)
- add standard Scala imports (needed for scala.Predef.`???`().)
- also try and guess method with (). ending
- check if the returned symbol is exactly the same as we were looking for (could not reproduce it 100% the same as I encountered in the wild, but it's close enough)

improvement: Further heuristic improvements

---

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcDefinitionProvider.scala

resolves: https://github.com/scalameta/metals/issues/6680
We use presentation compiler to find the definition of this symbol. (This happens also if using semanticdb the found symbol isn't exactly as expected). Since this is a jar `InteractiveDriver.toUriOption(pos.source)` did not return correct full uri but only `/com/monovore/decline/opts.scala`.

fix: use uri from params in pc for location

---

mtags-shared/src/main/scala/scala/meta/internal/mtags/CoursierComplete.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliSuite.scala

resolves: https://github.com/scalameta/metals/issues/6700

fix: completions for using directive deps when test scope

---

website/docusaurus.config.ts
website/package.json
website/yarn.lock

- migrate [configuration file](https://docusaurus.io/docs/configuration#syntax-to-declare-docusaurus-config) to typescript to get editor support
- use [swc-loader](https://github.com/swc-project/pkgs/tree/main/packages/swc-loader), a drop-in webpack babel-loader replacement to improve build speed by ~16%.
| method            | babel-loader (default) | swc-loader (new)         |
| ----------------- | ---------------------- | ------------------------ |
| with minification | 46.22s                 | 38.59s (83% of original) |
| no minification   | 42.60s                 | 34.73s (81% of original) |
<details><summary>Log</summary>
```sh
$ yarn docusaurus clear
$ time yarn build --no-minify
[INFO] Use `npm run serve` command to test your build locally.
Done in 42.32s. …
```

docs(perf): use `swc-loader`

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

resolves: https://github.com/scalameta/metals/issues/6712

fix: index top level with inner when apply with `{ }` in method

---

mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
tests/cross/src/test/scala/tests/pc/Release11CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/Release8CompletionSuite.scala

bugfix: Allow -release flag for Scala 3

---

metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClasses.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
metals/src/main/scala/scala/meta/internal/metals/debug/server/DebugeeParamsCreator.scala
metals/src/main/scala/scala/meta/internal/metals/debug/server/MainClassDebugAdapter.scala
metals/src/main/scala/scala/meta/internal/metals/debug/server/TestSuiteDebugAdapter.scala

resolves: https://github.com/scalameta/metals/issues/6714

fix: get correct classpath for running debug

---

mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala
mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala

One file failing to tokenize should not cause the entire jar to not be tokenized.
This was prompted by /doobie/free/kleisliinterpreter.scala which was ended in the middle inside the sources.
Fixes https://github.com/scalameta/metals/issues/6717

improvement: Ignore single failing file

---

build.sbt

Should fix https://github.com/scalameta/metals/issues/6694
I am not super sure why this doesn't actually break for me or the CI, but anyway this should work correctly now.

bugfix: Set semanticdb version correctly

---

metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala

~~Some distributions seem to require this to work, so it's safer to include it by default.~~
I reworked it, since the problem was actually different, we used wrong Java home, which might have been older.

bugfix: Use metals Java versions as default

---

metals-bench/src/main/scala/bench/SemanticTokensBench.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticTokensProvider.scala
tests/slow/src/test/scala/tests/feature/SemanticTokensScala3ExpectSuite.scala
tests/unit/src/main/scala/tests/MetalsTestEnrichments.scala
tests/unit/src/test/scala/tests/SemanticTokensExpectSuite.scala

It seems if we throw too much this will cause the extension to think metals is unresponsive.
Using tokens from the last parsing code should work ok enough in that case.
Fixes https://github.com/scalameta/metals/issues/6699

improvement: Fallback to last successful tokens instead of throwing

---

mtags/src/main/scala-2/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/WorkspaceSymbolSearch.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompilerSearchVisitor.scala
tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
tests/cross/src/test/scala/tests/pc/ShadowingCompletionSuite.scala
tests/slow/src/test/scala/tests/feature/ImportMissingSymbolCrossLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala

Finer grained accessibility check for  auto-imports

---

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala

The upcoming version of Bloop will be using sbt 1.5.8 as a baseline with some keys only added in 1.5.x version.

chore: Freeze bloop plugin for versions of sbt lower than 1.5.8

---

metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
project/V.scala
tests/slow/src/test/scala/tests/feature/RenameCrossLspSuite.scala
tests/unit/src/main/scala/tests/BaseRenameLspSuite.scala

Some previous versions of Scala 3 would included the final comma in a parameters list, this should help out with that case.
Versions from 3.5.2 and onwards work correctly.
I also reworked the tests to try and rename in each place a symbol is expected, which should catch more errors and need less test cases. I will follow up with changes to RenameLspSuite
Related to https://github.com/scalameta/metals/issues/6795

bugfix: Exclude comma if included in symbol range

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala

Per spec https://build-server-protocol.github.io/docs/specification#diagnostic:
```
/** The diagnostic's severity. Can be omitted. If omitted it is up to the
* client to interpret diagnostics as error, warning, info or hint. */
severity?: DiagnosticSeverity;
```
Defaulting to warn

Avoid NPE when no severity is supplied in PublishDiagnosticsParams.Diagnostic

---

metals/src/main/scala/scala/meta/internal/metals/SqlSharedIndices.scala

see #6801
It can be easily modified to fit specific project requirements, but the main idea is to follow the XDG Base Directory Specification, which Metals already does in most places except for this `SqlSharedIndices` class.
Update: I have used directories-jvm in the updated version, which was already present in the project. The SQL shared indices will be preserved across different platforms.
_NOTES: maybe `MetalsProjectDirectories` should be used instead of `ProjectDirectories`, see [bugfix: Don't hang on ProjectDirs](https://github.com/scalameta/metals/pull/6763/commits/6c2cbd07f50e8adb9d67512dbf75c6509b8416bb#diff-9eb2283d351d794e495756c6ec5effb0efa2c9740d86f7fa45dd6fa415ddff0e)_

bugfix: Metals `SqlSharedIndices.scala` XDG path violation

---

metals/src/main/scala/scala/meta/internal/metals/MtagsResolver.scala

The compiler doesn't publish presentation compiler for nonbootstrapped version, but it should work fine with bootstrapped one. It's mainly needed in scaladoc.

improvement: Use bootstrapped compiler always

---

metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsProjectDirectories.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerInputs.scala
metals/src/main/scala/scala/meta/internal/metals/Trace.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
metals/src/main/scala/scala/meta/metals/Main.scala
project/TestGroups.scala
tests/slow/src/main/scala/tests/scalacli/BaseScalaCLIActionSuite.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliActionsSuite.scala
tests/unit/src/main/scala/tests/Library.scala
tests/unit/src/main/scala/tests/codeactions/BaseCodeActionLspSuite.scala

It seems in rare scenarios it's possible that the method ProjectDirs.from will hang. To fix that I wrapped it in a Future and added some fallbacks.
Not sure if this will fix everything, but that's my best try.
Should help with https://github.com/scalameta/metals/issues/6762

bugfix: Don't hang on ProjectDirs

---

metals/src/main/scala/scala/meta/internal/metals/SbtOpts.scala
tests/unit/src/test/scala/tests/SbtOptsSuite.scala

I couldn't find any information about how .sbtopts should look like, but splitting on space should be ok. Especially that with spaces this doesn't work -> https://github.com/sbt/sbt/issues/7333
Fixes https://github.com/scalameta/metals/issues/6858

bugfix: Take into account space in sbtopts

---

metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsProjectDirectories.scala
metals/src/main/scala/scala/meta/internal/metals/Trace.scala

We were printing error to standard output which was interfering with LSP messages since metals.log was being set
Fixes https://github.com/scalameta/metals/issues/6762

bugfix: Fix not hanging on ProjectDirs

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ConvertToNamedArguments.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractMethodCodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ImplementAbstractMembers.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/InlineValueCodeAction.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/InsertInferredType.scala
mtags-interfaces/src/main/java/scala/meta/pc/CodeActionId.java
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala

I think we were still not perfect with the interfaces, some changes I did:
- I changed the default value to empty, which now makes it easy to see which methods migrated to the new interface method.
- removed maybeCodeActionId from code actions that we know can be handled otherwise
- added a CodeActionId class to gather all known classes once we agree on adding soemthing, can still be implemented separately
This added some duplication, since for older Scala version we need to use the older methods, but anything new should now be quite easy to handle.
So not so useful for older things, but still it's good to migrate to new codeAction interface.
@KacperFKorban What do you think?

refactor: Use codeAction interface for most code actions

---

metals/src/main/scala/scala/meta/internal/metals/CompilerConfiguration.scala

I noticed some issues with Scala 2.13.15 and I am not sure how to work around it. This can be worked around if the user needs it as Metals does work with 17 and up. 
I have not noticed the same issues with JDK <17
For reference:
- https://github.com/scala/bug/issues/13045
- https://github.com/scalameta/metals/issues/5272

improvement: Don't add release flag for versions from 17

---

build.sbt
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompiler.java

This is needed by the Scala 3 compiler.

bugfix: Publish interfaces and  mtagsShared for JDK 8

---

metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
tests/unit/src/test/scala/tests/ReferenceLspSuite.scala

I think we did it previously on purpose, but it seems it's mostly just confusing to users.
Fixes https://github.com/scalameta/metals/issues/6776

improvement: Always find all references

---

.github/workflows/ci.yml
tests/unit/src/main/scala/tests/BaseRangesSuite.scala
tests/unit/src/main/scala/tests/BaseRenameLspSuite.scala
tests/unit/src/main/scala/tests/FileLayout.scala
tests/unit/src/main/scala/tests/MetalsTestEnrichments.scala
tests/unit/src/test/scala/tests/ReferenceLspSuite.scala

We should check if references find the same amount of references when invoked at each occurrence. This will avoid having to write multiple tests differing in just @@ and make sure that the references are found reliably.

improvement: Check all references at the same time

---

mtags/src/main/scala-2/scala/meta/internal/metals/URIEncoderDecoder.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
tests/unit/src/test/scala/tests/UriEncoderDecoderSuite.scala

Should help with https://github.com/scalameta/metals/issues/6655

bugfix: Properly escape jar: paths

---

website/docusaurus.config.ts
website/package.json

This PR updates Docusaurus to version 3.6.0, introducing many build tool improvements.
For details: https://docusaurus.io/blog/releases/3.6

docs: Upgrade Docusaurus to Version 3.6.0

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractMethodCodeAction.scala
mtags/src/main/scala/scala/meta/internal/metals/TextEdits.scala
tests/cross/src/test/scala/tests/pc/ExtractMethodSuite.scala
tests/unit/src/test/scala/tests/codeactions/ExtractMethodLspSuite.scala

I must have missed the add Template Body

bugfix: Fix extract function not showing up

---

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/InlayHintResolveProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
metals/src/main/scala/scala/meta/internal/metals/SemanticTokensProvider.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/ReportContext.scala
mtags-shared/src/main/scala/scala/meta/internal/pc/CompilerAccess.scala
mtags/src/main/scala-2/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala/scala/meta/internal/mtags/JavaToplevelMtags.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/unit/src/test/scala/tests/ReportsSuite.scala

Otherwise, if a wrong string is used we will get an exception, which has already happened in the wild.

improvements: Explicitly use URI instead of string

---

metals/src/main/scala/scala/meta/internal/metals/ChosenBuildTool.scala

When researching https://github.com/scalameta/metals/issues/6950#issuecomment-2489515847
I found that this atomic it is touched twice, even it just attempts to write the value it obtained already. That doesn't seem right.
With this fix, if the atomic has a value it will take a faster path out.

improvement: avoid atomic double touch if not needed

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala

When choosing a default folder to start a BSP connection and failing to obtain one from the build tool, respect customProjectRoot setting before defaulting to workspace.
Fixes https://github.com/scalameta/metals/issues/6950
So the the proposal mentioned [here](https://github.com/scalameta/metals/issues/6950#issuecomment-2489515847) doesn't fly, because it seem like it never gets to writing the build tool.
Yet, I figured that the user settings are available where the Bloop-default folder is decided. So at that point, respecting the setting (if configured) seems only fair.
(I verified with a local build that indeed solves the problem)

bugfix #6950:respect customProjectRoot in BspConnector

---

metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
metals/src/main/scala/scala/meta/internal/metals/StandaloneSymbolSearch.scala
metals/src/main/scala/scala/meta/internal/metals/TargetData.scala
metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala
tests/unit/src/main/scala/tests/MetalsTestEnrichments.scala
tests/unit/src/test/scala/tests/DefinitionSuite.scala
tests/unit/src/test/scala/tests/ScalaVersionsSuite.scala

For jars if no scala version included in the path, fallback to using scala version from build target before defaulting to "2.13".
resolves: https://github.com/scalameta/metals/issues/6693

improvement: if no binary version in jar path try using build target info

---

metals/src/main/scala/scala/meta/internal/metals/PresentationCompilerClassLoader.scala
tests/unit/src/test/scala/tests/ClassloaderModulesSupport.scala

Fixes https://github.com/scalameta/metals/issues/6494
Fixes https://github.com/scala/scala3/issues/20560
We've found that classloader used to load presentation compiler is defined as follows:
```scala
package scala.meta.internal.metals
/**
* ClassLoader that is used to reflectively invoke presentation compiler APIs.
*
* The presentation compiler APIs are compiled against exact Scala versions of the compiler
* while Metals only runs in a single Scala version. In order to communicate between Metals and the
* reflectively loaded compiler, this classloader shares a subset of Java classes that appear in
* method signatures of the `PresentationCompiler` class.
*/
class PresentationCompilerClassLoader(parent: ClassLoader)
extends ClassLoader(null) {
override def findClass(name: String): Class[_] …
```

Presentation Compiler is now loaded with correct classloader

---

metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
mtags-interfaces/src/main/java/scala/meta/pc/PresentationCompilerConfig.java
mtags-shared/src/main/scala/scala/meta/internal/pc/CompilerInitializationOptions.scala
mtags-shared/src/main/scala/scala/meta/internal/pc/PresentationCompilerConfigImpl.scala
mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/completions/CompletionProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionWithoutDetailsSuite.scala

Some LSP clients (such as Emacs using Eglot and Corfu) use the label field to insert a completion if `completionItem/resolve` has not returned by the time the completion is selected. Including the contents of the detail property in the label causes it to be included in the file itself in these clients. To remedy this, we define a `isDetailIncludedInLabel` option under `compilerOptions` to make this behaviour toggleable. We also disable this behaviour by default in Emacs, since this is where the undesirable behaviour was located.
TODO:
Fixes #6849.

improvement: Make including detail in completion label configurable

---

mtags-shared/src/main/scala/scala/meta/internal/metals/ProxySymbolDocumentation.scala
mtags/src/main/scala-2/scala/meta/internal/pc/CompletionItemResolver.scala
mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala-3/scala/meta/internal/pc/CompletionItemResolver.scala
mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala
mtags/src/main/scala/scala/meta/internal/mtags/DefinitionAlternatives.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalametaCommonEnrichments.scala
mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala
tests/cross/src/main/scala/tests/pc/BaseHoverSuite.scala
tests/cross/src/test/scala/tests/hover/HoverScala3TypeSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala

fixes: #6852
A toplevel object that is a companion for a top-level type has a synthetic parent - `filename$package`. This is not reflected by Metals symbol indexer (`ScalaMtags`).  It would be problematic, since the the type definition might be after the object definition
For this code:
```demo.scala
// demo.scala
object Foo
type Foo = String
```
Symbols in compiler and what is in semanticDB is
```
_empty_/demo$package.Foo#
_empty_/demo$package.Foo.
```
Where Metals symbol indexer produces:
```
_empty_/demo$package.Foo#
_empty_/Foo.
```
1. Add symbols with `filename$package` to alternatives in definition search
2. When searching for docstring fallback to docs from found definition symbol

fix: use alternative with stripped synthetic `filename$package.`

---

metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/InlayHintResolveProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
mtags-shared/src/main/scala/scala/meta/internal/pc/InlayHints.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcInlayHintsProvider.scala
tests/mtest/src/main/scala/tests/TestInlayHints.scala
tests/unit/src/main/scala/tests/BaseInlayHintsExpectSuite.scala

resolves: https://github.com/scalameta/metals/issues/6968

improvement: make `inlayHints/resolve` not depend on focused document

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeExtractor.scala
metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeProvider.scala
metals/src/main/scala/scala/meta/internal/parsing/JavaFoldingRangeExtractor.scala
tests/unit/src/test/resources/foldingRange-scala3-foldLineOnly/expect/Main.java
tests/unit/src/test/resources/foldingRange-scala3-foldLineOnly/expect/i6938.scala
tests/unit/src/test/resources/foldingRange-scala3-foldLineOnly/input/Main.java
tests/unit/src/test/resources/foldingRange-scala3-foldLineOnly/input/i6938.scala
tests/unit/src/test/resources/foldingRange-scala3/expect/BlockWithNoBraces.scala
tests/unit/src/test/resources/foldingRange/expect/Blocks.scala
tests/unit/src/test/resources/foldingRange/expect/ForLoop.scala
tests/unit/src/test/resources/foldingRange/expect/ForYield.scala
tests/unit/src/test/resources/foldingRange/expect/Literals.scala
tests/unit/src/test/resources/foldingRange/expect/Main.java
tests/unit/src/test/resources/foldingRange/expect/PartialFunctionCases.scala
tests/unit/src/test/resources/foldingRange/expect/Try.scala
tests/unit/src/test/resources/foldingRange/input/Main.java
tests/unit/src/test/scala/tests/FoldingRangeSuite.scala

- don't merge region with parent when if parent too small without it
- allow to configure folding region threshold using server properties
- make threshold work consistently
resolves: https://github.com/scalameta/metals/issues/6938

improvement: thresholds for folding regions

---

mtags/src/main/scala-3/scala/meta/internal/pc/MetalsInteractive.scala
tests/cross/src/test/scala/tests/hover/HoverTermSuite.scala

Connected to: https://github.com/scalameta/metals/issues/7012
upstream issue: https://github.com/scala/scala3/issues/22207 (I'm not even sure what would be a proper solution here).

fix: workaround for hover for multi declaraction (Scala 3)

---

.github/workflows/ci.yml
build.sbt
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
project/V.scala
sbt-metals/src/sbt-test/sbt-metals/semanticdb/build.sbt
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala

I'm not 100% sure what I'm doing, but let's see...

Cross-build sbt-metals for sbt2

---

mtags/src/main/scala-2/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SignatureHelpProvider.scala

https://github.com/scalameta/metals/issues/6921

fix: scala 2 additional checks

---

metals/src/main/scala/scala/meta/internal/metals/StatusBarConfig.scala
tests/unit/src/test/scala/tests/ServerLivenessMonitorLspSuite.scala

Turns out it was actually set in a totally different place, which I haven't realized.
Fixes https://github.com/scalameta/metals/issues/6988

bugfix: Log message by default

---

metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala

This PR refactors the `validateWorkspace` function to gracefully handle missing `scalafmtConfigPath` files. Previously, this scenario would result in uncaught exceptions. 
```console
2024.12.31 11:48:07 ERROR Failed to connect with build server, no functionality will work.
java.nio.file.NoSuchFileException: {dir}/akka-quickstart-scala/.my_scalafmt.conf
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
at java.nio.file.Files.newByteChannel(Files.java:380)
at java.nio.file.Files.newByteChannel(Files.java:432)
at …
```

Refactor `validateWorkspace` to handle missing custom `scalafmtConfigPath` gracefully and log warning

---

metals-bench/src/main/scala/bench/MetalsBench.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/ReportContext.scala
mtags/src/main/scala-2/scala/meta/internal/mtags/MtagsEnrichments.scala
mtags/src/main/scala/scala/meta/internal/metals/Docstrings.scala
mtags/src/main/scala/scala/meta/internal/metals/JavadocIndexer.scala
mtags/src/main/scala/scala/meta/internal/mtags/JavaMtags.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalametaCommonEnrichments.scala

connected to: https://github.com/scalameta/metals/issues/7034

improvement: report QDox errors

---

mtags-shared/src/main/scala/scala/meta/internal/metals/ReportContext.scala

Quite commonly when we start getting an error report we keep getting the same one over and over again. This PR deduplicates error reports using hash on stack traces.

improvement: deduplicate reports

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

This case used to throw an exception, leading to no completions (and a crash report). Looks like just another unaccounted for variation of how method calls with default arguments are desugard by the presentation compiler.
Fixes #7088

bugfix: completion of args in method w/ default args

---

metals-docs/src/main/scala/docs/WorksheetModifier.scala

The docs have an extra `$` when showing the syntax for worksheet imports, probably leftover from a time when this was an interpolated string? 
Let me know if there's something I would need to do to help with getting this change published to the site if/when this is merged, I didn't see anything about updating the docs site itself in the contributing guidelines.

docs: fix syntax for worksheet imports

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala

On the original `initialized` message, we call `setUserConfig` to set the configuration gotten from `workspace/configuration`, but we weren't updating `excludedPackageHandler`. That would lead to the original config of `excludedPackages` being basically ignored.
The buggy behaviour might be masked depending on whether `initialized` or `workspace/didChangeConfiguration` set settings first. Those messages get sent by the LSP client in quick succession, so it is a toss up which reaches the config code first.
- if `workspace/didChangeConfiguration` logic got there first, it would update the `excludedPackageHandler` and correct behaviour would be observed
- if `initialized` logic got there first, it would update the config, but not the `excludedPackageHandler`, which would mean when the other …

bugfix: fix incorrect `excludedPackages` on startup

---

metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/FallbackDefinitionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/TargetData.scala
metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcDefinitionProvider.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala

resolves: https://github.com/scalameta/metals/issues/7027

improvement: use pc for go to def when stale semanticdb

---

metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala
tests/unit/src/test/scala/tests/NewFileLspSuite.scala
tests/unit/src/test/scala/tests/RenameFilesLspSuite.scala

This tweaks the package inference logic in `PackageProvider` to support the case where the directory structure is missing a common prefix of the package structure.
Implements scalameta/metals-feature-requests#414

Infer base package in `PackageProvider`

---

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
project/V.scala

Fix #7115
Also sbt-jdi-tools is now published with correct Maven pattern

update scala-debug-adapter and sbt-jdi-tools

---

bin/test.sh
build.sbt
mtags/src/main/scala-3/scala/meta/internal/pc/PcDefinitionProvider.scala

https://github.com/scalameta/metals/issues/7095

improvement: look for definition in pc only for local symbols in the current tree

---

mtags-shared/src/main/scala/scala/meta/internal/metals/PcQueryContext.scala
mtags-shared/src/main/scala/scala/meta/internal/pc/CompilerAccess.scala
mtags/src/main/scala-2/scala/meta/internal/pc/AutoImportsProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ExtractMethodProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/HoverProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/InferredMethodProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/InferredTypeProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaCompilerAccess.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SignatureHelpProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/Signatures.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala
mtags/src/main/scala-3/scala/meta/internal/pc/Scala3CompilerAccess.scala
mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala

resolves: https://github.com/scalameta/metals/issues/7091
I added `PcQueryContext` class, so it can be implicitly passed between pc methods. This way we can easily create and error report with all the context information from any place in the presentation compiler.

improvement: don't fail on `shortType`

---

build.sbt

It seems this commit: https://github.com/scalameta/metals/pull/7105/commits/2c9cf5e988c5d6c8dc95939441427f90ef922b63 
broke release https://github.com/scalameta/metals/actions/runs/12948583151/job/36117533530, since sonatype requires javadoc.
This PR doesn't simply revert the change but makes an empty scaladoc for all modules (previously only that was the case for mtags).

fix: publish empty scaladoc

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcDefinitionProvider.scala
tests/cross/src/test/scala/tests/typedef/TypeDefinitionSuite.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala

One of the short-circuiting conditions in the type definition logic was a bit too broad, leading to `typeDefinition` not returning a result if the position queried happened to precede a space in an identifier (see the test that was added).

bugfix: fix `typeDefinition` on backticked identifier

---

mtags/src/main/scala-2/scala/meta/internal/pc/InferredMethodProvider.scala
tests/cross/src/test/scala/tests/pc/InsertInferredMethodSuite.scala

Previously, we would try to find the generic signature of the object we invoked the method on, which would not work in a lot of cases. Now, we find the proper method type.

bugfix: Properly print method type

---

mtags/src/main/scala-2/scala/meta/internal/pc/InferredMethodProvider.scala
tests/cross/src/test/scala/tests/pc/InsertInferredMethodSuite.scala

Fixes https://github.com/scalameta/metals/issues/6954

bugfix: Infer arg type properly when complex

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ExtractValueCodeAction.scala
tests/unit/src/test/scala/tests/codeactions/ExtractValueLspSuite.scala

Resolves https://github.com/scalameta/metals/issues/7138

Fix extracting values for fewer braces

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceFolders.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
tests/slow/src/test/scala/tests/gradle/GradleLspSuite.scala

(e.g. import build) also assume, that workspace folder is Metals project if it contains `.bloop` folder
resolves: #7031

improvement: convert workspace folder to be a Metals project on chosen commands

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Previous behaviour would throw an exception, leading to no completions. This is just another unaccounted way in which methods with default args can be desugared.

bugfix: completion in args in generic method w/ default args

---

tests/unit/src/main/scala/scala/meta/internal/metals/debug/TestDebugger.scala

It seems it might sometimes fail when disconnecting, but that is not a huge deal
It happened in multiple recent PRs and it seems only flaky, not really reproducible

bugfix: Don't fail on broken pipe

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

Directly accessing `CompletionResult.ScopeMembers.results` bypasses accessibility and similar checks. Going through `matchingResults` ensures we get the same validation we'd get in other scope-based completion contexts.
Before this patch, the newly added test would propose the invalid completion
foo(arg = somePackagePrivStr)

bugfix: don't propose inaccessible named arg defaults

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

In the added test case, the previous behaviour would've been to complete to `Foo.overloaded` instead of just `overloaded`. This was because the effective owner of `overloaded` was `Foo` instead of `Bar`. Since those were not the same symbol, the logic for determining the prefix would incorrectly add a `Foo` prefix to the completion.
By augumenting the equality check to be a subtyping check, we ensure that we don't add prefixes to completions coming from supertype scopes.

bugfix: don't prefix scope completions from supertype

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcRenameProvider.scala
mtags/src/main/scala-3/scala/meta/internal/pc/PcRenameProvider.scala
tests/cross/src/test/scala/tests/pc/PcRenameSuite.scala

I noticed that sometimes rename worked on symbols not within the local scope and these checks should help.

chore: Check name when renaming

---

mtags-shared/src/main/scala/scala/meta/internal/metals/ReportContext.scala

Logging error report creation with `severe` makes users feel like something broke badly, where in most cases it only points to a single operation issue, that doesn't affect overall Metals's performance.

improvement: when logging error report creation use `warning` instead  of `severe`

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala
tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala

I've added safety null checks for cases where symbol information could be missing (triggered for example by shapeless Generic macros).
I default to showing the type of the tree or, if that is missing too, just a static placeholder.
I've also added a test that uses Shapeless to verify the fix. (Unfortunately I wasn't able to reproduce the bug any other way.)

bugfix: fix Scala 2 NPE in implicit inlay hints

---

mtags/src/main/scala-2/scala/meta/internal/pc/AutoImportsProvider.scala
tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala
tests/slow/src/test/scala/tests/scalacli/ScalaCliActionsSuite.scala
tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala

For now it's a small improvement, I tried some other cases, but for example if we have rhs that we want to check the type for it's currently impossible when the lhs type is not imported. 
Inserting the import and rechecking would be too costly in the auto imports context unfortunately.

improvement: Only show symbol import if static method exists

---

metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DiscoveryFailures.scala

This improves the error message for main classes discovery in a way that would have helped us in a problem we encountered. The old error message said:
`a.b.c.OurClass not found in any build target`
The new one says
`Main class '$className' not found in build target '${buildTarget}' (not considering dependencies)`
Giving away that the code actually did not ignore the build target we provided, only considered main classes, but not from dependencies. We tried to run a main class from a dependency, but it wasn't immediately clear why it didn't work.

improve error messages when no main classes can be found

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala

This tweaks the case-completion logic to always take auto-imports into account. The auto-import logic was present for known direct subclasses, but not for some other cases. Now, they all get handled uniformly.
The only hair in the soup is that extra work needs to go in to
def myList: List[Int]
myList match {
case N@@   // want `case Nil =>`, not `case immutable.Nil =>`
}
Reason here is that the `Nil` variant is completing with `scala.collection.immutable.Nil`, while only `scala.Nil` is in scope. The `scala.*` package re-exports are narrowly worked around since they probably would occur frequently.

fix: generate auto-imports for more pattern completions

---

mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/MatchCaseCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionPatternSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionSuite.scala

This ensures that scope-based completions show up in a pattern context, even if the symbol to complete is the same as the one underlying a pattern completion (see the `underscore-and-object` test added)
This is achieved by putting case pattern completions in a new completion member with its own dedup-ing `id`.
Although it turned out to not matter in this specific case, also fixed `inverseSemanticdbSymbol` incorrectly returning an object symbol for some class symbols. That tweak on its own didn't affect any test output.
fixes #7291

fix: colliding pattern and scope completions

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala

This allows clients to force compilation and await completion in order to mitigate races against compilation.
This is required for this metals-vscode PR: https://github.com/scalameta/metals-vscode/pull/1607

improvement: add CompileTarget server command

---

metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
tests/unit/src/test/scala/tests/DebugProtocolSuite.scala

Show client error message and suggest opening diagnostics view when trying to debug a workspace with compile errors.
Meant to be released in conjunction with https://github.com/scalameta/metals-vscode/pull/1601

Suggest open diagnotics for debug compile errors

---

metals/src/main/scala/scala/meta/internal/metals/scalacli/DependencyConverter.scala
tests/unit/src/test/scala/tests/rangeFormatting/ScalaCliDependencyRangeFormatter.scala

https://github.com/scalameta/metals/pull/7176 was not working for `test.dep`.
see: https://scala-cli.virtuslab.org/docs/guides/introduction/dependencies#test-dependencies

feat: convert sbt style deps on paste in for scala-cli test.dep

---

metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala

I am not sure actually why we were creating a new diagnostic, but we should not need to and any time anything new is added we will automatically support it.
I don't think the new fields are supported yet, but anyway this should be a simple fix.
Related to https://github.com/scalameta/metals-feature-requests/issues/424

improvement: Forward all LSP data from BSP

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcCollector.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcRenameProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/WithCompilationUnit.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala

toSemanticdb method is not thread safe and could cause multiple local symbols to have the same local name assigned. I removed usage of it from collectors since it seems it wasn't needed. ~I also added synchronized, since otherwise we can have weird issues all over the place. We should also try not to use it.~ I removed that, I think most other usages do not have the same issue. We could remove more usages of semanticdb method later if needed

bugfix: Fix issues when we would rename more symbols

---

metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala
tests/unit/src/test/scala/tests/codeactions/CreateNewSymbolLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala

When importing symbols in a range it might turn out we are able to get a better suggestions in a certain spot in the file.
For example if we know that one object has a specific method while the other doesn't.
This means that this import is better for the entire file since it's more concrete.
Previously, we would still show all options, but now search for the shortest action choice for each missing symbol.

bugfix: Make sure to choose the best import option

---

.github/workflows/ci.yml
.scalafmt.conf
build.sbt
project/V.scala
sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala
sbt-metals/src/sbt-test/sbt-metals/semanticdb/build.sbt
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala

Follows https://github.com/scalameta/metals/pull/7045
- https://github.com/sbt/sbt/issues/7956 was fixed
- Bloop is [still not cross-built](https://github.com/scalacenter/bloop/issues/2455) so sbt BSP must be used
- https://github.com/scalacenter/scala-debug-adapter cannot be re-enabled, it's still not cross-built

sbt-metals: publish for & test against 2.0.0-M4

---

metals/src/main/scala/scala/meta/internal/metals/WorkspaceSearchVisitor.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
mtags/src/main/scala/scala/meta/internal/mtags/GlobalSymbolIndex.scala
mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala
mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala
tests/mtest/src/main/scala/tests/DelegatingGlobalSymbolIndex.scala

In `WorkspaceSearchVisitor` we used `definition` to find the source file for the class file. This unnecessarily causes an indexing of that file. Since we use toplevel symbol for that search anyway, now we just look for the path in indexes avoiding unnecessary steps.

improvement: deduplicate file indexing in classfile symbol search

---

.github/workflows/release.yml

https://eed3si9n.com/back-publishing-actually/#sbt-pgp-231-is-back-published-to-sbt-200-m3
I attempted to backpublish https://github.com/scalameta/metals/pull/7340 via https://github.com/scalameta/metals/releases/tag/v1.5.2%403.x%40sbt-metals%2FpublishSigned%23sbt2.0.0-M4, but the github action did not start.

allow backpublishing with sbt-ci-release

---

.github/workflows/release.yml

Follows https://github.com/scalameta/metals/pull/7342#issuecomment-2757053512 & https://github.com/scalameta/metals/pull/7340#issuecomment-2757033907
See https://eed3si9n.com/tag-based-back-publishing-with-sbt/.
For example, to publish mtags v1.3.5 against 2.13.16, we should now push the tag `v1.3.5@2.13.16@mtags/publishSigned@mtagsShared/publishSigned`.

remove mtags backpublishing adhoc code

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/ScalatestTestFinder.scala
tests/unit/src/test/scala/tests/testProvider/ScalatestFinderSuite.scala

When using metals I found that many of my test suites would not pick up the individual test cases. After some debugging I figured out that they extend different traits and while they are the same as AnyWordSpec in structure they do not directly extend it or AnyWordSpecLike. 
I have added the additional WordSpec types that exist in the current ScalaTest so that test cases get correctly picked up.

improvement: add additional ScalaTest WordSpec types

---

mtags/src/main/scala-2/scala/meta/internal/pc/HoverProvider.scala
tests/unit/src/test/scala/tests/HoverLspSuite.scala

Identifiers that need backticks should have the hover code-snippet signature preview render with those backticks.

fix: add backticks in hover output when needed

---

metals/src/main/scala/scala/meta/internal/metals/FileDecoderProvider.scala
metals/src/main/scala/scala/meta/metals/DownloadDependencies.scala

This makes sure running the decompile actions work without internet access.

feat: add CFR dep to `DownloadDependencies`

---

mtags/src/main/scala-2/scala/meta/internal/pc/SignatureHelpProvider.scala
tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala

The non-resolved signature in signature help needs to rely on the symbol information type for producing the right signature (as opposed to just looking at the call directly in the AST). However, this means that some care must be taken to show a specific type for the member if being seen from a type which can help further constrain the signature.

fix: show more precise signature help types

---

mtags/src/main/scala-2/scala/meta/internal/pc/completions/ArgCompletions.scala
tests/cross/src/test/scala/tests/pc/CompletionArgSuite.scala

What:
More intuitive arguments autofill
How:
The label for autofill was changed

improvement: improve arguments autofill

---

metals/src/main/scala/scala/meta/internal/metals/formatting/ScalaCliDependencyRangeFormatter.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/DependencyConverter.scala
tests/unit/src/test/scala/tests/rangeFormatting/ScalaCliDependencyRangeFormatter.scala

part 3 of sbt style identifier to scala-cli conversion (part 1: #7176, part 2: #7333)
defaults to `dep`

feat: infer dependency identifier on pasting sbt-style dependencies

---

metals/src/main/scala/scala/meta/internal/metals/ImportedBuild.scala
tests/slow/src/test/scala/tests/mill/MillServerSuite.scala

https://github.com/scalameta/metals/issues/7218
Metals was ignoring BuildTargets tagged with `no-ide`, in this PR, a new filtering criteria was added to filter out BuildTargets tagged with `no-ide` from the list of targets to be imported.
**Before** 
**After**

Respect LSP build target no-ide tag

---

metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
metals/src/main/scala/scala/meta/internal/metals/formatting/InterpolateStringContext.scala
metals/src/main/scala/scala/meta/internal/metals/formatting/MultilineString.scala
metals/src/main/scala/scala/meta/internal/metals/formatting/OnTypeFormattingProvider.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/formatting/OnTypeFormattingSuite.scala

Add an on-type formatter that looks for what looks like a string interpolation argument `${}` inside of a string and then converts the string into an interpolation.
Closes https://github.com/scalameta/metals-feature-requests/issues/425

feat: convert string to interpolation on `${`

---

mtags-shared/src/main/scala/scala/meta/internal/mtags/KeywordWrapper.scala
mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionBacktickSuite.scala

Completions will try to include backticks if they were present at the definition site (in addition to ensuring there are backticks when they are essential).
Closes https://github.com/scalameta/metals-feature-requests/issues/426

feat: completions respect backticks at defn site

---

metals/src/main/scala/scala/meta/internal/metals/PackageProvider.scala

resolves: https://github.com/scalameta/metals/issues/7336
(I couldn't write a tests that wouldn't pass before the the fix, so it's just tested manually)

fix: don't rename if old and new packages are the same for package object

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SelectionRangeProvider.scala
tests/cross/src/test/scala/tests/pc/SelectionRangeSuite.scala

Fixed #7398 by switching away from using anonymous subclasses of `SelectionRange`. Also tweaked a number of existing selection ranges:
- function application and type application lists now get their own selection range for the list (if it has length > 1)
- LHS name of a def now has its own selection range

fix & feat: improvements in selection ranges

---

metals/src/main/scala/scala/meta/internal/metals/scalacli/DependencyConverter.scala

previously, converter didn't work for directives such as `//> using compileOnly.deps @@` because `compileOnly.deps` weren't listed in `dependencyIdentifiers`.
generated with: https://github.com/scarf005/scala-cli-deps-directives

feat: add missing scala-cli deps identifiers

---

metals-bench/src/main/scala/bench/InlayHintsBench.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
metals/src/main/scala/scala/meta/internal/metals/InlayHintsOptions.scala
mtags-interfaces/src/main/java/scala/meta/pc/InlayHintsParams.java
mtags-shared/src/main/scala/scala/meta/internal/metals/CompilerInlayHintsParams.scala
mtags-shared/src/main/scala/scala/meta/internal/metals/CompilerSyntheticDecorationsParams.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala
tests/cross/src/main/scala/tests/BaseInlayHintsSuite.scala
tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala
tests/unit/src/main/scala/tests/BaseInlayHintsExpectSuite.scala

This adds `=>` hints for function parameters that are passed by name.
The common case of block by-name arguments moves the `=>` to occur right
after the opening brace instead of before the entire argument.
Implements <https://github.com/scalameta/metals-feature-requests/issues/377>

feat: add inlay hints for byname parameters

---

metals/src/main/scala/scala/meta/internal/metals/debug/DotEnvFileParser.scala
tests/unit/src/test/scala/tests/debug/DotEnvFileParserSuite.scala

During our trial of transition from IntelliJ to Metals, we discovered that some environment variables from our usual dotenv file (`envFile` in launch.json) were wrongly parsed, particularly as follows:
```bash
A=
B=value
LEVEL=WARN # this is noisy
```
Case 1 is trivially a bug. Case 2 is less obvious since it's actually tested against the current output in the test suite, but I believe the test is wrong given that it's parsed into the expected result well in bash, IntelliJ, and the recent `sbt-dotenv`.
This PR updates `DotEnvFileParser.LineRegex` to [that of the latest revision](https://github.com/Philippus/sbt-dotenv/blob/0210db3e3ec6242a4a108b4d3933c298ec64a368/src/main/scala/au/com/onegeek/sbtdotenv/SbtDotenv.scala#L132-L154) in [sbt-dotenv](https://github.com/Philippus/sbt-dotenv). …

fix(`DotEnvFileParser`): empty values or nonquoted values with comment

---

mtags/src/main/scala-2/scala/meta/internal/pc/PcInlayHintsProvider.scala
tests/cross/src/test/scala/tests/pc/InlayHintsSuite.scala

This makes sure we don't display an extra `=> ` for default byname arguments which the user never wrote. Ideally we would have a better way to check for default arguments, but it looks like like scalac only fairly recently added an annotation info to indicate that an apply argument is defaulted. Checking for an empty position is a fallback that should work on old versions as well.

fix: don't show byname hints for defaulted args

---

metals/src/main/scala/scala/meta/internal/metals/CompilerConfiguration.scala
metals/src/main/scala/scala/meta/internal/metals/Compilers.scala

Co-authored with @migoilee @rajcspsg on Scala Tooling Spree
Resolves https://github.com/scalameta/metals/issues/7378

Use fallback mtags and presentation compiler implementations in 2.12

---

tests/cross/src/test/scala/tests/hover/HoverPlaintextSuite.scala

fixes: https://github.com/scala/scala-dev/issues/903

tests: make HoverPlaintextSuite independent of stdlib Scaladoc

---

metals/src/main/scala/scala/meta/internal/builds/MillBuildTool.scala
tests/unit/src/test/scala/tests/MillVersionSuite.scala

With Mill 0.13/1.0, Mill support YAML frontmatter to configure the preferred Mill version.
```scala
//| mill-version: 1.0.0
```
This pull request add support for reading the Mill version from the YAML frontmatter in the main build script.
This change maintains the following precedence rules:
1. if exists, read `.mill-version`
2. if exists, read `.config/mill-version`
3. if exists, read YAML frontmatter of `build.mill`
4. if exists, read YAML frontmatter of `build.mill.scala`
5. if exists, read YAML frontmatter of `build.sc`
6. if exists, parse the `DEFAULT_MILL_VERSION` attribute from a local `mill` script
(Steps 3-5 are newly added in this PR.)
Additional, the `-jvm` suffix is stripped from the version, since it is used to denote, that Mill should not attempt to use a native launcher. …

feat: read the Mill version from YAML frontmatter of the buildfile

---

metals/src/main/resources/mill
metals/src/main/resources/mill.bat

This latest version of the official Mill bootstrap scripts for Posix Shells and Windows Batch Script support reading the preferred Mill version from the builfile. 
*Example: `build.mill`*
```scala
//| mill-version: 1.0.0
```
This version no longer support the `--mill-version` CLI option, which was deprecated for a very long time and never an offical CLI option of Mill.
Both scripts are able to handle all previously released stable Mill releases.

chore: update the mill scripts to version `0.13.0-M2-3-ba7090`

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
tests/unit/src/test/scala/tests/DebugProtocolSuite.scala

this way the client can distinguish them and show a better message only for this case. we then also no longer need the server emitted message which currently erroneously comes together with a second vscode default message

improvement: use specific jsonrpc code for compile errors

---

metals/src/main/scala/scala/meta/internal/metals/ScalacDiagnostic.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/CodeActionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala
metals/src/main/scala/scala/meta/internal/metals/codeactions/RemoveInvalidImport.scala
metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
mtags-shared/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
tests/unit/src/test/scala/tests/codeactions/ImportMissingSymbolLspSuite.scala
tests/unit/src/test/scala/tests/codeactions/RemoveInvalidImportLspSuite.scala

Add a new code action to faciliate removing invalid imports (or invalid parts inside of them). Note that this is only as good as the spans of the errors around the imports. For instance, since Scala 2.12 does not have <https://github.com/scala/scala/pull/10868>, some quickfixes will be missing there.
Implements <https://github.com/scalameta/metals-feature-requests/issues/431>

feat: code action to remove invalid imports

---

metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
tests/slow/src/test/scala/tests/mill/MillServerSuite.scala
tests/unit/src/main/scala/tests/TestingClient.scala

I run into this issue in https://github.com/scalameta/metals/pull/7440 with Mill tests.
If presentation compiler was before compilation finished and `<...>.dest` folder was created,
these entries would be removed from the classpath leading to incorrect classpath passed to the presentation compiler.

fix: don't remove non-existent entries from classpath

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/PcDefinitionProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/SignatureHelpProvider.scala
mtags/src/main/scala-2/scala/meta/internal/pc/completions/Completions.scala

Fixes https://github.com/scalameta/metals/issues/7453
alternatives makes a case on OverloadedType, which seems to fail sometimes

bugfix: Don't use unsafe alternatives method which can throw

---

metals/src/main/scala/scala/meta/internal/metals/mcp/MetalsMcpServer.scala

fix: MCP test tool runs properly if `verbose` argument is not provided

---

mtags/src/main/scala-2/scala/meta/internal/pc/InferredTypeProvider.scala
tests/cross/src/test/scala/tests/pc/InsertInferredTypeSuite.scala

The name positions were not quite right for backticked identifiers. Switching to existing `namePosition` utilities fixes the issue (confusing encoded name length with decoded name length) and unifies the codepaths.

fix: location of insert-types code action

---

mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
tests/input/src/main/scala/example/TypeMembers.scala
tests/unit/src/test/resources/definition-scala3/example/TypeMembers.scala
tests/unit/src/test/resources/definition/example/TypeMembers.scala
tests/unit/src/test/resources/documentSymbol-scala3/example/TypeMembers.scala
tests/unit/src/test/resources/documentSymbol/example/TypeMembers.scala
tests/unit/src/test/resources/expect/toplevels-scala3.expect
tests/unit/src/test/resources/expect/toplevels.expect
tests/unit/src/test/resources/inlayHints/example/TypeMembers.scala
tests/unit/src/test/resources/inlayHints3/example/TypeMembers.scala
tests/unit/src/test/resources/mtags-scala3/example/TypeMembers.scala
tests/unit/src/test/resources/mtags/example/TypeMembers.scala
tests/unit/src/test/resources/semanticTokens/example/TypeMembers.scala
tests/unit/src/test/resources/semanticTokens3/example/TypeMembers.scala
tests/unit/src/test/resources/semanticdb-scala3/example/TypeMembers.scala
tests/unit/src/test/resources/semanticdb/example/TypeMembers.scala
tests/unit/src/test/resources/toplevel-with-inner-scala3/example/TypeMembers.scala
tests/unit/src/test/resources/toplevel-with-inner/example/TypeMembers.scala
tests/unit/src/test/resources/workspace-symbol/example/TypeMembers.scala
tests/unit/src/test/scala/tests/SaveExpect.scala

When a `type A` member was immediately followed by a closing brace (closing a surrounding scope), the indexer would swallow the closing brace while scanning the member. This would cause the rest of the file to be interpreted as though that closing brace was missing.
Fixes #7475

fix: indexer bug around type members

---

metals/src/main/scala/scala/meta/internal/metals/ReportContext.scala
mtags/src/main/scala-2/scala/meta/internal/metals/EncoderDecoder.scala
mtags/src/main/scala-2/scala/meta/internal/metals/URIEncoderDecoder.scala

For build target `@//:calculator`, previously we would create:
Now we encode any unsafe chars:

fix: encode build target names to include in report file name

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/bsp/BspServers.scala
metals/src/main/scala/scala/meta/internal/builds/BloopInstall.scala
metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
metals/src/main/scala/scala/meta/internal/metals/ConnectionProvider.scala
metals/src/main/scala/scala/meta/internal/metals/IndexProviders.scala
metals/src/main/scala/scala/meta/internal/metals/Messages.scala
metals/src/main/scala/scala/meta/internal/metals/clients/language/ConfiguredLanguageClient.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCliServers.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala
tests/unit/src/main/scala/tests/TestingClient.scala

fixes: https://github.com/scalameta/metals/issues/7509
This PR fixes blocking behaviour of waiting for user request inside of connect. The following fixes and improvements were implemented:
- when possible extracted requests to user from `connect`, or don't wait for their result (only callback)
- when impossible, add timeout and implement a cancel strategy, so a "stronger" connect request can cancel the previous.

fix: blocking user requests in connect

---

mtags/src/main/scala-2.11/scala/meta/internal/pc/Compat.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaCompilerAccess.scala

Alternative solution to https://github.com/scalameta/metals/pull/7541/files
Looks like running close should purge those caches as well, but we didn't run it before.

bugfix: Run close when stopping the presentation compiler

---

metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala
metals/src/main/scala/scala/meta/internal/bsp/BspResolvedResult.scala
tests/slow/src/test/scala/tests/sbt/SbtServerSuite.scala

Previously, even if we selected a server and .bsp entry was missing we would fallback to Bloop. Now, we will try to regenerate bsp config.

bugfix: Don't connect to Bloop even if bsp json file is missing

---

mtags-shared/src/main/scala/scala/meta/internal/metals/Fuzzy.scala
mtags/src/main/scala-2/scala/meta/internal/pc/CompletionProvider.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseInsensitiveSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionIssueSuite.scala
tests/cross/src/test/scala/tests/pc/CompletionOverrideSuite.scala
tests/unit/src/test/scala/tests/FuzzySuite.scala

This pr aims to resolve https://github.com/scalameta/metals-feature-requests/issues/249
I'm adding an updated version of the current fuzzy matching logic, which treats the first character of the query specially. When a query starts with a lowercase character the forgiving rule is selected in the CompletionProvider.
I wanted the new forgiving matcher to have a very similar feel like the current one, ideally have as little change as possible in the expected results for any existing query, while supporting a more forgiving approach to matching described in the issue above.
The logic I came up with was to give special treatment to the first character of the query. The first character also matches upper case characters. There are some exceptions to this. Symbols which themselves are starting …

Update fuzzy matcher logic to allow for slightly more forgiving matching

---

mtags/src/main/scala-2/scala/meta/internal/pc/SignatureHelpProvider.scala

bugfix: Fix signature help issue if .tpe is null

---

metals/src/main/scala/scala/meta/internal/metals/mcp/McpConfig.scala
metals/src/main/scala/scala/meta/internal/metals/mcp/MetalsMcpServer.scala

Fixes https://github.com/scalameta/metals/issues/7627

bugfix: Only recreate mcp entry for cursor

---

metals/src/main/scala/scala/meta/internal/metals/testProvider/frameworks/ScalatestTestFinder.scala
tests/unit/src/test/scala/tests/testProvider/ScalatestFinderSuite.scala

I'm back again with more updates to the Scalatest Finder. This time I am adding support for Feature specs. 
Let me know if you need any changes to this, I've tried to copy the existing pattern.

Improvement: Support for scalatest feature specs

---

metals-docs/src/main/scala/docs/Snapshot.scala

Quoting sonatype:
```
Due to a bug with the underlying service we rely on to provide SNAPSHOT hosting, we've had to temporarily remove browse access for SNAPSHOT releases. This is related to an outage we've experienced in early June 2025. You should still be able to publish and consume SNAPSHOT releases as usual, but you cannot browse them via the UI. Please let us know if you encounter any issues.
```

bugfix: Use the current version when publishing docs

---

mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
tests/cross/src/main/scala/tests/BaseCompletionSuite.scala
tests/cross/src/test/scala/tests/pc/CompilerStaleSymSuite.scala

Normally, symbols are invalidated between runs, but we seem to be always at runId = 1, which means no symbols are invalidated.
To fix that, when updating compilation unit I go over old top level symbols and invalidate if they are stale. I also had to fix the isStale check, which would accept stale Symbol
s such as prefixes of the current symbol.
Fixes https://github.com/scalameta/metals/issues/7587

bugfix: Remove stale top level symbols from current run

---

metals/src/main/scala/scala/meta/internal/metals/mcp/McpTestRunner.scala
metals/src/main/scala/scala/meta/internal/metals/mcp/MetalsMcpServer.scala
tests/unit/src/test/scala/tests/mcp/McpRunTestSuite.scala

I've seen claude do this a few times with sbt where it uses --z to
target a specific test that it knows it testing what i needs, not a
whole suite. I thought it'd be nice for the test tool to also be used
for this. So not not only can you pass in the testFile, but also the
testName in that file.

feat: add in `testName` to the test tool

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/mtags-auto-release.yml
bin/merged_prs.scala
build.sbt
website/blog/2025-08-09-osmium.md

skip-ci
Mainly updating Bloop, which has an issue in the previous release

docs: Add release notes for 1.6.2

---

metals/src/main/scala/scala/meta/internal/metals/MetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
metals/src/main/scala/scala/meta/internal/metals/StacktraceAnalyzer.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceLspService.scala
project/TestGroups.scala
tests/unit/src/main/scala/tests/TestingServer.scala
tests/unit/src/test/scala/tests/ResolveStacktraceLocationLspSuite.scala

Add new LSP command that resolves single stacktrace lines directly to Location objects. Uses existing workspaceFileLocationFromLine logic and filters to workspace files only.
Includes test suite covering various stacktrace formats.
Usage:
```json
{
"command": "resolve-stacktrace-location",
"arguments": ["at com.example.Class.method(File.scala:42)"]
}
```
Returns: Location object with URI and line number, or null if unresolvable.
```json
{
"range": {
"end": {
"character": 0,
"line": 10
},
"start": {
"character": 0,
"line": 10
}
},
"uri": "file:///path/to/Foo.scala"
}
```
I use this in Acme with [`acme-lsp`](https://github.com/cptaffe/acme-lsp/tree/feat/exec) and plumber to open the relevant file at the offending line when right clicking on a stack trace anywhere in the editor. The …

Add `resolve-stacktrace-location` LSP command

---

metals/src/main/resources/db/migration/V7__Toplevel_members.sql
metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
metals/src/main/scala/scala/meta/internal/metals/JarTopLevels.scala
metals/src/main/scala/scala/meta/internal/metals/SqlSharedIndices.scala
metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
mtags/src/main/scala/scala/meta/internal/mtags/GlobalSymbolIndex.scala
mtags/src/main/scala/scala/meta/internal/mtags/Mtags.scala
mtags/src/main/scala/scala/meta/internal/mtags/MtagsIndexer.scala
mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala
mtags/src/main/scala/scala/meta/internal/mtags/ScalaToplevelMtags.scala
mtags/src/main/scala/scala/meta/internal/mtags/SymbolIndexBucket.scala
mtags/src/main/scala/scala/meta/internal/mtags/ToplevelMember.scala
tests/mtest/src/main/scala/tests/DelegatingGlobalSymbolIndex.scala
tests/slow/src/test/scala/tests/feature/CompletionCrossLspSuite.scala
tests/unit/src/test/scala/tests/BaseToplevelSuite.scala
tests/unit/src/test/scala/tests/CompletionLspSuite.scala
tests/unit/src/test/scala/tests/JarTopLevelsSuite.scala
tests/unit/src/test/scala/tests/ScalaToplevelSuite.scala

This should not add too much to memory usage, even with zio library added, there was around 20 toplevel types.
Fixes https://github.com/scalameta/metals-feature-requests/issues/378
Update: I changed it a bit to mean toplevel members, so that we can include toplevel extension methods etc.

improvement: Index toplevel members from dependencies

---

metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala

We can no longer publish the old pattern that was used by versions of plugins published pre 1.9.0.
This should be msotly fine, no real changes in the plugin since that version.

bugfix: Set Bloop plugin version to 2.0.10 for pre 1.9.0

---

metals/src/main/scala/scala/meta/internal/metals/Directories.scala
metals/src/main/scala/scala/meta/internal/metals/ProjectMetalsLspService.scala
metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala
metals/src/main/scala/scala/meta/internal/metals/mcp/MetalsMcpServer.scala
metals/src/main/scala/scala/meta/internal/metals/mcp/ScalafixLlmRuleProvider.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCliServers.scala
tests/unit/src/main/scala/tests/mcp/McpTestClient.scala
tests/unit/src/test/scala/tests/mcp/McpServerLspSuite.scala

The intention is to do large scal refactorings even in larger codebase without the need to create a large context.

feature: Add MCP tool to generate and run scalafix rules

---

metals/src/main/scala/scala/meta/internal/metals/mcp/MetalsMcpServer.scala
tests/unit/src/main/scala/tests/mcp/McpTestClient.scala
tests/unit/src/test/scala/tests/mcp/McpServerLspSuite.scala

Support both JSON array and JSON string formats for symbolType parameter
Add InvalidSymbolTypeException for better error messages
Fixes https://github.com/scalameta/metals/issues/7735

Fix typed-glob-search to handle JSON string symbolType parameter with fallback

---

metals/src/main/scala/scala/meta/internal/parsing/Trees.scala
tests/unit/src/test/scala/tests/Scala3LspSuite.scala

Previously, if experimental import was included it would be ignored by metals. Now, we turn on the future dialect in that case.

bugfix: Support experimental imports

---

metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
tests/unit/src/test/scala/tests/WorkspaceSymbolLspSuite.scala

This PR updates the workspace symbol search logic in `WorkspaceSymbolProvider` to correctly include extension methods defined in the project.
- Extension methods from `inWorkspaceMethods` are now iterated and matched alongside regular symbols during workspace symbol search.
- "Search symbol in workspace" now finds extension methods.

fix: change workspace symbol search to include extension methods

---

build.sbt
metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
tests/unit/src/test/scala/tests/DefinitionLspSuite.scala

Previously, external libraries were collected, but not used during indexing. This change should enable `go to definition` operations on external libraries.

fix: Add correct indexing of external libraries

---

mtags/src/main/scala-2.11/scala/meta/internal/pc/Compat.scala
mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
mtags/src/main/scala-2/scala/meta/internal/pc/ScalaCompilerAccess.scala

#7543
This reverts commit f9a067e5c75a5d051d38e947fd9c9ad826f5712f.
Turns out it wasn't helping and started to cause https://github.com/scalameta/metals/issues/7806
Fixes https://github.com/scalameta/metals/issues/7806

Revert "bugfix: Run close when stopping the presentation compiler"

---

project/V.scala

sbt 2.0.0-RC5 broke bincompat, so please update to 2.0.0-RC6.
See https://github.com/sbt/sbt/releases/tag/v2.0.0-RC6

deps: Update to sbt 2.0.0-RC6

---

mtags-interfaces/src/main/java/scala/meta/pc/RawPresentationCompiler.java

`RawPresentationCompiler` is a direct, unsafe way to access presentation compiler interface.
It is up to the consumer to guarantee thread safety and sequential request processing.
The main story behind the need for such interface is that some servers may use custom runtime which will simplify presentation compiler usage and make it more performant. Currently there is no real way to specify the Thread that will be used to compute this, and on top of that we're creating a custom single threaded executor for each presentation compiler (each module has its own instance, so you can have even 20 or 30 of them).
The proposed implementation will be submitted in another PR directly in Scala 3 repository. At the moment of writing it is:
<details>
<summary>Implementation proposal</summary>
```scala …
```

Add RawPresentationCompiler interface
